### ISSUE TITLE
In this environment, the sources for assign MUST be an object 

### ISSUE THREAD

**Issue by avin3sh** [react-native-elements/react-native-elements#1149]
On `"react-native": "0.55.3"` and `"react-native-elements": "^0.19.1"`  using `iconRight` prop with `Button` gives "In this environment, the sources for assign MUST be an object " error.

The code from Components docs itself can be used to reproduce the error,
`<Button
  icon={
    <Icon
      name='arrow-right'
      size={15}
      color='white'
    />
  }
  iconRight
  title='BUTTON WITH RIGHT ICON'
/>`

**Comment by avin3sh** [comment]
Hey, you are right. Silly mistake at my side. I don't know when the Component doc version reverted to 1.0.0-beta4.

**Comment by xavier-villelegier** [comment]
@avin3sh Note that in the future you’ll be able to pass an object as before, it’s still a beta. We will standardize this behavior everywhere for the v1, so you’ll be able to use both objects and components
