### ISSUE TITLE
Switch within ListItem not working in 1.0.0-beta5

### ISSUE THREAD

**Issue by epshtielsl** [react-native-elements/react-native-elements#1264]
**Explain what you did**
Attempted to add a switch element to ListItem using the switch property.

**Expected behaviour**
A working Switch element.

**Describe the bug**
Switch value never changes and onValueChange is never called.  Switch immediately returns to off.  Note: the below switch, when copy/pasted, works fine on its own.

**To Reproduce**
<ListItem
  title='Enable Inventory'
  switch={
    <Switch
      value={this.state.isOn}
      onValueChange={(value) => this.setState({ isOn: value })}
    />
  }
  containerStyle={styles.listItem}
  titleStyle={styles.listTitleText}
  subtitleStyle={styles.listSubtitleText}
/>

**Your Environment (please complete the following information):**
  "dependencies": {
    "axios": "^0.18.0",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-elements": "^1.0.0-beta5",
    "react-native-linear-gradient": "^2.4.0",
    "react-native-vector-icons": "^4.6.0",
    "react-native-xml2js": "^1.0.3",
    "react-navigation": "^2.2.5",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0"
  }

**Comment by chrisid** [comment]
Although this is closed, <ListItem switch={}../> doesn't work for me, only <ListItem switchButton /> but with that, I can't find a way to add style to the switch.

**Comment by iRoachie** [comment]
The switch doesn’t have a style prop https://facebook.github.io/react-native/docs/switch#props
