### ISSUE TITLE
Bottom Sheet component

### ISSUE THREAD

**Issue by iRoachie** [react-native-elements/react-native-elements#1266]
Think it would be really cool if we could have a component like this. 

<img src="https://user-images.githubusercontent.com/5962998/41509798-511a12cc-7227-11e8-8612-cb573e73fcc0.gif" width="400" />

### Specs
Props could be:
- list of items with their icon
- title
- visible
- onRequestClose
- onSelect

**Comment by saxenanihal95** [comment]
I have created this : 
![Screen-Recording-2020-04-21-at-11 22 27-PM](https://user-images.githubusercontent.com/17348595/79897531-8220cc80-8427-11ea-8f57-b1dc2649690a.gif)

**Comment by flyingcircle** [comment]
@saxenanihal95 I don't think anyone else has started on it. It would be good for it to have default styling that more or less matches the other components as well as the ability to inject a custom component. It'll be easiest to discuss with an API doc as well. When you feel like you have something a bit more solid, open a PR and we can discuss tweaks from there.
