### ISSUE TITLE
FontAwesome v5?

### ISSUE THREAD

**Issue by donni106** [react-native-elements/react-native-elements#1338]
I cannot find anything concerning FontAwesome v5. Is there a way to use it?
With `{ type: 'font-awesome-5', name: 'chevron-right' };` there is a fallback to Material Icons.

**Comment by iRoachie** [comment]
Yea we still need to add it to the `getIconType` helper https://github.com/react-native-training/react-native-elements/blob/470dde7d7a9ddfd11483f5d3a06d3871a4faa6ca/src/helpers/getIconType.js#L31

**Comment by Kepro** [comment]
bower is deprecated omg... "...psst! While Bower is maintained, we recommend using Yarn and Webpack or Parcel for front-end projects read how to migrate!"

**Comment by iRoachie** [comment]
Closing this for now. FontAwesome5’s setup is too complicated to add in easily to our getIconType helper.

At the moment all the components that use icons allow passing a component as value. I recommend you use this method if you want to use FontAwesome5.

```jsx
import { Button } from ‘react-native-elements’
import FontAwesome5 from 'react-native-vector-icons/FontAwesome5';

…
<Button icon={{ name: ‘comments’ }} />
<Button icon={
  <FontAwesome5 name=“comments” />
} />
…

**Comment by ddman** [comment]
My solution.

`
import React from 'react';
import { Icon } from 'react-native-elements';
import FontAwesome5 from 'react-native-vector-icons/FontAwesome5';

export default props => {
  if (props.type === 'font-awesome5') {
    return <FontAwesome5 {...props} />;
  }
  return <Icon {...props} />;
};
`

**Comment by iRoachie** [comment]
Added proper support for this in the next release.

**Comment by ethanyuwang** [comment]
@iRoachie i dont see this change https://github.com/react-native-elements/react-native-elements/pull/2142 in the latest release. how do i have my package.json to point to this merged pull request? and will there be a new release with this change soon?

**Comment by vhesener** [comment]
This is mines

```ts
import { registerCustomIconType } from 'react-native-elements';
import FontAwesome5 from 'react-native-vector-icons/FontAwesome5';
registerCustomIconType('font-awesome-5', FontAwesome5);
```

Usage

```ts
import { Icon } from 'react-native-elements';
MyCheckbox = <Icon type='font-awesome-5' name='check-square' />;
```

**Comment by plaporte** [comment]
> This is mines
> 
> ```ts
> import { registerCustomIconType } from 'react-native-elements';
> import FontAwesome5 from 'react-native-vector-icons/FontAwesome5';
> registerCustomIconType('font-awesome-5', FontAwesome5);
> ```
> 
> Usage
> 
> ```ts
> import { Icon } from 'react-native-elements';
> MyCheckbox = <Icon type='font-awesome-5' name='check-square' />;
> ```

Elegant and simple. Thanks so much for saving me a headache.
