### ISSUE TITLE
Vector icon support for Slider thumbImage

### ISSUE THREAD

**Issue by devth** [react-native-elements/react-native-elements#1394]
**Is your feature request related to a problem? Please Describe.**

I'm not sure if `react-native-elements` version of `Slider` supports `thumbImage` (I don't see it in source), but I noticed it was forked from https://github.com/jeanregisser/react-native-slider which had `thumbImage` support two years ago. However, the original `react-native-slider` appears to be no longer maintained.

Assuming we could get `thumbImage` support `react-native-element`'s fork, I'd like to propose adding support for Expo's vector icons as well, since react-native `Image` only supports a limited number of non-vector image formats.

**Describe the solution you'd like**
Vector icon support for the thumb in `Slider`.

**Describe alternatives you've considered**
Considered requesting in `react-native-slider` but the author is non-responsive.

**Additional context**
`react-native-elements` is awesome!

**Comment by devth** [comment]
@iRoachie hey what do you think about this? I might be able to submit a patch if you're open to it.

**Comment by iRoachie** [comment]
It seems like a good idea. If you're up for it, feel free to propose a PR on how to do this.

**Comment by Biplovkumar** [comment]
Is it possible in future or not ?

**Comment by azilberbaum** [comment]
This would be great, I also would love to be able to use the thumbImage

**Comment by mikehardy** [comment]
Hi there, I notice this is somewhat dormant but is "philosophically accepted" (as in, if there were a solid PR for this or something like this) it might be accepted? I have a need for this in my app and would be willing to PR for at least an image feature if that is still the case. So: @iRoachie - still open to a PR to add image support to thumb on slider?

Cheers!

**Comment by iRoachie** [comment]
Yea exactly. I thought the OP actually had an implementation for it, but that wasn't the case. I'll be glad to review a PR that implements it

**Comment by mikehardy** [comment]
With apologies, my app ended up using a different UI and no longer needed the thumb to have an image. I don't want offer a PR for code I won't use (and thus won't maintain). But for anyone doing this in the future it really should just be to mod the slider component to take and render children, possibly with a type check that it is an image. Haven't tried it obviously but that was going to be my rough attempt
