### ISSUE TITLE
Card style not matching documentation

### ISSUE THREAD

**Issue by crammag** [react-native-elements/react-native-elements#1432]
**Explain what you did**
Adding a title to a Card and expecting to render as the documentation.

**Expected behaviour**
The title is completely different on the documentation (even the last betas), and I think that the old one was prettier.

**Describe the bug**
Missmatch between documentation and styles of Card.

**To Reproduce**
Just create a card like the one on the Documentation and you will notice the difference.

**Possible Solution**
Go back to the previous styles or add an option to choose the position of the title.

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | | 0.19.1
| react-native | | expo version
| npm or yarn | | 6.3.0

**Comment by crammag** [comment]
Versions, as I did something wrong while editing it and it's not showing:
 - react-native-elements: 0.19.1
 - react-native: expo version.
 - npm or yarn: npm 6.3.0

**Comment by iRoachie** [comment]
Correct, i've just checked through all the releases from about v0.5 and I can't find anything which would make the card look like that. The title was always rendered above the image.

**Comment by iRoachie** [comment]
We could either update the image in the docs, or implement some type of prop that would allow the Card to render like the image above
