### ISSUE TITLE
Recreate Example App on Snack

### ISSUE THREAD

**Issue by iRoachie** [react-native-elements/react-native-elements#1452]
Since Expo no longer allows you to run apps on ios remotely,  we should remake the example app in a snack, so that anyone can see it and play with it.

We could link to that on the Getting Started page.

**Comment by Monte9** [comment]
This is a good idea. Does that mean that the repo RNE-app repo is not worth investing time/effort into?

https://github.com/react-native-training/react-native-elements-app

It does have 700 stars, so that's worth something I guess.

**Comment by iRoachie** [comment]
Not sure as yet. I do know that only those with android will probably get to play with it, without downloading and running it on their computer.

I also don't see it working for iOS again because of Apple restrictions. However i guess it's good for example

**Comment by iRoachie** [comment]
May have to do this after we release, along with the `expo-font` warning on snack, there's others as well.
