### ISSUE TITLE
action onClear on SearchBar-Default not fired

### ISSUE THREAD

**Issue by ttkien** [react-native-elements/react-native-elements#1455]
I am using react-native-elements@1.0.0-beta5
What you were trying to accomplish.
I used the Searchbar with the flowing code, but onClear not fired with platform is "default"

```javascript
 public onChangeText = (text: string) => {
        this.props.searchLocation(text);
    }

    public onCancel = () => {
        this.onChangeText("");
    }

    public render() {
        return (
            <SafeAreaView>
                <SearchBar
                    onChangeText={this.onChangeText}
                    onCancel={this.onCancel}
                    onClear={this.onCancel}
                    placeholder="Enter location"
                ></SearchBar>
                <SearchLocationList
                    items={this.props.items}
                />
            </SafeAreaView>
        );
    }
```

#Expected behaviour
onClear function  should be fired

#Describe the bug

# Possible Solution
I check the source code at file https://github.com/react-native-training/react-native-elements/blob/master/src/searchbar/SearchBar-default.js. It seems forgot passing the "clear" action into defaultClearIcon

**Comment by xavier-villelegier** [comment]
Hey @ttkien 👋 This has been fixed in the `v1.0.0-beta6` release ! Could you please install it and tell us if it works ?

**Comment by pal-pinter** [comment]
Hi,

doesn't works yet.

**Comment by xavier-villelegier** [comment]
@pal-pinter @ttkien Something went wrong in the beta6 release so we released beta7 right after that, could be please tell us if it works ? Be sure to have `1.0.0-beta7` in your package.json and to clean install all your modules and remove any `package-lock.json` or `yarn.lock`.
```
rm -rf node_modules package-lock.json yarn.lock && yarn
```

**Comment by TobalOW** [comment]
i was having the same issue with the 1.0.0-beta5 but i upgrade to 1.0.0-beta7 and now works fine.

**Comment by xavier-villelegier** [comment]
Closing this as it is fixed in beta7
