### ISSUE TITLE
Would love to see a Two-Marker Slider for Setting a Range

### ISSUE THREAD

**Issue by quadsurf** [react-native-elements/react-native-elements#15]

**Comment by dabit3** [comment]
@quadsurf This sounds like a good idea. Can you shoot over a link to an example of what you had in mind, maybe implemented somewhere else? Thanks

**Comment by TheGermanGuy** [comment]
I think he is referring to a bidirectional related slider. 
Similar to the one on Tinder or something like the one shown in the link(http://www.tutorialspark.com/jqueryUI/jQuery_UI_Slider_Bidirectional_Related_Slider.php)
I would love to have this too.

**Comment by Monte9** [comment]
@quadsurf Here are some sliders that I found.
1. https://github.com/jeanregisser/react-native-slider - I like that it's customizable & API looks pretty robust. 
1. https://github.com/JackDanielsAndCode/react-native-multi-slider - Has implementation of multi-selection slider
1. https://github.com/franfran/react-native-snap-slider - Love the functionality that this provides

I think adding a **custom slider API** (like 1) + **multi-selection** (like 2) + **snap functionality** (like 3) would be good addition to the elements. 

@dabit3 thoughts?

**Comment by dabit3** [comment]
@Monte9 I like the idea of having the customizable api of 1 and the multi selection of 2, and the snap functionality looks cool as well. 

1. We can possibly add one of those existing projects as a dependency to get the component working out of the box.

2. or maybe you can even fork [#1](https://github.com/jeanregisser/react-native-slider) and implement the two slider feature into a pr or something and we can still add as a dependency

3. or maybe we can copy the existing component and add out tweaks as a new component to RN Elements?

I'm cool with any of these ideas, or anything along those lines really.

**Comment by Monte9** [comment]
Update: Slider has been added to the latest release of RNE. Check out the documentation [here](https://github.com/react-native-community/react-native-elements#slider-component).

We went with Option 1. I'll leave this issue open as it would be cool to add on Option 2 & Option 3 to the existing Slider component.

If anyone has bandwidth and would like to submit a PR to enhance it, I am open to merging it.

**Comment by Monte9** [comment]
In an effort to streamline all RNE issues such that it is easier to get to solutions faster/ submit a new issue we have decided to close any enhancement/roadmap features as "issues". 

Feel free to use this issue to talk about this feature and ping @binoy14 or me (@monte9) if you feel like you can submit a PR for this. Thanks in advance.

Also you can track the status of this feature and all other roadmap features [here](https://github.com/react-native-community/react-native-elements/issues/195#issuecomment-286213704).

**Comment by deadcoder0904** [comment]
Would love to see 2 sliders as well :)

I see this is a fork of https://github.com/jeanregisser/react-native-slider/pull/142 so this PR does just that.

What do ya'll think?

**Comment by mt81** [comment]
@flyingcircle I am interested in developing this,

**Comment by flyingcircle** [comment]
@mt81 go for it.

**Comment by HariAcidReign** [comment]
@flyingcircle Apologies for the duplicate ticket, but the idea is still worth implementing right? I've read all the closed PRs and issues on this thread, and I think I can work on implementing the Slider ideas 2 and 3. Is it alright if I start working on adding them to the library and then to the app?

**Comment by mhimanshu712** [comment]
I would like to work on it as well. @flyingcircle

**Comment by hetanthakkar1** [comment]
Working on this

**Comment by HariAcidReign** [comment]
Hey, I have already started working on this one. I'm actually planning to add it to RNEU after approval. Do check out other issues.

**Comment by hetanthakkar1** [comment]
@HariAcidReign What is your approach!? I also started as I thought its been 5 days so I thought you started doing some other issues!?

**Comment by HariAcidReign** [comment]
I had described it in the above issue in RNEU. They haven't given the go-ahead yet, but I had started to implement it anyway. So hopefully by this weekend, I should be done with half of my proposed issues. And the rest will be done (implementation+tests) by next weekend. 👍🏻

**Comment by hetanthakkar1** [comment]
@HariAcidReign if you have started it np! If you can tell me the props and few other details I can start making tests for the same! Are you also writing tests along with the component! because its will probably need tests !

**Comment by hetanthakkar1** [comment]
@HariAcidReign Sure no problem go ahed. Goodluck!

**Comment by hetanthakkar1** [comment]
@HariAcidReign This component will probably need writing tests! If you are not writing tests I can do that if you can let me know few implementation details!? Or you have also started writing tests!?

**Comment by HariAcidReign** [comment]
Haven't started testing yet. If I get any hiccups, I'll let you know for sure 🎉

**Comment by arpitBhalla** [comment]
Closing this in favor of [this discussion](https://github.com/react-native-elements/react-native-elements/discussions/3393)
