### ISSUE TITLE
Add theme fonts to components

### ISSUE THREAD

**Issue by iRoachie** [react-native-elements/react-native-elements#1542]
Right now it isn’t very easy to change the fonts for all the text throughout our components. 

Since we have the theme provider this should be pretty easy to do!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by anhtuank7c** [comment]
I would love to sync fonts to all `react-native-elements` component, can be change `withTheme` object.

ie:

```
import { StyleSheet } from 'react-native'

export default {
  primary: '#2089dc',
  secondary: '#8F0CE8',
  grey0: '#393e42',
  grey1: '#43484d',
  grey2: '#5e6977',
  grey3: '#86939e',
  grey4: '#bdc6cf',
  grey5: '#e1e8ee',
  greyOutline: '#bbb',
  searchBg: '#303337',
  success: '#52c41a',
  error: '#ff190c',
  warning: '#faad14',
  disabled: 'hsl(208, 8%, 90%)',
  // Darker color if hairlineWidth is not thin enough
  divider: StyleSheet.hairlineWidth < 1 ? '#bcbbc1' : 'rgba(0, 0, 0, 0.12)',
  platform: {
    ios: {
      primary: '#007aff',
      secondary: '#5856d6',
      success: '#4cd964',
      error: '#ff3b30',
      warning: '#ffcc00'
    },
    android: {
      primary: '#2196f3',
      secondary: '#9C27B0',
      success: '#4caf50',
      error: '#f44336',
      warning: '#ffeb3b'
    }
  },
  //Components
  Text: {
    style: {
      fontFamily: 'Roboto-Regular',
      color: '#fff',
      fontWeight: 'bold',
      fontSize: 16,
    },
    // h1
    h1: {
      fontSize: 27
    },
    // h2
    h2: {
      fontSize: 24
    },
    ...
  },
  Button: {
    props,
    // style
    style: {
      ...
    }
  }
}

```

**Comment by bdombro** [comment]
FYI I think it somewhat does this already, just not all style attribs are supported. For example, the following will make ALL Text elements italic by default, including h1,h2,h3 and h4.

```
Text: {
    style: {
      fontStyle: "italic"
    }
  }
```

**Comment by iRoachie** [comment]
All components don't use the `Text` component.

**Comment by xstable** [comment]
That doesn't work for me. ("react-native-elements": "^2.0.0",)
I'm not able to change any of the Text-Attributes via my theme.

**Here an example:** 

```
export const theme = {
  Text: {
    style: {
      fontStyle: "italic",
    },
    h1: {
      fontSize:15,
    }
  },
  Button: {
    raised: false,
    buttonStyle: {
      margin: 5,
      borderTopColor: color['primary-color-1'],
      borderTopWidth: 2,
      backgroundColor: color['main-color-dark'],
    },
    titleStyle: {color: color['font-light']},
  },
};
```
While `Button` works as expected, none of the Text-Styles work!

```
import {Button, Text, Image} from 'react-native-elements';
<Text h1 >Welcome</Text>
```
Any Idea why?

**Comment by xstable** [comment]
Figured out the following: 

If you use: 
```
  Text: {
    h1Style: {
      fontSize: 20,
      color: 'blue',
    },
  },
```
AND fully restart your Metro-Bundler, the Layout change like expected. 
Seems that hot-reloading / fast-refresh and (sometimes) manually reloading doesn't refresh the theme like expected.

**Comment by flyingcircle** [comment]
As stated, this is more or less already possible with current theming.

**Comment by cglacet** [comment]
@xstable Did you found a way to change button texts using `ThemeProvider`?
