### ISSUE TITLE
[ThemeProvider] Dark/Light Theme

### ISSUE THREAD

**Issue by piu130** [react-native-elements/react-native-elements#1626]
**Is your feature request related to a problem? Please Describe.**
Now that we have the `ThemeProvider` we should consider to support three predefined themes. The current theme, a light theme and a dark theme.

**Describe the solution you'd like**
We should add the two themes to `colors.js` and export them as `theme.dark`, `theme.light` and `theme.standard`.

`console.log(theme.dark)` would print `{ colors: { primary: '#...', ... } }`.

A user can then:

```jsx
import { ThemeProvider, theme } from 'react-native-elements'
...
<ThemeProvider theme={theme.dark}>...</ThemeProvider>
```

What do you think? Whats about the naming?

**Comment by iRoachie** [comment]
That's a good idea! And also the next step. We had planned to do this from the beginning so it's very much welcomed.

**Comment by iRoachie** [comment]
That's actually a pretty cool idea. How would that affect usage? I know a lot of persons use react-native-elements directly from github (using github repo link in package.json)

**Comment by piu130** [comment]
This seems a bit complicated. I found [this](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/) blogpost about `lerna` and yarns `workspaces`.

Maybe its better to create a `react-native-elements-theme(s)` repo? Or maybe workspaces would be a good preparation for future development?
