### ISSUE TITLE
Icons: allow styling the Touch container, like it was possible before

### ISSUE THREAD

**Issue by tiagoalves** [react-native-elements/react-native-elements#1637]
Previously (current stable version), when using the `<Icon />` component with `onPress`, the container was the `TouchableHighlight` component itself. Thus, we could easily style it with the `containerStyle` prop. ([code](https://github.com/react-native-training/react-native-elements/blob/stable/src/icons/Icon.js#L44))

Now (v1.0.0-beta7) there's an explicit `View` container and the child `TouchableHighlight` is not user-styleable, as far as I can see. ([code](https://github.com/react-native-training/react-native-elements/blob/master/src/icons/Icon.js#L36))

This prevents us from, for instance, adding padding to the touchable element and thus making smallish icons easier to tap.

There are alternatives such as adding a wrapping `TouchableHighlight` myself or padding the `iconStyle` but one kinda defeats the purpose of using RNE's `Icon` and the other implies we center the icon's internal text which apparently works differently in Android and iOS.

Can we add some additional styling property that is then applied to the `TouchableHighlight` component?
Alternatively, do you have an example of how I can easily pad the touchable part of an `Icon` that works cross-platform?

Btw, the `reverse` and `raised` props don't apply to my example as I want the icon to be flat.

**Comment by tiagoalves** [comment]
Sure, have a look here: https://snack.expo.io/@tiagoalves/rne-icon-touch-padding

I had to run the snack locally for some reason.

The original snack uses RNE v1.0.0-beta7 and the following picture shows the icon with a green border and its container with a red border. Even though the container has a 44px size, the touchable part of the icon is smaller (the blue background is the touch underlay).

<img width="93" alt="screen shot 2018-12-05 at 09 50 23" src="https://user-images.githubusercontent.com/215495/49505642-1bbbfe00-f874-11e8-910a-46f2728c77c9.png">

If we change the `react-native-elements` version to `0.19.1`, the icon now looks like the following image where you can see that the blue touch underlay is now the full 44px of the container. This makes tapping the icon much easier.

<img width="79" alt="screen shot 2018-12-05 at 09 50 35" src="https://user-images.githubusercontent.com/215495/49505653-2080b200-f874-11e8-8021-55806ee6ec12.png">

Again, I know that I can size the icon itself with the `iconStyle` prop but that requires centring text with `textAlign: "center", textAlignVertical: "center"` and that is Android-only as far as I know (and it also seems unexpected to me to have to center text instead of using flexbox props).

**Comment by tiagoalves** [comment]
Thanks for reviewing this, @iRoachie. You're right that the inner padding achieves the desired result, in this particular example.

However, I think that it's not a generic solution. If I change the icon size, I have to adapt the padding value manually and if the size is large enough (larger than 44 or 48), I might want to remove padding altogether.

The effect I need is a "tappable icon" which should have a min width of 44 or 48 according to the iOS and Android design guidelines, respectively. The `minWidth` style prop solves this easily.

I think the solution would be to simply remove the wrapping `View` and move the `containerStyle` prop to the inner `Component`, [here](https://github.com/react-native-training/react-native-elements/blob/master/src/icons/Icon.js#L36).

Anyway, if you guys don't feel this is a common issue, feel free to close it.

If someone else has the same issue, I'm using a wrapper similar to this, for now:

```
const TappableIcon = ({ onPress, underlayColor, containerStyle, ...props }) => {
  const Wrapper = onPress ? TouchableHighlight : View;
  return (
    <Wrapper
      onPress={onPress}
      underlayColor={underlayColor}
      style={[{ minWidth: 44, minHeight: 44 }, containerStyle]}
    >
      <Icon {...props} />
    </Wrapper>
  );
};
```

**Comment by iRoachie** [comment]
> However, I think that it's not a generic solution. If I change the icon size, I have to adapt the padding value manually and if the size is large enough (larger than 44 or 48), I might want to remove padding altogether.
>
> The effect I need is a "tappable icon" which should have a min width of 44 or 48 according to the iOS and Android design guidelines, respectively. The minWidth style prop solves this easily.

If you change the iconSize In the case where you use a minWidth and minHeight, then you'll get clipping of the icon anyway.

> I think the solution would be to simply remove the wrapping View and move the containerStyle prop to the inner Component, here.
You're only thinking of one platform here. What happens if persons want to use TouchableNativeFeedback on android through the `Component` prop? TouchableNativeFeedback doesn't behave like a View compared to the others, which means you can't apply styles directly to it.

What I think we can do though, is add an additional View inside the `Component`, which in your case would be able to handle the minHeight, minWidth suggestion you wanted to add. What do you think about this approach?

**Comment by tiagoalves** [comment]
> What I think we can do though, is add an additional View inside the `Component`, which in your case would be able to handle the minHeight, minWidth suggestion you wanted to add. What do you think about this approach?

Sounds good to me!
