### ISSUE TITLE
how to align icon on the left inro social button

### ISSUE THREAD

**Issue by maxime-aubry** [react-native-elements/react-native-elements#1689]
Hello

I would Like align icon, and text, into social button.
I can't do this.
Could you help me please ?

I used align-content and other properties, nothing worked.

Thanks.

**Comment by iRoachie** [comment]
![image](https://user-images.githubusercontent.com/5962998/50386094-d5113500-06b6-11e9-9018-54cc3c964fe9.jpeg)

This is what you mean?

**Comment by fernandocruz** [comment]
Check the style of View where the Social Button is inside. Can be the alignItems: center. Remove this to test. ;)
