### ISSUE TITLE
Tooltip coordinate system

### ISSUE THREAD

**Issue by cidevant** [react-native-elements/react-native-elements#1710]
**Explain what you did**
I am trying to show tooltips inside ScrollView(horizontal)

**Expected behaviour**
I expect to see tooltip in visible area

**Describe the bug**
If element has width 1000 (for example) - tooltip is rendered over center of the element (~500px) and nobody can see it. Tooltip coordinate system should reflect visible area and render tooltip over visible area of element.

**To Reproduce**
Horizontal ScrollView with elements wider than visible area.

**Possible Solution**
Rewrite coordinate system and render methods:
https://github.com/react-native-training/react-native-elements/blob/master/src/tooltip/getTooltipCoordinate.js
https://github.com/react-native-training/react-native-elements/blob/master/src/tooltip/Tooltip.js

**Screenshots**
![capture](https://danielprsala.cz/xxx.png)

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | ^1.0.0-beta7 |
| react-native | 0.57.3 |
| npm or yarn | yarn 1.12.3 |

**Comment by Monte9** [comment]
Off topic: that Tab Bar looks 😍 Can you share what package you used or how you did it?

**Comment by cidevant** [comment]
@Monte9 It is `react-navigation` + `react-navigation-tabs`. Using `createBottomTabNavigator` with this config `tabBarComponent: MyCustomBottomTabBar`. Component `MyCustomBottomTabBar` wraps native component `import { BottomTabBar } from 'react-navigation-tabs';`. Write me a mail, if you want source code.

**Comment by cidevant** [comment]
I solved it by properly calculating visible area of wrapped element.
```javascript
export const getElementVisibleWidth = (elementWidth, xOffset, ScreenWidth) => {
  // Element is fully visible OR scrolled right
  if (xOffset >= 0) {
    return (xOffset + elementWidth) <= ScreenWidth // is element fully visible?
      ? elementWidth // element is fully visible;
      : (ScreenWidth - xOffset) // calculate visible width of scrolled element
  } 
  // Element is scrolled LEFT
  else {
    return elementWidth - xOffset; // calculate visible width of scrolled element
  }
};
```
And then it should be used here:
```javascript
//react-native-elements/src/tooltip/getTooltipCoordinate.js

const center = [x + getElementVisibleWidth(width, x, ScreenWidth) / 2, y + height / 2];
```
and here (`elementVisibleWidth`)
```javascript
//react-native-elements/src/tooltip/Tooltip.js

import getTooltipCoordinate, { getElementVisibleWidth } from './getTooltipCoordinate';

class Tooltip extends React.PureComponent {
  // ...
  renderPointer = (tooltipY) => {
    const { backgroundColor, pointerColor } = this.props;
    const { yOffset, xOffset, elementHeight, elementWidth } = this.state;
    const pastMiddleLine = yOffset > tooltipY;
    const elementVisibleWidth = getElementVisibleWidth(elementWidth, xOffset, ScreenWidth);

    return (
      <View
        style={{
          position: 'absolute',
          top: pastMiddleLine ? yOffset - 13 : yOffset + elementHeight - 2,
          left: xOffset + elementVisibleWidth / 2 - 7.5,
        }}
      >
        <Triangle
          style={{ borderBottomColor: pointerColor || backgroundColor }}
          isDown={pastMiddleLine}
        />
      </View>
    );
  };
  // ...
}
```

**Comment by cidevant** [comment]
I will submit PR soon

**Comment by Monte9** [comment]
Awesome! Thanks for the detailed explanation about the tabs. I will look into it and will have to try it out. Looks really cool. 

Also thanks for submitting the PR! If it fixes it for you, I am sure others will find it useful as well. 🙌  Let's get it merged in and released as part of v1.
