### ISSUE TITLE
Button large prop removed and "may be re-added"?

### ISSUE THREAD

**Issue by antgel** [react-native-elements/react-native-elements#1770]
Firstly, thanks for an awesome toolkit.

The [Button section of the upgrade blog post](https://react-native-training.github.io/react-native-elements/blog/2019/01/27/1.0-release.html#button) says:

> Removed large prop. May re-add in future.

I'm relatively new to this ecosystem, what was the rationale and is there a workaround? I searched PRs and Issues but "large" and "prop" aren't great search words.

**Comment by iRoachie** [comment]
It wasn't intentionally removed. What happened is that between v0.19.1 and v1.0.0, the button had an entire refactor https://github.com/react-native-training/react-native-elements/pull/492. Some props may have been removed in an attempt to make to transition faster.

**Comment by antgel** [comment]
@iRoachie Thanks for the insight. With all due respect, even reading the PR, it has no discussion about that, and it's just gone kaboom with no deprecation warning (that I'm aware of). I guess in practice most people have been using the 1.x beta for a long time, and / or style the buttons with CSS. I just came along a month ago, so I wasn't aware of the history.

**Comment by iRoachie** [comment]
Sorry about that, I know how it feels to be in that position. We tried in the release notes in the v1 blog post to outline all breaking changes. However, v1 has been iterated on for about 9 months through 6 betas. 

Having button sizes seems like a good idea and it's something that's common in other libraries.

**Comment by antgel** [comment]
@flyingcircle Closing with no explanation?

**Comment by flyingcircle** [comment]
I was just going through closing stale tickets. I can reopen this if you'd like or are still interested in it.
