### ISSUE TITLE
Providing marginTop to Input via ThemeProvider applies to SearchBar elements and cannot be overridden.

### ISSUE THREAD

**Issue by Slapbox** [react-native-elements/react-native-elements#1790]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
Defining the following in my React Native Elements theme works properly, except that this affects SearchBar elements and cannot be overridden when the SearchBar uses `platform="Android"`

```js
  Input: {
    containerStyle: {
      marginTop: 16,
    },
  },
```

I've tried all methods of styling my SearchBar, but it always receives `marginTop: 16`

**Expected behaviour**
Theme `Inputs` with `containerStyle: { marginTop: 16 }` and then override that on a `SearchBar`.

**Describe the bug**
`SearchBar` `inputContainer`'s `marginTop` cannot be overridden when that value is provided via the `ThemeProvider`

**To Reproduce**
We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

----

### To reproduce:
1. Add the following to your theme:
```js
  Input: {
    containerStyle: {
      marginTop: 16,
    },
  },
```
2. Attempt to modify the `marginTop` on a `SearchBar` with `platform="Android"`

----

**Possible Solution**
Unknown

**Screenshots**

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  1.0.0  |
| react-native          | 0.57.1 (Via Expo) |
| npm or yarn           | Yarn@1.13.0 |

**Comment by Slapbox** [comment]
Anyone have any insight into this? It's really making my life difficult right now. Theming goes from a breeze to a nightmare since this cannot be overridden in any way. As a result I have to forego using themes on all inputs, which is incredibly tedious to maintain.

**Comment by iRoachie** [comment]
Hey @Slapbox just tested your problem and indeed it is a bug. Usually components that use other components (SearchBar using Input) usually have a prop that allows you to override, in this case SearchBar does not have one as the `containerStyle` is static https://github.com/react-native-training/react-native-elements/blob/master/src/searchbar/SearchBar-android.js#L106.

I don't have an easy way to solve this currently. For now, I'd suggest instead of theming the margin of the Input through ThemeProvider that you create a new Input using composition and then use that in your app in all the places where you need an Input with margin. Here's a demo from the docs https://react-native-training.github.io/react-native-elements/docs/customization.html#using-composition.

I'll bring it up with the other maintainers and see what they think

**Comment by Slapbox** [comment]
Thanks for your reply @iRoachie!  I just wanted to make sure someone in the position to know what's going on could take a look.

That's a really excellent workaround idea!

**Comment by cielojrdev** [comment]
My solution for this is adding SearchBar in your theme as well,
SearchBar: {
    inputContainerStyle: {
      marginTop: 0
    }
 }

**Comment by Slapbox** [comment]
@cielojrdev, that didn't work for me at all on `1.0.0.` Perhaps it's fixed now?

**Comment by cielojrdev** [comment]
> @cielojrdev, that didn't work for me at all on `1.0.0.` Perhaps it's fixed now?

Yeah, It worked for me, I'm using version 1.1.0

**Comment by AzzouDuGhetto** [comment]
Any news on this ?

**Comment by Slapbox** [comment]
@AzzouDuGhetto it was added to the `2.0.1` milestone, so I'm guessing a plan is in the works.

**Comment by AzzouDuGhetto** [comment]
If you don't want to use Composition, you can also wrap your SearchBar into an another Theme Provider, it will override the first one.  For example, this works for me:

```
<ThemeProvider theme={theme}>
   <Input {...} />
      <ThemeProvider theme={theme.searchBar}>
         <SearchBar {...} />
      </ThemeProvider>
</ThemeProvider>
```

where theme look like: 
```
const theme = {
  Input: {...},
  searchBar: {
    SearchBar:{...},
  },
};
```

**Comment by nlok5923** [comment]
@flyingcircle sir can i work on this issue.

**Comment by arpitBhalla** [comment]
@nlok5923 How are you going to do this?

**Comment by arpitBhalla** [comment]
@Slapbox Now the searchbar don't use themed input, so I am hoping it's no longer any issue in v4
