### ISSUE TITLE
(1.0.0) Header component height issue in android

### ISSUE THREAD

**Issue by kumaresan-cgvak** [react-native-elements/react-native-elements#1793]
Am able to reproduce the same issue that i reported earlier in beta version.(https://github.com/react-native-training/react-native-elements/issues/1574#issue-380651167)

I was trying to use the Header component in my app, the header component was working as expected in iOS but in Android I am getting status bar height along with the header component. Is there anyway to remove the status bar height from Android.

Here is the code snippet I have used:

```
<Header
          backgroundColor='transparent'
          containerStyle={{ width: '100%', backgroundColor: '#3488C0', borderBottomWidth: 0 }}
          leftComponent={{ icon: 'menu', color: '#fff', underlayColor: '#3488C0', onPress: () => this.toggleMenu(), }}
          centerComponent={{
            text: 'My History',
            style: {
              fontSize: 20,
              fontWeight: 'bold',
              fontFamily: Fonts.Lato,
              color: 'white'
            }
          }}
        />
```

Here is the result I am getting in Android and iOS:

Example:
**iOS:**
![screen shot 2019-02-19 at 7 50 31 pm](https://user-images.githubusercontent.com/5547152/53021742-e5a81680-347f-11e9-9dc0-4ae137d76d86.png)
![screen shot 2019-02-19 at 7 50 57 pm](https://user-images.githubusercontent.com/5547152/53021776-f6f12300-347f-11e9-9436-9054f7c18df8.png)
**Android:**
![screen shot 2019-02-19 at 7 55 09 pm](https://user-images.githubusercontent.com/5547152/53022125-8d254900-3480-11e9-8994-b2d2770569d4.png)

**Environment :**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.0.0     |
| react-native          |   0.58.4     |
| npm           |   6.7.0      |

**Comment by iRoachie** [comment]
What device are you testing on? Are you using expo?

**Comment by McFly78** [comment]
Hi,
I have the same problem on Android.
I am not using Expo.

react-native-elements: 1.0.0
react-native 	0.57.8

**Comment by wendelmoraes** [comment]
Do you using react-navigation? If yes, check your Navigator
createStackNavigator -> create a top bar
I recommend you use another navigator(createBottomTabNavigator, drawer, etc).

**Comment by kumaresan-cgvak** [comment]
> What device are you testing on? Are you using expo?

@iRoachie  Am testing it using Pixel emulator with API 28. 

Am not using expo.

**Comment by McFly78** [comment]
Yes I use react-navigation.
I tried on StackNavigator and TabNavigator and have the same issue.

As a workaround I use the following parameter :

statusBarProps={
    translucent: true, 
 }

**Comment by xavier-villelegier** [comment]
@kumaresan-cgvak As suggested by @McFly78 we are assuming that you use a translucent status bar (so we need to add the StatusBar to the Header height.

https://github.com/react-native-training/react-native-elements/blob/c668c78dddd9315f6ca5ec2548e051b2a7e29c73/src/header/Header.js#L158-L162

If you want a smaller header you can still override the height:

```
<Header containerStyle={styles.headerContainer} />

…

const styles = StyleSheet.create({
  headerContainer: {
    height: Platform.select({
        android: 56,
        default: 44,
      }),
  },
});
```

**Comment by kumaresan-cgvak** [comment]
@iRoachie @xavier-villelegier Making the StatusBar as translucent solves the issue. but it will be good if there is prop in Header component which can be set to true or false based on the StatusBar translucent status. So, the header height gets automatically updated by default.

**Comment by phanbien9x** [comment]
I use expo, react-navigation, statusBarProps={{ translucent: true }}, But my header on both android and ios like this. What I wana do to fix this?
![image](https://user-images.githubusercontent.com/47513285/54174455-22808f80-44b9-11e9-8366-7e90777aac58.png)

**Comment by Chris533** [comment]
```
TabNavigator.navigationOptions = ({ navigation }) => {
  // console.log(navigation.state)
  const { index } = navigation.state
  switch (index) {
    case 0: case 1: case 3: case 4:
      return {
        header: null
      }
    case 2:
      return {
        header: (
          <StatusBar translucent />
        )
      }
...
```

Screen which added header
```
  render () {
    return (
      <View style={styles.container}>
        <Header
          leftComponent={{ icon: 'menu', color: '#fff' }}
          centerComponent={{ text: '购物车', style: { color: '#fff' } }}
          rightComponent={{ icon: 'edit', color: '#fff' }}
        />
        <ScrollView>
...
```

**Comment by GutoLusilo** [comment]
I had the same issue. I know it's kind of a workaround, but **I solved this for me adding this prop:**

`containerStyle={{ paddingTop: 0 }}`

**Comment by oxyii** [comment]
@iRoachie @xavier-villelegier too small change for PR:

> so we need to add the StatusBar to the Header height

https://github.com/react-native-training/react-native-elements/blob/c668c78dddd9315f6ca5ec2548e051b2a7e29c73/src/header/Header.js#L158-L162

Yes! But only if expo is not handled it! First we must check for expo env:
```jsx
const expoRoot = (global.Expo || global.__expo || global.__exponent);
```
if expo in env then check for handling status bar:
```jsx
const skipAndroid =
  && !!expoRoot 
  && !!expoRoot.Constants 
  && !!expoRoot.Constants.manifest
  && !!expoRoot.Constants.manifest.androidStatusBar
```
So [react-native-status-bar-height](https://github.com/ovr/react-native-status-bar-height) can [skip android](https://github.com/ovr/react-native-status-bar-height#usage-getstatusbarheightskipandroid-boolean--false):

```jsx
getStatusBarHeight(skipAndroid)
```

**Comment by oxyii** [comment]
@McFly78 

> Yes I use react-navigation.

[this comment](https://github.com/react-navigation/react-navigation/issues/4336#issuecomment-392185562) will helps you

**Comment by RodolfoSilva** [comment]
@McFly78 this workaround works for me
```jsx
<Header
  containerStyle={Platform.select({
    android: Platform.Version <= 20 ? { paddingTop: 0, height: 56 } : {},
  })}
  centerComponent={{ text: 'Title', style: { color: '#fff' } }}
/>
```

**Comment by jedwiwat** [comment]
@McFly78 

from @oxyii @GutoLusilo answer

i combine this two and it works.

just add this

```
<Header
       containerStyle={styles.headerContainer}
	placement="left"
	leftComponent={{ icon: 'menu', color: '#fff' }}
	centerComponent={{ text: 'MY TITLE', style: { color: '#fff' } }}
	rightComponent={{ icon: 'home', color: '#fff' }}
/>
```

```
const styles = StyleSheet.create({
	container: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center'
	},
	headerContainer: {
		height: Platform.select({
			android: 56,
			default: 44
		}),
		paddingTop: 0
	}
});
```

**Comment by jedwiwat** [comment]
@kumaresan-cgvak 

This is my solution
just add this to your Header
 `statusBarProps={{ barStyle: 'light-content', translucent: true, backgroundColor: 'transparent' }}`

**Comment by crobinson42** [comment]
@iRoachie this can probably be closed after a comment or documentation is added in the docs about this quark effecting only Android

**Comment by iRoachie** [comment]
@oxyii Did we come up with any solutions to this?

**Comment by crobinson42** [comment]
@iRoachie this "quark" is related to the statusBar that's included in the Header component and adding the prop `statusBarProps={{ translucent: true}}` is the solution on Android phones that do not have a "notch" in the top of the viewport.

**Comment by oxyii** [comment]
@iRoachie #1854 ?

**Comment by kozanb** [comment]
I had the same issue and i have fixed it with a container View
Use this style and fix this issue; **style={{marginTop:Platform.OS === 'ios' ? 0 : -20}}**

`<View style={{marginTop:Platform.OS === 'ios' ? 0 : -20}}>`
   ` <Header`
       ` backgroundColor='#f5f5f5'`
        `leftComponent={{ icon: 'menu', color: '#3b3b3b'}}`
        `centerComponent={{ text: 'Home', style: { color: '#3b3b3b', fontSize:16, fontWeight:'bold' }}}`
        `rightComponent={{ icon: 'settings', color: '#3b3b3b'}} >`
    `</Header>`
`</View>`

**Comment by xlcrr** [comment]
```
const SCREEN_HEIGHT = Dimensions.get('window').height;

<Header containerStyle={{ paddingTop: 0, height: SCREEN_HEIGHT * 0.1 }} />
```

**Comment by Selman555** [comment]
When you're done headbanging a hole in the wall like me, you might want to check if you're importing `SafeViewArea` from `react-native` and not from `react-native-safe-area-context`.

I hope this helps someone. Now please excuse me while I bang my head a few more times for not noticing.
