### ISSUE TITLE
Tooltip Positioning Issue on Android

### ISSUE THREAD

**Issue by kufii** [react-native-elements/react-native-elements#1804]
Follow up to:
https://github.com/react-native-elements/react-native-elements/issues/1744

Issues related to this PR:
https://github.com/react-native-elements/react-native-elements/pull/1751

I've found 2 cases where the tooltip positioning is still messed up.

1) When ejecting from expo to pure react-native the issue still occurs
2) On expo, when running `StatusBar.setHidden(true)` the issue still occurs

Given all the potential edge cases requiring different yOffsets, I think the best bet is to add a yOffset prop to the Tooltip component so that the developer can fix it as needed

**Comment by kufii** [comment]
further investigation, on a pure react-native project the fix works if you run `StatusBar.setTranslucent(true)`

**Comment by kufii** [comment]
So here are my conclusions:

If the statusbar is hidden, or the statusbar is not translucent, the offset is not required

If the statusbar is not hidden, and the statusbar is translucent, the offset is required

As far as I can tell there no way to check if the statusbar is hidden/translucent or not. So the best option is probably either a `yOffset` property, or `statusBarIsHidden` and `statusBarIsTranslucent` properties.

**Comment by iRoachie** [comment]
This is fixed in https://github.com/react-native-elements/react-native-elements/pull/1875 by @oxyii
