### ISSUE TITLE
Move slider by touching spot on the line

### ISSUE THREAD

**Issue by bneigher** [react-native-elements/react-native-elements#1838]
**Question / Feature**
One thing that I believe would be valuable is if the slider thumb can jump to a position on the line if you touch that spot in the line, like how sliders behave on a website on a computer for example.

Maybe this is already possible manually or even as a parameter, but I couldn't find it myself and perhaps others like me are googling and looking for this.

Is this possible?  If not, does anyone think this would be a nice feature?

**Comment by manzoorwanijk** [comment]
Any update on this?

**Comment by liaokaime** [comment]
我认为这是非常好的建议
