### ISSUE TITLE
[web] Image component behavior

### ISSUE THREAD

**Issue by oxyii** [react-native-elements/react-native-elements#1855]
Related my RNWeb issue https://github.com/necolas/react-native-web/issues/1322

Need to look for a way around this... On web platform if `source` prop changed Avatar component shown overlay only.

**Comment by flyingcircle** [comment]
Looks like this fix is set for web version 13. Will wait until then

**Comment by flyingcircle** [comment]
Looks like the fix for this should be available now on web. @oxyii maybe you can double check this to see if you're still seeing the error?
