### ISSUE TITLE
Move docs to new URL

### ISSUE THREAD

**Issue by Monte9** [react-native-elements/react-native-elements#1857]
We just bought the domain name: reactnativeelements.com

Move the existing website/docs to the website.

Feel free to call out specific links on the readme/external websites that need to be updated.

**Comment by iRoachie** [comment]
What's the migration for this looking like? Did you already add it in Github settings?

Off the top of my head it should be just to update the docusaurus path. https://github.com/react-native-training/react-native-elements/blob/master/website/siteConfig.js#L12

**Comment by iRoachie** [comment]
@Monte9 do you have the credentials for godaddy so we can make this change? Message me on slack

**Comment by Monte9** [comment]
Yes, I do. I can transfer the domain to your godaddy so you can hook it up. I'll slack you

**Comment by pranshuchittora** [comment]
Hi @Monte9 
IMO instead of spending on the domain and the hassle of maintaining that, shall we migrate to `js.org` subdomain (react-native-elements.js.org).

Example
https://webpack.js.org
https://pranshuchittora.js.org

**Comment by Monte9** [comment]
I have made the required changes on GoDaddy

<img width="1175" alt="Screen Shot 2020-09-22 at 11 37 15 PM" src="https://user-images.githubusercontent.com/7840686/93922025-022cc480-fd2f-11ea-9800-11970fa6c446.png">

**Comment by Monte9** [comment]
This work is done thanks to @flyingcircle! 👏 

New website is live here: https://reactnativeelements.com/
