### ISSUE TITLE
position of Overlay is  not in control in version 1.1.0

### ISSUE THREAD

**Issue by wvalen** [react-native-elements/react-native-elements#1861]
**
In version 1.0.0, i could use  code
   `containerStyle={{justifyContent: 'flex-end'}} `
to set the position of Overlay on the bottom of page.

But in version 1.1.0, the position control is missing.
and i found no description about this in release detail.
**

**
Could this feature to be recover? 
**

**Comment by nimo007** [comment]
+1

**Comment by iRoachie** [comment]
Seems to be because of a nested View that isn't styleable by the user https://github.com/react-native-training/react-native-elements/blob/master/src/overlay/Overlay.js#L51

**Comment by wvalen** [comment]
Actually in version 1.0.0-beta5 or older,  we'd like to use Overlay to display like a dialog,  it's really useful and convenient. But in current version,  Overlay  seem to be more difficult to use than before.

**Comment by iRoachie** [comment]
The problem is that the old overlay had a ton of issues because it was never a _truly_ a modal before, and was only using zIndex and absolute positioning which had tons of issues on Android.

**Comment by wvalen** [comment]
I've got it.  Seems, i need to use custom  Modal  rather than Overlay.
Thanks for reply.

**Comment by AnthonyTailer** [comment]
In version **1.1**, you could use: 
`overlayStyle={{ position: 'absolute', bottom: 0 }}`
to set the position of Overlay on the bottom of page. Works for me.

**Comment by iRoachie** [comment]
Should be able to do the suggestion by @AnthonyTailer

**Comment by thanhluantl2304** [comment]
So the next release solved the problem @iRoachie ? Cause I don't want to use position 'absolute'

**Comment by iRoachie** [comment]
No. Position absolute works so I have no reason to implement another change

**Comment by thanhluantl2304** [comment]
But If i set absolute and then input some data to the components. The keyboard will put all the view up and some parts of view will be hidden. Do you have any idea about that?

**Comment by wvalen** [comment]
> But If i set absolute and then input some data to the components. The keyboard will put all the view up and some parts of view will be hidden. Do you have any idea about that?

You can use react-native-modal. It could help you to solve that problem.

**Comment by thanhluantl2304** [comment]
Ok, thanks @wvalen!  I will try it!
