### ISSUE TITLE
Slider will have a small delay at first render

### ISSUE THREAD

**Issue by SDxBacon** [react-native-elements/react-native-elements#1870]
Hi, 

I noticed that the thumb and the track of the Slider component will be rendered after a small delay. After I looked into `Slider.js` in RNE package, I think the reason might be the Slider component need to measure the size of track, thumb and container in the onLayout callback while rendering. It is not a big deal, but the delay time will increase with the raise of amounts of components in a screen. Which cause it much more easy to be noticed.

This happened on both Android and iOS. How do I overcome this problem?

Thanks!

**Demo GIF**
![](https://i.imgur.com/g5FXzNV.gif)

**Comment by pp-chain** [comment]
We have the same problem.
Slider has customized tracker and first time renders without customization at position 0.
Independent to our code (nothing from our code depends to it).

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this?

**Comment by flyingcircle** [comment]
In running a debugger on this page, I see them both the track and thumb pieces rendering at the same time now. Let me know if this ticket needs to be reopened.

**Comment by ElchinJ** [comment]
> In running a debugger on this page, I see them both the track and thumb pieces rendering at the same time now. Let me know if this ticket needs to be reopened.

How did you fix that?
