### ISSUE TITLE
Tooltip - customize pointer styles

### ISSUE THREAD

**Issue by v0lume** [react-native-elements/react-native-elements#1876]
I have new mockups for our application where tooltip has border shadow. I can set shadow for tooltip container, but not for pointer. How can i customize styles for pointer?

![image](https://user-images.githubusercontent.com/5075100/56745678-7999a580-6783-11e9-91c0-d21d7da98bb1.png)

Also there might be a problem with shadow in place between pointer and container:

![image](https://user-images.githubusercontent.com/5075100/56745794-b1a0e880-6783-11e9-968f-14d1409ef59b.png)

**Comment by oxyii** [comment]
@v0lume RNE Tooltip [triangle pointer](https://github.com/react-native-training/react-native-elements/blob/master/src/tooltip/Triangle.js) is very old [css trick](https://css-tricks.com/snippets/css/css-triangle/) and nothing more. Even if there is a possibility to add shadow to triangle, it will not be displayed correctly. Triangle shadow will be square! On Android - exactly. I think tooltip triangle should be a picture in your case...

I know that you using my gist instead RNE Tooltip. So try the following:

1. Remove gist from deps, copy [RNEModalTooltip file](https://gist.github.com/oxyii/b28c003d87c619674def0878473338a0#file-rnemodaltooltip-js) into folder in your app src
2. Copy [triangle pointer file](https://github.com/react-native-training/react-native-elements/blob/master/src/tooltip/Triangle.js) into the same folder, point `import Triangle` in first file to this file
3. Now you can work with pointer.

This is a very bad way, but I don’t see any other way in your case. At the same time, I do not think that this should be merged into RNE.
