### ISSUE TITLE
Button theme overrides external type style

### ISSUE THREAD

**Issue by michael-stern** [react-native-elements/react-native-elements#1886]
**Explain what you did**
I have a default buttonStyle in my theme with a default backgroundColor.
I am trying to make a Button that has the "outline" type but it looks like the theme buttonStyle is overriding the type prop passed to Button.

**Expected behaviour**
Given the style order of: Internal -> Theme -> External, I would expect the `type` prop to take precedence over the backgroundColor from the theme. 

**Describe the bug**
In line 100-102 of Button.js it's taking the `buttonStyle` prop (which can come from the theme) and applying that after `styles.button(type, theme)`. 
This means that the backgroundColor and borderWidth that the type creates are always overriden by the buttonStyle which can come from the theme. 

**To Reproduce**
Example:

```bash
# Snack
https://snack.expo.io/rkoXGXMhN

# Steps
1. See the theme with buttonStyle with backgroundColor
2. See the `type="outline"` prop passed to Button
3. See the button is not an outline button
4. Comment out the backgroundColor line in the theme, the button is now an outline button
```

**Possible Solution**
I think that the button type should always override other buttonStyles with regards to borderWidth and backgroundColor. 
I think this can be fixed by making the `styles.button(type, theme)` function take `buttonStyle` as a third argument and making the "outline" or "clear" types override the buttonStyle. 

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   1.1.0      |
| react-native          |  0.59.0       |

**Comment by saxenanihal95** [comment]
may i work on this one ?

**Comment by iRoachie** [comment]
Sure, what's your plan on how to fix it?

**Comment by saxenanihal95** [comment]
I think the way @michael-stern mentioned:
to pass buttonStyle as third argument in styles.button(type, theme)

**Comment by iRoachie** [comment]
Coool, try fixing it and see. If you get stuck you can definitely report back here

**Comment by saxenanihal95** [comment]
ok

**Comment by saxenanihal95** [comment]
@iRoachie 
I have tried passing the buttonStyle

![Screenshot from 2019-08-12 10-12-06](https://user-images.githubusercontent.com/17348595/62845968-1dcf3a00-bcea-11e9-88a2-38134929d090.png)

and override it like this

![Screenshot from 2019-08-12 10-12-40](https://user-images.githubusercontent.com/17348595/62845979-363f5480-bcea-11e9-97c5-4779b2184b97.png)

but problem with that is when we pass buttonStyle to Button in that case buttonStyle will be overrided by type

![Screenshot from 2019-08-12 10-14-26](https://user-images.githubusercontent.com/17348595/62846006-6981e380-bcea-11e9-86ea-6da74ec88985.png)

**Comment by iRoachie** [comment]
I think that’s what the OP is requesting

**Comment by robert-bo-davis** [comment]
Try this instead:

```javascript
const styles = {
  button: (type, theme, buttonStyle) => ({
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 3,
    padding: 8,
    borderColor: theme.colors.primary,
    ...buttonStyle,
    backgroundColor:
      type === 'solid'
        ? buttonStyle.backgroundColor
          ? buttonStyle.backgroundColor
          : theme.colors.primary
        : 'transparent',
    borderWidth:
      type === 'outline'
        ? buttonStyle.borderWidth
          ? buttonStyle.borderWidth
          : StyleSheet.hairlineWidth
        : 0
  }),
....
```

**Comment by saxenanihal95** [comment]
@iRoachie  I am not passing buttonStyle still getting buttonStyle in props of Button Class.

<img width="798" alt="Screenshot 2019-09-26 at 9 56 42 AM" src="https://user-images.githubusercontent.com/17348595/65658303-bd4f4e80-e044-11e9-8b60-96b69db66d96.png">
<img width="881" alt="Screenshot 2019-09-26 at 9 55 54 AM" src="https://user-images.githubusercontent.com/17348595/65658304-bd4f4e80-e044-11e9-8f7b-ce9336c260c9.png">

**Comment by iRoachie** [comment]
Don't think we have a good way to fix this. Instead, I'd just recommend setting the primary colour in your theme or directly on the component.

https://snack.expo.io/@roach_iam/blissful-pretzel

**Comment by a-fortunato** [comment]
I'm having the same problem when trying to make the border of buttons a bit wider.
If I add `borderWidth` to the theme, then "clear" buttons appear with a border too.

Would it be possible to make the theme object a bit more customizable?
Like, would it be an option that (inside theme) buttonStyles, or Button, receives a callback with the rest of Button props, or Button types and return a variable style depending on those.
Something like:
```ts
theme: Theme = {
   Button: {
      buttonStyle: props => {
         const commonStyle = { margin: 20 }
         if (props.type === 'outline') {
            return {
               ...commonStyle,
               borderWidth: 1.5,
            }
         }
         return commonStyle
      }
   }
}
```
Or maybe if it could receive a certain prop for each type, like:
```ts
theme: Theme = {
   Button: {
      buttonStyle: {
         outline: { borderWidth: 1.5 },
         margin: 20,
      }
   }
}
```
