### ISSUE TITLE
Slider not working for web

### ISSUE THREAD

**Issue by danielmarino24i** [react-native-elements/react-native-elements#1890]
Version: 1.1.0

**Explain what you did**
I rendered a Slider component, and run it on web. (It works for native)
```
import { Slider } from 'react-native-elements';
...
<Slider
    value={volume}
    onValueChange={player.setVolume}
/>
```

**Expected behaviour**
Successfully render Slider component

**Describe the bug**
Slider does not work as it throws `Uncaught TypeError: mainStyles.thumbHorizontal is not a function`
I don't know if having a function on styles is quite standard, but in any case, seems react-native-web is treating styles differently, when running the app, the var `mainStyles.thumbHorizontal` is an id (Stylesheet.create), and it is trying to invoke it as a function.

**Possible Solution**
I am not sure but maybe flattening `mainStyles.thumbHorizontal` (Stylesheet.flatten) addresses the issue
**Screenshots**
![image](https://user-images.githubusercontent.com/35027703/57615526-30679500-757c-11e9-935b-e73df7015382.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.1.0     |
| react-native          |    react-native-web 0.11.2     |
| npm or yarn           |    npm 6.4.1     |

**Comment by ncuillery-youitv** [comment]
I got the same when using React Native on a non-standard platform (proprietary graphic engine [You.i](https://www.youi.tv/))

I guess some theme properties are defined only for `android` or `ios`.

react-native-elements 1.1.0

**Comment by CHaNGeTe** [comment]
Made a PR that for me it solves the issue:
https://github.com/react-native-training/react-native-elements/pull/1919
