### ISSUE TITLE
Tooltip onLongPress option

### ISSUE THREAD

**Issue by ddereszewski** [react-native-elements/react-native-elements#1927]
**Is your feature request related to a problem? Please Describe.**
Often in the apps you can long press some text to show the tooltip with options. 
The Tooltip component fits perfectly to that. The only problem is that it works on onPress trigger

**Describe the solution you'd like**
In Tooltip it will be nice to have props like trigger which is defult onPress, but can be changed to onLongPress

**Comment by ddereszewski** [comment]
PR #1932

**Comment by flyingcircle** [comment]
@ddereszewski can you checkout my PR and see if that meets your needs?
