### ISSUE TITLE
Avatar icon should support URI images.

### ISSUE THREAD

**Issue by BoKKeR** [react-native-elements/react-native-elements#1952]
**Is your feature request related to a problem? Please Describe.**
There is no way to set the avatar icon to be a custom image. 
With the use URI images the usability of the avatar component would be expanded. 

With this adjustment the avatar component could be used to show expense items which in the corner could have the expense owners image. This cant be done right now. 

**Describe the solution you'd like**
With the current implementation we are for no reason limited to the inbuilt icons. 
From my understanding the underlying support is there for the images to be supported, and we would just need to pass down the URI as props to the component. 

**Not** even custom icons are supported at the moment.
This would open a whole new world of adjustments. 

**Describe alternatives you've considered**
Another option is just building a whole new component that would be a copy of the avatar and just have a different name and support for this. But that would add extra work to test, and upkeep for no reason.
![Screenshot 2019-07-10 at 15 23 23](https://user-images.githubusercontent.com/2664857/60972528-c0c91880-a326-11e9-98c4-bd3ebc986dbd.png)

**Comment by iRoachie** [comment]
What do you mean?

```jsx
<Avatar source={{ uri: 'your.iamge.com/test.png'}} />
```

**Comment by BoKKeR** [comment]
But that is for the avatar and not the corner icon! The corner icon should support URI just like the avatar part

**Comment by iRoachie** [comment]
Ohhh the edit icon! Got you now.

**Comment by BoKKeR** [comment]
Is there any feedback on this? Should I try to submit a PR?

**Comment by iRoachie** [comment]
It’s definitely a good idea. I think we should rename it to maybe `accessory`. A change like this would be a breaking change though.

The next release after 1.2.0 is going to be 2.0.0 so let’s do it then

**Comment by ganes1410** [comment]
@iRoachie  I'll work on this.

**Comment by ganes1410** [comment]
@iRoachie
 Here is the approach I am thinking for this issue. Add additional two more props called 
**editButtonSource**:  which accepts the uri and `conditionally render` this with icon.
**editButtonStyles**: an object to pass the styles for the .edit button.

Let me know what you think

**Comment by iRoachie** [comment]
I think what should happen first is that we should change the current edit button and it's docs to being `accessory`. Then we can make the change to allow it to use an image.
