### ISSUE TITLE
Enhance default styling for input

### ISSUE THREAD

**Issue by iRoachie** [react-native-elements/react-native-elements#1962]
Right now the Input component has very weird default styles for adding leftIcon which end up looking like this:
![Screenshot 2019-07-14 at 5 07 17 PM](https://user-images.githubusercontent.com/5962998/61189328-db1e3180-a659-11e9-8cfe-d606f589267b.png)

This is because of the margin added here https://github.com/react-native-training/react-native-elements/blob/master/src/input/Input.js#L184.

We should fix this so it looks better (no left margin and add padding).

Also some default margin bottom/top as well:

![Screenshot 2019-07-14 at 5 08 54 PM](https://user-images.githubusercontent.com/5962998/61189346-1fa9cd00-a65a-11e9-9cd8-35a45b2544ac.png)

This would be a breaking change since it’ll affect the layout of users. Slating this for 2.0.0 as a result

**Comment by ganes1410** [comment]
@iRoachie is anyone working on this ?

**Comment by iRoachie** [comment]
Nope! No one as yet. For future, if you see a `WIP` or `PR Submitted` label, it means someone has started working on it or they said they would.

**Comment by ganes1410** [comment]
@iRoachie ok.
