### ISSUE TITLE
Add testID prop for each component.

### ISSUE THREAD

**Issue by rollsroyc3** [react-native-elements/react-native-elements#1966]
**Is your feature request related to a problem? Please Describe.**
Need to add testID to each component to allow automated testing.

**Describe the solution you'd like**
To use a default testID or allow a custom testID prop to be passed into component.

Components with no testID:

- Avatar
- Badge
- Button
- Card
- ListItem
- PricingCard
- SocialIcon
- Text
- Tile
- FeaturedTile

Components with static testID:

- ButtonGroup
- Checkbox
- Header
- Icon
- Image
- Input
- Overlay
- SearchBar
- Slider
- Tooltip

**Comment by hariDasu** [comment]
i use testID without issue on `<ListItem/>`, i believe it passes whatever extra props you provide down with `{...attributes}`, I have XCUITests with `<ListItem testID="logOutButton"/>` working in my react native v0.59 app

**Comment by schmijos** [comment]
Same issue here with *react-native* `0.59.8` and *react-native-elements* `1.1.0`. `testID` works with `import {ListItem} from "native-base"` but not with `import {ListItem} from "react-native-elements";`

**Comment by jtich** [comment]
> Same issue here with _react-native_ `0.59.8` and _react-native-elements_ `1.1.0`. `testID` works with `import {ListItem} from "native-base"` but not with `import {ListItem} from "react-native-elements";`

The reason this works in `native-base` -- and conversely, does _not_ work in this "toolkit" -- is because those maintainers were kind enough to spread the `propTypes` of `TouchableHighlight` into `ListItem.propTypes` ([source](https://github.com/GeekyAnts/NativeBase/blob/1ca2d20776bbcb31daf85ce4012872e17cb9a0f6/src/basic/ListItem.js#L58)).

**Comment by iRoachie** [comment]
@jtich the same is done for this library https://github.com/react-native-training/react-native-elements/blob/next/src/list/ListItem.js#L102

Most If not all of our components are done this way

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Comment by KrisLau** [comment]
@iRoachie Still missing as a prop on numerous components

- https://github.com/react-native-elements/react-native-elements/issues/3786
