### ISSUE TITLE
Font size cannot be set for the title of featured tile

### ISSUE THREAD

**Issue by svmszcck** [react-native-elements/react-native-elements#1980]
I was trying to set the font size of tile title but I couldn't. Because when I check the source code, tile title has h4 prop. Font size doesn't have any effect...

Add titleStyle prop with {fontSize: 10} value for the featured tile. You will see that this doesn't have any effect...

**Expected behaviour**

Title font size of the featured tile should be able to set.

**Versions**

react-native-elements: 1.1.0
react: 16.8.6
react-native: 0.60.4

**Comment by immackay** [comment]
Applies to any tile, featured or not.

**Comment by Gregjarvez** [comment]
@svmszcck @immackay Would you like to send a PR for this?

**Comment by KayOhhDee** [comment]
I would want to tackle this.

**Comment by Gregjarvez** [comment]
@KayOhhDee go for it !

**Comment by KayOhhDee** [comment]
Sure

**Comment by Prateek93a** [comment]
Hello world, since the issue is still open, can I work on this, as my first coding open source contribution?

**Comment by Prateek93a** [comment]
I tested the Tile component particularly and fontSize worked fine, I guess the issue has been resolved already

**Comment by immackay** [comment]
On which platform? The h4 prop is still there, this issue has not been touched as of yet.

**Comment by svmszcck** [comment]
I am gonna open a PR tomorrow. Thanks...

**Comment by svmszcck** [comment]
Opened the PR: https://github.com/react-native-training/react-native-elements/pull/2057

**Comment by MaximLeonov** [comment]
Still does not work in 1.2.0
