### ISSUE TITLE
Font Awesome Icon version

### ISSUE THREAD

**Issue by JatinderSingh88** [react-native-elements/react-native-elements#1989]
**Is your feature request related to a problem? Please Describe.**
I want to use the latest version of font awesome with React Native elements 1.1.0 but unable to use. It is supporting font awesome 4.7.0 version icons. Please provide help to solve this issue.

**Comment by iRoachie** [comment]
We use Icons through react-native-vector-icons. You can use any version you want once it's greater than 6.0.0

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Comment by sowizz** [comment]
What icon type should be provided to use Font Awesome 5?

**Comment by iRoachie** [comment]
Available on the next branch. Should be out in 2.0.0 https://github.com/react-native-elements/react-native-elements/commit/6cc85af1f4a5d7466e169df9054337dd1ba67fff
