### ISSUE TITLE
Avatar - Add option to disable fade animation

### ISSUE THREAD

**Issue by danwhite-ad** [react-native-elements/react-native-elements#2004]
Require the ability to disable fade between icon and source. I am setting the avatar source within componentDidMount (fetching from cache), but I am experiencing a fade between the set icon and the fetched source which is a jarring user experience.

**Comment by iRoachie** [comment]
Fade in is the expected behaviour which is the direct opposite of jarring user experience. This can't be disabled at the moment. The avatar uses the RNE Image under the hood.

We may consider adding a prop to disable it if any more request come in

**Comment by danwhite-ad** [comment]
The issue I am having is that I have an image in cache, but because of the fade it is making it appear that the image is being remotely fetched every time the component is loaded.

**Comment by iRoachie** [comment]
Gotcha! That makes sense. It wouldn't be able to do in this next release though

**Comment by Prateek93a** [comment]
Can I work on this one?

**Comment by iRoachie** [comment]
Sure go ahead. This will need to be a prop on the Image component

**Comment by Prateek93a** [comment]
Ok

**Comment by Prateek93a** [comment]
Sir, thanks for providing me the chance to make my first coding open source contribution. Sir, according to my solution, there is a AllowFadeIn(a boolean) prop on Avatar component, and according to its value, fadeDuration prop of Image component imported from image folder, will be set to 0(if true) or 300(default value if false). Is it fine, or can we do something better?

**Comment by Prateek93a** [comment]
Also kindly explain me why we are using onLoadEnd in the Image component

**Comment by iRoachie** [comment]
The Image component has 2 parts, the underlying image and a placeholder view above it. The `onLoadEnd` function is called when the Image loads then we gradually fade the above placeholder.
