### ISSUE TITLE
(Web) Bundle size increases becuse of pre importing all fonts from vector icons

### ISSUE THREAD

**Issue by zivchen** [react-native-elements/react-native-elements#2006]
**Is your feature request related to a problem? Please Describe.**
I only use MaterialIcon but because of getIconType.js preloads all fonts my bundle size increases by 200KB (its the glyphmaps json files of the fonts).
I imagine its the same for native but its more significant on the web.

**Describe the solution you'd like**
Basically if i don't use a font don't load it

**Describe alternatives you've considered**
Not sure to be honest and open to suggestions 🥇 
Maybe Separate component for each font(sounds like allot of work)

**Comment by iRoachie** [comment]
Not sure how you are loading your fonts on the web but it doesn't load fonts by default. See create-react-app example https://github.com/iRoachie/rnw-cra-playground.

You have to manually include fonts https://github.com/iRoachie/rnw-cra-playground/blob/master/src/App.js

**Comment by zivchen** [comment]
Hi @iRoachie 
I load my fonts the same way as in the instructions in the links.
The 200kb is not the font itself but glyphicons (json file which are the map to the fonts), they are added to the code because of the import of fonts in getIconType.js (see image)
<img width="684" alt="Screen Shot 2019-08-07 at 18 44 56" src="https://user-images.githubusercontent.com/983093/62637353-f53eed00-b943-11e9-990d-3983ca34d8d4.png">
When i remove the top lines (except material icon that i use) its gone.
Thanks

**Comment by iRoachie** [comment]
Ahh i get you. Currently it's not possible to do that at the moment. However there's a discussion going on about how we can support this better going forward. See #1613

**Comment by bdombro** [comment]
@iRoachie is anybody working on this? If not, are there plans for anyone to work on this soon?

I guess what I'm really getting at, is is there a roadmap somewhere? :-P. I'd probably like to contribute soon and knowing the roadmap would be helpful for that.

**Comment by iRoachie** [comment]
I don't think anyone's working on it, it was just at a discussion phase. We've never had an official roadmap. You have any examples of open source projects that do?

**Comment by bdombro** [comment]
Not off hand, but I would think big ones do. Maybe I'm more thinking sponsored open source projects. Thanks!

**Comment by necolas** [comment]
I recommend that RN libraries switch to individual svg icons rather than fonts. Svgs have many advantages over fonts including smaller bundle sizes as you only import what you need

**Comment by zivchen** [comment]
If anyone is interested in a temporary fix i did the following:
I made an empty json file with only {} named emptyGlyph.json

on my webpack.config.js config file, in the alias part i added these line so it will replace all my unused fonts with the empty JSON file.
`
        './glyphmaps/AntDesign.json': path.resolve(__dirname, './mocks/emptyGlyph.json'),
        './glyphmaps/Entypo.json': path.resolve(__dirname, './mocks/emptyGlyph.json'),
        './glyphmaps/EvilIcons.json': path.resolve(__dirname, './mocks/emptyGlyph.json'),
        './glyphmaps/Feather.json': path.resolve(__dirname, './mocks/emptyGlyph.json'),
        './glyphmaps/FontAwesome.json': path.resolve(__dirname, './mocks/emptyGlyph.json'),
        './glyphmaps/FontAwesome5Free.json': path.resolve(__dirname, './mocks/emptyGlyph.json'),
        './glyphmaps/FontAwesome5Free_meta.json': path.resolve(__dirname, './mocks/emptyGlyph.json'),
        './glyphmaps/Fontisto.json': path.resolve(__dirname, './mocks/emptyGlyph.json'),
        './glyphmaps/Foundation.json': path.resolve(__dirname, './mocks/emptyGlyph.json'),
        './glyphmaps/Ionicons.json': path.resolve(__dirname, './mocks/emptyGlyph.json'),
        './glyphmaps/MaterialCommunityIcons.json': path.resolve(__dirname, './mocks/emptyGlyph.json'),
        // './glyphmaps/MaterialIcons.json': path.resolve(__dirname, './mocks/emptyGlyph.json'),
        './glyphmaps/Octicons.json': path.resolve(__dirname, './mocks/emptyGlyph.json'),
        './glyphmaps/SimpleLineIcons.json': path.resolve(__dirname, './mocks/emptyGlyph.json'),
        './glyphmaps/Zocial.json': path.resolve(__dirname, './mocks/emptyGlyph.json'),
`

**Comment by KeitelDOG** [comment]
@zivchen thanks a lot. I was getting headaches since months on a project I'm creating with React Native and NextJS. I managed to reduce lot of things, but didn't think of how to do this one.
I'm gonna use this pattern to directly remove useless codes in the main chunk that the Web part doesn't even use. A manual filter is necessary when the package don't provide tree shaking.
