### ISSUE TITLE
[Feature]: Add Image Component which supports parallax

### ISSUE THREAD

**Issue by kenshinman** [react-native-elements/react-native-elements#203]
Hi, thanks for this awesome project. I find it very useful and efficient.
I have a suggestion though, that'd be adding a parallax effext tp the `Tile` Component that fades into a Heaser of sort. Thanks

**Comment by binoy14** [comment]
@kenshinman It is on our lists, Keep an eye out for future releases.

**Comment by Monte9** [comment]
In an effort to streamline all RNE issues such that it is easier to get to solutions faster/ submit a new issue we have decided to close any enhancement/roadmap features as "issues". 

Feel free to use this issue to talk about this feature and ping @binoy14 or me (@monte9) if you feel like you can submit a PR for this. Thanks in advance.

Also you can track the status of this feature and all other roadmap features [here](https://github.com/react-native-community/react-native-elements/issues/195#issuecomment-286213704).

**Comment by filiphosko** [comment]
@binoy14 @Monte9 Is anybody working on this? I have friend who would like to take a crack at it.

**Comment by Monte9** [comment]
Nope. Your friend is more than welcome to work on it. 👍

**Comment by flyingcircle** [comment]
Closing due to lack of interest
