### ISSUE TITLE
Invariant Violation: {"backgroundColor":-859248897,"width":"<<NaN>>","height":"<<NaN>>"} is not usable as a native method argument

### ISSUE THREAD

**Issue by Baterka** [react-native-elements/react-native-elements#2061]
**Explain what you did**
Clean `blank` expo project with `react-native-elements` installed by Yarn. Enabled Remote JS Debugging and opened React Developer Tools (Windows Standalone app). Everytime I click, or hover over `<Input><View><Context.Consumer><RCTView>` app crashes with following error: [https://pastebin.com/zcT3geDH](https://pastebin.com/zcT3geDH)

**Expected behaviour**
No "Invariant Violation" crash 

**Describe the bug**
There is some code error what throwing this error and making app crash. **It is specifically for `<Input>` component!** (Or at least I found it just here)

**To Reproduce**
```
import * as React from 'react';
import { View} from 'react-native';

import { Input } from 'react-native-elements';

export default class App extends React.Component {
  render() {
    return (
      <View style={{marginTop: 100}}>
        <Input placeholder="Username"/>
      </View>
    );
  }
}
```

1. Start app with expo
2. Enable debugging and toggle inspector
3. Open React Developer Tools
4. Click/Hover on <Input> and his child `<RCTView>`
5. App crash

**Screenshots**
![image](https://user-images.githubusercontent.com/3463591/64645587-81e23c80-d415-11e9-97de-a907cb759c37.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| expo | ^34.0.1 |
| react-native-elements |   ^1.2.0      |
| react-native          |    https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz     |
| npm or yarn           |     1.17.3    |

**Comment by iRoachie** [comment]
Can you replicate this with a snack or example project?

**Comment by iRoachie** [comment]
I couldn't replicate this. This is what I saw when I did an inspect.

![Simulator Screen Shot - iPhone 11 - 2019-09-22 at 22 54 39](https://user-images.githubusercontent.com/5962998/65399664-f90bbf00-dd8b-11e9-92ca-e09056878667.png)

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
