### ISSUE TITLE
InputComponent react-native-datepicker libray cannot access child ref

### ISSUE THREAD

**Issue by Cchumi** [react-native-elements/react-native-elements#2062]
**Explain what you did**
Hi
I use Input for all my form input.
For this particular case I would to use a calendar picker.
I use react-native-datepicker who has a function to manually open the picker. (OnPressDate)
I implement this library as a ref with 

> const maRefCalendar = React.forwardRef((props, ref) 

Then I create an react native elements input where i put in the inputComponent the ref maRefCalendar.

Next I have an input before the datepicker with a next button on the keyboard.
I  would this button to open the calendar.
The issue is accessing the inputComponent Ref which is DatePicker to call the onPressDate function
How Can I achieve that ?

Is this a good way to do this ?

thank you

**Screenshots**

this is the result of the ref.current 
![image](https://user-images.githubusercontent.com/40697701/64676660-5479ab00-d476-11e9-8596-d28978980315.png)

this is my ui
![image](https://user-images.githubusercontent.com/40697701/64676071-fdbfa180-d474-11e9-8ed7-05a803e5706a.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   1.2.0      |
| react-native          |   0.59.10      |

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this? I'd love to test.

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
