### ISSUE TITLE
Avatar, (leftAvatar) local source

### ISSUE THREAD

**Issue by antoniosantangelo** [react-native-elements/react-native-elements#2063]
Avatar .. leftAvatar ... 
Can I use a local Image Object ( redux , asset.... )  as source .
Is there only  uri option?

**Comment by iRoachie** [comment]
You can use any of the options for the standard react native image. https://facebook.github.io/react-native/docs/images#docsNav

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
