### ISSUE TITLE
(Input) Seems ref has changed?  Can't access input.focus() anymore

### ISSUE THREAD

**Issue by bneigher** [react-native-elements/react-native-elements#2065]
> react-native-elements: 1.2.0

I recently upgraded from pre 1.0.0 to 1.2.0 and it says that some parts of Input component were changed, namely the ref is no longer containing some of the methods I would like to use, like .focus() to dynamically focus on inputs

Note the onSubmitEditing of the email input.  This doesn't work as the .focus() method is no longer attached to the ref.

```javascript
<Label label="Email" />
<Input
  multiline={false}
  placeholder="Your email"
  value={this.state.username}
  textContentType="username"
  ref={c => {
    this.emailInput = c;
  }}
  onSubmitEditing={() => {
    this.passwordInput.focus && this.passwordInput.focus();
  }}
  returnKeyType={'next'}
  onChangeText={value => this.onChangeText('username', value)}
/>
<Label label="Password" />
<Input
  placeholder="Enter password"
  value={this.state.password}
  ref={c => {
    this.passwordInput = c;
  }}
  textContentType="password"
  onSubmitEditing={this.onPressCreateAccount}
  returnKeyType={'send'}
  onChangeText={value => this.onChangeText('password', value)}
/>
```

Ideally - we can access this method like was available before.

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.2.0     |
| react-native          |     0.60.5    |
| npm or yarn           |    6.10.3     |

**Comment by iRoachie** [comment]
The only changes made to the Input component were for propTypes. The Input component works as normal https://snack.expo.io/@roach_iam/adequate-churros

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
