### ISSUE TITLE
Input cannot have full length

### ISSUE THREAD

**Issue by TonyWild** [react-native-elements/react-native-elements#2067]
Hi, I'm using Input. I want Input width full with the view. However, the input doesn't seem to fit with the view.

This is the picture of my screen.
![image](https://user-images.githubusercontent.com/18462177/64909132-2da3c900-d743-11e9-81ce-7d77078f85e6.png)

and this is my code.
```
          <View style={styles.mailView}>
            <Input
              containerStyle={styles.mailInputContainer}
              inputStyle={styles.mailInput}
              onChangeText={(text) => this.setState({ mailID: text })}
            />
          </View>
```

corresponding to the style
```
mailView: {
    borderWidth: 1,
    borderColor: 'blue',
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'stretch',
    marginTop: 5,
  },
  mailInputContainer: {
    borderWidth: 1,
    borderColor: 'green',
  },
  mailInput: {
    borderWidth: 1,
    borderColor: 'violet',
    marginLeft: 0,
    fontFamily: 'NanumSquareB',
    fontSize: 18,
    paddingVertical: 0,
  },
```

What is the problem here? :(

**Comment by iRoachie** [comment]
Set `width: '100%'` on the containerStyle.

**Comment by TonyWild** [comment]
Thanks for the reply. I tried that, however, that makes only green box full length, not the violet one.

**Comment by eviliana** [comment]
You need to remove the horizontal padding of input container. Just add `paddingHorizontal: 0` on your mailInputContainer style.

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
