### ISSUE TITLE
Custom component for CheckBox title

### ISSUE THREAD

**Issue by Auticcat** [react-native-elements/react-native-elements#2070]
**What's the problem**
I wanted to set a text that would display a link inside of it, without having to set the onPress to the whole component.

**What i would like to accomplish**
I'd like to be able to have a prop that let's me override the normal <Text> component that's used from default title.
The thing I'd like to accomplish is to have a checkbox with a text and a clickable part of it, like:
```javascript
<CheckBox
    //normal props
    titleComponent={<Text>Click <Text onPress={()=>null}>here</Text> to read our privacy policy</Text>}
/>
```

**Alternatives**
The only thing i found that could be used is `titleProps` but it doesn't give me a method to set it to a specific word or part of the string.

**Versions**
react-native-elements: 1.2.0
react: 16.8.6
react-native: 0.60.5

**Comment by iRoachie** [comment]
Sounds good! We already have a helper for this that we've used for other components. https://github.com/react-native-training/react-native-elements/blob/aae1a422c28a72eab7cad39e239c424e45c7990f/src/input/Input.js#L18

**Comment by flyingcircle** [comment]
I wrote a test, and there isn't anything stopping someone from setting the title as a component right now. It just isn't stated in the docs as possible. However, there are multiple components that use a 'title' prop, so I feel like this should be an all or nothing thing. Should 'title' props be changed to 'titleComponent' so that they are completely configurable?

**Comment by iRoachie** [comment]
Oh wait that's true, I think the only thing we need to do is update the docs

**Comment by iRoachie** [comment]
Here's an example of what it should say https://github.com/react-native-elements/react-native-elements/blame/next/docs/card.md#L204
