### ISSUE TITLE
Modification of underlayIcon Size

### ISSUE THREAD

**Issue by k3ithl1m** [react-native-elements/react-native-elements#2071]
**Is your feature request related to a problem? Please Describe.**
I'm trying to use the underlay icon at a very small scale. But I would like the icon within the overlay background color to be bigger when the size is too small.

**Describe the solution you'd like**
Being able to input an underlaySize / iconSize so that it either specifically change the size of the underlayBackground or change the size of the icon within the underlay

**Describe alternatives you've considered**
I've looked into the code and the only way I've considered is to write my own Icon class, or have a view on top of the icon. 

**Additional context**
Using size from Icon Component
![Screen Shot 2019-09-18 at 12 26 31 AM](https://user-images.githubusercontent.com/14284173/65125831-018a8100-d9ab-11e9-877c-46fde818c06e.png)

Desired look
![Screen Shot 2019-09-18 at 12 27 00 AM](https://user-images.githubusercontent.com/14284173/65125888-16ffab00-d9ab-11e9-8cc0-812ce4ae7daa.png)

**Comment by flyingcircle** [comment]
You can manually adjust the size of the icon container in the `containerStyle`
```js
<Icon 
  reverse 
  name="hdd-o" 
  size={62} 
  type="font-awesome" 
  containerStyle={{
    alignItems: "center", 
    justifyContent: true, 
    height: 100, 
    width: 100}} 
/>
```
