### ISSUE TITLE
Support for React Native for Web?

### ISSUE THREAD

**Issue by mikeaustin** [react-native-elements/react-native-elements#2083]
I successfully installed and configured rne for rnw for the most part, but some things are not quite right. Overlay is just a big inline view with a red border; Tooltip seems to be always visible and it duplicates it's children. Slider has a thumbHorizontal is not a function.

"React Native Elements just like on mobile can be used in your web projects. This is possible using react-native-web." I'm just curious if it Reactive Native for Web is still supported?

To get it working with a basic webpack.config.js, I used the following. It does not work if you put the babel properties in .babelrc or package.json. They must be in webpack.

```
module.exports = {
  module: {
    rules: [
      {
        test: /\.js?$/,
        use: {
          loader: 'babel-loader',
          options: {
            "presets": [
              "@babel/preset-env",
              "@babel/preset-react"
            ],
            "plugins": [
              "@babel/plugin-proposal-class-properties",
              ["@babel/plugin-transform-runtime", { "regenerator": true }]
            ]
          }
        },
        include: [
          /src/,
          /node_modules\/react-native-elements/,
          /node_modules\/react-native-vector-icons/,
          /node_modules\/react-native-status-bar-height/,
          /node_modules\/react-native-vector-icons/,
        ]
      },
```

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements | 1.2.1        |
| react-native-web          |  0.11.7       |
| npm or yarn           | 6.7.0         |

**Comment by iRoachie** [comment]
Yes there are some components that have some issues in react native web. @oxyii can you look into  Overlay and the other ones mentioned?

**Comment by oxyii** [comment]
@mikeaustin Thanks for your report! We know about web-platform support issues (#1890, #1808 and more). We are working on increasing web-platform supporting. But we cannot workaround webpack tuning at least because `react-native-vector-icons` deps [requires](https://github.com/oblador/react-native-vector-icons#web-with-webpack) webpack settings changes

**Comment by oxyii** [comment]
@mikeaustin about Tooltip exactly: this component uses RN [`Modal`](https://facebook.github.io/react-native/docs/modal) component that [not implemented](https://github.com/necolas/react-native-web/issues/1020) in RNW yet.

**Comment by mschipperheyn** [comment]
@oxyii we use https://github.com/Dekoruma/react-native-web-modal/tree/master/packages/modal-enhanced-react-native-web to work around RN Modal limitations. Out of curiosity, does react-native-elements support a `component` prop on its components so that the default implementation  (e.g. native Modal) can be overwritten to use the passed implementation (e.g. custom Modal with same api).

**Comment by oxyii** [comment]
@mschipperheyn many RNE components have a `Component` among their props. But not all components and not for all their parts. We do not close this issue to think through and implement the optimal solution for `Tooltip` component. I'm not sure what the solution will be able to redefine `Modal` part of `Tooltip`. It is quite fine-tuned there
https://github.com/react-native-elements/react-native-elements/blob/5d83ac0bd844ef78dac758f7baacd69a9a49853e/src/tooltip/Tooltip.js#L184-L191
but I'm sure we will find a solution

**Comment by mikeaustin** [comment]
I ended up rolling my own that simply has a root level absolute view, and pipe down events via context to add elements to it, with a backing view that removes it when tapped. So far it works with pop ups on top of modals. I’ll try the other 2 implementations.

**Comment by iRoachie** [comment]
Hey @oxyii should we add a Component prop on the `Overlay` or should we add https://github.com/Dekoruma/react-native-web-modal/tree/master/packages/modal-enhanced-react-native-web

**Comment by oxyii** [comment]
@iRoachie on `Overlay` and on `Tooltip`.
I'm not sure that one more platform-specific dep is a best way... `Component` prop will be better I think.
