### ISSUE TITLE
What is the best practice to align the header right and left component with title (has minimum no. of character or maximum no. of character)

### ISSUE THREAD

**Issue by nihp** [react-native-elements/react-native-elements#2087]
I am using Header from react-native-elements. I am trying to place the header as left, right and center components.

Here my left component is arrow after this the Title is started below the arrow and at the right above end, it has the Text or Icon. Refer this https://i.stack.imgur.com/2ggSr.png what I am expecting.

I have used margin values in negative so it does not work for different modal devices.
Refer code here https://snack.expo.io/@niph/grounded-watermelon and screenshot here https://i.stack.imgur.com/2ggSr.png

**Actual behavior with example code:**
I have tried with these two ways both not worked correctly for lower and higher modals

This worked for the small title and not worked for large title.
Refer code here https://snack.expo.io/@niph/headerwith-large-text and screenshot here https://i.stack.imgur.com/uTjO5.png

This not worked for the small title and not worked for large title and not worked for me in various device models
Refer code here and screenshot https://snack.expo.io/@niph/grounded-watermelon and https://i.stack.imgur.com/2ggSr.png

**Expected behavior:**

Need to align the header which is work for all models. Also if the title header is too long or it may be small. But it would be like this screenshot https://i.stack.imgur.com/2ggSr.png

**Comment by iRoachie** [comment]
This should do what you're looking to do https://snack.expo.io/@roach_iam/grounded-watermelon

The key is setting the `centerContainerStyle: {flex: 0}`, by default this is set to 3 and left and right set to 1 so that by default the centre takes up the most space. Since you aren't using the centre container, you can completely remove it.

Also a few other things: 
- There's no `outerContainerStyles` so setting this does nothing
- The Header has a default height, I removed that by setting `containerStyle: {height: 0}`
- Also removed the `flex: 1` from your View, as flex 1 will resolve to 0 if there's no set height on the parent

**Comment by nihp** [comment]
@iRoachie I have tried with your above flex changes with your updated code. Now I am able to see the like below. But I need to show the LIST OF NAMES in a line not need to show below. 

Otherwise the text will be shown before the **List text** and if the length exceeds further then show in the next line
![Screenshot 2019-10-01 at 10 29 42 AM](https://user-images.githubusercontent.com/36992338/65935510-f0c01d80-e436-11e9-9f89-14184198da16.png)
![Screenshot 2019-10-01 at 10 29 42 AM](https://user-images.githubusercontent.com/36992338/65935604-44326b80-e437-11e9-9bb8-e207f187efcd.png)

**Comment by iRoachie** [comment]
I’m not understanding what your intended layout is supposed to be

**Comment by nihp** [comment]
If the title is as "NAMES" I need t show as this https://i.stack.imgur.com/2ggSr.png. And If the title is too long I need to show like below attachement

![Screenshot 2019-10-01 at 11 36 48 AM](https://user-images.githubusercontent.com/36992338/65938144-cb83dd00-e43f-11e9-9611-205a92a0c075.png)

**Comment by iRoachie** [comment]
Your 2 Pictures are exactly the same the only different is the words 🤷🏽‍♂️

**Comment by nihp** [comment]
Yes, the only difference is words. But If I try with your code I can't able to achieve the above. Also, I have used margin left values so it does not work for all devices.

**Comment by nihp** [comment]
@iRoachie Any update for this

**Comment by iRoachie** [comment]
You can try add the `numberOfLines` prop  to your text element and set it to 1. https://facebook.github.io/react-native/docs/text#numberoflines

**Comment by nihp** [comment]
If I use numberOfLines = {1} means it shows like below. It ended with dots. Kindly refer the attached image below
![Screenshot 2019-10-08 at 10 42 23 AM](https://user-images.githubusercontent.com/36992338/66369075-77857500-e9b8-11e9-9efd-349f8066e6e0.png)

**Comment by iRoachie** [comment]
There’s no way to magically erase a portion of text, where do expect the text to go if it’s not long enough to fit on one line?

**Comment by nihp** [comment]
I need to show upto below the LIST text. Like this https://github.com/react-native-elements/react-native-elements/issues/2087#issuecomment-536882134

**Comment by iRoachie** [comment]
Just so I get you?


#### Text that fits

```
back-arrow    This text is okay    List
```

#### Text that doesn't fit
```
back-arrow    This text is too     List
              long to fit
```

**Comment by nihp** [comment]
Yes. Refer the attached screenshot for more details
![65938144-cb83dd00-e43f-11e9-9611-205a92a0c075 png  355×121 ](https://user-images.githubusercontent.com/36992338/66540704-60768c80-eb4a-11e9-9ce5-101640b67998.png)

**Comment by iRoachie** [comment]
Every screenshot you send is different 😞

**Comment by nihp** [comment]
Not different. Instead of LIST text there is NEXT text.

**Comment by nihp** [comment]
Any update

**Comment by nihp** [comment]
@iRoachie 
Here is my sample header section can I get like this. 


Note: Here I need to show the username in a line if it is large or small. If it is too large I will show it to next line

Did you get this now?

![Screenshot 2019-11-05 at 11 13 17 AM](https://user-images.githubusercontent.com/36992338/68185224-0e008280-ffc7-11e9-97a7-d9d768a1f397.png)

**Comment by iRoachie** [comment]
This should do what you described https://snack.expo.io/@roach_iam/petrified-ice-cream

**Comment by nihp** [comment]
Thanks @iRoachie
