### ISSUE TITLE
selectedIndex in ButtonGroup is delayed using React Hook useState

### ISSUE THREAD

**Issue by GianMantuan** [react-native-elements/react-native-elements#2088]
**Explain what you did**
So, I'm trying to change the selectedIndex in a ButtonGroup to fetch some data in my API, but the index in the useState is delayed.

**Expected behaviour**
As you change the index of the ButtonGroup, it calls a API that fetch some data based on the value of the index

**Describe the bug**
The index is delayed, so the index in the useState is behind compared to the event onPress.

**To Reproduce**
```bash
const [index, setIndex] = useState(null);

[ . . . ]

        <ButtonGroup
          onPress={i => {
            console.log(`SelectedI -> ${i}`);
            setIndex(i);
            console.log(`useStateI -> ${index}`);
          }}
          selectedIndex={index}
          buttons={[
            {
              element: () => (
                <View style={styles.ButtonGroupStyle}>
                  <Icon name="ios-school" color="#015880" size={30} />
                  <Text style={styles.TagTextStyle}>Button 1</Text>
                </View>
              ),
            },
            {
              element: () => (
                <View style={styles.ButtonGroupStyle}>
                  <Icon name="ios-school" color="#015880" size={30} />
                  <Text style={styles.TagTextStyle}>Button 2</Text>
                </View>
              ),
            },
          ]}
          containerStyle={styles.TagItemStyle}
          selectedButtonStyle={styles.TagItemSelectedStyle}
          selectedTextStyle={styles.TagTextStyle}
        />

```

**Screenshots**
![Screen Shot 2019-09-26 at 09 30 23](https://user-images.githubusercontent.com/28939811/65688501-a22f0f80-e041-11e9-9164-9cb393575b79.png)

| software              | version |
| --------------------- | ------- |
| react-native-elements | 1.2.1 | 
| react-native          | 0.60.5 |
| yarn           | 1.17.3 |

**Comment by iRoachie** [comment]
Using hooks has no effect on the responsiveness of the ButtonGroup. See https://snack.expo.io/@roach_iam/frisky-juice-box. You may need to look into optimizing your code

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
