### ISSUE TITLE
Input: Change inputComponent to InputComponent

### ISSUE THREAD

**Issue by iRoachie** [react-native-elements/react-native-elements#2089]
This is to standardize the props for all component that accept components (e.g. ViewComponent for Button).

This is a breaking change.

Change can be made here https://github.com/react-native-training/react-native-elements/blob/next/src/input/Input.js#L167

**Comment by jatinAroraGit** [comment]
Hey there,
I would like to work on this.
Can you assign this to me please ?
Thanks.

**Comment by iRoachie** [comment]
Sure thing go ahead! Make your change against the `next` branch

**Comment by iRoachie** [comment]
@jatinAroraGit Still interested in working on this?
