### ISSUE TITLE
Applying flex:1 to buttonStyle is "compressing" button in iOS

### ISSUE THREAD

**Issue by ATClemente** [react-native-elements/react-native-elements#2098]
**Explain what you did**
I had a button that I wanted to fill a view. I added flex: 1  to the button container which worked to make the container the size of the view but when I added flex: 1 to the buttonStyle itself, the button compresses to an extremely thin size and the text disappears but only on iOS. On Android the button expands to fill the view.

**Expected behaviour**
The behavior that occurs in Android which is the button expands to fill the container and the text is visible.

**Describe the bug**
Adding flex:1 to a buttonStyle under the conditions I am using seems to produce different behavior between Android and iOS

**To Reproduce**
Snack reproducing issue here: https://snack.expo.io/SyDP_vZdB

I have "color coded" the button as blue and its container as red to better illustrate what is occurring.

# Steps
1. Run snack on Android. Observer expected and desired behavior. Note that no red appears since the button is filling its container
2. Run snack on iOS. Observe thin button along top with no text displaying. Notice the size of button and its container which fills the screen
3. Remove or comment out the "flex:1" on the "searchButton" style.
4. Observe now both Android and iOS look the same but the button does not fill the container

**Possible Solution**

**Screenshots**

Android without flex:1
![androidWithoutFlex1cropped](https://user-images.githubusercontent.com/26755083/66008861-3c4de800-e486-11e9-88b6-c02ec23e1417.png)

iOS without flex:1
![iosWithOutFlex1cropped](https://user-images.githubusercontent.com/26755083/66008913-55ef2f80-e486-11e9-91a9-604348afcb49.png)

Android with flex:1
![androidWithFlex1Cropped](https://user-images.githubusercontent.com/26755083/66008941-67383c00-e486-11e9-9234-19f0598cdde2.png)

iOS with flex:1
![iosWithFlex1cropped](https://user-images.githubusercontent.com/26755083/66008948-70c1a400-e486-11e9-9759-bfb3100c9471.png)

Disregard the bit of stretching in the screenshot for iOS. I was running on a tablet. But as snack confirms this happens on a phone device as well.

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements | 1.1.0        |
| react-native          | 0.59 (Expo SDK v35.0)        |
| npm or yarn           | 6.9.0        |

**Comment by flyingcircle** [comment]
@ATClemente 
Testing with Expo 37 and RNE 2.0.0
This has to do with the difference of how the `Button` Component uses different `TouchableComponents` for iOS and Android. These are giving different behaviors (and maybe they shouldn't, but that is on react-native) But to work around that you can fix this by passing `flex:1` to the `style`, `buttonStyle`, and `containerStyle` props. `style` is being passed to the `TouchableComponent`, so any differences you continue to see between Android and iOS will likely require changes there. Hope this helps!
