### ISSUE TITLE
Keyboard disappears in searchbar component

### ISSUE THREAD

**Issue by codermug** [react-native-elements/react-native-elements#2102]
Hi, 
I'm using version 1.2.4 SearchBar component but when i use it in android device the keyboard disappears after every key input!
here is my code:
`const [searchBrand, setSearchBrand] = useState('');`
`const  searchFilterFunction = text => {    
                 setSearchBrand(text);
      };`
`const renderHeader = () => {    
        return (      
          <SearchBar        
          placeholder="Type Here..."
          onChangeText={searchFilterFunction}
          value={searchBrand}
          />    
        );  
      };`

**Comment by iRoachie** [comment]
Can't replicate this https://snack.expo.io/@roach_iam/sadistic-cake

**Comment by codermug** [comment]
Thank you, the issue caused because i used  <SearchBar> inside Flatlist headercomponent prop

`  <FlatList ListHeaderComponent={renderHeader}..... `

but when i used it outside the component it works properly.

`<View style={styles.container}>
       <SearchBar        
          placeholder="Type Here..."
          onChangeText={searchFilterFunction}
          value={searchBrand}
          clearIcon={null}          
           />   
            <FlatList  data={brandsData}   renderItem={({item}) => <RenderSingleItem item={item} />} />
        </View>`

**Comment by iRoachie** [comment]
Can you create an example with the FlatList on https://snack.expo.io that reproduces this?

**Comment by iRoachie** [comment]
Your example works fine for me on both iOS and Android

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Comment by Foxxiblak** [comment]
It still doesn't work if SearchBar is added to the Header of the FlatList
example:

`
    const [search, setSearch] = useState("");

    function updateSearch(value = ""):void {
        setSearch(value)
    }

    const onClearSearch = () => {
        setSearch('');
    }

    const renderHeader = () => {
        return (
            <SearchBar
                placeholder={"Text ..."}
                placeholderTextColor={"#808080"}
                onChangeText={updateSearch}
                onClear={() => onClearSearch()}
                value={search}
                containerStyle={styles.searchContainer}
                inputContainerStyle={ styles.inputContainer }
                inputStyle={styles.searchInput}
            />
        )
    }

    return (
        <View style={styles.container}>
            <FlatList
                data={[]}
                renderItem={({item}) => renderItem(item)}
                ListHeaderComponent={renderHeader}
                showsVerticalScrollIndicator={false}
                keyExtractor={(item, index) => (item + index).toString()}
            />
        </View>
    );`

**Comment by gaurav712** [comment]
I am facing the same issue. @codermug Could you ever find a solution to this? I can't move it out of the flatlist like how you resolved it.
