### ISSUE TITLE
Button Accessibility Issue, call onPress with enter key

### ISSUE THREAD

**Issue by AllanLa** [react-native-elements/react-native-elements#2103]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).
-react native version 0.59.9
**Explain what you did**
get onPress to be called with "enter" key from keyboard for accessibility issues

**Expected behaviour**
Enter Key from keyboard will call onPress function

**Describe the bug**
Does not call 
**To Reproduce**
We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:
Use the component, tab to it using a keyboard, and press enter . Does not actually "press" the button

Example:

```bash
# Snack
https://snack.expo.io/xxx

# Steps
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```
![image](https://user-images.githubusercontent.com/15465741/66154805-24d04580-e5d3-11e9-8ad6-4182bd689ef5.png)

**Possible Solution**
Can you suggest a possible fix that would address this issue?

**Screenshots**

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |         |
| react-native          |         |
| npm or yarn           |         |

**Comment by iRoachie** [comment]
Can you provide an example?

**Comment by AllanLa** [comment]
https://snack.expo.io/SJ4djR7_S , any basic example is just have a react native button, tab to it using the keyboard (not a phone keyboard, like a computer keyboard) and pressing the "enter" key . OnPress not called

**Comment by iRoachie** [comment]
So you're talking about react-native-web then?

**Comment by iRoachie** [comment]
In your snack you were importing from Button from react-native-paoer instead of react-native-elements.

Here you can see that the button works fine https://snack.expo.io/@roach_iam/healthy-sandwich
