### ISSUE TITLE
Moved to a new Github Org

### ISSUE THREAD

**Issue by iRoachie** [react-native-elements/react-native-elements#2108]
Today we moved the react-native-elements repo into its own Github organization. This is a move that allows us to have all our projects under a single place.

If you are having any issues accessing the docs, please note that they are available at a new URL https://react-native-elements.github.io/react-native-elements/.

Thanks 🙏

**Comment by darknblack** [comment]
I'm about to report an issue about it (error 404), glad you mention it here. 
Thank you and great work 👍 💯

**Comment by darknblack** [comment]
The search result from the new website still points to the old website.

**Comment by iRoachie** [comment]
As soon as permissions are updated, will redeploy the website fixing the search

**Comment by ivnnv** [comment]
Yes please make an update so the old site redirects 1-1 to the new one because all google results are giving 404s.

**Comment by iRoachie** [comment]
It's a lot harder to do that, as github repo transfers don't update links to github sites. Currently doing a workaround with redirects https://github.com/react-native-training/react-native-elements

**Comment by ivnnv** [comment]
I just checked doing a quick "react native elements button" google search and seems to work with the stub repo, at least with the actual version.
Thanks for fixing it that fast @iRoachie !

**Comment by iRoachie** [comment]
Awesome. Very sorry about this inconvenience, URLs should never ever break. We didn't foresee this happening.
