### ISSUE TITLE
ListItem: Add a "disabled" prop for every style prop

### ISSUE THREAD

**Issue by Barbiero** [react-native-elements/react-native-elements#2111]
**Is your feature request related to a problem? Please Describe.**

Currently there's no way to style a title, container etc.. according to `disabled` status unless we use the disabled status itself on the styling, eg:

```jsx
              <ListItem
                leftIcon={{ name: 'autorenew' }}
                titleStyle={{ color: resetModuleEnabled ? 'white' : 'grey' }}
                title={translate('screens.settings.reset')}
                disabled={!resetModuleEnabled}
                onPress={sendReset}
              />
```

Here I'm changing `titleStyle` according to `resetModuleEnabled`; but I'd rather there be some way to pass the disabled title style similar to how `disabledStyle` works for the listitem itself.

While the current solution *works*, it means I can't use `ThemeProvider` to globally set the disabled text style.

**Describe the solution you'd like**

I'd like to pass an alternative set of styles according to disabled status for *every* part of the component. either this:

```jsx
<ListItem {...} titleStyle={{color: 'white', disabledStyle: {color: 'grey'} }} />
```

or this:

```jsx
<ListItem ... titleStyle={{color:'white'}} disabledStyles={{title: {color: 'grey'} }} />
```

Note that the current `disabledStyle` works only for the underlying view component, but I'd like to have a way to style every sub-part of a ListItem(ie. the container, the right/left icons, title & subtitle etc), and so I'd be able to use `ThemeProvider` to determine how a disabled ListItem should behave

**Describe alternatives you've considered**

right now I'm passing the disabled property to determine the styling, but IMO that's not ideal.

**Comment by iRoachie** [comment]
In what case would the ListItem be in a disabled state?

**Comment by Barbiero** [comment]
in my particular case, ListItem works well for a settings screen but sometimes depending on what the user is doing, some settings might not be available - in particular, when his device is not paired to an external peripheral, I disable the "reset peripheral" button.

**Comment by iRoachie** [comment]
Ahh gotcha, sounds like a good idea.

**Comment by ganes1410** [comment]
@iRoachie Can i work on this if no one else started yet.

**Comment by flyingcircle** [comment]
There might be a prettier way to do this, but I was able to code up a dirty themed ListItem with disabled as a prop:

```js
let MyList = (props) => {
  const {theme, titleStyle, linearGradientProps, subtitleStyle, disabled, ...rest} = props;
  if (disabled && linearGradientProps) {
    linearGradientProps.colors = theme.ListItem.disabled.linearGradientProps.color;
  }
  return (
  <ListItem
    titleStyle={[
        titleStyle,
        disabled && theme.ListItem.disabled.titleStyle,]}
    subtitleStyle={[
      subtitleStyle,
      disabled && theme.ListItem.disabled.subtitleStyle
    ]}
    linearGradientProps={linearGradientProps}
    {...rest}
  />);
};
```

So I would say that we not add this as a feature. I think you could imagine a number of ways that someone might want a 'disabled' prop implemented or styled differently depending on their needs (they'd end up having to build this kind of component anyways to work around the default disabled settings)
And there are whole host of alternative props that people could want. A 'focused' prop or a 'selected' prop. And you can build your custom props to be compatible with theming to boot on top of that.
