### ISSUE TITLE
reverse icon have a transparent background instead of a white background RN 0.61.1

### ISSUE THREAD

**Issue by cesar3030** [react-native-elements/react-native-elements#2115]
**Explain what you did**
Floating Icons on the bottom right of the screen

**Expected behaviour**
Icons should be gray and have a white circular background.

**Describe the bug**
On Android (device and emulator) the `reverse=true` icons should have a white background but they are transparent instead.

**To Reproduce**
Icons:
```javascript
<View style={styles.mapMenuContainer}>
          <Icon
            reverse
            raised
            name="map-marker-plus"
            type="material-community"
            color="white"
            size={25}
            reverseColor="gray"
            onPress={this._handleCreateBtnPress}
          />
          <Icon
            reverse
            raised
            name="map-search-outline"
            type="material-community"
            color="white"
            size={32}
            iconStyle={styles.filterIconStyle}
            reverseColor="gray"
            onPress={this._handleFilterBtnPress}
          />
</View>
```
View style:
```
mapMenuContainer: {
    position: 'absolute',
    bottom: '3%',
    right: '2%',
    alignItems: 'center',
    zIndex: 1,
}
```

React Native Elements Theme:
```
Icon: {
    underlayColor: 'transparent',
    type: 'ionicon',
},
```
This is totally random, sometimes it appears transparent and after killing the app and reopen it, it appears with a white background.

**Possible Solution**
no idea but I think this is related to `position: absolute`. This issue started after I upgraded react-native from **0.60.5** to **0.61.1**

**Screenshots**
Working example:
<img width="95" alt="Screen Shot 2019-10-06 at 12 52 40 AM" src="https://user-images.githubusercontent.com/3688337/66271198-4165bb00-e829-11e9-873e-6a907b73cac7.png">

Not working example: 
<img width="121" alt="Screen Shot 2019-10-06 at 12 48 23 AM" src="https://user-images.githubusercontent.com/3688337/66271205-4fb3d700-e829-11e9-8937-42de810768a6.png">

**Environment:**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     1.2.0    |
| react-native          |    0.61.1     |
| npm or yarn           |     1.15.2    |

**Comment by iRoachie** [comment]
This is a bug in react-native 0.61.1, upgrade to 0.61.2 should fix. See https://github.com/facebook/react-native/issues/26544

**Comment by cesar3030** [comment]
Thank you very much! it upgrading to 0.61.2 seems to fix the issue!
