### ISSUE TITLE
how to make Tooltip adapte on text size?

### ISSUE THREAD

**Issue by medmo7** [react-native-elements/react-native-elements#2118]
**Explain what you did**
Use Tooltip on a text component 

**Expected behaviour**
Tooltip should be dynamic depending on text size

**Describe the bug**
Tooltip size dont change depending on text, and long text are cut 

**To Reproduce**
# Snack

https://snack.expo.io/SJJTv5__B

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  1.2.0       |
| react-native          |    0.60.3     |
| npm       |     6.10.3    |

**Comment by tingzhouu** [comment]
I faced the same issue when using Tooltip, here's a summary of how i created a custom component to get around it.

1. Assume a fixed width for the popover, so we only need to vary the height.
2. The custom component takes in the prop tooltipText and creates a View, containing tooltipText, which is hidden.
3. Using the [onLayout](https://facebook.github.io/react-native/docs/view#onlayout) prop, it stores the height of the View in the state.
4. Pass stored height as a prop to Tooltip component.

Snack: https://snack.expo.io/@tingzhou/rn-rne-tooltip
Github: https://github.com/tingzhouu/rn-rne-tooltip

**Comment by zmnv** [comment]
Still Nothing? 

There are in gif of https://react-native-elements.github.io/react-native-elements/docs/tooltip.html#toggleonpress.

HOW TO DO HUDGE?

**Comment by bgfernandes** [comment]
After some time trying to figure this out, I managed to do a somewhat autosize tooltip button that receives a content element as a prop (`tooltip`) and resizes itself based on its content, following more or less what @tingzhouu mentioned on his post.

The only way I got it to work properly was to set an initial size bigger than the content (500x500) and add more size to it (+30).

```
export default function ToolTipButton({ tooltip }) {
  const [tooltipSize, setTooltipSize] = useState({ w: 500, h: 500 })

  const tooltipClone = React.cloneElement(
    tooltip,
    { onLayout: (e) => setTooltipSize({ w: e.nativeEvent.layout.width, h: e.nativeEvent.layout.height }) }
  )

  return (
    <Tooltip popover={tooltipClone} width={tooltipSize.w + 30} height={tooltipSize.h + 30}>
      <Container>
        <Icon>?</Icon>
      </Container>
    </Tooltip>
  )
}
```

**Comment by flyingcircle** [comment]
Thanks @bgfernandes for a solution. Let me know if this ticket still needs to remain open.
