### ISSUE TITLE
Icon: iconStyle has mismatching types

### ISSUE THREAD

**Issue by Naturalclar** [react-native-elements/react-native-elements#2120]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-elements.github.io/react-native-elements/versions.html).

**Explain what you did**
What you were trying to accomplish.

Trying to apply `iconStyle` to Icon component while using typescript.

`iconStyle` contains `color` property, which is not available in `ViewStyle`, but the `Icon` component (which comes from react-native-vector-icons) is wrapped in `Text` component which expects `TextStyle`

**Expected behaviour**
specifying `iconStyle` with `color` property not giving type error

**Describe the bug**
specifying `iconStyle` with `color` property not giving type error

**To Reproduce**
We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

```tsx
import React from 'react'
import { StyleSheet } from 'react-native'
import { Icons } from 'react-native-elements'

const styles = StyleSheet.create({
  iconStyle : {
    color: 'white'
  }
})

const Icon: React.FC<{}> = () => <Icon name="..." type="..." iconStyle={styles.iconStyle} />

```

**Possible Solution**
Can you suggest a possible fix that would address this issue?
Upgrade `@types/react-native-vector-icons` to `6.4.3` or higher, which has fixed typings for `iconStyle` in `react-native-vector-icons`

**Screenshots**

<img width="546" alt="Screen Shot 2019-10-07 at 11 36 25 PM" src="https://user-images.githubusercontent.com/6936373/66321481-9ace0700-e95b-11e9-89cf-c59199618909.png">
<img width="493" alt="Screen Shot 2019-10-07 at 11 36 33 PM" src="https://user-images.githubusercontent.com/6936373/66321483-9ace0700-e95b-11e9-8616-2f01d29c8644.png">

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.2.5     |
| react-native          |    expo sdk34     |
| npm or yarn           |     yarn    |

**Comment by iRoachie** [comment]
This is strange, are you sure you're importing Icon from 'react-native-elements'. I just tried the same with a new expo project and got no errors.

```jsx
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Icon } from 'react-native-elements';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.tsx to start working on your app!</Text>

      <Icon name="home" iconStyle={styles.iconStyle} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconStyle: {
    color: 'white',
  },
});
```

Also when i hover over `iconStyle` it's a `TextStyle`
![image](https://user-images.githubusercontent.com/5962998/66322640-725cf300-e8f0-11e9-9cb4-4ca5c859436f.png)

**Comment by Naturalclar** [comment]
This is the code that's using `Icon`, which is importing from `react-native-elements`.

```
import * as React from "react";
import { StyleSheet } from "react-native";
import { Icon, IconType } from "react-native-elements";
import Colors from "../constants/Colors";

const styles = StyleSheet.create({
  container: {
    height: 16,
    width: 16,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8
  },
  icon: {
    color: Colors.white
  }
});

type Props = {
  icon: string;
  type?: IconType;
  color?: string;
};

export const Badge = ({ icon, type = "material", color = "blue" }: Props) => (
  <Icon
    name={icon}
    type={type}
    size={10}
    iconStyle={styles.icon}
    containerStyle={[styles.container, { backgroundColor: color }]}
  />
);
```

But I get the issue here. If you start a brand-new expo project, then you start out without `yarn.lock`, so yarn will install the latest `@types/react-native-vector-icons`, since inside the `package.json` of `react-native-elements`, `@types/react-native-vector-icons` is listed as `^6.4.1` with a hat(`^`), which will result in `6.4.5` (current latest) without a `yarn.lock` according to semver.

I'll fix my `yarn.lock` in my project and that should do the work for me.

**Comment by iRoachie** [comment]
Ohhh I see, I found the PR that changed it https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38639. Let's just update the version in your PR then

**Comment by Naturalclar** [comment]
Sounds good! I've moved the `@types/react-native-vector-icons` back to `dependencies` in my PR #2119
