### ISSUE TITLE
Update Contributing guidelines

### ISSUE THREAD

**Issue by iRoachie** [react-native-elements/react-native-elements#2121]
We've recently updated our github workflow to have 3 branches:

`master` - current version on npm that's live
`next` - upcoming features and changes
`patch` - bug fixes (usually released within a day)

We should update the contributing section on the website and maybe .github/CONTRIBUTING.md to let users know which branch they should base their changes on if they want to make a pull request.

**Comment by atrimn** [comment]
That would be master correct? @iRoachie

**Comment by iRoachie** [comment]
Yes this will PR will need to be based from the master branch

**Comment by atrimn** [comment]
> Yes this will PR will need to be based from the master branch

I submitted a PR for this
https://github.com/react-native-elements/react-native-elements/pull/2130
