### ISSUE TITLE
Tooltip: Icon and pointer shown at the wrong place when using RTL and showing the tooltip

### ISSUE THREAD

**Issue by msevestre** [react-native-elements/react-native-elements#2125]
Using version 1.1

**Explain what you did**
Create a view using the Tooltip component. Sets the RTL to true `I18nManager.forceRTL(true)`

The tooltip icon is positioned on the top right of the view as on screenshot below.
When using RTL, react-native does its magic and flip the whole UI. The tooltip icon is then on on the top left of the screen as expecetd

**Expected behaviour**
When using RTL, I am expected the tooltip icon to be on the left when the tooltip is visible. It is not the case. For some reasons, it flips back to it's non-RTL position

**Describe the bug**
Everything works great with the tooltip component until I set the RTL property to true in the I18nManager. 

Example: 

* Using a non-RTL Language (English)

Everyting works as expected. Tooltip icon is on the left
![image](https://user-images.githubusercontent.com/1041237/66584368-075f2680-eb53-11e9-8bbc-f0a2660291eb.png)

* Using an RTL Language such as Arabic or Hebrew (the text is not translated fully but it does not matter for this problem)

![image](https://user-images.githubusercontent.com/1041237/66584715-a2580080-eb53-11e9-994b-f83d749fb7bd.png)

![image](https://user-images.githubusercontent.com/1041237/66584575-6329af80-eb53-11e9-91d3-db9c20421bde.png)

You can see that the actual tooltip icon in on the left. But when toggling the tooltip, it is suddenly on the right again. The same goes with the pointer that is also not located at the expected position

**To Reproduce**
Set RTL to true on any example using the tooltip (provided that the tooltip is not centered) and you should be able to reproduce

**Comment by bikashsahucbnits** [comment]
The tooltip element is not working properly on the Web.
used toggleTooltips method as mentioned in Docs... But it not working properly in the Web environment only...Anyhow, its working fine with Mobile devices.
<Tooltip
  ref={tooltipRef}
  ...
/>
useEffect(() => {
  tooltipRef.current.toggleTooltip();
}, []);

**Comment by YraZinchenko** [comment]
1.2.0 version and have this problem

**Comment by abhigna-shah** [comment]
PR generated having fix for RTL support.
https://github.com/react-native-elements/react-native-elements/pull/2319

@iRoachie can you please review and check the same?

It has that pointer misplacement positioning UI issue fixed:
https://github.com/react-native-elements/react-native-elements/pull/2158
