### ISSUE TITLE
Not working with react-native-snackbar-component: fontFamily "space-mono" is not a system font and has not been loaded through Font.loadAsync.

### ISSUE THREAD

**Issue by 5ervant** [react-native-elements/react-native-elements#2127]
My `react-native-elements` version is **"^1.2.6"** and I'm using `expo` **"^35.0.0"**. I'm seeing this error on my Android emulator upon using `react-native-snackbar-component`, no problem when viewing my application on the web:

    fontFamily "space-mono" is not a system font and has not been loaded through Font.loadAsync.
    
    - If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.
    - If this is a custom font, be sure to load it with Font.loadAsync.
    - node_modules\react-native\Libraries\YellowBox\YellowBox.js:59:8 in error
    - node_modules\expo\build\environment\muteWarnings.fx.js:27:24 in error
    - ... 33 more stack frames from framework internals

It seems the `fontFamily` error starts to appear upon installing `react-native-snackbar-component`. It have a conflict with `react-native-elements`' `<Header />` component. The error is gone upon reinstalling `react-native-elements` **alone**, but came back upon installing `react-native-snackbar-component`. https://github.com/SiDevesh/React-Native-SnackBar-Component/issues/37

**Any solution to make it work with `react-native-snackbar-component`?** I tried running both of these but nothing seems to work, it will just change the problem to `fontFamily "material"`:
 - `npm install --save-dev react-native-vector-icons` [stackoverflow.com/a/49188160/2007055](https://stackoverflow.com/a/49188160/2007055)
 - `npm i react-native-vector-icons --save` https://github.com/react-native-elements/react-native-elements/issues/1986#issuecomment-517211882

**Comment by iRoachie** [comment]
We don't use "space-mono" font in react-native-elements, and neither does react-native-snackbar-component. 

I'm assuming this error is coming from another package you are using or in your code. Here's an example of the two packages working without any problems https://snack.expo.io/@roach_iam/intrigued-tortilla

**Comment by 5ervant** [comment]
My `<Header />` contains this `leftComponent`:

    <Header
      leftComponent={{ icon: 'menu', color: '#fff' }}

The _"burger menu"_ icon is appearing unformatted on my Android emulator *(but appearing well on the web)* when `react-native-snackbar-component` is installed.

I'm quite amazed why the _"burger menu"_ icon's showing well on Snack's Android view. I've used the boilerplate _"tabs"_ of Managed workflow on the creation of my application.

**Comment by 5ervant** [comment]
It's literally an issue while you install `react-native-snackbar-component` with Expo. I'm using Yarn, so I'd solved the problem by running these after installing `react-native-snackbar-component`:
```
yarn
expo r -c
```
