### ISSUE TITLE
alignItems: 'baseline' crashes app

### ISSUE THREAD

**Issue by MikeMajara** [react-native-elements/react-native-elements#2134]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-elements.github.io/react-native-elements/versions.html).

**Explain what you did**
Aligning Icons to text in a `flexDirection: 'row'` with `alignItems: 'baseline'`

**Expected behaviour**
That the icons remain aligned to the baseline together with the text.

**Describe the bug**
Whenever `alignItems: 'baseline'` is applied as style to the parent view containing Icons. The app crashes.

**To Reproduce**
[Reproduced in snack](https://snack.expo.io/S1K5kXGFH). No need to go nowhere app crashes as soon as opened. To check difference change `alignItems: 'baseline'` → `alignItems: 'center'`

**Possible Solution**
No idea how this even happens.

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   1.2.6      |
| react-native          |    0.61.2     |
| yarn           |   1.19.1      |
| npm | 6.9.0

**Comment by iRoachie** [comment]
This is such a weird bug. I have no idea

**Comment by BatDroid** [comment]
I traced this bug and turns out the problem is with [this line](https://github.com/react-native-elements/react-native-elements/blob/64315d6469cc34b67393e8c192d581118ed341c0/src/icons/Icon.js#L53). when i comment this line there is no crash. this style becomes visible when the `reversed` prop is true. As I don't want to remove this line, I'm afraid i can't do anything. I would have used `react-native-vector-icons` directly for this issue if i were you.

**Comment by flyingcircle** [comment]
I was able to work around this crash by adding `flex:1` to the container that had the `alignItems:baseline` in it. Not sure what's causing the crash, but hopefully this is a satisfactory answer for anyone running into this.

**Comment by ctwillie** [comment]
I think I am experiencing the same bug with ```flexDirection: 'row'``` and ```justifyContent: 'space-between'```. Really strange.

**Comment by Ahmedhamed77** [comment]
I have the same issue, any solutions ?

**Comment by Lewitje** [comment]
Same issue here, crashes on launch but not on hot reload:
`flexDirection: 'row',
  alignItems: 'baseline',
  justifyContent: 'space-between'`
If I change baseline to center it works

**Comment by mclrc** [comment]
I have run into this issue multiple times now over the past six months, that seemingly random combinations of views and flex properties instantly crash the ShadowQueue when mounted, but not during hot reload. Is anyone else still experiencing this?

Excerpt from the crash dump:
```
Thread 20 Crashed::  Dispatch queue: com.facebook.react.ShadowQueue
0   libsystem_kernel.dylib        	       0x1078c09ec __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x107ab71d0 pthread_kill + 256
2   libsystem_c.dylib             	       0x1801605cc abort + 104
3   libc++abi.dylib               	       0x18028ec78 abort_message + 128
4   libc++abi.dylib               	       0x18028e15c std::__terminate(void (*)()) + 24
5   libc++abi.dylib               	       0x18028e100 std::terminate() + 52
6   libdispatch.dylib             	       0x18016cd50 _dispatch_client_callout + 36
7   libdispatch.dylib             	       0x180174e3c _dispatch_lane_serial_drain + 960
8   libdispatch.dylib             	       0x1801759b4 _dispatch_lane_invoke + 388
9   libdispatch.dylib             	       0x180180d40 _dispatch_root_queue_drain_deferred_wlh + 276
10  libdispatch.dylib             	       0x18018038c _dispatch_workloop_worker_thread + 448
11  libsystem_pthread.dylib       	       0x107ab3924 _pthread_wqthread + 284
12  libsystem_pthread.dylib       	       0x107ab26e4 start_wqthread + 8

Thread 21:
0   libsystem_pthread.dylib       	       0x107ab26dc start_wqthread + 0

Thread 22:
0   libsystem_pthread.dylib       	       0x107ab26dc start_wqthread + 0


Thread 20 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000180292ce2   x5: 0x000000016bfba860   x6: 0x0000000000000064   x7: 0x0000000000000000
    x8: 0x000000016bfbb000   x9: 0x92cc775ae8119f4d  x10: 0x0000000000000200  x11: 0x000000016bfba390
   x12: 0x0000600000003db0  x13: 0x00000000001ff800  x14: 0x0000000000000010  x15: 0x00000000e1033073
   x16: 0x0000000000000148  x17: 0x00000000e1232814  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x000000016bfbb000  x21: 0x0000000000008e07  x22: 0x000000016bfbb0e0  x23: 0x0000000000000000
   x24: 0x0000600002c1df68  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x00006000018b5c00
   x28: 0x0000000000000000   fp: 0x000000016bfba7d0   lr: 0x0000000107ab71d0
    sp: 0x000000016bfba7b0   pc: 0x00000001078c09ec cpsr: 0x40001000
   far: 0x0000000000000000  esr: 0x56000080  Address size fault
```
