### ISSUE TITLE
Is it possible to make the title for a ListItem component multiline?

### ISSUE THREAD

**Issue by dmargu** [react-native-elements/react-native-elements#2136]
I have been trying to see if I can make my title multiline. I have a right component currently so sometimes if the title text is long it gets cut off. I need the user to be able to see the entire title and it's completely fine if it makes the listItem bigger and wraps down. 

I assume there's a way to do this but I have not been able to figure it out. I have tried making the title a text component instead of just a string but that leads to the same issue.

**Comment by iRoachie** [comment]
I can't seem to replicate this. The title wraps by default.
![Simulator Screen Shot - iPhone 11 - 2019-10-14 at 14 19 46](https://user-images.githubusercontent.com/5962998/66773747-bb331f80-ee8d-11e9-8023-d2bfc960008f.png)

https://snack.expo.io/@roach_iam/humiliated-fudge

**Comment by dmargu** [comment]
I hard-coded a height to the list item. It started working right when I got rid of it. Sorry for wasting your time, thanks for the help.

**Comment by iRoachie** [comment]
It's okay! Definitely not a waste of my time. Everyone has those days. Get back up and go! 💪

**Comment by vhesener** [comment]
> I hard-coded a height to the list item. It started working right when I got rid of it. Sorry for wasting your time, thanks for the help.

This saved me time, actually. Thanks! I did the same thing and found your issue while searching.
