### ISSUE TITLE
showReadOnlyText is missing / not working

### ISSUE THREAD

**Issue by kuyapete** [react-native-elements/react-native-elements#2140]
I was using the rating component, And I only need to display it as a readonly. When I use the prop showReadOnlyText with a value of false, the readonly text is still showing?

**Expected behaviour**
'(readonly)' text should be not displayed

**Possible Solution**
Workaround is to make a customized showRating text instead of using its props.

**Screenshots**
![image](https://user-images.githubusercontent.com/25590365/66955544-26027780-f095-11e9-8018-da1760bfb688.png)
![image](https://user-images.githubusercontent.com/25590365/66955558-3155a300-f095-11e9-8750-1f8d80a87def.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  ^1.2.3       |
| react-native          |   0.61.1      |
| npm or yarn           |    6.11.3     |

**Comment by iRoachie** [comment]
Seems like this feature has been removed or never was there and the docs are incorrect. @Monte9 is this something you want to add?

**Comment by iRoachie** [comment]
Yes this was removed in 1.0.0 https://github.com/react-native-elements/react-native-elements/pull/1671. I updated the docs.

**Comment by kuyapete** [comment]
@iRoachie Okay thanks.
