### ISSUE TITLE
Disable onPress when button is loading

### ISSUE THREAD

**Issue by imcvampire** [react-native-elements/react-native-elements#2141]
**Is your feature request related to a problem? Please Describe.**
Normally, a `loading = true` means there is a pending state. A button on loading state shouldn't pressable 

**Describe the solution you'd like**
`Button` will check `loading` prop before call `onPress`. If `loading = false`, it will call `onPress`

**Describe alternatives you've considered**

**Additional context**

**Comment by iRoachie** [comment]
Hey, I'll do some UX research on this and get back to you. I don't see this behaviour in other UI libraries, but i'll do some checking around

**Comment by imcvampire** [comment]
Thank you!

I find some UI lib that implements my suggestion:

https://github.com/ant-design/ant-design/blob/cd6ff75ab2848d515b05c33b21e395c896d98242/components/button/button.tsx#L184
https://github.com/ElemeFE/element/blob/2830c0478331543ff51951cad349d66170fd0120/packages/button/src/button.vue#L5

Btw, if you are okay, I can help to implement that feature too!

**Comment by atrimn** [comment]
If I could throw in my 2 cents I feel like that should be up to the developer to handle.

Your onPress function should have knowledge of the loading state and execute accordingly. As far as implementing this in the library I don’t see it being a bad thing but definitely not necessary IMO.

**Comment by iRoachie** [comment]
Yea I definitely understand the use case. I'm just wondering what's the best way to deal with it UX wise, see discussion here https://twitter.com/roach_iam/status/1185178868568731649

**Comment by imcvampire** [comment]
@atrimn yes, it could be up to developers. But let think about how many time you need to check `loading` on your `onPress` function? 

In my experience, it's all the time. So why don't follow other packages to implement that feature

**Comment by iRoachie** [comment]
Okay based on the discussion it seems that loading and disabled should be 2 separate states, and we shouldn't have to combine disabled + loading together to show a loading state.

**Comment by iRoachie** [comment]
Merged! Thanks, everyone 💯
