### ISSUE TITLE
The tooltip element is not working properly on the Web.

### ISSUE THREAD

**Issue by bikashsahucbnits** [react-native-elements/react-native-elements#2149]
The tooltip element is not working properly on the Web.
used toggleTooltips method as mentioned in Docs... But it not working properly in the Web environment only...Anyhow, its working fine with Mobile devices.
<Tooltip
ref={tooltipRef}
...
/>
useEffect(() => {
tooltipRef.current.toggleTooltip();
}, []);

**Comment by iRoachie** [comment]
Yes this because it's based on Modal, and the Modal component from react-native isn't in react-native-web as yet. See https://github.com/react-native-elements/react-native-elements/issues/2083

**Comment by iRoachie** [comment]
Fixed by https://github.com/react-native-elements/react-native-elements/commit/c277ef394c864330329ab6670034edbc6b7b079d

**Comment by drixie** [comment]
Issue still persists
