### ISSUE TITLE
Bugs in normalize text algorithm

### ISSUE THREAD

**Issue by chinesedfan** [react-native-elements/react-native-elements#2153]
**Explain what you did**

Call `normalize(1)` in iPhone 5. It will return 0.95.

**Expected behavior**

It should be 1 according to the comments in source codes.

**Describe the bug**

The reason is that iPhone 5 has a 320x568 screen, which will trigger the first if statement in src/helpers/normalizeText.js.

What's more, in other cases like `pixelRatio >= 3 && pixelRatio < 3.5` and `pixelRatio >= 3.5`, the condition of the first if statement includes deviceWidth=360, but `pixelRatio >= 2 && pixelRatio < 3` does not. It looks like strange.

At last, would you mind adding tests like https://github.com/gitpoint/git-point/pull/899 for this file?

```
    // iphone 5s and older Androids
    if (deviceWidth < 360) {
      return size * 0.95;
    }

    // iphone 5
    if (deviceHeight < 667) {
      return size;
      // iphone 6-6s
    }
```

**To Reproduce**

See https://github.com/gitpoint/git-point/pull/899.

**Screenshots**

None.

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    any     |
| react-native          |    any     |

**Comment by iRoachie** [comment]
@chinesedfan Thanks for submitting this. Would you mind submitting a fix for this? You can make the PR to the `master` branch.

**Comment by flyingcircle** [comment]
I'm wondering if instead of trying to fix this rather complicated algorithm we instead change to using this library instead: https://github.com/NewBieBR/react-native-normalize thoughts? This would likely require a major revision bump though.

**Comment by flyingcircle** [comment]
I tested out a few different libraries and I think this one will be the best way to go: https://github.com/nirsky/react-native-size-matters

**Comment by pranshuchittora** [comment]
> I tested out a few different libraries and I think this one will be the best way to go: https://github.com/nirsky/react-native-size-matters

Looks interesting. Just had a look over the source code. Looks hardcore and very CPU intensive.
https://github.com/nirsky/react-native-size-matters/blob/f8dea549b87d50854eba39ce281b6e6c10f83406/lib/ScaledSheet.js#L6

But if that solves the problem then we must go ahead integrating that :)

**Comment by flyingcircle** [comment]
I don't see anything CPU intense. The only functions used are here: https://github.com/nirsky/react-native-size-matters/blob/f8dea549b87d50854eba39ce281b6e6c10f83406/lib/scaling-utils.js

**Comment by pranshuchittora** [comment]
> I don't see anything CPU intense. The only functions used are here: https://github.com/nirsky/react-native-size-matters/blob/f8dea549b87d50854eba39ce281b6e6c10f83406/lib/scaling-utils.js

IMO regex have exponential complexity.

**Comment by flyingcircle** [comment]
`ScaledSheet` is never imported or used in RNE.

**Comment by flyingcircle** [comment]
As a side note, to my knowledge regexs are only expensive when `.*` is overused and the likelyhood of the regex having to backtrack increases. That regex looks fairly straight forward and not too intense of a process. Also, that regex is only run once. If the regex was being run every time it needed to scale a number, I'd agree that that would intense.

**Comment by pranshuchittora** [comment]
@flyingcircle `react-native-size-matters` doesn't consider the pixel ration. Show which dimension to use for scaling `X` or `Y` ?
