### ISSUE TITLE
Failed prop type due to incorrect React Native version

### ISSUE THREAD

**Issue by haruelrovix** [react-native-elements/react-native-elements#2156]
**Explain what you did**

Found warnings on this build, [#3300](https://travis-ci.org/react-native-elements/react-native-elements/builds/602404014).

**Expected behavior**

No warning.

**Describe the bug**

See the Jest's log:

```
PASS src/checkbox/__tests__/CheckBox.js
  ● Console
    console.error node_modules/react/node_modules/prop-types/checkPropTypes.js:19
      Warning: Failed prop type: Invalid prop `accessibilityRole` of value `checkbox` supplied to `TouchableOpacity`, expected one of ["none","button","link","search","image","keyboardkey","text","adjustable","imagebutton","header","summary"].
          in TouchableOpacity
    console.error node_modules/react/node_modules/prop-types/checkPropTypes.js:19
      Warning: Failed prop type: Invalid prop `accessibilityStates[0]` of value `unchecked` supplied to `TouchableOpacity`, expected one of ["selected","disabled"].
          in TouchableOpacity
    console.error node_modules/react/node_modules/prop-types/checkPropTypes.js:19
      Warning: Failed prop type: Invalid prop `accessibilityStates[0]` of value `checked` supplied to `TouchableOpacity`, expected one of ["selected","disabled"].
          in TouchableOpacity
```

These warnings occurred because RNE still uses RN v0.59. Meanwhile, `accessibilityRole: checkbox` and `accessibilityStates: checked` are new in v.0.60.

Respective source code:
- https://github.com/facebook/react-native/blob/v0.59.10/Libraries/Components/View/ViewAccessibility.js#L43
- https://github.com/facebook/react-native/blob/v0.60.0/Libraries/Components/View/ViewAccessibility.js#L16

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     1.2.6    |
| react-native          |      0.59.10   |

**Comment by iRoachie** [comment]
Yes I did see this. Not sure how we should resolve this.

**Comment by haruelrovix** [comment]
@iRoachie the versioning documentation in React Native website is messed up 🤦‍♂ 

![image](https://user-images.githubusercontent.com/17120764/67630862-9c3a8180-f8c0-11e9-8234-e92f4de0f4ee.png)

The `accessibilityRole` in `0.59` should stop in `summary`. Docs in screenshot should be for `0.60` and above.

**Comment by iRoachie** [comment]
Yea i brought it up on twitter. The react native docs are out of date, but the code has the changes.

https://github.com/facebook/react-native/commit/7b35f427fd66cb0f36921b992095fe5b3c14d8b9

**Comment by techgig17** [comment]
So is there anyway to prevent this issue from coming up in ios. i am using rn elements v2.0.0 and use checkbox and on rn v 0.59.0.
