### ISSUE TITLE
image prop in Card won't accept a variable

### ISSUE THREAD

**Issue by AkalUstat** [react-native-elements/react-native-elements#2157]
I  am using the latest version of `react-native-elements` (1.2.0)
**Explain what you did**
In my project, I have all my configuration set up in a `.json` file (including image location, etc). I was trying to get the `Card` component to accept variable from its props to display the image but it just gives this error: 

`components/CourseCard.js: components/CourseCard.js:Invalid call at line 23: require("" + JSON.stringify(this.props.img))`

My code: 
`<Card
        image={require(`${JSON.stringify(this.props.img)}`)}>
            <Text style={courseCard.text}>{this.props.desc}</Text>
            <Button style={courseCard.button} title="Click!"/>
        </Card>`

**Expected behavior**

The variable would be accepted and the card would display the image from the `json` file

1. create a json file that contains the link to a local image 
2. pass it into the `Card` component's props
3. try to access that props value from the `Card`'s image property

**Screenshots**
![Screen Shot 2019-10-27 at 11 19 02 AM](https://user-images.githubusercontent.com/43657841/67639320-9b4b2500-f8ab-11e9-9158-cabf62b39aac.png)
<img width="183" alt="Screen Shot 2019-10-27 at 11 19 28 AM" src="https://user-images.githubusercontent.com/43657841/67639326-a7cf7d80-f8ab-11e9-8399-badc349ef5d4.png">

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  1.2.0       |
| react-native          |    0.62     |

**Comment by oxyii** [comment]
@AkalUstat [require](https://nodejs.org/api/modules.html#modules_require_id) is server-side method and packager follows `require` instructions while building your bundle. But `this.props` is runtime client-side object. You cannot use `require(this.props.img)` because `this.props` is not exists while building. See [here](https://github.com/facebook/metro/issues/52)

**Comment by AkalUstat** [comment]
I see. Thanks!

**Comment by AkalUstat** [comment]
Is there another way to accomplish what I need, then?

**Comment by oxyii** [comment]
As I understand it, we are talking about local images... the most obvious solution is conversion your `json` file into `js` format and change image locations to `require(<location>)`...
if your `json` has this structure
```json
{
  "course1": {
    "title": "some name",
    "desc": "some desc",
    "img": "path/to/image.png"
  },
  ...
}
```
your new `js` file will be
```js
module.exports = {
  course1: {
    title: 'some name',
    desc: 'some desc',
    img: require('path/to/image.png'),
  },
  ...
}
```

**Comment by oxyii** [comment]
@AkalUstat Let me know if this issue is still actual, I'll reopen it
