### ISSUE TITLE
buttongroup containerStyle marginHorizontal  not work

### ISSUE THREAD

**Issue by vergilw** [react-native-elements/react-native-elements#2170]
buttongroup containerStyle marginHorizontal  not work

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this?

**Comment by oxyii** [comment]
Reproduced.
@vergilw Please use `marginLeft` and `marginRight` for now.
@iRoachie `marginHorizontal` cannot override pre-defined margins
https://github.com/react-native-elements/react-native-elements/blob/c1690c20f4dd0e39779a42222341b0d7ff83d6f7/src/buttons/ButtonGroup.js#L174-L177

**Comment by oxyii** [comment]
Looks like this is veeery old issue https://github.com/facebook/react-native/issues/14587
