### ISSUE TITLE
flexWrap property not working in containerStyle of ButtonGroup

### ISSUE THREAD

**Issue by sushant023** [react-native-elements/react-native-elements#2172]
I want to render multiple buttons as buttongroup which should wrap if exceeds the container width. But giving flexWrap : "wrap" to containerStyle is not working. Any suggestions on how to achieve this?

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this?

**Comment by sushant023** [comment]
Here is the example
https://snack.expo.io/@sushant.b/buttongroup-flexwrap-example
Please note that I want the number of buttons in one row be equal to the "numCols" prop.
Trying to get the same behaviour as numColumns prop of FlatList
Thanks

**Comment by iRoachie** [comment]
I'm really not understanding this code you have. What should the final thing look like?

**Comment by sushant023** [comment]
The final thing should look like this
![buttonGroup](https://user-images.githubusercontent.com/8553818/68401593-0b0cba00-01a0-11ea-93bc-1f4a320ca0fb.png)

**Comment by iRoachie** [comment]
This isn't possible right now since it isn't possible to access the container of the button. This PR attempts to implement it https://github.com/react-native-elements/react-native-elements/issues/2172

**Comment by sushant023** [comment]
OK. Thanks for the update

**Comment by iRoachie** [comment]
Sorry realized i linked the wrong issue https://github.com/react-native-elements/react-native-elements/pull/2084

**Comment by sushant023** [comment]
Got it. Thanks again

**Comment by flyingcircle** [comment]
`buttonContainerStyle` prop is now available.
