### ISSUE TITLE
Can I show the Image and title at the same time？

### ISSUE THREAD

**Issue by asagcs** [react-native-elements/react-native-elements#2173]
I need a gradient backgroundColor，So I prepared the gradient background image, but it didn't show the title and image at the same time。
RN： 0.59.9
RNE： 1.1.0

**Comment by iRoachie** [comment]
What component are you referring to?

**Comment by asagcs** [comment]
Avatar

**Comment by asagcs** [comment]
Avatar



---Original---

**Comment by iRoachie** [comment]
There's no way to both show image and title at the same time.
