### ISSUE TITLE
undocumented attribute "activeOpacity" of component "ListItem" 

### ISSUE THREAD

**Issue by xiechao06** [react-native-elements/react-native-elements#2174]
**Explain what you did**

`ListItem` uses the attribute `activeOpacity` to control the active opacity when it is activated. But this attribute is not documented in https://react-native-elements.github.io/react-native-elements/docs/listitem.html

**Expected behavior**
this attribute should be documented

**Describe the bug**

SKIPPED

**To Reproduce**

SKIPPED

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Screenshots**

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  1.2.7  |
| react-native          | 0.61.3 |

**Comment by iRoachie** [comment]
Thanks for reporting. ListItem extends all props from TouchableHighlight. We should add a message similar to https://react-native-elements.github.io/react-native-elements/docs/button.html#props


> Also receives all [TouchableHighlight](http://facebook.github.io/react-native/docs/touchablehighlight#props-1) props

**Comment by tingzhouu** [comment]
hi! is it possible for me to try this as my first issue?

**Comment by iRoachie** [comment]
Sure! Go ahead @tingzhouu
