### ISSUE TITLE
Still needing manual linking 

### ISSUE THREAD

**Issue by dialpa** [react-native-elements/react-native-elements#2175]
**Explain what you did**
I have installed react-native-elements and react-native-vector-icons latest releases through npm and following the getting started manual

**Expected behavior**

**Describe the bug**
 it does not work properly. It appears a cross or it does not even appear.
It works when I link it manually which is  not supposed to be necessary.
Does is matter if I still use manual linking? It shows the error as stated but it seems to work fine.

**To Reproduce**

**Screenshots**

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   1.2.0      |
| react-native          |    0.62     |

**Comment by iRoachie** [comment]
Yes the problem is that react-native-vector-icons has font files (example Ionicons.ttf). So these need to be added to your project as well.

**Comment by flyingcircle** [comment]
Make sure to follow the installation directions at: https://github.com/oblador/react-native-vector-icons#installation
