### ISSUE TITLE
Avatar Background Image Flashing Grey

### ISSUE THREAD

**Issue by Sbphillips19** [react-native-elements/react-native-elements#2182]
Issue- when I type into handle change basically every time it re-renders the overlayContainerStyle every time.  I am able to switch to just image and it will never re-render, but I would like to use the avatar and edit badge.  I included a video attachment with what is going on

Versions:

"react-native-elements": "^1.2.0",
"react-native": "0.60.5",

Video of issue:

https://vimeo.com/user105102986/review/372705871/7aa951b3a3

Code:

WHERE THE ISSUES IS:

```
<Avatar
                  size="xlarge"
                  rounded
                  source={{ uri: this.state.profilePicture }}
                  showEditButton
                />
```
Full code

```
import React, { Component } from "react";
import { connect } from "react-redux";
import {
  updateProfilePhoto,
  updateUserInformation,
  loadCurrentUserProfile
} from "../../../store/profile/actions";
import { loadCurrentUser } from "../../../store/chat/actions";

import {
  Text,
  TextInput,
  View,
  SafeAreaView,
  ScrollView,
  ActivityIndicator,
} from "react-native";
import { Avatar } from "react-native-elements";
import styles from "./Styles";

class EditProfileComponent extends Component {
  constructor(props) {
    super(props);

    this.state = {
      description: this.props.currentUser.about,
      profilePicture: this.props.currentUser.profilePicture,
    };

    this.handleDescriptionChange = description => {
      this.setState({ description });
    };
  }

  componentDidMount() {
    this.props.updateProfilePhoto;
    this.props.updateUserInformation;
    this.props.loadCurrentUser;
  }

  componentDidUpdate(prevProps) {
    if (this.props.photoUrl && prevProps.photoUrl !== this.props.photoUrl) {
      this.setState({ profilePicture: this.props.photoUrl });
    }
  }

  
  render() {
    const { username, loadingProfilePicture } = this.props;
    const {
      header,
      flex1,
      safeAreaView,
      label,
      descriptionContainer,
      descriptionText,
      characterCount,
    } = styles;
    return (
      <SafeAreaView style={safeAreaView}>
        <View style={flex1}>
          <ScrollView style={flex1}>
            <View style={header}>
              {!loadingProfilePicture ? (
                <Avatar
                  size="xlarge"
                  rounded
                  source={{ uri: this.state.profilePicture }}
                  showEditButton
                />
              ) : (
                <ActivityIndicator />
              )}
              <Text style={styles.username}>{username}</Text>
            </View>
            <View style={flex1}>
              <Text style={label}>ABOUT ME:</Text>
              <View style={descriptionContainer}>
                <TextInput
                  multiline={true}
                  numberOfLines={10}
                  onChangeText={this.handleDescriptionChange}
                  value={this.state.description}
                  placeholder="Tell everyone about your riding style, 
                  favorite mountains, what makes you unique, etc.."
                  editable={true}
                  maxLength={300}
                  style={descriptionText}
                />
              </View>
              {this.state.description ? (
                <Text style={characterCount}>
                  Characters Count: {this.state.description.length}/300
                </Text>
              ) : null}
            </View>
          </ScrollView>
        </View>
      </SafeAreaView>
    );
  }
}

const mapStateToProps = state => ({
  loadingProfilePicture: state.profile.loadingProfilePicture,
  loadingProfileDescription: state.profile.loadingProfileDescription,
  currentUser: state.chat.currentUser,
  loading: state.chat.loadCurrentUser,
  photoUrl: state.profile.photoUrl,
  interests: state.profile.interests,
  currentUserProfile: state.profile.currentUserProfile
});

const mapDispatchToProps = {
  updateProfilePhoto,
  updateUserInformation,
  loadCurrentUser,
  loadCurrentUserProfile
};

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(EditProfileComponent);

```

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this?

**Comment by Sbphillips19** [comment]
I wasn't able to just bringing in avatar and a text input.  I will continue to try to build it out with redux, but have some fires to put out first so this jumped to lower priority unfortunately/ may just have to swap out with image for now since that seems to work.  Here is a snack that works and doesn't have any errors.

https://snack.expo.io/SysjpuCoH

In my code I tried this:

loadingProfilePicture===true && alert("loading new pic")

And that never gets triggered.  Also removed openPhotoPicker which doesn't make a difference either.  No idea what is being rerendered that is affecting it but i've basically tried removing lines refreshing over and over again and can't get rid of it.  Will keep playing with it though

**Comment by oxyii** [comment]
@Sbphillips19 Look, React will re-render after changing **any** state or prop (exclude using in `memo`). So you just need to exclude avatar into standalone component and Avatar will not be re-rendered after input changes https://snack.expo.io/HJxupMGhB

**Comment by Sbphillips19** [comment]
Unfortunately the avatar is dependent on the state since I am allowing the user to update their profile picture so I need to be able to update the avatar.   `source={{ uri: this.state.profilePicture }}`

Why would React Native Image not rerender while Avatar rerenders?

**Comment by oxyii** [comment]
@Sbphillips19 under the hood `RNE Avatar` have `RNE Image`. This Image component make [fade in](https://github.com/react-native-elements/react-native-elements/blob/32fbb7ab60040b81ce148a749c5e7ae29fde4408/src/image/Image.js#L19-L38) effect. So I think you're in trap on this. Avatar will blinking on `source` prop changes

**Comment by iRoachie** [comment]
There's an option to disable the animation, that will come in the next release https://github.com/react-native-elements/react-native-elements/commit/4a19e4c7a9d8f0a219c75b49d3fae2252bcd9bdb#diff-db91516ae3fd33db904a11400a5e19e4

**Comment by oxyii** [comment]
@iRoachie Will Avatar support this prop for passing into Image?

**Comment by iRoachie** [comment]
Avatar already supports this by use of the [`imageProps` prop](https://react-native-elements.github.io/react-native-elements/docs/avatar.html#imageprops)

**Comment by Sbphillips19** [comment]
@iRoachie will close and try implementing once release is out.  Would I just use transition=false?

**Comment by iRoachie** [comment]
```jsx
imageProps={{ transition: false }}
```
