### ISSUE TITLE
SearchBar onCancel not firing

### ISSUE THREAD

**Issue by darrylyoung** [react-native-elements/react-native-elements#2184]
**Explain what you did**

Added a `SearchBar` component to my Expo app.

**Expected behavior**

Based on the [documentation](https://react-native-elements.github.io/react-native-elements/docs/searchbar.html#oncancel), I expected my callback to be fired when pressing the _Cancel_ button that appears alongside the search when there's text in the input. 

**Describe the bug**

The function passed to `onCancel` doesn't fire. Instead, tapping the _Cancel_ button just appears to blur the input. This forces the keyboard to close and focus to be lost, leaving any text in the input.

I get that I can pass `showCancel` to the component and that this will always show the _Cancel_ button (which can then be pressed to fire the callback) but this kind of defeats the object of having it there in the first place and doesn't work in the same way a native iOS search bar works (try searching in _Settings_ – you can tap cancel for it to clear and close whereas the small clear button in the input just clears but keeps focus). If it has to stay like this with your component, it'd be great if you could adjust the section on `onCancel` as right now it doesn't mention a potential requirement of `showCancel` being `true`.

Basically, I would've liked to be able to press _Cancel_ and have my callback clear the input and blur focus in one go as opposed to having to tap the input once to blur (and hide _Cancel_) to only then be able to tap the clear icon.

**To Reproduce**

```ts
const handleCancelSearch = () => {
  // Do something...
}
```

```jsx
<SearchBar
  platform="ios"
  placeholder={"..."}
  onChangeText={handleSearch}
  onCancel={handleCancelSearch}
  lightTheme={true}
  value={searchQuery}
/>
```

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements | ^1.2.7 |
| react-native          |  Expo SDK 35.0.0       |

Thank you for all the hard work you and the team put into React Native Elements! It's awesome.

**Comment by oxyii** [comment]
@darrylyoung Hm... Cannot reproduce it https://snack.expo.io/BkctsYnsB

**Comment by darrylyoung** [comment]
Hi, @oxyii. Thanks for trying it out. As soon as I have chance – hopefully this weekend – I'll try again and let you know. If I still have the problem, I'll try to create a snack and provide some more code.

Have a nice weekend.

**Comment by darrylyoung** [comment]
Hi, @oxyii. Quickly running your example on my iPhone now, it looks like the difference is that I was wrapping _everything_ – the `SearchBar` followed by the rest of the screen – in a single `ScrollView`. If I change your `SafeAreaView` to `ScrollView`, I can reproduce the situation I originally mentioned.

That, however, would remove scrolling, which I want, so I've realised that I'm probably better doing something like this:

```tsx
<SafeAreaView style={{ flex: 1, paddingTop: 40 }}>
  <SearchBar
    platform="ios"
    lightTheme
    placeholder="..."
    onChangeText={text => setSearchQuery(text)}
    onCancel={() => setCancelClicked(cancelClicked+1)}
    value={searchQuery}
  />
  <ScrollView style={styles.container}>
    <Text style={styles.paragraph}>
      Cancel times {cancelClicked}
    </Text>      
  </ScrollView>
</SafeAreaView>
```

I guess I'm good now. Thanks for the quick help; I really appreciate it. Have a nice weekend!

**Comment by oxyii** [comment]
@darrylyoung Reproduced. This is not a `SearchBar` issue exactly. It's `ScrollView` and ScrollView-based components (such a FLatList) [behavior](https://facebook.github.io/react-native/docs/scrollview#keyboardshouldpersisttaps).
```jsx
<ScrollView keyboardShouldPersistTaps="handled"> {/* or "always" */}
  <SearchBar ... />
</ScrollView>
```

**Comment by darrylyoung** [comment]
Got it. Thank for you the explanation! I’m new to React Native so learning this as I go. Have a nice weekend.
