### ISSUE TITLE
Input Clear Button Styling

### ISSUE THREAD

**Issue by nica0012** [react-native-elements/react-native-elements#2190]
**Explain what you did**

**Expected behavior**

**Describe the bug**

**To Reproduce**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Screenshots**

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |         |
| react-native          |         |

**Comment by nica0012** [comment]
Ever since I updated to RN v60, My input text styles and clear buttons have gone very faint. I managed to fix the text styles by adding a color property, but there doesn't seem to be any control over the clear button.

It shows okay on my simulator, but on my device you can barely see it. 

If there is a way to change the styling like size / color, this would be no issue - maybe I missed something?

Cheers.

**Comment by iRoachie** [comment]
I don't know of RN v60 changing anything visually. Can you create an example on https://snack.expo.io that reproduces this?

**Comment by nica0012** [comment]
@iRoachie Since it works on the simulator I dont know if it would be of much use, but my code for the Input is as follows:

`          <Input
            autoFocus
            autoCorrent={false}
            clearButtonMode="always"
            leftIcon={{
              type: 'font-awesome',
              name: 'search',
              color: colors.grayIcon,
              size: 24, 
              marginRight: 12, 
              marginTop: -2 
            }}
            maxLength={30}
            inputContainerStyle={{ 
              borderBottomWidth: 0, paddingRight: 10,
            }}
            inputStyle={{ 
              color: colors.blackText,
              fontSize: 18,
              fontFamily: 'Avenir',
            }}
            onFocus={() => {
              this.onFocus();
            }}
            onBlur={() => {
              this.onBlur();
            }}
            onChangeText={(textEntry) => {
                this.setState({
                  userSearch: textEntry,
                 });
                this.props.usernameSearch(textEntry);
            }}
            containerStyle={[styles.inputContainerStyle,
            { 
              // backgroundColor: this.state.inputFocused ? colors.pressFocus : colors.inputBackground ,
              backgroundColor: colors.inputBackground ,
              width: deviceWidth - 30
              }]}
            placeholderTextColor={colors.placeholder}
            placeholder={'Search by username...'}
          />`

**Comment by iRoachie** [comment]
Are you experiencing this on Android or iOS?

**Comment by nica0012** [comment]
IOS (Only on physical device)

**Comment by nica0012** [comment]
Although it would be nice to have props like clearButtonColor / clearButtonStyle, a simple workaround is to just create a right icon thats touchable like so:

```
  clearIcon = () => {
    if (this.state.userSearch) {
      return (
        <TouchableOpacity
          onPress={() => {
            this.myTextInput.current.clear();
            this.setState({ userSearch: null })
          }}
        >
          <FontAwesome5Pro
            name="times-circle"
            color={colors.grayIcon}
            size={20}
            regular
          />
      </TouchableOpacity>
      );
    } else {
      return null;
    }
  }
```
