### ISSUE TITLE
Custom fontFamily does not work with Text Heading (h1, h2, h3, h4)

### ISSUE THREAD

**Issue by bearbytes** [react-native-elements/react-native-elements#2191]
I'm loading a custom font using Expo as described [here](https://docs.expo.io/versions/latest/guides/using-custom-fonts/).

Setting the new font as `fontFamily` style works in regular Text components.

However, as soon as one of the heading props are set on the Text component, the fontFamily is no longer applied.

Example:
```
import { Text } from 'react-native-elements'

<Text
  h1
  h1Style={{ color: 'red', fontFamily: 'dosis-regular' }}
  style={{ color: 'blue', fontFamily: 'dosis-regular' }}
>This is my text</Text>
```

This text is large, red and uses the default font.
After removing the `h1` prop, the text is small, blue and using the [Dosis](https://fonts.google.com/specimen/Dosis) font.

Keeping `h1` but removing `h1Style`, the text is large, blue and using the default font.
Keeping `h1` but removing `style` does nothing.

**Environment:**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   1.2.7      |
| react-native          |     0.59.10    |
| expo | 35.0.0|

**Comment by oxyii** [comment]
@bearbytes I'm not sure about exactly **REGULAR** fonts for using with `h*` props...
https://github.com/react-native-elements/react-native-elements/blob/0f06b924fc7536f7599aca268864a75f33e13b1e/src/text/Text.js#L29-L32
Please try to use **BOLD** font.

**Comment by bearbytes** [comment]
Setting `fontWeight: 'normal'` seems to fix the issue. Loading and setting the Bold variant of the font however doesn't seem to make any difference if the fontWeight is not changed.

Maybe the information about which "weight" the font has is getting lost when loaded by `expo-font`, and all fonts are handled as regular.

For now, I'll change the default fontWeight of all h-elements in the ThemeProvider, thanks!

**Comment by oxyii** [comment]
@iRoachie or we can qualify this issue as a bug?

**Comment by Usamaliaquat123** [comment]
@iRoachie  @oxyii  can i fix this issue... ?

**Comment by ispulkit** [comment]
This is also happening with Button. Custom `fontfamily` and `fontWeight` are not working. 
```
<Button
                  title="Request OTP"
                  buttonStyle={{
                    borderRadius: 8,
                    padding: '4%',
                    backgroundColor: '#0E85DD',
                  }}
                  fontFamily="Nunito-Bold"
                  fontWeight="bold"
                  onPress={sendOTPPressHandler}
```

Using `    "react-native-elements": "^1.2.7"`.

**Comment by xstable** [comment]
It's even seems not to work at least with bold-fonts, but only if you set it to `fontWeight:"nomal"` ?!

Please try it with `Montserrat-Bold` and Montserrat-Regular: https://fonts.google.com/specimen/Montserrat

Even if you use `Montserrat-Bold` as Font, it wouldn't appear, if you don't set `fontWeight:"normal"`.

In my opinion it seems to be an Bug.

**Comment by seankovacs** [comment]
I'm finding that on iOS, changing the h*Style fontFamily works fine without fontWeight, but not for Android. On Android it's causing the fontFamily to not work unless you add the fontWeight: 'normal'. So i did this for the time being: fontWeight: Platform.OS === 'ios' ? null : 'normal' .

**Comment by oxyii** [comment]
@seankovacs  This is known RN issue. For example - [this](https://github.com/facebook/react-native/issues/28854) is one of many related issues. See workaround [here](https://github.com/facebook/react-native/issues/25696)
