### ISSUE TITLE
SearchBar's height

### ISSUE THREAD

**Issue by emmx** [react-native-elements/react-native-elements#2192]
It's not possible to easily increase the height of the SearchBar. It would be nice to have a height prop on the SearchBar component for that purpose.

There are a few styling props such as inputStyle, inputContainerStyle, containerStyle, etc. but none would let you change its height in a way that the whole thing is adjusted accordingly (ie, the search/cancel buttons should become smaller, the placeholder font, the input itself and the container too).

Maybe I'm missing something, in that case please provide an example.

**Comment by Usamaliaquat123** [comment]
> It's not possible to easily increase the height of the SearchBar. It would be nice to have a height prop on the SearchBar component for that purpose.

@iRoachie  can i do this  👍

**Comment by Gabsys** [comment]
Set height in _inputStyle_ to adjust the **height of SearchBar** & set height in _containerStyle_ to adjust **height of the icons** to be align with the SearchBar.

**Comment by flyingcircle** [comment]
@emmx let me know if @Gabsys did not work.

**Comment by sriteja777** [comment]
@Gabsys  I tried your solution with Input Element, however when I set height in inputContainerStyle or containerStyle, the placeholder is not displaying, without setting the prop placeholder is working fine, can you please look into that?

**Comment by arn-ob** [comment]
inputContainerStyle={{ height: 20 }}

**Comment by lxt-ing** [comment]
it doesn't work for me , i can't change the height

**Comment by nimeshmaharjan1** [comment]
same here there is not inputContainerStyle prop 
and this doesnt change anything
`inputStyle={{
            height: 12,
          }}`

**Comment by ghost** [comment]
set the height in the style prop for the container and set the minHeight as well to same you will get the desired output.
`const $searchbar: ViewStyle = {
  backgroundColor: colors.palette.neutral100,
  height: hp('5.5%'),
}
const $input: TextStyle = {
  color: colors.palette.primary,
  minHeight: hp('5.5%'),
}`

**Comment by ibrust** [comment]
To reduce the height of the searchbar I needed to override the minheight of the inputStyle to match what the new height will be, minheight was preventing the textinput from shrinking which was causing it to be misaligned.
