### ISSUE TITLE
deepmerge util in 'withTheme' HoC chokes on extraneous props with circular references

### ISSUE THREAD

**Issue by ankhzet** [react-native-elements/react-native-elements#2197]
**Explain what you did**

I've used the Input component in combination with a HoC, that provides some extra props, that can be an objects with circular refs. Usually i'd expect any extraneous props to be ignored by any component, so i passed current props directly to the wrapped Input without filtering out HoC-introduced props.

**Expected behavior**
Input component (and probably any other themed component) would ignore the props it doesn't expect to receive (why withTheme HoC even try to traverse and clone the prop it has nothing to do with?), or at least documentation would contain a warning about this specific caveat with a mention of a possible "Maximum call stack size exceeded" exception in `mergeObject` function, it would probably save some time googling for us unfortunate souls xD.

**Describe the bug**
`withTheme` HoC tries to clone all the props that the wrapped component receives.

**To Reproduce**

https://snack.expo.io/@ankhzet/funny-edamame

```javascript
const circular = {
  a: 1,
  b: 2,
};
circular.c = circular;

<Input 
    circular={circular} // some extraneous prop with circular references in it
/>
```

**Possible solution**
In `withTheme.js`, specify options `{ clone: false }` for `deepmerge` function. It would effectively prevent `deepmerge` from traversing the props, that don't exist in the `theme` object.

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  1.2.7  |
| react-native          | 0.59.8  |

**Comment by saxahan** [comment]
It stands still
