### ISSUE TITLE
Can't remove horizontal padding in SearchBar component

### ISSUE THREAD

**Issue by darrylyoung** [react-native-elements/react-native-elements#2198]
**Component**: SearchBar

**Explain what you did**

I'm trying to remove the padding in the `SearchBar` component.

**Expected behavior**

I would've expected to be able to remove the extra padding with `{{ padding: 0 }}`.

**Describe the bug**

**To Reproduce**

Wrap the `SearchBar` in a wrapper that gives `16px` padding on both sides. You can see this in the screenshot. It's a little hard to see with the background being white but know that the two blue cards are both `16px` from the outer edges of the screen.

I want the outer grey part of the `SearchBar` to also align with these cards. The component itself is aligning to them but the actual input inside the container seems to have padding pushing it in. I've given the container a red background to show what I mean. It looks like there's `8px` padding on the wrapper. Looking at the [code](https://github.com/react-native-elements/react-native-elements/blob/next/src/searchbar/SearchBar-default.js#L89) – I think this is the right code – it looks like there's padding set by the theme but that anything passed to `containerStyle` should work. In this case, I thought passing `padding: 0` to `containerStyle` would work but it doesn't appear to do anything.

![PNG image](https://user-images.githubusercontent.com/1460800/69978949-9ffb9c80-152d-11ea-8ed3-80ca186b2f7d.png)

```tsx
<SafeAreaView style={styles.container}>
  <SearchBar
    platform="ios"
    placeholder={translate('common.searchIn', { name: categoryName })}
    onChangeText={handleSearch}
    lightTheme={true}
    value={searchQuery}
    containerStyle={{ backgroundColor: 'red', padding: 0 }}
    inputStyle={{ color: color.palette.offBlack }}
    inputContainerStyle={{ backgroundColor: color.palette.iOSLightGrey }}
  />
```

I've also tried adding `margin: 0` and `padding: 0` to `containerStyle`, `inputStyle`, and `inputContainerStyle`.

**Screenshots**

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  1.2.7       |
| react-native          |     Expo sdk-35.0.0    |

**Comment by darrylyoung** [comment]
I noticed that using works in `containerStyle={{ padding: 0 }}` to achieve what I want when **not** using `platform="ios"`. I would like to, however, use the iOS style. Is there a better workaround?

**Comment by darrylyoung** [comment]
I noticed containerStyle={{ padding: 0 }} works to achieve what I want when not using platform="ios". I would like to, however, use the iOS style. Is there a better workaround?

**Comment by darrylyoung** [comment]
I noticed `containerStyle={{ padding: 0 }}` works to achieve what I want when not using `platform="ios"`. I would like to, however, use the iOS style. Alternatively, I can add `containerStyle={{ margin: -8 }}` to pull it out to the desired edges (red background shown below to illustrate this) but it seems like a hacky workaround. Is there a better way?

![PNG image](https://user-images.githubusercontent.com/1460800/70033999-cdd5f500-15b0-11ea-8b54-f1bf3f4c3970.png)

**Comment by Qiyu8** [comment]
I know what you mean, inside searchbar, The ios mode containerStyle has the default "paddingBottom: 13, paddingTop: 13" attribute, which can't be override by padding, so I recommend you modify these attribute to achieve your desired style.

**Comment by darrylyoung** [comment]
Are you suggesting to fork and modify the code in the component itself or override these by passing a prop (or setting some CSS)? Apologies if I misunderstood. Thanks for the reply.

**Comment by darrylyoung** [comment]
> I know what you mean, inside searchbar, The ios mode containerStyle has the default "paddingBottom: 13, paddingTop: 13" attribute, which can't be override by padding, so I recommend you modify these attribute to achieve your desired style.

@Qiyu8 – Are you suggesting to fork and modify the code in the component itself or override these by passing a prop (or setting some CSS)? Apologies if I misunderstood. Thanks for the reply.

**Comment by Qiyu8** [comment]
I mean you can try code below. focused on containerStyle.
```
<SafeAreaView style={styles.container}>
  <SearchBar
    platform="ios"
    placeholder={translate('common.searchIn', { name: categoryName })}
    onChangeText={handleSearch}
    lightTheme={true}
    value={searchQuery}
    containerStyle={{ backgroundColor: 'red', paddingBottom: 0 }}
    inputStyle={{ color: color.palette.offBlack }}
    inputContainerStyle={{ backgroundColor: color.palette.iOSLightGrey }}
  />
```

**Comment by darrylyoung** [comment]
Ah, yeah. I'd been trying `padding: 0` and `paddingVertical: 0` but these don't actually override the individual `paddingTop` and `paddingBottom`. Thanks for the suggestion, @Qiyu8. 👍

![PNG image](https://user-images.githubusercontent.com/1460800/70217488-8f237480-1741-11ea-9375-faff1a5b1a88.png)

Now, to make the input go right to the edges...

In the [iOS code](https://github.com/react-native-elements/react-native-elements/blob/next/src/searchbar/SearchBar-ios.js#L146-L147), anything you pass to `inputContainerStyle` will override the ability for the search bar to shrink (with right margin) as the cancel button is shown. For example:

```tsx
<SearchBar
  platform="ios"
  placeholder={translate('common.searchIn', { name: categoryName })}
  onChangeText={handleSearch}
  lightTheme={true}
  value={searchQuery}
  containerStyle={{
    backgroundColor: 'red',
    paddingBottom: 0,
    paddingTop: 0
  }}
  inputContainerStyle={{
    backgroundColor: color.palette.iOSLightGrey,
    marginLeft: 0 // <- this works to allow the input to start at the left edge of its container
    marginRight: 0 // <- here is the issue now (see below)
  }}
  inputStyle={{ color: color.palette.offBlack }}
/>
```

![PNG image](https://user-images.githubusercontent.com/1460800/70218610-921f6480-1743-11ea-833c-3b2e79a064fe.png)

This finally looks like I want it to look, by overriding the `marginRight` set [here](https://github.com/react-native-elements/react-native-elements/blob/next/src/searchbar/SearchBar-ios.js#L275), but what this means is that now, when the input has focus, it won't slide in by adjusting its margin – code [here](https://github.com/react-native-elements/react-native-elements/blob/next/src/searchbar/SearchBar-ios.js#L146). I'm going to open a PR and see if they'll switch around the order of the applied CSS here as that should allow users to apply whatever margin they want but also still have it slide in when the cancel button shows.

Thanks for the replies, @Qiyu8.
