### ISSUE TITLE
Usage with Storybook and react-native-web

### ISSUE THREAD

**Issue by neilgamb** [react-native-elements/react-native-elements#2201]
I'm looking to create a docs site / component library using storybook.  I have followed the instructions here: https://react-native-elements.github.io/react-native-elements/docs/web_usage.html

but when I compile the storybook, I'm getting the following error:

`Module parse failed: Unexpected token (61:11)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. `

**Your Environment (please complete the following information):**

```
{
  "name": "scandy-ui",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@types/jest": "24.0.23",
    "@types/node": "12.12.11",
    "@types/react": "16.9.11",
    "@types/react-dom": "16.9.4",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-native-elements": "^1.2.7",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.11.7",
    "react-scripts": "3.2.0",
    "typescript": "3.7.2"
  },
  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -c .storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/core": "^7.7.2",
    "@babel/plugin-proposal-class-properties": "^7.7.4",
    "@storybook/addon-actions": "^5.2.6",
    "@storybook/addon-docs": "^5.2.6",
    "@storybook/addon-links": "^5.2.6",
    "@storybook/addon-viewport": "^5.2.6",
    "@storybook/addons": "^5.2.6",
    "@storybook/preset-typescript": "^1.1.0",
    "@storybook/react": "^5.2.6",
    "babel-loader": "^8.0.6",
    "customize-cra": "^0.9.1",
    "react-app-rewired": "^2.1.5",
    "react-docgen-typescript-loader": "^3.5.0",
    "ts-loader": "^6.2.1"
  }
}
```

**Comment by iRoachie** [comment]
Judging based on your comment only, I have no way to determine where `61:11` is or what file it is. Is this the full error log?

**Comment by cjam** [comment]
I'm having a similar issue getting react-native-elements working in my typescript monorepo.  It seems to be related to the webpack config but I just can't seem to get it all working together.

I've got a repo structure like:
```
MyProject/
  packages/
    components/
    mobile/
    web/
```

My typescript projects are setup with references, and the *components* project is using react-native-elements and I've added the webpack config described here https://react-native-elements.github.io/react-native-elements/docs/web_usage.html. Everything compiles and runs fine in react-native but in the web project i get:

```
/MyProject/node_modules/react-native-elements/src/avatar/Avatar.js
SyntaxError: /MyProject/node_modules/react-native-elements/src/avatar/Avatar.js: Unexpected token (71:4)

  69 | 
  70 |   const Utils = showEditButton && (
> 71 |     <TouchableHighlight
     |     ^
  72 |       style={StyleSheet.flatten([
  73 |         styles.editButton,
  74 |         {
```

It's choking on the jsx unfortunately.  I compared all of the webpack config objects with the https://github.com/react-native-elements/create-react-app-example project but can't seem to overcome this error.  Anyone have any ideas?

**Comment by cjam** [comment]
After a lot of reading / writing of config files I finally got this to work.  It was an issue with the paths that I was resolving for the babel loader.  Here is what I ended up with, which seems fairly general.  I'll need to see if I can apply it to storybook as well.

```js

// require.resolve will resolve to the entry point of the module
// but we just want the folder
function resolveModuleDir(moduleName) {
    const pattern = new RegExp(`(?<=${moduleName}).*$`);
    return require.resolve(moduleName).replace(pattern, "");
}

module.exports = {
    webpack: (config, env) => {
        const newConfig = override(
            removeModuleScopePlugin(),
            ...addBabelPlugins(
                ["@babel/plugin-proposal-decorators", { "legacy": true }],
                ['@babel/plugin-proposal-class-properties', { "loose": true }],
                'babel-plugin-react-native-web'
            ),
            addWebpackPlugin(new webpack.DefinePlugin({ __DEV__: env !== 'production' })),
            babelInclude([
                resolveModuleDir('react-native-elements'),
                resolveModuleDir('react-native-vector-icons'),
                resolveModuleDir('react-native-ratings'),
                ...appIncludes
            ])
        )(config);
        return newConfig;
    }
}
```

**Comment by cjam** [comment]
@neilgamb I ended up getting my storybook working with react-native-elements.  It was just a matter of getting the right modules transpiled by babel.  The *webpack.config.js* in my `.storybook` folder looks like this:

```js

  const oneOfRules = config.module.rules[3];
  const babelLoader = oneOfRules.oneOf[1];
  babelLoader.include = [
    ...babelLoader.include,
    'node_modules/react-native-elements',
    'node_modules/react-native-vector-icons',
    'node_modules/react-native-ratings'
  ]
```

You may also want to confirm that you either have the `babel-plugin-react-native-web` plugin installed and configured or that you've added a webpack resolve alias for `react-native':'react-native-web'.

Hope that helps.

**Comment by gsouf** [comment]
in case it might help someone I had to run in a few more steps.

- first: explicitly declare babel config in the webpack rule (vs in `.babelrc`) or else babel config was not applied for content in node_modules for reasons I ignore.
- second: add a `file-loader` because reaction-native-ratings imports files.

Example webpack rule config that works for me:

```
{
        test: /\.(js|jsx)$/,
        exclude: function(content) {
          return (
            /node_modules/.test(content) &&
            !/\/react-native-elements\//.test(content) &&
            !/\/react-native-vector-icons\//.test(content) &&
            !/\/react-native-ratings\//.test(content)
          );
        },
        use: {
          loader: 'babel-loader',
          options: {
            presets: [
              [
                '@babel/preset-env',
                {
                  targets: {
                    chrome: '70'
                  }
                }
              ],
              '@babel/preset-react'
            ],
            plugins: [['@babel/plugin-proposal-class-properties', { loose: true }]]
          }
        }
      },
```

**Comment by neilgamb** [comment]
wonderful! I'm coming back to this after working on something else for a few weeks.  I will give this a shot a report back.  Thanks for your input @cjam

**Comment by aethiss** [comment]
Hi all, i still have problem, i hope somebody can give me some help or idea.

I created a react storybook (NO with react-create-app), then i add the library **react-native-web**, configured the storybook webpack and my babel, and everything works fine.

THEN i added the **react-native-elements** lib, i configured webpack follow the instructions found here and on the official docs, but i still have a error (ONLY WHEN I IMPORT A FILE USING 'react-native-component') like this :

`Module parse failed: Unexpected token (18:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file`

image attached from storybook maybe is more clear

<img width="1680" alt="Screenshot 2020-02-23 at 10 40 03" src="https://user-images.githubusercontent.com/1488133/75110733-cd864c80-5629-11ea-88c6-7d8cf9232198.png">


this is my babel config
`module.exports = function(api) {
  api.cache(true)
  return {
    plugins: ['react-native-web'],
    presets: ['@babel/preset-react']
  }
}
`

and this is my webpack inside ./storybook
`const path = require('path');
const webpack = require('webpack');

module.exports = async ({ config, mode }) => {
  config.module.rules.push(
    {
      test: /\.js$/,
      include: [
        path.resolve(__dirname, '../node_modules/react-native-elements/'),
        path.resolve(__dirname, '../node_modules/react-native-ratings/'),
        path.resolve(__dirname, '../node_modules/react-native-vector-icons/'),
        path.resolve(__dirname, '../'),
      ],
      use: {
        loader: 'babel-loader',
        options: {
          cacheDirectory: false,
          presets: ['module:metro-react-native-babel-preset'],
          plugins: [
            // needed to support async/await
            'babel-plugin-react-native-web',
            '@babel/plugin-transform-runtime',
            '@babel/plugin-proposal-class-properties'
          ]
        }
      }
    },
    // loader for png
    {
      test: /\.(gif|jpe?g|png|svg)$/,
      use: {
        loader: 'file-loader'
      }
    },
    // loader for font icons
    {
      test: /\.ttf$/,
      loader: 'url-loader',
      include: path.resolve(__dirname, '../node_modules/react-native-vector-icons/'),
    }
  );

  config.resolve.extensions = ['.web.js', '.js', '.json', '.web.jsx', '.jsx'];

  config.resolve.alias = {
    'react-native': 'react-native-web'
  };

  return config;
};
`

Any help will be very appreciated guys :)

**Comment by Aria461863631** [comment]
I start from the official 2018 guide
 [Comprehensive Guide to create simple app using React Native Web and React Native Elements](https://react-native-elements.github.io/react-native-elements/blog/2018/12/13/react-native-web.html#0-initial-step)
and reach this error

The author proposed a solution in this [commit](https://github.com/haruelrovix/gitphone/commit/8c0e6036d9231cc934285502528a2061b848ce2d)
by modifying `config/webpack.config.dev.js` and `config/webpack.config.prod.js` 

I just simply add `react-native-ratings` and it works

```js
          // Process application JS with Babel.
          // The preset includes JSX, Flow, and some ESnext features.
          {
            test: /\.(js|mjs|jsx|ts|tsx)$/,
             //include: paths.appSrc,
            include: [
              paths.appSrc,
              `${paths.appNodeModules}/react-native-elements`,
              `${paths.appNodeModules}/react-native-vector-icons`,
              `${paths.appNodeModules}/react-native-ratings`,
            ],
```

**Comment by aethiss** [comment]
@Aria461863631 , tnx for your help, unfortunately do not solve my problem. My solution is the same, the only difference on yours, is using the "paths" helper. But i try following also the link from the commit you provided.
Also, mine is a web-app, not a react-native-app (is just a storybook), but again, react-native-elements should works with react-native-web.

i simplify the webpack configuration, but the error still the same

```
'use strict';
const paths = require('./paths');

// This is the development configuration.
module.exports = {
  resolve: {
    // `web` extension prefixes have been added for better support
    // for React Native Web.
    extensions: ['.web.js', '.mjs', '.js', '.json', '.web.jsx', '.jsx'],
    alias: {
      // Support React Native Web
      'react-native': 'react-native-web'
    },
  },
  module: {
    strictExportPresence: true,
    rules: [
      // loader for png
      {
        test: /\.(gif|jpe?g|png|svg)$/,
        loader: 'file-loader'
      },
      // loader for font icons
      {
        test: /\.ttf$/,
        loader: 'url-loader',
        include: path.resolve(__dirname, '../node_modules/react-native-vector-icons/'),
      },
      // Process JS with Babel.
      {
        test: /\.(js|jsx|mjs)$/,
        include: [
          paths.appSrc,
          `${paths.appNodeModules}/react-native-elements`,
          `${paths.appNodeModules}/react-native-vector-icons`,
          `${paths.appNodeModules}/react-native-ratings`,
        ],
        loader: require.resolve('babel-loader'),
        options: {

          // The 'react-native' preset is recommended to match React Native's packager
          presets: ['react-native'],
          // Re-write paths to import only the modules needed by the app
          plugins: ['react-native-web'],
          // This is a feature of `babel-loader` for webpack (not Babel itself).
          // It enables caching results in ./node_modules/.cache/babel-loader/
          // directory for faster rebuilds.
          cacheDirectory: true,
        },
      },
    ],
  },
};
```

**Comment by flyingcircle** [comment]
Let me know if this is still an ongoing issue.

**Comment by droplessjordan** [comment]
> Hi all, i still have problem, i hope somebody can give me some help or idea.
> 
> I created a react storybook (NO with react-create-app), then i add the library **react-native-web**, configured the storybook webpack and my babel, and everything works fine.
> 
> THEN i added the **react-native-elements** lib, i configured webpack follow the instructions found here and on the official docs, but i still have a error (ONLY WHEN I IMPORT A FILE USING 'react-native-component') like this :
> 
> `Module parse failed: Unexpected token (18:12) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file`
> 
> image attached from storybook maybe is more clear
> 
> <img alt="Screenshot 2020-02-23 at 10 40 03" width="1680" src="https://user-images.githubusercontent.com/1488133/75110733-cd864c80-5629-11ea-88c6-7d8cf9232198.png">
> 
> this is my babel config
> 
> ```
> module.exports = function(api) {
>   api.cache(true)
>   return {
>     plugins: ['react-native-web'],
>     presets: ['@babel/preset-react']
>   }
> }
> ```
> 
> and this is my webpack inside ./storybook
> 
> ```
> const path = require('path');
> const webpack = require('webpack');
> 
> module.exports = async ({ config, mode }) => {
>   config.module.rules.push(
>     {
>       test: /\.js$/,
>       include: [
>         path.resolve(__dirname, '../node_modules/react-native-elements/'),
>         path.resolve(__dirname, '../node_modules/react-native-ratings/'),
>         path.resolve(__dirname, '../node_modules/react-native-vector-icons/'),
>         path.resolve(__dirname, '../'),
>       ],
>       use: {
>         loader: 'babel-loader',
>         options: {
>           cacheDirectory: false,
>           presets: ['module:metro-react-native-babel-preset'],
>           plugins: [
>             // needed to support async/await
>             'babel-plugin-react-native-web',
>             '@babel/plugin-transform-runtime',
>             '@babel/plugin-proposal-class-properties'
>           ]
>         }
>       }
>     },
>     // loader for png
>     {
>       test: /\.(gif|jpe?g|png|svg)$/,
>       use: {
>         loader: 'file-loader'
>       }
>     },
>     // loader for font icons
>     {
>       test: /\.ttf$/,
>       loader: 'url-loader',
>       include: path.resolve(__dirname, '../node_modules/react-native-vector-icons/'),
>     }
>   );
> 
>   config.resolve.extensions = ['.web.js', '.js', '.json', '.web.jsx', '.jsx'];
> 
>   config.resolve.alias = {
>     'react-native': 'react-native-web'
>   };
> 
>   return config;
> };
> ```
> 
> Any help will be very appreciated guys :)

Hey @aethiss, did you ever find a fix for this?

**Comment by aethiss** [comment]
sorry for delay @droplessjordan , yes i found a working solution, i copy here my storybook webpack config (webpack 4)

```'use strict';
const path = require('path');

// This is the development configuration.
module.exports = {
  module: {
    strictExportPresence: true,
    rules: [
      // loader for png
      {
        test: /\.(gif|jpe?g|png|svg)$/,
        loader: 'file-loader',
      },
      // loader for font icons
      {
        test: /\.ttf$/,
        loader: 'url-loader',
        include: path.resolve(__dirname, '../node_modules/react-native-vector-icons/'),
      },
      // Process JS with Babel.
      {
        test: /\.(js|jsx|mjs)$/,
        include: [
          path.resolve(__dirname, '../src/'),
          path.resolve(__dirname, '../node_modules/react-native-elements/'),
          path.resolve(__dirname, '../node_modules/react-native-vector-icons/'),
          path.resolve(__dirname, '../node_modules/react-native-ratings/'),
        ],
        loader: 'babel-loader',
        options: {

          // The 'react-native' preset is recommended to match React Native's packager
          presets: [
            [
              'module:metro-react-native-babel-preset',
              { disableImportExportTransform: true }
            ]
          ],
          // Re-write paths to import only the modules needed by the app
          plugins: ['react-native-web'],
          // This is a feature of `babel-loader` for webpack (not Babel itself).
          // It enables caching results in ./node_modules/.cache/babel-loader/
          // directory for faster rebuilds.
          cacheDirectory: true,
        },
      },
    ],
  },
};```
