### ISSUE TITLE
onCancel is not working for android

### ISSUE THREAD

**Issue by mohak1990** [react-native-elements/react-native-elements#2205]
onCancel event is not firing on Android, working properly on IOS   |

**Comment by Qiyu8** [comment]
which component? Can you paste your code here.

**Comment by mohak1990** [comment]
search-bar

**Comment by Qiyu8** [comment]
It looks like perfect working in my computer, here shows the code. After click on the left icon, the input focus was lost. 
```
handleCancel(e){
    console.log("canceled")
    this.state.searchQuery = ""
  }
<SearchBar
    platform="android"
    onCancel = {this.handleCancel}
  />
```

**Comment by mohak1990** [comment]
`<SearchBar
        lightTheme
        inputStyle={styles.inputStyle}
        inputContainerStyle={styles.inputContainerStyle}
        round
        autoFocus={true}
        placeholder={placeholder || 'Search'}
        containerStyle={styles.searchContainer}
        onChangeText={text => handleChangeText(text)}
        value={searchText}
        autoCorrect={false}
        onCancel={onCancel}
        showCancel={true}
        cancelButtonTitle="Cancel"
        cancelButtonProps={{
          color: Colors.text.blueDark,
          buttonTextStyle: styles.cancelButtonStyle,
        }}
        platform={Platform.OS === 'ios' ? 'ios' : 'android'}
        clearIcon={{ type: 'material-community', color: '#86939e', name: 'close' }}
      />`

**Comment by oxyii** [comment]
@mohak1990 Did you use SearchBar inside ScrollView? May be [this](https://github.com/react-native-elements/react-native-elements/issues/2184#issuecomment-554658025) helps?..

**Comment by oxyii** [comment]
Or one more platform difference: https://github.com/react-native-elements/react-native-elements/issues/2223

**Comment by flyingcircle** [comment]
Per the documentation: 
```callback fired when pressing the cancel button (iOS) or the back icon (Android)```

The 'x' icon doesn't cause the `onCancel` to be triggered but the back button that appears causes it to. I'm assuming that we probably want `onCancel` to also trigger on the `x` button as well.

**Comment by himanishm07** [comment]
`The 'x' icon doesn't cause the onCancel to be triggered but the back button that appears causes it to. I'm assuming that we probably want onCancel to also trigger on the x button as well.`

If this is the requirement then passing onClear should work.
https://react-native-elements.github.io/react-native-elements/docs/searchbar.html#onclear
