### ISSUE TITLE
Image Component doesn't honor onLoad passed to it.

### ISSUE THREAD

**Issue by TomJKlug** [react-native-elements/react-native-elements#2206]
**Explain what you did**

Image Component onLoad is not being fired. When given a function through props.

**Expected behavior**

I expect the onLoad I supply to the Image Component to run.

**Describe the bug**

The Image component doesn't honor my onLoad function and instead only runs its own onLoad method.

**To Reproduce**
1. Create and Image component
2. Give it an onLoad function that console logs
3. Have it run
4. It won't console log.

`<ImageComponent
          testID="RNE__Image"
          {...attributes}
          onLoad={this.onLoad}`

The problem is here in Image.js

**Your Environment (please complete the following information):**

react-native-elements 1.2.7
react-native 0.61.5

**Comment by Qiyu8** [comment]
It looks like RNE image has a default onLoad function and didn't handle the passed onLoad function.  a PR is welcomed

**Comment by xavier-villelegier** [comment]
This issue was addressed by @fwuensche for the "Contribute" meetup at Doctolib ! It's now available on the `next` branch 👌
