### ISSUE TITLE
trackStyle for Slider, styles passed not being applied

### ISSUE THREAD

**Issue by yazmnh87** [react-native-elements/react-native-elements#2207]
**Explain what you did**

Attempting to apply a different color to the track on the Slider component

**Expected behavior**

-pass style to trackStyle prop using either backgroundColor or color and color will update

                   <Slider
                      minimumValue={0}
                      maximumValue={20}
                      thumbTintColor="#44B38A"
                      trackStyle={{color:'blue'}}
                      value={state.dependents}
                      onValueChange={value =>
                        setState(prevState => ({
                          ...prevState,
                          value: Math.round(value)
                        }))
                      }
                    />

**Describe the bug**

trackStyle prop is not working.  I've tried passing many different style properties to it and the color of the track is not updating

**To Reproduce**

apply prop trackStyle to Slider component,
attempt using "backgroundColor:'blue" or color:"blue"

ie trackStyle={{backgroundColor:'blue}} or
trackStyle={{color:'blue}}

the color of the track does not update

| software       
| --------------------- | ------- |
| react-native-elements 1.2.7 **latest version available
| react-native        https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz

**Comment by Qiyu8** [comment]
Hi,yazmnh87,if you want to change the backgroud color of the track, try use minimumTrackTintColor and maximumTrackTintColor. inside trackStyle color is invalid while backgroundColor will override by default maximumTrackTintColor.
```
<Slider
                  minimumValue={0}
                  maximumValue={20}
                  thumbTintColor="#44B38A"
                  minimumTrackTintColor="blue"
                  maximumTrackTintColor="red"
                  value={state.dependents}
                  onValueChange={value =>
                    setState(prevState => ({
                      ...prevState,
                      value: Math.round(value)
                    }))
                  }
                />
```

**Comment by yazmnh87** [comment]
> Hi,yazmnh87,if you want to change the backgroud color of the track, try use minimumTrackTintColor and maximumTrackTintColor. inside trackStyle color is invalid while backgroundColor will override by default maximumTrackTintColor.
> 
> ```
> <Slider
>                   minimumValue={0}
>                   maximumValue={20}
>                   thumbTintColor="#44B38A"
>                   minimumTrackTintColor="blue"
>                   maximumTrackTintColor="red"
>                   value={state.dependents}
>                   onValueChange={value =>
>                     setState(prevState => ({
>                       ...prevState,
>                       value: Math.round(value)
>                     }))
>                   }
>                 />
> ```

Thanks this ended up working for me, still unsure the use of trackStyle but I have a solution.  Thank you!
