### ISSUE TITLE
SearchBar  - typed text in SearchBar does not appear in the SearchBar

### ISSUE THREAD

**Issue by Chanach** [react-native-elements/react-native-elements#2208]
**Explain what you did**
I want to use SearchBar-Component of react native elements in my App, 

Version: "react-native-elements": "^1.2.7"

Typed text in SearchBar does not appear in the SearchBar, means there is a problem with prop "value".
In the Console i can see, that typing text in the SearchBox works, but it does not appear in the SearchBox.

I've followed official documentation: https://react-native-elements.github.io/react-native-elements/docs/searchbar.html

**Expected behavior**

Entered text in the SearchBar should be displayed in the SearchBar.  

**Describe the bug**

```
<SearchBar 
     placeholder="From" 
     lightTheme
     onChangeText={this.handleSearch}
     value={this.state.searchText}
/>
```

```
handleSearch = (searchText) => {    
    this.setState({searchText});
  }
```

**Comment by Qiyu8** [comment]
Hi,Chanach. You need to pass the platform attribute manually.
```
<SearchBar 
     platform="android"
     placeholder="From" 
     lightTheme
     onChangeText={this.handleSearch}
     value={this.state.searchText}
/>
```

**Comment by oxyii** [comment]
@Chanach Can you make a small demo to reproduce this issue ? https://snack.expo.io/

**Comment by flyingcircle** [comment]
@Chanach I and @saxenanihal95 were unable to reproduce the issue you're describing. If you can provide a snack example of this not working, I'll reopen the ticket.

**Comment by aej11a** [comment]
@Chanach did you find a solution to this? I have the same problem in my app but the exact same code is working on snack.expo.io

cc @flyingcircle
