### ISSUE TITLE
Normalize does not scale the font correctly

### ISSUE THREAD

**Issue by mi-mazouz** [react-native-elements/react-native-elements#2209]
**Explain what you did**

I'm trying to use normalize on a big size. It supposed to scale the font and render the same thing on every size of screen but with a normalize(36) it does not work on Iphone 11.

**Expected behavior**

Iphone 5s
<img width="399" alt="Screen Shot 2019-12-10 at 10 25 26 AM" src="https://user-images.githubusercontent.com/24244248/70542889-8531b500-1b37-11ea-8c68-34e84dfdb51a.png">

Iphone 11 Pro Max
<img width="384" alt="Screen Shot 2019-12-10 at 10 25 16 AM" src="https://user-images.githubusercontent.com/24244248/70542955-aabebe80-1b37-11ea-884d-962d290eafa9.png">

**What's wrong**

Iphone 7
<img width="415" alt="Screen Shot 2019-12-10 at 10 24 59 AM" src="https://user-images.githubusercontent.com/24244248/70542919-95499480-1b37-11ea-9580-85d45d224f9f.png">

Iphone 8 Plus
<img width="322" alt="Screen Shot 2019-12-10 at 10 28 57 AM" src="https://user-images.githubusercontent.com/24244248/70543150-f1acb400-1b37-11ea-8db6-7ab705b0e094.png">

**Your Environment (please complete the following information):**

| react-native-elements |         1.2.7
| react-native |                          0.59

**Comment by Qiyu8** [comment]
That's weird because iphone 8 plus has the same pixalRadio with iphone 11, They should performed in the same way, while using normalize, RNE enlarge iphone 8's size with 1.25 Multiples,  and iphone 8 plus&iphone 11 with 1.27 Multiples.

**Comment by Qiyu8** [comment]
@iRoachie I found a piece of code [here ](https://github.com/NewBieBR/react-native-normalize/blob/master/src/index.ts) that can fix this issue and [#2153](https://github.com/react-native-elements/react-native-elements/issues/2153), what do you think?

**Comment by mi-mazouz** [comment]
Sorry I was totally wrong about the pictures, I updated them correctly

**Comment by mi-mazouz** [comment]
@Qiyu8 The first link you sent works fine!

**Comment by flyingcircle** [comment]
Going to track this issue from #2153
