### ISSUE TITLE
Tooltip Direction cannot be horizontal screen

### ISSUE THREAD

**Issue by lhaiqing** [react-native-elements/react-native-elements#2210]
react-native 0.58
Direction cannot be horizontal screen

**Comment by Qiyu8** [comment]
Can you describe in more detail? as far as I know, Tooltip don't have direction prop.

**Comment by craig1123** [comment]
I believe @lhaiqing is referring to Landscape mode (turning the phone horizontally). I can verify this. When opened, the tooltip turns the whole screen to portrait mode and moves the children prop around.

**Comment by arpitBhalla** [comment]
Can you confirm in v4 beta?
