### ISSUE TITLE
Badge component should expose textProps

### ISSUE THREAD

**Issue by VytautasLozickas** [react-native-elements/react-native-elements#2212]
**Is your feature request related to a problem? Please Describe.**
When font scaling is enabled in a device there's no way to apply `allowFontScaling` property to `Badge` component.

**Describe the solution you'd like**
Exposing `textProps` (of the `Text` component) would allow setting this prop (`allowFontScaling`) to `false` in turn resolving the problem.

**Describe alternatives you've considered**
I can apply `allowFontScaling` to static `defaultProps` of react-native `Text` component, but it doesn't play nice with TypeScript and latest React.

**Comment by xavier-villelegier** [comment]
@VytautasLozickas You can directly pass a custom `Text`:
```jsx
<Badge value={<Text>whatever</Text> />}
```

**Comment by flyingcircle** [comment]
On the one hand, there's the workaround with passing your own Component, but then you're losing the default styling and would end up having to recreate it in your own app. So I agree that this would be a good enhancement.
