### ISSUE TITLE
Slow rendering of Checkbox

### ISSUE THREAD

**Issue by Niryo** [react-native-elements/react-native-elements#2217]
I Am trying to render a list of checkboxes, but the checkbox themselves renders very slow.
I added a gif that shows the problem: you can see that in the first run (after refreshing the simulator), the checkboxes take a lot of time to render and the flicker is visible, but in the second run they are probably cached and being render immediately.
I tried a simple page with just couple of checkboxes and nothing else, and the problem reproduces.
It worth to mention that regular checkboxes of react-native renders smoothly in my case.

![slow checkbox gif](https://user-images.githubusercontent.com/8758348/70819645-68b7a600-1ddf-11ea-97e0-988498de5a54.gif)

**Comment by Qiyu8** [comment]
Can you paste your low performance code snippet here?

**Comment by Niryo** [comment]
I created a small app that demonstrates the problem: https://github.com/Niryo/TestReactNativeElementsCheckbox
you can clone it and after `npm install` just run `expo start`. you can see that any time you refresh the simulator, the checkboxes flicker.

**Comment by Niryo** [comment]
I have also opened an issue in expo/vector-icons:
https://github.com/expo/vector-icons/issues/117

**Comment by flyingcircle** [comment]
As stated from the expo team:
> this is a common thing to see in expo client because the icon font is loaded on demand over http the first time it's used. this isn't an issue when you do a standalone app build because it's bundled in the binary.

>to get rid of this delay in expo client you can preload the font:
https://github.com/expo/expo/blob/c8a6b90f678483ac8b6f6ca2041059a616c3e232/templates/expo-template-tabs/App.js#L29-L33
