### ISSUE TITLE
How about adding an example module in this repository？

### ISSUE THREAD

**Issue by Qiyu8** [react-native-elements/react-native-elements#2218]
**Is your feature request related to a problem? Please Describe.**
 I'm always frustrated when searching for some standard official code snippet about how to use RNE components correctly, I have to jump to the https://react-native-elements.github.io/react-native-elements/ in order to get what I want , which is not convenient and sometimes confusing because some code snippet is incomplete. 

**Describe the solution you'd like**
How about add an example module in this repository, just like [react-native-canlendars](https://github.com/wix/react-native-calendars/tree/master/example) , I think this is a good way to publicize RNE,anyone can get the runnable component demo instantly.

**Describe alternatives you've considered**
If anyone agree with this idea, we can maintain the example module together! 

**Additional context**

**Comment by oxyii** [comment]
@Qiyu8 something like [this](https://github.com/react-native-elements/react-native-elements-app)?

**Comment by Qiyu8** [comment]
@oxyii This is an app with high integrity. It's a good sample to demonstrate what RNE can do, But what I want is an example for every single componentwith full props. (in RNE case, I mean 21 demo pages)

**Comment by oxyii** [comment]
I think existing examples are enough. if you have a desire to experiment, here are my experiments on this subject https://github.com/react-native-elements/react-native-elements/issues/1851#issuecomment-478279304
