### ISSUE TITLE
Looking for Core contributors!

### ISSUE THREAD

**Issue by Monte9** [react-native-elements/react-native-elements#2222]
React Native Elements is (and always has been) a **community-first project**. That means that a core group of contributors has led the project in their spare time with the help of 100's of individual contributors.

<a href="https://github.com/react-native-elements/react-native-elements/graphs/contributors"><img src="https://opencollective.com/react-native-elements/contributors.svg?width=890&button=false" /></a>

Also, in an effort to better support our contributors, we have an **[OpenCollective fund with over $2000](https://opencollective.com/react-native-elements)**. We use this fund to compensate for the time and effort put in by the contributors to improve this library.

Unfortunately, the core team of contributors no longer have the time and/or resources to continue maintaining and leading this project. Hence we are looking for experienced React Native Open Source developers to join the core team and lead this library.

#### What we are looking for:

- 2+ years of experience as a React Native developer
- [Bonus] Have experience maintaining an open-source library

#### What you get to do:

- Provide valuable feedback on PR's to help individual contributors write better code
- Decide which PR's to merge based on the roadmap of the library
- Answer and close issues
- Manage releases and own the roadmap for future versions
- Experience working closely with the core team
- Experience maintaining a popular open-source library
- Compensation of $150/month for leading the project

If this sounds like the right fit for you, please join our [Slack](https://react-native-elements-slack.herokuapp.com/) and DM @monte9 or @iRoachie. 😃

**Comment by tarang9211** [comment]
Hello everyone! I would be happy to help contribute/lead this initiative! Looking forward.

**Comment by Usamaliaquat123** [comment]
@Monte9  @iRoachie  Thanks sure will do 🎉. I'm interested 🙌

**Comment by dig22** [comment]
@iRoachie  / @Monte9 , 

> please join our [Slack ](https://reactnativetraining.herokuapp.com/)

Slack Link no longer works, Looking forward to contribute 

Thanks

**Comment by sharpercoder** [comment]
I would be really happy to join to the team and help. :) 

Slack link is not working, how can I join to your team.

**Comment by Monte9** [comment]
@dig22 @sharpercoder fixed the link. 

https://react-native-elements-slack.herokuapp.com/

Feel free to DM me on Slack.

**Comment by ansarikhurshid786** [comment]
I would be happy to join and contribute as much as i can.

**Comment by hengkx** [comment]
Can I become a collaborator please?
