### ISSUE TITLE
How does onCancel not delete the input box content?  

### ISSUE THREAD

**Issue by wxxxxxxxx** [react-native-elements/react-native-elements#2223]
How does onCancel not delete the input box content?

**Comment by Qiyu8** [comment]
onCancel is used to remove the focus from the input box, not to delete the content.

**Comment by oxyii** [comment]
@wxxxxxxxx https://github.com/react-native-elements/react-native-elements/issues/2184

**Comment by Qiyu8** [comment]
> @wxxxxxxxx may be related #2184
> 
> @Qiyu8 looks like you are wrong
> 
> https://github.com/react-native-elements/react-native-elements/blob/98962d6aed51d82f49dfdefa8032a808c5db70cb/src/searchbar/SearchBar-ios.js#L58-L59
on SearchBar-android.js, The code is diffrent.
```
cancel = () => {
    this.blur();
    this.props.onCancel();
  };
```

**Comment by flyingcircle** [comment]
I tested this out on both iOS and Android for all 3 versions of Searchbar, try updating to RNE v2. Let me know if it still isn't working
