### ISSUE TITLE
Default Icon set for the Components

### ISSUE THREAD

**Issue by smartameer** [react-native-elements/react-native-elements#2227]
I was linking react-native-vector-icons and was deleting some of the unused font files from build, and it gave me error saying MaterialIcons is required because SearchBar uses the default Icon search and clear.

When I went to your code the [getIconType.js](https://github.com/react-native-elements/react-native-elements/blob/next/src/helpers/getIconType.js), it has the switch case default registerd to MaterialIcons, and because of that some of my icons are IonIcons and some default ones are MaterialIcons.

I wanted my app's IOS to use IonIcons & android to use MaterialIcons. But there is no such way other than overriding with the components props (LeftIcon, RightIcon, CloseIcon etc...) with my wished icons may be based on OS

Can a registerHelper can be exposed to set defaultIcon set for the OS, in that way I can be specific to use one icon for ios and other for android if not set it can always use MaterialIcons for both

**Comment by anthowm** [comment]
+1

**Comment by iRoachie** [comment]
Best way to do this at the moment is via the ThemeProvider. You can do exactly what you're saying in one place.
