### ISSUE TITLE
ListItem pad prop not working for web

### ISSUE THREAD

**Issue by felix4321** [react-native-elements/react-native-elements#2230]
**What I did**

I am developing a react-native (version 0.61.5) Expo-App with a **ListItem** (react-native-elements version 1.2.7). 

**Bug**

The problem is, that the pad prop (for the space between Avatar and title/subtitle) only is working in my Android/iOS-App. In my Web-App the space is zero.

I also started the 'react-native-elements/react-native-elements-app' locally. There is also no space and the pad props does not work (see screenshot).

![Screenshot 2020-01-04 at 23 00 16](https://user-images.githubusercontent.com/50043030/71772184-2d744700-2f47-11ea-8429-c8721cea9d35.png)

**Expected behavior**

The space (configured via  the pad prop) should also appear in the Web-App like in the iOS App:

![Screenshot 2020-01-04 at 23 25 25](https://user-images.githubusercontent.com/50043030/71772304-952b9180-2f49-11ea-88b9-918c230d3148.png)

**Comment by felix4321** [comment]
I found a workaround. I set the pad to 0 and implement my own spacing:

```
<ListItem
   pad={0}
   leftAvatar={{ source: { uri: conversation.avatarUrl } }}
   key={conversation.id}
   title={ conversation.name &&
           <Text style={{
             marginLeft: 16
           }}>
              {conversation.name}
          </Text>
} />
```

**Comment by ivanee** [comment]
This line line appears to be causing the problem: ListItem.js:369
`            child && [child, index !== length - 1 && <View width={pad}></View>]`

Padding works when this is changed to:
`            child && [child, index !== length - 1 && <View style={{padding-left:pad}}></View>]`

**Comment by flyingcircle** [comment]
I've been trying to recreate this issue, but all I see when I start up is that the Title is centered in the middle of the component even when the `pad` is set to 0. Have you tried again with RNE 2.0.0?
![Screen Shot 2020-05-07 at 8 27 20 AM](https://user-images.githubusercontent.com/5239875/81313308-93c7be00-903c-11ea-9929-d2f8decfb334.png)
