### ISSUE TITLE
Support for the `accessibilityLabel` prop

### ISSUE THREAD

**Issue by Bradzer** [react-native-elements/react-native-elements#2231]
**Is your feature request related to a problem? Please Describe.**
There is no support for the `accessibilityLabel` prop for UI automation test purposes on react native elements components.

**Describe the solution you'd like**
It would be great to have the components support the `accessibilityLabel` just like other React Native components like `View` do.

**Comment by flyingcircle** [comment]
I'm not sure I understand what you mean. I have been able to set the `accessibilityLabel` on most any component I use regularly. Is there a specific component that isn't working?
