### ISSUE TITLE
How to change the bottom border color the header?

### ISSUE THREAD

**Issue by dmargu** [react-native-elements/react-native-elements#2234]
I am using the header component and it is working great except there is a white line at the bottom of it that I cannot seem to change. How is it possible to change this line? I want to make it a light grey and decrease the width.

My component is as follows:
```
<Header
        leftComponent={<MenuButton navigation={this.props.navigation} />}
        centerComponent={<Text style={styles.screenTitle}>{this.props.screenName}</Text>}
        backgroundColor={colors.mainDark}
        containerStyle={styles.viewStyle}
        barStyle='light-content'
 />
```
And the style:
```
  viewStyle: {
    borderWidth: 0.25,
    borderColor: colors.mainDark
  },
```
![image](https://user-images.githubusercontent.com/51426359/71857106-44847780-30b4-11ea-8a5a-45d3cc40da89.png)

**Comment by oxyii** [comment]
@dmargu Please try to use `borderBottomColor` and `borderBottomWidth` instead of `borderColor` and `borderWidth`

**Comment by dmargu** [comment]
That was it. Thank you.
