### ISSUE TITLE
leftAvatar doesn't load local images (listItem)

### ISSUE THREAD

**Issue by sunsetjesus** [react-native-elements/react-native-elements#2235]
**What works** - 

 <ListItem

                                key={list.item.TID} 
                                leftAvatar={{ source: { uri: "https://s3.amazonaws.com/uifaces/faces/twitter/ladylexy/128.jpg"} }} 
                                title={this.render_timestamp.bind(this,list.item.t_accept_timestamp)}
                                subtitle={list.item.v_reg_no}
                                refreshing={this.api_call_on} 
                                bottomDivider 
                                chevron 
                                onPress={this.do_navigate.bind(this,list.item.TID)} 
                           /> 

**What doesn't work** - 

 <ListItem

                                key={list.item.TID} 
                                leftAvatar={{ source: { uri: "path to local image"} }} 
                                title={this.render_timestamp.bind(this,list.item.t_accept_timestamp)}
                                subtitle={list.item.v_reg_no}
                                refreshing={this.api_call_on} 
                                bottomDivider 
                                chevron 
                                onPress={this.do_navigate.bind(this,list.item.TID)} 
                           /> 

Is this a bug?

**Comment by oxyii** [comment]
@sunsetjesus 
```jsx
<ListItem
  leftAvatar={{ source: require('path to local image') }}
  ...
/>
```

**Comment by sunsetjesus** [comment]
thanks a lot.
