### ISSUE TITLE
VS Code Intellisense not working after some time

### ISSUE THREAD

**Issue by Skullcan** [react-native-elements/react-native-elements#2236]
Hi guys, first, thanks for this awesome lib.

I'm using RNE in a new project and having a blast. But there's something interfering with the VS Code intellisense.

First when you open up the project everything works fine. Then after you type some lines in the components you have the intellisense stops.
No help or auto completion at all. Just Loading..... Even for react native components and classes.
Then if you reopen the VS Code it start working again.

| VS Code |Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT (Server) x64 10.0.14393

| react-native-elements |  1.20       |
| react-native                 | 0.61.5      |

PS: I tested this on mac OS Catalina and it is fine.

Thanks again!

**Comment by Sameer-Ijaz** [comment]
It's pretty easy to get it up & working again using this. https://www.youtube.com/watch?v=59vqVqIGEe8&feature=youtu.be
