### ISSUE TITLE
Invariant Violation: [...,"top: <<NaN>>",...] is not usable as a native method argument

### ISSUE THREAD

**Issue by vikjovanov** [react-native-elements/react-native-elements#2237]
**Explain what you did**

I use "tooltip" to indicate a message when a user press on a text.
This tooltip is located on a text that is in an Item of a flatlist.

**Expected behavior**

I want the tooltip to show up!

**Describe the bug**

The tooltip works very well! However, if the flatlist item is located very low in the flatlist rendering window and I click on the text, I get an ugly error like this:

Tip: It only seems to happen on Android.

**To Reproduce**

- Make a flatlist with some large (in height) item
- Put a text at the bottom of this item
- Create an absolute view that wrap the text and apply it a tooltip (cause there is a problem with statusbar on Android)
- Scroll the items, when a text with tooltip is at the bottom of the rendering window, click on it.

**Screenshots**

![Screenshot_2020-01-11-11-44-16](https://user-images.githubusercontent.com/43797348/72203235-44e09200-3469-11ea-932b-ea73ee727316.png)

**Your Environment (please complete the following information):**

```bash
react-native info

System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 1.69 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.1 - /usr/local/bin/node
    npm: 6.13.4 - ~/.npm-global/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^3.0.4 => 3.0.4
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
```

```bash
react-native elements version

react-native-elements": "^1.1.0
```

**Comment by oxyii** [comment]
@vikjovanov Hmmm... Looks like something wrong on this line
https://github.com/react-native-elements/react-native-elements/blob/98962d6aed51d82f49dfdefa8032a808c5db70cb/src/tooltip/Tooltip.js#L97
Can you make a simple [snack](http://snack.expo.io/) to reproduce it?

**Comment by MustaphaGhlissi** [comment]
You should provide only number, or an expression that return a number

Exp: 
`top: 15`

**Comment by daimonkor** [comment]
> 
> 
> **Explain what you did**
> 
> I use "tooltip" to indicate a message when a user press on a text.
> This tooltip is located on a text that is in an Item of a flatlist.
> 
> **Expected behavior**
> 
> I want the tooltip to show up!
> 
> **Describe the bug**
> 
> The tooltip works very well! However, if the flatlist item is located very low in the flatlist rendering window and I click on the text, I get an ugly error like this:
> 
> Tip: It only seems to happen on Android.
> 
> **To Reproduce**
> 
>     * Make a flatlist with some large (in height) item
> 
>     * Put a text at the bottom of this item
> 
>     * Create an absolute view that wrap the text and apply it a tooltip (cause there is a problem with statusbar on Android)
> 
>     * Scroll the items, when a text with tooltip is at the bottom of the rendering window, click on it.
> 
> 
> **Screenshots**
> 
> ![Screenshot_2020-01-11-11-44-16](https://user-images.githubusercontent.com/43797348/72203235-44e09200-3469-11ea-932b-ea73ee727316.png)
> 
> **Your Environment (please complete the following information):**
> 
> ```shell
> react-native info
> 
> System:
>     OS: macOS 10.14.6
>     CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
>     Memory: 1.69 GB / 16.00 GB
>     Shell: 5.3 - /bin/zsh
>   Binaries:
>     Node: 10.16.1 - /usr/local/bin/node
>     npm: 6.13.4 - ~/.npm-global/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
>   IDEs:
>     Android Studio: 3.5 AI-191.8026.42.35.6010548
>     Xcode: 10.3/10G8 - /usr/bin/xcodebuild
>   npmPackages:
>     @react-native-community/cli: ^3.0.4 => 3.0.4
>     react: 16.8.6 => 16.8.6
>     react-native: 0.60.4 => 0.60.4
> ```
> 
> ```shell
> react-native elements version
> 
> react-native-elements": "^1.1.0
> ```

The same bug reproduced for flatlist and tooltip exists into list item (bug reproduced when scrolled list)

**Comment by irodeanu** [comment]
Same issue `"react-native-elements": "^1.2.7"` android

**Comment by SevakAvet** [comment]
Same issue "react-native-elements": "^1.2.7", Android

**Comment by ezranbayantemur** [comment]
Not any problem on 0.61.5 but occurs on 0.62.2

**Comment by flyingcircle** [comment]
I've tried reproducing this error to no success, so either someone needs to post their code that is causing this and create a snack, or I won't be able to make headway on this.

**Comment by LucidNinja** [comment]
I was getting this issue but managed to fix it by waiting for the screen to finish painting, by using the requestAnimationFrame method

`requestAnimationFrame(() => tooltipRef.current?.toggleTooltip());`

**Comment by LucidNinja** [comment]
However, I'm still having an issue on older Android devices that seem to be ignoring the new skipAndroidStatusBar prop. That is, the requestAnimationFrame fix removes the error, but doesn't allow it time to get the right position, and so the tooltip's yOffset is higher than it should be.

**Comment by LucidNinja** [comment]
@flyingcircle I've created a PR which is a simple, single line of code. Unfortunately it failed the Travis CI verification - not sure why? But I can verify that this fix is working for me locally. Let me know if the PR was submitted incorrectly?

**Comment by bernhardt1** [comment]
This is occuring on my Samsung s9+. I wouldn't consider it a slower device.

**Comment by renjfk** [comment]
This is still occurring for some cases especially on simulator and when hermes is enabled which ends up with app crashing. For now as workaround providing default values to measure callback seems to be resolving issue at least for my situation (manual toggle). Even if it gets wrong positioning at first since toggleTooltip hence getElementPosition is called every time it ends up with correct ones ultimately without any glitch. I could create another PR for this kind of situation as safety measure since I don't see any harm with this kind of change.

```javascript
...
  getElementPosition = () => {
    const { skipAndroidStatusBar } = this.props;
    this.renderedElement &&
      this.renderedElement.measure(
        (
          frameOffsetX,
          frameOffsetY,
          width = 0,
          height = 0,
          pageOffsetX = 0,
          pageOffsetY = 0
        ) => {
...
```

**Comment by alon7** [comment]
@renjfk Thanks for sharing the solution. I managed to patch the package and use it together with hermes successfully.

**Comment by RonRadtke** [comment]
I have the same problem. using the <Icon> component form RNE doesn't help.

**Comment by appsgenie** [comment]
Should this issue still happen on ^3.4.3 ? I am using "react-native-elements": "^3.4.3" and still get this error.

**Comment by appsgenie** [comment]
hi any idea from anyone how to avoid this? still happening on Android for me. mainly when i conditionally render the tooltip for a variable that gets populated later in the component cycle..
