### ISSUE TITLE
Setting Text styles by ThemeProvider does not work [Web]

### ISSUE THREAD

**Issue by subroh0508** [react-native-elements/react-native-elements#2243]
**Explain what you did**

I tried react-native-elements on Android and Web.
Setting color used by ThemeProvider, and setting padding locally. Like this.

```javascript
// index.js
const commonTheme = {
  Text: {
    style: {
      color: '#afeeee', 
    },
  },
};

export const TestComponent = () => (
  <ThemeProvider theme={ commonTheme }>
    <App/>
  </ThemeProvider>
);

// App.js
export const SignIn = () => {
  const { theme } = useContext(ThemeContext);
  const styles = withStyles(theme);

  return (
    <Text style={ styles.title }>Title</Text>
  );
}

const withStyles = ({ colors }) => (
  StyleSheet.create({
    title: {
      paddingTop: 8,
      paddingBottom: 16,
    },
  })
);
```

**Expected behavior**

Applying same color both Android and Web.

**Describe the bug**

The color on Web does not apply.

**To Reproduce**

Actually code here
- generate common theme: https://github.com/subroh0508/ID44/blob/32029954970a051b4a873c4e9a2953f807339091/frontend/assets/themes.js#L40-L44
- set locally theme: https://github.com/subroh0508/ID44/blob/32029954970a051b4a873c4e9a2953f807339091/frontend/components/signin/containers/SignIn.js#L32-L34

**Screenshots**

[Android]
<img width="409" alt="MacScreenShot 2020-01-20 2 17 32" src="https://user-images.githubusercontent.com/8080435/72685247-af5d9600-3b2b-11ea-9799-6bf4d3903330.png">

[Web]
<img width="580" alt="MacScreenShot 2020-01-20 2 18 34" src="https://user-images.githubusercontent.com/8080435/72685251-b4bae080-3b2b-11ea-9f5d-b2c26791ea6e.png">

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.2.7   |
| react-native          |    0.61.3   |
| react-native-web | 0.11.7 |

**Comment by xstable** [comment]
Same on 
software | version
-- | --
react-native-elements | 2.0.0
react-native | 0.62.2
react | 6.11.0

**Comment by flyingcircle** [comment]
I tried this out with react-native-web 0.12, and react 16.13 using this app: https://github.com/react-native-elements/create-react-app-example

And it works. Try updating your libraries, otherwise, I'd look into seeing what other styling or tools you might be using that is interfering with this.
