### ISSUE TITLE
More Social Media Icons need to be added.

### ISSUE THREAD

**Issue by tusharojha** [react-native-elements/react-native-elements#2244]
## Social Media Icons 

1. TikTok

## Need of Tabs Layout

Something similar to react-native-tab-view

**Comment by Usamaliaquat123** [comment]
@tusharojha  thanks. 🎉 You will need to open this issue in `react-native-vector-icons` cause icons are imported from `react-native-vector-icon` 🎉

**Comment by tusharojha** [comment]
Okay, Sure!
