### ISSUE TITLE
The Facebook SocialIcon doesn't follow the brand guidelines from FB

### ISSUE THREAD

**Issue by raRaRa** [react-native-elements/react-native-elements#2245]
The Facebook type for `SocialIcon` doesn't follow the brand guidelines from Facebook. The F icon should have a white background like in the following screenshot:

<img src="https://scontent.frkv1-1.fna.fbcdn.net/v/t39.2365-6/18928641_251957295286418_4362086450741641216_n.png?_nc_cat=111&_nc_eui2=AeG3bsyJV9kRrPljVvB00_bV2TPaRwKvo6HGxntG25xFR6VWsgoym-cFXFEG8z01eB9P-Hh7vxx6S-USOtEQPjLnY8bzV217Uo_AiUDQLQXt0A&_nc_ohc=_UBqY4_jERkAX_5Dq6F&_nc_ht=scontent.frkv1-1.fna&oh=4d649f6aeb4a0d827089ccab3d4888b2&oe=5ECA7105" />

> Do use the version of the “f” logo that comes with a blue box on white or light colored backgrounds and the version of the logo that comes on a white box on blue or dark colored backgrounds

Ref: https://developers.facebook.com/docs/facebook-login/userexperience

I have SVG for this F logo, if that would be helpful. Otherwise the brand assets can be found on https://en.facebookbrand.com/

Thanks.

**Comment by Usamaliaquat123** [comment]
@raRaRa  thanks. You can change the color by passing the `iconColor` prop. Well you are right by `default` this need to be `blue`.
