### ISSUE TITLE
Slider thumb not in track when component loads

### ISSUE THREAD

**Issue by pavithra-expedux** [react-native-elements/react-native-elements#2248]
**Explain what you did**
    Simply i create component and added slider in it.

**Expected behavior**
Thumb should set on the track

**Describe the bug**
 When i render component thumb loads from below to the track and afterwards sets on the track.
In given snack i simply added slider inside component for showing bug clearly. 

But my exact scenario is i added this slider inside the modal. When modal opens slider thumb displays from below to the track and slowly it sets onto the track

**To Reproduce**
https://snack.expo.io/@git/github.com/pavithra-expedux/expo_slider

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     1.1.0    |
| react-native          |    0.61.4     |

**Comment by flyingcircle** [comment]
I don't see this happening on the snack. Confirm if this is still happening in `2.1.0` and update your snack as well to show reproduction, and I can reopen the ticket if so.
