### ISSUE TITLE
Element type is invalid when using DatePicker in inputComponent of <Input/>

### ISSUE THREAD

**Issue by BBenGit** [react-native-elements/react-native-elements#2256]
I have a form with mulitples `<Input/>` components, and in one of them I want to replace the `TextInput` with a date picker. I choose [this date picker](https://www.npmjs.com/package/react-native-datepicker) that works perfectly in my form but when i put it inside the `inputComponent` it triggers this error :

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of Input.
```

**Expected behavior**

I want the `DatePicker` to replace the `TextInput` as said in the doc.

**Describe the bug**

**To Reproduce**

```
<Input
            containerStyle={styles.input}
            label="date."
            inputComponent={
              <DatePicker
                style={{ width: 200 }}
                date={this.state.date}
                mode="date"
                placeholder="select date"
                format="YYYY-MM-DD"
                minDate="2016-05-01"
                maxDate="2016-06-01"
                confirmBtnText="Confirm"
                cancelBtnText="Cancel"
                customStyles={{
                  dateIcon: {
                    position: "absolute",
                    left: 0,
                    top: 4,
                    marginLeft: 0
                  },
                  dateInput: {
                    marginLeft: 36
                  }
                  // ... You can check the source to find the other keys.
                }}
                onDateChange={date => {
                  this.setState({ date: date });
                }}
              />
            }
          />
```

**Screenshots**

<img width="230" alt="image" src="https://user-images.githubusercontent.com/44926723/73738515-e0051880-4744-11ea-871d-3e0c9da35102.png">

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     1.2.7    |
| react-native          |    16.12.0     |

**Comment by iqbalfaisal** [comment]
@BBenGit write like this  ` inputComponent={()=><>your component</>}`

**Comment by BBenGit** [comment]
It works perfectly thx !
