### ISSUE TITLE
latest version 1.2.7 not working with react-native-web 0.12.0

### ISSUE THREAD

**Issue by 28harishkumar** [react-native-elements/react-native-elements#2257]
**Explain what you did**

- created a new project
- added react-native-elements (1.2.7)
- added react-native-web (0.12.0)
- write hello world code

**Expected behavior**

should print hello world

**Describe the bug**
```
 web  Failed to compile.
project_path/node_modules/react-native-elements/src/config/ViewPropTypes.js
Module not found: Can't resolve 'react-native-web/dist/exports/ViewPropTypes' in 'project_path/node_modules/react-native-elements/src/config'
```

**It is working with `react-native-web: 0.11.7`** 
I found that  0.12.0 is released just 9 days before. **[And they are not going to maintain ViewPropTypes](https://github.com/necolas/react-native-web/issues/1512#issuecomment-568180289).**

**Comment by samereberlin** [comment]
+1... The latest RNE version is not working with RNW 0.12.1 as well (due to the same reason: removal of deprecated APIs). Thanks!

**Comment by zamponotiropita** [comment]
PropStyles (e.g. Image.propTypes) are deprecated in the current RN version. Please remove them.
Otherwise compatibility with the current react-native-web (1.12.0) is broken as it has completely removed PropTypes

**Comment by flyingcircle** [comment]
I believe this is also a requirement for compatibility with RN 62, they removed propTypes from RN core, and I don't think there's a community version quite yet. But it looks like RN is suggesting either using Flow or Typescript instead. Does anyone have experience or thoughts as to which direction we should go for this?

**Comment by flyingcircle** [comment]
There's another issue is that `react-native-vector-icons` is also not at a version that can support rn-web 0.12. Even with this fix, I'm not sure that RN-elements will be able to run with RN-web 12 due to that dependency.  @iRoachie I think this issue will have to wait for beyond version 2.0.0. Do you agree?

**Comment by Monte9** [comment]
@flyingcircle thanks for fixing this in `react-native-ratings`. I have published a new version - v7.0

**Comment by flyingcircle** [comment]
@28harishkumar or @samereberlin can you test out my branch to see if it works for web 0.12 now? To double check the work.

**Comment by samereberlin** [comment]
Hi @flyingcircle , yes it works :-) Thanks!

**Comment by MahmoudShaeer** [comment]
:/ can any one help me  same issue here :/
