### ISSUE TITLE
ListItem title View is rendered even when no title is set

### ISSUE THREAD

**Issue by Oize** [react-native-elements/react-native-elements#2259]
**Explain what you did**

I want to make a ListItem without title, but it's view is still rendered.

**Expected behavior**

If title is not specified its View shouldn't be rendered.

**Describe the bug**

Title is currently set as an empty string in defaultProps while the check in render compares it to undefined hence always triggers render.

**Screenshots**

<img width="429" alt="Screenshot 2020-02-10 at 02 16 17" src="https://user-images.githubusercontent.com/14310999/74112275-34c4eb00-4bac-11ea-84a8-3a21c94e864b.png">

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     1.2.7    |
| react-native          |     expo sdk-35    |

**Comment by himanishm07** [comment]
https://github.com/react-native-elements/react-native-elements/pull/2436 

@flyingcircle pull request for the same
