### ISSUE TITLE
Issue with the Slider component in a horizontal FlatList since React Native 0.61 [iOS only]

### ISSUE THREAD

**Issue by superKalo** [react-native-elements/react-native-elements#2260]
I have the following structure (pseudo-code):

```jsx
<ScrollView>
    <FlatList horizontal={true}>
        <Slider />
    </FlatList>
</ScrollView>
```

With React Native 0.59, swiping the slider was working perfectly fine (Expo SDK v35).
Since updating to React Native 0.61 (Expo SDK v36) swiping the Slider is triggering the FlatList scroll too.

**Expected behavior & Describe the bug**

When I swipe the Slider - the FlatList scrolling should not get triggered too. Or in general, the Slider component should block all other interfering scroll events while it gets swiped.

**To Reproduce**

I re-created the bug on a [Snack](https://snack.expo.io/@superkalo/react-native-elements-slider-nested-in-a-flatlist).

On Android - all good. On iOS however - when you swipe (change) the Slider value, the FlatList and the ScrollView gets scrolled too. Blah.

Android (all good):

![ezgif-3-36d8dc4beba0](https://user-images.githubusercontent.com/2548061/74337036-33f8a880-4da8-11ea-80da-b2e46c1edf87.gif)

iOS: issue:

![ezgif-3-1b5d1c94ae5f](https://user-images.githubusercontent.com/2548061/74337366-d44ecd00-4da8-11ea-809e-82f62f58cf1d.gif)

**Environment:**

| software              | version |
| --------------------- | ------- |
| react-native-elements | 1.2.7 |
| react-native          | 0.61 |

**Comment by superKalo** [comment]
I updated my issue with a [Snack](https://snack.expo.io/@superkalo/react-native-elements-slider-nested-in-a-flatlist) and GIFs showcasing the issue 👆 

It turned out that the issue only happens on iOS. On Android it works just fine.

**Comment by flyingcircle** [comment]
Looking at the other tickets you opened in react-native, it looks like you determined the issue was not with RNE.

**Comment by superKalo** [comment]
I'm not really sure about anything anymore.

I'd appreciate if you investigate when you have time because the issue is still present :)

**Comment by FaizyQadri** [comment]
> I have the following structure (pseudo-code):
> 
> ```js-jsx
> <ScrollView>
>     <FlatList horizontal={true}>
>         <Slider />
>     </FlatList>
> </ScrollView>
> ```
> 
> With React Native 0.59, swiping the slider was working perfectly fine (Expo SDK v35).
> Since updating to React Native 0.61 (Expo SDK v36) swiping the Slider is triggering the FlatList scroll too.
> 
> **Expected behavior & Describe the bug**
> 
> When I swipe the Slider - the FlatList scrolling should not get triggered too. Or in general, the Slider component should block all other interfering scroll events while it gets swiped.
> 
> **To Reproduce**
> 
> I re-created the bug on a [Snack](https://snack.expo.io/@superkalo/react-native-elements-slider-nested-in-a-flatlist).
> 
> On Android - all good. On iOS however - when you swipe (change) the Slider value, the FlatList and the ScrollView gets scrolled too. Blah.
> 
> Android (all good):
> 
> ![ezgif-3-36d8dc4beba0](https://user-images.githubusercontent.com/2548061/74337036-33f8a880-4da8-11ea-80da-b2e46c1edf87.gif)
> 
> iOS: issue:
> 
> ![ezgif-3-1b5d1c94ae5f](https://user-images.githubusercontent.com/2548061/74337366-d44ecd00-4da8-11ea-809e-82f62f58cf1d.gif)
> 
> **Environment:**
> 
> software	version
> react-native-elements	1.2.7
> react-native	0.61

const { width } = Dimensions.get('screen');

<FlatList
 onScroll={(e) => {
            var scrollX = e.nativeEvent.contentOffset.x
            console.log(scrollX, 'scrooll ')
            var index = Math.ceil(scrollX / width)
            setIndicator(index)
          }}/>

---------------------------------------------------------------
on my scroll if i calculate the width by floor the first index is repeating twice n foe ceil the last one

**Comment by talhatsk** [comment]
@FaizyQadri @superKalo found any fix for this ?
