### ISSUE TITLE
'opencollective' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by kimfucious** [react-native-elements/react-native-elements#2261]
**Explain what you did**
In an existing **expo generated** app, with `react-native-elements` already imported and working, I attempted to run ` npm install aws-amplify aws-amplify-react-native`.

I was trying to install some packages.

**Expected behavior**
The packages should be installed without error.

**Describe the bug**

```console
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-elements@0.19.1 postinstall: `opencollective postinstall`
npm ERR! Exit status 1
npm ERR!
```

**To Reproduce**
1.  create a new RN app using Expo
2.  install react-native-elements via npm
3. run npm i aws-amplify aws-amplify-react-native
4. get above error

**Your Environment (please complete the following information):**
react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
react-native-elements": "^1.2.7

**Comment by kimfucious** [comment]
For the record, this only happens when running in Powershell.

**Comment by kimfucious** [comment]
Apparently, installing opencollective globally solves this issue (`npm i -g opencollective opencollective-postinstall`), but I'm not sure if that's the best thing to do to really address this issue.

**Comment by flyingcircle** [comment]
I was able to install those packages locally without error in an expo app. This was likely an error with one of the packages that you tried to install and they have likely fixed the issue on their end.
