### ISSUE TITLE
Slider not draggable when TextInput is focus

### ISSUE THREAD

**Issue by functionwell** [react-native-elements/react-native-elements#2262]
**Explain what you did**
When TextInput is focus, try to drag Slider, the Slider thumb is not draggable, blur the TextInput then Slider is draggable

**Expected behavior**
Slider is draggable when TextInput is focus

**Describe the bug**
When TextInput is focus, try to drag Slider, the Slider thumb is not draggable, blur the TextInput then Slider is draggable

**To Reproduce**
use a React Native TextInput and Silder in same screen, when TextInput is focus, try to drag Slider, the Slider thumb is not draggable, blur the TextInput then Slider is draggable

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Screenshots**

![image](https://user-images.githubusercontent.com/18190879/74303302-52ed3f80-4d94-11ea-803e-152f53a16a62.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.2.7     |
| react-native          |    0.61.4     |

**Comment by flyingcircle** [comment]
Used Expo 38 with RNE `2.1.0` and was unable to reproduce the issue. Let me know if this is still an issue and create a snack showing the issue and then I can reopen.
