### ISSUE TITLE
Listitem top and bottom border properties issue

### ISSUE THREAD

**Issue by BBenGit** [react-native-elements/react-native-elements#2264]
Implemented a `ListItem` but the borders sometimes randomly doesn't show.

**Expected behavior**

![signal-attachment-2020-02-14-144810 copy](https://user-images.githubusercontent.com/44926723/74537699-e82a3880-4f3a-11ea-9b63-d547ce728214.png)

**Describe the bug**

There is no border between the two first elements. This bug happend throughout many projects.

![signal-attachment-2020-02-14-144810](https://user-images.githubusercontent.com/44926723/74537748-fed08f80-4f3a-11ea-8f05-665d4afc0e1d.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   1.2.7      |
| react-native          |    0.61.5     |

**Comment by flyingcircle** [comment]
Can you try running on latest version. If this is still happening on the latest version please let me know, but I can't reproduce this.

**Comment by flyingcircle** [comment]
I found out that the issue has to do with how RN/iOS/Android is placing items on the screen. The bottom border is set by using:
```borderBottomWidth: StyleSheet.hairlineWidth```

However it seems that every so often, RN draws a component ever so slightly 1 or 2 pixels off thus covering up the border line. So the only way that I have seen to fix this is to add:
```style={{padding: StyleSheet.hairlineWidth}}``` to `ListItem`.

**Comment by M-Jas** [comment]
@flyingcircle are you seeing this behavior on the Simulator or a Device? Or Both? I noticed this behavior once or twice before on the simulator, but on the device it was magically gone. I chalked it up to a drawing issue with debug on simulators.

**Comment by BBenGit** [comment]
@M-Jas I saw the issue on Android both simulator and real device.

**Comment by pranshuchittora** [comment]
I am able to reproduce the issue successfully. So the issue is with the rendering pipeline, on the scroll the lines appear and disappear.
This thread might help => https://github.com/facebook/react-native/issues/22927#issuecomment-559027303

**Comment by pranshuchittora** [comment]
A workaround, for the time being, is to set the width to `StyleSheet.hairlineWidth * 2` which decreases the change of such issue drastically.

**Comment by flyingcircle** [comment]
At least on the devices where I see this happen, changing the border width only kind of works. The border that wasn't visible is then newly visible again, but is thinner than the other borders. I still think this lies somewhere in React Native itself, but I'm still not sure what the root cause is. Item's not being properly rendered in a `ScrollView`?

**Comment by flyingcircle** [comment]
Removing the 3.0 milestone. I might try to log an error with react-native as that's where I believe the issue to be. But I wouldn't expect this issue to be fixed anytime soon.

**Comment by flyingcircle** [comment]
I think we've successfully shown that this is likely an issue with React Native's `ScrollView`. There are several tickets open there that mention this issue even without RNE. So I'm not sure we'll make any progress on this issue from this library.
