### ISSUE TITLE
SocialIcon Without Rounded Corners!

### ISSUE THREAD

**Issue by zaptrem** [react-native-elements/react-native-elements#2265]
**Is your feature request related to a problem? Please Describe.**
I'm about to rip my hair out! My Apple and Google SignIn buttons from other sources are square, but the only option for an FB button that isn't Native (you guys) is round!

**Describe the solution you'd like**
Square button (with slightly rounded edges, roundness preferably configurable)

**Describe alternatives you've considered**
Deleting the entire 6-months long project, dropping out, and becoming a hermit.

**Additional context**
It burns 
![image](https://user-images.githubusercontent.com/1612230/74707516-0ff1f880-51e8-11ea-9016-f3771c0ac07e.png)

**Comment by xavier-villelegier** [comment]
Hey @zaptrem 

You can just use the `style` props like this:

```jsx
<SocialIcon
  title='Sign In With Facebook'
  button
  type='facebook'
  style={{ borderRadius: 0 }}
/>
```

**Comment by zaptrem** [comment]
This solution worked perfectly for me. Still trying to align that Google logo but that isn’t your problem :P

Thanks!

**Comment by iRoachie** [comment]
@italomarca Definitely not. Best not to create props that directly mirror styles
