### ISSUE TITLE
Local theme not merging with internal theme

### ISSUE THREAD

**Issue by kimfucious** [react-native-elements/react-native-elements#2266]
Great product; thanks!

I feel like I've tried everything to get the Theme Provider working, so either I'm doing something stupid, or something is amiss.  Apologies in advance if it's the former.

**Explain what you did**

I've configured the Theme Provider like this at app's entry point:

**index.js**
```jsx
...
const AppWrapper = () => {
  const colorScheme = useColorScheme();
  return (
    <AppearanceProvider>
      <ThemeProvider theme={theme[colorScheme]}>
        <Authenticator hideDefault={true}>
          <CustomLogin override={"SignIn"} />
          <App />
        </Authenticator>
      </ThemeProvider>
    </AppearanceProvider>
  );
};

registerRootComponent(AppWrapper);
```
FYI:  this is an expo app and I've changed the entry point so as to wrap the app with a few things.

Also, the `useColorScheme()` allows `theme[colorScheme]` to produce `theme.light` or `theme.dark` according to the iOS screen appearance setting.

My local `theme.js` file is like this:

```js
const baseContainerStyles = {
  flex: 1,
  justifyContent: "center",
  alignItems: "center"
};

export const theme = {
  dark: {
    container: {
      ...baseContainerStyles,
      backgroundColor: "black",
      color: "white",
      width: "100%"
    }
  },
  light: {
    container: {
      ...baseContainerStyles,
      backgroundColor: "white",
      color: "black",
      width: "100%"
    }
  }
};
```

If I console log the value for `theme[colorScheme]` in the `index.js` file above, it shows the correct container values for the applicable screen appearance setting.

In the `<App>` component, wrapped by the Theme Provider, the `theme prop` exists; however, the values from the `theme.js` file, imported into `index.js` and added as a prop for `<ThemeProvider>` are not merged.

For example, the backgroundColor shows as `#FFF`.

I've even tried a simpler version of the file, eliminating the use of `theme[colorScheme]` and just using `theme` like this:

```js
<ThemeProvider theme={theme}>
```
and this:
```js
export const theme = {
  container: {
    backgroundColor: "hotpink",
    color: "white"
  }
};
```
... but the result is the same.

**What am I trying to accomplish**

I'm trying to use a single, custom theme file with Theme Provider.

**Expected behavior**

The `theme` prop should include the values from the `theme.js` file.

I expected the `theme` prop to include the values that I set in the `theme.js` file.

**Describe the bug**

Values in the custom theme object are not getting merged the theme object found in props. 

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |^1.2.7 |
| react-native          |https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz |

![image](https://user-images.githubusercontent.com/26792769/75091877-ba7d6900-55a4-11ea-956e-1b9a1cab65aa.png)

**Comment by kimfucious** [comment]
Okay, I just realized something:  the keys of `theme` in `props` are not from React Native Elements.  And, if I remove the Theme Provider tasks from `index.js`, the `theme` prop is still there.

If I move the Theme Provider inward like the below, `theme` becomes undefined, as soon as it's nested under the `Authenticator` tag.

```js
    <AppearanceProvider>
      <Authenticator hideDefault={true}>
        <ThemeProvider theme={theme[colorScheme]}>
          <CustomLogin override={"SignIn"} />
          <App />
        </ThemeProvider>
      </Authenticator>
    </AppearanceProvider>
```

FYI:  Authenticator is from AWS Amplify for providing Cognito sign-in functionality.

**Comment by kimfucious** [comment]
So the Authenticator component was overriding the `theme` prop.

I've found that the following fixes the situation.  I've used `theme={theme[colorScheme]}` as I can't pass an empty object without React Native throwing a red box:

```jsx
    <AppearanceProvider>
      <Authenticator hideDefault={true} theme={theme[colorScheme]}>
        <ThemeProvider theme={theme[colorScheme]}>
          <CustomLogin override={"SignIn"} />
          <App />
        </ThemeProvider>
      </Authenticator>
    </AppearanceProvider>
```
I'm gonna leave this open for a couple/few days, just in case someone has a better solution.

**Comment by kimfucious** [comment]
Unfortunately, I was mistaken in that this does work.

Whatever component (Authenticator / ThemeProvider) is placed within the other tramples the other's props.

**Comment by iRoachie** [comment]
Did you manage to figure out what was wrong? Wasn't sure based on what you said if you actually got it figured out

**Comment by kimfucious** [comment]
Thanks for the follow up, @iRoachie 

In brief, I...
-  got rid of the Amplify authentication wrapper, as it was driving me nuts.
-  opted out of using React Native Elements theme provider, as React Navigation (v5) has a nice `useTheme()` hook
- am maintaining `theme` object like a global stylesheet
- am using React Native's AppearanceProvider to check the iOS display setting (dark/light)

So a button looks like the below.

Although, I'm guessing that there might be a better way to do this, I haven't spent the time to find out what that could be.

```jsx
      <Button
        title="️🐌 Go to Slugbucket"
        titleStyle={ theme.buttons.outline.titleStyle }
        type="outline"
        buttonStyle={{
          ...theme.buttons.outline.buttonStyle,
          paddingLeft: 16,
          paddingRight: 18,
          marginTop: 18
        }}
        onPress={() => Linking.openURL("http://awesome.url")}
      />
```
