### ISSUE TITLE
react-native-elements / SearchBar - App crashes when entering '*' or '(' or ')'. - SyntaxError: Invalid regular expression: /*/: Nothing to repeat. 

### ISSUE THREAD

**Issue by asiriPiyajanaka** [react-native-elements/react-native-elements#2267]
![Simulator Screen Shot - iPhone 8 - 2020-02-24 at 16 02 28](https://user-images.githubusercontent.com/18325613/75145504-14a23980-571f-11ea-9ecc-3e02ebba9ed0.png)

**Explain what you did**

Enter some regex tin to searchBar.

**Expected behavior**

App should be showing search results as any other search.

**Describe the bug**

App crashed right after inserting above mentioned regex.

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.2.0     |
| react-native          |     0.60.5    |

**Comment by oxyii** [comment]
@asiriPiyajanaka Hmmm..... So strange. I see no one regexp checker in SearchBar component. https://snack.expo.io/@oxyii/rne-2267

May be RegExp checker works somewhere else?

**Comment by flyingcircle** [comment]
I have been unable to reproduce this issue. If this is still a problem, please let me know.
