### ISSUE TITLE
Detect when user stops typing in search bar

### ISSUE THREAD

**Issue by DuranMoodley** [react-native-elements/react-native-elements#2271]
I am trying to send a search request to the server and retrieve a set of results. I would like a way to detect when the user has stopped typing then execute the request to the server.
Please can someone assist me with this issue.  It would be great if there was some enhancement to this component to achieve this if possible.

**Comment by oxyii** [comment]
Something like [this](https://snack.expo.io/@oxyii/rne-2271)?
