### ISSUE TITLE
Update docs to use new Slack invite website

### ISSUE THREAD

**Issue by Monte9** [react-native-elements/react-native-elements#2281]
We have a public slack [reactnativetraining.slack.com](reactnativetraining.slack.com). Users would be able to request an invite through the website: https://reactnativetraining.herokuapp.com/

That website was outdated and so I have deployed a new website to serve the same purpose. Now users can join our slack through this website: https://react-native-elements-slack.herokuapp.com/

**TODO:** We need to update our docs to point to the new website.

**Comment by iRoachie** [comment]
Where do we have this link right now?

**Comment by grasmash** [comment]
Looks like https://react-native-elements-slack.herokuapp.com/ is down. Is this still an active community?

**Comment by arpitBhalla** [comment]
Hey, please join discord, link is available in Readme
