### ISSUE TITLE
Button loading spinner is not vertically centered when using smaller heights on Android

### ISSUE THREAD

**Issue by nihiluis** [react-native-elements/react-native-elements#2282]
**Explain what you did**

When I reduce the height of a Button to a certain height, say 20 (via StyleSheet), then the loading spinner is no longer vertically centered  properly.

**Expected behavior**

The spinner is centered vertically, even for smaller button heights.

**Describe the bug**

Spinner should always be centered vertically, even on Android.

**To Reproduce**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

https://snack.expo.io/SJFbnX!VI

Web version works, Android does not..

**Screenshots**

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    ^1.2.7     |
| react-native          |  ~0.61.4       |

**Comment by iRoachie** [comment]
What do you propose should happen here? The problem is that the loading indicator is larger than the height of the button.

**Comment by flyingcircle** [comment]
Checked out the android snack here for Expo sdk 37 and the loading spinner stayed centered even at low height.
