### ISSUE TITLE
Integrate font awesome 5 with icon type

### ISSUE THREAD

**Issue by mrzainulabideen** [react-native-elements/react-native-elements#2284]
I was using react-native-element listitem in which i was using icons with leftIcon prop there i was using font awesome 5 icon but was unable to use them as icons type only have font-awesome as a valid value.

I would like to add a new value to the icon's type prop to integrate font-awesome-5

**Comment by sowizz** [comment]
Duplicate of #1989? `font-awesome-5` will be available in 2.0.0.

**Comment by mrzainulabideen** [comment]
Closing as this is duplicate and the feature is going to be out in 2.0.0
