### ISSUE TITLE
Is there a way to add gradient to buttonGroup

### ISSUE THREAD

**Issue by Egizas** [react-native-elements/react-native-elements#2285]
**Is your feature request related to a problem? Please Describe.**
I cannot find a way how gradient can be added to all of the buttons

**Describe the solution you'd like**
Something like this would be sufficient:
```
         linearGradientProps={{
           colors: ['rgba(255,255,255,0.10)', 'transparent']
         }}
```

**Describe alternatives you've considered**
I tried wrapping the whole buttonGroup with _LinearGradient_ from 'expo-linear-gradient'; but unsuccessfully.

If you know a workaround, would be nice to hear about it

**Comment by flyingcircle** [comment]
Is this that you want the gradient to extend the entire group? Or do you want the each individual button to use the same gradient? The second one you could probably pass in your own component that is wrapped in a LinearGradient, but the first I do not believe would be possible as it sits currently. If you're interested in submitting a PR for that, I can reopen this ticket for further discussion.

**Comment by Egizas** [comment]
This is exactly how I solved it, by passing my own buttons component.
