### ISSUE TITLE
_reactNativeElements.Image.getSize is not a function

### ISSUE THREAD

**Issue by Biplovkumar** [react-native-elements/react-native-elements#2286]
**Explain what you did**

I have added below code which is giving Error

**Expected behavior**

Able to get image size and width.

**Describe the bug**

 Image.getSize(profileimage, (width, height)  Not supporting.

**To Reproduce**

If I am using default react native image. then it is working fine.
but in Element Image, it is not supported.
How I get Image size & Width from URI?

**Screenshots**
![Screenshot 2020-03-04 at 11 50 07 AM](https://user-images.githubusercontent.com/30401136/75850848-42b60680-5e0e-11ea-952e-0ab2acd28b5d.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.2.7     |
| react-native          |     0.59.9    |
  "react": "16.9.0",

**Comment by oxyii** [comment]
@Biplovkumar As I understand, you talking about static method [getSize](https://reactnative.dev/docs/image#getsize)... I see no reason to include this method into RNE. Anyway you **must** pass `uri` arg to `getSize` method (you cannot use image uri from `source` prop). Please try something like this:

```jsx
import React, { useState, useEffect } from 'react';
import { Image as RNImage } from 'react-native';
import { Image as RNEImage } from 'react-native-elements';

function YourImageComponent({ uri, ...otherProps }) {
  const [size, setSize] = useState(null);

  const success =(width, height) => setSize({ width, height });

  useEffect(() => {
    RNImage.getSize(uri, success); // react-native Image here
  }, [uri]);

  return size && <RNEImage {...yourProps} />; // react-native-elements Image here
}
```

**Comment by Biplovkumar** [comment]
@oxyii 
i am not satisfied with this answer.
If RNEImage Has All props of RNImage.
so why [getsize](https://reactnative.dev/docs/image#getsize) not working in RNEImage.

**Comment by iRoachie** [comment]
@oxyii Should be easy to add this in. Should forward the ref

**Comment by Biplovkumar** [comment]
Thanks @iRoachie .
