### ISSUE TITLE
Bug with Image Component 1.2.x

### ISSUE THREAD

**Issue by jjg77** [react-native-elements/react-native-elements#2293]
Image component loses rounded edges, does not alignSelf, and does some other weird ghosting.  I had to revert to 1.1.0. 

`<Image
            source={{uri: imgUri}}
            style={{
              width: imgWidth, 
              height: imgHeight,
              borderRadius: 10,
              alignSelf: 'center'
            }}
            PlaceholderContent={<ActivityIndicator color={Colors[theme].accent} />}
          />
`

**Comment by Egizas** [comment]
same here

**Comment by cooperwalter** [comment]
Here's a Snack that I believe demonstrates this bug.

https://snack.expo.io/@cooperawalter/9a5eff

**Comment by flyingcircle** [comment]
I can see the bug in the snack, but then when I try to recreate the exact same code in my local app, I don't see the bug anymore. If anyone has additional examples or code. Or if you could test out the next branch to see if the issue is still there in the most current code.

**Comment by flyingcircle** [comment]
Found a solution to this problem. You need to move `alignSelf: "center"` to `containerStyle` as in from the example:
```js
<Image
    containerStyle={{alignSelf: "center"}}
    style={{
      height: 200,
      width: 200,
      borderWidth: 1,
      borderRadius: 10,
    }} source={{ uri: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQWct5rgLe8KgjleLDs3RSVDmgF9NUoCvi7ME7Ye60T6knWNZcY&usqp=CAU'}}/>```

alignment is a tricky thing and usually belongs in the container, not the content component itself.
