### ISSUE TITLE
card view

### ISSUE THREAD

**Issue by Ranindu15** [react-native-elements/react-native-elements#2295]
I can not see the feature for create cards in row style. Which mean if i need view two cards as row i haven't any feature for this. 
Please add it or if it's already is there just explain how to do it. Thank you

**Comment by iqbalfaisal** [comment]
@Ranindu15 try this

```
<View style={{
 flex:1,
 flexDirection: 'row',
 justifyContent: 'space-between',
 }}>
  <Card  containerStyle={{flex: 1}} />
  <Card  containerStyle={{flex: 1}} />
</View>
```

**Comment by flyingcircle** [comment]
@iqbalfaisal that looks like it worked for me!
