### ISSUE TITLE
Fontawesom icon "wind" not found.

### ISSUE THREAD

**Issue by BBenGit** [react-native-elements/react-native-elements#2300]
**Explain what you did**

I want the icon [wind](https://fontawesome.com/icons/wind?style=solid) in my app but I got a warning `Failed prop type`.

Not all font-awesome icons seem to be implemented, or am I wrong somewhere ?

**Expected behavior**

The icon wind to show.
![image](https://user-images.githubusercontent.com/44926723/76955114-e1b02780-6911-11ea-88c9-0fb83a96b57d.png)

**Describe the bug**

No icon showing but this instead (the question mark).
<img width="85" alt="image" src="https://user-images.githubusercontent.com/44926723/76954718-1cfe2680-6911-11ea-875a-427d48f772e1.png">

**To Reproduce**
```
<Icon name="wind" type="font-awesome" />
```

**Screenshots**

<img width="503" alt="image" src="https://user-images.githubusercontent.com/44926723/76954701-153e8200-6911-11ea-806d-daced614f031.png">

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.2.7     |
| react-native          |     0.61.5    |

**Comment by oxyii** [comment]
@BBenGit 

> <Icon name="wind" type="font-awesome" />

[`type="font-awesome-5"`](https://github.com/oblador/react-native-vector-icons/blob/master/glyphmaps/FontAwesome5Free.json#L1316)

**Comment by BBenGit** [comment]
> @BBenGit
> 
> > `<Icon name="wind" type="font-awesome" />`
> 
> [`type="font-awesome-5"`](https://github.com/oblador/react-native-vector-icons/blob/master/glyphmaps/FontAwesome5Free.json#L1316)

@oxyii The type is not event recognized, it's showing a warning with material icons...

**Comment by oxyii** [comment]
@BBenGit Ohhh.. So sorry. FA5 [will be](https://github.com/react-native-elements/react-native-elements/commit/6cc85af1f4a5d7466e169df9054337dd1ba67fff) in [v2.0](https://github.com/react-native-elements/react-native-elements/releases/tag/untagged-755114d62e14ea50b101)

**Comment by BBenGit** [comment]
@oxyii  Ok, no problem, is there a release date ?

**Comment by oxyii** [comment]
iRoachie

**Comment by vinnyA3** [comment]
Any word on this?

**Comment by flyingcircle** [comment]
This is coming soon. Likely within the week. Otherwise you can try pulling directly from the next branch to implement the new version before the official release.

**Comment by iRoachie** [comment]
Live in 2.0.0
