### ISSUE TITLE
 Add includeFontPadding from the react native text component to the Text component in react-native-elements

### ISSUE THREAD

**Issue by nihiluis** [react-native-elements/react-native-elements#2302]
**Is your feature request related to a problem? Please Describe.**
I'm unable to properly align text due to non removable padding. See this: https://stackoverflow.com/questions/41525842/react-native-android-text-component-extra-padding

**Describe the solution you'd like**

Add includeFontPadding from the react native text component to the Text component in react-native-elements to remove situations like this: https://stackoverflow.com/questions/41525842/react-native-android-text-component-extra-padding

See docs:

https://reactnative.dev/docs/text-style-props#includefontpadding

**Describe alternatives you've considered**

havent seen any tbh.

**Additional context**

**Comment by flyingcircle** [comment]
The Text element already passes all props that are included in RN `Text`. So no addition necessary.
