### ISSUE TITLE
Checkbox crashes if title prop is empty string

### ISSUE THREAD

**Issue by irmantasra** [react-native-elements/react-native-elements#2305]
**Explain what you did**
I provide empty string for checkbox title prop.

**Expected behavior**
Checkbox renders flawlessly with an empty title.

**Describe the bug**
On checkbox rendering the app crashed and throw error.

In the CheckBox.js file at line 59 I found the place where title is rendered:
![carbon](https://user-images.githubusercontent.com/35938092/77416970-56310d80-6dcd-11ea-9d3d-afd77163f09f.png)
On line 61 `title && (<TextElement>` the code breaks. If I remove `title &&` everything works fine.
Of course I can make workaround and check when the string is empty, but if the prop is string or element, so I could also should be able to give empty string without any problems.

**Screenshots**
![Screenshot_20200324-123425](https://user-images.githubusercontent.com/35938092/77416095-203f5980-6dcc-11ea-849e-d48ff2b86604.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     "^1.2.7"    |
| react-native          |    "0.60.5"     |

**Comment by oxyii** [comment]
@irmantasra please make a [snack](https://snack.expo.io/) to reproduce it. I beleave that something wrong with your **valid** `title` React Component.

**Comment by jittuu** [comment]
@irmantasra try to use `!!title && `
