### ISSUE TITLE
Add loadingProps Props for SocialIcon component

### ISSUE THREAD

**Issue by predescu** [react-native-elements/react-native-elements#2307]
**Is your feature request related to a problem? Please Describe.**
On the Sign In screen, I like to use the SocialIcon component instead the Button component. If the background of the button is white, the loading (active indicator) is not visible.
There is no option to set the loadingProps on the SocialIcon component.
```
<SocialIcon
  light
  title="Sign in with Apple"
  button
  loading={loading}
  disabled={loading}
  type="apple"
  onPress={() => {}}
/>

```

**Describe the solution you'd like**
Add support for loadingProps on SocialIcon. Both colour and size are useful. 

**Describe alternatives you've considered**
One option is to use the Button component and set the and set the loadingProps.

**Additional context**
![Simulator Screen Shot - iPhone 11 - 2020-04-05 at 19 30 40](https://user-images.githubusercontent.com/2477691/78506792-04489a00-7774-11ea-9c28-c49988bd5d6e.png)

**Comment by bmuthoga** [comment]
@predescu I believe these are already supported by the SocialIcon component.

- If passing the `light` prop you can as well pass the `iconColor` prop to change the loader color.

- And for the loader size you can pass the `small` prop.

For example:

```
        <SocialIcon
          light
          title="Sign in with Github"
          button
          loading={true}
          disabled={true}
          type="github"
          onPress={() => {}}
          iconColor="red"
          small={true}
        />
```

Although I've noticed a bug where the propTypes for the `small` prop has been set to `PropTypes.string`, while it should instead be `PropTypes.bool`. So you'll get a warning message but it'll still work.

```
{loading && (
  <ActivityIndicator
    animating
    style={StyleSheet.flatten([
      styles.activityIndicatorStyle,
      activityIndicatorStyle,
    ])}
    color={iconColor || 'white'}
    size={(small && 'small') || 'large'}
  />
)}
```

```
SocialIcon.propTypes = {
  ...,
  iconColor: PropTypes.string,
  small: PropTypes.string,
  ...
};
```

And here's how it looks:
![SocialIcon2](https://user-images.githubusercontent.com/6702127/79594117-267fd780-80e5-11ea-896b-9d604a7bb54e.gif)

**Comment by predescu** [comment]
@bmuthoga thank you very much for your message.
You are right. I missed this part. I was more looking to match with the properties from the Button Component. Silly mistake. 

I'm closing the issue.
