### ISSUE TITLE
Input element takes full width when place in flex direction row

### ISSUE THREAD

**Issue by vishalenrique** [react-native-elements/react-native-elements#2308]
**Explain what you did**

Trying to use the Input element in a row with a custom component on the right side of it.

**Expected behavior**

Both components should be displayed.

**Describe the bug**

The input element takes the full width thus the other component is not displayed.

**To Reproduce**

Just place the Input element in flex direction row with other components.

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   1.2.7      |
| react-native          |    0.61.5      |

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this?

**Comment by bmuthoga** [comment]
@vishalenrique try adding `flexShrink` `containerStyle` to the components like shown below:

```import React, {Component} from 'react';
import {View} from 'react-native';
import {Button, Input} from 'react-native-elements';

export default class App extends Component {
  render() {
    return (
      <View>
        <View style={{flexDirection: 'row', padding: 5}}>
          <Input placeholder="random text" containerStyle={{flexShrink: 3}} />
          <Button title="My Button" containerStyle={{flexShrink: 2}} />
        </View>
      </View>
    );
  }
}
```

**Comment by cooperwalter** [comment]
@iRoachie Here's a Snack that I believe replicates what @vishalenrique is referring to. You can see that the red box of width 200 is pushed off the screen. The Snack also shows that @bmuthoga's suggestion of adding flexShrink causes the red box to show.

https://snack.expo.io/@cooperawalter/react-native-element's-input-element-takes-full-width-when-place-in-flex-direction-row

**Comment by flyingcircle** [comment]
@cooperwalter thanks for the snack, but I was able to set the `Input` width with:
```js
<Input containerStyle={{width: 100}} />
```
So I don't see anything outside of what should be reasonably expected.
