### ISSUE TITLE
Display local image as Icon in INPUT element

### ISSUE THREAD

**Issue by saibhargavag** [react-native-elements/react-native-elements#2309]
**Is your feature request related to a problem? Please Describe.**
Currently I am trying to implement a simple component with multi colored ICON inside Textbox.
Available options are not permitting to use local  SVG image as ICON or multi colored SVG image as Icon. If I try to import colored Icon to any font I am loosing color.
**Describe the solution you'd like**

When go through the INPUT component code it looks like a simple fix. All I need to do is Add Image component to the list and implement it. Since Image component accepts local SVG image as source I can display it as small icon inside text box, which solves my issue.

**Describe alternatives you've considered**
As an alternative I tried to import SVG to font and tried to use it. But my Image is multi colored I am not getting a single character instead I am getting multi character gylphs. which I can not use as Icon name.

**Additional context**
I want to see INPUT element as below.

![image](https://user-images.githubusercontent.com/43450773/79196723-701aaa80-7de5-11ea-90c6-1f889d4562b5.png)

**Comment by iRoachie** [comment]
The `leftIcon` prop can accept a component https://react-native-elements.github.io/react-native-elements/docs/input.html#lefticon. You can do:

```jsx
<Input leftIcon={<Image {...your props} />} />
```

**Comment by saibhargavag** [comment]
Thanks this is working.
