### ISSUE TITLE
Typescript: useContext(ThemeContext) doesn't expose extended theme types

### ISSUE THREAD

**Issue by bscaspar** [react-native-elements/react-native-elements#2310]
My theme looks something like this: 
```js
const theme = {
  colors: {
    primary: '#fff'
  },
  customColors: {
    background: '#000'
  }
}
```

Referencing an extended theme with `const { theme } = React.useContext(ThemeProvider)` does not expose the extended theme elements in typescript - in this example, typescript does not know about the `customColors` object on the theme.

Copying @braincore from #2007, it looks like this is because the ThemeContext statically defines the generic in ThemeProps as {}. And a workaround is to use a type assertion: `const { theme } = useContext(ThemeContext) as ThemeProps<MyTheme>;`

Is this workaround the recommended way to do this? Or is it possible to define the ThemeContext in some way after the defaultTheme is defined by deep merging the base theme with the custom theme? 

Envi details:

| software              | version |
| --------------------- | ------- |
| react-native-elements | ^1.2.7 |
| react-native          |  0.61.4  |

**Comment by Johan-dutoit** [comment]
I've done this before with StyledComponents and going to give it a go now with react-native-elements.

https://styled-components.com/docs/api#create-a-declarations-file

**Comment by Johan-dutoit** [comment]
Here's my solution (based of the way styled components does it)

Note that I am only adding my own types in the declaration

react-native-elements.d.ts
```typescript
export type RecursivePartial<T> = { [P in keyof T]?: RecursivePartial<T[P]> };

declare module 'react-native-elements' {
  export interface TextProps {
    p1Style: StyleProp<TextStyle>;
  }

  export interface Colors {
    background: string;
    border: string;
    text: string;
    altText: string;
    danger: string;
  }

  export interface FullTheme {
    colors: RecursivePartial<Colors>;
    Text: Partial<TextProps>;
  }
}
```
Now in any other file, I can do this:

```typescript
const { theme } = useContext(ThemeContext);
const dangerColor = theme.colors.danger //valid
```

**Comment by bscaspar** [comment]
This worked for me, thank you! A note - I found that for changing the theme with the existing props this doesn't pick up that those props already exist, so I simply extended this theme with the original in the interface declaration at which point the TS compiler was happy and everything was working as expected: 
```ts
import { Theme } from 'react-native-elements';

export const theme: ExtendedTheme extends Theme = {
  Card: {
    containerStyle: {
      borderRadius: 5,
    },
  }
}


```

**Comment by Johan-dutoit** [comment]
Strange! 

Maybe I am not fully understanding your issue but I didn't need to extend the theme at all.  In fact I am not using a custom interface for the theme, I am using the existing theme type provided by elements- `FullTheme`.

**Comment by bscaspar** [comment]
I see now! I didn't realize `FullTheme` was the existing theme. I updated my code to match and it works great, thanks!

**Comment by Johan-dutoit** [comment]
Glad it worked for you!

**Comment by Johan-dutoit** [comment]
I've submitted a PR to add this to the docs: https://github.com/react-native-elements/react-native-elements/pull/2354

**Comment by brerdem** [comment]
> Here's my solution (based of the way styled components does it)
> 
> Note that I am only adding my own types in the declaration
> 
> react-native-elements.d.ts
> 
> ```ts
> export type RecursivePartial<T> = { [P in keyof T]?: RecursivePartial<T[P]> };
> 
> declare module 'react-native-elements' {
>   export interface TextProps {
>     p1Style: StyleProp<TextStyle>;
>   }
> 
>   export interface Colors {
>     background: string;
>     border: string;
>     text: string;
>     altText: string;
>     danger: string;
>   }
> 
>   export interface FullTheme {
>     colors: RecursivePartial<Colors>;
>     Text: Partial<TextProps>;
>   }
> }
> ```
> 
> Now in any other file, I can do this:
> 
> ```ts
> const { theme } = useContext(ThemeContext);
> const dangerColor = theme.colors.danger //valid
> ```

That didn't work for me. I tried to add new colors but I can see only the ones in the default theme. It seems d.ts file is completely ignored

**Comment by Johan-dutoit** [comment]
@brerdem ensure TS is setup to 'read' your types directory/file

tsconfig.json
```
...
 "paths": {
      "*": ["types/*"] // Path to your types directory/file
    }
...
```

**Comment by brerdem** [comment]
@Johan-dutoit thanks it worked. However now I'm getting error about every element that I didn't declared in the file (see the screenshot below) Shouldn't it be merged to existing definitions?

![image](https://user-images.githubusercontent.com/778976/88072980-59bb8200-cb7e-11ea-9925-841aa989613b.png)

**Comment by brerdem** [comment]
When I got this error I commented `paths` in tsconfig and all of a sudden it worked. I don't know why. It seems when I put the definition file in `types` folder it automatically recognized by the compiler

**Comment by kickbk** [comment]
In one of my files I have:
`const { theme } = useContext(ThemeContext);`
When I hover on top of { theme } I get the correct type: `Partial<FullTheme>`

I then created the `d.ts` file as instructed. As soon as I save it, theme definition changes to `theme: any`
So I'm guessing that TypeScript detected the changes, but did not apply them correctly.
Any idea what I'm missing?

**Comment by Johan-dutoit** [comment]
@kickbk  It's a utility type, which I've copied from the main lib. It doesn't need to be exported, unless you want to use it for something else.

**Comment by CKitisak** [comment]
@brerdem I have the same issue like you. Would you please share how to solve that issue?

@Johan-dutoit any help would be appreciated.

Thank you.

my type module file is located at: `/src/types/react-native-elements.d.ts`
```typescript
type RecursivePartial<T> = {[P in keyof T]?: RecursivePartial<T[P]>};

declare module 'react-native-elements' {
  export interface TextProps {
    p1Style: StyleProp<TextStyle>;
  }

  export interface Colors {
    background: string;
    border: string;
    text: string;
    altText: string;
    danger: string;
  }

  export interface FullTheme {
    colors: RecursivePartial<Colors>;
    Text: Partial<TextProps>;
  }
}
```

my `tsconfig.json`:
```json
{
  "compilerOptions": {
    ...,
    "baseUrl": "./",
    "paths": {
      "*": ["node_modules/@types/*", "src/types/*"]
    }
  }
}
```

my `src/index.tsx`:
```typescript
import React from 'react';
import { Button, ThemeProvider, } from 'react-native-elements';

const theme = {
  Button: {
    raised: true,
    titleStyle: {
      color: 'green',
    },
    type: 'clear',
  },
};

const App = () => {
  return (
    <ThemeProvider theme={theme}>
      <Button title="Hey!" />
    </ThemeProvider>
  );
};

export default App;
```

my dependencies:
```json
"dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-elements": "^2.3.2",
    "react-native-vector-icons": "^7.1.0"
  },
```

**Comment by walterholohan** [comment]
I have the same issue too. It seems that the declaration merging is not working. I get the following typescript error when trying to import ThemeProvider.
![image](https://user-images.githubusercontent.com/5293650/93753191-aad80880-fbf7-11ea-9762-f2bcab766150.png)

**Comment by walterholohan** [comment]
I just figured out what the issue was. I was using typescript 4. If I downgrade to typescript 3.9.7 it works

**Comment by flycj** [comment]
@walterholohan  I have the same issue too. It seems that the declaration merging is not working.

**Comment by flycj** [comment]
I have solved this problem
Need to add import'react-native-elements' at the top of the file

**Comment by walterholohan** [comment]
Same here, in order to resolve the issue I had to add `import {Colors, FullTheme} from 'react-native-elements'` to the top of the file. Example of my declaration file below

e.g.
```
import {Colors, FullTheme} from 'react-native-elements'

type RecursivePartial<T> = {[P in keyof T]?: RecursivePartial<T[P]>}

declare module 'react-native-elements' {
  export interface Colors {
    background: string
    darkText: string
  }

  type ThemeFontDimention = {
    fontSize: number
    lineHeight: number
  }

  export interface FullTheme {
    colors: RecursivePartial<Colors>
    padding: {
      small: number
      default: number
      large: number
      screen: number
    }
    fontSizes: {
      small: ThemeFontDimention
      medium: ThemeFontDimention
      large: ThemeFontDimention
    }
  }
}
```

**Comment by eddyhdzg** [comment]
How can I add variants other than h1, h2, h3, h4?

What I want to achieve is something like

Theme
```
const theme: Theme = {
  Text: {
    p1: true,
    p1Style: {
      color: "blue",
    },
  },
};
```
Usage
```
<Text p1>Paragraph 1</Text>
```

**Comment by wkoutre** [comment]
Does anyone have a working example where they've successfully extended `TextProps` and `FullTheme["Text"]` in their own `react-native-elements.d.ts` file and it works properly when doing something like (to go off the [example in the docs](https://reactnativeelements.com/docs/customization/#typescript-definitions-extending-the-default-theme)):

```
import { TextProps, useTheme };

- TextProps.p1Style // Intellisense properly recognizes this
- useTheme().theme.Text?.p1Style // Intellisense properly recognizes this
```

I can't, for the life of me, get this working properly.

**Comment by wkoutre** [comment]
Ah, I think I figured it out...

In `react-native-elements/dist/text/Text.d.ts`, TextProps is a `type`, not an `interface`. An interface can have multiple merged declarations, but a type alias for an object type literal cannot.

If this

```
export declare type TextProps = TextProperties & { ... }
```

is changed to this:

```
export declare interface TextProps extends TextProperties { ... }
```

Then all all works as expected using:

```
export * from "../../node_modules/react-native-elements";

import { TextStyle } from "react-native";
import { RecursivePartial, MandatoryColors, PrimaryButtonProps } from ".";

declare module "react-native-elements" {
  export interface TextProps {
    p1Style?: TextStyle;
    p2Style?: TextStyle;
    p3Style?: TextStyle;
  }

  // eslint-disable-next-line @typescript-eslint/no-empty-interface
  export interface Colors extends MandatoryColors {}

  export interface FullTheme {
    colors: RecursivePartial<Colors>;
    Text: Partial<TextProps>;
    PrimaryButton: PrimaryButtonProps;
  }
}
```

Will make a PR.
