### ISSUE TITLE
Image component tintColor style does not work

### ISSUE THREAD

**Issue by bscaspar** [react-native-elements/react-native-elements#2312]
The Image component style prop `tintColor` does not change the color for non-transparent pixels which would be the expected behavior according to the [react native docs](https://reactnative.dev/docs/0.36/image-style-props#tintcolor) and the [RNE docs](https://react-native-elements.github.io/react-native-elements/docs/image.html) that mention this component "Also receives all React Native Image props"

Example code which works if Image is imported from react-native instead:
```js
import { Image } from 'react-native-elements'

export const ColoredImage = () => (<Image style={{ height: 40, width: 40, tintColor: '#ff0000' }} /> )

```

[Snack](https://snack.expo.io/@bcaspar/rne-image-tint-color)

**Comment by oliverdolgener** [comment]
Can confirm. Same problem with Avatar imageProps

**Comment by cooperwalter** [comment]
Here's a simple Snack demonstrating the bug. It shows the expected behavior on RN's Image component and the current behavior on RNE's Image component.

https://snack.expo.io/@cooperawalter/react-native-elements-image-tintcolor-bug

**Comment by oliverdolgener** [comment]
It's because `containerStyle` does not apply to the Image component but to the View around it.
https://github.com/react-native-elements/react-native-elements/blob/next/src/image/Image.js#L59

There should be a tweak in this line: https://github.com/react-native-elements/react-native-elements/blob/next/src/image/Image.js#L65 to support `tintColor`

**Comment by bscaspar** [comment]
Looks like we arrived at the same conclusion! I submitted a PR (linked above) with a fix that applies all styles to the base Image component at that line.
