### ISSUE TITLE
Change the component of the checkbox title

### ISSUE THREAD

**Issue by rwanito** [react-native-elements/react-native-elements#2327]
Hi !
Thanks for your work !
I suggest a little change for the checkbox.

I want to put my own Text component, but it didn't work when I add the fontFamily prop.

Can you add textComponent to checkbox ?

Thanks !

**Comment by flyingcircle** [comment]
@rwanito There's a separate prop for entering in titleProps, did you add it there?

**Comment by flyingcircle** [comment]
I checked it out and was able to add the fontFamily to the prop and it worked. You can double check your code against mine:

```js
<CheckBox title={<Text style={{fontWeight:"bold", fontFamily:"Arial"}}>Title!</Text>} />
```

**Comment by rwanito** [comment]
Hi !
Thanks for your reply !
Okay, I'll try it asap !

Big thanks !
