### ISSUE TITLE
Keyboard  Avoiding in Overlay

### ISSUE THREAD

**Issue by SyedShahbazHussain** [react-native-elements/react-native-elements#2339]
**Is your feature request related to a problem? Please Describe.**
TextInput in Overlay not avoiding the keyboard, Keyboard is hiding the input fields 

**Describe the solution you'd like**
When open the keyboard, overlay push up and shows the input field clearly.

**Comment by flyingcircle** [comment]
Can you write a snack displaying the issue?

**Comment by SyedShahbazHussain** [comment]
> Can you write a snack displaying the issue?

Here you can see the example of my code, run it on ios and please provide me a solution, I was also used KeyboardAvoidingView of react native but it's not solve my problem.

https://snack.expo.io/@syedshahbazhussain/overlay?session_id=snack-session-EC38uuGpG&preview=true&platform=ios&iframeId=l4pqfhu125&theme=dark

**Comment by billy607** [comment]
Same issue here. In my case, keyboard push the textinput out of the screen top. This also happen when you click the first view in SyedShahbazHussain's snack.

**Comment by flyingcircle** [comment]
I was able to get most of the way there. Try using this in your code and see if it works for you:

```js
<View style={styles.container}>
  <Overlay
    isVisible={true}
    windowBackgroundColor="rgba(0, 0, 0, .5)"
    // overlayBackgroundColor="red"
    overlayStyle={{flex:1, width: "50%"}}
    width="auto"
    height="auto"
    borderRadius={8}>
    <KeyboardAvoidingView behavior="padding" style={{ flex: 1, justifyContent: "center" }}>
    <View style={{ width: '90%' }}>
      <Text>sdf sdf!</Text>
      <View style={styles.inputView}>
        <TextInput
          placeholder={'Describe here...'}
          multiline={true}
        />
      </View>
      <View style={styles.inputView}>
        <TextInput
          placeholder={'Describe here...'}
          multiline={true}
        />
      </View>
      <View style={styles.inputView}>
        <TextInput
          placeholder={'Describe here...'}
          multiline={true}
        />
      </View>
      <View style={styles.inputView}>
        <TextInput
          placeholder={'Describe here...'}
          multiline={true}
        />
      </View>
      <View style={styles.inputView}>
        <TextInput placeholder={'Describe here...'} multiline={true} />
      </View>
    </View>
    </KeyboardAvoidingView>
  </Overlay>
</View>
```
