### ISSUE TITLE
Can an Image be used inside of Tooltip, instead of Text?

### ISSUE THREAD

**Issue by dudeinthemirror** [react-native-elements/react-native-elements#2343]
This might be already possible, but I can't figure out how to do it.
I have this control. When the users presses on the Info icon, I need to display a tooltip with a long text.

![Screen Shot 2020-05-01 at 7 39 51 PM](https://user-images.githubusercontent.com/981638/80853485-3835a480-8be6-11ea-83c9-21516275d3a1.png)

I was able to display the tooltip using `<Text>press me</Text>` following your example. 

![Screen Shot 2020-05-01 at 7 55 34 PM](https://user-images.githubusercontent.com/981638/80853439-cc533c00-8be5-11ea-95bf-86e4fe930d45.png)

But whenever I try to replace it with an Image, it doesn't work, no matter what I tried. Can this be done?

So, the desired code would look something like this:
```javascript
import { Tooltip, Image, Text } from 'react-native-elements';

...
render() {
...
    <Tooltip containerStyle={{left: 10, width: '95%', height: 150, backgroundColor:'#0ABAA6'}} pointerColor='#0ABAA6' popover={<Text style={{fontSize: 17}}>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley.</Text>}>
      <Image
      containerStyle={styles.icon}
      source={source}/>
    </Tooltip>
...
}
```

**Comment by flyingcircle** [comment]
@dudeinthemirror I tried it in my app with both Image and Icon and was able to use either. Can you make a snack to show the problem?

**Comment by dudeinthemirror** [comment]
thanks for you reply @flyingcircle 
So, I was able to get it working, but the arrow is off. 

![Screen Shot 2020-05-06 at 6 47 22 PM](https://user-images.githubusercontent.com/981638/81245549-1cf1dd00-8fca-11ea-9349-58e542c9f0e1.png)

Here is the code. What should I change to make it centered under the icon?

<details>
  <summary>Click to expand!</summary>
```javascript

import { Tooltip } from 'react-native-elements';

import { View, StyleSheet, Image } from 'react-native';

const tooltipText =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley.";

const renderIconWithTooltip = (
    source,
    tooltipText,
  ) => (
    <Tooltip
      containerStyle={styles.tooltipContainerStyle}
      pointerColor="#0ABAA6"
      popover={<Text style={styles.popoverStyle}>{tooltipText}</Text>}>
      <View
        style={[
          styles.iconTooltipContainer,
          { marginRight: 20 },
        ]}>
        <Image style={styles.tooltipIcon} source={source} />
      </View>
    </Tooltip>
  );

const styles = StyleSheet.create({
  iconTooltipContainer: {
    width: 32,
    alignItems: 'center',
    justifyContent: 'center',
    resizeMode: 'contain',
  },
  popoverStyle: {
    fontSize: 19,
    color: '#333333',
  },
  tooltipContainerStyle: {
    left: 11,
    width: '95%',
    height: 150,
    backgroundColor: '#0ABAA6',
  },
  tooltipIcon: {
    width: 32,
    height: 32,
  },
});
```
</details>

**Comment by flyingcircle** [comment]
I would guess that playing around with padding or margin in the `containerStyle` will likely be your answer.
