### ISSUE TITLE
Why react native elements is not using React.memo in all its components?

### ISSUE THREAD

**Issue by glauberfc** [react-native-elements/react-native-elements#2348]
Why react native elements is not using **React.memo** in all its components to avoid unnecessary re-renders?

I'm sorry by not following the issue templates. I'm didn't see one for questions.

**Comment by flyingcircle** [comment]
Can you not already wrap the RNE elements in React.memo if you need it?

How would a user disable the memoization if there is no need for it? Memoization is for performance optimization and can lead to bugs in some cases. I'm not sure how it is possible to make these decisions outside of a specific app's implementation.

**Comment by glauberfc** [comment]
Got it. I think the team can add a section explaining this on the website. For a long time I had problems with unnecessary re-renders with the Avatar component and I didn't know how fix it.

**Comment by flyingcircle** [comment]
The Avatar specifically actually will be memoized in 2.0.1
