### ISSUE TITLE
Avatar rounded prop is not working

### ISSUE THREAD

**Issue by nimahkh** [react-native-elements/react-native-elements#2349]
Hello guys. 
I am using this code: 

```
<Avatar
              size={'medium'}
              rounded
              source={{
                uri:
                item.get_user_avatar? `${image_server}${item.get_user_avatar.image}`: null,
              }}
            />
```

but the Avatar is not rounded. if I remove the source, it is ok with a 'title', but if i put source, it is not showing it rounded.

**Comment by flyingcircle** [comment]
I put your code into a snack here: https://snack.expo.io/@flyingcircle/d9453c
It shows up rounded there. My guess is that some other styling that you haven't included here is causing your issue. If not, feel free to recreate your issue on a snack and then I'll be able to review it from there.
