### ISSUE TITLE
Styling ButtonGroup not working

### ISSUE THREAD

**Issue by tranvanquang** [react-native-elements/react-native-elements#2351]
**Explain what you did**
How I can style this ButtonGroup, I'm try using selectedTextStyle but not working.
**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     2.0.0    |
| react-native          |  0.62       |

**Comment by tranvanquang** [comment]
I'm trying           selectedTextStyle={styles.textSelect}  and 
textSelect:{
color: red
}
But not working !!! Can u help me? Thanks u so much

**Comment by flyingcircle** [comment]
@tranvanquang please recreate this issue in a snack. Then we can work on this.

**Comment by thanhluantl2304** [comment]
phần này giải quyết như thế nào rồi bạn @tranvanquang? mình đang bị tắc chỗ này

**Comment by reactnetau** [comment]
selectedTextStyle={{ color: '#fff' }}
textStyle={{ color: '#000' }}

Confirmed, this doesn't work.

Does anyone know how to fix this?
