### ISSUE TITLE
Accessory background color: square it

### ISSUE THREAD

**Issue by fdelavra** [react-native-elements/react-native-elements#2353]
Hello.

When I try to change accessory button background color, a square appear 

**My code**

<Avatar 
                    containerStyle={styles.avatar}
                    rounded 
                    icon={{name: 'user-alt', type: 'font-awesome-5'}}
                    onAccessoryPress={() => Alert.alert("change avatar")}
                    overlayContainerStyle={{backgroundColor: Properties.COLOR.grey}}
                    size={hp('15%')}
                    showAccessory
                    accessory={{containerStyle: {backgroundColor: Properties.COLOR.orange}}}
                />

**Expected behavior**

A rounded accessory with orange background color

**Describe the bug**

a rounded accessory with grey background color, and inside a square orange background colored with the icon

**To Reproduce**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Screenshots**

| react-native-elements |    2.0.0     |
| react-native          |    0.62.2
<img width="138" alt="Capture d’écran 2020-05-09 à 17 18 28" src="https://user-images.githubusercontent.com/40144260/81477650-1c9b5100-9219-11ea-81d9-ef58bfc53ace.png">
     |

**Comment by flyingcircle** [comment]
This is not completely obvious from the docs, but you can provide a background color this way:

```js
accessory={{style: {backgroundColor: "orange"}}}
```

`style` is what is passed to the accessory's container. `containerStyle` is passed directly to the Icon component. You could alternatively provide a `color` to the accessory and then also provide `reverse: true`, but this then messes with the default sizing that the `accessory` prop does. Anyway, using `style` should meet your requirements. This probably deserves a note in the docs.

**Comment by fdelavra** [comment]
Thank you for your reactivity ;)

**Comment by peterthompson** [comment]
In the version you are using the style prop for accessory is applied to the icon and to the container 😔. So there is not a nice way around this.
