### ISSUE TITLE
Can't Pass ListItem's rightIcon a conditional render + onPress to set state

### ISSUE THREAD

**Issue by nashford77** [react-native-elements/react-native-elements#2357]
<ListItem
          title="Account"
          bottomDivider
          titleStyle={{color: 'grey'}}
          containerStyle={localStyle.sectionItemContainer}
          rightIcon={
            (changeIcon(),
            {onPress: () => setIsAccountCollapsed(!isAccountCollapsed)})
          }
  />

This  works just fine if i set only rightIcon ={changeIcon()}

I can manually set that state and it renders fine, i however want to use a prop as well and can't. I want onPress to be on the rightIcon NOT on the whole ListItem.

  const changeIcon = () => {
    if (isAccountCollapsed !== true) {
      return <ChevronDown \/>;
    }
    return <ChevronUp \/>;
  };

Am i doing something wrong or is this a bug? Notably ChevronUp & Down are coming from elsewhere and work fine. However if theres is a better way to have a listitem that is collapsable and has conditional rendering for up / down arrows, that is ok too.

**Comment by flyingcircle** [comment]
I'm not sure I know what pattern you are attempting here. I would instead create a different component as such:
```js
function chevronIcon() {
  const [isAccountCollapsed, setIsAccountCollapsed] = useState(false);
  const changeState = () => setIsAccountCollapsed(!isAccountCollapsed);
  if(isAccountCollapsed){
    <ChevronUp onPress=changeState />
  } else {
    <ChevronDown onPress=changeState />
  }
}
```

And then pass that in directly to your rightIcon
