### ISSUE TITLE
Strange behavior on theming (for Buttons)

### ISSUE THREAD

**Issue by xstable** [react-native-elements/react-native-elements#2358]
**Explain what you did**
I try to set the borderTop to the right side in my favorite color.

Here is what working so far: 
![image](https://user-images.githubusercontent.com/1778068/81581074-84cf6b80-93ae-11ea-938e-135a0a32e8c0.png)

But if I change the borderTopColor and borderTopWidth with borderLeftColor and borderLeftWidth, it looks like this: 

![image](https://user-images.githubusercontent.com/1778068/81581341-e394e500-93ae-11ea-9c9a-b1456b7ced7b.png)

It seems the OS-Default Primary Color is used, and not the one I declared.
BorderTop and BorderBottom work, BorderLeft and BorderRight not!

| software              | version |
| --------------------- | ------- |
| react-native-elements |   2.0.0      |
| react-native          |    0.62.2     |

## Additional Info:
Figured out, that the left & right border work declared in `containerStyle`. But this seems not the way it should work?!?

**Comment by flyingcircle** [comment]
Looks like this is a RN issue: https://github.com/facebook/react-native/issues/19981 https://github.com/facebook/react-native/issues/20137
