### ISSUE TITLE
Input Component styling is behaving different for 2.0.0

### ISSUE THREAD

**Issue by Relax594** [react-native-elements/react-native-elements#2359]
**Explain what you did**

Just updated from 1.2.7 to 2.0.0

**Expected behavior**

Make everything look the same as before the update

**Describe the bug**

Input Component is higher than before without changing anything. Removing `rightIcon` doesn't make a difference, so it isn't related to using an icon within the input.

**To Reproduce**

```
<Input
   ref={ref}
   containerStyle={[Styles.item_input_default_input]}
   inputContainerStyle={{
                borderBottomColor: 'transparent',
            }}
   rightIcon={<Text style={Styles.rightIcon}>€</Text>}
/>

const Styles = StyleSheet.create({
    item_input_default_input: {
        borderWidth: 2,
        borderColor: '#d3d3d3',
        marginVertical: 6,
        borderRadius: 20,
        flex: 1,
    },
    rightIcon: {
        fontWeight: 'bold',
        fontSize: 16,
    },
});
```

**Screenshots**
Version 1.2.7
![grafik](https://user-images.githubusercontent.com/22765758/81650111-ade51000-9431-11ea-9674-9b8c8f24e1e9.png)

Version 2.0.0
![grafik](https://user-images.githubusercontent.com/22765758/81649755-1b447100-9431-11ea-8d22-888d65233258.png)

**Your Environment:**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  2.0.0  |
| react-native          |   0.62.2   |

**Comment by flyingcircle** [comment]
There is no promise for the look to stay the same between major releases. In fact, that's exactly what a major release means: the layout of components has likely changed. For `Input`, adding `renderErrorMessage={false}` may solve your problem.
