### ISSUE TITLE
ListItem how to use FontAwesome5 icons

### ISSUE THREAD

**Issue by goxr3plus** [react-native-elements/react-native-elements#2365]
What i don't understand about [ListItem](https://react-native-elements.github.io/react-native-elements/docs/listitem.html) , is how i can use **FontAwesome5** icons .

![image](https://user-images.githubusercontent.com/20374208/82675284-44dd7380-9c4d-11ea-9465-b7678657e2b1.png)

As far as i can see in the default examples it seems that you are using by default **material-icons**

```
const list = [
  {
    title: 'Appointments',
    icon: 'av-timer'
  },
  {
    title: 'Trips',
    icon: 'flight-takeoff'
  },
  ... // more items
]
```

But when i try for example ` icon: 'fas fa-times'` which is fontawesome5 related it doesn't work . What am i doing wrong ?

How is also this icon related to the [ICON ](https://react-native-elements.github.io/react-native-elements/docs/icon.html)from your documentation ?

Thank you :)

**Comment by flyingcircle** [comment]
Per the docs, you can pass in `Icon` props to `ListItem`. So your component would look something like:
```js
<ListItem
  rightIcon={{type: 'font-awesome-5', name: 'times'}}
/>
```
