### ISSUE TITLE
Slider to be reverted

### ISSUE THREAD

**Issue by dameyerdave** [react-native-elements/react-native-elements#2369]
I'd like to revert the slider in the way that the min value is on the right and the max value is on the left in 'horizontal' orientation and the min value is at the bottom and the myax value is at the top in 'vertical' orientation. 

This could be implemented by a property **revert**: true|false or with additional orientation properties like **vertical-revert** or **horizontal-revert**.

Please think about that feature, it would be nice to have it.

Perhaps there is also a workaround which I did not figure out yet.

**Comment by dameyerdave** [comment]
I figured out the workaround: 
`
const [level, setLevel] = useState(1)
<Slider value={max - level} onValueChange={(value) => { setLevel(max - value) }} />
`
Therefore it does not make sense to implement this feature.

**Comment by jqn** [comment]
This might be a better explanation:

```
const VerticalSlider = () => {
  const [fontSize, setFontSize] = React.useState(0);
  return (
    <View style={styles.vertical}>
      <Text>{fontSize}</Text>
      <Slider
        style={{
          height: 240,
        }}
        step={1}
        minimumValue={0}
        maximumValue={50}
        value={50 - fontSize}
        onValueChange={(value) => setFontSize(50 - value)}
        minimumTrackTintColor="#2C2D31"
        orientation="vertical"
        thumbTintColor="#07AE61"
      />
    </View>
  );
};
```

**Comment by Markyza** [comment]
> 
> 
> I figured out the workaround to invert the scale of the slider:
> 
> ```
> const [level, setLevel] = useState(1)
> <Slider value={max - level} onValueChange={(value) => { setLevel(max - value) }} />
> ```
> 
> Therefore it does not make sense to implement this feature.

Can you explain your example? I need to use inverted scale, but in my case onValueChange should update min/max in parent component.
