### ISSUE TITLE
Avatar PropTypes throwing warning when source is undefined

### ISSUE THREAD

**Issue by flyingcircle** [react-native-elements/react-native-elements#2372]
As mentioned here: https://github.com/react-native-elements/react-native-elements/pull/2338#issuecomment-636649920

There is an issue with some of the PropTypes when making the transition to removing PropTypes. Might have to rethink how to do some of the PropTypes.

**Comment by AzzouDuGhetto** [comment]
As mentioned here https://stackoverflow.com/questions/52720585/what-prop-type-should-i-check-for-requiring-the-source, the good way to do this will be
```
PropTypes.oneOfType([
  PropTypes.shape({
    uri: PropTypes.string,
    headers: PropTypes.objectOf(PropTypes.string)
  }),
  PropTypes.number,
  PropTypes.arrayOf(
    PropTypes.shape({
      uri: PropTypes.string,
      width: PropTypes.number,
      height: PropTypes.number,
      headers: PropTypes.objectOf(PropTypes.string)
    })
  )
])
``` since it's how RN itself handle it for now (see `./node_modules/react-native/Libraries/Image/Image.android.js`. I tested it with monkey patch, no more warnings.

If you thinks it's a suitable way, I can do the PR 👍

**Comment by flyingcircle** [comment]
That would be appreciated, the issue is much bigger than just `Avatar`. It looks like in RNE Image 

```
Image.propTypes = {
  ...ImageNative.propTypes,
  ImageComponent: PropTypes.elementType,
  PlaceholderContent: nodeType,
  containerStyle: PropTypes.object,
  placeholderStyle: PropTypes.object,
  transition: PropTypes.bool,
};
```

My guess is that `...ImageNative.propTypes` is returning `undefined` as well. So source needs to be defined here, and then used in all locations where we used to `RNImage.proptypes.source`. I would appreciate a PR if you can.

**Comment by AzzouDuGhetto** [comment]
From what I see in #2338, Avatar was the only component using `RNImage.proptypes.source`

So removing it in Avatar.js and add it in Image.js will do it ?

**Comment by flyingcircle** [comment]
It was also referenced in `Card`, `Header`, `FeaturedTile`, and `Tile`

**Comment by AzzouDuGhetto** [comment]
Oh you're right, it's under different name for each of them, my bad  😅So if I follow you, Image,js will look like this: 
```
Image.propTypes = {
  ...ImageNative.propTypes,
  ImageComponent: PropTypes.elementType,
  PlaceholderContent: nodeType,
  containerStyle: PropTypes.object,
  placeholderStyle: PropTypes.object,
  transition: PropTypes.bool,
  source: PropTypes.oneOfType([
    PropTypes.shape({
      uri: PropTypes.string,
      headers: PropTypes.objectOf(PropTypes.string)
    }),
    PropTypes.number,
    PropTypes.arrayOf(
      PropTypes.shape({
        uri: PropTypes.string,
        width: PropTypes.number,
        height: PropTypes.number,
        headers: PropTypes.objectOf(PropTypes.string)
      })
    )
  ]),
};
```
but I'm not sure what to change in `Card`, `Avatar` etc.. How to use it there ? Somethings like `source: Image.propTypes.source` ?

**Comment by flyingcircle** [comment]
Correct, I think that should work.
