### ISSUE TITLE
Can't set an array for style prop

### ISSUE THREAD

**Issue by omid-ebrahimi** [react-native-elements/react-native-elements#2373]
I upgraded `react-native-elements` from 1.2.7 to 2.0.1. I see the following error for most of the components. I can't set an array as style for components.

Example Code:

`<Button
            {...otherProps}
            containerStyle={[styles.buttonContainer, containerStyle]}
            buttonStyle={[styles.button, buttonStyle]}
            disabledStyle={[styles.disabled, disabledStyle]}
/>`

**Expected behavior**

It should work as before.

**Error (in Dev Tools)**

![image](https://user-images.githubusercontent.com/1673391/83441286-89da8480-a45b-11ea-82ad-2d49c2737587.png)

**To Reproduce**

Just pass an array as style.

**Comment by arabold** [comment]
I just reported this as well and created a PR for it: https://github.com/react-native-elements/react-native-elements/issues/2374
