### ISSUE TITLE
Integration with react-native-gesture-handler

### ISSUE THREAD

**Issue by Lestt** [react-native-elements/react-native-elements#2377]
Hi all,

I'm new with React Native ecosystem, and I tried to use React Native Element with React Native Gesture handler.

First, to make a Button able to animate a View, I do:
```
import { TapGestureHandler } from "react-native-gesture-handler";
import { Button } from "react-native-elements";

<TapGestureHandler onHandlerStateChange={this.onHandleChange}>
    <Button title="Move" />
</TapGestureHandler>
```
It doesn't work, I think it's because the touch event is received by the `Button`, and not the `TapGestureHandler`.

Then I saw this in the doc:
- [TouchableComponent](https://react-native-elements.github.io/react-native-elements/docs/button.html#touchablecomponent): component for user interaction.

So, according to this, I was trying to do:
```
import { TapGestureHandler } from "react-native-gesture-handler";
import { Button } from "react-native-elements";

<Button 
    TouchableComponent={TapGestureHandler}
    onHandlerStateChange={this.onHandleChange}
    title="Move" />
```
Here, I expect to pass the class component that the Button has to use for Handling touchable event, with the `onHandleStateChange` property for it.

Am I missing something ?

**Comment by flyingcircle** [comment]
I see there is a bug in your code above where you are missing an `=` in `onHandlerStateChange{this.onHandleChange}`. I assume that is not the error you were talking about? You'll have to share what error you are getting with your first attempt.

**Comment by Lestt** [comment]
@flyingcircle I have updated my post to make it more clear.

**Comment by flyingcircle** [comment]
@Lestt I tried this out and saw it triggering. Though I don't have a strong understanding of this component. Not sure what more I can answer for you. Maybe you can create a snack that reproduces this error?

**Comment by Lestt** [comment]
@flyingcircle  You're right. Everything is ok. My issue is from somewhere else. Sorry for the false alert.
