### ISSUE TITLE
Received `false` for a non-boolean attribute `solid` / `brand`

### ISSUE THREAD

**Issue by ubuntutest** [react-native-elements/react-native-elements#2381]
hi, I get the following console error on my React app:

```
Warning: Received `false` for a non-boolean attribute `solid`.

If you want to write it to the DOM, pass a string instead: solid="false" or solid={value.toString()}.

If you used to conditionally omit it with solid={condition && value}, pass solid={condition ? value : undefined} instead.
```
```
Warning: Received `false` for a non-boolean attribute `brand`.

If you want to write it to the DOM, pass a string instead: brand="false" or brand={value.toString()}.

If you used to conditionally omit it with brand={condition && value}, pass brand={condition ? value : undefined} instead.
```
I can't understand the problem, this "solid" and "brand" I don't know where they come from.

If I remove the SearchBar component, I no longer experience the problem, so I guess it's something related to this component.

Any suggestions?
Thanks

**Comment by flyingcircle** [comment]
Not sure it'll be possible to help without better context. I think you'd need to post the context of this code.

**Comment by ubuntutest** [comment]
Hi sorry, you're right, I was very busy solving the problem and I forgot to send the code I'm working on.
I have streamlined the code as much as possible to make it easy to understand and debug.
This generates the error that I reported on the first post:

```
import * as React from 'react';
import {
  Text,
  View,
  StyleSheet,
  FlatList,
  ActivityIndicator,
  Platform,
} from 'react-native';
import { SearchBar } from 'react-native-elements';
import {BrowserRouter, Link, Route, Switch} from 'react-router-dom';


export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = { isLoading: true, search: '' };
  }
  componentDidMount() {
    this._isMounted = true;
    return fetch('https://jsonplaceholder.typicode.com/posts')
    .then(response => response.json())
    .then(responseJson => {
        this.setState(
          {
            dataSource: responseJson,
          },
        );
    })
  }
  render() {
    return (
      <SearchBar/>
    );
  }
}

```

**Comment by flyingcircle** [comment]
I don't see anything that is related here to `SearchBar` and I don't see how anything in your code would even remotely create this warning. I started up web and was not able to reproduce this error. My best guess for you is that this warning is being created from another third party package.

**Comment by ubuntutest** [comment]
I retested everything, if in this code I delete exactly this line `<SearchBar/`>, the problem is gone, I really don't understand what could depend otherwise

**Comment by flyingcircle** [comment]
`solid` and `brand` are props in the `Icon` component, they are booleans though so the warning isn't making sense. They both default to `false` and the default `SearchBar` has a default `Icon` that it displays. But there's nothing wrong here. Please post your `package.json`.

**Comment by flyingcircle** [comment]
What this comes down to is this sounds like it is likely a problem deeper down, my guess is in `react-native-web`, or perhaps you're on an old version of the `react-dom`?

**Comment by ubuntutest** [comment]
Thanks for investigating further, this is the content of my `package.json`:

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~37.0.3",
    "history": "^4.10.1",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-elements": "^2.0.1",
    "react-native-screens": "~2.2.0",
    "react-native-web": "~0.11.7",
    "react-router-dom": "^5.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "@types/react": "~16.9.23",
    "@types/react-native": "~0.61.17",
    "babel-preset-expo": "~8.1.0",
    "typescript": "~3.8.3"
  },
  "private": true
}

```

**Comment by ubuntutest** [comment]
any suggestions regarding this problem? I haven't been able to solve yet
