### ISSUE TITLE
iconContainerStyle prop has no effect

### ISSUE THREAD

**Issue by jorgtz** [react-native-elements/react-native-elements#2382]
**Explain what you did**
I installed latest version of the ReactNativeElements (2.0.2) library on the latest ReactNative (0.62.2) version project. I  want to reposition or give the icon container custom style, to do so I set the iconContainerStyle with 

`        iconContainerStyle={{ marginRight: 50 }}
`

**Expected behavior**
Icon should be 50px away from text title.

**Describe the bug**
Style has no effect, I even put a backgroundColor: 'red' with no luck.

**To Reproduce**
Set the button component as follows
```
      <ElementsButton
        onPress={onPress}
        title='hola'
        icon={icon}
        activeOpacity={0.8}
        buttonStyle={{ borderRadius: 25, height: 50, width: '100%' }}
        iconContainerStyle={{ marginRight: 50 }}
      />
```

**Screenshots*
![code](https://user-images.githubusercontent.com/66479719/83887018-71919080-a70d-11ea-8af1-c92240a39367.png)
![Simulator Screen Shot - iPhone 7 - 2020-06-05 at 00 37 35](https://user-images.githubusercontent.com/66479719/83887051-7a826200-a70d-11ea-8c9b-30055a2682dc.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   2.0.2      |
| react-native          |    0.62.2     |

**Comment by flyingcircle** [comment]
I tried this out with my own code and I was able to successfully move around the `icon` in a `button` with `iconContainerStyle`. If you can recreate an Expo snack showing a bug, I'll reopen the ticket. But as it is now, I was not able to reproduce the issue.

**Comment by MarianAlexandruAlecu** [comment]
I'm having the same issue, you can try it on the [official playground!](https://react-native-elements.js.org/#/button)

<img width="1260" alt="Screenshot 2021-02-27 at 13 54 40" src="https://user-images.githubusercontent.com/5826632/109386463-6b7aba00-7903-11eb-84f8-68fc5e0166ed.png">

`iconContainerStyle.marginRight` does not work, you can try with any value

**Comment by Pozee** [comment]
I seem to have the same problem & can't figure it out.

**Comment by flyingcircle** [comment]
You can use `marginRight` in the `style` prop of `Icon` to make the effect that you are looking for.
<img width="1006" alt="Screen Shot 2021-02-28 at 10 22 22 AM" src="https://user-images.githubusercontent.com/5239875/109429078-da611d00-79ae-11eb-8953-e705e687fd18.png">

**Comment by MarianAlexandruAlecu** [comment]
Indeed, but I was trying to achieve this on all buttons in the app. In the end, I used `titleStyle.marginHorizontal`:
```
Partial<FullTheme> = {
	Button: {
		titleStyle: {
			marginHorizontal: 5,
		},
	},
};
```

Anyways, what's the purpose of `iconContainerStyle`? In which cases does it makes sense to be used?

**Comment by flyingcircle** [comment]
It's just a forward to `Icon`'s `containerStyle`. Not the best prop imo as I've tried reducing the amount of prop forwarding that is in the API as I think it unnecessarily complicates things. What does `containerStyle` even do? I don't know really. My guess is that usually there's a bug or someone wants to do something very specific that requires injecting into a specific spot in the component. You can view the code for `Icon` yourself and see how `containerStyle` is used.

**Comment by nomi9995** [comment]
if you want to make this prop work than you need to edit this file `node_modules/react-native-elements/dist/buttons/Button.js` line:104
```
{!loading &&
                !!title &&
                renderNode(Text, title, Object.assign({ style: titleStyle }, titleProps))}
            <View style={iconContainerStyle}>
            {!loading &&
                icon &&
                iconRight &&
                renderNode(Icon, icon, {
                    containerStyle: StyleSheet.flatten([
                        styles.iconContainer,
                        iconContainerStyle,
                    ]),
                })}
            </View>
```

**Comment by jeton-th** [comment]
I had the same issue and this is my workaround:

```
 Button: ({ icon, iconRight }) => ({
      titleStyle: {
        marginLeft: icon ? 10 : 0,
        marginRight: iconRight ? 10 : 0,
      },
    }),
```

**Comment by juncoding** [comment]
```
import { Button } from '@rneui/base';
import React from 'react';
import { ScrollView } from 'react-native';

export const ButtonsScreen = () => {
  return (
    <ScrollView
      style={{
        backgroundColor: 'pink',
        flex: 1,
      }}>
      <Button
        title="Hello"
        icon={{
          type: 'ionicon',
          name: 'flash-sharp',
        }}
        iconContainerStyle={{
          backgroundColor: '#00FF00',
        }}
        containerStyle={{ width: '50%', margin: 20 }}
      />
    </ScrollView>
  );
};
```

<img width="211" alt="CleanShot 2023-01-27 at 17 36 06@2x" src="https://user-images.githubusercontent.com/3412867/215054531-667e9e37-5c33-466f-a81e-ca507b05dc78.png">
