### ISSUE TITLE
Don't work props showCancel in component SearchBar

### ISSUE THREAD

**Issue by ilyapishchulin** [react-native-elements/react-native-elements#2383]
Hi, props showCancel in component SearchBar isn't work.

Video -- https://youtu.be/WXyVjcSz-l8
Use version -- 2.0.2

I am use this construction:
```
<View style={styles.searchTopBar}>
     <SearchBar
            containerStyle={styles.searchBar}
            inputContainerStyle={styles.searchBarInput}
            placeholder='Поиск'
            platform='ios'
            showLoading={false}
            showCancel={false}
     />
</View>

**Comment by PudiccaA** [comment]
Same here.

In my case, it's even worse. The input container would not automatically shrink when the cancel button popped up.

**Comment by JB1905** [comment]
Hi! I can prepare fix for this issue!

**Comment by flyingcircle** [comment]
This is a misunderstanding of what the `showCancel` prop is. As described in the docs 

```
When true the cancel button will stay visible after blur events.
```

So the `showCancel` prop being `false` does not mean that the cancel button will never appear. `showCancel` being true means that even when the user isn't focused on the search bar, 'cancel' will still be there. When it is false, when the user isn't focused on the `SearchBar`, it will disappear.
