### ISSUE TITLE
Cannot get the module to work

### ISSUE THREAD

**Issue by kchangch** [react-native-elements/react-native-elements#2384]
undefined Unable to resolve module `@expo/vector-icons/Fontisto` from `node_modules/react-native-elements/src/helpers/getIconType.js`: @expo/vector-icons/Fontisto could not be found within the project.

I'm experiencing this issue after installing the module. Anyone knows how to fix it?

**Comment by jacobrunner27** [comment]
I am having the same issue. It does not want to recognize the import when using Expo. Any way to fix this?

**Comment by flyingcircle** [comment]
https://github.com/expo/vector-icons/issues/119#issuecomment-619720703
Install `@expo/vector-icons@10.1.0` which is where they included `Fontisto`.
