### ISSUE TITLE
Input errorMessage won't hide

### ISSUE THREAD

**Issue by LautaroRk** [react-native-elements/react-native-elements#2387]
**Explain what you did**
Add an error message for an Input component to validate required fields in my login screen.

**Expected behavior**
Show the error message only when renderErrorMessage prop returns false.

**Describe the bug**
The errorMessage is always showing. I even tried to set renderErrorMessage prop to false explicitly and it is still showing the error message.

**Screenshots**
![Screen Shot 2020-06-07 at 20 32 03](https://user-images.githubusercontent.com/39719620/83982929-d19c5880-a900-11ea-9691-ae62fea43774.png)
![Screen Shot 2020-06-07 at 20 32 14](https://user-images.githubusercontent.com/39719620/83982939-deb94780-a900-11ea-912a-cac6b7737729.png)

**Your Environment (please complete the following information):**

| software              | version |
| -------------------- | ------- |
| react-native-elements |    2.0.1     |
| react-native          |    0.62.2     |

**Comment by flyingcircle** [comment]
This is a simple misunderstanding of the prop. `renderErrorMessage`, as described in the docs: "If the error message container should be rendered". This way the spacing where the error appears does not appear/disappear (I hope that makes sense)
See this PR to see what that prop is meant to do: https://github.com/react-native-elements/react-native-elements/pull/1801
To make the error go away, you'll have to supply the string as a state variable.
