### ISSUE TITLE
Unclear which theming options are supported by each component

### ISSUE THREAD

**Issue by daviddelusenet** [react-native-elements/react-native-elements#2389]
I'm using this library and I'm loving it so far!

However, I'm struggling to find out which theming options are supported by each component. For example, I'm now trying to update the theming of the `SearchBar` component but it's just trail and error.

Is there any documentation about all of the theming options for each component? Because I can't find it 😞

**Comment by flyingcircle** [comment]
Theming options follow the same pattern as all styles available. So you should be able to look at what styles are available and use that as a guide as to what's possible for your theme.
