### ISSUE TITLE
Docs don't match Avatar props

### ISSUE THREAD

**Issue by JNotelddim** [react-native-elements/react-native-elements#2393]
Using v2.0.2, and looking at docs for v2.0.2

**Explain what you did**
I was using the `size` prop on the Avatar component, until I just updated and suddenly the prop was gone. It's not very convenient to remove the `size` prop, but if that's what you prefer it'd be fine -- but the docs should at least be updated https://react-native-elements.github.io/react-native-elements/docs/avatar.html#avatarstyle 

** What you were trying to accomplish.  **
Use `Avatar` prop `size` which was replaced with `small`, `medium`, `large`, `xlarge`, `width`, `height`, and it naturally was complaining that there is no `size` prop -- but that confused me because the docs show it. So when I looked at the actual code I figured there was an update and the docs just weren't updated.

**Expected behavior**
Code behaviour should match docs.

**Comment by JNotelddim** [comment]
(maybe this should be another issue, but I also landed on using the new `height` / `width` props that aren't in the docs for one avatar, because i want it smaller than `34`. But any height below `20` doesn't seem to do anything.)

**Comment by flyingcircle** [comment]
`size` was not removed, so I don't know what your error is referring to, but I would guess that it is an error in your code. I just tried today with 2.0.2 and was able to use the `size` prop.
https://github.com/react-native-elements/react-native-elements/blob/next/src/avatar/Avatar.js#L44
