### ISSUE TITLE
ListItem & alignItems center - #1142 is not fixed

### ISSUE THREAD

**Issue by alburdette619** [react-native-elements/react-native-elements#2396]
**Explain what you did**

I reproduced #1142 by placing a ListItem in a View that had the style property `alignItems: 'center'`.

**Expected behavior**

The ListItem will display all of its contents

**Describe the bug**

The ListItem displays none of its contents.

**To Reproduce**

See matching screenshots below.

Initial View:
```javascript
      <View style={{ backgroundColor: 'red' }}>
        <ListItem title="Test" />
      </View>
```
With centering:
```javascript
      <View style={{ alignItems: 'center', backgroundColor: 'red' }}>
        <ListItem title="Test" />
      </View>
```
Removing flex from `contentContainer`.  This seems to fix at least the whole container being shown, but the icons don't seem to show up if added.
```javascript
      <View style={{ alignItems: 'center', backgroundColor: 'red' }}>
        <ListItem title="Test" contentContainerStyle={{ flex: 0 }} />
      </View>
```

**Screenshots**
<img width="350" alt="Screen Shot 2020-06-16 at 1 34 17 PM" src="https://user-images.githubusercontent.com/22638838/84808505-c28b6980-afd6-11ea-9fb1-a4dd7d3962dc.png">
<img width="350" alt="Screen Shot 2020-06-16 at 1 34 26 PM" src="https://user-images.githubusercontent.com/22638838/84808507-c28b6980-afd6-11ea-95b4-a877cbcf6504.png">
<img width="339" alt="Screen Shot 2020-06-16 at 1 34 41 PM" src="https://user-images.githubusercontent.com/22638838/84808508-c28b6980-afd6-11ea-883f-e60fea2045e7.png">

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    `^1.2.7`     |
| react-native          |    `0.62.2`     |

**Comment by flyingcircle** [comment]
I reverted the fix in 2.2.1. There were trade-offs happening elsewhere that I think were worse than this issue. For anyone that runs into this issue simply set the `ListItem`'s `containerStyle` with `alignSelf: 'center'` and that should fix this issue for you
