### ISSUE TITLE
Tooltip - Need support to disable auto hiding of tooltip when touching/scrolling anywhere inside the active tooltip popover container

### ISSUE THREAD

**Issue by anandhakumarpalanisamy** [react-native-elements/react-native-elements#2413]
**Is your feature request related to a problem? Please Describe.**
Need a way to disable auto hiding of tooltip when touching/scrolling anywhere inside the active tooltip popover contents

**Describe the solution you'd like**

- It would be great if the tooltip does not close automatically, when I am scrolling/touching the popover container.

- I would like an option to hide the tooltip container only when we click somewhere outside the tooltip container or a close button  

- I followed the documentation to disable the "toggleOnPress" and use tooltip reference to toggle the popover.

**Creating Tooltip Reference :**

```typescript

likedByToolTipRef = React.createRef<Tooltip>();

```

**Tooltip part**

```typescript
                    <Tooltip
                      ref={this.likedByToolTipRef}
                      toggleOnPress={false}
                      height={280} 
                      width={Dimensions.get("window").width*.90} 
                      popover={this.renderLikedByList()}
                      backgroundColor={"darkslategrey"}
                    >  
                      <TouchableOpacity onPress={() => this.toggleLikedByModal()}>
                        <Text style={styles.userActivityTextStyle}>{this.state.contentHeartCount} {(this.state.contentHeartCount>1)?"Hearts":"Heart"}</Text>
                      </TouchableOpacity>
                    </Tooltip>

```

**Custom tooltip Toggle function**

```typescript

 toggleLikedByModal = () => {
      this.likedByToolTipRef.current.toggleTooltip();
  };

```

**Describe alternatives you've considered**
 Not yet tried 

**Issue Video**

![tooltipissue](https://user-images.githubusercontent.com/30879156/85456629-74123800-b59f-11ea-9890-30516a9a66a0.gif)

- I am loading a scrollable list of items in the tooltip .  It does not allow to scroll over the contents of the list . 

- The touch on the tooltip closes it automatically. Only at certain lucky first times i am able to perform a scroll .

- How to disable this behaviour.

**Comment by flyingcircle** [comment]
@anandhakumarpalanisamy please message me on slack for a thank you from the open collective. I'm @flyingcircle on their as well.
