### ISSUE TITLE
Styled Components and React Native Elements: Invalid props.style key `0` supplied to `Image`

### ISSUE THREAD

**Issue by daviddelusenet** [react-native-elements/react-native-elements#2417]
I'm using Styled Components in combination with React Native Elements in my application. According to [this issue](https://github.com/react-native-elements/react-native-elements/issues/1786) I need to use the `.attrs` function to set the `containerStyle` of my `Image`.

I ended up with this code (which actually works):

```tsx
import { Dimensions } from 'react-native';
import { Image } from 'react-native-elements';
import styled from 'styled-components/native';

export const StyledArtwork = styled(Image).attrs({
    containerStyle: {
        height: Dimensions.get('window').width,
        width: '100%',
    },
})``;
```

However, when I use this component I get the following error:

```bash
Failed prop type: Invalid props.style key `0` supplied to `Image`.
Bad object: {
  "0": {},
  "position: "absolute",
  "left: "0",
  "right: "0",
  "top: "0",
  "bottom: "0"
}
Valid keys: [
  // A list with all of the valid keys
]
```

| software              | version |
| --------------------- | ------- |
|react-native-elements|2.0.2|
|react-native|0.62.2|
|styled-components|5.1.1|

Please let me know if you need any more information and thanks in advance!

**Comment by flyingcircle** [comment]
Related to: https://github.com/styled-components/styled-components/issues/645
https://github.com/GeekyAnts/NativeBase/issues/575
`Image` style does not currently accept an array which is what the styled components is passing it. We could fix it for this one prop, but I suspect that there is an issue with more than just `Image.style`. I'll keep this in mind with the refactor I'm hoping to do in v3.

**Comment by githuboftigran** [comment]
Had the same issue.
Temporary fix `delete roundStyle['0'];` saved the day.
```
const RoundImage = ({ size, style, ...restProps }) => {
  const roundStyle = {
    ...style,
    width: size,
    height: size,
    borderRadius: size / 2,
  };
  delete roundStyle['0'];
  return <Image style={roundStyle} {...restProps} />;
};
```

**Comment by alexttyip** [comment]
Not sure if this is strictly related but it is related to styled-components too so I will put it here:

Avatar straight up does not work with styled-components, no warnings whatsoever.
