### ISSUE TITLE
jest: The above error occurred in the <Card> component

### ISSUE THREAD

**Issue by ggunti** [react-native-elements/react-native-elements#2418]
**Explain what you did**
I just wanted to run a test. I execute the `npm run test` command.

**Expected behavior**
Run test without any error.

**Describe the bug**
The test ran okay, it passed, but I always obtain an error message regarding `react-native-elements` `Card` component. How could I solve it?:
<img width="1357" alt="Captură de ecran din 2020-06-24 la 19 10 00" src="https://user-images.githubusercontent.com/26307699/85596099-1e4a9800-b652-11ea-8673-41a691b79b6f.png">

**To Reproduce**
My `__tests__/App-test.js` file looks like this:
```
import 'react-native';
import React from 'react';
import App from '../src/App';
// Note: test renderer must be required after react-native.
import renderer from 'react-test-renderer';

it('renders correctly', () => {
  renderer.create(<App />);
});
```

Then just run the `npm run test` command.

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     ^2.0.2    |
| react-native          |    0.62.0     |

**Comment by flyingcircle** [comment]
You have to post your `Card` code since that's where the error is?

**Comment by flyingcircle** [comment]
That's not pointing to RNE `Card. This is about `react-navigation`'s `Card.js`

**Comment by ggunti** [comment]
I understand. Thanks for your response.
But how did you find out where is it pointing? I see `ThemeProvider` in the stack, that's why I think it is from `react-native-elements`. Yes, there is also `Router` in the stack, but it is just a file from my source code, as you can see:
<img width="1032" alt="Captură de ecran din 2020-06-24 la 21 14 25" src="https://user-images.githubusercontent.com/26307699/85610504-bdc25780-b65f-11ea-9d38-ea057b3b6751.png">

**Comment by flyingcircle** [comment]
react-navigation also has a `ThemeProvider` there's nothing in your stack that is obviously coming from RNE. None of the code you've even posted shows you ever importing RNE anywhere.
