### ISSUE TITLE
ListView actions

### ISSUE THREAD

**Issue by rodrigore** [react-native-elements/react-native-elements#242]
Hi, I was wondering how can I implement something like *ion-option-button* from Ionic, where I can select some item from the list and choose some actions.

![screen shot 2017-03-22 at 10 54 06 pm](https://cloud.githubusercontent.com/assets/1557305/24228401/ba0d9454-0f52-11e7-9275-c93546309b7e.png)

**Comment by binoy14** [comment]
@rodrigore We do not have this implemented yet, it is in our roadmap. If you would like to help us build it, feel free to send a PR and we will review it. Thank you

**Comment by Monte9** [comment]
For starters, please look at this [react-native-swipe-list-view](https://github.com/jemise111/react-native-swipe-list-view).

I'd be open to the idea of using another library under the hood to provide this functionality. Please let me know if anyone would like to submit a PR for this.

**Comment by MrHubble** [comment]
@rodrigore did you end up using https://github.com/jemise111/react-native-swipe-list-view? If yes, would you recommend using it in combination with react-native-elements?

**Comment by Monte9** [comment]
@MrHubble we haven't added this to RNE yet, and I personally haven't used it before.

But looks like it's being actively maintained and it also have about ~900 stars on it. So I'd think that it would be a good package to use if you wanted that functionality. And sure, you could use it alongside RNE too.

**Comment by kennylbj** [comment]
Any plan to combine `react-native-swipe-list-view` with RNE listItem? It seems that the swipe actions are common usage. XD
