### ISSUE TITLE
Docs nor demo app seems to show how to use error in Input

### ISSUE THREAD

**Issue by enigmablue** [react-native-elements/react-native-elements#2421]
I'm trying to figure out how to use the error message and set up conditions for the text input.
There is props on showing error message.

But how do i set the trigger and conditions?

**Comment by flyingcircle** [comment]
If `errorMessage` is set, then it shows. Set it to a blank string to make it no longer appear.
`renderErrorMessage` should probably more be "display the errorMessage container". So whether the message is showing or not the container where the `errorMessage` appears does not appear/disappear.

**Comment by enigmablue** [comment]
Thanks! what is this renderErrorMessage? I dont see it in the props

**Comment by flyingcircle** [comment]
Hmm I updated the docs today, and might have messed something up. But you can read about that prop here in the `next` branch of the docs: https://react-native-elements.github.io/react-native-elements/docs/next/input.html#rendererrormessage
