### ISSUE TITLE
ButtonGroup containerStyle flexWrap not working

### ISSUE THREAD

**Issue by brickmaker17** [react-native-elements/react-native-elements#2428]
**Explain what you did**

I had 4 buttons and added the following to the ButtonGroup containerStyle, buttonStyle, buttonContainerStyle `containerStyle={{
            flex: 1,
            height: 500,
            width: 500,
            flexWrap: 'wrap',
            backgroundColor: 'blue',
          }}
          buttonStyle={{
            flex: 1,
            margin: 10,
            backgroundColor: 'green',
          }}
          buttonContainerStyle={{
            flex: 1,
            height: 100,
            width: 100,
            margin: 10,
            backgroundColor: 'red',
          }}`

**Expected behavior**

I was expecting the last button buttonContainerStyle to wrap to next line

**Describe the bug**

I can flexWrap within the buttonContainerStyle but I cant flexWrap the containerStyle

**To Reproduce**

to reproduce the issue add the following style to a 4+ ButtonGroup ` containerStyle={{
            flex: 1,
            height: 500,
            width: 500,
            flexWrap: 'wrap',
            backgroundColor: 'blue',
          }}
          buttonStyle={{
            flex: 1,
            margin: 10,
            backgroundColor: 'green',
          }}
          buttonContainerStyle={{
            flex: 1,
            height: 100,
            width: 100,
            margin: 10,
            backgroundColor: 'red',
          }}`

**Screenshots**
<img width="401" alt="Screen Shot 2020-07-02 at 8 20 13 PM" src="https://user-images.githubusercontent.com/34072446/86425202-bc1d1300-bca1-11ea-93c4-14010242cfd7.png">

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |      2.0.4   |
| react-native          |    0.62.2     |

**Comment by brickmaker17** [comment]
The only way that I can get it to wrap is when the containerStyle width is 80 or less

**Comment by flyingcircle** [comment]
Figured this out. `flexWrap` doesn't work with `flex: 1` so you need remove the `flex:1`'s that you have there and add `flex: 0` to the `buttonContainerStyle`.

**Comment by guigralho** [comment]
I'm still having the same issu
