### ISSUE TITLE
ReactNative versions bigger than 0.61 will have toolbar-android error

### ISSUE THREAD

**Issue by Zkuns** [react-native-elements/react-native-elements#2429]
My versions
```
"react": "16.11.0",
"react-native": "0.62.2"
```

 When I use react-native-elements, I will get an error

> Unable to resolve module `@react-native-community/toolbar-android` from `node_modules/react-native-vector-icons/lib/toolbar-android.js`: @react-native-community/toolbar-android could not be found within the project.

After google, I find that is [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) project issue, ToolbarAndroid was deleted in ReactNative 0.61 but it is still used in latest version of react-native-vector-icons

react-native-vector-icons already fixed it in [https://github.com/oblador/react-native-vector-icons/issues/1104](https://github.com/oblador/react-native-vector-icons/issues/1104) .But it is not yet published new version to fix npm.

My temporary fix method
```
yarn add @react-native-community/toolbar-android
```

**Comment by flyingcircle** [comment]
Yep, that's an issue with the vector-icons library. Thanks for the note for others.
