### ISSUE TITLE
Button onPress not working in android

### ISSUE THREAD

**Issue by prakhar28** [react-native-elements/react-native-elements#2431]
The onPress is not working on the android device. 
`<>
<StatusBar backgroundColor={theme.bgColor} barStyle={'dark-content'} />
<Button					
title="Schedule a Free Trial"					
onPress={() => {console.log('pressesd');}}
/>			
</>`

This is my complete code and it is working in ios device but it is not working in the android device. Can you please check it.

**Comment by flyingcircle** [comment]
Feel free to make a minimal example either in a repo or an expo example showing the error.

**Comment by flyingcircle** [comment]
Was not able to reproduce. Please provide a minimal snack example and I'll reopen the ticket.

**Comment by Rutger** [comment]
I'm also having this issue. I think it only happens when the **debugger** is on.

**Comment by fengmingye** [comment]
I'm also having this issue. I also happens when the debugger is off

**Comment by pranshuchittora** [comment]
> I'm also having this issue. I also happens when the debugger is off

Can you provide a demo on the snack, reproducing the following issue? And the version of rne you are using too.

**Comment by JaapWeijland** [comment]
I just verified that this happens with:

`<ListItem onPress={() => Alert.alert("Click!')} />`

However, when debug mode turned off, it works perfectly fine. Note that my `ListItem` is placed inside a `react-navigation@4` drawer. Since it is debugger-related I cannot create a snack for it.

**Comment by heysoftwaredave** [comment]
Any update on this? I am also having this issue 
import {Button} from 'react-native-elements';
...
          <Button
            title="Choose Something"
            buttonStyle={{
              backgroundColor: '#60A1F1',
              borderRadius: 10,
            }}
            onPress={() => console.log('I am being pressed')}
          />

**Comment by flyingcircle** [comment]
@heysoftwaredave  or any future commenters. Please recreate this on a snack and post it here and then I will gladly reopen the ticket. I have tried the code suggested and am unable to reproduce the error.

**Comment by JaapWeijland** [comment]
For me it had to do with this:

https://github.com/facebook/react-native/issues/27008

**Comment by abrahamjsb** [comment]
Hello, thanks. Did you ran it on android device? still doesn't change the text. Anyway I fint the solution using the prop TouchableComponent and use TouchableOpacity from react-native-gesture-handler. 

https://snack.expo.io/@abrahamjsb/bug-button-onpress
