### ISSUE TITLE
Easily change the entire font system

### ISSUE THREAD

**Issue by Johan-dutoit** [react-native-elements/react-native-elements#2433]
**Is your feature request related to a problem? Please Describe.**
Currently it's pretty painful to change the font family across the board.

**Describe the solution you'd like**
Perhaps setting the font via the theme

**Describe alternatives you've considered**
Changing the `fonts.js` file directly in the `config` folder and then using `npx patch-package react-native-elements`

**Comment by flyingcircle** [comment]
Isn't this already possible? You can change components default props using the `ThemeProvider`: https://react-native-elements.github.io/react-native-elements/docs/customization
