### ISSUE TITLE
Mention that react-native-elements support web in https://reactnative.directory/?web=true

### ISSUE THREAD

**Issue by CyxouD** [react-native-elements/react-native-elements#2438]
**Is your feature request related to a problem? Please Describe.**
-

**Describe the solution you'd like**
Mention that react-native-elements support web in https://reactnative.directory/?web=true

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by flyingcircle** [comment]
https://github.com/react-native-directory/website/pull/401
