### ISSUE TITLE
Avatar not using fallback on title when source is undefined

### ISSUE THREAD

**Issue by Relax594** [react-native-elements/react-native-elements#2442]
**Explain what you did**

Set source to undefined to show the placeholder title

**Expected behavior**

If source is undefined fallback on the defined title as placeholder

**Describe the bug**

Avatar does not fallback to placeholder title when source set to undefined.

**To Reproduce**

Example:

```bash
const [avatar, setAvatar] = useState({uri: 'https://s3.amazonaws.com/uifaces/faces/twitter/ladylexy/128.jpg' });

const removeAvatar = () => {
 setAvatar(undefined);
}

<Avatar
           rounded
           size="large"
           title={benutzerName.charAt(0)}
           containerStyle={styles.avatarContainer}
           showAccessory
           onAccessoryPress={removeAvatar}
           source={avatar}
    />
```

**Screenshots**

Avatar with image:
![image](https://user-images.githubusercontent.com/22765758/87876124-2c33d480-c9d6-11ea-9a98-f9798d7da393.png)

Avatar with source set to undefined:
![image](https://user-images.githubusercontent.com/22765758/87876114-23430300-c9d6-11ea-8f35-93f5c7e10cbe.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  2.0.4   |
| react-native          |   0.63.1   |

**Comment by djhr** [comment]
avatar seems quite broken on v2, even the basic examples from docs doesn't work, e.g.
```
// Avatar with Title
<Avatar rounded title="MD" />

// Avatar with Icon
<Avatar rounded icon={{ name: 'home' }} />
```

**Comment by daryllukas** [comment]
@djhr @flyingcircle fallback seems to be working fine for me. It's just not visible on a white background. See [Snack](https://snack.expo.io/@daryllukas/avatar-fallback)

**Comment by flyingcircle** [comment]
@daryllukas is correct. The placeholder background is `transparent` and the default text color is `white`. So you either need to change the default text color style in the Avatar, or change your background color.

**Comment by sureshcapternal** [comment]
It's still not working on Android.
<img width="1437" alt="Screen Shot 2020-08-03 at 11 24 36 AM" src="https://user-images.githubusercontent.com/15980110/89150346-fcf79880-d57b-11ea-848e-27e40652ee90.png">

**Comment by pamojadev** [comment]
any fix for android yet? Avatar doesn't fallback to icon either when source is undefined

**Comment by arpitBhalla** [comment]
Hey @pamojadev would it be possible for you to create new issue with updated info.
