### ISSUE TITLE
[Android] SearchBar not showing Icons.

### ISSUE THREAD

**Issue by DodoTheDeveloper** [react-native-elements/react-native-elements#2443]
**Explain what you did**

I wanted to use the SearchBar in an Android/iOS environment.

**Expected behavior**

The SearchBar and it's icons render correctly.

**Describe the bug**

When using the SearchBar on Android, the icons are not getting rendered correctly for me. iOS does not have this issue.

![image](https://user-images.githubusercontent.com/38818906/87882106-2a7e0700-c9fe-11ea-915c-f76449d9eb78.png)

I manually added <Icon> but those would also not render correctly.

**To Reproduce**

I created a completely new react-native demo project and only added react-native-elements and react-native-vector-icons. Added the SearchBar to the App.js component and could immediately reproduce it, as can be seen in the screenshot.

Weirdly, when using a Snack, I can not reproduce this error.

https://snack.expo.io/NGGoIIgqz

**Screenshots**

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements | 2.0.4 |
| react-native-vector-icons | 7.0.0 |
| react-native          | 0.63.1 |

**Comment by codeandgabe** [comment]
Did you correctly linked the react-native-vector-icons library?

**Comment by DodoTheDeveloper** [comment]
@codeandgabe Hey, thank you for your hint. 

I had to add the folliwng to my app/build.gradle:

`apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"`

as stated at https://github.com/oblador/react-native-vector-icons. I thought autolinking would work. I'm closing this issue.
