### ISSUE TITLE
Avatar placeholderStyle props: backgroundColor not working

### ISSUE THREAD

**Issue by daryllukas** [react-native-elements/react-native-elements#2447]
**Explain what you did**
Set source to undefined to show the title as a place holder. Then I changed the `backgroundColor` in the `placeholderStyle` prop
```
<Avatar
    rounded
    showAccessory
    title="GA"
    size="xlarge"
    onAccessoryPress={() => console.log('Accessory pressed')}
    placeholderStyle={{backgroundColor: '#0047f7'}}
/>
```

**Expected behavior**
If source is undefined, fallback on the defined title as placeholder with the background color set to `#0047f7`

**Describe the bug**
Avatar placeholder does not use the `backgroundColor` specified in the `placeholderStyle` prop. I suspect this is what's happening with issue #2442 . At first, before changing the background color of the placeholder, I couldn't see the placeholder entirely because the background color of the container component was white. But after changing the container background, I noted the the Avatar component was indeed using the title as a fallback but wasn't using the background set in `placeholderStyle`.

**To Reproduce**
Refer to this [Expo Snack](https://snack.expo.io/@daryllukas/react-native-elements-avatar-placeholder)

**Screenshots**
![Screenshot_1595500376](https://user-images.githubusercontent.com/1014489/88279096-ce5c0100-cce3-11ea-89e6-73cc3cbaa74c.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    2.0.4     |
| react-native          |  0.63.1       |

**Comment by flyingcircle** [comment]
`Placeholder` is exactly this: a place holder while the `Image` is being fetched. If there is no `source` provided, then the placeholder `backgroundColor` is set to `transparent`. To set the `backgroundColor` in this instance, you should instead use `containerStyle`.
