### ISSUE TITLE
Icon's containerStyle has no effect

### ISSUE THREAD

**Issue by ThatMate** [react-native-elements/react-native-elements#2448]
**Explain what you did**

Trying to set `backgroundColor` of `<Icon>` component something like this:

```
          <Icon
            name="arrow-right"
            type="font-awesome"
            containerStyle={{backgroundColor: 'red'}}
            raised
          />
```

**Expected behavior**

Background color should have been red.

**Describe the bug**

Background color stays the default value

**To Reproduce**

Try creating an icon as specified earlier

**Screenshots**

![containerStyle has no effect](https://i.imgur.com/hvTHpXU.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    ^2.0.2     |
| react-native          |    0.62.2     |

**Comment by ThatMate** [comment]
Possibly, the same bug is causing this issue: https://github.com/react-native-elements/react-native-elements/issues/2382

**Comment by flyingcircle** [comment]
This has to do with how `raised` or `disabled` is affecting the styling of the component. Looking at the code, I don't see any obvious solution atm.

**Comment by ThatMate** [comment]
Actually, I had to use `raised` because I wanted to get the solid circle around the icon as displayed in the document, here: https://react-native-elements.github.io/react-native-elements/docs/icon.html

I wanted to achieve the result as shown in the row marked with # 1
![Icons with solid background color](https://i.imgur.com/vyayzau.png)

I assume in that case, this would be right way to get the colored background:

```
          <Icon
            name="arrow-right"
            type="font-awesome"
            color={primaryColor}
            containerStyle={{
              backgroundColor: secondaryColor,
              height: 50,
              width: 50,
              borderRadius: 25,
              justifyContent: 'center',
              alignItems: 'center',
              elevation: 1
            }}
            onPress={onNext}
          />
```

If that's the case please close the ticket, and thanks for the quick reply I really appreciate it. 💯

**Comment by flyingcircle** [comment]
Yes I think that row was created by applying both `raised` and `reverse`. and then you can set `color={backgroundColor}` and `reverseColor={iconColor}`. I believe that should work. If that doesn't work, let me know and I can reopen the ticket.

**Comment by ThatMate** [comment]
That did the magic. Thanks a lot!

**Comment by RyanTG** [comment]
For me, that does not do the trick. If I use `raised` and `reverse` it's not raised. It's only when I add `containerStyle={{overflow: 'visible'}}` that it gets raised. However, with that, the icon turns into a square when pressed.

````
                                    <Icon
                                        raised
                                        reverse
                                        name='tools'
                                        type='entypo'
                                        color='#1e9dff'
                                        size={25}
                                        containerStyle={{overflow: 'visible'}}
                                        onPress={() => this.setShowLocationToolsModal(true)}
                                    />
````

**Comment by cglacet** [comment]
Did anyone managed to reproduce the documentation image using only the Icon component?
