### ISSUE TITLE
LinearGradientProps crashes Android build bundle

### ISSUE THREAD

**Issue by y04nqt** [react-native-elements/react-native-elements#2452]
**Explain what you did**

`<Button 
							title='Find More Shifts'
							onPress={()=>navigation.navigate('AvailableShifts')}
							titleStyle={styles.text_bold}
							icon={<MaterialIcons name='search' color="white" size={26} style={{ paddingHorizontal: 10 }}/>}
							containerStyle={styles.margin_20}
							linearGradientProps={
								{
									colors: [colors.blue, colors.blue_dark],
									start: {
										x: 0.5,
										y: 0.5
									}
								}
							} />
`
When this was deployed to Google Play, it would crash the app and cause force closure.
**Expected behavior**

No force closing and no crashing, should show the linearGradient as it would using expo.

**Describe the bug**

LinearGradientProps causes the react native app to crash when deployed to an Android bundle in the Google Play store.

**To Reproduce**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:
# Steps
1. Add a button to the app with linearGradientProps
2. Publish to Android release bundle
3. Open app and navigate to screen with the linearGradientProps button
4. See the app crashes

**Screenshots**

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements | ~2.0.0 |
| react-native          | https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz (0.61) |

**Comment by flyingcircle** [comment]
If this is happening only in the release build then it sounds like this is likely an Expo issue not an RNE issue. I suggest opening a ticket there.
