### ISSUE TITLE
The icon of socialIcon does not show

### ISSUE THREAD

**Issue by lisichka999** [react-native-elements/react-native-elements#2454]
I am using the socialIcon in the following way:

```
<TouchableOpacity style={styles.buttonContainer} onPress={handleFacebookLogin}>
     <SocialIcon style={styles.SocialIconButton} title="Continue with Facebook" button type="facebook" />
</TouchableOpacity>
```
But the icon never show:

![20200727_221335](https://user-images.githubusercontent.com/44223548/88582124-dfe03880-d056-11ea-867a-df3b84e505e8.jpg)

**Comment by flyingcircle** [comment]
You don't post what your environment is here (expo/cli) (ios/android/web). By default, social icon uses `font-awesome`, so you'll need to make sure that `react-native-vector-icons` is available and setup correctly for your environment.
