### ISSUE TITLE
Issue in opening the QR code on React Native Elements App Website

### ISSUE THREAD

**Issue by y471n** [react-native-elements/react-native-elements#2456]
On scanning the QR code on https://expo.io/@monte9/react-native-elements-app, encountered the following issue:

The experience you requested uses Expo SDK v34.0.0 but this copy of Expo client requires at least v35.0.0 The author should update their experience to a newer Expo SDK version.

**Comment by flyingcircle** [comment]
Duplicate of https://github.com/react-native-elements/react-native-elements-app/issues/112
