### ISSUE TITLE
Input prop renderErrorMessage not working as expected

### ISSUE THREAD

**Issue by mikoyats** [react-native-elements/react-native-elements#2457]
**Explain what you did**

Render `Input` error message conditionally

**Expected behavior**

If `renderErrorMessage` prop is set to false, it will hide `errorMessage`. 
If true, will show the `errorMessage`.

**Describe the bug**

`errorMessage` will show regardless of `renderErrorMessage` value.

**To Reproduce**

**Snack**
https://snack.expo.io/@mikoyats/c2a2fb

**Steps**
1. Set `errorMessage` to 'This field is required' (the error will show by default)
2. Set `renderErrorMessage` to true (The error will show)
3. Set `renderErrorMessage` to false (The error will still show)

**Screenshots**

![Input required](https://user-images.githubusercontent.com/61535706/88638621-4f553700-d0ee-11ea-9e25-e378b9ab44e3.gif)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements | 2.0.4 |
| react-native          | 0.62.2 |

**Comment by saxenanihal95** [comment]
@mikoyats `renderErrorMessage` is to handle the space taken by the errorMessage prop

Please check this comment: https://github.com/react-native-elements/react-native-elements/pull/1801#issuecomment-552477806

So when `errorMessage` is present it will show error, even if `renderErrorMessage` is false

**Comment by mikoyats** [comment]
Ah, that explains things. 
The prop is currently not in the documentation listed here:  [link](https://react-native-elements.github.io/react-native-elements/docs/input.html#props) 
And then I checked it through vscode.
![image](https://user-images.githubusercontent.com/61535706/88760785-576daf00-d1a0-11ea-8d3c-f45fcf4fdd7c.png)


But after checking the GitHub documentation, I found it here: [link](https://github.com/react-native-elements/react-native-elements/blob/next/docs/input.md#rendererrormessage)

So before I seeing that, I thought it was what I expected it to be.

Anyway, I just emptied the errorMessage if I want to hide it.
[Input validation](https://snack.expo.io/@mikoyats/2ec048)
Or
```
const App = () => {
  const [name, setName] = useState('')
  const isNotValid = name == ''
  const errorMessage = isNotValid ? 'This field is required.' : ''

  return <Input onChangeText={setName} errorMessage={errorMessage} />
}
```

**Comment by flyingcircle** [comment]
I'll look into fixing this by end of day today.

**Comment by flyingcircle** [comment]
Fixed in the docs now
