### ISSUE TITLE
[Suggestion] ListItem -> Add divider horizontal margin control

### ISSUE THREAD

**Issue by SrBrahma** [react-native-elements/react-native-elements#2458]
**Is your feature request related to a problem? Please Describe.**
I moved to React Native Elements because my own ListItem was getting so much complex and certainly a lib already did what I was doing. Touché. But, this lib ListItem divider is a border, and being a border, we can't change its size without changing the View size.

**Describe the solution you'd like**
Maybe a style prop to change the divider style (maybe one for top and one for bottom divider)

**Describe alternatives you've considered**
In my ListItem I've made, I had this to control the divider size
```
{ hasSeparator &&
    <View style={{ backgroundColor: backgroundColor, paddingHorizontal: 18 }}>
        <View style={{ height: 1, backgroundColor: separatorColor || styles.separator.borderBottomColor }}/>
    </View>
```

**Additional context**
Android settings, Whatsapp settings... most of the Apps don't use a 100% width divider. It really looks awkward.

**Comment by flyingcircle** [comment]
The top and bottom dividers simply set the `borderTopWidth` and `borderBottomWidth` in the `containerStyle` respectively. So any overriding or customization to those borders can already be done inside of `containerStyle`.

**Comment by SrBrahma** [comment]
I don't mean the thickness of the border, but its length.

I managed to get it working with this:

containerStyle={{
        backgroundColor: '#0000',
        paddingLeft: 0,
        paddingRight: 0,
        marginLeft: 20,
        marginRight: 20
}}

Without this transparent bgc, the highlight was strange, coloring the inner and out areas differently.

**Comment by SrBrahma** [comment]
Also, there isn't a way to make the divider be only below the title/subtitle (and maybe below the right icon, as Apps usually do). The divider is always below the left icon (not common in Apps)

**Comment by flyingcircle** [comment]
Yes I would agree with you that the `ListItem` is somehow both the kitchen sink of components but also is not very easy to customize. `ListItem` needs to be refactored quite badly. It's near the top of my to do list.

**Comment by SrBrahma** [comment]
Here is my current ListItem code using the lib one and implementing the Pressable and the divider. Not a very pretty solution, but works for what I need right now. For iOS will certainly need the onPress style change.

```
import React from 'react';
import { ListItem, ListItemProps } from 'react-native-elements';
import { Pressable, View, StyleSheet } from 'react-native';


interface MyListItemI extends Omit<ListItemProps, 'bottomDivider'> {
  blankLeftIcon?: number | boolean, // You may pass the size of the icon.
  bottomDivider?: boolean | 'full' | 'mid'
}

const iconDefaultSize = 24;
const defaultPaddingLeft = 22;
const defaultPaddingRight = 22;
const defaultVerticalPadding = 18;

export const MyListItem: React.FC<MyListItemI> = ({ blankLeftIcon: leftIconPad, chevron, bottomDivider, ...rest }) => {

  function divider() {
    if (!bottomDivider)
      return;

    if (bottomDivider === 'full')
      return <View style={{ height: StyleSheet.hairlineWidth, backgroundColor: '#0004' }}/>;

    let marginLeft = defaultPaddingLeft - 2;

    if (leftIconPad) {
      marginLeft  += 16; // 16 is the default 'pad' of ListItem between icon and text
      if (typeof leftIconPad === 'number')
        marginLeft += leftIconPad;
      else
        marginLeft += iconDefaultSize;
    }

    if (rest.leftIcon) {
      if ((rest.leftIcon as any).size)
        marginLeft += (rest.leftIcon as any).size;
      else
        marginLeft += iconDefaultSize;
    }

    return <View style={{
      backgroundColor: '#0000',
      marginLeft: marginLeft,
      marginRight: defaultPaddingRight,
    }}>
      <View style={{ height: StyleSheet.hairlineWidth, backgroundColor: '#0004' }}/>
    </View>;

  }
  return (<>
    <ListItem
      Component={Pressable as any}
      chevron={chevron === true ? ({ size: 24 }) : chevron}
      // TODO: iOS will need style here. It's possible to pass pressed arg to style
      // https://reactnative.dev/docs/pressable#style
      // But probably will need to disable ripple.
      containerStyle={{
        backgroundColor: '#0000',
        paddingLeft: defaultPaddingLeft,
        paddingRight: defaultPaddingRight,
        paddingVertical: defaultVerticalPadding,
      }}
      {...{ android_ripple: { color: '#0002' } }}
      {...leftIconPad && { leftIcon: {
        name: 'add', color: '#0000',
        size: typeof leftIconPad === 'number' ? leftIconPad : undefined
      } }}
      {...rest}
    />

    { divider()}

  </>);
};
```
