### ISSUE TITLE
[Suggestion] ListItem -> Add a new text field

### ISSUE THREAD

**Issue by SrBrahma** [react-native-elements/react-native-elements#2459]
**Is your feature request related to a problem? Please Describe.**
Whatsapp app have a ListItem feature that it doesn't seem possible to do with this lib.

![image](https://user-images.githubusercontent.com/28177550/88761693-ffa25a00-d145-11ea-8795-8f744879c4fb.png)

**Describe the solution you'd like**
It looks like it's an 'preTitle', or a subSubTitle (**more** likely to be a preTitle, as my name there is bold, and all titles in the app are bold). So, ListItem would need 2 new props, preTitle and preTitleStyle.

**Comment by SrBrahma** [comment]
I think this got wrongly closed.

Also, came here to say that I implemented this "pretitle" as a title component, but, the icons were logically center aligned to the entire view unlike the post image, that the icons are certainly center aligned to the view of the pretitle and the title. It looks better in the image way.

Also, I can't understand the new ListItem.js file (https://github.com/react-native-elements/react-native-elements/blob/next/src/list/ListItem.js). Will title and subtitle (etc) be deprecated?

**Comment by flyingcircle** [comment]
@SrBrahma Yes title and subtitle are getting deprecated and I'm planning on removing them for v3. With the new version You should be able to create a more custom `ListItem` as you want here. Check out the working blog article that I have on this change: https://react-native-elements.github.io/react-native-elements/blog

Hopefully after all the deprecated code is removed, the code will be much easier to read.

So I think you should be able to implement that view with the new `ListItem`. If you come up with a subcomponent for `ListItem` that ends up creating this look, I'm still up for adding it. But to be honest, to me, it looks quite specific to your use case. Let me know how trying out the new `ListItem` goes.

**Comment by SrBrahma** [comment]
Looks really cool! Will port my current code to it and give you a feedback and post here my code. I was even going to create a new feature request to allow left icon styling (to add a padding between it and the texts), but seems it is already possible with this new feature.

**Comment by flyingcircle** [comment]
`ListItem.Content` is to replace the box `View` that held both the `title` and `subtitle`. I agree, not the prettiest solution. But it was the easiest way to refactor out the old method and have a direct 1-to-1 from the old style to the new style. I'm hoping to do the same thing for `Card` and maybe `Tile` as well.

**Comment by SrBrahma** [comment]
Can't LisItem have by default a ListItem.Content?
