### ISSUE TITLE
react native avatar showEditButton Isnt working

### ISSUE THREAD

**Issue by aleluiah** [react-native-elements/react-native-elements#2461]
react native avatar show edit button isnt working

**Comment by flyingcircle** [comment]
This was a docs error. The prop is named: `showAccessory`

**Comment by rojingharooni** [comment]
i solved it by adding <Avatar.Accessory size={24} onPress={() => console.log("Accessory worked!")} />
inside <Avatar> tag

`             <Avatar  rounded title="MD" size="large" >
                     <Avatar.Accessory size={24} onPress={() => console.log("accesory!")} />
            </Avatar>`
