### ISSUE TITLE
Tooltip positioning issue on android still exists in version 2.0.4.

### ISSUE THREAD

**Issue by saadsaleem187** [react-native-elements/react-native-elements#2462]
**Explain what you did**

**Expected behavior**

**Describe the bug**

**To Reproduce**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Screenshots**

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |         |
| react-native          |         |

**Comment by saadsaleem187** [comment]
When i tap on tooltip on android it changes it's position. On iOS it's working fine. I modify in Tooltip.js by changing yOffset: pageOffsetY. Now tooltip position is fixed on android. Kindly resolve this issue asap.
react-native-elements: 2.0.4
react-native: 0.62.2

**Comment by molchanovskiy** [comment]
Same for me.
How it can be fixed?
![IMG_3673](https://user-images.githubusercontent.com/8407709/89153273-3d9be580-d56d-11ea-8f87-f37f5f08e286.jpg)

**Comment by abhi4098** [comment]
Use this from props `skipAndroidStatusBar ={true}`.It worked for me 👍

**Comment by arpitBhalla** [comment]
@Ashutosh-Tiwari can you check with bleeding edge version? 

```bash
expo init app --template react-native-elements-template@bleeding-edge
```

**Comment by Ashutosh-Tiwari** [comment]
@arpitBhalla 
I imported the tooltip from `@react-native-elements/themed` and implemented the snippet. But nothing's popping up. What am I doing wrong?

![image](https://user-images.githubusercontent.com/17219007/154635955-19cdd982-45f2-449c-8b37-ac6081362f49.png)

**Comment by arpitBhalla** [comment]
Refer [Migration Guide](https://reactnativeelements.com/docs/next/migration_guide#tooltip)

**Comment by arpitBhalla** [comment]
I am not sure about this, but bleeding edge is stable, you can surely add it to your project.

**Comment by arpitBhalla** [comment]
Try `closeOnlyOnBackdropPress={true}`

**Comment by arpitBhalla** [comment]
@Ashutosh-Tiwari Can you confirm other `Tooltip` open issues, if they are working now?

**Comment by Ashutosh-Tiwari** [comment]
Can we set the height to be dynamic by setting height={null}? If yes, I don't see any other issue with the tooltip as of now, but I'll keep you posted as the tooltip is heavily used in my project.
