### ISSUE TITLE
expo demo app is outdated

### ISSUE THREAD

**Issue by axetroy** [react-native-elements/react-native-elements#2468]
Scanning the code with the latest version of expo can no longer open the app.

Upgrade expo SDK and publish a new App.

Thx for your great job!

**Comment by flyingcircle** [comment]
This was already updated. Try refreshing the docs page: https://expo.io/@flyingcircle/react-native-elements-app

**Comment by axetroy** [comment]
@flyingcircle Thx. There seems to be another problem

I don't have permission to open this project

**Comment by axetroy** [comment]
> Note that Expo Client on iOS can no longer open published projects that don't belong to the signed in user.
> More info on this change can be found on https://expo.io/ios-limitations

**Comment by flyingcircle** [comment]
@axetroy that's unfortunate to hear. You are always able to download the repo and try out the demo app: https://github.com/react-native-elements/react-native-elements-app It should be fairly straightforward how to open up the app.
