### ISSUE TITLE
Linear gradient props for Overlay overlayStyle ?

### ISSUE THREAD

**Issue by enigmablue** [react-native-elements/react-native-elements#2473]
ListItem has a way to add linear gradients to the background.

Is there a way or can there be a way to add one for Overlay background too? Thank you

**Comment by flyingcircle** [comment]
You might be able to do it by passing in a child component that uses the `LinearGradient` Component? The one in `ListItem` is all done through Expo's `LinearGradient`. You might be able to  do it that way.

**Comment by flyingcircle** [comment]
Let me know if I haven't fully answered your question or come check out the Slack channel where you can ask others for help on this as well.
