### ISSUE TITLE
Avatar Title not showing on "Android device"

### ISSUE THREAD

**Issue by sureshcapternal** [react-native-elements/react-native-elements#2475]
**Explain what you did**

Trying to set Avatar title in both Avatar and ListItem component.

**Expected behavior**

Title must be there if url is undefined or blank same as iOS and Web.

**Describe the bug**

Title shows for few seconds and disappears on android devices.

**To Reproduce**
Reproduced on Snack

**Screenshots**

<img width="1552" alt="Screen Shot 2020-08-03 at 11 47 25 AM" src="https://user-images.githubusercontent.com/15980110/89152512-e869cf00-d580-11ea-8568-8afe6c1275d8.png">

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   2.1.0      |
react-native-cli.    |    2.0.1     |
react-native.         |  0.62.2

**Comment by flyingcircle** [comment]
Remove `flex: 1` and you'll see the `Avatar`s appear. Here is the snack rewritten: https://snack.expo.io/70fLLplN!

**Comment by sxs1995** [comment]
I have the same issue. the title is not shown on the android.
![image](https://user-images.githubusercontent.com/22333956/100068155-19dd1200-2e72-11eb-957a-2d4a3e9c3c19.png)

**Comment by ahnafnafee** [comment]
> Remove `flex: 1` and you'll see the `Avatar`s appear. Here is the snack rewritten: https://snack.expo.io/70fLLplN!

Could you share this fix again, if possible? I'm encountering the same issue

**Comment by ahnafnafee** [comment]
If anyone is looking for a fix for android, use this for the source:
```
source={
    card.profilePicUrl
        ? { uri: card.profilePicUrl }
        : undefined
}
```
