### ISSUE TITLE
Chevron defaults to right arrow after upgrading to react-native-vector-icons 6.7 (iOS)

### ISSUE THREAD

**Issue by NathanNovak** [react-native-elements/react-native-elements#2478]
**Explain what you did**
After upgrading to 2.1.0 Chevron defaults to a right arrow on iOS. 

**Expected behavior**

Chevron remain as a chevron unless otherwise specified.

**Describe the bug**

After upgrading to 2.1.0 Chevron defaults to a right arrow on iOS.  did not affect Android.

BEFORE upgrade would display correctly.
`<ListItem 
     ...  
     chevron >`

AFTER upgrade I have to use icon library.
` <ListItem
          ...
          chevron={{
            name: 'right',
            type: 'antdesign',
            color: themes.LIST_CHEVRON_COLOR,
            size: 16,
          }}
        /> `

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements | 2.1.0 |
| react-native          |  0.6.3 |

**Comment by flyingcircle** [comment]
You can double check the changes, but there were no changes made to `ListItem` between `2.0.4` and `2.1.0`. What version did you upgrade from and what version of icons are you using?

**Comment by NathanNovak** [comment]
@flyingcircle We looked into Vector Icons and Ionicons more.  The code in RNE has the chevron for iOS as `arrow-forward`:  

https://github.com/react-native-elements/react-native-elements/blob/aed8d12d9eed90b8d0b9ec4863a3ad264f733562/src/list/ListItem.js#L27

In the new version of Ionicons (5.0.0) they renamed the arrow icon to `arrow-forward` and since Vector Icons is using the newer version of Ionicons the name `arrow-forward` is not the chevron anymore on iOS.  The correct new name for the ionicon chevron is `chevron-forward`.

**Vector Icons Package.json**
https://github.com/oblador/react-native-vector-icons/blob/32bbd538794a5835de685f54bf2dd6c053ede54c/package.json#L85

**Ionicons Change Log**
https://github.com/ionic-team/ionicons/blob/master/CHANGELOG.md

**Comment by flyingcircle** [comment]
So then this has nothing to do with upgrading RNE to version `2.1.0`, but with you probably also updating `react-native-vector-icons` from `6.6.0` to >=`6.7.0`.

I'm open to updating the default if `chevron-forward` is backwards compatible with `6.6.0`, otherwise that change will have to wait for a major update since it will be changing the peer dependency requirement.

**Comment by flyingcircle** [comment]
Also in tracking with this ticket: https://github.com/expo/vector-icons/pull/138 expo/vector-icons has not updated to ionIcons v5 yet, so any change or update would leave out expo users. I think this will have to sit and wait until that update happens. Until then, if you want to use a more recent version of `react-native-vector-icons`, you'll have to make the change manually in your code. I think we have to wait until other packages are updated to make the update and major version bump to RNE.

**Comment by ivansenic** [comment]
You can always set a custom icon in a theme and thus avoid any surprises.
