### ISSUE TITLE
Icon style typescript error

### ISSUE THREAD

**Issue by hengkx** [react-native-elements/react-native-elements#2482]
**Explain what you did**

**Expected behavior**

**Describe the bug**
![image](https://user-images.githubusercontent.com/8358236/89406017-0f75fb80-d74f-11ea-9f9a-936953dd38db.png)
![image](https://user-images.githubusercontent.com/8358236/89406035-14d34600-d74f-11ea-8b26-ec1db9215b20.png)

**To Reproduce**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Screenshots**

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |         |
| react-native          |         |

**Comment by flyingcircle** [comment]
`Icon` has no `style` prop. Use `containerStyle`.

**Comment by hengkx** [comment]
Then TS states that style should be removed

**Comment by flyingcircle** [comment]
Fair enough.

**Comment by flyingcircle** [comment]
I updated the yarn.lock to update to RN-63 types in a recent PR, but I also noticed that here you're trying to pass in an array which isn't listed as a possibility for that type. If you think that that should be changed, look at submitting a PR for `@types/react-native-vector-icons` as that is the source of what is causing the error.
