### ISSUE TITLE
SearchBar resets each time I type

### ISSUE THREAD

**Issue by Alpha110CX** [react-native-elements/react-native-elements#2483]
Hi everyone,
I'm starting an app project in order to learn React Native, and I want to use the SearchBar.
So I'm using Expo to test it directly on my smartphone but I have an issue :
After every letter I type on the bar, it resets. Sometime, i'm fast enough to type 2 letters, then it is erased. When I print the text with "onChangeText", I only have one letter, and sometimes 2, but never the entire word.

Did it happen to someone ?
Thank you

**Comment by flyingcircle** [comment]
Sounds like you aren't updating the `value` in your `onChangeText`. Make sure that you are using `setState` to update the `value` field or the equivalent if using hooks.

**Comment by Alpha110CX** [comment]
Hi, thank you for your answer.
Is it normal to close an issue before the answer of the one who asked the question ?
Because, in my case, the issue is not solved.
![image](https://user-images.githubusercontent.com/23504333/89451574-b8772300-d75c-11ea-85aa-dc5fed736846.png)

I have the same code for a TextInput element, and it's working perfectly, but not on SearchBar

**Comment by flyingcircle** [comment]
I closed the ticket because this is not a bug or feature request. The API and example on how to implement search bar is written here: https://react-native-elements.github.io/react-native-elements/docs/searchbar I suggest that you use the example written there to fix your code.

**Comment by flyingcircle** [comment]
If this is a bug, please feel free to write an expo snack and link it here to demonstrate the bug and then I will reopen the ticket.

**Comment by Alpha110CX** [comment]
Ok, thanks, I've mixed up Issue/Need Help and Bug
