### ISSUE TITLE
ListItem typescript error typo upgrade 2.2.0

### ISSUE THREAD

**Issue by hengkx** [react-native-elements/react-native-elements#2492]
**Explain what you did (Required)**

**Expected behavior (Required)**

**Describe the bug (Required)**
![image](https://user-images.githubusercontent.com/8358236/89738670-0e293380-daad-11ea-9d06-6bc23a8b03c7.png)

**To Reproduce (Required)**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Screenshots (Required)**

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |         |
| react-native          |         |

**Comment by SrBrahma** [comment]
Also happening here.

**Comment by davidgovea** [comment]
Currently working around this using `<ListItem children={null} ...`
