### ISSUE TITLE
SearchBar inputContainerStyle borderBottom not showing

### ISSUE THREAD

**Issue by chansc2016** [react-native-elements/react-native-elements#2495]
**Explain what you did (Required)**
<SearchBar
          placeholder="Find Outlets..."
          onChangeText={setSearch}
          value={search}
          containerStyle={{
            backgroundColor: 'transparent',
            borderBottomColor: 'transparent',
            borderTopColor: 'transparent',
          }}
          inputContainerStyle={{
            backgroundColor: 'trasnaprent',
            borderRadius: 8,
            borderWidth: 1,
            borderStyle: 'solid',
          }}
        />

To show full border

**Expected behavior (Required)**
Border show fully

**Describe the bug (Required)**
As picture

Border bottom not show up

**To Reproduce (Required)**
"react-native-elements": "^2.2.0",

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:
https://snack.expo.io/VCWtJLzzn

**Screenshots (Required)**
![Screenshot 2020-08-10 at 5 15 58 PM](https://user-images.githubusercontent.com/22651091/89768194-e0d09a00-db2d-11ea-8219-b916250be00e.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    2.2.0     |
| react-native          |     0.63.2    |

**Comment by JB1905** [comment]
Hi! 😃
You can add `borderBottomWidth: 1` to `inputContainerStyle`. It works for me.

**Comment by flyingcircle** [comment]
Feel free to open a PR fixing this.

**Comment by JB1905** [comment]
Hi! I can prepare a fix for this issue, but it is related to the Input component.

**Comment by flyingcircle** [comment]
I apologize for not looking a bit more into this earlier. Yes, you can override the `bottomBorderWidth` in your `inputContainerStyle` if you want to change the look and format of the default `SearchBar`
