### ISSUE TITLE
Module 'React native' has no exported member 'PressableProps'

### ISSUE THREAD

**Issue by Marvedog** [react-native-elements/react-native-elements#2496]
**Explain what you did (Required)**

* Upgrade `react-native-elements: v2.2.0` 
* Upgrade `react-native: v0.63.2` 

**Expected behavior (Required)**

Compile with `yarn tsc`. Expects no errors.

**Describe the bug (Required)**

Typescript compiler returns error:

```shell
node_modules/react-native-elements/src/index.d.ts:25:3 - error TS2305: Module '"react-native"' has no exported member 'PressableProps'.

25   PressableProps,
     ~~~~~~~~~~~~~~
```

**To Reproduce (Required)**

* `react-native-elements: v2.2.0` 
* `react-native: v0.63.2` 
* `typescript: v3.8.3`

**Screenshots (Required)**

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  2.2.0  |
| react-native          |  0.63.2  |

**Comment by flyingcircle** [comment]
I am not really a typescript person (though it seems like I need to get better at it). Did you make sure to upgrade your `@types` packages?

**Comment by Marvedog** [comment]
It seems it's I who have to get better at it @flyingcircle :) Thanks for the quick response
