### ISSUE TITLE
Custom font in Button is not centered vertically

### ISSUE THREAD

**Issue by williamgoodhew** [react-native-elements/react-native-elements#2501]
**Explain what you did (Required)**

I have added custom fonts to my Button element - the font is showing up correctly but it is not vertically centred. Please see screenshot - you'll notice it is just above centre.

**Expected behaviour (Required)**

The title prop should be centred vertically in the Button

```
import React from 'react';
import {
  View,
} from 'react-native';

import { Button } from 'react-native-elements';
import {textStyle} from '../../Styles/textStyle';

export default function ButtonMain(props) {
    const {title, onPress, disabled, loading} = props;
    return (
        <View>
            <Button
                raised={true}
                title={title}
                disabled={disabled}
                buttonStyle={{
                    borderRadius: 10,
                    backgroundColor: '#f7d92a',
                }}
                titleStyle={{
                    ...textStyle.input,
                    justifyContent: 'center'
                }}
                containerStyle={{
                    margin: 10,
                    overflow: 'visible',
                }}
                onPress={onPress}
                loading={loading}
            />
        </View>
    );
};
```
```
=>font style = input: {
        color: colors.primaryBlack,
        fontSize: fontSizes.small,
        fontFamily: 'FSLucas-SemiBold',
        fontWeight: fontWeight.medium,
    },
```
![Simulator Screen Shot - iPhone 11 Pro - 2020-08-12 at 12 12 59](https://user-images.githubusercontent.com/32809621/90009179-7dfa1280-dc95-11ea-9343-7c9e9b2db5d1.png)

**Comment by grohj** [comment]
Hey, it happens to me as well when using custom roboto font. The issue gets more noticable as the button gets smaller

![image](https://user-images.githubusercontent.com/16671782/90618914-e35b7f80-e210-11ea-9ea9-72e74795d1f8.png)
![image](https://user-images.githubusercontent.com/16671782/90618987-f8d0a980-e210-11ea-8a58-db29aaab2ff1.png)
![image](https://user-images.githubusercontent.com/16671782/90619057-10a82d80-e211-11ea-9ffb-0761e1698be4.png)

```
fontFamily: fonts.body.regular,
    fontSize: 13,
    textTransform: 'none',
    justifyContent: 'center',
```
