### ISSUE TITLE
`allowTouchTrack` Slider thump position is off when sliding

### ISSUE THREAD

**Issue by hannojg** [react-native-elements/react-native-elements#2509]
**Explain what you did (Required)**

I am using the `Slider` component. I was upgrading from version `2.0.4` to `2.2.1` in order to access the new `allowTouchTrack` prop. Before this upgrade, when sliding, the thumb was at the exact same position of the finger.

**Expected behavior (Required)**

The behaviour hasn't changed.

**Describe the bug (Required)**

The bug is, that the slider's thumb position is a bit ahead of the actual click/grab position.
See the video below.

**To Reproduce (Required)**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

By any means, I am willing to create a reproduction. I am not sure whether this bug is at your attention currently, or whether this is something specific that happens on my side. I will create a reproduction in the next 24 hours. Would be interesting to know meanwhile, whether this happens to other users as well.

When turning the prop `allowTouchTrack` on, the behaviour occurs. When turning it off everything is okay again.

**Screenshots (Required)**
[Video link](https://streamable.com/wo81ch)
<img width="853" alt="Screenshot 2020-08-18 at 22 35 02" src="https://user-images.githubusercontent.com/16821682/90562813-1b2bde00-e1a3-11ea-829f-63a7745896cf.png">

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   2.2.1      |
| react-native          |     0.63.2    |

**Comment by hannojg** [comment]
Okay, reproduction is super simple: just create a slider and set the allowTouchTrack prop:

https://snack.expo.io/@hannojg/allowtouchtrack-bug

**Comment by hannojg** [comment]
@pranshuchittora this is still happening, just tested it on 4.5.0:
https://snack.expo.io/V2eezKjmZ

As you can see in the video, the slider is always to the right of the actual touch position, while I expect it to be at the exact touch position:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16821682/102371011-08dd7780-3fbe-11eb-9a5a-f086bdb76151.gif)

**Comment by pranshuchittora** [comment]
Hi @hannojg it seems that you are using an older version of React Native Elements.

![Screenshot from 2020-12-16 21-20-03](https://user-images.githubusercontent.com/32242596/102371952-bebbbc80-3fe4-11eb-8387-d6e894a38ef8.png)

I updated it to version `3.0.0-alpha.1` and not able to repro the issue.

Could you try this with the above-mentioned version and let me know whether the issue still persists.
Looking forward to hearing back from you.

Happy Hacking :)

**Comment by hannojg** [comment]
Thanks for getting so fastback at me!
Looks like I upgraded the wrong lib 🤦 
However: I just tried it with 3.0.0-beta1 and it still doesn't work (check out the expo snack link again):

![updated-3 0 0-alpha1](https://user-images.githubusercontent.com/16821682/102375625-06315100-3fc3-11eb-818e-3e3a9d04fba9.gif)

**Comment by pranshuchittora** [comment]
Hi @hannojg that's the intended behaviour. If you press and hold and drag the slider will change as this is the intended behaviour of the Pan Gesture Handler. 

What could have been a bug?
If the slider responds outside its area.

The area of response is equal to the height.

Try this on the Playground
Here -> https://react-native-elements.js.org/#/slider

Paste the below code.

```jsx
import * as React from "react";
import { Slider, Icon } from "react-native-elements";

export default () => {
  return (
    <Slider
      animateTransitions
      animationType="timing"
      maximumTrackTintColor="#ccc"
      maximumValue={100}
      minimumTrackTintColor="#222"
      allowTouchTrack
      onSlidingComplete={() =>
        console.log("onSlidingComplete()")
      }
      onSlidingStart={() =>
        console.log("onSlidingStart()")
      }
      onValueChange={value =>
        console.log("onValueChange()", value)
      }
      orientation="horizontal"
      step={1}
      style={{ width: "80%", height: 10 }}
      thumbStyle={{ height: 20, width: 20 }}
      thumbProps={{
        children: (
          <Icon
            name="heartbeat"
            type="font-awesome"
            size={20}
            reverse
            containerStyle={{ bottom: 20, right: 20 }}
            color="#f50"
          />
        )
      }}
      thumbTintColor="#0c0"
      thumbTouchSize={{ width: 2, height: 2 }}
      trackStyle={{ height: 10, borderRadius: 20 }}
      value={50}
    />
  );
}
```
