### ISSUE TITLE
Styling avatar with both titleStyle and avatarStyle doesn't work

### ISSUE THREAD

**Issue by sajeezy** [react-native-elements/react-native-elements#2510]
**Explain what you did (Required)**

I created an avatar with initials. When I tried to apply an avatarStyle and titleStyle it didn't work. 
`<Avatar
              size="large"
              rounded
              onPress={() => console.log('Works!')}
              activeOpacity={0.7}
              title={user.initials}
              titleStyle={{ color: 'white' }}
              avatarStyle={{ backgroundColor: primaryColor }}
            />`

This is the outcome
![image](https://user-images.githubusercontent.com/3699393/90609331-2c590700-e204-11ea-9924-304dabd906c2.png)

I expected the initials to be white. When I remove the avatarStyle white is applied. 
![image](https://user-images.githubusercontent.com/3699393/90609460-590d1e80-e204-11ea-9d18-59e7fa4fcbd1.png)

Anyone seen this before?

**Comment by flyingcircle** [comment]
I'm not sure I understand what you're trying to do. The `Avatar` docs say that `avatarStyle` is for "Style for avatar image". Are you intending to use `containerStyle`?

**Comment by SanjayRavi0077** [comment]
Try this its working

 <Avatar
            size="xlarge"
            rounded
            title="CR"
            containerStyle={{backgroundColor:'green'}}
            onPress={() => console.log('Works!')}
            activeOpacity={0.7}
          />
![fix 1](https://user-images.githubusercontent.com/58472132/90794843-ecd90a80-e32a-11ea-8866-67524b0ff3b9.PNG)

**Comment by sajeezy** [comment]
Looks like I was looking for ```overlayContainerStyle={{backgroundColor: 'blue'}}```
