### ISSUE TITLE
Button component ripple doesn't respect border radius on Android when (raised/absolute positioned?)

### ISSUE THREAD

**Issue by ewan-m** [react-native-elements/react-native-elements#2511]
Using the button as a rounded floating action button as such given these props - the ripple on android doesn't respect the border radius, and ignores the overflow hidden as well.

Here is an exact implementation to reproduce the error.
```
import { Button } from 'react-native-elements'

const App = () => (
 <Button
    raised
    title={title}
    onPress={()=>{console.log('clicked')}}
    containerStyle={[
      {
        position: 'absolute',
        bottom: 40,
        right: 16,
        overflow: 'hidden',
      },
    ]}
    buttonStyle={{
      borderRadius: 100,
      paddingHorizontal: 24,
      paddingVertical: 8,
      backgroundColor: '#06C',
    }}
  />
)
```

![118073891_348670136521988_7094443451929744742_n](https://user-images.githubusercontent.com/53658878/90650461-d1d79f00-e233-11ea-949c-2570c9a0fdfe.jpg)

| software              | version |
| --------------------- | ------- |
| react-native-elements |     2.2.1    |
| react-native          |    0.63.2     |

**Comment by flyingcircle** [comment]
Did you try applying the same border radius to the `containerStyle`?

**Comment by ewan-m** [comment]
> Did you try applying the same border radius to the `containerStyle`?

Yep tried that too, but no luck 😔 Just using the touch component as TouchableOpacity instead as a quick fix

**Comment by flyingcircle** [comment]
Try just setting the `style` component. That should go directly to the `TouchableComponent`.

**Comment by ewan-m** [comment]
Tried that one too

Seems like the 'raised' style is overriding my overflow hidden, can fix this by changing the order of the stylesheet flattening - don't think it would affect too much else. I can raise a PR for it?
