### ISSUE TITLE
2.0.3 breaks e2e detox tests on  ListItem

### ISSUE THREAD

**Issue by Overtorment** [react-native-elements/react-native-elements#2519]
We have a ListItem with `testID` property that's used by detox e2e tests.
All works fine on 2.0.2 but upgrade to 2.0.3 makes test fail with an error:

```
    androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'at least 75 percent of the view's area is displayed to the user.' doesn't match the selected view.
    Expected: at least 75 percent of the view's area is displayed to the user.
         Got: null
```

Test line that fails:

```
await expect(element(by.id('EncyptedAndPasswordProtected'))).toBeVisible();
```

Heres thee full markup of the component:

```js

        <BlueListItemHooks
          testID="EncyptedAndPasswordProtected"
          hideChevron
          title={loc.settings.encrypt_enc_and_pass}
          Component={TouchableWithoutFeedback}
          switch={{ onValueChange: onEncryptStorageSwitch, value: storageIsEncrypted }}
        />

....

export const BlueListItemHooks = props => {
  const { colors } = useTheme();
  return (
    <ListItem
      testID={props.testID}
      bottomDivider
      containerStyle={{
        backgroundColor: 'transparent',
        borderBottomColor: colors.lightBorder,
        paddingTop: 16,
        paddingBottom: 16,
      }}
      titleStyle={{
        color: props.disabled ? colors.buttonDisabledTextColor : colors.foregroundColor,
        fontSize: 16,
        fontWeight: '500',
      }}
      rightTitleStyle={{ flexWrap: 'wrap', color: colors.alternativeTextColor, fontWeight: '400', fontSize: 14 }}
      subtitleStyle={{ flexWrap: 'wrap', color: colors.alternativeTextColor, fontWeight: '400', fontSize: 14 }}
      subtitleNumberOfLines={1}
      titleNumberOfLines={0}
      Component={TouchableOpacity}
      {...props}
    />
  );
};


```

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     2.0.3+    |
| react-native          |     0.62.2    |

**Comment by Overtorment** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1517

**Comment by Overtorment** [comment]
PS. 2.2.1 also affected

**Comment by flyingcircle** [comment]
You can see what changes were made to `ListItem` in 2.0.3 here: https://github.com/react-native-elements/react-native-elements/compare/v2.0.2...v2.0.3#diff-5f3dd90156d47ed6c5b770d658ad48c3

But I don't see anything that would cause this.

**Comment by flyingcircle** [comment]
As you can see that since there are no obvious changes between 2.0.2 and 2.0.3 that would cause this, it looks like maybe this is deriving from your test code? This ticket needs more information and confirmation that RNE is the actual source. I'm assuming that the list item component is indeed showing up in your application, so the problem is somewhere in your test code then? There are a lot of tools and changes around tools that can throw this off. Something as innocuous as a jest upgrade could cause this to be thrown off. If you can provide more info, I can reopen the ticket.

**Comment by Overtorment** [comment]
Im looking at https://github.com/react-native-elements/react-native-elements/compare/v2.0.2...v2.0.3
and see  several commits mentioning list item and test id

could it be the issue?

**Comment by flyingcircle** [comment]
That was only around the `PadView` which is a child component of `ListItem`, so no changes on `ListItem` itself.
