### ISSUE TITLE
ListItem typescript error with 2.3.0

### ISSUE THREAD

**Issue by ottob** [react-native-elements/react-native-elements#2523]
**Explain what you did (Required)**

Tried to follow the [upgrade guide for 2.3.0](https://react-native-elements.github.io/react-native-elements/blog/2020/08/10/2.3-upgrade-guide/). Im upgrading from 2.1.0.

Changed my old code:
```ts
<ListItem
    title="Edit message"
    leftIcon={{ name: 'edit' }}
    onPress={() => {
      setMenu(false)
      setEditing(true)
    }}
/>
```
to:
```ts
<ListItem
      onPress={() => {
        setMenu(false)
        setEditing(true)
      }}
        >
      <ListItem.Content>
        <Icon name="edit" />
        <ListItem.Title>Edit message</ListItem.Title>
      </ListItem.Content>
</ListItem>
```

**Expected behavior (Required)**

Successful typescript compile.

**Describe the bug (Required)**

Got a typescript error:

```
Property 'Content' does not exist on type 'typeof ListItem'.  TS2339

214 |           <ListItem.Content>
    |                     ^
```
I also get the same error for `ListItem.Title`:
```
Property 'Title' does not exist on type 'typeof ListItem'. TS2339
```

**To Reproduce (Required)**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Screenshots (Required)**

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  2.3.0       |
| react-native          |   0.63.2      |

**Comment by SimenB** [comment]
I just added the stuff I needed myself, but we're applying this patch if it helps anybody get unblocked

```diff
diff --git a/node_modules/react-native-elements/src/index.d.ts b/node_modules/react-native-elements/src/index.d.ts
index 35fe68b..9099352 100644
--- a/node_modules/react-native-elements/src/index.d.ts
+++ b/node_modules/react-native-elements/src/index.d.ts
@@ -1199,7 +1197,10 @@ export interface ListItemProps extends TouchableComponent {
 /**
  * ListItem component
  */
-export class ListItem extends React.Component<ListItemProps, any> {}
+export class ListItem extends React.Component<ListItemProps, any> {
+  static Content: React.ComponentType<{right?: boolean}>;
+  static Title: React.ComponentType<TextProps & {right?: boolean, rightStyle?: StyleProp<ViewStyle>}>;
+}
 
 export interface OverlayProps extends ModalProps {
   /**

```

**Comment by flyingcircle** [comment]
@SimenB I really don't have any good in depth knowledge of Typescript. Can you open a PR with these changes? There are similar changes in `Card` and `Avatar` as well that would need this.

**Comment by codakkk** [comment]
Same problem here. SimenB "patch" seems working properly.

**Comment by M-Jas** [comment]
I know this is closed but I'm still seeing this issue for `ListItem.Title` & `ListItem.Subtitle` for passing raw text. My components work and the text is visible, but the lint warning is gross. Any suggestions? 

```
            <ListItem>
              <ListItem.Content>
                <ListItem.Title >Office</ListItem.Title>
                <ListItem.Subtitle >Address</ListItem.Subtitle>
              </ListItem.Content>
            </ListItem>
```

**Comment by flyingcircle** [comment]
@M-Jas perhaps removing that rule from your lint?

**Comment by M-Jas** [comment]
@flyingcircle Alternate solution: turn the "raw text" into `const`'s. Cheap and Quick

```
const TITLE = 'Office'
const SUBTITLE = 'Address'

         <ListItem>
              <ListItem.Content>
                 // Lint Error: Raw text (Office) cannot be used outside of a <Text> tageslint(react-native/no-raw-text)
                <ListItem.Title >{TITLE}</ListItem.Title>
                <ListItem.Subtitle >{SUBTITLE}</ListItem.Subtitle>
              </ListItem.Content>
            </ListItem>
```

**Comment by flyingcircle** [comment]
@M-Jas glad you found a work around that works for your project. I can't imagine though that RNE is unique in having `Text` Components that use raw text as the children. Seems like it would be a pretty common pattern.
