### ISSUE TITLE
Dropdown or Picker component

### ISSUE THREAD

**Issue by kayazinc** [react-native-elements/react-native-elements#253]
Is there any combobox (aka dropdown, picker) component?
eg. http://shoutem.github.io/docs/ui-toolkit/components/dropdown-menu

**Comment by binoy14** [comment]
Not currently. Will add it to the roadmap. Thanks for reporting

**Comment by dyaacov** [comment]
Any estimation? the lack of this components blocks me from using your great library :(

**Comment by binoy14** [comment]
@dyaacov any suggestions on how it should look? Having some screenshots would be helpful for anyone building this feature

**Comment by dyaacov** [comment]
https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3UE5aelZUMnZUZzA/components_menus_behavior4.png

**Comment by martinezguillaume** [comment]
Good idea ! Need this component ! 👏👏

**Comment by felemedeiros** [comment]
I would add [https://material.io/guidelines/components/menus.html#menus-simple-menus](https://material.io/guidelines/components/menus.html#menus-simple-menus) as a reference as well.

**Comment by Monte9** [comment]
Also adding https://www.npmjs.com/package/react-native-modal-dropdown as a reference. Thanks @xstable

And in the meantime, please check out the Picker component supported by React Native here: https://facebook.github.io/react-native/docs/picker.html

**Comment by camux** [comment]
I would add this
[(https://github.com/toystars/react-native-multiple-select)]
 is very flexible

**Comment by jstansbe** [comment]
Hey, was anything implemented?

**Comment by iRoachie** [comment]
Not currently @jstansbe

**Comment by geminiyellow** [comment]
oh~ hope we can use it tomorrow.

**Comment by martinezguillaume** [comment]
https://github.com/react-native-training/react-native-elements/pull/1216

**Comment by jstansbe** [comment]
@martinezguillaume that looks great!

**Comment by camux** [comment]
When this component is released on beta?

**Comment by martinezguillaume** [comment]
@camux Maybe the pr will be finished during the next month

**Comment by Ryan-ED** [comment]
Any updates on this component? Thanks.

**Comment by escalepion** [comment]
+1 !!!!!!

**Comment by martinezguillaume** [comment]
Sorry guys 😔 I’ve been busy last weeks, I’ll try to do my best to finish this pr in the next days !!

**Comment by iRoachie** [comment]
Same here 🙈

**Comment by ggdegreat** [comment]
still waiting ..

**Comment by datner** [comment]
Same here, hope it's done soon

**Comment by bytenaija** [comment]
Still waiting

**Comment by geminiyellow** [comment]
oh, it looks stoped

**Comment by rdewolff** [comment]
Any reason why this seems to have been dropped?

**Comment by martinezguillaume** [comment]
I’m not really sure of the way to implement this, I’ve made a first shot but I don’t think it’s a good implementation, we need to discuss of that (And I admit that I don’t have much time to work on it 🙁)

**Comment by YikSanChan** [comment]
@martinezguillaume I had an implementation that consists of basically 2 parts and want to do exactly the same as https://react-select.com/creatable#creatable.

![image](https://user-images.githubusercontent.com/17229109/55981606-eec98e80-5c4b-11e9-929d-dee098677dc8.png)

Part 1: A search bar, at the same time, a result bar.
Part 2: An `onLayout` FlatList.

It allows create field if you want, and the create functionality can be easily disable by setting the `readonly` props.

Not sure if this is what the community is looking for. If so, I will try to make a PR. @iRoachie

**Comment by humolabs** [comment]
up!

**Comment by rdewolff** [comment]
Any other language good example to mention? We could use as ref and make a PR.

**Comment by mi-mazouz** [comment]
any updates?

**Comment by tylerolechnowicz** [comment]
Any updates on this? Would really like something like https://github.com/toystars/react-native-multiple-select

**Comment by CodySwannGT** [comment]
+1

**Comment by yuriburk** [comment]
+1

**Comment by jstansbe** [comment]
+1000

**Comment by abduraufsherkulov** [comment]
+1

**Comment by Guusy** [comment]
https://gph.is/28UlIyX

**Comment by Dzhuneyt** [comment]
Still waiting for this :)

**Comment by felemedeiros** [comment]
This is has been solved, Google "Flutter"

**Comment by skaptox** [comment]
+1

**Comment by juniorklawa** [comment]
+1

**Comment by donalbertico** [comment]
+1

**Comment by ecaepsey** [comment]
+1

**Comment by Dzhuneyt** [comment]
Please refrain from using "+1" comments. Instead, use the :thumbsup: emoji on the original comment in order to keep the comments section clear for actual discussion.

**Comment by FeleConvo** [comment]
> Please refrain from using "+1" comments. Instead, use the  emoji on the original comment in order to keep the comments section clear for actual discussion.

+1

**Comment by azwar** [comment]
Is dropdown already implemented?

**Comment by flyingcircle** [comment]
Let me know if someone is willing to take on this task. I'm hoping that someone is willing to put together a PR for this in the next 2-3 months.

**Comment by enigmablue** [comment]
Need this because the material dropdown thats out there isn't maintained and breaks in RN 62.0 :(

https://github.com/n4kz/react-native-material-dropdown

**Comment by dlopez12003** [comment]
I am sad :( I bet on this UI library, this component should have been included from the beginning

**Comment by azwar** [comment]
> https://github.com/react-native-training/react-native-elements/pull/1216

Link was broken

**Comment by azwar** [comment]
I'm waiting this component so long time and now I develop it, if there are something missing just let me know, please. Here is my pull request: https://github.com/react-native-elements/react-native-elements/pull/2670

**Comment by pranshuchittora** [comment]
A basic dropdown is quite easy but considering the compatibility and use cases, I would prefer using https://www.npmjs.com/package/@react-native-community/picker this.

**Comment by flyingcircle** [comment]
@pranshuchittora that library is a good find. It looks well maintained. I don't think we want to be duplicating efforts, so unless there's a compelling reason someone can give for RNE to have another drop down component. I'll close out this ticket.

**Comment by Seanmclem** [comment]
> Sorry guys 😔 I’ve been busy last weeks, I’ll try to do my best to finish this pr in the next days !!

How's your PR?

I'll try this in the mean-time 
https://www.npmjs.com/package/react-native-select-dropdown

**Comment by humzajamil** [comment]
so no picker yet?

**Comment by anietieasuquo** [comment]
Any update on this?

**Comment by BLipscomb** [comment]
Will this component be added?

**Comment by Seanmclem** [comment]
> Will this component be added?

It's odd to think of that this would not be one of the first considered, core components

**Comment by Wabbas0** [comment]
Comon guys, this issue should be picked up. :) 

I will try to check and see what I can do.

**Comment by jdnichollsc** [comment]
Any plans to add this new component? <3
