### ISSUE TITLE
Not clear about the default Icons

### ISSUE THREAD

**Issue by enigmablue** [react-native-elements/react-native-elements#2533]
I'm trying to refer to Header / Button Group. For example 

on the header:
`leftComponent={{ icon: 'menu', color: '#fff' }}`
or on the icon:
`<Icon  name='rowing' />`

I can't for the life of me figure out where the basic/default set of icon names is derived from? 
The documentation for Icon does mention when type Is specified (eg evilicon, or others) 

Can someone share some tips, or perhaps the docs can update with this info?

**Comment by JB1905** [comment]
Are you asking what is the default icon set?
When the `type` prop is not set the component uses icons from [`material`](https://material.io/resources/icons/?style=baseline).

**Comment by flyingcircle** [comment]
@JB1905 The default is indeed listed in the documentation: https://react-native-elements.github.io/react-native-elements/docs/icon#type

**Comment by enigmablue** [comment]
Sorry it was just simply i dont see anywhere in the docs that says when type is not set, the icon uses material

**Comment by flyingcircle** [comment]
https://oblador.github.io/react-native-vector-icons/

that's currently available in `material-comunity`.
