### ISSUE TITLE
Update react-native-vector-icons

### ISSUE THREAD

**Issue by dakkafex** [react-native-elements/react-native-elements#2535]
**Is your feature request related to a problem? Please Describe.**
no

**Describe the solution you'd like**
Update RN-vector-icons to latest version

**Additional context**
Currently it seems this package has a dependency of vector icons 6.6.0, the latest version is 7.0.0

**Comment by flyingcircle** [comment]
Duplicate #2478

Also, it is only a peer dependency. You can already upgrade to the latest version if you'd like
