### ISSUE TITLE
Input component miss replace "x" with "×" (multiplication sign)

### ISSUE THREAD

**Issue by alesmraz** [react-native-elements/react-native-elements#2546]
**Explain what you did (Required)**

Bug report - **iOS problem only**

**Expected behavior (Required)**

"x" is **not** replaced with "×" (multiplication sign)

**Describe the bug (Required)**

As you can see on screenshot, when you try to type something like "1x2" or "332x52" (math operation) then RN elements Input component change this "x" character into  "×" (multiplication sign). At first I thought so it is problem with configuration, but then I tried same configuration on RN TextInput (https://reactnative.dev/docs/textinput). RN TextInput doesn't change "x" into  "×" (multiplication sign).

**To Reproduce (Required)**

Install react native elements by documentation.

Component props:

keyboardType="email-address"
textContentType="none"
autoCapitalize="none"
autoCorrect={false}

**Screenshots (Required)**

first line (gray text 1×2) is RN element Input component (https://react-native-elements.github.io/react-native-elements/docs/input/)
second line (black text 1x2) is RN TextInput (https://reactnative.dev/docs/textinput)

<img width="345" alt="Screenshot 2020-09-02 at 15 18 05" src="https://user-images.githubusercontent.com/16062058/91988860-16813100-ed30-11ea-98cd-450213dccb4a.png">

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     1.2.7    |
| react-native          |    0.61.5     |

_Thanks for help!_

**Comment by flyingcircle** [comment]
@alesmraz any reason why you're still on `1.2.7`? I can look into the issue, but I won't be able to patch the 1.x branch with a fix.

**Comment by alesmraz** [comment]
For anyone who has same issue:

**I found that problem was in font itself**. We use [Inter font](https://fonts.google.com/specimen/Inter) that transform sign. Nothing related with React native elements.

Thanks for great library folks!
