### ISSUE TITLE
prop has been deprecated and will be removed in the next version

### ISSUE THREAD

**Issue by enigmablue** [react-native-elements/react-native-elements#2557]
Hi,

Anyone suddenly seeing this in the console?

 '\'ListItem.chevron\' prop has been deprecated and will be removed in the next version.'
 '\'ListItem.subtitle\' prop has been deprecated and will be removed in the next version.',
'\'ListItem.titleStyle\' prop has been deprecated and will be removed in the next version.',
\'Card.title\' prop has been deprecated and will be removed in the next version.',

I have the latest elements 

react-native-elements": "^2.3.2
react-native": "0.62.0

**Comment by pweisensee** [comment]
Yes, you may want to have a [look at this blog post](https://react-native-elements.github.io/react-native-elements/blog/2020/08/10/2.3-upgrade-guide) and the recent changes to the library. Many props have been deprecated.

**Comment by enigmablue** [comment]
Got it thank you

**Comment by enigmablue** [comment]
I think the Avatar.accessory instructions is not updated into the main docs yet.

But I can see the ListItem new way (via ListItem.content, ListItem.Title, ListItem.SubTitle) looks like its updated in the docs

**Comment by enigmablue** [comment]
Sorry also i dont see any instruction or any way to add a subtitle on the right. Is that removed?

**Comment by RyanTG** [comment]
The upgrade blog post mentions how to add a subtitle on the right https://reactnativeelements.com/blog/2020/08/10/2.3-upgrade-guide/#righttitle-righttitlestyle-righttitleprops-rightsubtitle-rightsubtitlestyle-rightsubtitleprops

`<ListItem.Subtitle right style={titleStyle} {...titleProps}>`

However, this is not working for me. It's placing the subtitle below the title. So I may go with absolute positioning, as you did.
