### ISSUE TITLE
PlaceholderContent in Image doesnt show on android 

### ISSUE THREAD

**Issue by infothien** [react-native-elements/react-native-elements#2562]
Sorry guys, I need your help with the issue about PlaceholderContent in Image doesnt show on android which is really confused :(, I got the very small code like
```

      <Image
        source={{uri: undefined}}
        style={{height:64, width:64}}
        onPress={toggleOverlay}
        PlaceholderContent={<Text>test</Text>}
      />

```
**_ Issue:** Doesnt show placeholderContent for android.

**_ Expected:**  it should show placeholderContent for both android and ios.

<img width="1412" alt="Item-0_and_Item-0_and_Item-0" src="https://user-images.githubusercontent.com/30365498/92515488-ab16f200-f24e-11ea-969b-4fe441be6eaa.png">

**_ Environment:** 
+"react-native-elements": "^2.3.2",
+"react-native": "0.63.2",

Hope to receive you guys feedbacks soon

**Comment by pranshuchittora** [comment]
Hi @infothien I am not encountering the following bug in Android

![Screenshot from 2020-09-13 06-23-22](https://user-images.githubusercontent.com/32242596/93007725-b8531a00-f589-11ea-9a78-e6f066809fb6.png)

```json
    "react-native": "~0.62.2",
    "react-native-elements": "^2.3.2",
    "react-native-vector-icons": "^7.1.0",
```

**Comment by pranshuchittora** [comment]
Hi @infothien just a quick update. 

The cause of the following issue is the `uri: undefined`. Try removing that line and it will work like cheese.

**Comment by infothien** [comment]
thank you for your :D reply, but then it is not the point I think, b/c I want achieve sth like 
```
     <Image
        source={{uri: myUrl? myUrl : undefined}}
        style={{height:64, width:64}}
        onPress={toggleOverlay}
        PlaceholderContent={<Text>test</Text>}
      />
```
so I still need uri: undefined I think @pranshuchittora

**Comment by pranshuchittora** [comment]
Oh, I see. I will try to work on a possible fill. Until then you try the workaround method of pre-paring the prop object and using object spread to inject prop conditionally. Though not the appropriate one.

**Comment by infothien** [comment]
thank you for your help @pranshuchittora, I appreciated

**Comment by flyingcircle** [comment]
I have to undo this change as this has broken loading local image files. Your code should instead be in order to have this work as intended.

`source={ myUrl? {uri: myUrl} : undefined}`
