### ISSUE TITLE
Spread IconProps in Icon. TypeScript

### ISSUE THREAD

**Issue by codakkk** [react-native-elements/react-native-elements#2563]
I have this interface:

```tsx
interface RandomName {
    leftIcon?: IconProps;
    .....attributes
}
```
then, having `item` of type `RandomName`, I do: 
```tsx
.....
<Icon {...item.leftIcon} />
```

an error about types pop-up! (only types error, it's working properly on React Native)
eg: `Type 'true' is not assignable to type 'Readonly<IconProps>' and other errors like that.`

I'm on last version.

**Comment by pranshuchittora** [comment]
Hey @codakkk, 
Can you please provide a code sample on Snack, that would make it easy to reproduce the following error.
:)

**Comment by flyingcircle** [comment]
What are you actually assigning to `item.leftIcon` more info is required here.

**Comment by codakkk** [comment]
Hello guys, sorry for the late answer.
After some hours (today), I just figured out the problem was the leftIcon type in my interface.
Actually I just wrote IconNode instead of IconProps. 
Sorry 🙏
