### ISSUE TITLE
Import error using TypeScript: Cannot find module 'react-native-elements' or its corresponding type declarations.

### ISSUE THREAD

**Issue by tiavina-mika** [react-native-elements/react-native-elements#2564]
`"Cannot find module 'react-native-elements' or its corresponding type declarations."`

I have this typescript / eslint warning when importing any react-native-element.
e.g: import { Text } from 'react-native-elements';

How to fix it?
Thanks

**Comment by pranshuchittora** [comment]
Hey @tiavina-mika can you please provide some more information regarding the dependencies, tsconfig, version of those 
 dependencies.

It would be great if you can share the code which is encountering the following error.

**Comment by tiavina-mika** [comment]
fixed. It was a VS Code / Eslint error. I just close VS Code, I just delete node_modules, npm install, and it work fine

**Comment by pranshuchittora** [comment]
Great 🎉
If you think that the issue has been resolved, then pls close the issue.
