### ISSUE TITLE
Phone number masking for Input

### ISSUE THREAD

**Issue by kickbk** [react-native-elements/react-native-elements#2568]
Formatting a phone number, or any other type of text is not available with any library out there without extraneous setup and configuration.
Do you guys think you may be interested to add masking as an option for the Input component? Perhaps as one of the props? `maskType="phone"`

**Comment by pranshuchittora** [comment]
Hi @kickbk  that's a great idea. But IMO a general-purpose component library is meant to not cover those specific features. The most common and widely used method is to use custom regex filtering, on change.

If this didn't cover what you suggested will achieve then I would love to discuss more on it.
Happy Hacking :)

**Comment by pranshuchittora** [comment]
Apart from that as a library, we want to keep our surface area as min. as possible by shipping only general-purpose features which wide range of audience needs.

**Comment by kickbk** [comment]
I get what you mean, and you're probably right to keep the library lean. Still, masking an TextInput is a very common task which would be great to have taken care of by the library out of the box. Much in the style that [Wix MaskedInput](https://wix.github.io/react-native-ui-lib/docs/MaskedInput/) does it.
I would hate my suggestions to introduce complexity to the library. It's just a suggestion that, if you feel could be added easily and has merit, then great, if not, well... then great 👍

**Comment by flyingcircle** [comment]
@kickbk there is a prop that allows you to replace the `InputComponent` with a separate one. And there is a community component that does what you ask here: https://github.com/react-native-community/react-native-text-input-mask

I think you should be able to insert that component right into the RNE one and get the functionality that you want. And then everyone is happy :) Separation of concerns and the functionality is already available through libraries.
