### ISSUE TITLE
Bug(ThemeProvider): Toggling useDark prop doesn't updates the theme.

### ISSUE THREAD

**Issue by pranshuchittora** [react-native-elements/react-native-elements#2571]
**Description**
While working on a feature of enabling dark mode by toggling a `Switch` which in turn changes the prop of the `ThemeProvider`. After successfully changing the `prop` the theme didn't get updated.

**Expected Behaviour**
The theme must update on the change of prop.

**Comment by SaveYourTime** [comment]
@pranshuchittora I'm facing this issue as well, and it seems to be fixed in 3.0.0.
What's is the current workaround to fix this in the 2.x version?

**Comment by pranshuchittora** [comment]
> @pranshuchittora I'm facing this issue as well, and it seems to be fixed in 3.0.0.
> What's is the current workaround to fix this in the 2.x version?

Hi @SaveYourTime IMO there's no workaround for this in v2.x.
We are ready to ship v3, unfortunately, there's a blocking issue from the `expo`'s end. Once that gets merged we will release v3 :)
