### ISSUE TITLE
Missing styles 'imageCardTitle' and 'overlayContainer' in Card in 'next' branch

### ISSUE THREAD

**Issue by hondahmd** [react-native-elements/react-native-elements#2579]
**Explain what you did**

I am reading your source code and find that styles called 'imageCardTitle' and 'overlayContainer' are missing in Card.js [here](https://github.com/react-native-elements/react-native-elements/blob/next/src/card/Card.js#L118) and [here](https://github.com/react-native-elements/react-native-elements/blob/next/src/card/Card.js#L134), it seems that they were accidently moved into [CardTitle.js](https://github.com/react-native-elements/react-native-elements/blob/next/src/card/CardTitle.js) when refactoring, it happened 23 days ago and I am wondering if this would be a bug.

**Expected behavior**

The styles definition should exist or the references should be removed.

**Describe the bug**

Code missing.

**To Reproduce**

Check the code in [Card](https://github.com/react-native-elements/react-native-elements/blob/next/src/card/Card.js) and search for the styles.

**Screenshot**

None.

**Your Environment:**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    next     |
| react-native          |     any    |

**Comment by flyingcircle** [comment]
Sorry, they were accidentally removed. That method is also deprecated, so I would suggest changing your `Card` components to the new style: https://react-native-elements.github.io/react-native-elements/blog#card
