### ISSUE TITLE
🎉 Hacktoberfest 2020 🎉

### ISSUE THREAD

**Issue by pranshuchittora** [react-native-elements/react-native-elements#2588]
Hello :wave: 
And here comes another season on `Hacktoberfest`. We are as excited as you are and hope we all collaborate and build some awesome things this season. We are almost there to complete our [`v3`](https://github.com/react-native-elements/react-native-elements/milestone/16) milestone and we will try our best to release it as soon as possible. 

The thread is open to new ideas and discussions about design systems / `react-native-elements`.

Feel free to discuss :loudspeaker: 
Happy Hacking :man_technologist: :woman_technologist:

**Comment by Karthik-B-06** [comment]
A great library for react-native. How about having a Switch Component? 
I have created a separate library though, you can have a look at it [here ](https://github.com/timelessco/react-native-reanimated-switch).

I hope it can be added to react-native-elements.

**Comment by pranshuchittora** [comment]
Hi @Karthik-B-06 thanks for such awesome words. 
Great component btw, but we are open to add new generic components to the lib, but the current priority is to make the design consistent and improve performance. But, its not limited to those changes only :)

**Comment by pranshuchittora** [comment]
Kudos to all the new and old collaborators. It was an honour collaborating will all of you
Thank you all for such a great response. :confetti_ball:
