### ISSUE TITLE
Button(Props): Make the icon prop more intuitive and dynamic

### ISSUE THREAD

**Issue by pranshuchittora** [react-native-elements/react-native-elements#2591]
**Description**
The `icon` position props come with a huge surface area. The idea is to decrease the APIs surface area by introducing more functionalities.

**Proposed Change**
Instead of `iconRight` and default left position of the `icon`, we can introduce a new prop called `iconPosition`. 
And the usage looks might look something like this :arrow_down: 
```js
iconPosition: = "left" | "right" | "top" | "bottom"
```

The following functionality can be achieved by using the `flex` container for the text and the icon and changing it's the direction to `row | row-reverse | column | column-reverse` to achieve all the possible combinations.

**Comment by flyingcircle** [comment]
I wonder if it might be simpler to or possible to have button follow the same general pattern as `Card` and `ListItem` have now. Something like:

```js
<Button>
  <Button.Icon />
  <Button.Title />
</Button>
```

This leaves greater flexibility and customization for users without having to sacrifice ease of use. And it also helps prevent prop bloat.

**Comment by pranshuchittora** [comment]
Looks great, this can unlock new possibilities of a discrete set of children. May be an image btn

**Comment by laxmy** [comment]
Hi @pranshuchittora , Can I take this up?

**Comment by HariAcidReign** [comment]
Hi @flyingcircle , this looks like something I can work on..Is it available and can I be assigned to it?

**Comment by HariAcidReign** [comment]
Working on it!

**Comment by vanya-24** [comment]
Hi @flyingcircle, 
Can I also work on this issue as I found this issue to get started with, Or can you guide me with to get started? 
Thank you😊

**Comment by flyingcircle** [comment]
@vanya-24 go for it. I usually try to take the best from multiple solutions. someone can help you get started in the slack channel.

**Comment by vanya-24** [comment]
Thanks, working on it

**Comment by hetanthakkar1** [comment]
> I wonder if it might be simpler to or possible to have button follow the same general pattern as `Card` and `ListItem` have now. Something like:
> 
> ```js
> <Button>
>   <Button.Icon />
>   <Button.Title />
> </Button>
> ```
> 
> **And it also helps prevent prop bloat.**

We are just replacing iconRight with iconPosition so do u still think it will create prop bloat!? And I think the main advantage of using this iconPosition method as opposed to child method is that the users which are currently using iconRight will have to modify their code a lot as compared to just replacing the iconRight with iconPosition.

**Comment by khushal87** [comment]
Can we halt it till GSoC ends? Displaying the props could be a difficult task for the inherited props as we don't have sections and currently, all of the children components are maintained manually by giving a link reference. Once the process is clear, we can look at this. @pranshuchittora @flyingcircle @arpitBhalla

**Comment by pranshuchittora** [comment]
> Can we halt it till GSoC ends? Displaying the props could be a difficult task for the inherited props as we don't have sections and currently, all of the children components are maintained manually by giving a link reference. Once the process is clear, we can look at this. @pranshuchittora @flyingcircle @arpitBhalla @dhruvdutt And, if we are planning to add this, please can we do it on priority? So that I can pick the changes and look at the code so that I can proceed with the document generation for this component.

You can start with other components first. Then we can take a look at this because delaying this might not be a good idea 🤔
