### ISSUE TITLE
Avatar: No placeholder when source is an empty object {}

### ISSUE THREAD

**Issue by pranshuchittora** [react-native-elements/react-native-elements#2592]
**Explain what you did (Required)**
<Avatar
  rounded
  source={{  }}
/>

**Expected behavior (Required)**
Placeholder should render

**Describe the bug (Required)**
Avatar source validation issue.

**Comment by pranshuchittora** [comment]
Possible Cause https://github.com/react-native-elements/react-native-elements/blob/c69d761a822d046382957f0a9ab715847551c34c/src/avatar/Avatar.js#L81

**Comment by tarunyadav1** [comment]
You can assign this issue to me.

Thank You

**Comment by pranshuchittora** [comment]
@tarunyadav1 I have assigned this issue to you.
You can refer to this [guide](https://react-native-elements.github.io/react-native-elements/docs/contributing/), hope it helps.
Looking forward to it :)

**Comment by tarunyadav1** [comment]
@pranshuchittora  thanks

**Comment by pranshuchittora** [comment]
@tarunyadav1 we will be releasing the v3 soon, it would be great if we can fix this before the release.
Thanks :)

**Comment by tarunyadav1** [comment]
@pranshuchittora I am unable to fix the issue. I am new to open source, can you guide me a little bit.

**Comment by pranshuchittora** [comment]
No worries :) 
I have already given the code pointer above which points to the exact line which is causing the issue. Kindly read the Contributing guide https://reactnativeelements.com/docs/contributing

**Comment by tarunyadav1** [comment]
@pranshuchittora  Please review my pull request #2625  

Thank You

**Comment by jehielmartinez** [comment]
Can I work on this one?

**Comment by flyingcircle** [comment]
Fixed. Thanks @jehielmartinez
