### ISSUE TITLE
Some Icons don't get displayed

### ISSUE THREAD

**Issue by dipamsen** [react-native-elements/react-native-elements#2595]
**Explain what you did (Required)**
Icon of `arrow-left-right-bold` from `material-community-icons`

**Expected behavior (Required)**
Icon doesn't get displayed

**Describe the bug (Required)**

Some icons of MaterialCommunityIcons not getting displayed while using `react-native-elements` `Icon` component

**To Reproduce (Required)**

```jsx
import React from 'react'
import { Icon } from 'react-native-elements`

// ...

// for example
<Icon name="set-left-right" color="#fff" type="material-community-icons" />
```

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements | `^2.3.2` |
| react-native          |  `38.0.2`  |

**Comment by JB1905** [comment]
Hi!
It works for me when I replace `material-community-icons` with `material-community`. `material-community-icons` is not supported icon type name.

**Comment by pranshuchittora** [comment]
@JB1905 thanks for the help :)

@dipamsen you can refer the following in the docs [here](https://react-native-elements.github.io/react-native-elements/docs/icon#available-icon-sets).
