### ISSUE TITLE
There is no alternative to ListItem.rightElement

### ISSUE THREAD

**Issue by rarenatoe** [react-native-elements/react-native-elements#2597]
**Explain what you did (Required)**

I wanted and tried to switch to the new way of writing components, so that I could get rid of those **ugly deprecation warnings**.

**Expected behavior (Required)**

I expected to find an alternative to`rightElement` for `ListItem`.

**Describe the bug (Required)**

There was no alternative to `rightElement` for `ListItem`, and when I add it the old way, the element shows up on the left, not the right.

**To Reproduce (Required)**

Basic Example:
```
const Markers = props => {
  return (
    <View style={{ flexDirection: 'row', alignSelf: 'flex-start' }}>
      {props.isFavorite ? (
        <Image
          style={{ marginRight: 8 }}
          source={require('../../../../images/iconFavorite.png')}
        />
      ) : null}
      {props.isCritical ? (
        <Image source={require('../../../../images/iconCritical.png')} /> // This is the image that shows up in the screenshot
      ) : null}
    </View>
  )
}

<ListItem
              rightElement={() => (
                <Markers isFavorite={false} isCritical={true} />
              )}
              >
              <ListItem.Content style={StyleSheet.listItemDetails}>
                <ListItem.Title>Title</ListItem.Title>
                <ListItem.Subtitle>
                  Some text
                </ListItem.Subtitle>
              </ListItem.Content>
            </ListItem>
```

**Screenshots (Required)**

![WhatsApp Image 2020-09-22 at 11 22 26](https://user-images.githubusercontent.com/44821537/93909930-fbb63280-fcc5-11ea-8392-fb7cb753460b.jpeg)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     2.3.2    |
| react-native          |     0.62.2    |

**Comment by flyingcircle** [comment]
Try this:

```js
<ListItem>
    <ListItem.Content style={StyleSheet.listItemDetails}>
      <ListItem.Title>Title</ListItem.Title>
      <ListItem.Subtitle>
          Some text
      </ListItem.Subtitle>
    </ListItem.Content>
    <Markers isFavorite={false} isCritical={true} />
</ListItem>
```

**Comment by rarenatoe** [comment]
Thanks @flyingcircle, I tried this before but it doesn't seem to align it to the top anymore, but rather it centers it.
There might be something else to tweek in the style that I haven't tried before....

**Comment by flyingcircle** [comment]
I don't know what to tell you, this was a basic refactor, so nothing should have changed. The part of the code that renders the `rightElement` wasn't changed at all.

**Comment by rarenatoe** [comment]
Sorry, yeah, I just tried it again, for whatever reason it works. Thank you.
