### ISSUE TITLE
Docs Website Broken

### ISSUE THREAD

**Issue by jspizziri** [react-native-elements/react-native-elements#2600]
Doc's website is `404`ing for all assets.

**Explain what you did (Required)**

Visited https://reactnativeelements.com/

**Expected behavior (Required)**

Website works.

**Screenshots (Required)**

![Screen Shot 2020-09-22 at 1 20 38 PM](https://user-images.githubusercontent.com/1452066/93921947-e72e6600-fcd6-11ea-86f6-d0a04ffa27e9.png)
![Screen Shot 2020-09-22 at 1 18 29 PM](https://user-images.githubusercontent.com/1452066/93921965-ebf31a00-fcd6-11ea-8d3a-d91b5b2ce0de.png)

**Your Environment (Required):**

macOS with Firefox

**Comment by Monte9** [comment]
Good catch! This is WIP currently as part of https://github.com/react-native-elements/react-native-elements/issues/1857

We are aware of it and working to fix it ASAP

**Comment by jspizziri** [comment]
@Monte9 , thanks for the update!

**Comment by Monte9** [comment]
Website should be live here: https://reactnativeelements.com/

**Comment by jspizziri** [comment]
@Monte9 , docs site is down again.

**Comment by jspizziri** [comment]
back up.

**Comment by pranshuchittora** [comment]
Going to Versions > Next  might work  Unfortunately the search is not
working too.
