### ISSUE TITLE
Roadmap for reactnativeelements.com

### ISSUE THREAD

**Issue by pranshuchittora** [react-native-elements/react-native-elements#2602]
Just a thought.
Instead of hosting docs directly to the https://reactnativeelements.com/ we can serve a landing page and then the user can either go to docs, OC, etc.

**Comment by flyingcircle** [comment]
I'm not sure I understand. The homepage for the website is already a landing page and links to any additional tool (eg. a future Playground for instance) can be added to the menu on top or the homepage itself.

**Comment by Monte9** [comment]
Can we add more images to the landing page please? It looks too boring right now.. as it's mostly just text. 😄

**Comment by flyingcircle** [comment]
I think we have a good looking index page now. @pranshuchittora added a link to the playground and an image was added to the front page as well.

**Comment by pranshuchittora** [comment]
Great, all looks great. Here are some insights of the Playground.

![Screenshot from 2020-12-15 06-57-49](https://user-images.githubusercontent.com/32242596/102156204-20740d80-3ea3-11eb-9bd0-1a42eda3090c.png)

P.S. I have added Google Analytics to get insights for the improvement (Latency etc). @flyingcircle we can remove that now if you agree

**Comment by flyingcircle** [comment]
I'm fine either way on the analytics. I don't think it's harming anything to keep them there, but if you'd rather remove it that's fine too.

**Comment by pranshuchittora** [comment]
Great. I am also with keeping GA to get basic insights
