### ISSUE TITLE
Tooltip position is wrong (always at top of the screen) on web

### ISSUE THREAD

**Issue by jameschetwood** [react-native-elements/react-native-elements#2603]
I'm using the Tooltip component with React Native Web.

I expect the Tooltip to behave the same way as it does on native. However the overlay position is always at the top of the screen, not near its "trigger" as it should be. 

I'm using version 2.3.2.

https://snack.expo.io/@jamesweblondon/thankful-truffle

```
import * as React from 'react';
import {  View, StyleSheet } from 'react-native';
import { Tooltip, Text } from 'react-native-elements';
import Modal from 'modal-react-native-web';


export default function App() {
  return (
    <View style={styles.container}>
      <Tooltip 
        popover={<Text>Info here</Text>} 
        ModalComponent={Modal} 
        overlayColor={'rgba(0, 0, 0, 0)'}
        withPointer={false}
      >
        <Text>Press me</Text>
      </Tooltip>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
    padding: 40,
  },
});
```

![Screenshot 2020-09-24 at 12 11 19](https://user-images.githubusercontent.com/6142418/94137880-1374ee80-fe5f-11ea-88a8-04de1525c1be.JPG)

**Comment by flyingcircle** [comment]
`Modal` is  not currently supported by `react-native-web`: https://github.com/necolas/react-native-web/issues/1020

**Comment by pranshuchittora** [comment]
@jameschetwood you can always track the component compatibility over here -> https://github.com/necolas/react-native-web#components

**Comment by Elijen** [comment]
Modal seems to be implemented in `react-native-web` now, but the `Tooltip` component is still not rendering properly. Any idea on workarounds?
