### ISSUE TITLE
Docs: Arrange props alphabetically 

### ISSUE THREAD

**Issue by pranshuchittora** [react-native-elements/react-native-elements#2604]
The documentation of all components lists the `props` as well as their usage. It would be great if we arrange the `props` list alphabetically to make it easier to find the required props.

Just like the [expo docs](https://docs.expo.io/versions/v39.0.0/react-native/pressable/) and others.

**Proposed Fix**
The docs are written using `markdown` and can be found [here](https://github.com/react-native-elements/react-native-elements/tree/next/website/docs).

You can make multiple PRs (one PR for one component ) as it makes it easy to review. Considering the surface area of this issue.

**As multiple peoples will be working on this issue, make sure to comment down the name of the component you will work on.**

#### Done
- [x] Avatar
- [x] Badge
- [x] BottomSheet
- [x] Button
- [ ] ButtonGroup
- [x] Card
- [x] Checkbox
- [x] Header 
- [x] Icon
- [x] Image
- [ ] Input
- [x] ListItem
- [x] Overlay
- [x] Pricing 
- [x] Searchbar
- [x] Slider 
- [ ] Text
- [x] Tile 
- [x] Tooltip
- [x] Modal
- [x] Rating

**Comment by a-developer-and-her-mac** [comment]
So this would be just rearranging the props list in each markdown file to be alphabetical?

**Comment by pranshuchittora** [comment]
Yeah @a-developer-and-her-mac the idea to make prop search more fast and intuitive for the mobile users as `Find` in a page takes a lot of clicks. 
Thanks for taking this issue. Assigning it to you :)

**Comment by flyingcircle** [comment]
Avatar was done in: #2605

I'm also fine if someone wants to do more than one component per PR if that is easier.

**Comment by a-developer-and-her-mac** [comment]
Alright, I'll try to do at least two per PR. If it's alright though, I might wait for a week so the rest can count towards Hacktoberfest.

**Comment by pranshuchittora** [comment]
Removing all assignees as this is a big issue so multiple people can work on this simultaneously.

**Comment by mukuakhilesh** [comment]
As there can be multiple assignees, can I take up and edit few of the component's markdown files ?

**Comment by pranshuchittora** [comment]
@mukuakhilesh go ahead :)
Pls, comment here about the components you will work upon, in order to avoid duplicate PRs.

**Comment by mukuakhilesh** [comment]
I can work upon [checkbox.md](https://github.com/react-native-elements/react-native-elements/tree/next/website/docs/checkbox.md) for now, if no one has started to work on it.

**Comment by pranshuchittora** [comment]
Great, adding this to the issue description :)

**Comment by ujjwal404** [comment]
@pranshuchittora , I made a pull request in which I arranged props of image.md file in order. Can you please check.

**Comment by a-developer-and-her-mac** [comment]
I'll start working on badge.md and button.md.

**Comment by mukuakhilesh** [comment]
@pranshuchittora I have made a pull request for checkbox.md. Can you check it once.

**Comment by mukuakhilesh** [comment]
I will like to take up [header.md](https://github.com/react-native-elements/react-native-elements/blob/next/website/docs/header.md) and [icon.md](https://github.com/react-native-elements/react-native-elements/blob/next/website/docs/icon.md), if no one has started working on it.

**Comment by pranshuchittora** [comment]
> I will like to take up [header.md](https://github.com/react-native-elements/react-native-elements/blob/next/website/docs/header.md) and [icon.md](https://github.com/react-native-elements/react-native-elements/blob/next/website/docs/icon.md), if no one has started working on it.

Sure, Pls go ahead :)

**Comment by JB1905** [comment]
@pranshuchittora add Tooltip to Progress as done

**Comment by mbeuil** [comment]
Hey ! if nobody work on those can I take tile.md  and slider.md ?

**Comment by pranshuchittora** [comment]
> Hey ! if nobody work on those can I take tile.md and slider.md ?

Sure

**Comment by mbeuil** [comment]
slider and tile were done in : #2619 .
(Don't know how to link a PR to an issue sorry -_-)

**Comment by ujjwal404** [comment]
I've made a pull request and sorted component in overlay.md file. #2622 .

**Comment by pranshuchittora** [comment]
> I will start work on pricing.md and rating.md, if no one has started on these.

Great. Go Ahead :)

**Comment by sanskritip** [comment]
I would like to work on input.md  and labels.md if no one has started working on it!

**Comment by sanskritip** [comment]
I would like to work on searchbar.md and listitem.md if no one has started working on it!

**Comment by pranshuchittora** [comment]
> I would like to work on searchbar.md and listitem.md if no one has started working on it!

Ya sure, pls go ahead :)

**Comment by sanskritip** [comment]
> 
> 
> > I would like to work on searchbar.md and listitem.md if no one has started working on it!
> 
> Ya sure, pls go ahead :)

Made a PR - Docs: arrange props alphabetically in searchbar.md, listitem.md #2629 . Kindly review it :)

**Comment by dummy26** [comment]
Hi! Just made a PR - Arranged props alphabetically in pricing.md #2631.

**Comment by dummy26** [comment]
Is someone working on rating.md. If no, then I can take it up.

**Comment by pranshuchittora** [comment]
Hi @dummy26 thanks, I have merged your PRs.

**Comment by chas-e** [comment]
I will work on bottomsheet if that still needs alphabetizing.

**Comment by chas-e** [comment]
I will alphabetize input.md's props.

**Comment by JiriJAdam** [comment]
Hello! Can I work on this?

**Comment by PropeReferio** [comment]
Any other docs here that need help? I'd like to work on this.
