### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by lorensr** [react-native-elements/react-native-elements#2609]
After clicking `Try the demo app`

![image](https://user-images.githubusercontent.com/251288/94345759-4c939700-fff6-11ea-940a-eba36036bbc0.png)

I'm taken to:

https://expo.io/@flyingcircle/react-native-elements-app

When I scan the QR code, the expo app opens with:

![IMG_3631](https://user-images.githubusercontent.com/251288/94345743-46051f80-fff6-11ea-853e-79ecb18c72e4.PNG)

(Opening other expo apps on my phone works fine)

**Comment by flyingcircle** [comment]
Fixed now. Not sure why it disappeared.
