### ISSUE TITLE
Question about use Input component to read barcode with external device.

### ISSUE THREAD

**Issue by jochercoles** [react-native-elements/react-native-elements#2617]
Hi colleagues, I'm using the input component where I need read a barcode with an Unitech Ring Scanner. When I do a read, this code input in ladder way, but If I use the internal Scanner of mobile, the code input OK.

I paste a capture return by the app.

[Mon Sep 28 2020 12:13:47.160]  LOG      142 A
[Mon Sep 28 2020 12:13:47.280]  LOG      142 AS
[Mon Sep 28 2020 12:13:47.418]  LOG      142 ASI
[Mon Sep 28 2020 12:13:47.553]  LOG      142 ASIG
[Mon Sep 28 2020 12:13:47.692]  LOG      142 ASIGN
[Mon Sep 28 2020 12:13:47.829]  LOG      142 ASIGNA
[Mon Sep 28 2020 12:13:47.989]  LOG      142 ASIGNA0
[Mon Sep 28 2020 12:13:48.900]  LOG      142 ASIGNA01
[Mon Sep 28 2020 12:13:48.255]  LOG      142 ASIGNA013
[Mon Sep 28 2020 12:13:48.385]  LOG      142 ASIGNA0132
[Mon Sep 28 2020 12:13:48.541]  LOG      142 ASIGNA01320
[Mon Sep 28 2020 12:13:48.665]  LOG      142 ASIGNA013202

I need that, when I read the barcode, return ASIGNA013202, in only one pass.

I hope be clear.

Regards.

Javier

**Comment by pranshuchittora** [comment]
Hi @jochercoles that's unfortunate that you are facing this issue.
But I am not able to reproduce the following issue in my system. I would be great if you can provide a demo reproducing the following issue on https://snack.expo.io/

**Comment by flyingcircle** [comment]
@jochercoles if you can provide more info, I'll reopen the ticket.
