### ISSUE TITLE
How to customize and add variants to Text or other components?

### ISSUE THREAD

**Issue by eddyhdzg** [react-native-elements/react-native-elements#2623]
How can I add variants other than h1, h2, h3, h4?

What I want to achieve is something like

Theme
```
const theme: Theme = {
  Text: {
    p1: true,
    p1Style: {
      color: "blue",
    },
  },
};
```
Usage
```
<Text p1>Paragraph 1</Text>
```

The customization page didn't work for me.
https://reactnativeelements.com/docs/customization#typescript-definitions-extending-the-default-theme

**Comment by flyingcircle** [comment]
You would create your own `Text` component. You can look at the code for `Text` to see how the `h` props were created and do something similar for your own component.
