### ISSUE TITLE
Expo 39 PadView Function components cannot be given refs

### ISSUE THREAD

**Issue by kickbk** [react-native-elements/react-native-elements#2628]
Hi guys,
I just upgraded to Expo 39 and I'm getting some errors. I wouldn't be surprised if it was not the last one I'll encounter since Expo 39 is very new.

The full warning I'm getting is:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `PadView`.
    in LinearGradient (at ListItem.js:371)
    in PadView (at ListItem.js:220)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at TouchableScale.js:60)
    in TouchableWithoutFeedback (at TouchableScale.js:54)
    in TouchableScale (at ListItem.js:214)
    in ListItem (at withTheme.js:44)
    in Themed.ListItem (at AccountScreen.tsx:57)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Carousel.tsx:1158)
    in RCTView (at View.js:34)
    in View (at Carousel.tsx:647)
    in bound _getCellRendererComponent (at VirtualizedList.js:2127)
    in CellRenderer (at VirtualizedList.js:900)
    in RCTScrollContentView (at ScrollView.js:1124)
    in RCTScrollView (at ScrollView.js:1260)
    in ScrollView (at ScrollView.js:1286)
    in ScrollView (at VirtualizedList.js:1329)
    in VirtualizedList (at FlatList.js:624)
    in FlatList (at AnimatedFlatList.js:24)
    in ForwardRef (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Carousel.tsx:1337)
    in Carousel (at AccountScreen.tsx:124)
    in RCTView (at View.js:34)
    in View (at Themed.tsx:100)
    in View (at AccountScreen.tsx:122)
    in RCTView (at View.js:34)
    in View (at Themed.tsx:100)
    in View (at AccountScreen.tsx:95)
    in AccountScreen (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:150)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:221)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:220)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:563)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:545)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:539)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:535)
    in RCTView (at View.js:34)
    in View (at Card.tsx:529)
    in Card (at CardContainer.tsx:189)
    in CardContainer (at CardStack.tsx:558)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:69)
    in MaybeScreen (at CardStack.tsx:551)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:48)
    in MaybeScreenContainer (at CardStack.tsx:461)
    in CardStack (at StackView.tsx:458)
    in KeyboardManager (at StackView.tsx:456)
    in SafeAreaProviderCompat (at StackView.tsx:453)
    in RCTView (at View.js:34)
    in View (at StackView.tsx:452)
    in StackView (at createStackNavigator.tsx:85)
    in StackNavigator (at BottomTabNavigator.tsx:189)
    in AccountNavigator (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:150)
    in RCTView (at View.js:34)
    in View (at BottomTabView.tsx:41)
    in SceneContent (at BottomTabView.tsx:117)
    in RCTView (at View.js:34)
    in View (at ResourceSavingScene.tsx:43)
    in RCTView (at View.js:34)
    in View (at ResourceSavingScene.tsx:26)
    in ResourceSavingScene (at BottomTabView.tsx:112)
    in RCTView (at View.js:34)
    in View (at src/index.native.js:134)
    in ScreenContainer (at BottomTabView.tsx:96)
    in RCTView (at View.js:34)
    in View (at BottomTabView.tsx:95)
    in SafeAreaProviderCompat (at BottomTabView.tsx:94)
    in BottomTabView (at createBottomTabNavigator.tsx:41)
    in BottomTabNavigator (at BottomTabNavigator.tsx:44)
    in BottomTabNavigator (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:150)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:221)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:220)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:563)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:545)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:539)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:535)
    in RCTView (at View.js:34)
    in View (at Card.tsx:529)
    in Card (at CardContainer.tsx:189)
    in CardContainer (at CardStack.tsx:558)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:69)
    in MaybeScreen (at CardStack.tsx:551)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:48)
    in MaybeScreenContainer (at CardStack.tsx:461)
    in CardStack (at StackView.tsx:458)
    in KeyboardManager (at StackView.tsx:456)
    in SafeAreaProviderCompat (at StackView.tsx:453)
    in RCTView (at View.js:34)
    in View (at StackView.tsx:452)
    in StackView (at createStackNavigator.tsx:85)
    in StackNavigator (at navigation/index.tsx:73)
    in RootNavigator (at navigation/index.tsx:62)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:390)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at navigation/index.tsx:36)
    in Navigation (at App.tsx:22)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:74)
    in SafeAreaProvider (at App.tsx:21)
    in ApolloProvider (at App.tsx:20)
    in App (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in DevAppContainer (at AppContainer.js:121)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
- node_modules/react-native/Libraries/LogBox/LogBox.js:173:8 in registerError
- node_modules/react-native/Libraries/LogBox/LogBox.js:59:8 in errorImpl
- node_modules/react-native/Libraries/LogBox/LogBox.js:33:4 in console.error
- node_modules/expo/build/environment/react-native-logs.fx.js:27:4 in error
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:106:4 in printWarning
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:75:16 in error
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:13002:13 in validateFunctionComponentInDev
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:12966:36 in mountIndeterminateComponent
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:19181:22 in beginWork$1
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18085:22 in performUnitOfWork
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18013:38 in workLoopSync
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:17977:18 in renderRootSync
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:17674:33 in performSyncWorkOnRoot
* [native code]:null in performSyncWorkOnRoot
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5321:31 in runWithPriority$argument_1
- node_modules/scheduler/cjs/scheduler.development.js:653:23 in unstable_runWithPriority
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5316:21 in flushSyncCallbackQueueImpl
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5304:28 in flushSyncCallbackQueue
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:17718:28 in batchedUpdates$1
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2492:29 in batchedUpdates
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2638:16 in _receiveRootNodeIDEvent
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2767:27 in receiveTouches
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:416:4 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:109:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:108:4 in callFunctionReturnFlushedQueue
* [native code]:null in callFunctionReturnFlushedQueue
```
The issue is possibly here: https://github.com/react-native-elements/react-native-elements/blob/ed6e90d55f18f371ce606019c28f937f816ea3a8/src/list/ListItem.js#L358 where you use a `createRef`, which now expects `forwardRef`?

**Comment by pranshuchittora** [comment]
Hi, @kickbk that unfortunate that you are facing such error :disappointed: 
I am not able to investigate the following error properly, can you provide a simple demo reproducing the following error on the https://snack.expo.io/

By the way, are you trying to reference the following ListItem?

**Comment by kickbk** [comment]
@pranshuchittora thanks for replying. So I did some more debugging.

I am getting the error I pasted above when I add `linearGradientProps`. When I remove it, no error. I am also using the same code as in your example:
```
linearGradientProps={{
    colors: ['#FF9800', '#F44336'],
    start: { x: 1, y: 0 },
    end: { x: 0.2, y: 0 },
  }}
```

**Comment by pranshuchittora** [comment]
Hi @kickbk no worries. I have to take a deep dive to investigate the following issue.
Happy Hacking :)

**Comment by pranshuchittora** [comment]
Able to reproduce. IMO forwarding the ref will resolve the issue, just an early insight.
![Screenshot from 2020-10-07 03-16-36](https://user-images.githubusercontent.com/32242596/95263524-8876f980-084b-11eb-8aec-2d25bd5ba517.png)

![Screenshot from 2020-10-07 03-15-45](https://user-images.githubusercontent.com/32242596/95263532-8c0a8080-084b-11eb-832e-469a140874ea.png)

**Comment by kickbk** [comment]
@pranshuchittora by "forwarding the ref" you mean changing the library code that I mentioned or something I can do on my end?

**Comment by pranshuchittora** [comment]
The library is not forwarding the ref, which is the cause of the error.
That's from the libs end. I will try to fix this ASAP.
Once fixed you can use the `next` branch as your dependency's version.

**Comment by kickbk** [comment]
Thank you @pranshuchittora

**Comment by pranshuchittora** [comment]
Thanks for reporting :+1:

**Comment by pranshuchittora** [comment]
Hi @kickbk 
A workaround solution for this (Expo only)

Remove ` ViewComponent={LinearGradient}` this line.
Can you confirm whether the error is still occurring or not?

**Comment by kickbk** [comment]
Where do you find this line? I don't have it in my code anywhere

**Comment by pranshuchittora** [comment]
```jsx
import { ListItem, Avatar } from 'react-native-elements';
import TouchableScale from 'react-native-touchable-scale'; // https://github.com/kohver/react-native-touchable-scale
import LinearGradient from 'react-native-linear-gradient'; // Only if no expo

<ListItem
  Component={TouchableScale}
  friction={90} //
  tension={100} // These props are passed to the parent component (here TouchableScale)
  activeScale={0.95} //
  linearGradientProps={{
    colors: ['#FF9800', '#F44336'],
    start: { x: 1, y: 0 },
    end: { x: 0.2, y: 0 },
  }}
  ViewComponent={LinearGradient} // Only if no expo
>
  <Avatar rounded source={{ uri: avatar_url }} />
  <ListItem.Content>
    <ListItem.Title style={{ color: 'white', fontWeight: 'bold' }}>
      Chris Jackson
    </ListItem.Title>
    <ListItem.Subtitle style={{ color: 'white' }}>
      Vice Chairman
    </ListItem.Subtitle>
  </ListItem.Content>
  <ListItem.Chevron color="white" />
</ListItem>;
```

From the docs

**Comment by kickbk** [comment]
Oh sorry, I got confused. I am using expo so I already have removed that line long ago. Still got the error.

**Comment by pranshuchittora** [comment]
Can you share exactly what props you are passing? It would be great if you can share that exact component here.

**Comment by kickbk** [comment]
```
({ item }: { item: any }) => (
  <>
    <ListItem
        style={{ marginLeft: 15 }}
        containerStyle={{ padding: 0, borderRadius: 10 }}
        Component={TouchableScale}
        friction={90}
        tension={100}
        activeScale={0.95}
        linearGradientProps={item.gradient}>
```

Which, by the way, gives me typescript errors as well (unrelated to this original issue and was giving errors before the upgrade to expo 39. Just wanted to mention it)

**Comment by DumiduPabasara** [comment]
> Hi guys,
> I just upgraded to Expo 39 and I'm getting some errors. I wouldn't be surprised if it was not the last one I'll encounter since Expo 39 is very new.
> 
> The full warning I'm getting is:
> 
> ```
> Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
> 
> Check the render method of `PadView`.
>     in LinearGradient (at ListItem.js:371)
>     in PadView (at ListItem.js:220)
>     in RCTView (at View.js:34)
>     in View (at createAnimatedComponent.js:165)
>     in AnimatedComponent (at createAnimatedComponent.js:215)
>     in ForwardRef(AnimatedComponentWrapper) (at TouchableScale.js:60)
>     in TouchableWithoutFeedback (at TouchableScale.js:54)
>     in TouchableScale (at ListItem.js:214)
>     in ListItem (at withTheme.js:44)
>     in Themed.ListItem (at AccountScreen.tsx:57)
>     in RCTView (at View.js:34)
>     in View (at createAnimatedComponent.js:165)
>     in AnimatedComponent (at createAnimatedComponent.js:215)
>     in ForwardRef(AnimatedComponentWrapper) (at Carousel.tsx:1158)
>     in RCTView (at View.js:34)
>     in View (at Carousel.tsx:647)
>     in bound _getCellRendererComponent (at VirtualizedList.js:2127)
>     in CellRenderer (at VirtualizedList.js:900)
>     in RCTScrollContentView (at ScrollView.js:1124)
>     in RCTScrollView (at ScrollView.js:1260)
>     in ScrollView (at ScrollView.js:1286)
>     in ScrollView (at VirtualizedList.js:1329)
>     in VirtualizedList (at FlatList.js:624)
>     in FlatList (at AnimatedFlatList.js:24)
>     in ForwardRef (at createAnimatedComponent.js:165)
>     in AnimatedComponent (at createAnimatedComponent.js:215)
>     in ForwardRef(AnimatedComponentWrapper) (at Carousel.tsx:1337)
>     in Carousel (at AccountScreen.tsx:124)
>     in RCTView (at View.js:34)
>     in View (at Themed.tsx:100)
>     in View (at AccountScreen.tsx:122)
>     in RCTView (at View.js:34)
>     in View (at Themed.tsx:100)
>     in View (at AccountScreen.tsx:95)
>     in AccountScreen (at SceneView.tsx:122)
>     in StaticContainer
>     in StaticContainer (at SceneView.tsx:115)
>     in EnsureSingleNavigator (at SceneView.tsx:114)
>     in SceneView (at useDescriptors.tsx:150)
>     in RCTView (at View.js:34)
>     in View (at CardContainer.tsx:221)
>     in RCTView (at View.js:34)
>     in View (at CardContainer.tsx:220)
>     in RCTView (at View.js:34)
>     in View (at CardSheet.tsx:33)
>     in ForwardRef(CardSheet) (at Card.tsx:563)
>     in RCTView (at View.js:34)
>     in View (at createAnimatedComponent.js:165)
>     in AnimatedComponent (at createAnimatedComponent.js:215)
>     in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:545)
>     in PanGestureHandler (at GestureHandlerNative.tsx:13)
>     in PanGestureHandler (at Card.tsx:539)
>     in RCTView (at View.js:34)
>     in View (at createAnimatedComponent.js:165)
>     in AnimatedComponent (at createAnimatedComponent.js:215)
>     in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:535)
>     in RCTView (at View.js:34)
>     in View (at Card.tsx:529)
>     in Card (at CardContainer.tsx:189)
>     in CardContainer (at CardStack.tsx:558)
>     in RCTView (at View.js:34)
>     in View (at Screens.tsx:69)
>     in MaybeScreen (at CardStack.tsx:551)
>     in RCTView (at View.js:34)
>     in View (at Screens.tsx:48)
>     in MaybeScreenContainer (at CardStack.tsx:461)
>     in CardStack (at StackView.tsx:458)
>     in KeyboardManager (at StackView.tsx:456)
>     in SafeAreaProviderCompat (at StackView.tsx:453)
>     in RCTView (at View.js:34)
>     in View (at StackView.tsx:452)
>     in StackView (at createStackNavigator.tsx:85)
>     in StackNavigator (at BottomTabNavigator.tsx:189)
>     in AccountNavigator (at SceneView.tsx:122)
>     in StaticContainer
>     in StaticContainer (at SceneView.tsx:115)
>     in EnsureSingleNavigator (at SceneView.tsx:114)
>     in SceneView (at useDescriptors.tsx:150)
>     in RCTView (at View.js:34)
>     in View (at BottomTabView.tsx:41)
>     in SceneContent (at BottomTabView.tsx:117)
>     in RCTView (at View.js:34)
>     in View (at ResourceSavingScene.tsx:43)
>     in RCTView (at View.js:34)
>     in View (at ResourceSavingScene.tsx:26)
>     in ResourceSavingScene (at BottomTabView.tsx:112)
>     in RCTView (at View.js:34)
>     in View (at src/index.native.js:134)
>     in ScreenContainer (at BottomTabView.tsx:96)
>     in RCTView (at View.js:34)
>     in View (at BottomTabView.tsx:95)
>     in SafeAreaProviderCompat (at BottomTabView.tsx:94)
>     in BottomTabView (at createBottomTabNavigator.tsx:41)
>     in BottomTabNavigator (at BottomTabNavigator.tsx:44)
>     in BottomTabNavigator (at SceneView.tsx:122)
>     in StaticContainer
>     in StaticContainer (at SceneView.tsx:115)
>     in EnsureSingleNavigator (at SceneView.tsx:114)
>     in SceneView (at useDescriptors.tsx:150)
>     in RCTView (at View.js:34)
>     in View (at CardContainer.tsx:221)
>     in RCTView (at View.js:34)
>     in View (at CardContainer.tsx:220)
>     in RCTView (at View.js:34)
>     in View (at CardSheet.tsx:33)
>     in ForwardRef(CardSheet) (at Card.tsx:563)
>     in RCTView (at View.js:34)
>     in View (at createAnimatedComponent.js:165)
>     in AnimatedComponent (at createAnimatedComponent.js:215)
>     in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:545)
>     in PanGestureHandler (at GestureHandlerNative.tsx:13)
>     in PanGestureHandler (at Card.tsx:539)
>     in RCTView (at View.js:34)
>     in View (at createAnimatedComponent.js:165)
>     in AnimatedComponent (at createAnimatedComponent.js:215)
>     in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:535)
>     in RCTView (at View.js:34)
>     in View (at Card.tsx:529)
>     in Card (at CardContainer.tsx:189)
>     in CardContainer (at CardStack.tsx:558)
>     in RCTView (at View.js:34)
>     in View (at Screens.tsx:69)
>     in MaybeScreen (at CardStack.tsx:551)
>     in RCTView (at View.js:34)
>     in View (at Screens.tsx:48)
>     in MaybeScreenContainer (at CardStack.tsx:461)
>     in CardStack (at StackView.tsx:458)
>     in KeyboardManager (at StackView.tsx:456)
>     in SafeAreaProviderCompat (at StackView.tsx:453)
>     in RCTView (at View.js:34)
>     in View (at StackView.tsx:452)
>     in StackView (at createStackNavigator.tsx:85)
>     in StackNavigator (at navigation/index.tsx:73)
>     in RootNavigator (at navigation/index.tsx:62)
>     in EnsureSingleNavigator (at BaseNavigationContainer.tsx:390)
>     in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
>     in ThemeProvider (at NavigationContainer.tsx:90)
>     in ForwardRef(NavigationContainer) (at navigation/index.tsx:36)
>     in Navigation (at App.tsx:22)
>     in RNCSafeAreaProvider (at SafeAreaContext.tsx:74)
>     in SafeAreaProvider (at App.tsx:21)
>     in ApolloProvider (at App.tsx:20)
>     in App (created by ExpoRoot)
>     in ExpoRoot (at renderApplication.js:45)
>     in RCTView (at View.js:34)
>     in View (at AppContainer.js:106)
>     in DevAppContainer (at AppContainer.js:121)
>     in RCTView (at View.js:34)
>     in View (at AppContainer.js:132)
>     in AppContainer (at renderApplication.js:39)
> - node_modules/react-native/Libraries/LogBox/LogBox.js:173:8 in registerError
> - node_modules/react-native/Libraries/LogBox/LogBox.js:59:8 in errorImpl
> - node_modules/react-native/Libraries/LogBox/LogBox.js:33:4 in console.error
> - node_modules/expo/build/environment/react-native-logs.fx.js:27:4 in error
> - node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:106:4 in printWarning
> - node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:75:16 in error
> - node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:13002:13 in validateFunctionComponentInDev
> - node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:12966:36 in mountIndeterminateComponent
> - node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:19181:22 in beginWork$1
> - node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18085:22 in performUnitOfWork
> - node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18013:38 in workLoopSync
> - node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:17977:18 in renderRootSync
> - node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:17674:33 in performSyncWorkOnRoot
> * [native code]:null in performSyncWorkOnRoot
> - node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5321:31 in runWithPriority$argument_1
> - node_modules/scheduler/cjs/scheduler.development.js:653:23 in unstable_runWithPriority
> - node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5316:21 in flushSyncCallbackQueueImpl
> - node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5304:28 in flushSyncCallbackQueue
> - node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:17718:28 in batchedUpdates$1
> - node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2492:29 in batchedUpdates
> - node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2638:16 in _receiveRootNodeIDEvent
> - node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2767:27 in receiveTouches
> - node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:416:4 in __callFunction
> - node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:109:6 in __guard$argument_0
> - node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:10 in __guard
> - node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:108:4 in callFunctionReturnFlushedQueue
> * [native code]:null in callFunctionReturnFlushedQueue
> ```
> 
> The issue is possibly here:
> 
> https://github.com/react-native-elements/react-native-elements/blob/ed6e90d55f18f371ce606019c28f937f816ea3a8/src/list/ListItem.js#L358
> 
> where you use a `createRef`, which now expects `forwardRef`?

I am getting the same error. Hope it will solve soon

**Comment by flyingcircle** [comment]
Working with expo 40 and RNE 3.0.1 I do not see this error. @pranshuchittora and @kickbk is this error resolved?

**Comment by DumiduPabasara** [comment]
Hi @flyingcircle, I previously worked with expo 39 and RNE 3.0.0-alpha.1. Then I upgrade to expo 40 and RNE 3.0.1 and the error seems to be resolved. But gives following warning, looks like manageble. Thank you.
![image](https://user-images.githubusercontent.com/63274475/102717814-c217b680-430a-11eb-806e-03dc55096911.png)

**Comment by flyingcircle** [comment]
Awesome! Thanks for the update. Yep trying to do some work to resolve that. It's going to require a lot of work in `Button` to make work.

**Comment by RajatGang07** [comment]
@pranshuchittora I am not using expo, still getting the same error.

**Comment by bdotsamir** [comment]
Hey crew, I am actually still getting this warning. Tried forwarding the ref on my end to no avail.

Using [Expo's DateTimePicker](https://docs.expo.dev/versions/latest/sdk/date-time-picker/) as the `InputComponent`. Tried looking at their end to see if there was an issue, and [this comment](https://github.com/react-native-datetimepicker/datetimepicker/issues/372) seemed to provide some insight, but there was no further discussion after the `useImperativeHandle` suggestion so I'm not sure if this worked.

FWIW: their DateTimePicker doesn't even accept a `ref` prop, so forwarding it just kind of does nothing. And it doesn't clean up the warning. Womp womp
