### ISSUE TITLE
Error with ListItem and react-native-web

### ISSUE THREAD

**Issue by hankstenberg** [react-native-elements/react-native-elements#2633]
After the upgrade of RNE from 2.2.something to 2.3.2 I'm getting the following error in when trying to render a ListItem in the browser (using expo and react-native-web):

`TypeError: react_native_web_dist_exports_Platform__WEBPACK_IMPORTED_MODULE_10__.default.select(...) is undefined`

Looking at the source code I see that the following call in ListItem:

```
const renderIcon = (content, theme) =>
  renderNode(Icon, content, {
    color: Platform.select(theme.colors.platform).grey,
    size: 24,
  });
```

So it looks like `Platform` is not resolved in the native-web context. It does work on my Android though.

Here's a Snack that reproduces the problem: https://snack.expo.io/rGHEaYbtn

**Comment by pranshuchittora** [comment]
Hi can you share a demo reproducing the following error on snack? That would help a lot in fast-tracking the issue resolution :)

**Comment by hankstenberg** [comment]
Hi pranshuchittora, thanks for the quick reply.

Here you go: https://snack.expo.io/rGHEaYbtn

**Comment by pranshuchittora** [comment]
The snack demo is working perfectly.

![Screenshot from 2020-10-12 02-59-57](https://user-images.githubusercontent.com/32242596/95690686-0dd92000-0c37-11eb-83a4-2b0f789aceb0.png)


If you are talking about this error 

![Screenshot from 2020-10-12 03-00-07](https://user-images.githubusercontent.com/32242596/95690701-20535980-0c37-11eb-92ce-20d4fab3ca52.png)


Then this got fixed and will be released in `v3`, which is about to release very soon.

**Comment by hankstenberg** [comment]
Looks like it is a browser question.

On firefox I get:

> h.Platform.select(...) is undefined

On Chrome I indeed get:

> Cannot read property 'grey' of undefined

Looking forward to the release, then.

**Comment by baileytincher** [comment]
Is there a short-term workaround or can a v3 alpha version be uploaded to npm? @pranshuchittora

**Comment by pranshuchittora** [comment]
> Is there a short-term workaround or can a v3 alpha version be uploaded to npm? @pranshuchittora

Hi @baileytincher we have released `v3` in alpha, I hope this will help.
Happy Hacking :)

**Comment by baileytincher** [comment]
@pranshuchittora hmm I updated to `3.0.0-alpha.1`, but I'm seeing the same error listed above for web. It seems that the default theme only recognizes `ios` and `android` as platforms and not `web`. 

Here's a very rough example of a workaround I found to manually set the theme :/

```typescript
import React, { useEffect, useState } from 'react';

import { Theme, withTheme, Text, ListItem, UpdateTheme } from 'react-native-elements';

const ListItemExample: React.FC<{ theme: Theme; updateTheme: UpdateTheme }> = ({
  theme,
  updateTheme,
}) => {
  const [ListTest, setListTest] = useState(<></>);

  useEffect(() => {
    updateTheme({
      colors: {
        platform: {
          web: {
            grey: 'gray',
          },
        },
      },
    });
  }, [updateTheme]);

  useEffect(() => {
    if (theme.colors?.platform?.web != null) {
      setListTest(
        <ListItem>
          <Text>Works!</Text>
        </ListItem>
      );
    }
  }, [theme.colors?.platform?.web]);

  return <>{ ListTest }</>;
};

export default withTheme(ListItemExample);
```
