### ISSUE TITLE
MaximumValue on Slider creates mismatch between thumb position and actual value / track position

### ISSUE THREAD

**Issue by nkhalsa** [react-native-elements/react-native-elements#2634]
**Explain what you did (Required)**
I added the maximumValue field to a slider to make it 0-100, incrementing by 1:
```
export const ZeroToHundredByOneSlider = (props) => {
  return (
    <Slider
      trackStyle={{ height: 3 , backgroundColor: global.colors.dark }}
      minimumTrackTintColor={global.colors.grey}
      maximumTrackTintColor={global.colors.light}
      thumbStyle={{ height: 19, width: 19, backgroundColor: global.colors.light, borderWidth:1, borderColor:global.colors.light}}
      thumbProps={props.customIcon ? {children: props.customIcon} : null}
      step={1}
      maximumValue={100}
      minimumValue={0}
      {...props}
      />
    )
```

**Expected behavior (Required)**
It did work as expected, making such a slider.

**Describe the bug (Required)**
However, only track position showed the correct value. The thumb did not.

**To Reproduce (Required)**
This code should be sufficient to reproduce it
**Screenshots (Required)**

**Your Environment (Required):**
![simulator_screenshot_F6AD9DB5-10EC-42F6-8D67-8BB4010726F8](https://user-images.githubusercontent.com/36167440/95417324-a5faa080-08e9-11eb-9ee9-27bbf1a10e4b.png)

| software              | version |
| --------------------- | ------- |
| react-native-elements | 2.3.2        |
| react-native          | 0.62.2        |

**Comment by nkhalsa** [comment]
Update: this was "fixed" by putting the Slider's value-related props before the style-related props. It doesn't necessary fix the problem, but it provides a solution in case anyone else was having it.

**Comment by nkhalsa** [comment]
Update: It appears the SliderThumb component starts with start == 0, then on the next update the value changes but it doesn't re-render

**Comment by pranshuchittora** [comment]
Hi @nkhalsa I have tested the following bug and it's working perfectly in the latest codebase and the following changes will be released soon in `v3`.

It would be great if it is possible for you to test the `v3` beta for the following fix.

You can use it by changing the version in `package.json` like this

https://github.com/react-native-elements/react-native-elements-app/blob/35c23a00e4b51d35537e35c6c89cfa0557072207/package.json#L37

**Comment by nkhalsa** [comment]
Thank you @pranshuchittora it works
