### ISSUE TITLE
how to close a full screen overlay?

### ISSUE THREAD

**Issue by dominick-designs** [react-native-elements/react-native-elements#2636]
**Is your feature request related to a problem? Please Describe.**

See the [Overlay element](https://reactnativeelements.com/docs/overlay/#fullscreen) with a ```fullScreen``` prop which takes a boolean. I don't see an option to EXIT the ```fullScreen```.

**Describe the solution you'd like**

My issue is that I don't see a way to close the full screen overlay modal.

**Describe alternatives you've considered**

There are other react native options that involve more components. But I was thinking that this should be an option if ```fullScreen``` is an option. If I can enter ```fullScreen``` then I should be able to exit ```fullScreen```.

**Additional context**

apologies, but I don't feel comfortable on slack. I never liked it. I have about 10 accounts and I just can't continue to add slack email accounts each time I want to join a new slack channel. So, I thought I would post my request here.

**Comment by pranshuchittora** [comment]
Have you tried changing [isvisible](https://reactnativeelements.com/docs/overlay/#isvisible) prop to false from a CTA in the fullscreen overlay?

**Comment by dominick-designs** [comment]
Thanks for the reply! I was thinking to do that but I can’t think of a way to trigger this when it is open. The original state is invisible and it becomes visible when the button is tapped and it takes up full screen; but I cannot think of a way to trigger it to make isVisible === false

**Comment by dominick-designs** [comment]
The problem is that I don't see how to use [```onBackdropPress```](https://reactnativeelements.com/docs/overlay/#onbackdroppress) if there is no backdrop visible?

**Comment by pranshuchittora** [comment]
> The problem is that I don't see how to use [`onBackdropPress`](https://reactnativeelements.com/docs/overlay/#onbackdroppress) if there is no backdrop visible?

This will work only if the `fullScreen` is false. So the recommended way is to change the visibility prop via a state change

**Comment by dominick-designs** [comment]
I ended up using ```TouchableOpacity``` with the code that is in the expo demo to show an overlay: 

```
// this is from expo demo code
const [visible, setVisible] = useState(false);

          const toggleOverlay = () => {
            setVisible(!visible);
          };

return (

// overlay begins here....

<TouchableOpacity onPress={toggleOverlay}>

<Badge
                      status="error"
                      value="Exit"
                      containerStyle={{ marginTop: "10%", marginBottom: "5%" }}
                      textStyle={{ marginTop: 50, marginBottom: 50, color: "black" }}
                    />
</TouchableOpacity >

// text element here....

// overlay ends here....


)

```

**Comment by pranshuchittora** [comment]
Great :+1: 
Happy Hacking :)
