### ISSUE TITLE
Demo app not working on Expo

### ISSUE THREAD

**Issue by rambunctiousmonk** [react-native-elements/react-native-elements#2649]
**Explain what you did (Required)**

Attempted to run the demo app on Expo by following this link from the readme: https://expo.io/@monte9/react-native-elements-app

**Expected behavior (Required)**

Expo should have opened the sample app with options to run in browser/on a device

**Describe the bug (Required)**

Error message from Expo:
This project uses Expo SDK v34.0.0. If you want to open this project, the author will need to update the project's SDK version.

**Screenshots (Required)**
![image](https://user-images.githubusercontent.com/60016201/97100905-88bb2580-1690-11eb-86ed-1875f7880048.png)

**Comment by pranshuchittora** [comment]
Hi @rambunctiousmonk that's quite unfortunate. But I am not sure about the support of the demo app.
We are working on some cool component playground. It's in a very early stage but would love to have your valuable feedback on the same. 

https://react-native-elements-playground.netlify.app/
