### ISSUE TITLE
Ability to add additional icons to the search bar, such as a filter & sort.

### ISSUE THREAD

**Issue by javida1492** [react-native-elements/react-native-elements#2654]
I wanted to implement a search bar with an integrated filter button, such as the Airbnb search bar, but currently the prop set provided does not allow for this.

Alternatives I've considered are to create my own custom search bar.

See below image for Airbnb example that I am trying to replicate.
![image](https://user-images.githubusercontent.com/44504197/97461119-d0051880-1913-11eb-9c0b-c5e078db9614.png)

**Comment by pranshuchittora** [comment]
Hi @javida1492 thanks for reaching out. This looks interesting, but as a UI library, we are bound to implementing general UI components with high customization so we cover a wide range of use cases. I am not sure about going ahead with the implementation of the following component.

**Comment by pranshuchittora** [comment]
Closing this now. But feel free to open this any time for any discussion.

Happy Hacking :)
