### ISSUE TITLE
various style props using incorrect PropsType validation

### ISSUE THREAD

**Issue by carlost** [react-native-elements/react-native-elements#2659]
**Explain what you did (Required)**

Used a compiled react-native StyleSheet object to style a react-native-elements Button component.

**Expected behavior (Required)**

The Button component uses the stylesheet to control how it was displayed ... and it doesn't complain about it.

**Describe the bug (Required)**

The style prop was used by the component.  However, it logged a prop-type violation message:

> checkPropTypes.js:19 Warning: Failed prop type: Invalid prop `titleStyle` supplied to `Button`.

This occurs with just about any style prop i looked at in react-native-elements.

These error messages make me itchy!

**To Reproduce (Required)**

https://snack.expo.io/Zh6z6hZCT

This is a slight head scratcher ... I do not see the error message in snack.  I assume it is because the runtime checks performed by prop-types only occur in the dev env.

**Screenshots (Required)**

NA

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   v2.0.3      |
| react-native          |    v0.63.3     |
| react-native-web | v0.13.18|

I suspect that I am missing something here.  The type def consistently used in RNE for style props is:

```javascript
PropTypes.oneOfType([PropTypes.object, PropTypes.array])
```

It is my understanding that `StyleSheets.create` returns an object that has numbers as values.  RN basically memoizes these stylesheets for performance purposes. So if your `StyleSheet` looks like this:

```javascript
const styles = StyleSheet.create({
  button: {
    backgroundColor: 'grey'
  },
  buttonText: {
    color: 'red',
    fontSize: 18
  }
});
```

a call to `styles.button` will return a `number` and not an `array` or `object`.  You can wrap these numbers in arrays to bypass the prop-types checks or call `StyleSheet.flatten` to pass in the actual styles object instead of the number ID. However, those solutions are either confusing or a performance sinkhole.

If i am correct ... i am not entirely sure what the appropriate solution is.  

I punish myself with Flow, so I am not familiar with prop-types best practices.  RN has moved the various `StyleSheets` props into files named `react-native/Libraries/DeprecatedPropTypes/DeprecatedXXStylePropTypes.js`... so i am not sure if using those files is appropriate.

I suspect that widening the validation rule for the style props to:

```javascript
PropTypes.oneOfType([PropTypes.object, PropTypes.array, PropTypes.number])
```

isn't very useful because any ole number won't do ... it needs to be a StyleSheet ID.

**Comment by EricVanDerDijs** [comment]
I'm also having this Warning messages on the Input component (containerStyle, labelStyle, inputStyle).

this are my deps:
```
    "react-native-elements": "^3.0.0-alpha.1",
    "react-native-web": "^0.14.7",
```

Also, I'm using typescript and the types seem to be the correct ones

**Comment by flyingcircle** [comment]
I tried this out in our example app but wasn't able to make any warnings appear with `titleStyle` using the exact same code that you mention with `StyleSheet.create`. If you can supply a larger context for your code, maybe there is some other coding error that you are making. But the problem as presented is not reproducible.
