### ISSUE TITLE
Please add props custom style OverLay Component

### ISSUE THREAD

**Issue by thaiphamvan** [react-native-elements/react-native-elements#2661]
Please check example my fork
https://github.com/thaiphamvan/react-native-elements/commit/4521dcbb6096059534ddd3ea56a42c1da56cc040

**Comment by thaiphamvan** [comment]
Example: Add a style when the Keyboard is open or close.

**Comment by pranshuchittora** [comment]
@thaiphamvan thanks for reaching out.
That looks interesting, but as a component library, our aim is to build and ship general-purpose components to cover a wide range of audience.

The mentioned functionality is quite a niche and might not be required by most of the users. For the time being, I am closing this issue, feel free to reopen it any time.

Happy Hacking :)
