### ISSUE TITLE
Error while updating property 'nativeBackgroundAndroid' of a view managed by: RCTView

### ISSUE THREAD

**Issue by iqbalfaisal** [react-native-elements/react-native-elements#2662]
Android API: 19
![Screenshot_1604314895](https://user-images.githubusercontent.com/46706064/97861012-e7ce0980-1d24-11eb-99d7-84300e578b32.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   ^2.0.0      |
| react-native          |   0.63.2      |

**Comment by pranshuchittora** [comment]
Hi @iqbalfaisal pls provide more details. It would be great if you can provide a demo on Snack reproducing the following error.

**Comment by lekeCoder** [comment]
I am having the same issue now with Android Api 19, react 16.13, react-native: 0.63.2. When I press the ListItem, the onPress action is to navigate to the next page and this error crashes the app. help somebody

**Comment by flyingcircle** [comment]
Stale ticket: No response from author.

**Comment by romonsalve** [comment]
I had the same issue with API 19 

Following this issue https://github.com/facebook/react-native/issues/9870#issuecomment-262855033 i understand that TouchableNativeFeedback is not supported on API < 21

React elements Button use TouchableNativeFeedback for Android, so i use Touchable Opacity when API is < 21 and works 

Like this 

`<ElementButton
    ...
    TouchableComponent={(
      Platform.OS === 'android' && Platform.Version >= 21
        ? TouchableNativeFeedback
        : TouchableOpacity
    )}
  />`

**Comment by lekeCoder** [comment]
For me, the `ListItem` component is crashing in Android 19 for the same reason
