### ISSUE TITLE
Avatar and Card components do not show static images

### ISSUE THREAD

**Issue by pakjiddat** [react-native-elements/react-native-elements#2663]
**I tried to use a static image with the Avatar and Card components**

**I expected the images to show correctly**

**Instead of the static image, a gray placeholder image shows**

**Try the following steps:**

1. Try the following code:
`<Avatar source={require('./images/image-name.png')} />`

2. The code works in snack.expo.io, but does not work in Android emulator

3. See following screenshot of the Android emulator. It shows a small gray square placeholder image instead of the image in the images folder

![Screenshot_1604319669](https://user-images.githubusercontent.com/20923812/97867663-0f769f00-1d30-11eb-8036-875a127ad0e7.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    3.0.0-alpha.1     |
| react-native          |   0.63.2      |

**Comment by leidto** [comment]
Temporary workaround:
`<Avatar placeholderStyle={{ backgroundColor: 'transparent' }} source={require('./images/image-name.png')} />`

**Comment by pakjiddat** [comment]
Adding transparent background color to the placeholder worked. The Avatar image is now showing correctly. Thanks.

Adding the following code to the Card.Image element fixes the problem with showing card image:

`placeholderStyle={{ backgroundColor: 'transparent' }}`

**Comment by infothien** [comment]
@pakjiddat , I got the pr for fixing you dont mind give it a check !

**Comment by pranshuchittora** [comment]
> **I tried to use a static image with the Avatar and Card components**
> 
> **I expected the images to show correctly**
> 
> **Instead of the static image, a gray placeholder image shows**
> 
> **Try the following steps:**
> 
> 1. Try the following code:
>    `<Avatar source={require('./images/image-name.png')} />`
> 2. The code works in snack.expo.io, but does not work in Android emulator
> 3. See following screenshot of the Android emulator. It shows a small gray square placeholder image instead of the image in the images folder
> 
> ![Screenshot_1604319669](https://user-images.githubusercontent.com/20923812/97867663-0f769f00-1d30-11eb-8036-875a127ad0e7.png)
> 
> **Your Environment (Required):**
> 
> software	version
> react-native-elements	3.0.0-alpha.1
> react-native	0.63.2

Pls refer the docs. The source mentioned here doesn't have the key named `uri`.
https://github.com/react-native-elements/react-native-elements-app/blob/35c23a00e4b51d35537e35c6c89cfa0557072207/src/views/avatars.js#L82

**Comment by UGhari** [comment]
Same issue exists with Icon

**Comment by UGhari** [comment]
@pranshuchittora 

I disagree with the closing of this issue, previously in old versions you could use a local asset with require to show an image within an avatar suddenly in 

react-native-elements | 3.0.0-alpha.1
react-native | 0.63.2

you can't. It breaks a lot of code in my current app and I am unable to upgrade to the latest versions of RN Elements because of this. The Icon component has also broken displaying nothing

`<Icon type={'material-community'} name={'pencil-plus-outline} size={30} color={color} />`

Again this all worked in previous versions. I would really appreciate it if you reconsider
