### ISSUE TITLE
Header does not have shadow style

### ISSUE THREAD

**Issue by crabbynguyen** [react-native-elements/react-native-elements#2664]
**Is your feature request related to a problem? Please Describe.**
I want to add shadow to my Header component. I have tried to add

`shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 3
    },
    shadowRadius: 5,
    shadowOpacity: 1.0`

to `containerStyle` but it seems did not work

**Describe the solution you'd like**
By default Header should have shadow

**Describe alternatives you've considered**
Or can style shadow like describe before

**Additional context**

**Comment by flyingcircle** [comment]
Worked when I tried it:

![simulator_screenshot_CCE49F7F-FB07-41B2-AFA7-D2C8AECA38D5](https://user-images.githubusercontent.com/5239875/102667149-91365680-413d-11eb-8ace-cae571512862.png)
