### ISSUE TITLE
Any chance to support GIF with the <Image> ?

### ISSUE THREAD

**Issue by enigmablue** [react-native-elements/react-native-elements#2665]
Currently it dosen't seem i can play GIF in the Image component
Any chance it can be supported?

**Comment by pranshuchittora** [comment]
Hi @enigmablue the Image component works as same as the official react-native image component. So pls refer the steps to render gif in react-native and that will work here as well.


Closing this issue, for now. Feel free to reopen this again

Happy Hacking :)
