### ISSUE TITLE
Allow ReactNode to be passed as prop to Button title

### ISSUE THREAD

**Issue by zachgibb** [react-native-elements/react-native-elements#2666]
I would love to have more flexibility in customizing the Button contents. There are two use cases that I've run into which are currently not possible in the current implementation.
 - adding a subtitle
    <img width="381" alt="Screen Shot 2020-11-03 at 3 11 46 PM" src="https://user-images.githubusercontent.com/8093376/98036211-a3f00880-1de7-11eb-8be1-5f1013bd96f7.png">
- text with different styling for a section of it
    > Not John Doe? **Sign out**

If the title was rendered like the [icon](https://github.com/zachgibb/react-native-elements/blob/next/src/buttons/Button.js#L144-L152) with `renderNode`, this type of customization would be possible.

```
{!loading &&
  !!title &&
  renderNode(Text, title, {
    style: titleStyle,
    ...titleProps
  })}
```

**Comment by flyingcircle** [comment]
Good catch. I'm wondering if though that it might be better to moving these to being subComponents of `Button`. The code gets a bit messy when passing whole components as props, whereas it's much more straightforward when using sub-components. But just adding `renderNode` will be much less disruptive.
