### ISSUE TITLE
Make SearchBar iOS version more compact

### ISSUE THREAD

**Issue by nimabrownlee** [react-native-elements/react-native-elements#2668]
**Is your feature request related to a problem? Please Describe.**
Right now when using the iOS version of the SearchBar, the input has too much vertical padding. And I've tried every style prop to decrease it but it doesnt work.

**Describe the solution you'd like**
Be able to make SearchBar more compact just like the true iOS style.

**Additional context**
Here is what it looks now: https://i.imgur.com/zUgY2z0.png and how it should should: https://i.imgur.com/qOJYX5y.png (look at the docs version)

**Comment by pranshuchittora** [comment]
Thanks @nimabrownlee 
Thanks for pointing that out. We always try to make components more configurable. I really liked the idea.

I am thinking of a `prop` margin which can take 3 values `small`, `medium`, `large`.
Would love to discuss and refine the idea :)

**Comment by M-Jas** [comment]
@pranshuchittora

Playing devil's advocate, but what if someone wants an `x-medium` version? 

Adding another prop to this party isn't addressing the real issue with this component, flexibility. Maybe we should step backwards slightly by removing some of the specific styles/props, giving us a more minimal flexible component?

**Comment by flyingcircle** [comment]
I was able to change the look of the `SearchBar` using the following:

```
containerStyle={{height: 50}}  \\ height of outer container
inputContainerStyle={{height: 20}}  \\ height of the input container
```
