### ISSUE TITLE
Tooltip positioning inconsistent in ScrollViews on Android

### ISSUE THREAD

**Issue by brooksbecton** [react-native-elements/react-native-elements#2669]
**Explain what you did (Required)**
Put a tooltip  around text inside a scrollview.
Ran code in Android simulator. 
Scroll around in view
Tap on the tooltip
Didn't see tooltip on screen or saw it incorrectly positioned
Press same tooltip again
See it work correctly

**Expected behavior (Required)**
Have the tooltip be correctly positioned consistently on Android even if scrolling has occurred. 

**Describe the bug (Required)**

It seems like when you when you have a tooltip in a scroll view it gets the position of the tooltip before the screen is scrolled. 

**To Reproduce (Required)**

[https://snack.expo.io/@broabect/react-native-elements-tooltip-scroll-issue](https://snack.expo.io/@broabect/react-native-elements-tooltip-scroll-issue)
```bash


# Steps
1. Run snack on Android
2. Press a highlighted word
3. See tooltip work
4. Switch to ScrollView
5. Press a highlighted word
6. See tooltip work
7. Scroll down the screen some
8. Press a highlighted word
8. See that tooltip has shifted down with the scroll. 
```

**Screenshots (Required)**
Working in a normal view
![ViewWorking](https://user-images.githubusercontent.com/9373516/98288143-65d41f80-1f74-11eb-8a65-8caa74fdd00e.png)
Broken after having scrolling down the page
![BrokenScrollView](https://user-images.githubusercontent.com/9373516/98288138-64a2f280-1f74-11eb-8b07-a771c34a5d40.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   3.0.0-alpha.1      |
| react-native          |      React Native 0.63   |

**Comment by pranshuchittora** [comment]
This is because of wrapping `ToolTip` inside `Text`

**Comment by brooksbecton** [comment]
Is there any way to use a `Tooltip` inside `Text`?

**Comment by vikaskathuria** [comment]
Hey have you found the solution? facing the same issue
