### ISSUE TITLE
Tile Component is missing typings for certain props

### ISSUE THREAD

**Issue by scousino** [react-native-elements/react-native-elements#2673]
**Explain what you did (Required)**
Installed v2.3.2 and imported and used the Tile component.

**Expected behavior (Required)**

Expected all props listed on the documentation to be available as fields on TileProps

**Describe the bug (Required)**

titleNumberOfLines, and possibly other props are not a part of the typings declaration in the latest version. Even though they are in the documentation and the source code

**To Reproduce (Required)**

Just use the Tile component in a typescript react project.

**Screenshots (Required)**

```
export interface TileProps {
  /**
   * Icon Component Props
   */
  icon?: IconObject;

  /**
   * Styling for the outer icon container
   */
  iconContainerStyle?: StyleProp<ViewStyle>;

  /**
   * Text inside the tile
   */
  title?: string;

  /**
   * Styling for the title
   */
  titleStyle?: StyleProp<TextStyle>;

  /**
   * Text inside the tile when tile is featured
   */
  caption?: string;

  /**
   * Styling for the caption
   */
  captionStyle?: StyleProp<TextStyle>;

  /**
   * Changes the look of the tile
   */
  featured?: boolean;

  /**
   * @default none	object (style)	Styling for the outer tile container
   */
  containerStyle?: StyleProp<ViewStyle>;

  /**
   * Source for the image
   */
  imageSrc: ImageURISource | string | number;

  /**
   * Styling for the image
   */
  imageContainerStyle?: StyleProp<ViewStyle>;
  /**
   * Styling for overlay
   */
  overlayContainerStyle?: StyleProp<ViewStyle>;
  /**
   * @default none	function (event)	Function to call when tile is pressed
   */
  onPress?(): void;

  /**
   * Number passed to control opacity on press
   *
   * @default 0.2
   */
  activeOpacity?: number;

  /**
   * Styling for bottom container when not featured tile
   */
  contentContainerStyle?: StyleProp<ViewStyle>;

  /**
   * Width for the tile
   *
   * @default Device Width
   */
  width?: number;

  /**
   * Height for the tile
   *
   * @default Device Width * 0.8
   */
  height?: number;

  /**
   * Specify a different component as the Image component
   * @default React Native BackgroundImage component
   */
  ImageComponent?: React.ComponentClass;

  /**
   * Optional properties to pass to the image if provided e.g "resizeMode"
   */
  imageProps?: Partial<ImageProps>;
}
```
Couldn't screenshot, but this is the TileProps interface as served via npm

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  2.3.2       |
| react-native          |      0.62.2   |

**Comment by scousino** [comment]
I'd say overall the typescript definitions in this library are often out of date or not in parity with the documentation. I've come across multiple scenarios. For example, Tile has no definition for onLongPress, however it does support it because it also receives all props that TouchableNativeFeedback and TouchableOpactiy do, which includes onLongPress.

**Comment by pranshuchittora** [comment]
> I'd say overall the typescript definitions in this library are often out of date or not in parity with the documentation. I've come across multiple scenarios. For example, Tile has no definition for onLongPress, however it does support it because it also receives all props that TouchableNativeFeedback and TouchableOpactiy do, which includes onLongPress.

I agree with you, as of now, the types are not auto-generated which leaves some grey areas. We will try to integrate some auto-type definition generator like TS or Flow.

**Comment by flyingcircle** [comment]
Fixed. I agree that this needs a longer term solution. I looked for a way to auto gen this file, but it just doesn't exist. I think if we really want to get serious about this, we'll probably have to convert the code to typescript at some point soon. But this issue has been resolved.

**Comment by scousino** [comment]
You're already using typescript, all your files are TSX files, aka TypeScript JSX
