### ISSUE TITLE
Animated: useNativeDriver Warning

### ISSUE THREAD

**Issue by kimfucious** [react-native-elements/react-native-elements#2675]
**Explain what you did (Required)**
I've implemented a Slider based on docs [here](https://reactnativeelements.com/docs/slider) in a React Native app, built with Expo, using the managed workflow.

I have seen the issue that exists in the React Native Elements repo [here](https://github.com/react-native-elements/react-native-elements/issues/2330), but it appears to be closed while the issue seems to remain.

Perhaps this issue exists because this is a fork of React Native Slider and it's not been resolved upstream, as per [this](https://github.com/jeanregisser/react-native-slider/issues/187)?

Any advice toward resolving this would be appreciated.

**Expected behavior (Required)**
The Slider should work without showing a warning.

**Describe the bug (Required)**

A warning message is thrown with every change of the slider

```console
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false
```
**To Reproduce (Required)**

Use Slider as in the below:
```js
        <Slider
          animateTransitions={true}
          disabled={isUpdatingAutoSlurpNotificationTime}
          value={currentSliderTime}
          minimumValue={8}
          maximumValue={24}
          step={2}
          onValueChange={value => setCurrentSliderTime(value)} // saves to local state
          onSlidingComplete={value => handleSelectTime(value)} // saves to the db, then redux state, which updates local state
          trackStyle={{ height: 5, backgroundColor: "transparent" }}
          thumbStyle={{ height: 14, width: 14, backgroundColor: "transparent" }}
          thumbProps={{
            children: (
              <Icon
                name="schedule"
                type="material"
                size={14}
                reverse
                containerStyle={{ bottom: 14, right: 14 }}
                color={
                  isUpdatingAutoSlurpNotificationTime
                    ? theme.colors.mutedText
                    : theme.colors.primary
                }
              />
            )
          }}
        />
```
Note that, for me, the slider won't move without setting `animateTransitions` to `true`, and when I do that, the above warning is thrown `onSlidingComplete`.

**Screenshots (Required)**

![image](https://user-images.githubusercontent.com/26792769/98663746-0dd65800-237c-11eb-9f09-21ca7f79f047.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  2.3.2  |
| react-native          |   0.62  |
| expo sdk          |   38  |

**Comment by pranshuchittora** [comment]
Hi, the slider is built by tinkering with `width` and `height` property. But the native driver understands transform only, hence supporting the native driver will require a complete refactoring of the slider.

**Comment by olafurnsig** [comment]
@pranshuchittora - I think you're misunderstanding?

Animations now require that `useNativeDriver` is either set as true or false, if not then there's always a warning coming.

So what's missing here is `useNativeDriver: false` being set to remove the warnings.
