### ISSUE TITLE
Slider thumbTouchSize is not working on Android

### ISSUE THREAD

**Issue by AllyssaLBatten** [react-native-elements/react-native-elements#2678]
**Explain what you did (Required)**

Within my app, I have a Slider which has a thumb styled larger (48x48) than the default touch area (40x40). I added a thumbTouchSize value that is significantly larger (120x120). This works on iOS, but is not registering on Android. On Android, the responsive touch area is still the default 40x40.

**Expected behavior (Required)**

The Slider should register a press within the touch area set by thumbTouchSize, on Android and iOS.

**Describe the bug (Required)**

The thumbTouchSize value is not registering on Android, but is working on iOS.

**To Reproduce (Required)**

Use the Slider like below:

```
<View style={styles.container}>
  <Text style={styles.text}>
    {quantity}
  </Text>
  <View style={styles.sliderContainer}>
    <Slider
      value={quantity}
      onValueChange={setQuantity}
      minimumValue={0.25}
      maximumValue={5}
      step={0.25}
      thumbStyle={styles.thumbStyle}
      thumbTouchSize={{width: 120, height: 120}}
      debugTouchArea
    />
  </View>
</View>
```

[Here's the bug recreated on Snack.](https://snack.expo.io/@allyssabatten/slider-bug)

**Screenshots (Required)**

_On iOS:_

![iOS](https://user-images.githubusercontent.com/18508593/98983305-9543d880-24ee-11eb-8767-1c6ca3c82a1b.gif)

_On Android:_

![android](https://user-images.githubusercontent.com/18508593/98983290-8fe68e00-24ee-11eb-85dc-06a091b9a5b7.gif)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    2.3.2     |
| react-native          |    0.63.3     |

**Comment by pranshuchittora** [comment]
Hi, I assigned some height to the Slider using `style={{height:100}}` this fixed the issue. You can explore more in the Playground -> https://react-native-elements.js.org/#/slider
