### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by petr7555** [react-native-elements/react-native-elements#2680]
**Is your feature request related to a problem? Please Describe.**
I want to use this library on Windows. Some components are fine, but components, that choose their style depending on platform do not work. This is because the library is calling react-native's _Platform.select_, which on Windows returns _undefined_.
So then `Platform.select(theme.colors.platform).grey` fails with an error _Cannot read property 'grey' of undefined_.

**Describe the solution you'd like**
Add fallback colors when platform is undefined.

**Describe alternatives you've considered**
An obvious alternative would be React Native team making `Platform.select` work on Windows too.
My temporary fix is to define my own _Platform_ object with method _select_ that always returns '_android_'.

**Comment by pranshuchittora** [comment]
Hi @petr7555 that would be great. I have added this issue to our next major release roadmap. It would be great if you can help us achieve this by contributing to the project :)

**Comment by wcarle** [comment]
@petr7555 
FYI you can workaround this by using the ThemeProvider.  Just wrap your components or whole app in <ThemeProvider> and add windows or macos colors:

```
import { ThemeProvider } from 'react-native-elements';

const theme = {
  colors: {
    platform: {
      macos: {
        error: '#f44336',
        grey: 'rgba(0, 0, 0, 0.54)',
        primary: '#2196f3',
        secondary: '#9C27B0',
        success: '#4caf50',
        warning: '#ffeb3b',
      },
      windows: {
        error: '#f44336',
        grey: 'rgba(0, 0, 0, 0.54)',
        primary: '#2196f3',
        secondary: '#9C27B0',
        success: '#4caf50',
        warning: '#ffeb3b',
      },
    },
  },
};

class App extends React.Component {
  render() {
    return (
      <>
        <ThemeProvider theme={theme}>
          <StatusBar barStyle="dark-content" />
          <OtherStuff />
        </ThemeProvider>
      </>
    );
  }
};
```

**Comment by pranshuchittora** [comment]
@wcarle that would work but internally there are lots of conditionalities based on platform (Android or iOS). That might break. Unfortunately as of now, I don't have Windows installed. Will install soon :+1:
