### ISSUE TITLE
Icons are not rendering in searchBar in android only

### ISSUE THREAD

**Issue by Yandamuri** [react-native-elements/react-native-elements#2683]
**Explain what you did (Required)**

Arrow icon and clear icon are not rendering in searchBar

**Expected behavior (Required)**

Arrow icon should always be there left side and clear icon should be there right side when some text is entered in the searchBar

**Describe the bug (Required)**

Arrow icons and clear icons are not rendering.

**To Reproduce (Required)**

Just implement the searchBar as described in the example in package documentation and you can find that icons are not rendering. Note that this issue is occuring in android only and working perfect in ios. so please run the code in android only. 

**Screenshots (Required)**

Please look at th ebelow screen shot where some inappropriate things are rendering instead of actual icons 

![elements 2](https://user-images.githubusercontent.com/31983789/99385089-754d5400-28f6-11eb-9f30-6d9083a4efae.PNG)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    2.2.1    |
| react-native          |     0.63.2    |

**Comment by rmovieira** [comment]
Same Issue here :(

**Comment by pranshuchittora** [comment]
Kindly refer this and let me know it works or not :)
https://github.com/react-native-elements/react-native-elements/issues/2677#issuecomment-725420267

**Comment by rmovieira** [comment]
> 
> 
> Kindly refer this and let me know it works or not :)
> [#2677 (comment)](https://github.com/react-native-elements/react-native-elements/issues/2677#issuecomment-725420267)

It worked for me.
The strange thing is that I have icons on other screens that work normally. But after `react-native link` everything seems to be working as expected.
Thanks for your help!

**Comment by namakujuo** [comment]
I have the same issue. I'm on react native 63.3 linking doesn't solve the issue for me

**Comment by Yandamuri** [comment]
@pranshuchittora Excellent. this solution worked for me
