### ISSUE TITLE
Icons are not rendering with expo SDK 39

### ISSUE THREAD

**Issue by bietkul** [react-native-elements/react-native-elements#2684]
**Explain what you did (Required)**

Check this link Icons are not working with expo SDK 39.0 but when I change it to 38.0 then it works.
https://snack.expo.io/@bietkul/b97b9f?&preview=true&platform=ios&iframeId=qn4os3zz2g&theme=dark

**Expected behavior (Required)**

Icon should render regardless of expo SDK version

**Describe the bug (Required)**

**To Reproduce (Required)**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

Example:

```bash
# Snack
https://snack.expo.io/@bietkul/b97b9f?&preview=true&platform=ios&iframeId=qn4os3zz2g&theme=dark

**Comment by pranshuchittora** [comment]
Kindy refer this and let me know it works or not https://github.com/react-native-elements/react-native-elements/issues/2677#issuecomment-725420267

**Comment by flyingcircle** [comment]
Tried out what @pranshuchittora and that works. You try using the `next` branch directly in your code or wait for the next release version.
