### ISSUE TITLE
Allow the option to remove Cancel button on SearchBar for IOS look

### ISSUE THREAD

**Issue by UGhari** [react-native-elements/react-native-elements#2686]
**Is your feature request related to a problem? Please Describe.**
No

**Describe the solution you'd like**
I am using the react native elements searchbar in my application, and has chosen to use the IOS look for both Android and IOS (platform={'ios'}). However, I am not a fan of the cancel button and would like to remove it.  Would it be possible to make the cancelIcon prop available for IOS look too, so we can set it to false and not see the cancel Icon? I tried using cancelButtonTitle={''} but there's some weird blank spacing.

**Comment by flyingcircle** [comment]
I think you may be better suited to using the `default` searchbar. You can set `lightTheme` to `true` and `round` to `true` and that should more less be the exact searchbar that you're describing.

**Comment by UGhari** [comment]
Ill give it a go and close the issue if I get the desired effect mentioned above thanks

**Comment by UGhari** [comment]
Worked flawlessly thanks!
