### ISSUE TITLE
Card(Props): support for different levels of elevation (shadow)

### ISSUE THREAD

**Issue by reinaldosimoes** [react-native-elements/react-native-elements#2687]
**Is your feature request related to a problem? Please Describe.**
The `Card` component works fine for most cases, but it would be cool to have a little bit more customization when it comes to the levels of elevation, either for UX reasons, or just to follow an already set design. The values for `shadow` would take into consideration Google's Material Design documentation and Apple's Human Interface Guidelines.

**Describe the solution you'd like**
Introducing a `shadow` prop with options for how elevated the `Card` component should be, with `"xs"` being the current shadow, and the default if `shadow` is not defined.

```
shadow: = "xs" | "sm" | "md" | "lg"
```

**Usage**
```
<Card shadow="sm">
  <Card.Image source={require('../image.png')} />
  <Text>Hello World!</Text>
</Card>

**Comment by pranshuchittora** [comment]
I thought of that before but considering the overall design aspects of other components, it won't be a good fit. 
If a user wants to add shadow he can easily do so by adding the `containerStyle` prop

**You can try this out in the RNE Playground -> https://react-native-elements.js.org/#/card** 

Copy and Paste the following code :point_down: in the Playground

```jsx
import * as React from "react";
import { Card } from "react-native-elements";
import { View, Image } from "react-native";

export default () => {
  return (
    <Card
      containerStyle={{
        shadowColor: "#0002",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 1,
        shadowRadius: 20
      }}
      wrapperStyle={{}}
    >
      <Card.Title>CARD WITH DIVIDER</Card.Title>
      <Card.Divider />
      <View
        style={{
          position: "relative",
          alignItems: "center"
        }}
      >
        <Image
          style={{ width: "100%", height: 100 }}
          resizeMode="contain"
          source={{
            uri:
              "https://avatars0.githubusercontent.com/u/32242596?s=460&u=1ea285743fc4b083f95d6ee0be2e7bb8dcfc676e&v=4"
          }}
        />
        <Text>Pranshu Chittora</Text>
      </View>
    </Card>
  );
}
```

**Comment by reinaldosimoes** [comment]
I see the possibility of using this based on the platform, but for consistency, it might not be the best approach.
