### ISSUE TITLE
RNE Website: Searches are resulting in "Not Found" pages

### ISSUE THREAD

**Issue by RyanTG** [react-native-elements/react-native-elements#2690]
**Explain what you did (Required)**

I clicked on a search result on the [RNE website](https://reactnativeelements.com). For example, I searched "icon" and then clicked the "available icon sets" result.

**Expected behavior (Required)**

I expected to visit the appropriate website.

**Describe the bug (Required)**

Instead, I am sent to a "Not Found" page. Example URL: https://reactnativeelements.com/react-native-elements/docs/icon.html#available-icon-sets

**To Reproduce (Required)**

On the website, type a search in the upper right searchbar, then click one of the suggested results.

The correct url is: https://reactnativeelements.com/docs/icon#available-icon-sets

So it looks like the `/react-native-elements/` path in the search result url string is the issue.

Additionally, the `.html` in the search result url string seems to produce an issue with anchored links. For example:

https://reactnativeelements.com/docs/icon/#available-icon-sets - works great
https://reactnativeelements.com/docs/icon.html/#available-icon-sets - results in a redirected url that strips out everything starting at `/html...`. So the anchor disappears from the url.

**Comment by pranshuchittora** [comment]
Thanks for reporting :+1: 
I am able to reproduce

**Comment by flyingcircle** [comment]
Thanks for pointing this out. It's fixed now.
