### ISSUE TITLE
Masked input for TextInput ?

### ISSUE THREAD

**Issue by rwanito** [react-native-elements/react-native-elements#2692]
Hi !
Thanks for your work !

It would be a great feature if you add masked input to the input component.
Because, in my case, I try to add a simple date input like : yyyy/mm/dd and it's not quite easy to achieve it.

Do you have any ideas to do it or is it ok to add on RNE ?

Thanks !

**Comment by flyingcircle** [comment]
This is already provided by: https://github.com/benhurott/react-native-masked-text If you want it to have the RNE styling then you have us the `InputComponent` prop to inject it into the RNE component.

**Comment by mogol23** [comment]
@flyingcircle tried, but losing focus after change value.
```
<Input
                        value={form.phone}
                        onChangeText={(v, b) => handleForm('phone')(v)}
                        label="phone"
                        placeholder="+62-852-1234-5678"
                        leftIcon={{ color: secondaryColor, type: 'material-community', name: 'cellphone-iphone' }}
                        InputComponent={(props) => {
                          return (
                            <TextInputMask
                              {...props}
                              mask={"(+62) [000]-[0000]-[00000]"}
                              ref={this.phoneField}
                            />
                          )
                        }}
                      />
```

**Comment by MaximMatsuk** [comment]
same problem with losing focus

**Comment by flyingcircle** [comment]
My guess is that you'll need to implement the static functions that the `Input` component depends on. https://github.com/react-native-elements/react-native-elements/blob/next/src/input/Input.js

`focus`, `blur`, etc. And have the forwarded ref be the ones that call that function.

But I can't promise that'll these 2 components will work together. And you can see from the code base in the masked component, doing a mask library function is not a simple undertaking.

**Comment by willerrodrigo** [comment]
Hi ! @mogol23 @MaximMatsuk 

You can do it in reverse order. TextInputMask has a customTextInput prop that you can use to the react-native-elements Input :)
