### ISSUE TITLE
Icons show [?] and other icons.

### ISSUE THREAD

**Issue by pioNavarro** [react-native-elements/react-native-elements#2693]
**Explain what you did (Required)**
Icons show [?] and other icons.

**Expected behavior (Required)**
![image](https://user-images.githubusercontent.com/51459273/101520298-3f643280-39bf-11eb-90f5-53653961acb8.png)

**Describe the bug (Required)**

On the simulator the APP works fine but on the live APP icons from antdesign are not working. 

**Screenshots (Required)**
On live APP this is how it looks.
![image](https://user-images.githubusercontent.com/51459273/101520215-1fcd0a00-39bf-11eb-8baf-c7b39e267179.png)

On my simulator using expo build for simulator.
![image](https://user-images.githubusercontent.com/51459273/101520298-3f643280-39bf-11eb-90f5-53653961acb8.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    ^1.2.7     |
| react-native          |    sdk-38.0.2     |

 Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.4 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.5.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.10 
      react: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed

**Comment by AJIXuMuK** [comment]
Same issue

**Comment by AJIXuMuK** [comment]
I have `@expo/vector-icons` as a reference, and tried both `v10` and `v12` for the package.

**Comment by flyingcircle** [comment]
Did you follow all of the installation instructions for the vector-icons lib? https://github.com/oblador/react-native-vector-icons#ios

**Comment by pranshuchittora** [comment]
@pioNavarro can you try this -> https://github.com/react-native-elements/react-native-elements/issues/2677#issuecomment-725420267

**Comment by AJIXuMuK** [comment]
My problem was in ejected expo project.

**Comment by kickbk** [comment]
Guys, I don't want to start a new issue and this is related. There were some breaking changes in Expo SDK 40 which was released recently. One of them is the updated Ionicos version. This means that they old icon names don't work anymore. For instance, in `ListItemChevron.js` we need to update `ios-arrow-forward` to `chevron-forward-outline`. I also have to update other icons I use. It's really annoying to do, but if you guys could update the icons and release an update, that would be very much appreciated!

**Comment by flyingcircle** [comment]
@kickbk this ticket is unrelated to that since they're using expo 38. We already have changes prepped for expo 40 including that already done. v3 will be coming out soon. You can try using the `next` branch for testing it out as the fix is already there.

**Comment by flyingcircle** [comment]
@AJIXuMuK I noticed you're using an old, old version of RNE. Please update to the latest version and see if you're still seeing this issue.

**Comment by flyingcircle** [comment]
Confirmed that this is an Expo issue: https://github.com/expo/expo/issues/7792

Their solution to this was that you should delete your ios and android folders and rebuild.
