### ISSUE TITLE
prop "value" of Slider should be given integer value as per doc, but only works if string value is given.

### ISSUE THREAD

**Issue by JayantJoseph** [react-native-elements/react-native-elements#2694]
**Explain what you did (Required)**

So, it's pretty simple. I imported the Slider from react-native-elements version ^2.3.2, and this is my slider

```
<Slider
            disabled={isSliderDisabled}
            maximumValue={100}
            onValueChange={(sliderVal) => setSliderValue(Math.round(sliderVal))}
            style={styles.sliderStyle}
            thumbStyle={{
              backgroundColor: sliderDisabled? 'red' : 'lime'
            }}
            trackStyle={{ height: 2 }}
            maximumTrackTintColor={sliderDisabled? 'red' : 'lime'}
            minimumTrackTintColor={sliderDisabled? 'red' : 'lime'}
            value={50}
          />
```

**Expected behavior (Required)**

The slider thumb stays at the middle, as the `maximumValue `is 100

**Describe the bug (Required)**

It does not. Instead, it stays at the middle if string value is given, ie `value="50"`

**To Reproduce (Required)**

Just try giving a number as initial value (value prop of Slider component)

**Comment by flyingcircle** [comment]
Not able to reproduce. I used but int and string value and both worked. Though using a a string value throws a warning about using the wrong prop type. This is using the most recent version of RNE though. So I'd look to upgrading and trying that.

**Comment by flyingcircle** [comment]
Not able to reproduce. I used but int and string value and both worked. Though using a a string value throws a warning about using the wrong prop type. This is using the most recent version of RNE though. So I'd look to upgrading and trying that.
