### ISSUE TITLE
OnPress in ListItem wont work on Android React Native 0.63.4

### ISSUE THREAD

**Issue by glintpursuit** [react-native-elements/react-native-elements#2696]
**Explain what you did (Required)**
   
 1. We have ListItem in Scrollview 
 2. OnPress event on ListItem wont work with Android 
 3. It use to work with previous version of React Native & it is still working for iOS. 

**Expected behavior (Required)**

1. OnPress event should work

**Describe the bug (Required)**

1. OnPress will not get call on Android device, samsung s10 (It works on Android Simulator) 

` <ScrollView
          contentInsetAdjustmentBehavior="automatic"
          style={styles.scrollView}>
          <Header />
          <ListItem
            title="Click 1"
            onLongPress={() => console.log('long press')}
            onPress={() => {
              console.log('clicked');
            }}></ListItem>
          <ListItem
            title="Click 1"
            onPress={() => {
              console.log('clicked');
            }}></ListItem>
          <ListItem
            title="Click 1"
            onPress={() => {
              console.log('clicked');
            }}></ListItem>
          <ListItem
            title="Click 1"
            onPress={() => {
              console.log('clicked');
            }}></ListItem>
          <ListItem
            title="Click 1"
            onPress={() => {
              console.log('clicked');
            }}></ListItem>
          {global.HermesInternal == null ? null : (
            <View style={styles.engine}>
              <Text style={styles.footer}>Engine: Hermes</Text>
            </View>
          )}
        </ScrollView>`

**Your Environment (Required):**

`{
  "name": "ListItemTest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-elements": "^2.3.2",
    "react-native-vector-icons": "^7.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

**Comment by glintpursuit** [comment]
Observation:  this issue does not exist on Oneplus-8T Android 11

**Comment by flyingcircle** [comment]
This seems like a 99% likely error in React Native itself. I'd suggest opening a ticket there. But they'll also likely want more debugging information than you are presenting here. A list Item is simply a RN `View`, so there's not much to get messed up here.

**Comment by glintpursuit** [comment]
Thanks 
We have resolve this for now using touchable opacity over list item.

**Comment by lukewlms** [comment]
I had a similar issue where ListItem (but not TouchableOpacity) was eating keystrokes when the keyboard is up.  Setting different keyboardShouldPersistTaps values was not helpful.

Solved the same way as @glintpursuit, but wrapping ListItem in a TouchableOpacity.
