### ISSUE TITLE
SearchBar Null Is Not An Object (evaluating '_this.input.blur' )

### ISSUE THREAD

**Issue by namakujuo** [react-native-elements/react-native-elements#2712]
![image](https://user-images.githubusercontent.com/66373379/102418759-5e208580-3fcc-11eb-8fc1-e30682624e45.png)

This happens when I search, switch to a different screen, go back to the screen with the search bar, and then hit the cancel button.

I'm thinking this happens because it loses reference when switching screens and thus refers to a null?

Any ideas? Your help will be greatly appreciated.

**Comment by flyingcircle** [comment]
If you could create a simple repo that recreates this issue that would help out in figuring out what is going on. Or even a branch in the example app repo could do it.

**Comment by flyingcircle** [comment]
I did your steps as stated in Expo 40, RNE 3.0.1. Was not able to reproduce.

**Comment by namakujuo** [comment]
Sorry haven't had the time to setup an example.

I'm using bare react-native project on RNE 3.01 and React Native 63.3. I do have an old expo project where the search works fine. 

On the bare react-native is where the issue occurs. I did find a work around where I call this.search.clear() at the end of the api call in the finally promise. This isn't ideal, but is suitable fix for my needs. I would return to the expo version, but a lot of the libraries I use do not work with expo

**Comment by flyingcircle** [comment]
I would imagine that this is highly dependent then on how you setup your navigation with the app. I also have a `SearchBar` in a native app that I have developed for, but I have never seen this error you mention (Though that app is still on 2.x, the Searchbar hasn't changed considerably from 2.x).

**Comment by namakujuo** [comment]
Just want to note that the the navigation in the expo version and the native version is the same yet no issue on the expo version.

I'll try to create an example in the near future that reproduces the issue. 

Also I'm not sure if this helps, but I'm using the search bar in a functional component as opposed to a class based one. I don't think that is the issue because this also how my expo version is set up. Just thought it was worth mentioning seeing as the 'this' keyword is more commonly used in class components.

**Comment by batical** [comment]
On my Side, I fix this forcing platform to 'ios' for android

**Comment by JuanSBass** [comment]
> 

I have same error... can u fix it? TY!
