### ISSUE TITLE
after upgrade to 3.0.0 Header's leftComponent and rightComponent appears in the left side of header 

### ISSUE THREAD

**Issue by Aparus** [react-native-elements/react-native-elements#2713]
Hi! Thank you for v3! 

After upgrade from v2.3.2 to v3.0.0, in Header leftComponent and rightComponent appears on the left side of Header. 

In v2.3.2 they looked good: leftComponent at the left, rightComponent at the right. 

Here is my code: 

```jsx
<Header
  leftComponent={{
	  icon: 'home',
	  color: '#fff',
	  onPress: () => navigation.navigate('Home')
  }}
  rightComponent={{
	  icon: 'menu',
	  color: '#fff',
	  onPress: () => navigation.toggleDrawer()
  }}
/>
```
Here is how it looks like: 

![Screenshot from 2020-12-18 02-07-52](https://user-images.githubusercontent.com/1222611/102554986-e5f2b680-40d6-11eb-81ee-f28d412fa6af.png)

I tried different settings of `containerStyle` (justifyContent: 'space-around', 'space-between', width: '100%') , I even added `centerComponent` like a placeholder (I don't need it), but anyway they all appears in the left part of Header. 

Also `home` button is hard to click - I should click on its left side, for handler work. 

Is it bug, or I can't understand new way of using Header? 

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   3.0.0      |
| react-native          |   0.63.4      |
| expo |   40.0.0, web |

**Comment by flyingcircle** [comment]
Thanks! I'll look into this shortly.

**Comment by flyingcircle** [comment]
I was not able to reproduce this at least in iOS. This seems limited to web.
