### ISSUE TITLE
After upgrade to v3.0.0 all Image components turned to grey rectangulars 

### ISSUE THREAD

**Issue by Aparus** [react-native-elements/react-native-elements#2714]
Hi! Thank you for v3! 

After upgrade from v2.3.2 to v3.0.0, all Images (imported from RNE) turned to grey rectangulars. 

Here is my code:

```jsx
<Image
	source={image}
	style={[
		{ width: 100, height: 100, resizeMode: 'contain' },
		contentTypeStyle.image
	]}
/>
```

Importing Image from `react-native` instead of `react-native-elements` fixed the issue:  

import { Image } from 'react-native ~~-elements~~'

Honestly I don't know why I need RNE Image, but I just inform you. May be it will be a good bug report? 

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   3.0.0      |
| react-native          |   0.63.4      |
| expo |   40.0.0, web |

**Comment by flyingcircle** [comment]
RNE `Image` has an animated transition for when an Image loads so it can provide a better aesthetic. I noticed this happening when I transitioned to Expo 40, but it only happened in the emulator environment. Is this happening still when you run it on a real device?

**Comment by Aparus** [comment]
> RNE `Image` has an animated transition for when an Image loads so it can provide a better aesthetic. I noticed this happening when I transitioned to Expo 40, but it only happened in the emulator environment. Is this happening still when you run it on a real device?

Thank you for explanation about Image! 
Expo 40! I upgraded to it before RNE upgrade. 
My laptop with browser is a real device )) But, no. I used to use Expo client, but because of some issues (String.matchAll(regex) doesn't work in React-Native) and I didn't fix it yet...

**Comment by flyingcircle** [comment]
The `Image` is still working in the Playground: https://react-native-elements.js.org/#/image . So I don't really have a way of reproducing what you're describing here.

**Comment by Aparus** [comment]
> The `Image` is still working in the Playground: https://react-native-elements.js.org/#/image . So I don't really have a way of reproducing what you're describing here.

sorry , i didn't mention that I use `<Image source={require(file/local/path/)} /> `. I don't know how to reproduce it in playground. But on my laptop (expo  web), {uri} works, but {require} doesn't work. Here is an example with your image from playground: 

![localhost_19006_(iPhone 6_7_8)](https://user-images.githubusercontent.com/1222611/102643425-500b6a00-4170-11eb-9435-56f988e3db70.png)

**Comment by flyingcircle** [comment]
I believe you have the `Image` prop written incorrectly. the prop should be `source={{uri: require(...)}}`

**Comment by flyingcircle** [comment]
I see where the issue is now. I'll write up a PR soon.

**Comment by Aparus** [comment]
in Expo client still appears grey rectangulars.

**Comment by flyingcircle** [comment]
Is this Expo client in web?

**Comment by flyingcircle** [comment]
I noticed grey rectangles for a bit in Expo 40 when using the emulator, but installing to a real device works. Which makes me think that that's an expo issue.

**Comment by Aparus** [comment]
> Is this Expo client in web?

It is expo client on Android. In web it works after patch rne 3.0.1. And yes it's expo 40.

**Comment by flyingcircle** [comment]
I tried this on Expo Android RNE 3.0.1, Expo 40. Was not able to reproduce what you're saying.

**Comment by Aparus** [comment]
> I tried this on Expo Android RNE 3.0.1, Expo 40. Was not able to reproduce what you're saying.

Now I also can't reproduce. I don't know why it was. But now it's ok :) 
sorry.
