### ISSUE TITLE
Please keep the docs from 2.2.x

### ISSUE THREAD

**Issue by betoharres** [react-native-elements/react-native-elements#2715]
**Is your feature request related to a problem? Please Describe.**
Keep the docs from 2.2.x version online

**Describe the solution you'd like**
It's hard to handle big projects alone, and the JS world move too fast for one person to keep it up with all the dependencies updates, so please don't remove the docs from past versions <3 I love this library but I just got a sad surprise today.

**Describe alternatives you've considered**
an alternative link

Thank you!

**Comment by flyingcircle** [comment]
There really isn't that much of a difference between the 2.2 docs and the 2.3 docs. 2.3 deprecated a few props, but beyond those warnings, you should be able to upgrade safely to 2.3.2 without any issue. For any doubt, you can always reference specific version documentation from the github tag: https://github.com/react-native-elements/react-native-elements/tree/v2.2.1/website/docs
