### ISSUE TITLE
Slider is not working on expo web 

### ISSUE THREAD

**Issue by Aparus** [react-native-elements/react-native-elements#2728]
Hi! 
I copied your code with Slider from playground. And it works with expo android client. I can change position and see events in the console. 
But, I can't move Slider's seeker in expo web client. It behaves like a static image, don't respond on my actions. 
Can you check it please? 

![Screenshot from 2020-12-25 04-05-15](https://user-images.githubusercontent.com/1222611/103112473-b0b20f80-4666-11eb-8f0a-daeb7e8cdd62.png)

| software              | version |
| --------------------- | ------- |
| react-native-elements |   3.0.1      |
| react-native          |   0.63.4      |
| expo |   40.0.0, web |

**Comment by flyingcircle** [comment]
I'm going to put the likelihood of this getting fixed quickly as quite low. Have you tried using `react-native-community/slider` to see if it works?

**Comment by Aparus** [comment]
> I'm going to put the likelihood of this getting fixed quickly as quite low. Have you tried using `react-native-community/slider` to see if it works?

no, I didn't. thank you for informing!

**Comment by silenteyesoncode** [comment]
@flyingcircle  what about react-native-elements?

**Comment by flyingcircle** [comment]
@silenteyesoncode what about it?

**Comment by silenteyesoncode** [comment]
sorry I was about to say whats the status of slider
can I put a PR?

**Comment by flyingcircle** [comment]
@silenteyesoncode feel free to submit a pr for this. thanks.

**Comment by silenteyesoncode** [comment]
hi @flyingcircle 
on which branch should i work for this slider 
?

**Comment by flyingcircle** [comment]
@silenteyesoncode https://reactnativeelements.com/docs/contributing
