### ISSUE TITLE
Failed prop type: Invalid prop `inputStyle` supplied to `SearchBar`

### ISSUE THREAD

**Issue by woodcockjosh** [react-native-elements/react-native-elements#2729]
I'm trying to use SearchBar in expo project.

I expect there to be no errors printed to the console

<details>
<pre>
index.js:1 Warning: Failed prop type: Invalid prop `inputStyle` supplied to `SearchBar`.
    in SearchBar (at SearchBar.js:38)
    in SearchBar (at withTheme.js:42)
    in ThemedComponent (at withTheme.js:59)
    in ForwardRef(Themed.SearchBar) (at SearchBarComponent.tsx:22)
    in SearchBarComponent (at ChatScreen.tsx:20)
    in div (created by View)
    in View (at ChatScreen.tsx:19)
    in ChatScreen (at BottomNavigationComponent.tsx:58)
    in StaticContainer
    in StaticContainer (created by SceneView)
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabView)
    in div (created by View)
    in View (created by SceneContent)
    in SceneContent (created by BottomTabView)
    in div (created by View)
    in View (created by ResourceSavingScene)
    in div (created by View)
    in View (created by ResourceSavingScene)
    in ResourceSavingScene (created by BottomTabView)
    in div (created by View)
    in View (created by BottomTabView)
    in div (created by View)
    in View (created by BottomTabView)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in BottomTabNavigator (at BottomNavigationComponent.tsx:27)
    in BottomNavigationComponent (at HomeContainer.tsx:25)
    in HomeContainer (at TopBarComponent.tsx:90)
    in StaticContainer
    in StaticContainer (created by SceneView)
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by CardContainer)
    in div (created by View)
    in View (created by CardContainer)
    in div (created by View)
    in View (created by CardContainer)
    in div (created by View)
    in View (created by ForwardRef(CardSheet))
    in ForwardRef(CardSheet) (created by Card)
    in div (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (created by ForwardRef(AnimatedComponentWrapper))
    in ForwardRef(AnimatedComponentWrapper) (created by Card)
    in Dummy (created by Card)
    in div (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (created by ForwardRef(AnimatedComponentWrapper))
    in ForwardRef(AnimatedComponentWrapper) (created by Card)
    in div (created by View)
    in View (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in div (created by View)
    in View (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in div (created by View)
    in View (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in CardStack (created by Context.Consumer)
    in KeyboardManager (created by Context.Consumer)
    in div (created by View)
    in View (created by NativeSafeAreaView)
    in NativeSafeAreaView (created by SafeAreaProvider)
    in SafeAreaProvider (created by Context.Consumer)
    in SafeAreaProviderCompat (created by StackView)
    in div (created by View)
    in View (created by StackView)
    in StackView (created by StackNavigator)
    in StackNavigator (at TopBarComponent.tsx:84)
    in TopBarComponent (created by ConnectFunction)
    in ConnectFunction (at App.tsx:26)
    in EnsureSingleNavigator (created by ForwardRef(BaseNavigationContainer))
    in ForwardRef(BaseNavigationContainer) (created by ForwardRef(NavigationContainer))
    in ThemeProvider (created by ForwardRef(NavigationContainer))
    in ForwardRef(NavigationContainer) (at App.tsx:25)
    in PersistGate (at App.tsx:24)
    in ThemeProvider (created by Provider)
    in div (created by View)
    in View (created by Portal.Host)
    in Portal.Host (created by Provider)
    in Provider (at App.tsx:23)
    in Provider (at App.tsx:22)
    in App (created by ExpoRootComponent)
    in ExpoRootComponent (created by RootComponent)
    in RootComponent
    in div (created by View)
    in View (created by AppContainer)
    in div (created by View)
    in View (created by AppContainer)
    in AppContainer
</pre>
</details>

**To Reproduce (Required)**
Use this library in expo project.
Run web view
Look at the console to errors

**Screenshots (Required)**
![error](https://i.paste.pics/b8ce171fe3577a4a1befe994a34bd5fb.png?trs=8b4cd7fbb3aa38b87ff8e8d0527756f556db47b01c1f700bb95ac5a2e941b62d)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     2.3.2    |
| react-native          |    0.63.2     |

**Comment by woodcockjosh** [comment]
Here is the code that implements
```typescript
        const { search } = this.state;
        const inputStyle: StyleProp<TextStyle> = styles.input
        return (

            <SearchBar
                containerStyle={styles.container}
                inputContainerStyle={styles.inputContainer}
                placeholder="Search"
                onChangeText={this.updateSearch}
                value={search}
                inputStyle={inputStyle}
            />
        );
```

It is possible this is an expo issue but I'm only getting this error with the `SearchBar`

**Comment by woodcockjosh** [comment]
If I remove `StyleSheet.create(` and replace with just a static object then I don't get any errors. I'm not sure why. 
```typescript
import React, {Component} from "react";
import {SearchBar} from "react-native-elements";
import { StyleSheet } from "react-native";
import {AppTheme} from "../../themes/AppTheme";

interface MyProps {}
interface MyState {}

export class SearchBarComponent extends Component<MyProps, MyState> {
    state = {
        search: '',
    };

    updateSearch = (search) => {
        this.setState({ search });
    };

    render() {
        return (

            <SearchBar
                containerStyle={stylesStatic.container}
                inputContainerStyle={stylesStatic.inputContainer}
                placeholder="Search"
                onChangeText={this.updateSearch}
                value={this.state.search}
                inputStyle={stylesStatic.input}
            />
        );
    }
}

const stylesStatic = {
    container: {
        width: '100%',
        flexDirection: "row",
        backgroundColor: AppTheme.colors.background,
        borderBottomColor: AppTheme.border.veryLight.borderColor,
        borderTopColor: 'transparent',
        alignSelf: "center",
        padding: 15,
        paddingTop: 0
    },
    input: {
        fontSize: 16
    },
    inputContainer: {
        backgroundColor: AppTheme.colors.background,
        ...AppTheme.border.veryLight,
        borderBottomWidth: AppTheme.border.veryLight.borderWidth,
        borderRadius: AppTheme.border.radiusNormal,
        borderBottomColor: AppTheme.border.veryLight.borderColor,
        height: AppTheme.search.height
    }
}
```

**Comment by flyingcircle** [comment]
I created a Snack here: https://snack.expo.io/sEFEp4tEF and was not able to reproduce. I'm guessing that the problem you're seeing lies elsewhere.

**Comment by superdopey** [comment]
I am seeing the same behaviour:

```
//not woring when wrapped with StyleSheet.create()
const styleNotWorking = StyleSheet.create({
  inputContainer: {
    borderBottomColor: colors.lightGrey,
    
  },
})

//works, but now we don't have intellisense on the ViewStyles
const style = {
  inputContainer: {
    borderBottomColor: colors.lightGrey,
  },
}
```
