### ISSUE TITLE
Theming compatibility with React Navigation

### ISSUE THREAD

**Issue by pythys** [react-native-elements/react-native-elements#2733]
**React Navigation** provides theming using `<NavigationContainer theme={MyTheme}>...` whereas **react-native-elements** provides the same with `<ThemeProvider theme={MyTheme}>`

A few questions:
- Is there a conflict here?
- Which should I use?
- What wraps what? If I should use RNE themes, should I wrap the theme around the NavigationContainer?

Thank you for any insights folks.

**Comment by flyingcircle** [comment]
`react-navigation`'s theming is not as extensive and only includes colors.
`react-native-elements`' theming allows you to globally define particular fonts and styles for any component and all RNE components by default. You can extend it with your own components using `withTheme`.

Either way, you will have to code up the theming either way. You should analyze the features and use cases of both and decide which will be more pertinent to your work.

It doesn't really matter where you wrap the Theme so long as it wraps all of the components you want themed.
