### ISSUE TITLE
ListItem switch usage unclear in new 3.x docs

### ISSUE THREAD

**Issue by juanjsebgarcia** [react-native-elements/react-native-elements#2741]
**Is your feature request related to a problem? Please Describe.**
The [documentation](https://reactnativeelements.com/docs/listitem/) mentions usage of a switch button in the opening paragraph, but then does not provide any clear usage of how its achieved.

**Describe the solution you'd like**
An example in the docs of how to achieve the classic switch toggle now on the v3.0 refactor of ListItem.  My project used these on v2.x and I am struggling to port to v3.x

**Describe alternatives you've considered**
I have tried using `ListItem.Checkbox` but not sure this is the correct approach.

**Comment by flyingcircle** [comment]
As stated here: https://reactnativeelements.com/blog#input-buttongroup-switchprops-checkbox-badge-chevron-checkmark

You should be able to do something like:

```js
import {Switch} from 'react-native';
...

<ListItem>
  <ListItem.Content>...</ListItem.Content>
  <Switch />
</ListItem>
```

**Comment by flyingcircle** [comment]
There is also an example of it being implemented in the example app: https://github.com/react-native-elements/react-native-elements-app/blob/next/src/views/lists2.js
