### ISSUE TITLE
Documentation: Example should be complete / working code.

### ISSUE THREAD

**Issue by TobbyReign** [react-native-elements/react-native-elements#2744]
The doc is a real mess.
Alll the source provided miss some part of code, import is only the part of elements (why don't you just use the real code used for the demo app?)

**Comment by pranshuchittora** [comment]
@TobbyReign that's unfortunate to hear that. I truly understand the issue you are facing. 
We will try to fix this ASAP, it would be great if you can help us by contributing to the same :)

**Comment by flyingcircle** [comment]
@TobbyReign Please make your report more specific. What exact document doesn't have a full example?
