### ISSUE TITLE
Avatar Accessory default position

### ISSUE THREAD

**Issue by Mwild2** [react-native-elements/react-native-elements#2752]
**Explain what you did (Required)**
Using the Avatar component (rounded) with accessory is meant to yield an avatar as pictured here:

![](https://reactnativeelements.com/img/avatar/avatar--edit.jpg)

Since the Avatar rework that moved the Accessory into its own component, the default location for the accessory is bottom: 0, right: 0. This produces the following:

<img width="174" alt="Screenshot 2021-01-15 at 14 29 55" src="https://user-images.githubusercontent.com/54813089/104739023-26793a80-573e-11eb-9c71-480715e89044.png">

**Expected behavior (Required)**

The accessory should be positioned as before the rework. 

**Describe the bug (Required)**

Functionality has regressed. Currently I am employing extra code to determine the size of the avatar and in hand how many pixels to move the accessory to get it positioned correct.

**To Reproduce (Required)**
```
<Avatar
        rounded
        source={{ uri: `https://storage.googleapis.com/image-path` }}
        size='xlarge'>
          <Avatar.Accessory raised
              name='heartbeat'
              type='font-awesome'
              color='#f50' />
</Avatar>
```
**Your Environment (Required):**

| --------------------- | ------- |
| react-native-elements | 3.0.0-alpha.1 |
| react-native          | 0.63.3 |

**Comment by flyingcircle** [comment]
You don't need to move the position, increase the size of the Accessory with the `size` prop.
