### ISSUE TITLE
Ability to change theme for a component tree via state change

### ISSUE THREAD

**Issue by kdo1234** [react-native-elements/react-native-elements#2754]
**Is your feature request related to a problem? Please Describe.**
It seems that there is no way to dynamically change the theme for a ThemeProvider's tree directly via a state change. The theme for the ThemeProvider tree can be dynamically set before the first render, but can't be changed later because the tree does not start using the new theme. By "change the theme" I don't mean changing the properties of the theme (which would be expensive to detect) but changing the theme prop to refer to a different object.

**Describe the solution you'd like**
Changing the ThemeProvider's theme should update components within the ThemeProvider's tree.
```
export default class App extends React.Component {
  state = { theme: 0}

  theme() {
    return this.state.theme === 1 ? theme1 : theme0;
  }

  render() {
    return (
        <ThemeProvider
          theme={this.theme()}
          >
          <Button
            onPress={() => {this.setState((state) => {return {theme: (state.theme + 1) % 2 }})}}
            title={"Change Theme with state (does not work)"} 
          />
        </ThemeProvider>
    );
  }
}
```

**Describe alternatives you've considered**
I've implemented an alternative with a hidden component that uses getDerivedStateFromProps to trigger a call to `withTheme`, but it doesn't seem DRY to duplicate specifying the theme.

```
class ThemeChanger extends React.Component {
  state = {}

  static getDerivedStateFromProps(props, state) {
    const { realTheme } = props;
    if (realTheme !== state.realTheme) {
      if (state.realTheme !== undefined) {
        props.replaceTheme(realTheme);
      }
      return {
        realTheme,
      };
    }
    return null;
  }

  render() {
    return null;
  }
}

const ThemedThemeChanger = withTheme(ThemeChanger);

export default class App extends React.Component {
  state = { theme: 0}

  theme() {
    return this.state.theme === 1 ? theme1 : theme0;
  }

  render() {
    return (
        <ThemeProvider
          theme={this.theme()}
          >
          <ThemedThemeChanger realTheme={this.theme()}/>
          <Button
            onPress={() => {this.setState((state) => {return {theme: (state.theme + 1) % 2 }})}}
            title={"Change Theme with side effect (works)"} 
          />
        </ThemeProvider>
    );
  }
}
```

const ThemedThemeChanger = withTheme(ThemeChanger);

**Additional context**
Here is a snack that reproduces the current behavior and the alternative: https://snack.expo.io/DhVc8tX4z

**Comment by flyingcircle** [comment]
You can probably write a hook to do this. See how to dynamically change the theme in the example app: https://github.com/react-native-elements/react-native-elements-app/blob/next/src/navigation/DrawerNavigator.js. You can also try it out for yourself to see how it works.

**Comment by kdo1234** [comment]
Please don't close this issue just yet. It seems inconsistent that `ThemeProvider` handles the special case of the `useDark` prop changing, but not the `theme` prop changing. It doesn't seem like there would be any measurable performance impact of supporting changing the theme based on state. The enhancement/fix seems like it might require a few small changes to `ThemeProvider`'s `constructor` and `getDerivedStateFromProps` that I've included below. I haven't tested it yet, but I can work on it as a PR. If this enhancement/fix is not desirable for some reason it would be wonderful if there was an explanation.

If this enhancement/fix is not desirable for some reason then can the ThemeChanger be added to RNE as a utility class?

```
export default class ThemeProvider extends React.Component {
  constructor(props) {
    super(props);

    const defaultColors = props.useDark ? darkColors : colors;

    this.defaultTheme = deepmerge(
      {
        colors: defaultColors,
      },
      props.theme
    );
    this.state = {
      theme: this.defaultTheme,
      useDark: props.useDark,
      themeProp: props.theme
    };
  }

  static getDerivedStateFromProps(props, state) {
    const { useDark, theme } = props;
    if (useDark !== state.useDark && theme !== state.themeProp) {
      const defaultColors = useDark ? darkColors : colors;
      return {
        theme: deepmerge(
          state.theme,
          deepmerge(
            {
              colors: defaultColors,
            },
            props.theme
          )
        ),
        useDark,
        themeProp: theme
      };
    } 
    return null;
  }
```

**Comment by flyingcircle** [comment]
I guess I'm still not seeing the issue here. Is there any reason why you are not using the `updateTheme` to update your theme? It's been a while since I've looked at this, but the reasons I remember are that updating the Theme is an expensive operation. But also the `updateTheme` function provided by the Theme Context already provides this in a pretty DRY way.

I'm open to reopening the ticket, but let's flesh out a little bit more first.

**Comment by kdo1234** [comment]
Thank you! 

Here is how I have been thinking about it:

- `ThemeProvider` is pure when the `useDark` prop changes and when the `useDark` and `theme` props change in the same update.
- `ThemeProvider` is not pure when the `theme` prop changes without the `useDark` prop changing.

The result is that whenever the theme should be updated but there is no programatic event for it because the logic for determining the theme is pure, then a component such as the `ThemedThemeChanger` above is required to generate a side effect call to `updateTheme`.

The reasoning that "theme updates are not applied because updating the theme is expensive" seems to be inconsistently applied because it's not followed for useDark` prop changes. If we are willing to perform the expensive operation for `useDark` updates then why not for `theme` updates?

Also, using `updateTheme` is not DRY for pure code that sets the theme, because the same theme logic must be fed to `updateTheme` and `ThemeProvider`.

**Comment by flyingcircle** [comment]
I don't know what you mean by `updateTheme` logic must be fed to both `updateTheme` and `ThemeProvider`. `updateTheme` only needs to be called once as described in the docs: https://reactnativeelements.com/docs/customization#using-the-theme-in-your-own-components

**Comment by kdo1234** [comment]
Yes, that is accurate, but for a use case where the theme is derived from pure logic the initial theme must be passed to the `ThemeProvider`. The initial theme and updates to it must also be passed to the component that produces side effect calls to `updateTheme` based on state changes so that it knows when to call `updateTheme`.

This point seems less important than whether `ThemeProvider` should be pure for `theme` prop updates to be consistent with its pureness for`useDark` prop updates.

**Comment by flyingcircle** [comment]
Hmm, I'm not seeing how this simplifies things. In fact, it may make things more complicated.
I'm not sure what use case you have for a dynamic theme change, but I can imagine a few scenarios.

But! I am in favor of rewriting the component. I found this article: https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#what-about-memoization

We don't explicitly use any of the anti-patterns described there, but perhaps the Context should be rewritten using a `PureComponent`? https://reactjs.org/docs/react-api.html#reactpurecomponent

**Comment by mattmcginnis** [comment]
> I'm not sure what use case you have for a dynamic theme change, but I can imagine a few scenarios.
Wouldn't the most basic scenario for a dynamic theme change be the user going into settings and changing the theme?  You would expect the theme to change instantly, and also be merged with the default light/dark theme, but this doesn't unless useDark changes. It's possible to change from one "dark theme" to another "dark theme".

**Comment by Gautam-Arora24** [comment]
@flyingcircle I would like to work on this issue. Kindly assign it to me 😄

**Comment by hetanthakkar1** [comment]
I have submitted the PR for this issue. @flyingcircle  could you please review!

**Comment by anthowm** [comment]
This will be available in next release ?
