### ISSUE TITLE
Support Variables and custom attributes

### ISSUE THREAD

**Issue by laithfawwaz** [react-native-elements/react-native-elements#2755]
**Problems**
1. It's not easy to customize the default font size for text h1 and other things like that, 
if I needed to customize them, I need to write the theme object with textStyle -> fontSize for text component...
2. There is a small range of font sizes that the text supports, only the headings, what about small font size and paragraph font size
3. Customization can be easier of we can write our custom attributes inside the theme object instead of writing our custom components

**Suggested solution**
**re 1,2**: I suggest not hard code anything that can be a variable, such as h1 font size, you can add variables file that the developers can override
**re 3**: I suggest supporting something like this
```
  const Theme = {
     Text: {   ----- RNE component
        bgRed: {. ---- RNE custom attributes
          containerStyle: {.  --- RNE component attribute value when custom attribute is true
            background: red
         }
       }
  }
```
example usage:
`<Text bgRed>Example</Text>`
is equivalent to 
`<Text containerStyle={background: red}></Text>`

**Comment by flyingcircle** [comment]
I don't see how customization would be any easier by writing props in a theme. I think what you're looking for is implemented here: https://styled-components.com/docs/basics
