### ISSUE TITLE
The official React Native Elements App on Expo website is outdated. Requires a newer SDK to be tried.

### ISSUE THREAD

**Issue by flaviorbianchi** [react-native-elements/react-native-elements#2756]
The link on the README file directs us to https://expo.io/@monte9/projects/react-native-elements-app where we get the message:

_This project uses Expo SDK v34.0.0. If you want to open this project, the author will need to update the project's SDK version._

Is there a way we can contribute to that app by updating its SDK or any other way? Or just wait for @Monte9 to see this and update the SDK? Not complaining. Just looking for opportunities to contribute.

**Comment by suretarget** [comment]
Checkout Demo app by @flyingcircle 
[https://expo.io/@flyingcircle/projects/react-native-elements-app](https://expo.io/@flyingcircle/projects/react-native-elements-app)
