### ISSUE TITLE
How to solve TS error: Object is possibly 'undefined' when access to the theme with bracket notation?

### ISSUE THREAD

**Issue by cristian05** [react-native-elements/react-native-elements#2767]
**Explain what you did (Required)**

I want to build a component that allows me to have different button sizes. To achieve this I build a custom component which have a property `size` and with this I access dynamically to a specific size of the button with its respective styles inside `theme` object. Everything works as expected, but I have the following error in typescript: `TS2532: Object is possibly 'undefined'.` every time I try to access to the `sizes` object inside `theme` with the bracket notation.

### What I have

```typescript
import React, { useContext } from 'react';
import { Button, FullTheme, ThemeContext } from 'react-native-elements';

export type Props = Button['props'];
export type Theme = Partial<FullTheme>;

const styles = {
  button: (theme: Partial<FullTheme>, size: string) => ({
    padding: theme?.Button?.sizes[size]?.padding, // problem here
  }),
  title: (theme: Partial<FullTheme>, size: string) => ({
    fontSize: theme?.Button?.sizes[size]?.fontSize, // problem here
    lineHeight: theme?.Button?.sizes[size]?.lineHeight, // problem here
    fontFamily: theme?.Button?.font?.fontFamily,
  }),
};

function ButtonElement(props: Props): JSX.Element {
  const {
    size = 'medium',
    children,
    ...rest
  } = props;
  const { theme } = useContext(ThemeContext);

  return (
    <Button
      titleStyle={styles.title(theme, size)}
      buttonStyle={styles.button(theme, size)}
      {...rest}
    >
      {children}
    </Button>
  );
}
```

### Theme object

```typescript
export const theme = {
  Button: {
    font: {
      fontFamily: 'inter-display-bold',
    },
    sizes: {
      small: {
        fontSize: 14,
        padding: 10,
        lineHeight: 20,
      },
      medium: {
        fontSize: 18,
        padding: 14,
        lineHeight: 24,
      },
      large: {
        fontSize: 20,
        padding: 18,
        lineHeight: 24,
      },
    },
  },
}

// react-native-elements.d.ts -> Extend the default theme to accept sizes object
import { StyleProp, TextStyle } from 'react-native';

export type Sizes = {[index: string]: TextStyle};
export type Size = 'small' | 'medium' | 'large';

declare module 'react-native-elements' {
  export interface ButtonProps {
    sizes?: Sizes;
    size?: Size;
  }

  export interface FullTheme {
    Button: Partial<ButtonProps>;
  }
}
```

- I've used the ? operator as suggested by [this](https://stackoverflow.com/a/58401023/8582246) stackoverflow answer.
- I also used some suggestions mentioned in this [post](https://linguinecode.com/post/how-to-solve-typescript-possibly-undefined-value), using if statement to verify theme is not undefined.

**Expected behavior (Required)**

although the code works, Typescript still gives me the error mentioned above.

**Describe the bug (Required)**

the error always comes up when I try to access dynamically to some nested objects in `theme` with the bracket notation.

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    ^3.1.0     |
| react-native          |    40.0.1     |

**Comment by flyingcircle** [comment]
Did you try the nullish coalescing suggestion as well?
```
let x = foo ?? bar();
```
