### ISSUE TITLE
Accessory?

### ISSUE THREAD

**Issue by enigmablue** [react-native-elements/react-native-elements#2775]
Hi did something change for the Accessory. cant' find it as a component

And the <Avatar.Accessory> example in the components dosen't really say anything.
Maybe can update the example? Thanks!

**Comment by flyingcircle** [comment]
Is there something confusing about it? Accessory is a relatively simple component. https://reactnativeelements.com/docs/avatar#accessory It can use any props from either `Icon` or `Image` and there's an example of it in the very first block of code in `Avatar`. Can you be more specific about what you think is missing?

**Comment by enigmablue** [comment]
Sorry maybe its a stupid question. I couldn't figure out how to pass the Icon props into it. 

I would have thought it was something like
<Avatar.Accessory component = {<Icon xx/>}

The example shows {... AccessoryProps} , i was hoping for an example of this accessoryprops.

**Comment by flyingcircle** [comment]
You just pass it Icon props as if it were an Icon. The documentation says ```Receives either all Icon or Image props.``` So you can use it as if it was one or the other.

**Comment by junqdu** [comment]
@flyingcircle  Do you know if it is possible to move the accessory to the top right corner?

**Comment by enigmablue** [comment]
> You just pass it Icon props as if it were an Icon. The documentation says `Receives either all Icon or Image props.` So you can use it as if it was one or the other.

I'd kind of be honest i have no idea what 'Receives either all Icon or Image props' means.

I had no choice but to try to find other examples and now i'm doing (i think an outdated) way of
<Avatar> 
<Accessory name="add"/>
</Avatar>

But i place the style in the Accessory to move it around the Avatar.

**Comment by junqdu** [comment]
@enigmablue, just use the `Avatar.Accessory` as an Icon or Image component, e.g.

```
        <Avatar
          size={96}
          rounded
          source={{ uri: photoUrl }}
          containerStyle={styles.avatarContainer}
          onPress={() => {
            navigation.navigate(Routes.Account);
          }}
        >
          <Avatar.Accessory
            name="pencil-alt"
            type="font-awesome-5"
            size={16}
          />
        </Avatar>
```

**Comment by flyingcircle** [comment]
@junqdu Accessory is styled using absolute positioning, so you should be able to overwrite the style with top, left, right, and bottom  to change the position.

**Comment by flyingcircle** [comment]
@enigma  : @junqdu 's example is a good one showing how to use Accessory. The documentation more or less follows the same pattern as the React Native documentation. For example `TextInput` inherits  `View Props` and is stated as such here: https://reactnative.dev/docs/textinput#props 
I probably would also perfer the language of "inherits" over "receives all x props", but they mean the same thing.

**Comment by enigmablue** [comment]
> @enigma : @junqdu 's example is a good one showing how to use Accessory. The documentation more or less follows the same pattern as the React Native documentation. For example `TextInput` inherits `View Props` and is stated as such here: https://reactnative.dev/docs/textinput#props
> I probably would also perfer the language of "inherits" over "receives all x props", but they mean the same thing.

Thank you! when it says 'receive either all props of image or icon' - i think it dosen't mean it acts like one.
Maybe its still a good idea to put a real example down
