### ISSUE TITLE
removed

### ISSUE THREAD

**Issue by ericbaobao** [react-native-elements/react-native-elements#2776]
my bad, I just found out I rename the folder wrongly

**Comment by flyingcircle** [comment]
What version of Javascript do you have set in your typescript config? I suggest setting it to the latest, but I think it needs to at least be ES6.

**Comment by ericbaobao** [comment]
> What version of Javascript do you have set in your typescript config? I suggest setting it to the latest, but I think it needs to at least be ES6.

it is esnext which is the lastest one of latest js available
