### ISSUE TITLE
Typescript update

### ISSUE THREAD

**Issue by flyingcircle** [react-native-elements/react-native-elements#2777]
Here is a ticket to track the TS conversion process. please merge all PR's and work into the branch `typescript-work`. Here is the current work completed and left to be done:

- [x] Accessory
- [x] Avatar
- [x] Badge
- [x] withBadge
- [x] BottomSheet
- [x] Button
- [x] ButtonGroup
- [x] Card
- [x] Card - Subcomponents
- [x] Checkbox
- [x] config
- [x] Divider
- [x] Header
- [x] helpers
- [x] Icon
- [x] Image
- [x] Input
- [x] ListItem
- [x] ListItem - Subcomponents
- [x] Overlay
- [x] Pricing
- [x] Searchbars
- [x] Slider
- [x] SocialIcon
- [x] Text
- [x] Tile
- [x] Tooltip
- [ ] Autogen d.ts file

**Comment by flyingcircle** [comment]
@MohammedFaragallah alright I have the branch setup. I've pushed all my current work so far. So feel free to claim whatever is still left. Basically right now, it's about trying to resolve as many TS errors as possible without changing the meaning of the code itself.

So feel free to use `any` if something is too difficult to figure out. We can do future work to add stricter requirements later. And for anything really tricky using a `ts-ignore` on individual lines is acceptable too.

**Comment by MohammedFaragallah** [comment]
@flyingcircle there is a pattern that needs a solution to fix many of the current errors

```ts
const styles = {
  namedStyle: (theme: Theme) => ({
    propertyName: someStyleUsingTheme
  })
};
```

the returned values are not typed properly and may have other harmful behavior I have some ideas but most of them are not backward compatible

**Comment by flyingcircle** [comment]
@MohammedFaragallah yep, I agree. I've updated a few of them in a couple of the components such as `Button`: https://github.com/react-native-elements/react-native-elements/pull/2766/files#diff-a4a4eaf5f85ed40c14a570378492560d1ca2695473ec3cc49ae4e2e90cad68b0

Basically, I moved any of the styles that depended on arguments to the component itself and made the `styles` var into a proper `StyleSheet`. So, it requires moving things around, but I think it should hopefully behave the same as before.

**Comment by MohammedFaragallah** [comment]
I'll do the same

**Comment by MohammedFaragallah** [comment]
most of the remaining errors are related to

- trying to access a style property from `StyleProp`
- adding components as static properties to a functional component

I don't have a good way to deal with both any suggestions?

**Comment by flyingcircle** [comment]
I haven't solved those yet myself. For the static properties in functional components one, there was a way we supplied that in the index.d.ts. Let me find it...

Here: https://github.com/react-native-elements/react-native-elements/blob/next/src/index.d.ts#L221

Maybe there is some way to supply something similar in to the tsx file that allows at least the `Themed` component to have those static members? 

I really don't even understand what the issue is with the `StyleProp`. Do you have any insight to that problem?

**Comment by MohammedFaragallah** [comment]
StyleProp can be several structures(arrays/false) not just objects I think accessing style property from StyleProp may lead to some bugs and limitations and should be replaced with how the style is calculated before added to StyleProp

if a component with `containerStyle` and the implementation depends on its height/width the component should accept separate height/width props

excuse my English, Grammarly is telling me the tone isn't what I mean thank you

**Comment by flyingcircle** [comment]
@MohammedFaragallah fixed the static member issue. Pull latest.

**Comment by flyingcircle** [comment]
Decided to just ignore all of `Slider`, that's just a big old bowl of mess. Fixed a few more issues and ignored some other lines that I can't figure out. `tsc` says there's only 6 remaining errors.

**Comment by flyingcircle** [comment]
@MohammedFaragallah Thanks much! I usually like to say thank you for submissions to the repo with a token $25. Feel free to contact me on the RNE slack for details if you're interested.

**Comment by MohammedFaragallah** [comment]
@flyingcircle thank you for the offer that won't be necessary I like RNE a lot and happy to help any time
