### ISSUE TITLE
Using conditional props in Styled ReactNativeElement Components

### ISSUE THREAD

**Issue by djamesp1** [react-native-elements/react-native-elements#2778]
Wondering if it's possible to use Styled Components' conditional props functionality on RNElements components?

e.g - the styled(Button).attrs code works, but won't accept ${...} since not in backticks at that point in code?
Example code (** failing backgroundColor):

export const StyledRNEButton = styled(Button).attrs({
  buttonStyle: {
   **  backgroundColor: ${(props) => (props.highlighted ? "aqua" : "yellow")};
    height: 50,
    width: 200,
    borderRadius: 20,
  },
})``;

**Comment by flyingcircle** [comment]
I've never used "Styled Props". But I've seen people open a ticket or 2 about them. So there are other people using that library with RNE successfully, but I can't speak to your exact situation or how conditional props work. RNE components are mostly just plain RN, so most anything should work as expected with any other library. If you're having problems, I'd go asking questions from the library you're trying to implement.
