### ISSUE TITLE
CheckBox icon cannot be seen

### ISSUE THREAD

**Issue by Ritzz03** [react-native-elements/react-native-elements#2784]
I am developing an app right now and am trying to create a _CheckBox_ but I cannot see the icon...I also tried copy-pasting the exact same code from the documentation but it still didn't work...if you think there is a way to fix it please let me know...**and here is the code that I wrote to create a CheckBox**

### <CheckBox
      title='All visits completed'
      checked={this.state.allVisitsCompleted}
      checkedIcon='check'
      uncheckedIcon='close'
      onPress={() => this.setState({allVisitsCompleted:!this.state.allVisitsCompleted})}
 />

Thanks in advance!

**Comment by flyingcircle** [comment]
Your code looks right here. Your issue is probably elsewhere.

**Comment by Ritzz03** [comment]
Oh okay! Thank you!
