### ISSUE TITLE
Header shadow/elevation doesn't show on Android

### ISSUE THREAD

**Issue by pors** [react-native-elements/react-native-elements#2785]
**Explain what you did (Required)**

I try to apply a shadow/elevation to the `Header` element on Android.

**Expected behavior (Required)**

I expect to see a shadow/elevation under the Header

**Describe the bug (Required)**

I don't see a shadow/elevation on my Android phone in Expo Go.

**To Reproduce (Required)**

See Snack: https://snack.expo.io/@pors/header-elevation-problem-android

It works for Web, iOS, and also for the Android device in the Snack, but not on my Android phone;

**Screenshots (Required)**

![photo_2021-02-21 15 59 42](https://user-images.githubusercontent.com/1078320/108629089-a0e45b00-745e-11eb-9acf-881753e1421f.jpeg)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   3.2.0      |
| react-native          |   0.62.2      |

**Comment by flyingcircle** [comment]
This isn't related to RNE. Android just isn't able to show shadow all that well. So you can see the shadow in your snack if you set the elevation to something like 30-60. In Android RN, there's simply no way to set the shadow's color, size, etc. There is a library out there that creates its own shadow for android: https://github.com/879479119/react-native-shadow

Not the answer you probably wanted, but this is a RN limitation.
