### ISSUE TITLE
Avatar with an Image as Accessory

### ISSUE THREAD

**Issue by Brechard** [react-native-elements/react-native-elements#2787]
I implemented the avatar component with an accessory as explained in the docs. It mentions that we can have the props of the Image or Icon, therefore it should accept a custom image when setting it in source for the accessory but it does not load the image.
I have created a snack to show the issue:

https://snack.expo.io/@brechard/avatar-acessory

**Comment by Scbojer** [comment]
I have had the same issue and it appears that source={source} is missing from the Accessory.js file for the Image tag.

File: node_modules/react-native-elements/src/avatar/Accessory.js

You can make a work around by adding a temporary fix to line 35. Add source={source} and the code will be:

`<Image
            source={source}
            style={{
              width: size,
              height: size,
              borderRadius: size / 2,
            }}
            {...props}
          />`

**Comment by flyingcircle** [comment]
Fixed in #2793
