### ISSUE TITLE
Cannot set style on Button linearGradientProps 

### ISSUE THREAD

**Issue by CKitisak** [react-native-elements/react-native-elements#2788]
| software              | version |
| --------------------- | ------- |
| react-native-elements |3.0.1|
| react-native          |0.62.2|
|react-native-linear-gradient|2.5.6|

I would like to achieve the following `LinearGradient` configuration on the Button Component:
```
<LinearGradient
  colors={['#7733dd', '#773399']}
  start={{ x: 0, y: 0.5 }}
  end={{ x: 1, y: 0.5 }}
  style={{ flex: 1 }}
>
  <Text>My Button</Text>
</LinearGradient>
```

so I tried to put a `style` key to `linearGradientProps` but it doesn't seem to work.
```
<Button
  title="My Button"
  ViewComponent={LinearGradient}
  linearGradientProps={{
    colors: ['#7733dd', '#773399'],
    start: { x: 0, y: 0.5 },
    end: { x: 1, y: 0.5 },
    style: { flex: 1 },
  }}
/>
```

How do I style a LinearGradient of the Button component?
Thank you.

**Comment by flyingcircle** [comment]
Set the style using `buttonStyle`
