### ISSUE TITLE
prop type validation in icon color property will be failed if use PlatformColor

### ISSUE THREAD

**Issue by mr-africa** [react-native-elements/react-native-elements#2794]
**Explain what you did (Required)**

I try to use [platform color](https://reactnative.dev/docs/platformcolor) as a color for icon

**Expected behavior (Required)**

no warning messages

**Describe the bug (Required)**
Everything is working, but I get warning message:

```
Warning: Failed prop type: Invalid prop `color` of type `object` supplied to `Icon`, expected `string`.
```

**To Reproduce (Required)**

for ios:
```
import { PlatformColor } from 'react-native'

<Icon name="home" color={PlatformColor('secondaryLabel')} />
```

for android:
```
import { PlatformColor } from 'react-native'

<Icon name="home" color={PlatformColor('@android:color/background_light')} />
```

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     3.2.0    |
| react-native          |    0.63.4     |

**Comment by jeeva2812** [comment]
PR #2812 might fix this.
