### ISSUE TITLE
Rebuild Tooltip into a Tooltip2

### ISSUE THREAD

**Issue by flyingcircle** [react-native-elements/react-native-elements#2797]
`Tooltip` is the component that seems to attract the highest number of bug tickets. Part of this is that it is trying to tackle a rather difficult problem of using absolute positioning and using Layout positioning which seems to have its own problems with implementing a consistent solution.

What is needed is a replacement component that for now we will call `Tooltip2` so that we can eventually deprecate `Tooltip`/ replace it with this new `Tooltip`.

Requirements list:
Functional component
All state vars use hooks
Verify that all currently open `Tooltip` issues are resolved:  #2782, #2751, #2462, #2414, #2392, #2210
Uses latest animation API
Looks sleeker: Follow Material UI styles and pattern

**Comment by jeeva2812** [comment]
Hello, @flyingcircle I am willing to work on this issue. Can you please assign me for this?

**Comment by jeeva2812** [comment]
I am extremely sorry @flyingcircle looks like it's much more extensive work than I thought it would be. I am unassigning myself.

**Comment by abhishekkumar08** [comment]
@flyingcircle can you assign me this? And can you guide me how should I start on this, the changes would be the same like the given PR's?

**Comment by deevo-sage** [comment]
@flyingcircle can I be assigned the task. I converted the Button component to a Functional component in a recent PR and would love to do the same with The Tooltip if possible.

**Comment by flyingcircle** [comment]
This is quite a difficult task, I would say try and see how far you can get with it. It may take multiple people working on it so feel free to collaborate.

**Comment by deevo-sage** [comment]
I fail to understand why the test case is failing otherwise, both the components (Tooltip, Tooltip2) are rendering and working the same when run on an android emulator in a practice project.

**Comment by jalajcodes** [comment]
> I fail to understand why the test case is failing otherwise, both the components (Tooltip, Tooltip2) are rendering and working the same when run on an android emulator in a demo project.

Can you provide some more information about the error?

**Comment by deevo-sage** [comment]
@jalajcodes 
**  Tooltip component › does not render pointer

    TypeError: Cannot read property 'state' of null

      69 |     ).root;
      70 |     component.findAllByType(TouchableOpacity)[0].props.onPress();
    > 71 |     expect(component.instance.state.isVisible).toBe(true);
         |                               ^
      72 |     try {
      73 |       component.findByType(Triangle);
      74 |     } catch (e) {

      at Object.state (src/tooltip/__tests__/Tooltip2.js:71:31)


Test Suites: 1 failed, 33 passed, 34 total
Tests:       1 failed, 334 passed, 335 total
**
this is the failed test

**Comment by arpitBhalla** [comment]
@flyingcircle May I work on this Sir
