### ISSUE TITLE
Slider2 Component

### ISSUE THREAD

**Issue by flyingcircle** [react-native-elements/react-native-elements#2799]
We need a refactored cleaned up version of the `Slider` component.

Requirements:
1. Uses Functional Components
2. Uses hooks for all state
3. Uses up-to-date Animation API's (and native driver where possible)
4. Designed with tickets such as #2542 #15 and #2728 and resolves all open tickets against `Slider`.
5. Better design to follow more closely to Material UI

**Comment by flyingcircle** [comment]
Go for it! Are you part of the Google Summer of Code?

**Comment by nlok5923** [comment]
@flyingcircle not yet sir but i want to work in this project under Google summer of code,

**Comment by ruddi10** [comment]
@flyingcircle  kindly assign it to me

**Comment by jalajcodes** [comment]
@flyingcircle I am working on it.

**Comment by ruddi10** [comment]
@jalajcodes i have taken this issue please take some other one.

**Comment by jalajcodes** [comment]
> @jalajcodes i have taken this issue please take some other one.
The scope is pretty big, I think it would be nice to break it into smaller issues. Just a suggestion, what do you think @flyingcircle ?

**Comment by flyingcircle** [comment]
This is open source. So it's better to have 2 solutions than 1. That way we can use the best ideas from the 2 solutions and combine them. If you both want to work on it, I say that it would make for a better outcome overall.

**Comment by adarsh-technocrat** [comment]
Hello, @flyingcircle 🤝I too interested in working on this issue but it seems like already @jalajcodes  and @ruddi10  are working on this issue as this would be my first step in contributing to this repo,@flyingcircle  would you please guide me through the steps for getting started with :)

**Comment by flyingcircle** [comment]
@hetanthakkar1 did a really good job refactoring. To such a point that I think that we maybe don't need to go this route of building a completely new version: #2875
