### ISSUE TITLE
Overlay still visible after setting isVisible to false on iOS

### ISSUE THREAD

**Issue by sidhant1608** [react-native-elements/react-native-elements#2800]
**Explain what you did (Required)**

I have created a loading indicator with an Overlay component and an AcitivityIndicator component inside. I mantain a loading state on each screen that requires a Loading display and then display this Loading Component whenever needed. 

**Expected behavior (Required)**

Expected behavior is that it should be visible as long as I am providing the isVisible prop as true and should vanish as soon as it turns to false. 

**Describe the bug (Required)**

It is still visible even after I have updated the state to false and am passing isVisible as false. This only occurs in iOS. 

**To Reproduce (Required)**

It is random as far as I have found it to be and only occurs on real devices. This issue does not occur on emulators for some reason, but the App Store has rejected my app multiple times due to this. 

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Screenshots (Required)**

na

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   3.1.0      |
| react-native          |  0.62.2       |

**Comment by flyingcircle** [comment]
Sorry this is happening to you, but this doesn't really sound like an RNE bug, probably either a deeper issue with RN itself or a race condition somewhere in your code?

**Comment by ReactNativ** [comment]
```
	setTimeout(() => {
			this.setState({	 isVisible: false });
		}, 500);
```
