### ISSUE TITLE
ListItem Chevron showing typescript error

### ISSUE THREAD

**Issue by pweisensee** [react-native-elements/react-native-elements#2801]
**Explain what you did (Required)**

I'mr trying to render simply `<ListItem.Chevron />` and discover potential props for the element from Typescript hints.

**Expected behavior (Required)**

ListItem and ListItem.Chevron render normally and Typescript throws no errors or warnings. `onTextLayout` should not be a required prop.

**Describe the bug (Required)**

VS Code shows a Typescript error for `<ListItem.Chevron />` even though this comes [directly from the docs](https://reactnativeelements.com/docs/listitem#using-map-function---implemented-with-link-and-icon). This seems to happen with both TS `4.2.2` and `4.2.3`. 

The Typescript error states:
```
Property 'onTextLayout' is missing in type '{}' but required in type 'Pick<Partial<IconProps>, "style" | "onLayout" | "testID" | "accessible" | "accessibilityActions" | "accessibilityLabel" | "accessibilityRole" | "accessibilityState" | ... 62 more ... | "brand">'.ts(2741)
```

Upon adding updating the code to `<ListItem.Chevron onTextLayout={null} />`, the error goes away. But it is not supposed to need this prop. It is not clear what `onTextLayout` even does here.

**To Reproduce (Required)**

render:

```

return (
    <ListItem bottomDivider onPress={() => {}}>
        <ListItem.Content>
            <ListItem.Title>{'title'}</ListItem.Title>
        </ListItem.Content>
        <ListItem.Chevron />
    </ListItem>
);
```

**Screenshots (Required)**

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    3.3.0     |
| react-native          |     0.63.2    |
| expo          |     40.0.1    |
| typescript          |     ~4.2.2    |

```
Expo CLI 4.2.1 environment info:
  System:
    OS: macOS 10.15.7
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6821437
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  npmPackages:
    expo: ^40.0.0 => 40.0.1 
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
  npmGlobalPackages:
    expo-cli: 4.2.1
  Expo Workflow: managed
```

**Comment by hengkx** [comment]
Icon same

**Comment by hetanthakkar1** [comment]
@flyingcircle I'm pretty sure that this error is due to the icon.d.ts file generated. I made changes in those files and realized latter that these files are mentioned in gitignore section.I fixed this issue editing that d.ts file of Icon component.

**Comment by flyingcircle** [comment]
Can someone confirm if this error still exists in 3.3.2? I added some `Icon` type fixes.

**Comment by pweisensee** [comment]
This specific issue does appear to be resolved in the recent fixes, but some lingering icon and component prop type issues are lingering. I'll have to submit a separate issue for those though, so you can have a clear reproducible example. Thanks for the fixes!
