### ISSUE TITLE
Improving Pull Request template.

### ISSUE THREAD

**Issue by jeeva2812** [react-native-elements/react-native-elements#2808]
**Is your feature request related to a problem? Please Describe.**

It's difficult for reviewing a PR, as there ain't any information about which issue it fixes.

**Describe the solution you'd like**

Asking for some more details and adding a checklist will be helpful.

**Comment by abhi0504** [comment]
Hi @jeeva2812 I want to work on this issue

**Comment by jeeva2812** [comment]
I don't have the rights to assign. If the issue is accepted, the maintainers might assign you.

**Comment by jeeva2812** [comment]
PR #2816 might fix this
