### ISSUE TITLE
test: setup test to validate pull request on certain parameters 

### ISSUE THREAD

**Issue by nlok5923** [react-native-elements/react-native-elements#2810]
**Is your feature request related to a problem? Please Describe.**

Whenever any new pull request open it should be tested so that the contributor should know about what changes he needs to bring in it's pull request all it will be easy for maintainer to review pull request

**Describe the solution you'd like**

Setting up test for certain paramters like lint testing, running `npm test` on new feature added in pr.

**Describe alternatives you've considered**
setting up test is the best solutions.

**Additional context**

**Comment by flyingcircle** [comment]
We already do that. You can see that in the "CodeCov" reports that are created automatically.
