### ISSUE TITLE
404 not found: redirected to 404 page

### ISSUE THREAD

**Issue by nlok5923** [react-native-elements/react-native-elements#2811]
**Explain what you did (Required)**
 when to https://reactnativeelements.com/help/ and Clicked on link [documentation on this site](https://reactnativeelements.com/$%7BdocUrl('getting_started.html')%7D)
![image](https://user-images.githubusercontent.com/56120084/110576924-a5f81880-8187-11eb-93c1-16d28e53e088.png)

it will redirect you to 404 page

**Expected behavior (Required)**
 it should redirect to relevant page of document on this site 

**Describe the bug (Required)**
redirect to 404 page instead needed to redirect at document on this site page

**To Reproduce (Required)**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

 Go to https://reactnativeelements.com/help/
 Click on link [documentation on this site](https://reactnativeelements.com/$%7BdocUrl('getting_started.html')%7D)

**Screenshots (Required)**

click on documentation on this site link to see bug
![image](https://user-images.githubusercontent.com/56120084/110576924-a5f81880-8187-11eb-93c1-16d28e53e088.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |      not needed   |
| react-native          |      not needed   |

**Comment by nlok5923** [comment]
i would like to work on this issue if it is approved.

**Comment by jalajcodes** [comment]
@nlok5923 as you are already assigned to #2798 , I can work on it. 🙂

**Comment by nlok5923** [comment]
@jalajcodes the issue #2798 is acute quite a bigger one it will take much time to resolve it that's why I thought to resolve some smaller issues in the mean time. 😄

**Comment by HariAcidReign** [comment]
@priyanshu-219 you normally discuss here, get assigned by the mentor, and then only work on the issue...
