### ISSUE TITLE
Failed tests on running yarn test

### ISSUE THREAD

**Issue by abhishekkumar08** [react-native-elements/react-native-elements#2819]
## Description 
I ran the test by ```yarn test``` and found out there are many errors.

## Screenshots
![image](https://user-images.githubusercontent.com/59651136/110652768-ad004480-81e2-11eb-90cc-b8dbf21a8b87.png)

## Note
Can you guide me how to resolve those errors? @flyingcircle 
I searched on the web and found out that some of the failed tests may be due to wrong imports/exports.
**Refrence** https://stackoverflow.com/questions/42813342/react-createelement-type-is-invalid-expected-a-string?page=1&tab=votes#tab-top

**Comment by flyingcircle** [comment]
These are not failed tests, it's just console.error logs. You can look into fixing these console errors, but I don't know how to go about fixing it. You'd have to research the issue and try out some possible fixes.

**Comment by abhishekkumar08** [comment]
Thanks for replying, gonna look for sure.

**Comment by AkshadK7** [comment]
What about this one ?  @flyingcircle 
![image](https://user-images.githubusercontent.com/52818443/111610378-4f32b480-8801-11eb-8a8e-4dfda8a5a199.png)
