### ISSUE TITLE
bug:search bar in settings not working properly

### ISSUE THREAD

**Issue by abhishekkumar08** [react-native-elements/react-native-elements#2825]
**Explain what you did (Required)**
I was testing the react-native-elements-app. In this settings section the input search bar doesn't let me type anything. As soon as I enter anything the `onChange()` clears it.

** To Reproduce **
1. Use the react-native-elements-app
2. Go to the setting section.
3. Try to write in the search bar.

**Screenshots (Required)**

https://user-images.githubusercontent.com/59651136/110808698-42b2d700-82aa-11eb-9b4d-3ec7d31983b8.mp4

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |         |
| react-native          |         |

**Comment by abhishekkumar08** [comment]
Is it due to the app only or the react-native-element?
I'm new to the codebase still.

**Comment by tewarig** [comment]
Hi @abhishekkumar08 ,  I think you should raise this issue in https://github.com/react-native-elements/react-native-elements-app this repo. Also, react-native-elements is just a  UI Toolkit, This is just a dummy app to showcase the beauty of react-native elements. currently, this app doesn't have any functionality implemented such as login, signup, or even search.

**Comment by abhishekkumar08** [comment]
@tewarig okay thanks for the suggestion I will raise an issue there.
