### ISSUE TITLE
Opening Modal -> Invisible Layer

### ISSUE THREAD

**Issue by MichaelGorski** [react-native-elements/react-native-elements#2836]
**Explain what you did (Required)**
When opening a modal, sometimes it cause an invisible layer which makes half of the screen not clickable.

Just open an modal and edit some informations in the app
**Expected behavior (Required)**
Open Modal, Close it, use the app normal as it is.

I use rn-action-sheet and wanted to edit a information block in my app, so it should open the modal, edit some stuff, close it and everything should be fine.
**Describe the bug (Required)**
So what happens is that I open the modal, at the bottom screen of the app, it pops up, closes immediately and the bottom half of the screen is not clickable. It is like a frozen layer on it.

**To Reproduce (Required)**
I tried to reproduce it on snack but somehow it is working there. I provided a video where you can see the behaviour about what is happening.

https://user-images.githubusercontent.com/8994411/110935370-a03d3700-832f-11eb-896b-79544950c006.mov

**Screenshots (Required)**

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    ^3.2.0     |
| react-native          |    ~0.63.4    |
| expo |    40.0.1    |

**Comment by flyingcircle** [comment]
Looks like a flipper issue: https://github.com/facebook/react-native/issues/29492 try reading through that and see if it resolves your issue.
