### ISSUE TITLE
Add Radio Button as a component in React-Native-Elements

### ISSUE THREAD

**Issue by tewarig** [react-native-elements/react-native-elements#2852]
**Is your feature request related to a problem? Please Describe.**
Currently, React Native Elements don't have a Radio Button as a component. Also, react-native don't have a Radio button component. Now as a  UI Library  React Native Elements should have Radio Button Component so developers can directly import it when they need it instead of hardcoding it every time. 

**Describe the solution you'd like**
React native elements should a Radio Button as a Components so developers using React Native elements would be able to directly import it. 

**Additional context**
I have designed a mock-up of the Radio Buttons in Figma.  
https://www.figma.com/file/Cn01bhyo5GHdz8CR1pggPr/React-Native-Elements?node-id=0%3A1

I would like to work on this feature please assign it to me. 

![Group 5](https://user-images.githubusercontent.com/54894783/111062376-69515780-84ce-11eb-8df0-06ab1bda4f6a.png)
![Group 14](https://user-images.githubusercontent.com/54894783/111065137-344d0100-84de-11eb-8536-06072fef7a3b.png)
![Group 15](https://user-images.githubusercontent.com/54894783/111065153-45960d80-84de-11eb-8ebd-be4dd97d596e.png)
![Group 16](https://user-images.githubusercontent.com/54894783/111065162-5050a280-84de-11eb-97fa-ef6c4df22009.png)

**Comment by tewarig** [comment]
I was going through docs... just realized there is a checkbox component.. we can achieve same result with that... shall i go ahead with this? 😅

**Comment by flyingcircle** [comment]
Yeah I'm not sure that it would add too much. It would just be making a "round" checkbox. Good idea. Keep the idea juices flowing ;P

**Comment by tewarig** [comment]
sure I would be re-designing and suggesting more components.

**Comment by stfenjobs** [comment]
> 是的，我不确定会增加太多。它将仅是一个“圆形”复选框。好主意。保持想法不断流动； P

how to make  a Radio Group if i use CheckBox

**Comment by stfenjobs** [comment]
@flyingcircle 

can you make a Radio Group ?  thank you very much

ref:
https://wix.github.io/react-native-ui-lib/docs/RadioGroup/
https://callstack.github.io/react-native-paper/radio-button-group.html
