### ISSUE TITLE
Create a Toast component

### ISSUE THREAD

**Issue by maxikgreat** [react-native-elements/react-native-elements#2854]
# Title

Creating a new **Toast UI** component.

# Motivation

As I have been developing different apps for different purposes and have been used a wide specter of UI libraries for pretty interfaces and UX, in most cases, this type of component was really helpful to provide a convenient way to show information and make the interface more friendly for end-user.

# Propose

I think the better way to implement that functionality is to add hook ```useToast``` with basic function (and probably the only one 😉 ) - ```show```

The additional configuration may be passed throw the third parameter of that function. E.g 
```show('Ooops. Something went wrong', 'error', {config})```

or it can be globally configured with ThemeProvider:

```
<ThemeProvider
    theme={
        Toast:  {
            position: 'top' | 'bottom',
            backgroundColor: 'red',
        }
    }
>

</ThemeProvider>
```

# Design Details

The design must be fittable to the rest of the already existing components and looks similar to them.

# Inpired by 

- [react-native-paper](https://callstack.github.io/react-native-paper/index.html)
- [react-toastify](https://www.npmjs.com/package/react-toastify)
- [react-native-base](https://nativebase.io/)

So what we're waiting for? 😜

**Comment by abhishekkumar08** [comment]
The idea looks really nice, looking forward to it.

**Comment by flyingcircle** [comment]
It seems to me that this API is a little too complicated for this library. This library is a simple set of base components that are easily extendable. Compare this to the Compare it to the API here: https://www.npmjs.com/package/react-native-toast-message where the API, setup, styling, and extendibility are all readily apparent and easy to understand. I don't think we want to overly complicate this library.
