### ISSUE TITLE
On the RTL devices( at the rtl devices, it is not moving from left to right, only from left to right

### ISSUE THREAD

**Issue by wangtiger317** [react-native-elements/react-native-elements#2857]
**Explain what you did (Required)**

**Expected behavior (Required)**

**Describe the bug (Required)**

**To Reproduce (Required)**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Screenshots (Required)**

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |         |
| react-native          |         |

**Comment by wangtiger317** [comment]
I hope that the team fix that issue

**Comment by flyingcircle** [comment]
This is a very poorly written Issue. There is not enough detail here to do anything with it.

**Comment by wangtiger317** [comment]
In  that case,  which library do you use?

**Comment by wangtiger317** [comment]
![image](https://user-images.githubusercontent.com/54022798/111276990-f3e8a280-8605-11eb-80ed-2541761c64c4.png)
it is working only like on the ltr devies. when move it to left, it dont' move any more at minvalue
