### ISSUE TITLE
Development (contribution) npm install is not working

### ISSUE THREAD

**Issue by Aymer-el** [react-native-elements/react-native-elements#2872]
Just to run the project as mention in the guideline of contribution

Running the app

**Describe the bug (Required)**
A command is not recogized by my system and cannot go until finishing the installation of node_modules. A screenshot will be, in my opinion, more useful: 

**To Reproduce (Required)**

This is previous to snack.io, since it is during npm installation

**Screenshots (Required)**
![image](https://user-images.githubusercontent.com/32161241/111510493-1ede0e00-874e-11eb-903b-ed47c944d864.png)

**Your Environment (Required):**

OS                         windows 10 Home
| software              | version |
https://github.com/react-native-elements/react-native-elements-app
branch origin/next

**Comment by arpitBhalla** [comment]
```npm install --global yarn``` 
```yarn install```

**Comment by Aymer-el** [comment]
Thanks you for help. yes, still npm install was not working. Just mentionning

**Comment by arpitBhalla** [comment]
I don't think its a bug, its npm's weakness
