### ISSUE TITLE
Create a Custom Switch Component for the package

### ISSUE THREAD

**Issue by khushal87** [react-native-elements/react-native-elements#2873]
**Is your feature request related to a problem? Please Describe.**
Currently we don't have a Switch Component in the package, So I would like to work on the same and add it.

**Describe the solution you'd like**
I would like to create a custom switch component for the package. This will increase user engagement and preference of the package

**Describe alternatives you've considered**
The native Switch would be extended to serve our purpose and theme. So that can be an alternative.
Others:
- React native paper etc.

**Additional context**
None yet, but it is planned to be bug free and target a great usability over time.

**Comment by khushal87** [comment]
@flyingcircle @pranshuchittora @Monte9 Can I work on this issue?

**Comment by Abhishek765** [comment]
@khushal87 can you share the link of the package through which you found that the switch component was not present so that I can also cross-check whether the component I am planning to add is already present or not?
