### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by rajat2502** [react-native-elements/react-native-elements#2874]
**Describe the solution you'd like**

A markdown file with contribution guidelines to the project repository's root. This will help beginners in setting up and contributing to the project easily.

**Comment by arpitBhalla** [comment]
https://reactnativeelements.com/docs/contributing/

**Comment by rajat2502** [comment]
Hey @arpitBhalla, I also noticed that there was a page in the docs entirely for contributions guidelines, Maybe in the markdown file, we can just place the link so that people can find the guidelines easily?

**Comment by snitin315** [comment]
https://github.com/react-native-elements/react-native-elements/blob/next/.github/CONTRIBUTING.MD

**Comment by snitin315** [comment]
Already present.

**Comment by rajat2502** [comment]
I didn't notice it, thanks for mentioning. Closing the issue.
