### ISSUE TITLE
SearchBar typescript props missing

### ISSUE THREAD

**Issue by kickbk** [react-native-elements/react-native-elements#2878]
I import SearchBar and need to create a ref for it:
```
import { SearchBar, SearchBarProps } from 'react-native-elements';
const searchFieldRef = useRef<SearchBarProps>(null);
const blurSearch = useCallback(() => {
   searchFieldRef.current?.blur();
  }, [searchFieldRef]);

<SearchBar ref={searchFieldRef} onPress={blurSearch} ...
```
I get a typescript error on:
1. `searchFieldRef.current?.blur();` - it doesn't know about blur.
2. `ref={searchFieldRef}` on the SearchField itself

The first issue I can, in an ugly way, fix by adding the methods to the typescript definition like so:

```
type MissingProps = {
  focus: () => void;
  blur: () => void;
  clear: () => void;
  cancel: () => void;
}
const searchFieldRef = useRef<SearchBarProps & MissingProps>(null);
```

I prefer this to be handled correctly of course.
But one thing I am not sure how to fix is `ref={searchFieldRef}`

Could you please advise how to properly import the typescript definition of this component?
Thanks!

**Comment by darrylyoung** [comment]
There are other issues with the `SearchBar` types, too. For example, the [docs](https://reactnativeelements.com/docs/searchbar#props) say I can use `placeholder`, for example, but I'm getting a warning that it's not a valid prop. Looking through the types shipped, it looks like this is missing.

The codebase only just transitioned to TypeScript so I'm guessing it's just a small bug that got through and one that'll be fixed soon. The same for your case, too.

**Comment by Aymer-el** [comment]
Hello,

First I would like to say I am new here. So, I might be totally out of the subject :).

Regarding your questions @darrylyoung I had a discussion about it with @flyingcircle. 

Identification issue: 
I think our issue is just typing as you said too. 
It is true only our component has the action typed (blur etc) and not the type itself. 

Action: 
I can place the type (blur, focus, clear, render, cancel) on the SearchBarProps. as well as adding the placeholder and value props (of type string).

Thanks you

**Comment by darrylyoung** [comment]
Hi, @Aymer-el. 👋 

Thanks for the message.Yeah, that sounds good. I'm not sure internally how the `Searchbar` component is written – that is, if it's just a wrapper around a `TextInput`, for example – but I also noticed that it doesn't accept any accessibility props such as `accessibilityRole="search"` either.

**Comment by Aymer-el** [comment]
Here is a small commit proposition: https://github.com/Aymer-el/react-native-elements/commit/3c4e0bd6c72d51a0c29d66ccb7672cf06eaafc82

**Concerning accessibility**
Issue detection:
It is a wrapper around a `Input` along with `Text` elements. I have seen an accessibility, hard written, mentioned in Ios but not for android.

Potential Fix:
- Typing the component with AccessibilityProps of Text so that it can read voice
- Providing the props to the wrapped `text`
Nevertheless, I don't know if it will handle the full feature of accessibility (because it is not a `TextInput` that is wrapped.
:)

**Comment by dancixx** [comment]
Hi, typedef of placeholder doesnt exists too.

**Comment by khushal87** [comment]
> There are other issues with the `SearchBar` types, too. For example, the [docs](https://reactnativeelements.com/docs/searchbar#props) say I can use `placeholder`, for example, but I'm getting a warning that it's not a valid prop. Looking through the types shipped, it looks like this is missing.
> 
> The codebase only just transitioned to TypeScript so I'm guessing it's just a small bug that got through and one that'll be fixed soon. The same for your case, too.

I have raised the PR for the same https://github.com/react-native-elements/react-native-elements/pull/2892 this will be solved soon. Thank you.

**Comment by mr-ryan-james** [comment]
> I import SearchBar and need to create a ref for it:
> 
> ```
> import { SearchBar, SearchBarProps } from 'react-native-elements';
> const searchFieldRef = useRef<SearchBarProps>(null);
> const blurSearch = useCallback(() => {
>    searchFieldRef.current?.blur();
>   }, [searchFieldRef]);
> 
> <SearchBar ref={searchFieldRef} onPress={blurSearch} ...
> ```
> 
> I get a typescript error on:
> 
> 1. `searchFieldRef.current?.blur();` - it doesn't know about blur.
> 2. `ref={searchFieldRef}` on the SearchField itself
> 
> The first issue I can, in an ugly way, fix by adding the methods to the typescript definition like so:
> 
> ```
> type MissingProps = {
>   focus: () => void;
>   blur: () => void;
>   clear: () => void;
>   cancel: () => void;
> }
> const searchFieldRef = useRef<SearchBarProps & MissingProps>(null);
> ```
> 
> I prefer this to be handled correctly of course.
> But one thing I am not sure how to fix is `ref={searchFieldRef}`
> 
> Could you please advise how to properly import the typescript definition of this component?
> Thanks!

This is super hacky, but I was able to fix the second issue by creating a "temp" component that just accepts any Props. If someone wants to add better type definitions, they are welcome to do so.

```
const SearchBarTempFix = (props) => {
  return <SearchBar {...props} />;
};

```

**Comment by singhakshita** [comment]
if i create isBlurred , isClear, isfocused , props and that would be assigned value true or false , on the actions of event listeners ,will that solve the issue ?

**Comment by flyingcircle** [comment]
I'm wondering if this is being caused by the `withTheme` typing. Either way here is a workaround to the original example code:
```typescript
import { SearchBar, SearchBarProps } from 'react-native-elements';
const searchFieldRef = useRef<TextInput>(null);
const blurSearch = useCallback(() => {
   searchFieldRef.current.blur();
  }, [searchFieldRef]);

<SearchBar platform='default' ref={searchFieldRef} onBlur={blurSearch} />
```

There is a small error in the TS that I see that `placeholder` needs to be optional, but that's a small side issue. We could export a separate `SearchBarClass` that isn't wrapped with `withTheme` and I think that would work, but that seems to be a dirty fix.

**Comment by tidusjar** [comment]
What about the missing `value` prop?
I would have thought this prop type would have been pretty key as it's required for the searchbar to work correctly

**Comment by KaterinaLupacheva** [comment]
> What about the missing `value` prop?
> I would have thought this prop type would have been pretty key as it's required for the searchbar to work correctly

Same here. Got TypeScript error - Property 'value' does not exist

**Comment by tidusjar** [comment]
We have now lost the `onChangeText` prop, so this change has introduced a breaking change

**Comment by arpitBhalla** [comment]
> We have now lost the `onChangeText` prop, so this change has introduced a breaking change

Can You again confirm Please😃

**Comment by arpitBhalla** [comment]
Hey @tidusjar Its still working for me
