### ISSUE TITLE
FAB and Speed Dial Components

### ISSUE THREAD

**Issue by arpitBhalla** [react-native-elements/react-native-elements#2880]
**Describe the solution you'd like**

https://material.io/components/buttons-floating-action-button

**Comment by rajat2502** [comment]
Hey @arpitBhalla, I would like to work on this one!

**Comment by arpitBhalla** [comment]
@rajat2502 😃 I am near to completion

**Comment by arpitBhalla** [comment]
Thanks for asking brother😄

**Comment by rajat2502** [comment]
Oh okay, I saw that it wasn't assigned to anyone :)

**Comment by arpitBhalla** [comment]
😅 Only maintainer can assign
