### ISSUE TITLE
Safe Area Provider with Wix Navigation

### ISSUE THREAD

**Issue by MaganAnkur** [react-native-elements/react-native-elements#2884]
I am using wix react native navigation and there is no app function in it

Navigation.events().registerAppLaunchedListener(() => {
  startApp();
});
How should I wrap the app with SafeAreaProvider

**Comment by flyingcircle** [comment]
Looks like there are some people that have done something like this: https://github.com/wix/react-native-navigation/issues/6092 Looks like you need to wrap your screens in it.
