### ISSUE TITLE
Missing type definition files for several components

### ISSUE THREAD

**Issue by khushal87** [react-native-elements/react-native-elements#2893]
**Explain what you did (Required)**
Looking at the codebase there are several components which miss the type definitions for the props passed in the components. I would like to add them and therefore the code will be clean with time.

**Expected behavior (Required)**
Type definitions files for the components should be present under `.d.ts` extensions and this will increase code flexibility.

**Describe the bug (Required)**
Missing type definitions files for the components.

**To Reproduce (Required)**
Look at the folders of the component's code in src.
We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Components**

- [ ] Avatar
- [ ] Badge
- [ ] BottomSheet
- [ ] Buttons
- [ ] Card
- [ ] Checkbox
- [ ] Divider
- [ ] Header
- [ ] Icons
- [ ] Image
- [ ] Input
- [ ] LinearProgress
- [ ] List
- [ ] Overlay
- [ ] Pricing
- [ ] Searchbar
- [ ] Slider
- [ ] SocialIcon
- [ ] Switch
- [ ] Text
- [ ] Tile
- [ ] Tooltip

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     3.3.2    |
| react-native          |     0.63.2     |

**Comment by khushal87** [comment]
@pranshuchittora @flyingcircle Can I start working on it?

**Comment by arpitBhalla** [comment]
@khushal87 it's automatically generated after ```tsc```

**Comment by khushal87** [comment]
Yes but those definitions must also be present in the folder of components, This is an ideal architecture and the types would be described with description they have. @arpitBhalla . That's my suggestion, though I need review for the same from @flyingcircle and others.

**Comment by flyingcircle** [comment]
@arpitBhalla is correct. The `d.ts` files are auto built but not added to the repo. This is standard practice. You can see what the `d.ts` look like by building them with `tsc`.

**Comment by khushal87** [comment]
Okay, sir. Thank you for your views over it. Yes, I have seen those generated with the ` tsc ` command. @flyingcircle
