### ISSUE TITLE
New Rating compoment

### ISSUE THREAD

**Issue by hetanthakkar1** [react-native-elements/react-native-elements#2899]
Currently, we are using another library for our rating component. Can we replace that if I come up with a rating component so that we don't need to use that library!?

**Comment by flyingcircle** [comment]
I'm not sure I really see a strong point. Is there a bug in the rating library that means needing to replace it?

**Comment by hetanthakkar1** [comment]
we are importing that from other UI library so I thought reducing external dependency might be a priority

**Comment by flyingcircle** [comment]
It doesn't really change the amount of code. If in the future we need to fork that library for some reason to fix something, we can.
