### ISSUE TITLE
Create New Counter Component

### ISSUE THREAD

**Issue by khushal87** [react-native-elements/react-native-elements#2904]
**Is your feature request related to a problem? Please Describe.**
Currently, there is no Counter component in our package. Having it will encourage user engagement with the package.

**Describe the solution you'd like**
Create a counter component with a plus and minus button and which would increase or decrease on click events of the button. 

**Describe alternatives you've considered**
I have considered a UI similar to this
![counter](https://user-images.githubusercontent.com/39884168/112342290-1b1b3000-8ce8-11eb-9752-7410d11b88e2.PNG)

**Additional context**
NA

**Comment by khushal87** [comment]
@flyingcircle Can i work on it?

**Comment by pranshuchittora** [comment]
1. I think this is not required as this seems to be very easily accomplished by anyone.
2. This is not a building block / composable component.
3. Personally I never came across any requirement for this component.

**Comment by khushal87** [comment]
People generally tend to use packages for the same so I thought if we have the same here, users can take it from here. Talking about the counter, we use it in the cart feature of e-commerce or it can have other users too. @pranshuchittora

**Comment by flyingcircle** [comment]
I generally agree with @pranshuchittora on this one. This is like the "hello world" of learning react hooks. And the use case is quite limited. I appreciate the thought, but I think we'll pass on this one.

**Comment by khushal87** [comment]
Okay. Thank you @flyingcircle
