### ISSUE TITLE
Proposal for new footer bar 

### ISSUE THREAD

**Issue by HariAcidReign** [react-native-elements/react-native-elements#2918]
**Is your feature request related to a problem? Please Describe.**

The React Native Elements UI Toolkit currently lacks a Footer Menu component. However, an image of this component exists in the banner image in the README.md section of this project repository. 

![image](https://user-images.githubusercontent.com/58134096/112576982-71d45700-8e19-11eb-93c0-cef1883027d3.png)

**Describe the solution you'd like**

Create a footer menu component that will be sticky on the scroll as well. This ensures 2 things:
- User can see the menu options at all times
- Easier navigation than a hamburger menu (which is harder to reach than a footer menu on a standard smartphone screen)

**Describe alternatives you've considered**

There are no alternatives. This is a completely new component that has not been created yet. 

**Additional context**

The final product will look exactly the same as the image I have posted on top. The end user-developer can change the text and icons to better suit their requirements

**_PS: After the creation of this component, I will be immediately adding the same into the RNE-app as well._**

**Comment by flyingcircle** [comment]
That footer in the image I believe came from the React-Navigation lib.

**Comment by HariAcidReign** [comment]
@flyingcircle Alright, but would it be of any value to the project if I added an RNE component of the footer bar (using only RNE elements and no external dependencies)? Is that something that you might be interested in seeing?

**Comment by flyingcircle** [comment]
Hmm. Well at least with most app designs I've seen, the footer is usually used to move between screens which does seem like it would fit with `react-navigation` more. My personal opinion is that is clutters the screen a bit too much, but I guess sometimes it's unavoidable. I'm wondering what do you think it would look like beyond just a view at the bottom that a dev can stick things in? It's not quite as standard as the `Header` bar typically is.

**Comment by arpitBhalla** [comment]
@HariAcidReign isn't it a tab Bar sticked to bottom?

**Comment by pranshuchittora** [comment]
I agree with @flyingcircle 
The goal behind RNE is to provide building blocks for any app. The footer seems to be more inclined towards navigation & anyone can make this using the base component like icon button or button group from the RNE backed by some navigation logic.

**Comment by HariAcidReign** [comment]
@flyingcircle @pranshuchittora Absolutely! The Footer bar is normally used to navigate screens and the library we used in RNE-app for the sidebar can be used to make a standard sticky footer bar. So me making that is redundant.
But what if, I want a footer bar (which by default is hidden) that I can swipe up from the bottom to see different functionalities or CTA buttons? This is as far as I can see, not a component in `React-Navigation` so maybe we can consider building one for RNE?
I'll attach a sample bar (from Discord) for reference. I believe this way, we can attach much more functionalities than a standard footer bar + keep it from obstructing the view, so it's a win-win. What do you guys think?

![image](https://user-images.githubusercontent.com/58134096/112713764-d1eff980-8efc-11eb-9571-7db4477d8093.png)

**Comment by pranshuchittora** [comment]
This can be achieved with Gesture Handler and Reanimated. Pls try to understand the scope of the project.

**Comment by HariAcidReign** [comment]
Very well. I'll close this issue and work on something else

**Comment by HariAcidReign** [comment]
@flyingcircle @pranshuchittora As of now, I don't think a footer bar can be used for anything other than Navi and showing additional features. However, if there is any other variation of this feature that you feel can benefit this project, kindly let me know. I'll be happy to work on it 🙌🏻
