### ISSUE TITLE
Tooltip closeOnlyOnBackdropPress effect is not working

### ISSUE THREAD

**Issue by panda919** [react-native-elements/react-native-elements#2923]
**Explain what you did (Required)**

 I have been used tooltip with  closeOnlyOnBackdropPress .

**Expected behavior (Required)**

Tooltip has to dismiss when only overlay text is clicked

**Describe the bug (Required)**

But. tootlip overlay (popover) UI is invisible when click tooltip.
**To Reproduce (Required)**

`
   <SafeAreaView style={styles.container}>
            <Text>Open up App.js to start working on your app!</Text>
            <View style={styles.modalContainer}>
                <Tooltip
                    popover={<Text>Hello world</Text>}
                    closeOnlyOnBackdropPress={true}
                    skipAndroidStatusBar={true}
                    toggleAction="onLongPress"
                    backgroundColor="white">
                    <Text style={styles.text}>Hello World</Text>
                </Tooltip>
            </View>
        </SafeAreaView>
`
`container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalContainer: {
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    },
    text: {
        color: 'black',
    },`

**Screenshots (Required)**
init screen
![image](https://user-images.githubusercontent.com/25161426/112719421-e3a0c380-8f33-11eb-9781-1759e2d39507.png)
when click "hello world" text
![image](https://user-images.githubusercontent.com/25161426/112719430-f5826680-8f33-11eb-9223-97ba39b43c9d.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  3.3.2       |
| react-native          |  0.63.4       |

**Comment by panda919** [comment]
Means I have to instal react-native-element@next version?

**Comment by arpitBhalla** [comment]
Please wait till maintainer review the code 😅

**Comment by harisbaig100** [comment]
@panda919 install version 2.3.0, that will fix your issue

**Comment by arpitBhalla** [comment]
Closing this issue after a prolonged period of inactivity. If this issue is still present in the latest release, please feel free to create a new issue with up-to-date information.
