### ISSUE TITLE
Strict TypeScript 

### ISSUE THREAD

**Issue by flyingcircle** [react-native-elements/react-native-elements#2929]
A good goal for all TS libraries is to get to a point where we can turn on 'strict' mode in the `ts.config`. If you do so as of the time I'm writing this ticket, it shows that there about 170 errors when 'strict' mode has been turned on.

So, there's a lot of possible work here so no need to submit a PR solving everything (but please don't solve just 1 thing either. Try to solve a good chunk before submitting a PR). Don't submit a PR that actually turns on 'strict' mode, just the fixes. Once everything has been fixed, then we'll turn it on.

To turn it on temporarily change the following line in the `tsconfig.json` to `true`
```
"strict": false
```

then run `tsc`. And you should see the additional errors that pop up.

**Comment by Yunicorn228** [comment]
@flyingcircle Hi Jeremy, I'm trying to participate in this project in the Google Summer of code, however, I can not join the slack channel, I'm fairly new to open source projects and really need some help.

**Comment by abdulsamad** [comment]
Hi Jeremy, Is this issue resolved or can I give it a try? Is somebody working on it?
@flyingcircle
