### ISSUE TITLE
npm install causes error unable to resolve dependency tree

### ISSUE THREAD

**Issue by Dynelc** [react-native-elements/react-native-elements#2934]
I forked and cloned react-native-elements. But when i tried to install package with npm install it causes error unable to resolve dependency tree.
npm version on my machine: 7.6.1

**Comment by arpitBhalla** [comment]
do `yarn install`

**Comment by Dynelc** [comment]
yes i did installed with yarn

**Comment by Enigmage** [comment]
@Dynelc getting the same issue on npm version `7.6.5`. This has do with new [peer dependency management](https://blog.logrocket.com/whats-new-in-npm-v7/) in npm 7. A work around to this, if you don't want to downgrade your npm version, is to install deps with `--legacy-peer-deps` flag, like:

``` $ npm install --legacy-peer-deps```

This makes npm 7 behave like legacy npm versions(4 to 6). Tested this on my machine, it works. But this is only a temporary fix, changes will have to be made upstream to make react-native-elements compatible with npm 7.

**Comment by fukemy** [comment]
i installed success 
```
THG:VedaxLink thehe$ npm install @rneui/themed @rneui/base --legacy-peer-deps

added 10 packages, removed 28 packages, and audited 1304 packages in 4s

94 packages are looking for funding
  run `npm fund` for details

7 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

but get many warn, then still got error when import from 'react-native-elements'. please help

```
> 10 | import { List, ListItem } from 'react-native-elements';
 react-native-elements could not be found within the project or in these directories:
  node_modules

```
