### ISSUE TITLE
Proposal for Video Component 

### ISSUE THREAD

**Issue by HariAcidReign** [react-native-elements/react-native-elements#2938]
**Is your feature request related to a problem? Please Describe.**

There is currently no `Video` component in RNE. An example of what this component is: 
https://shoutem.github.io/docs/ui-toolkit/components/video

**Describe the solution you'd like**

When the link to the video and other dimensions are passed as props, it should be able to render the video properly in Webview.
This is what I want to implement using RNE, as it is a much more popular library than the one above, and also such a component has a lot of use cases, especially for media-based apps. 

**Additional context**

Do let me know if this is something that will benefit the product, and if yes, I am willing to implement it here, make the demo in RNE-App, and write documentation as well. 🙌🏻

**Comment by flyingcircle** [comment]
I don't think this is necessary. Its a pretty specific widget and doesn't really have many needed themable pieces.
