### ISSUE TITLE
New Component List Accordion

### ISSUE THREAD

**Issue by arpitBhalla** [react-native-elements/react-native-elements#2940]
*Is your feature request related to a problem? Please Describe.*
List Accordion 
An expansion panel is a lightweight container that may either stand alone or be connected to a larger surface, such as a card.

They may be used for a variety of tasks, such as:
- To edit a setting
- To create a tool for ad campaigns

>  **<ListItem.Accordion/>**

Reference
- https://callstack.github.io/react-native-paper/list-accordion-group.html
- https://material-ui.com/components/accordion/#accordion
- https://material.io/archive/guidelines/components/expansion-panels.html

 <img src='https://callstack.github.io/react-native-paper/screenshots/list-accordion-group.png'/>
<img src=https://callstack.github.io/react-native-paper/screenshots/list-accordion-1.png>

*Describe alternatives you've considered*

*Additional context*

Stateless Component is required

**Comment by arpitBhalla** [comment]
@pranshuchittora  May I work on this?

**Comment by flyingcircle** [comment]
I think that is being done here: https://github.com/react-native-elements/react-native-elements/pull/2944

**Comment by arpitBhalla** [comment]
@flyingcircle it's different,

**Comment by arpitBhalla** [comment]
@flyingcircle

**Comment by arpitBhalla** [comment]
@flyingcircle I am near to completion, can you check my approch I  making subcomponent as `ListItem.Accordion`

**Comment by flyingcircle** [comment]
@arpitBhalla If you can accomplish the same thing as that other PR but with a simpler method like a `ListItem.Accordion` subcomponent, that would be very much preferable to entire new set of code in the Dropdown PR.
