### ISSUE TITLE
Feature Request: Discord and Slack Icons

### ISSUE THREAD

**Issue by CIPHERTron** [react-native-elements/react-native-elements#2941]
**Is your feature request related to a problem? Please Describe.**

Add Discord and Slack Icons to the set of icons list. I feel these icons are necessary because nowadays, most of the communities, organizations have their workspace either in discord or slack. I personally have felt the need for these two particular icons. Thus, I was planning to add these two icons to the icon list.

**Describe the solution you'd like**

I searched for the two icons at Feather Icons, antdesign, font awesome, and material icons pack but not each and every pack has got these two icons except for font awesome. Thus, I propose we take from the Font-Awesome icon pack. I'm attaching the links below.

https://fontawesome.com/icons/discord?style=brands
https://fontawesome.com/icons/slack?style=brands

**Describe alternatives you've considered**

The only alternative that I've considered is [Material Design Icons](https://materialdesignicons.com/). 

**Additional context**

![Screenshot 2021-04-03 175933](https://user-images.githubusercontent.com/56754747/113478436-71396180-94a6-11eb-9e13-13eb7cdab6f8.png)

![Screenshot 2021-04-03 175827](https://user-images.githubusercontent.com/56754747/113478429-667ecc80-94a6-11eb-8817-6251eea0493c.png)

**Comment by flyingcircle** [comment]
I'm not sure what you're asking for here. It sounds like you found the icons that you want?

**Comment by CIPHERTron** [comment]
@flyingcircle  Since the RNE app doesn't have the above-mentioned icons, I was proposing that we can add those icons to the RNE app.

**Comment by flyingcircle** [comment]
RNE supports all the icons listed here: https://oblador.github.io/react-native-vector-icons/ . So again, not sure what you mean by RNE not having them. You can already accomplish this with the RNE `Icon` component: https://reactnativeelements.com/docs/icon
