### ISSUE TITLE
Support for referencing branch on github instead of npm as the package version

### ISSUE THREAD

**Issue by pranshuchittora** [react-native-elements/react-native-elements#2942]
**Description**
Until `v3` RNE supports direct reference to the git branch as the dependency.
``` json
-> package.json

"dependencies": {
  "react-native-elements": "https://github.com/react-native-elements/react-native-elements#next",
}
```

With the current version (next) it is not possible to directly reference the branch as the new source is written in TS and hence require an additional build step in order to compatible with all the RN projects / apps.

**Possible Approach**
One of the possible ways is to build and deploy the code in CI and push it back to a new branch say `dist`

Let's discuss 📢

**Comment by pranshuchittora** [comment]
Open to different approaches / implementations

**Comment by flyingcircle** [comment]
This was done in the RNE-app by adding a `postinstall` step: https://github.com/react-native-elements/react-native-elements-app/blob/next/package.json#L21

**Comment by pranshuchittora** [comment]
1. This will work only in UNIX based devices.
2. The idea is that anyone can reference the dist branch from the GitHub without any postinstall build step

**Comment by pranshuchittora** [comment]
With the changes in #2943 
On pushing to the next branch it runs the build step in CI and pushes the generated build to the dist branch
