### ISSUE TITLE
Proposal for Calendar and Time Components 

### ISSUE THREAD

**Issue by HariAcidReign** [react-native-elements/react-native-elements#2947]
**Is your feature request related to a problem? Please Describe.**

A calendar component can be used to select a Date/Month/Year value with ease, and the time component can be used to select the Hour: Minute: Second value with ease. 

**Describe the solution you'd like**

https://material.io/components/time-pickers/android
https://material.io/components/date-pickers

**Additional context**

Open to alternatives and feedback, and willing to implement on both RNE and RNE-app 🙌🏻

**Comment by flyingcircle** [comment]
This already exists in this package: https://github.com/react-native-datetimepicker/datetimepicker

**Comment by HariAcidReign** [comment]
I think the Wix component is a better option i.e. https://github.com/react-native-elements/react-native-elements/issues/214
So, closing this makes sense. Thank you!
