### ISSUE TITLE
Proposal For QR Code Scanner

### ISSUE THREAD

**Issue by PrathamSinghSaluja** [react-native-elements/react-native-elements#2948]
**Is your feature request related to a problem? Please Describe.**

A QR Code Scanner can help in scanning the code and get information attached with the QR Code. It would be of great help.

**Describe the solution you'd like**

https://reactnativeexample.com/tag/qr-code/

**Describe alternatives you've considered**

Open to alternatives and feedback, and willing to implement on both RNE and RNE-app 

**Additional context**

**Comment by HariAcidReign** [comment]
A QR scanner is not a UI element, it is more of a standalone functionality. Apart from the camera module, there is not much front end to it. Also, there are already many libraries that integrate this functionality with a React Native app, so I don't know why there is a need to create that functionality here. Just my two cents 💰

**Comment by PrathamSinghSaluja** [comment]
Not Frontend but we can connect backend with it and make our own QR Codes and can add a functionality to the app. It can lead to opportunities.

**Comment by pranshuchittora** [comment]
@PrathamSinghSaluja thanks for the idea, but this is not related to the UI component library.
