### ISSUE TITLE
Badge property 'textStyle' has type ViewStyle instead of TextStyle

### ISSUE THREAD

**Issue by joaomrcsmartins** [react-native-elements/react-native-elements#2954]
**Explain what you did (Required)**

I used several Badges to work as category tags. 

**Expected behavior (Required)**

I wanted to change the text color using *textStyle* attribute:
```ts
<Badge textStyle={{color: 'white'}} />
```

**Describe the bug (Required)**

An error shows because the *textStyle* type is not TextStyle, but ViewStyle

**To Reproduce (Required)**

Just use a Badge and try to pass TextStyle attributes in the *textStyle* property.
**Screenshots (Required)**

Docs: 

![docs](https://i.imgur.com/cBluq4T.png)

Package Code:

![package](https://i.imgur.com/n4siXxu.png)

Error Example:

![error](https://i.imgur.com/i7Tptu4.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    3.3.2     |
| react-native          |    0.64.0     |

**Comment by joaomrcsmartins** [comment]
I just realized that what I want can be achieved by simply doing the styling on the Text component I have for the value. But still, there is a mismatch between the docs and the package code, so I won't close it atm

**Comment by khushal87** [comment]
Can I pick up this issue and solve it? @joaomrcsmartins

**Comment by joaomrcsmartins** [comment]
Yes, of course :smile:

**Comment by mpochron** [comment]
I am having issue too with TextStyle.

**Comment by khushal87** [comment]
@mpochron will be fixed soon
