### ISSUE TITLE
Input style={{textAlign:center}} makes cursor go to the right

### ISSUE THREAD

**Issue by Aparus** [react-native-elements/react-native-elements#2955]
![photo5445356866302489425](https://user-images.githubusercontent.com/1222611/114272741-05b04080-9a20-11eb-8fde-430686b11789.jpg)

**Your Environment (Required):**

Expo Go (android)

| software              | version |
| --------------------- | ------- |
| react-native-elements |   3.3.2      |
| react-native          |     0.63.2    |

**Comment by arpitBhalla** [comment]
![Screenshot_1618066503](https://user-images.githubusercontent.com/55053424/114274184-e96dcd00-9a3a-11eb-8c44-903b21071ee3.png)

**Comment by Aparus** [comment]
expo diagnostics:
```
  Expo CLI 4.3.4 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.15.2 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 7.6.3 - /usr/local/bin/npm
    npmPackages:
      expo: ^40.0.1 => 40.0.1 
      react: ^16.13.1 => 16.13.1 
      react-dom: ^16.13.1 => 16.13.1 
      react-native: ^0.63.2 => 0.63.2 
      react-native-web: ^0.13.18 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.3.4
    Expo Workflow: managed
```

**Comment by arpitBhalla** [comment]
Can you again check, I am not getting that
![Screenshot_1618066503](https://user-images.githubusercontent.com/55053424/114274909-24bdcb00-9a3e-11eb-8fb2-9ddff8a7f941.png)

**Comment by Aparus** [comment]
@arpitBhalla  Thank you. I am sorry for disturbing you. 
When I closed completely Expo Go and reopened it (with reload), cursor now in the center.
