### ISSUE TITLE
Floating Bubble

### ISSUE THREAD

**Issue by PrathamSinghSaluja** [react-native-elements/react-native-elements#2956]
**Is your feature request related to a problem? Please Describe.**

Let us add a new feature of Floating Bubble in RN App. It can help in increasing User Functionality by dragging it , clicking it or if not in use remove it.

**Describe the solution you'd like**

https://www.npmjs.com/package/react-native-floating-bubble

**Describe alternatives you've considered**

Open to alternatives and feedback, and willing to implement on RNE-app

**Additional context**

**Comment by flyingcircle** [comment]
The package already exists, so it seems pretty unnecessary to add here.
