### ISSUE TITLE
ref does not work in button

### ISSUE THREAD

**Issue by uwwangxiangyu** [react-native-elements/react-native-elements#2960]
**Explain what you did (Required)**

My use case: I'm using react-native-web and I want to know if the button is hovered or not. So I need to reference the button component.

But I think it will be helpful to reference the button in all platform.

**Expected behavior (Required)**

It should forward the ref

**Describe the bug (Required)**

It is working perfectly in `3.30` but failed in the latest version. I checked the change log and I found the reason is the button component has been converted to functional. (https://github.com/react-native-elements/react-native-elements/commit/2f50ef068c85d51ed5f43bfb9831ddda432e409f#)

**To Reproduce (Required)**

```javascript
const buttonRef = useRef(null)
const isHovered = useHover(buttonRef)
const isFocused = useFocus(buttonRef)
const isActive = useActive(buttonRef)

...

<Button
    ref={buttonRef}
/>
```

**Screenshots (Required)**

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   ^3.3.2      |
| react-native          |    ^0.63.4     |

**Comment by arpitBhalla** [comment]
@uwwangxiangyu I will open a PR for this

**Comment by arpitBhalla** [comment]
@uwwangxiangyu Can you please provide your code, so I can test it

**Comment by uwwangxiangyu** [comment]
> @uwwangxiangyu Can you please provide your code, so I can test it

Just reference the button component.

For my case, I'm using `react-native-web`  so I have something like this. You don't need to test like this, you can just test if the `buttonRef` is referencing the button components, and there is no warning like `Attempts to access this ref will fail`.
```
import { useActive, useFocus, useHover } from 'react-native-web-hooks'

const buttonRef = useRef(null)
const isHovered = useHover(buttonRef)
const isFocused = useFocus(buttonRef)
const isActive = useActive(buttonRef)

<Button
    ref={buttonRef}
/>
```

**Comment by flyingcircle** [comment]
How about wrapping the button in your own component?

**Comment by arpitBhalla** [comment]
@uwwangxiangyu 
```js
<Button 
  TouchableComponent={props=><Pressable ref={ref}
{...props}
/>}
/>
```

**Comment by uwwangxiangyu** [comment]
Hey @arpitBhalla 
However it will unmount the old component and mount a new component even theres only style changes.
```
import React, { useRef } from 'react'
import { useActive, useFocus, useHover } from 'react-native-web-hooks'

const buttonRef = useRef(null)
const isHovered = useHover(buttonRef)
const isFocused = useFocus(buttonRef)
const isActive = useActive(buttonRef)

<Button
   TouchableComponent={(props) => (
       <Pressable ref={ref} {...props} />
     )}
   buttonStyle={backgroundColor: isHovered ? '#58b1ba' : '#4fa9b3'}
/>
```

**Comment by arpitBhalla** [comment]
@uwwangxiangyu 
```js
const MyButton=React.forwardRef((p,ref)=><Button
   TouchableComponent={(props) => (
       <Pressable ref={ref} {...props} />
     )}
/>)
```
