### ISSUE TITLE
Slider thumbTintColor animation effect based on slider's value

### ISSUE THREAD

**Issue by voulgarakis** [react-native-elements/react-native-elements#2963]
Is it possible to have an animated color change when the value of slider changes?

**Comment by HariAcidReign** [comment]
You mean constantly changing the color of the `thumbProp` when sliding? Is there any use case for it?

**Comment by voulgarakis** [comment]
Exactly. Based on a state value, change the color of the slider.

**Comment by HariAcidReign** [comment]
While that certainly seems possible, how do you plan on changing the colors. By that I mean, do you want the entire `thumbTintColor` to change from one solid color to another, or just to change its intensity/tint (growing brighter or darker as you slide)?

**Comment by HariAcidReign** [comment]
Once the mentor approves of this idea, we can work on this then.

**Comment by voulgarakis** [comment]
Basically I would like to change the entire thumbTintColor from green to red based on a value in [0, 10] range 
0 --> red
1 --> close to red
..
9 --> close to green
10 --> green

**Comment by arpitBhalla** [comment]
Hey @voulgarakis 

We can use `Animated` API for this
```
thumbTintColor={String(
  animation.interpolate({
    inputRange: [0, 10],
    outputRange: ['rgba(0,0,255,1)', 'rgba(0,250,0,1)'],
  })
)}
```

**Comment by arpitBhalla** [comment]
Hey @voulgarakis 

We can do it using linear interpolation,

**Comment by HariAcidReign** [comment]
This does seem to be the right solution. Just replace the font-awesome icon in the slider with this and I think you should be good to go. Do close this issue if this works, as I don't think a separate slider component for just this use case is necessary.

**Comment by pranshuchittora** [comment]
@arpitBhalla would you mind adding this to the app

**Comment by arpitBhalla** [comment]
@pranshuchittora in the docs??
