### ISSUE TITLE
How to theme Avatar.Accessory?

### ISSUE THREAD

**Issue by PurTahan** [react-native-elements/react-native-elements#2965]
I need to theme Avatar.Accessory, but I cant use it like others. because there is **.**(dot) in its name.
help me please!

**Comment by khushal87** [comment]
`<Avatar.Accessory />` 
Feel free to add supported props as per the documentation. That's how we do it. Kindly refer https://reactnativeelements.com/docs/avatar
@PurTahan

**Comment by PurTahan** [comment]
I use ThemeProvider and pass json format theme to theme prop of it.
```
<ThemeProvider theme={theme}>
...
</ThemeProvider>
```

and in that json, I set all my theming settings

**Comment by khushal87** [comment]
@PurTahan which property do you want to set as in theme?

**Comment by PurTahan** [comment]
Icon props like : `color`, `containerStyle`, `type` and etc.

**Comment by khushal87** [comment]
@PurTahan You can pass this as direct props in the component.
```
<Avatar.Accessory
    color="red"
    backgroundColor="blue"
    containerStyle={{ borderRadius: 50 }}
    size={23}
  />
```

**Comment by PurTahan** [comment]
Dear @khushal87 ,
I can use `Avatar.Accessory` same as your above code. BUT my question is **how to theme it globally** to show it in all sections of my app like together.

hear is my theme.json
```
Text: {
    style: {
      color: c.text1,
      fontWeight: 'normal',
      fontFamily: 'Vazir-Regular-FD-UI',
      fontSize: 16,
    },
    h1Style: {
      color: c.text1,
      fontWeight: 'normal',
      fontFamily: 'Vazir-Black-FD-UI',
      fontSize: 30,
    },
    h2Style: {
      color: c.text1,
      fontWeight: 'normal',
      fontFamily: 'Vazir-Bold-FD-UI',
      fontSize: 26,
    },
    h3Style: {
      color: c.text1,
      fontWeight: 'normal',
      fontFamily: 'Vazir-Medium-FD-UI',
      fontSize: 22,
    },
    h4Style: {
      color: c.text1,
      fontWeight: 'normal',
      fontFamily: 'Vazir-Bold-FD-UI',
      fontSize: 18,
    },
  },
  Button: {
    titleStyle: {
      fontWeight: 'normal',
      fontFamily: 'Vazir-Bold-FD-UI',
    },
    iconRight: true,
    color: c.color1,
    iconContainerStyle: {
      paddingHorizontal: m.padSmall,
    },
  },
  Icon: {
    color: c.color1,
    containerStyle: {
      paddingHorizontal: m.padSmall,
    },
    type: 'font-awesome-5',
  },
  Badge: {
    textStyle: {
      fontWeight: 'normal',
      fontFamily: 'Vazir-Thin-FD-UI',
    },
  },
```
and send it as ThemeProvider prop.

**Comment by khushal87** [comment]
This doesn't work on my end too after testing. I am looking for a potential solution. Will soon try to get a fix and reply here. @PurTahan

**Comment by arpitBhalla** [comment]
> Dear @khushal87 ,
> I can use `Avatar.Accessory` same as your above code. BUT my question is **how to theme it globally** to show it in all sections of my app like together.
> 
> hear is my theme.json
> 
> ```
> Text: {
>     style: {
>       color: c.text1,
>       fontWeight: 'normal',
>       fontFamily: 'Vazir-Regular-FD-UI',
>       fontSize: 16,
>     },
>     h1Style: {
>       color: c.text1,
>       fontWeight: 'normal',
>       fontFamily: 'Vazir-Black-FD-UI',
>       fontSize: 30,
>     },
>     h2Style: {
>       color: c.text1,
>       fontWeight: 'normal',
>       fontFamily: 'Vazir-Bold-FD-UI',
>       fontSize: 26,
>     },
>     h3Style: {
>       color: c.text1,
>       fontWeight: 'normal',
>       fontFamily: 'Vazir-Medium-FD-UI',
>       fontSize: 22,
>     },
>     h4Style: {
>       color: c.text1,
>       fontWeight: 'normal',
>       fontFamily: 'Vazir-Bold-FD-UI',
>       fontSize: 18,
>     },
>   },
>   Button: {
>     titleStyle: {
>       fontWeight: 'normal',
>       fontFamily: 'Vazir-Bold-FD-UI',
>     },
>     iconRight: true,
>     color: c.color1,
>     iconContainerStyle: {
>       paddingHorizontal: m.padSmall,
>     },
>   },
>   Icon: {
>     color: c.color1,
>     containerStyle: {
>       paddingHorizontal: m.padSmall,
>     },
>     type: 'font-awesome-5',
>   },
>   Badge: {
>     textStyle: {
>       fontWeight: 'normal',
>       fontFamily: 'Vazir-Thin-FD-UI',
>     },
>   },
> ```
> 
> and send it as ThemeProvider prop.

Hey @PurTahan you can use `Accessory` key for this

**Comment by khushal87** [comment]
Yes we can do it this was too @PurTahan . Theme supports `Accessory` alone as key.

**Comment by arpitBhalla** [comment]
Hey @PurTahan @khushal87 

I guess there is conflict in name of themeKey 

https://github.com/react-native-elements/react-native-elements/blob/5c2d6b68284c9abf15f89b5284b90e5c5f4beba3/src/avatar/Accessory.tsx#L93

https://github.com/react-native-elements/react-native-elements/blob/5c2d6b68284c9abf15f89b5284b90e5c5f4beba3/src/config/theme.tsx#L36

**Comment by khushal87** [comment]
Yes @arpitBhalla There is an issue here that's why it didn't work on my end too. Fixing this will solve the issue according to me.

**Comment by flyingcircle** [comment]
You can theme it using "AvatarAccessory" as the themekey says. Is this not working?
