### ISSUE TITLE
SearchBar component for expo and typescript

### ISSUE THREAD

**Issue by dhanushm360** [react-native-elements/react-native-elements#2969]
Hello,

I'd like to build this searchbar component into my react native typescript mobile app managed by expo. How can I use the platform specific searchbar to display the ios styled searchbar?

**Comment by HariAcidReign** [comment]
You want to use the iOS styled search bar in your app using React Native Elements, right? Did you check out the component in the `react-native-elements-app` repo? 

https://github.com/react-native-elements/react-native-elements-app/blob/daa5664127e2e2b2fba8a22e345c9d78a1401d1f/src/views/inputs.tsx#L61

I think this is what you want. Let me know if I am right.

**Comment by flyingcircle** [comment]
Yep, read the docs. If you're still confused, ask a question on the RNE slack
