### ISSUE TITLE
Transfer List 

### ISSUE THREAD

**Issue by PrathamSinghSaluja** [react-native-elements/react-native-elements#2970]
**Is your feature request related to a problem? Please Describe.**

A transfer list lets us move one or more items between lists. It can help in selecting the preferences and move the selected ones into a new list and remove the unselected ones.

**Describe the solution you'd like**

The best solution can be using https://material-ui.com/components/transfer-list/ 
Open for other methods of implementation as well.

**Describe alternatives you've considered**

Open For suggestions or modifications.

**Additional context**

**Comment by flyingcircle** [comment]
This doesn't really seem like a thing for mobile apps which is what React Native focuses on.
