### ISSUE TITLE
Custom Button shadow is displayed on top of default shadow, instead of replacing it

### ISSUE THREAD

**Issue by RyanTG** [react-native-elements/react-native-elements#2971]
**Explain what you did (Required)**

I am trying to customize the Button shadow. Say, a bigger radius, or a different color shadow.

**Expected behavior (Required)**

I expect to have to use `raised` and then overwrite the shadow styles within the buttonStyle prop.

**Describe the bug (Required)**

When you include `raised`, it automatically adds a shadow to the button. If you add your own styles into buttonStyle, instead of replacing the default shadows, it seems to **add the new shadow on top of the default ones**. So you end up with two sets of shadows!

Is there a way to simply overwrite the default shadow, or add your own shadow without using `raised`?

**To Reproduce (Required)**

Create a button:

```     
            return(
        <Button
            buttonStyle={s.buttonStyle}
            raised
        />
    )
}

const getStyles = (theme) => StyleSheet.create({
    buttonStyle: {
        shadowColor: '#dcd3d6',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.9,
        shadowRadius: 5,
        elevation: 5,
    },
```

**Screenshots (Required)**

In the below screenshot, the Button and the ButtonGroup both have the same shadow style. But, the Button clearly has an additional shadow on it (added by default by `raised`)

![buttonshadow](https://user-images.githubusercontent.com/632682/114906345-ca6e9280-9dce-11eb-91e5-75231e348954.jpeg)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |         |
| react-native          |    ^3.3.2     |

**Comment by arpitBhalla** [comment]
Hey @RyanTG  please use `containerStyle` prop

**Comment by RyanTG** [comment]
Ah... thank you. I was so close. I had tried that, but didn't include "overflow: visible".

So, to summarize: if you want a custom shadow on a button, you don't need to include `raised`. Just put the shadow styles in containerStyle and include `overflow: 'visible'`

```
...
<Button
            containerStyle={s.containerStyle}
/>

    containerStyle: {
        shadowColor: '#dcd3d6',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.9,
        shadowRadius: 5,
        elevation: 5,
        overflow: 'visible'
    },
```
