### ISSUE TITLE
Invalid type of style prop in Divider Component

### ISSUE THREAD

**Issue by khushal87** [react-native-elements/react-native-elements#2984]
**Explain what you did (Required)**
While checking the code of the `Divider` component. I found that the type of `style` prop is `object | any[]` while it should be `StyleProp<ViewStyle>`

**Expected behavior (Required)**
The style prop should have `StyleProp<ViewStyle>`

**Describe the bug (Required)**
Mentioned above

**To Reproduce (Required)**
Check the code of the `Divider` component
We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behavior:

**Screenshots (Required)**
```
export type DividerProps = ViewProps & {
  style?: object | any[];
};
```

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   3.4.0    |
| react-native          |     0.63.2    |

**Comment by khushal87** [comment]
Can I work on the fix?

**Comment by arpitBhalla** [comment]
@khushal87 if its good
