### ISSUE TITLE
List.Accordion do not works

### ISSUE THREAD

**Issue by kovalevroman7** [react-native-elements/react-native-elements#2986]
![Screenshot_11](https://user-images.githubusercontent.com/67242846/115575830-9a8e2600-a2cb-11eb-9e14-1a97c6d19ae3.png)
```bash
# Snack
https://snack.expo.io/@kovalevrp/bug-listaccordion

| software              | version |
| --------------------- | ------- |
| react-native-elements |   3.4.0      |

**Comment by arpitBhalla** [comment]
@kovalevroman7 Can you please Share your code

**Comment by arpitBhalla** [comment]
Hey @kovalevroman7

**Comment by kovalevroman7** [comment]
> 
> 
> Hey @kovalevroman7, Kindly change the `content` prop to this
> 
> ```js
> content={
> <>
>   <Icon name="place" size={30} />
>   <ListItem.Content>
>   <ListItem.Title>List Accordion</ListItem.Title>
>   </ListItem.Content>
> </>
> }
> ```
> 
> Updated Snack https://snack.expo.io/@arpitbhalla/bug-listaccordion
> 
> Hope it will help you

Your option did help, but only for sdk40. It also does not work on sdk 41

**Comment by arpitBhalla** [comment]
Hey @kovalevroman7 if it works please close the issue

**Comment by kovalevroman7** [comment]
thanks it helped
