### ISSUE TITLE
Adding new props to Divider

### ISSUE THREAD

**Issue by khushal87** [react-native-elements/react-native-elements#2987]
**Is your feature request related to a problem? Please Describe.**
Yes, currently we don't have much flexibility with the `Divider` component. Therefore, we can make it more customizable and dynamic by adding new props. We don't have such flexibility in any of the popular packages in RN.

**Describe the solution you'd like**
I would like to add new props such as `inset(left, right and middle)`, `orientation(vertical/horizontal)`, `subHeader` , `width`, etc.

**Describe alternatives you've considered**
 https://material-ui.com/components/dividers/ and https://material.io/components/dividers

**Additional context**
The concept and design can be referred from the above links. Hope this will help a lot of users and increase user engagement with the package.

**Comment by khushal87** [comment]
Looking forward to the community's feedback on it? What do you say @arpitBhalla @HariAcidReign @pranshuchittora @flyingcircle and others.

**Comment by arpitBhalla** [comment]
Chakk de fatte
