### ISSUE TITLE
Cant change the resizeMode of Card.Image 

### ISSUE THREAD

**Issue by KrisLau** [react-native-elements/react-native-elements#2989]
**Explain what you did (Required)**
Tried a Card.Image to my Card and setting the `resizeMode` to either contain or stretch. 
```
<TouchableOpacity style={...}>
<Card>
  <Card.Image source={{uri: '...'}}  containerStyle={styles.img}/>
  <Card.Title>{l.title}</Card.Title>
  <Text>...</Text>
</Card>
</TouchableOpacity>
```

In stylesheet:
```
img: {
    resizeMode: 'stretch',
}
```

**Expected behavior (Required)**
This is the result I was hoping for and I used the react Image component to achieve it.
![image](https://user-images.githubusercontent.com/46275463/115895125-b0146480-a41f-11eb-8808-9c2a1188f300.png)

**Describe the bug (Required)**
This is what I get when I use the Card.Image
![image](https://user-images.githubusercontent.com/46275463/115894973-81968980-a41f-11eb-859c-a6b200448eb2.png)
The Card.Image seems to be defaulting and staying with resizeMode: cover

**Comment by flyingcircle** [comment]
This library doesn't do anything to the `resizeMode`. Your issue is likely something else.
