### ISSUE TITLE
Slider: view not updated when the value prop changes

### ISSUE THREAD

**Issue by anarthal** [react-native-elements/react-native-elements#2995]
**Explain what you did (Required)**

Using the Slider component to build something that responds to changes. Essentially, the value prop of the slider is stored in a state variable in the parent component, and updated periodically. This gist describes what I am trying to achieve: https://gist.github.com/anarthal/4f4e4025c9a5d854a7ff9b35ca1a1a5f

PR: https://github.com/react-native-elements/react-native-elements/pull/2996

**Expected behavior (Required)**

The Slider view is updated whenever the value changes.

**Describe the bug (Required)**

The Slider view is not updated. It is only updated if the value > maximumValue.

**To Reproduce (Required)**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

https://snack.expo.io/@anarthal/slider-bug

**Screenshots (Required)**

https://snack.expo.io/@anarthal/slider-bug

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   3.4.1      |
| react-native          |   expo managed SDK, v40.0.0      |

**Comment by arpitBhalla** [comment]
Can you fix this?? 
![Screenshot_1619871075](https://user-images.githubusercontent.com/55053424/116782034-7dfca580-aaa4-11eb-90df-5c7885469efb.png)

**Comment by vincentjames501** [comment]
Just ran into this one myself!

**Comment by eee9** [comment]
I have the same problem
https://snack.expo.io/@eee9/rneslider1
https://snack.expo.io/@eee9/rneslider2
Diffrence is only in react-native-elements versions. Last 2 versions have a bug.

**Comment by govindprasadgupta** [comment]
Update slider value using props and try to drag the slider. it resets to the previous slider value.

Example:
Set slider value by dragging
Now update slider value by props
Tap on the slider. it reset again to the previous value.
