### ISSUE TITLE
can you make a Radio Group ? thank you very much

### ISSUE THREAD

**Issue by stfenjobs** [react-native-elements/react-native-elements#3002]
can you make a Radio Group ? thank you very much

ref:
https://wix.github.io/react-native-ui-lib/docs/RadioGroup/
https://callstack.github.io/react-native-paper/radio-button-group.html

**Comment by arpitBhalla** [comment]
Hey @stfenjobs Can we use Single Radio CheckBox to make a group?

**Comment by stfenjobs** [comment]
it's work ,

thank you very much @arpitBhalla

**Comment by arpitBhalla** [comment]
@stfenjobs hehe

**Comment by darkbasic** [comment]
@arpitBhalla how is it supposed to work with Typescript?

```ts
import {CheckBox, CheckBoxProps, Icon} from 'react-native-elements';

const MyRadio: FC<CheckBoxProps> = (props: any) => (
  <CheckBox
    checkedIcon={
      <Icon
        name="radio-button-checked"
        type="material"
        color="green"
        size={25}
        iconStyle={{marginRight: 10}}
      />
    }
    uncheckedIcon={
      <Icon
        name="radio-button-unchecked"
        type="material"
        color="grey"
        size={25}
        iconStyle={{marginRight: 10}}
      />
    }
    {...props}
  />
);
```

If I remove `: any` it complains about `CheckBoxProps` not being the right type for `CheckBox`, which doesn't make sense.

**Comment by KrisLau** [comment]
Snack I made for myself to test the  https://snack.expo.dev/t7fqw_Qe0

> Hey @stfenjobs Can you use Multiple "Single Radio CheckBox" to make a group instead?
> 
> ```js
> const MyRadio = (props) => <CheckBox
>         checkedIcon={
>           <Icon
>             name="radio-button-checked"
>             type="material"
>             color="green"
>             size={25}
>             iconStyle={{ marginRight: 10 }}
>           />
>         }
>         uncheckedIcon={
>           <Icon
>             name="radio-button-unchecked"
>             type="material"
>             color="grey"
>             size={25}
>             iconStyle={{ marginRight: 10 }}
>           />
>         }
>      {...props}
> />
> ```
> 
> ```js
> const [ check, setCheck ] = React.useState(0)
> 
> ["My Option 1", "My Option 2"].map((opt,index)=>(
> <MyRadio
>         title={opt}
>         checked={check===index}
>         onPress={() => setCheck(index)}
>       />
> ))
> ```
> 
> What do you say?

Snack I made of this code just to test: https://snack.expo.dev/t7fqw_Qe0
