### ISSUE TITLE
Ratings => AirbnbRating

### ISSUE THREAD

**Issue by rohail111** [react-native-elements/react-native-elements#3003]
AirbnbRatings module is not present in elements and it's available in the documentation. 
kindly remove AirbnbRating from the documentation or add it to the plugin.

**Comment by arpitBhalla** [comment]
Hey @rohail111 it's already present

**Comment by khushal87** [comment]
@rohail111 will be fixed soon with my PR https://github.com/react-native-elements/react-native-elements/pull/3000

**Comment by khushal87** [comment]
@arpitBhalla The name is changed now in the package, that is why he is facing a problem I think.

**Comment by vynerth0429** [comment]
Hello @khushal87 , may we know when would it be possible to release the fix of this?

It seems like this breaks the web version. Only the native part is working.
You can use this [repo ](https://github.com/vynerth0429/rne-rating) for replication.

**Comment by khushal87** [comment]
I have already raised a PR to add the new supported Names for the import. Waiting for the approval @vynerth0429

**Comment by khushal87** [comment]
https://github.com/react-native-elements/react-native-elements/pull/3000/files you can understand the imports here. @vynerth0429

**Comment by vynerth0429** [comment]
Hello @khushal87 ,

Below is the problem when I serve the web application.
Btw, I am using Typescript and I just imported react-native-elements `import {} from 'react-native-elements';` in `App.tsx` to show the error.

```
rne-rating/src/react-native/node_modules/react-native-elements/node_modules/react-native-ratings/src/index.d.ts
TypeScript error in /Users/junrey.ellezo/Documents/Projects/house-call/src/react-native/node_modules/react-native-elements/node_modules/react-native-ratings/src/index.d.ts(66,21):
Namespace '"rne-rating/src/react-native/node_modules/@types/prop-types/index"' has no exported member 'object'.  TS2694

    64 |    * Exposes style prop to add additonal styling to the container view
    65 |    */
   > 66 |   style?: PropTypes.object;
       |                     ^
    67 | 
    68 |   /**
    69 |    * Whether the rating can be modiefied by the user
```

**Comment by khushal87** [comment]
Please upgrade your React native ratings version. @vynerth0429

**Comment by vynerth0429** [comment]
@khushal87 , I don't have `react-native-ratings` on my package file since this is already included in `react-native-elements`. 

And also, correct me if I am wrong to this, regardless if I update the `react-native-ratings`, `react-native-elements` still need to update the proper imports as stated here: [https://github.com/react-native-elements/react-native-elements/pull/3000/files](https://github.com/react-native-elements/react-native-elements/pull/3000/files)

PS: I tried to update the `react-native-ratings` as advised but the issue still persists.

**Comment by khushal87** [comment]
This is something strange, as it's working on my end irrespective of the version.  You may have to wait for a new update as this tsc issue is already solved in a subsequent version of react native ratings (https://github.com/Monte9/react-native-ratings/pull/138). I have already raised a PR for the same to upgrade the package here. And yes, react-native ratings are already present as a dependency in the package react-native-elements. The error you are getting is a tsc issue which is already solved in the latest version of react-native-ratings and the version is to be updated here. For now, you can ignore it using a tsc fix. @vynerth0429

**Comment by rohail111** [comment]
Thanks for replying to all of you guys. @khushal87 I knew about the react-native rating plugin but all I wanted was to tell that either add that feature in the plugin or remove it from documentations. Any how I just reported this issue because further people don't get the same issue as I faced earlier.

**Comment by khushal87** [comment]
@rohail111 Airbnbratings is in the plugin. You can use it without any issue.

**Comment by rohail111** [comment]
It's not working with me in the latest version. Is its name changed?

**Comment by khushal87** [comment]
@rohail111 No, the name is the same. Check the names of imports here https://github.com/Monte9/react-native-ratings/blob/master/src/index.tsx

**Comment by rohail111** [comment]
[image: image.png]

no suck module found in plugin. on the other hand, Rating is present.

[image: image.png]

**Comment by khushal87** [comment]
@rohail111 this is a strange issue. @vynerth0429 are you facing it too?

**Comment by vynerth0429** [comment]
Hey @khushal87 , I can view the images attached by rohail. 

How you tried to clone and run this repo: [https://github.com/vynerth0429/rne-rating](https://github.com/vynerth0429/rne-rating) ?

The setup is just basic and maybe you can provide some workaround on this. The web version is entirely unusable on my end. :(
