### ISSUE TITLE
[RFC] Visual Preview of components in VS Code

### ISSUE THREAD

**Issue by arpitBhalla** [react-native-elements/react-native-elements#3004]
![Screenshot from 2021-05-01 16-46-53 (1)](https://user-images.githubusercontent.com/55053424/116780993-9ddc9b00-aa9d-11eb-97a0-5f6513d85c5d.jpg)

Can be achieved by adding this above the component code
```javascript
/**
 * Documentation: https://reactnativeelements.com/docs/searchbar
 *
 * Preview: ![Search Box](https://user-images.githubusercontent.com/17592779/31586716-f6e8ff9c-b1d4-11e7-918f-2a7e11d51b08.gif)
 *
 * Demo Code: ```
   <SearchBar
        placeholder="Type Here..."
        onChangeText={this.updateSearch}
        value={search}
      />
 * ```
 */
```

@pranshuchittora @flyingcircle @dhruvdutt

**Comment by hetanthakkar1** [comment]
it's great

**Comment by arpitBhalla** [comment]
Solved by https://marketplace.visualstudio.com/items?itemName=rne.snippets
