### ISSUE TITLE
Slider vertical orientation not working

### ISSUE THREAD

**Issue by micaelillos** [react-native-elements/react-native-elements#3008]
**Explain what you did (Required)**

When setting the orientation prop in the Slider component to 'vertical' the Slider becomes unusable. 
(In mobile and web)
```javascript
 <Slider
            value={val}
            minimumValue={0}
            allowTouchTrack={true}
            maximumValue={100}
            step={10}
            orientation='vertical'
            onValueChange={(value: number) => handleChange(value)}
            minimumTrackTintColor={colors.menu}
            maximumTrackTintColor={colors.white}
            thumbStyle={{ height: 10, width: 10, backgroundColor: 'green' }}
          />
```

**Expected behavior (Required)**

Expected for the slider to be displayed in a vertical fashion

**Describe the bug (Required)**

This is how the slider looks when I set the orientation to 'vertical':
![photo_2021-05-04_11-32-28](https://user-images.githubusercontent.com/14940062/116978537-82a3a280-accc-11eb-8a64-5837f3c7d8be.jpg)

This is how it shoud look like
![photo_2021-05-04_11-33-20](https://user-images.githubusercontent.com/14940062/116978574-9222eb80-accc-11eb-9c23-606edcb020e7.jpg)

**To Reproduce (Required)**

To reproduce the bug set 'vertical' in the orientation prop in the slider

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |3.4.1 |
| react-native          |0.64.0|

**Comment by arpitBhalla** [comment]
Hey @micaelillos, I updated your code, Please Check https://snack.expo.io/@arpitbhalla/rne-vertical-slider

**Comment by micaelillos** [comment]
Please look at https://snack.expo.io/@micaelil/rne-vertical-slider
You can see that the slider is inconsistent.
- When you slide down the allotted track becomes longer.
- There is a gap between the end of the thumb and the start of the path

**Comment by arpitBhalla** [comment]
Hey @khushal87 see that yellow line 
![image](https://user-images.githubusercontent.com/55053424/117464641-7c345580-af6e-11eb-8a44-0bb98a105135.png)

**Comment by khushal87** [comment]
> Hey @khushal87 see that yellow line
> ![image](https://user-images.githubusercontent.com/55053424/117464641-7c345580-af6e-11eb-8a44-0bb98a105135.png)

Are you checking it on my snack?

**Comment by arpitBhalla** [comment]
nhi re

**Comment by arpitBhalla** [comment]
increse the width of thumb

**Comment by khushal87** [comment]
https://snack.expo.io/@khushal87/rne-vertical-slider

**Comment by arpitBhalla** [comment]
yep, that looks best

**Comment by khushal87** [comment]
Thanks @arpitBhalla :)

**Comment by flyingcircle** [comment]
Thanks @khushal87 and @arpitBhalla for working the solution here :)

**Comment by dinatazy** [comment]
When the slider is vertical the Minimum value is up and the Maximum value is down. Is there a way to make it the opposite?
