### ISSUE TITLE
Request to add "onRequestClose" feature to BottomSheet

### ISSUE THREAD

**Issue by koaladlt** [react-native-elements/react-native-elements#3009]
Hey guys, is there a way to close the BottomSheet component if the back button is pressed on Android?

So, I tried to use the [BackHandler ](https://reactnative.dev/docs/backhandler) library to make this work, but there is no way to make it work when the component is visible. Maybe this issue is something similar that happens when a modal is open, you can't use BackHandler, and that's why they included the [onRequestClose ](https://reactnative.dev/docs/modal#onrequestclose) prop to make it work.

Maybe we can have something similar to that.

Thanks!

**Comment by khushal87** [comment]
Hey @koaladlt this is a great recommendation. Currently, the closing of the bottom sheet works on clicking the cancel button on the modal. We can have a prop which would enable this event you have suggested. I will see if we can do this in the future and update you. Thank you.

**Comment by koaladlt** [comment]
@khushal87 Great 🙌🏻

**Comment by khushal87** [comment]
@koaladlt 
`
<BottomSheet
        modalProps={{
          onRequestClose: () => {
            setIsVisible(false);
          },
        }}
        isVisible={isVisible}
      >
        {list.map((l, i) => (
          <ListItem
            key={i}
            containerStyle={l.containerStyle}
            onPress={l.onPress}
          >
            <ListItem.Content>
              <ListItem.Title style={l.titleStyle}>{l.title}</ListItem.Title>
            </ListItem.Content>
          </ListItem>
        ))}
      </BottomSheet>
`

This will work fine. Please try.

**Comment by koaladlt** [comment]
@khushal87 It is working like a charm! Thank you so much!
