### ISSUE TITLE
Require cycles

### ISSUE THREAD

**Issue by MaksimSerg** [react-native-elements/react-native-elements#3010]
Require cycle: node_modules/react-native-elements/dist/list/ListItem.js -> node_modules/react-native-elements/dist/list/ListItemAccordion.js -> node_modules/react-native-elements/dist/list/ListItem.js

react-native-elements: v3.4.1

  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4

**Comment by khushal87** [comment]
Thanks for addressing the issue @MaksimSerg. I will look for a fix and update you soon.

**Comment by detroit007** [comment]
issue still exist: I've updated to version 3.4.1 and facing same problem.

**Comment by detroit007** [comment]
@MaksimSerg did it resolved your issue? @flyingcircle can you please check the issue is closed but the problem still exists.

**Comment by arpitBhalla** [comment]
> issue still exist: I've updated to version 3.4.1 and facing same problem.

Hey @detroit007 wait for next patch

**Comment by detroit007** [comment]
@arpitBhalla thanks for the response, when will be the next patch? I'm facing this issue for quite some time and need to solve this pls, Thanks again.

**Comment by detroit007** [comment]
@arpitBhalla is there any way to hide this warning?

**Comment by arpitBhalla** [comment]
`console.disableYellowBox = true;`

**Comment by arpitBhalla** [comment]
🤔 You will not get it in Production, lets wait for 3.4.2
