### ISSUE TITLE
Error in using SpeedDial component -  "Exception in HostFunction: Malformed calls from JS: field sizes are different."

### ISSUE THREAD

**Issue by mongapuneet** [react-native-elements/react-native-elements#3011]
**Explain what you did (Required)**
I am trying to use the SpeedDial component in my app. I have pasted a very basic version of my app.js. I have also attached screenshots of the errors I am receiving in my expo go app.

I am trying to use the SpeedDial component as described in the react-native-elements documentation.

**Expected behavior (Required)**
SpeedDial component should work without any errors.

**Describe the bug (Required)**
Receiving error Error: "Exception in HostFunction: Malformed calls from JS: field sizes are different." on using SpeedDial in my app.js

**To Reproduce (Required)**
Please use the following App.js 

`import React, {useState} from 'react';
import {View} from 'react-native';
import {SpeedDial} from 'react-native-elements'; 

export default function App() {
  const [open, setOpen] = useState("");
  return (<View>
    <SpeedDial
  open={open}
  icon={{ name: 'edit', color: '#fff' }}
  openIcon={{ name: 'close', color: '#fff' }}
  onChange={() => setOpen(!open)}
  >
  <SpeedDial.Action
    icon={{ name: 'add', color: '#fff' }}
    title="Add"
    onPress={() => console.log('Add Something')}
  />
  <SpeedDial.Action
    icon={{ name: 'delete', color: '#fff' }}
    title="Delete"
    onPress={() => console.log('Delete Something')}
  />
</SpeedDial>
  </View>);
}`

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Screenshots (Required)**
![WhatsApp Image 2021-05-06 at 00 24 53](https://user-images.githubusercontent.com/116957/117258260-a0265880-ae01-11eb-9926-4dbc47d913d3.jpeg)
![WhatsApp Image 2021-05-06 at 00 24 53 (1)](https://user-images.githubusercontent.com/116957/117258262-a0beef00-ae01-11eb-866e-c903e7c7b7c0.jpeg)
![WhatsApp Image 2021-05-06 at 00 24 53 (2)](https://user-images.githubusercontent.com/116957/117258267-a1578580-ae01-11eb-8617-39f70518495b.jpeg)
![WhatsApp Image 2021-05-06 at 00 24 53 (3)](https://user-images.githubusercontent.com/116957/117258268-a1578580-ae01-11eb-8d6a-4341c4c079c9.jpeg)
![WhatsApp Image 2021-05-06 at 00 24 53 (4)](https://user-images.githubusercontent.com/116957/117258269-a1f01c00-ae01-11eb-9000-883e86a1a646.jpeg)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   3.4.1      |
| react-native          |   0.63.3      |

**Comment by arpitBhalla** [comment]
Hey @mongapuneet Please check https://snack.expo.io/@arpitbhalla/speeddial, from where did you pick that code, it seems to be older

**Comment by mongapuneet** [comment]
@arpitBhalla  - Thanks for the quick turnaround. It works like a charm now.
