### ISSUE TITLE
[RFC] Redesign Homepage of website

### ISSUE THREAD

**Issue by arpitBhalla** [react-native-elements/react-native-elements#3015]
References:
https://alpha.nativebase.io/
https://akveo.github.io/react-native-ui-kitten/ 

https://docusaurus.io/showcase/

@hetanthakkar1 @khushal87 @HariAcidReign @jugshaurya we can together work on this

**Comment by jugshaurya** [comment]
count me in

**Comment by HariAcidReign** [comment]
Love it! Right up my alley so I'm in
Let the mentors approve it tho 😄

**Comment by HariAcidReign** [comment]
> count me in, but isn't this one of the GSoC ideas? we should wait for mentors to announce the projects first.
> If they don't pick it under GSoC, we all can still work on it in the summer

Where is it mentioned in the ideas list? Also, we should consider the fact that it **might** clash with idea#4 (merging doc + playground)

**Comment by arpitBhalla** [comment]
We only be doing (if doing) homepage part so i dont think its conflicting....

**Comment by snitin315** [comment]
I can help with this too.

**Comment by jugshaurya** [comment]
Idea #1 (Design 2.0) implicity covers this, if we are changing core components designs then it includes homepage to match designs

**Comment by jugshaurya** [comment]
> @arpitBhalla looks good, just we need to be sure about mentors approval because it may clash with idea 4

I agree

**Comment by arpitBhalla** [comment]
> > @arpitBhalla looks good, just we need to be sure about mentors approval because it may clash with idea 4
> 
> I agree

Bhai Slack dekho

**Comment by HariAcidReign** [comment]
> Idea #1 (Design 2.0) implicity covers this, if we are changing core components designs then it includes homepage to match designs

That kinda makes sense. You would want the core design of the components and app to be similar to the website, true. eg. UI kitten

**Comment by jugshaurya** [comment]
> > Idea #1 (Design 2.0) implicity covers this, if we are changing core components designs then it includes homepage to match designs
> 
> That kinda makes sense. You would want the core design of the components and app to be similar to the website, true. eg. UI kitten

Exactly, that's why we should wait for GSoC period to start or mentor approvals

**Comment by arpitBhalla** [comment]
Should we start now?

**Comment by arpitBhalla** [comment]
@snitin315 @khushal87 @jugshaurya I guess we can start it
