### ISSUE TITLE
Auto scroll Text

### ISSUE THREAD

**Issue by KrisLau** [react-native-elements/react-native-elements#3017]
**Is your feature request related to a problem? Please Describe.**
Nope not a problem I just think it would be a useful addition to the Text component. I was hoping to have the Text component auto scroll if it is longer than the container. 

**Describe the solution you'd like**
It would be kind of like the way the music title scrolls on Spotify or something like the scrolling text on google search when you search "marquee html". It would be nice if it was just a boolean prop on the Text component like this: <Text autoscroll={true} /> and some other options to control the speed of the scroll. 

**Describe alternatives you've considered**
There's this package: https://github.com/deanhet/react-native-text-ticker but it didn't seem to work within my project and it seems to not be supported anymore.

**Additional context**
N/A

**Comment by HariAcidReign** [comment]
I got what you mean. I love the component idea and the package as you mentioned seems to be inactive so making a new component from scratch with all the crucial props like `scrollSpeed`, `animation`, a bool prop to check if the text is long enough, and `loop` makes sense to me. 

@pranshuchittora @flyingcircle would love your thoughts on if this is a useful addition to the toolkit

**Comment by flyingcircle** [comment]
Not supported? It says the last published date is 2 months ago. Looks like that's the package to use, or fork it and fix whatever isn't working? I don't think we want this in RNE.
