### ISSUE TITLE
iconPosition not working in Tab.Item

### ISSUE THREAD

**Issue by jorgegvallejo** [react-native-elements/react-native-elements#3018]
**Explain what you did (Required)**

Trying to position the Tab.Item icon below the title in RNE 3.4.1

**Expected behavior (Required)**

using "bottom" for iconPosition should place the icon below the title

**Describe the bug (Required)**

iconPosition has no effect on icon positioning

**To Reproduce (Required)**

use "bottom" for iconPosition

![Screen Shot 2021-05-07 at 12 12 51 PM](https://user-images.githubusercontent.com/33339972/117485943-9e0de800-af2e-11eb-9ac2-a9e24bbb3d12.png)

**Comment by arpitBhalla** [comment]
Hey @jorgegvallejo 
```javascript
 <Tab.Item
          buttonStyle={{flexDirection:"column-reverse"}}
          ...
```
Can you use this

**Comment by jorgegvallejo** [comment]
@arpitBhalla, thanks!
