### ISSUE TITLE
[RFC] Improving List to work better.

### ISSUE THREAD

**Issue by khushal87** [react-native-elements/react-native-elements#3020]
**Is your feature request related to a problem? Please Describe.**
This issue is in continuation of #3014. While I was working on the solution and improving how the List is been written in the package it came to my mind that we also have Title, SubTitle, Checkbox, Chevron in the List which does nothing much but only displays the Title text and Subtitle text of a ListItem and Chevron displays an Icon.

**Describe the solution you'd like**
So, I want to remove them and add props to the ListItem(obviously customizable). This would decrease unnecessary nodes while implementing and using, rather it would increase the props but having relevant props is better than having a Node in itself to do the same work.

- For title, we can have string|Node field
- For the subtitle, we can have string|Node field
- For Chevron, we can have a boolean field, which if true displays a chevron
- For Checkbox, we can have a boolean field too, which if true displays the checkbox

**_Rather, we can have a Title, Subtitle for the List overall_.**

**Describe alternatives you've considered**
There's none but most of the packages use this solution and we would also work on making the existing codebase performant and better.

**Additional context**
As such none. I am already working on improving the code structure of ListItem to be used as List.Item with the admin's permission.

**Comment by khushal87** [comment]
What is your opinion about it? @pranshuchittora @flyingcircle @arpitBhalla @hariacidreign and others from the community.

**Comment by arpitBhalla** [comment]
Mast adea h

**Comment by arpitBhalla** [comment]
What about similar to Material UI 
```javascript
<List
      subheader={
        <ListSubheader component="div" id="nested-list-subheader">
          Nested List Items
        </ListSubheader>
      }
    >
      <ListItem button>
        <ListItemText primary="Sent mail" />
      </ListItem>
</List>
```
So we can make

```javascript
<List
      subheader={
        <ListSubheader component="div" id="nested-list-subheader">
          Nested List Items
        </ListSubheader>
      }
    >
      <List.Item button>
        <List.ItemText primary="Sent mail" />
      </List.Item>
</List>
```

Something like this I guess

**Comment by khushal87** [comment]
Yes, the above is exactly what I mean, and Title and SubTitle could be for the entire list.

**Comment by arpitBhalla** [comment]
@khushal87 We can close this I guess
