### ISSUE TITLE
Error: Featured Tile

### ISSUE THREAD

**Issue by brianvarskonst** [react-native-elements/react-native-elements#3021]
**Explain what you did (Required)**
Want to use the featured Tile Component.

**Expected behavior (Required)**
To not get this error.

**Describe the bug (Required)**
Got this Error:
![image](https://user-images.githubusercontent.com/53712359/117552712-65b0fb80-b04d-11eb-851e-608103f214e6.png)

**To Reproduce (Required)**
I pasted my Code into Snack to see what happens there.

If I remove this Code ` || !('fontSize' in titleStyle)` the Tile Component works as expected.

# Snack
https://snack.expo.io/@brianvarskonst/react-native-elements---issue-featured-tile

**Screenshots (Required)**
Error:
![image](https://user-images.githubusercontent.com/53712359/117552465-c2abb200-b04b-11eb-8a06-0e23ebdb6c40.png)
Code:
![image](https://user-images.githubusercontent.com/53712359/117552478-dce59000-b04b-11eb-9cc1-7c131bd1d3c3.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  0.63.4  |
| react-native          | 3.4.1 |

**Comment by khushal87** [comment]
Thanks for reporting the issue @brianvarskonst I will give you a fix soon.

**Comment by arpitBhalla** [comment]
I guess `typeof styles.title` is giving number, that's why this is happening

**Comment by arpitBhalla** [comment]
Hey @brianvarskonst  flatten the styles, https://snack.expo.io/@arpitbhalla/react-native-elements---issue-featured-tile

**Comment by brianvarskonst** [comment]
> Hey @brianvarskonst flatten the styles, https://snack.expo.io/@arpitbhalla/react-native-elements---issue-featured-tile
> 
> ```js
>  titleStyle={[styles.title]}
> ```

Awesome, thanks. I was thinking about this.... 😄

**Comment by brianvarskonst** [comment]
> Thanks for reporting the issue @brianvarskonst I will give you a fix soon.

The Answer from @arpitBhalla fixes this. 

>  `titleStyle={[styles.title]}`

**Comment by arpitBhalla** [comment]
Please Close the issue

**Comment by khushal87** [comment]
Great, yes this would work fine. 😄
