### ISSUE TITLE
Element type is invalid when using FC Component in inputComponent of <Input/>

### ISSUE THREAD

**Issue by mannix-lei** [react-native-elements/react-native-elements#3029]
Type '() => JSX.Element' is not assignable to type 'typeof Component'.
  Type '() => Element' provides no match for the signature 'new <P = {}, S = {}, SS = any>(props: P | Readonly<P>): Component<P, S, SS>'.ts(2322)
Input.d.ts(45, 5): The expected type comes from property 'InputComponent' which is declared here on type 'IntrinsicAttributes & Omit<TextInputProps & RefAttributes<TextInput> & { containerStyle?: StyleProp<ViewStyle>; ... 15 more ...; renderErrorMessage?: boolean | undefined; } & Partial<...>, keyof ThemeProps<...>> & ... 4 more ... & Partial<...>'

const RadioGroup: FC<IProps> = ({
    values = [
        {key: '1', label: 'male'},
        {key: '2', label: 'famale'},
    ],
    initialValues,
    onChange,
}: IProps) => {
    return (
        <View style={styles.radioGroupCon}>
            {values.map(item => (
                <CheckBox
                    center
                    containerStyle={styles.containerStyle}
                    title={item.label}
                    checkedIcon="dot-circle-o"
                    uncheckedIcon="circle-o"
                    checked={item.key === initialValues}
                    onPress={() => {
                        onChange(item.key);
                    }}
                />
            ))}
        </View>
    );
};

export default RadioGroup;

**Comment by khushal87** [comment]
Are you getting a tsc error? @mannix-lei

**Comment by khushal87** [comment]
Is it working fine with my snack now? @mannix-lei

**Comment by arpitBhalla** [comment]
Why you want to use a Radio as Input component?

**Comment by khushal87** [comment]
Yes, this could be a better approach. Can I raise a PR for it in the package? @arpitBhalla

**Comment by khushal87** [comment]
https://snack.expo.io/@khushal87/radio-rne this will work. I will raise a PR and solve the label issue.

**Comment by mannix-lei** [comment]
> Why you want to use a Radio as Input component?
That's because product design need it.
I got a form, it needs a Radio, So I use a Radio in an Input component. 
I don't know how to make it better, so I did this and got this error.

**Comment by mannix-lei** [comment]
> Exactly, why do you want so? Because of Formik? @mannix-lei

just because product design.
