### ISSUE TITLE
TypeScript: Header leftComponent doesn't accept iconStyle

### ISSUE THREAD

**Issue by chmac** [react-native-elements/react-native-elements#3032]
**Explain what you did (Required)**

```typescript
import { Header } from "react-native-elements";

const Example = () => (
  <Header
    leftComponent={{
      icon: "menu",
      iconStyle: { padding: 16, margin: -16 },
    }}
  />
);

```

**Expected behavior (Required)**

According to the [docs for Header](https://github.com/react-native-elements/react-native-elements/blob/next/website/docs/props/header.md#leftcomponent) any valid props for Icon should be valid. According to the [docs for Icon](https://github.com/react-native-elements/react-native-elements/blob/next/website/docs/props/icon.md#iconstyle) passing `iconStyle` is valid. I can also confirm that this actually works the styles are applied.

**Describe the bug (Required)**

```
No overload matches this call.
  Overload 1 of 2, '(props: PropsWithChildren<Omit<HeaderProps, keyof ThemeProps<any>>>, context?: any): ReactElement<any, any>', gave the following error.
    Type '{ iconStyle: { padding: number; margin: number; }; }' is not assignable to type 'IntrinsicAttributes & Omit<HeaderProps, keyof ThemeProps<any>> & { children?: ReactNode; }'.
      Property 'iconStyle' does not exist on type 'IntrinsicAttributes & Omit<HeaderProps, keyof ThemeProps<any>> & { children?: ReactNode; }'.
  Overload 2 of 2, '(props: HeaderProps): ReactElement<any, any>', gave the following error.
    Type '{ iconStyle: { padding: number; margin: number; }; }' is not assignable to type 'IntrinsicAttributes & ViewProps & { ViewComponent?: typeof Component; linearGradientProps?: Object; statusBarProps?: StatusBarProps; ... 13 more ...; elevated?: boolean; }'.
      Property 'iconStyle' does not exist on type 'IntrinsicAttributes & ViewProps & { ViewComponent?: typeof Component; linearGradientProps?: Object; statusBarProps?: StatusBarProps; ... 13 more ...; elevated?: boolean; }'.ts(2769)
```

**To Reproduce (Required)**

The snippet above should be enough to see the TypeScript error in VSCode, etc. If you need me to recreate that on snack, just let me know. As it's a typing error I assumed the snack wouldn't be necessary, but if I've misunderstood that, just let me know.

**Further info**

I guess this type here is missing `iconStyle`:

https://github.com/react-native-elements/react-native-elements/blob/26fc8e0e30fb3b549e0961c3b50a0ad040713d7e/src/icons/Icon.tsx#L38-L44

But it also seems to be missing `brand`, `iconProps` and maybe a handful of others if the docs are correct. I'm not quite sure how the docs are maintained, I guess they're not rendered from the TypeScript, so I'm not quite sure how to submit an appropriate PR here. Just adding `iconStyle` seems like it's not quite the right approach. But I'm open to trying my hand here if somebody can offer some guidance. (Caveat, it might take a while for me to get back to this, we work in intermittent sprints).

PS> Thanks to all the folks who make react native elements, it's **epic**. ❤️ ❤️ ❤️

**Comment by khushal87** [comment]
@chmac Can you try using `style` instead of `iconStyle` and tell me if that works?

**Comment by chmac** [comment]
@khushal87 Wow, that was FAST! :-)

Using `style` passes type checking, but the styles are not actually applied. While using `iconStyle` the styles are actually applied to the icon. So in the case of using the padding & negative margin (to fake a hit slop), it works with `iconStyle` and does not work with `style`.

**Comment by khushal87** [comment]
Yes, it is used in the code, but not been defined as a type to Header, that is why tsc checks are failing at your end. @chmac

**Comment by chmac** [comment]
@khushal87 There seem to be a bunch of types missing. I thought maybe they were defined in the code somewhere else and might just need imported? Or maybe they haven't been created at all?

**Comment by khushal87** [comment]
Yes, it seems to be an issue, let me run it on my side and figure it out. Thanks, will keep you posted 😄

**Comment by khushal87** [comment]
@chmac So the issue was that there was a property `style` for both `text` and `icon` in the props therefore the issue was coming up, I have fixed this with the PR #3033 by adding an `iconStyle` property to the IconObject which had overlapping `style`(that of text). This would solve the issue imo.
Note: This segregates the `style` with `iconStyle`.

**Comment by chmac** [comment]
@khushal87 That's epic, thanks a lot for the fast response.

I think the `brand` prop might also be missing. I tried adding it to my code to test, and it comes back with an error. According to this I think it is a boolean:

https://github.com/react-native-elements/react-native-elements/blob/26fc8e0e30fb3b549e0961c3b50a0ad040713d7e/src/icons/Icon.tsx#L48-L60

Maybe it makes sense to also add it in the same PR? But I really don't know, I haven't fully understood the code path so maybe I'm missing something. Either way, thanks a lot, really appreciate the responsiveness.

**Comment by khushal87** [comment]
So currently the icon doesn't import IconProps but IconObject, that is why you don't get the flexibility of using all the props of Icon. @chmac

**Comment by khushal87** [comment]
I understand adding IconProps may add more flexibility and usability, but the admins must have done it for some reason. If I get any response I will surely modify the code to use IconProps too.
