### ISSUE TITLE
[Theme] updateTheme doesn't switching colors on the fly/dynamically (Expo)

### ISSUE THREAD

**Issue by DenysMoro** [react-native-elements/react-native-elements#3037]
**Explain what you did (Required)**
Hi. We are using RNE and we are trying to change theme on the fly. We are using hook `useTheme` and method `updateTheme` to switch colors. I've attached repo with example

**Expected behavior (Required)**
We want have ability to switch Theme dynamically. We can do it now with local state of the main parent component and then pass it through all child component

Parent:
```
const [theme, setTheme] = useState(initialTheme)

if (...) { setTheme(theme2) } else { ... }

<ThemeProvider theme={theme}>
  {this.props.children}
</ThemeProvider>
```
Child:
```
const { theme } = useTheme()

<View style={{ color: theme.colors.primary }} />
```

Do you have any ideas how we can use `updateTheme`?

**Describe the bug (Required)**
We can't change theme colors on the fly with `updateTheme` method usage

**To Reproduce (Required)**
Repo - https://github.com/DenysMoro/rne-updateTheme-runtime
Release channel - https://expo.io/@taranis/projects/rne-updateTheme-runtime?release-channel=rne-updatetheme-runtime

**Screenshots (Required)**

https://user-images.githubusercontent.com/77282657/118392398-42381300-b642-11eb-8bdc-02c9c6c868a6.mov

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   3.4.1      |
| react-native          |    0.63.2     |

**Comment by arpitBhalla** [comment]
Hey @DenysMoro can you check https://snack.expo.io/@arpitbhalla/rne-theme

**Comment by DenysMoro** [comment]
Yes. It works in such way. I've implemented such functionality for now, but I believe we need to have ability to switch colors/theme on the fly out of the box (out of the RNE)

**Comment by dinhbt** [comment]
Hi DenysMor,

I think issue exist in file ThemeProvider.tsx.
You can create pull request and change code on below.
`
static getDerivedStateFromProps(
    props: {
      theme: Theme;
      useDark?: boolean;
    },
    state: ThemeProviderState
  ) {
    const { useDark } = props;
    const isTheme = (theme: Partial<FullTheme>) => {
      return !(Object.keys(theme).length === 0 && theme.constructor === Object);
    };
    //isTheme will check if the theme is provided by user and will update the theme only if its provided by user
    //Not checking if the theme exist or not will always result in if statement getting executed as props.theme !== state.theme if theme is not provided
    if (
      useDark !== state.useDark ||
      (isTheme(props.theme) && props.theme !== state.theme)
    ) {
      const defaultColors = useDark ? darkColors : colors;
      return {
        theme: deepmerge(
          deepmerge(
            {
              colors: defaultColors,
            },
            props.theme
          ),
          state.theme
        ),
        useDark,
      };
    }
    return null;
  }
`

**Comment by brataaaan** [comment]
@DenysMoro Did you find a workaround?
