### ISSUE TITLE
Update docs for: Text styles with themeprovider not working on Android.

### ISSUE THREAD

**Issue by deekshith4450** [react-native-elements/react-native-elements#3042]
**Explain what you did (Required)**
With the help of theme provider i was trying to use same text styles where ever i needed them inside the app.

**Expected behavior (Required)**
Currently it working with ios. I have no idea why it is not working on Android. (Please correct if i am doing any thing wrong.)

**Describe the bug (Required)**
I have couple of custom fonts and those are font styles are used through out the app. Instead using them on every text component style i wanted to use theme provider. Text styles with custom fonts work as expected on ios but on Android it does not.

**To Reproduce (Required)**

```
const theme = {
	Text: {
		h1Style: {
			fontSize: 24,
			fontFamily: 'Museo-slab',
		},
		h2Style: {
			fontSize: 18,
			fontFamily: 'Museo-sans',
		},
		h4Style: {
			fontSize: 18,
			fontFamily: 'Museo-slab',
		},
		h3Style: {
			fontSize: 16,
			fontFamily: 'Museo-sans',
		},
	},
	Button: {
		titleStyle: {
			fontSize: 18,
			fontFamily: 'Museo-sans',
		},
		buttonStyle: {
			borderRadius: 4,
		},
	},
};

```
ThemeProvider wrapped around app.js
```
function App() {
	const isLoadingComplete = useCachedResources();
	const colorScheme = useColorScheme();
	if (!isLoadingComplete) {
		return null;
	} else {
		return (
			<ThemeProvider theme={theme}>
				<SafeAreaProvider>
					<Route  />
					<Toast ref={(ref) => Toast.setRef(ref)} />
					<StatusBar backgroundColor={Colors.primary.primaryDark} />
				</SafeAreaProvider>
			</ThemeProvider>
		);
	}
}
export default App;

```
This is how i am using it.
```
import React from 'react';
import { View, StyleSheet } from 'react-native';
import { Text } from 'react-native-elements';
const AccountCreationHeading = ({ heading, style }: any) => {
	return (
		<View>
			<Text h1 h1Style={style}>
				{heading}
			</Text>
		</View>
	);
};

export default AccountCreationHeading;
```

**Screenshots (Required)**
<img width="515" alt="Screen Shot 2021-05-19 at 12 09 31 AM" src="https://user-images.githubusercontent.com/63818399/118759467-b3401c00-b836-11eb-9aa0-c1520e8c5a2a.png">

<img width="471" alt="Screen Shot 2021-05-19 at 12 09 26 AM" src="https://user-images.githubusercontent.com/63818399/118759492-c2bf6500-b836-11eb-9ffa-9604cad51b68.png">

Student login on Android should look like Student login on ios.

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  3.4.1       |
| react-native          |         |

**Comment by warrendeleon** [comment]
Hello @deekshith4450,

Have you tried using `makeStyles()`? Docs [here](https://reactnativeelements.com/docs/customization/#using-the-theme-in-your-own-components)

```
const AccountCreationHeading = ({ heading, style }: any) => {
  const styles = useStyles()
	return (
		<View>
			<Text h1 h1Style={styles.h1Style}>
				{heading}
			</Text>
		</View>
	);
};

const useStyles = makeStyles((theme) => ({
  h1Style: {}
})

export default AccountCreationHeading;
```
