### ISSUE TITLE
Image component does not render base64 

### ISSUE THREAD

**Issue by seankonig** [react-native-elements/react-native-elements#3043]
**Explain what you did (Required)**

Use expo-camera takePictureAsync(options) to take image. I pass the base64: true property to options and successfully get a base64 string back

**Expected behavior (Required)**

I expected that I can set this string(`data:image/jpg;base64,${base64}`) on the source uri property and see my image

**Describe the bug (Required)**

No image is displayed. 

If I simply use Image from react-native it all works as it should. No changes to how I retrieve the string or set the property.

**To Reproduce (Required)**

use expo-camera to capture an image and try to display the base64 string using React Native Element Image component

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
"react-native-elements": "^3.3.2",
"react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
"expo": "~41.0.0",

**Comment by arpitBhalla** [comment]
Hey @seankonig It works, https://snack.expo.io/@arpitbhalla/3043, I guess you are not giving style prop

**Comment by arpitBhalla** [comment]
Hey @seankonig It works, https://snack.expo.io/@arpitbhalla/3043, I guess you are not using style prop

**Comment by seankonig** [comment]
Yeah that's strange. I don't see the same behaviour on my side and width and height set. Not a major issue, simply changing the import to react-native library works. Just thought I would mention it
