### ISSUE TITLE
SearchBar: Property 'round' does not exist on type - Typescript error

### ISSUE THREAD

**Issue by pweisensee** [react-native-elements/react-native-elements#3045]
**Explain what you did (Required)**

Trying to render a rounded SearchBar component in Typescript

**Expected behavior (Required)**
SearchBar renders rounded with no errors or warnings

**Describe the bug (Required)**

Typescript shows error for rounded SearchBar, even though it is a documented Prop.

**To Reproduce (Required)**
```
<SearchBar
    multiline={false}
    onFocus={this.onPress}
    placeholder="Search for anything..."
    round
/>
```

**Screenshots (Required)**

![Screen Shot 2021-05-20 at 5 38 38 PM](https://user-images.githubusercontent.com/6617776/119057545-480b5c80-b992-11eb-958b-3a9942662957.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     3.4.1    |
| react-native          |     0.63.2    |
| expo          |     40.0.1  |
| typescript          |    4.2.4  |

**Comment by arpitBhalla** [comment]
Would you like to open a PR?

**Comment by saideepesh000** [comment]
Hey @arpit-bhalla , can I work on this, u can assign me
