### ISSUE TITLE
Playground in the Document Website

### ISSUE THREAD

**Issue by Enesklmc** [react-native-elements/react-native-elements#3048]
Hi, can i volunteer to do this project? if there is no one doing and there is no plan about to saving the idea for the next Gsoc.

**Comment by arpitBhalla** [comment]
I guess @hetanthakkar1 is doing this, you can joinly do I guess

**Comment by hetanthakkar1** [comment]
@Enesklmc I have talked with mentors regarding same we can do this! Mentors have agreed with my approach

**Comment by hetanthakkar1** [comment]
@Enesklmc I have talked with mentors regarding same. Mentors have agreed with my approach. You can join me

**Comment by Enesklmc** [comment]
I would like to join if you are okay. By the way which stage are you at and where are you guys communicating from?

**Comment by arpitBhalla** [comment]
I am from Mars

**Comment by hetanthakkar1** [comment]
@Enesklmc I am currently trying to obtain webpack config for react native elements

**Comment by Enesklmc** [comment]
actually i did that docusaurus config. i can save your time [here the pull request](https://github.com/react-native-elements/react-native-elements/pull/2959)

**Comment by hetanthakkar1** [comment]
@Enesklmc Can we converse on slack?

**Comment by jugshaurya** [comment]
@hetanthakkar1, who(mentor) agreed to your approach, i think your approach was to build a new website, can you share your proposal or some lines about your approach. We can discuss it.

**Comment by Enesklmc** [comment]
yeah there might be approaching differences [my proposal](https://docs.google.com/document/d/1G0xbzFGfoVOnbEKnKt7dSuVY5f6Onl9J1Zt_kMZ8qMU/edit?usp=sharing) about minimized playgorund

**Comment by pranshuchittora** [comment]
Hello everyone feel free to work on this :)
