### ISSUE TITLE
Rating rendered as square instead of star in release/archive mode

### ISSUE THREAD

**Issue by junqdu** [react-native-elements/react-native-elements#3053]
Dev:
![Screen Shot 2021-05-27 at 2 20 45 AM](https://user-images.githubusercontent.com/4250728/119801218-5bd32900-be92-11eb-8323-6dd75e8860d4.png)

Release/Archive, build with `react-native run-ios --configuration Release`
![Screen Shot 2021-05-27 at 2 17 24 AM](https://user-images.githubusercontent.com/4250728/119801286-6988ae80-be92-11eb-8e15-1a7abe6da260.png)

**Comment by khushal87** [comment]
Are you having a flex style above? 
Check this: https://snack.expo.io/AXs5tbIEQ it should work.
