### ISSUE TITLE
Header borderBottomColor not working

### ISSUE THREAD

**Issue by KrisLau** [react-native-elements/react-native-elements#3055]
**Explain what you did (Required)**
I set the borderBottomWidth to 5 and borderBottomColor to orange but the only thing that appeared was a grey border line.  It seems to be similar to what happened in #2234 but the fix there (specifying borderBottom instead of just border for both the color and width) didn't work for me. I have worked around the bug by just putting a View with a top border around my components under the header but it would be nice to be able to just put the border on the header.

**Expected behavior (Required)**
I wanted an orange bottom border on the header.

**Describe the bug (Required)**
borderColor on the header isn't working; Applying a border always ends up with a grey line as shown in the screenshot and in the snack.

**To Reproduce (Required)**
https://snack.expo.io/@kris_lau/header

**Screenshots (Required)**
![image](https://user-images.githubusercontent.com/46275463/119845828-37497200-becf-11eb-8483-b60ab0897c8c.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    ^3.4.1     |
| react-native          |    ^0.64.0     |

**Comment by khushal87** [comment]
Hey, @KrisLau you had a type `borderBottomColorColor` which should be actually `borderBottomColor`. Kindly fix this and this will work.
Ref: https://snack.expo.io/JWb5Ck8N2

**Comment by KrisLau** [comment]
@khushal87 Can't believe I missed that! Sorry for the trouble and thanks for the help!
