### ISSUE TITLE
Dialog component doesn't work on web

### ISSUE THREAD

**Issue by khushal87** [react-native-elements/react-native-elements#3057]
**Explain what you did (Required)**
Run the rne-app on the web and tested the Dialog component.

Was analyzing the behavior of the component in the web.
**Expected behavior (Required)**
It should work as in android/ios.

**Describe the bug (Required)**
The dialogs don't open and the UI breaks on the web.

**To Reproduce (Required)**
Run the rne-app on web/ Use the dialog component on web.

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Screenshots (Required)**
![Screenshot from 2021-05-27 22-55-41](https://user-images.githubusercontent.com/39884168/119870186-b2963c80-bf3e-11eb-9269-d0623ea7ae10.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |         |
| react-native          |         |

**Comment by khushal87** [comment]
@Dhananjayan-PN Can you look into the issue? Also kindly refer #3056 for improvements in the code of the component. Thanks.

**Comment by Dhananjayan-PN** [comment]
@khushal87 On it!
