### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by rambleraptor** [react-native-elements/react-native-elements#3061]
I would've asked this in the Slack, but it appears that the Heroku app for joining is [down](https://github.com/react-native-elements/react-native-elements/issues/3060).

Huge fan of the library and really excited for ListItem.Swipable. Any idea when the next release will be?

**Comment by arpitBhalla** [comment]
Will be comming soon,

**Comment by arpitBhalla** [comment]
You can try with next version

**Comment by pranshuchittora** [comment]
Hi @rambleraptor 
The slack invite app runs on free tier of Heroku, it seems like we have exhausted our monthly limit. It will be up automatically from next month.
