### ISSUE TITLE
SocialIcon: Renders as button with 'raised={false}' and 'light={true}' props

### ISSUE THREAD

**Issue by rishabhsxn** [react-native-elements/react-native-elements#3065]
**Explain what you did (Required)**
I was trying to render the light themed 'facebook' SocialIcon without the elevation.
I checked on both android and iOS, facing the same issue.

**Expected behavior (Required)**
```javascript
<SocialIcon` type="facebook" raised={false} light />
```
should render
![image](https://user-images.githubusercontent.com/48175786/120930214-fdb40a80-c709-11eb-9ffe-7272a6fe50ae.png)

**Actual behavior**
But, it renders:  
![image](https://user-images.githubusercontent.com/48175786/120930431-d6117200-c70a-11eb-9a5b-f201f08647a8.png)

**Describe the bug (Required)**
* This behaviour is shown only when raised={false} and  light={true}, not in any other combination of these two props.
* Doesn't show expected behaviour even when you pass button={false} with raised={false} and light={true}.

**To Reproduce (Required)**
https://snack.expo.io/Bez6JulMd

**Screenshots (Required)**
![image](https://user-images.githubusercontent.com/48175786/120930989-46b98e00-c70d-11eb-9442-d4a594a2d255.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    3.4.1     |
| react-native          |     0.63.2    |
| expo          |     41.0.1    |

**Comment by arpitBhalla** [comment]
```javascript 
      <SocialIcon
        style={{
          width: 42,
          height: 42,
        }}
        type="facebook"
        raised={false}
        light={true}
      />
```
This can be reconsidered
https://github.com/react-native-elements/react-native-elements/blob/08c0cb0edea6f4c2f12396a93c37cbf107c2d2fa/src/social/SocialIcon.tsx#L147
