### ISSUE TITLE
SocialIcon: Overall icon size doesn't change when prop raised={true}

### ISSUE THREAD

**Issue by rishabhsxn** [react-native-elements/react-native-elements#3066]
**Explain what you did (Required)**
I was trying to render the SocialIcon with an iconSize of less than default of 24.

**Expected behavior (Required)**
The overall size of icon should decrease.
```javascript
<SocialIcon type="facebook"  iconSize={16} />
```
should look like
![image](https://user-images.githubusercontent.com/48175786/120933128-496cb100-c716-11eb-9a4a-847ace52fbfd.png)

**Actual behavior**
But it only decreased the size of inner symbol:
![image](https://user-images.githubusercontent.com/48175786/120933186-9b153b80-c716-11eb-8bd7-8ed978130abf.png)

**Describe the bug (Required)**
* It shows same unexpected behaviour of outer wrapper unable to adapt to the passed iconSize prop for both: increasing or decreasing the iconSize from default of 24 pixels.
* This unexpected behaviour is not shown when we set raised={false}.
* This issue may be related to issue #3065 

**To Reproduce (Required)**
https://snack.expo.io/@rishabhsxn/socialicon-bug2

**Screenshots (Required)**
![image](https://user-images.githubusercontent.com/48175786/120933676-c8fb7f80-c718-11eb-8bfc-33deabb907ed.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    3.4.1     |
| react-native          |      0.63.2   |
| expo           |      41.0.1  |

**Comment by rishabhsxn** [comment]
When I removed !raised and !light from the conditional statement in : 
https://github.com/react-native-elements/react-native-elements/blob/08c0cb0edea6f4c2f12396a93c37cbf107c2d2fa/src/social/SocialIcon.tsx#L147

both the issue #3065 and #3066 were solved in my project. I am new to open-source contribution, I would love if anyone can guide me.
Please let me know if my suggested solution is correct or not. If yes, how could I submit it for PR?

**Comment by khushal87** [comment]
@rishabhsxn How can I help you with raising a PR, where are you facing issues, can you be specific?

**Comment by rishabhsxn** [comment]
I was confused with the different branches and test suites. I figured it out and made a PR.
Thank you @khushal87 for being open to help. I'll ping you if I get stuck. :)

**Comment by souviknsl07** [comment]
Can anyone help me? I am very new to open-source. My question is how to check the changes in the components. Like in this case, suppose I made a change to the SocialIcon.tsx then how to check if it's working properly or not like seeing the UI of the social icon itself and how the changes affected it. It might seem silly but I haven't worked on something like this before so any kind of help would be much appreciated. @khushal87 @flyingcircle
