### ISSUE TITLE
autoCompleteTypes works only in Expo Go.

### ISSUE THREAD

**Issue by AugustinasMK** [react-native-elements/react-native-elements#3067]
**Explain what you did (Required)**

Created 2 <Input> elements for "Email" and "Password" and set them to correct autoCompleteTypes.

**Expected behavior (Required)**

Both in Expo Go and in Standalone Apps, the context menu (Samsung Pass on my device) shows up.

**Describe the bug (Required)**

The context menu shows up only in Expo Go. After building a standalone app, the menu does not show up. If I use <TextInput> from RN, it works correctly in both environments.

**To Reproduce (Required)**

Have a simple login form with 2 input fields and a button that leads to another screen. 
Set the autocomplete types for the inputs.
Build a standalone app with expo tools.
Fill in the information for the first time. 
Information should be saved.
Reopen the app and see if saved information is provided.

**Screenshots (Required)**

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements | 3.4.1        |
| react-native          | 0.63.2        |
| expo                     | 41.0.1        |

**Comment by flyingcircle** [comment]
I'm honestly not seeing how this could be related to RNE. We don't do anything with this, the props like this get passed directly to `TextInput`. I see a couple of tickets in React Native open that look relevant though such as this one:

https://github.com/facebook/react-native/issues/31518

This looks like a RN issue.
