### ISSUE TITLE
ListItemSubtitle is invisible in dark theme

### ISSUE THREAD

**Issue by andkom** [react-native-elements/react-native-elements#3069]
**Explain what you did (Required)**

**Expected behavior (Required)**

In dark mode list item subtitle should be light

**Describe the bug (Required)**

In dark mode list item subtitle is dark so it's invisible on dark background.

**To Reproduce (Required)**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

```
<ThemeProvider useDark={true}>
    <ListItem>
        <ListItem.Subtitle>Subtitle</ListItem.Subtitle>
    </ListItem>
</ThemeProvider>
```

**Screenshots (Required)**

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   3.4.1      |
| react-native          |   0.64.2      |

**Comment by arpitBhalla** [comment]
https://github.com/react-native-elements/react-native-elements/blob/09d6f780245b03e0156b12edf5076b7396038d9c/src/list/ListItemSubtitle.tsx#L40
This might be reconsidered, would you like to create a PR
