### ISSUE TITLE
Dialog component container style 

### ISSUE THREAD

**Issue by chinieer** [react-native-elements/react-native-elements#3076]
I feel puzzled that style name childrenContainer in [https://github.com/react-native-elements/react-native-elements/blob/next/src/dialog/Dialog.tsx](url)
`
 childrenContainer: {    marginBottom: 5,  }`

**Explain what you did (Required)**

it leads to produce extra space when i just use loading and cannot rewrite it directly
remove this style

**Expected behavior (Required)**

**Describe the bug (Required)**

**To Reproduce (Required)**

**Screenshots (Required)**

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    3.4.2     |
| react-native          |     0.63.4    |

**Comment by arpitBhalla** [comment]
@Dhananjayan-PN kindly look into this, 🙂

**Comment by ritwik-boringnews** [comment]
hi can i work on this

**Comment by arpitBhalla** [comment]
@ritwik-boringnews Go ahead

**Comment by Manan17** [comment]
Hi, can I work on this @arpitBhalla

**Comment by ritwik-boringnews** [comment]
I am currently working
