### ISSUE TITLE
Customizing ListItemCheckbox in theme

### ISSUE THREAD

**Issue by jorgegvallejo** [react-native-elements/react-native-elements#3082]
**Explain what you did (Required)**

Trying to custom theme list items that include checkboxes

**Expected behavior (Required)**

Being able to change the style, doing something like this:

```
"ListItemCheckbox":{
  "size": 30
 }
```

**Describe the bug (Required)**

Changing the ListItemCheckbox `size`, `style` or `containerStyle` didn't have any effect.

**Your Environment (Required):**

react-native-elements  3.4.1
react-native   0.64.0

**Comment by ShivamTyagi12345** [comment]
HI @jorgegvallejo . I am fairly new to OS and want to work on this issue.

For this issue,the following is where I am getting started with :
[https://reactnativeelements.com/docs/web_usage](url)

please, respond with any other helpful resources (if any)

**Comment by souviknsl07** [comment]
@jorgegvallejo In my case, I am able to change the size and containerStyle is working fine too.

My Environment:
react-native-elements: 3.4.1
react-native: 0.63.4

**Comment by arpitBhalla** [comment]
He wants to change in theme, for each checkbox

**Comment by souviknsl07** [comment]
> He wants to change in theme, for each checkbox

Could you explain it to me what does that mean? I am pretty new

**Comment by arpitBhalla** [comment]
https://reactnativeelements.com/docs/customization#theme

**Comment by souviknsl07** [comment]
> https://reactnativeelements.com/docs/customization#theme

Ya I checked it just now..Thanks

**Comment by arpitBhalla** [comment]
Hey @jorgegvallejo You need to use `ListItemCheckBox` Capital B

**Comment by arpitBhalla** [comment]
Check This https://snack.expo.io/@arpitbhalla/3082

**Comment by arpitBhalla** [comment]
https://github.com/react-native-elements/react-native-elements/blob/c94e84701e4cf9fdbfe882e09b2b61acb61b5873/src/config/theme.tsx#L63

**Comment by flyingcircle** [comment]
Awesome catch @arpitBhalla Not a bug.

**Comment by jorgegvallejo** [comment]
> Hey @jorgegvallejo You need to use `ListItemCheckBox` Capital B

Thank you my man
