### ISSUE TITLE
Nothing happens when click on tabs

### ISSUE THREAD

**Issue by stephenjen** [react-native-elements/react-native-elements#3083]
**Explain what you did (Required)**
Followed usage code for tabs

**Expected behavior (Required)**
On click on any non-open tabs, expected clicked tab and content to change.

**Describe the bug (Required)**
Tabs and tab content did not change.

**To Reproduce (Required)**

# Snack
https://snack.expo.io/aVc0QiC64

# Steps
1. Click on FAVORITE OR CART ta bs
2. Nothing happens

**Screenshots (Required)**

<img width="331" alt="image" src="https://user-images.githubusercontent.com/8771850/121996965-1f815180-cddc-11eb-91ed-643af3a6bc18.png">

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements | 3.4.2 |
| react-native          | 0.63.4 |

**Comment by arpitBhalla** [comment]
You need to add onChange handler and put value of index

**Comment by arpitBhalla** [comment]
This is wrong in your code `const { index, setIndex } = useState(0);`

**Comment by arpitBhalla** [comment]
Check this https://snack.expo.io/@arpitbhalla/3083

**Comment by stephenjen** [comment]
😱  Thanks!

**Comment by stephenjen** [comment]
😱

Thanks!
