### ISSUE TITLE
Can't updateTheme

### ISSUE THREAD

**Issue by dinhbt** [react-native-elements/react-native-elements#3088]
Hi team,
I have an issue when call updateTheme.  You can check this problem on below.

```
import * as React from 'react';
import { View, StyleSheet } from 'react-native';
import { Button, withTheme, ThemeProvider } from 'react-native-elements';

const theme = {
  colors: {
    primary: 'yellow',
  },
};

const AppText = withTheme(({ updateTheme }) => {
  return (
    <View style={styles.container}>
      <Button
        title="Hey"
        onPress={() =>
          updateTheme({
            colors: {
              primary: 'pink',
            },
          })
        }
      />
    </View>
  )
});

export default () => (
  <ThemeProvider theme={theme}>
    <AppText />
  </ThemeProvider>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: 10,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});

```
I checked and found issue line 61 to 69 in (https://github.com/react-native-elements/react-native-elements/blob/4f90e00919f4897a9a1320f74c8203ba7ec9e9f2/src/config/ThemeProvider.tsx)

I resloved issue with code on below. Can you update it ?
`
 static getDerivedStateFromProps(props, state) {
    const { useDark } = props;
    if (useDark !== state.useDark) {
      const defaultColors = useDark ? darkColors : colors;
      return {
        theme: deepmerge(
          deepmerge(
            {
              colors: defaultColors,
            },
            props.theme
          ),
          state.theme
        ),
        useDark,
      };
    }
    return null;
  }
`

Thanks,
Please help me!

**Comment by arpitBhalla** [comment]
> I resloved issue with code on below. Can you update it ?
Can you review https://github.com/react-native-elements/react-native-elements/pull/3027
