### ISSUE TITLE
FlatList is not scrollable inside TabView

### ISSUE THREAD

**Issue by marcuiulian13** [react-native-elements/react-native-elements#3091]
**Explain what you did (Required)**
Using `TabView` and `TabView.Item`, containing a list inside the `TabView.Item`.

**Expected behavior (Required)**
The list inside the `TabView` should continue to be scrollable.

**Describe the bug (Required)**
When having a `FlatList` inside a `TabView.Item`, the scrolling of the list is broken - you can only scroll if you very quickly swipe the screen.

**To Reproduce (Required)**
I created this Snack:
https://snack.expo.io/2K8V8ALHy

You will notice that, in the browser, everything seems to work. If you actually use Expo GO and scan the app to run it on your device, you will be able to reproduce the bug - not being able to scroll the list in the first tab.

**Screenshots (Required)**
![image](https://user-images.githubusercontent.com/3667966/122680858-51822180-d1e9-11eb-97df-0471d677d8eb.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements | 3.4.2 |
| react-native          | Expo 40 |

**Comment by arpitBhalla** [comment]
I am able to do it in Android

**Comment by marcuiulian13** [comment]
I've tested this on a Pixel 4 XL (Android). Does this work straight away for you?

**Comment by arpitBhalla** [comment]
Yep wworkinv fine
https://user-images.githubusercontent.com/55053424/122680992-ccf6c980-d20f-11eb-9045-469aeb4aa743.mp4

**Comment by marcuiulian13** [comment]
Very odd, I tried restarting my device and also enabling the navigation bar in Android and I can still reproduce on my device in both cases.

**Comment by marcuiulian13** [comment]
A similar behaviour can be seen in the Snack I attached if you test on iOS in the browser - the list is scrolled just a few pixels when dragging.

**Comment by arpitBhalla** [comment]
Do you think it is due to PanResponder used in TabView?

**Comment by marcuiulian13** [comment]
I don't have any experience with the `PanResponder` unfortunately, but I would imagine that the issue is it capturing all the events, even the ones in the children... I tried using `preventDefault` and `stopPropagation` in the list `onScroll` handler, but that does nothing.

**Comment by ruiaraujo012** [comment]
I have almost the same problem if I put a ScrollView inside a TabView.Item the content of the ScrollView disappears

Without
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/16304685/122913961-0899ac80-d352-11eb-94ca-b1e17c3080d9.png)

With ScrollView
![MicrosoftTeams-image](https://user-images.githubusercontent.com/16304685/122914034-2109c700-d352-11eb-8a4e-3ead127f2ccb.png)

**Comment by arpitBhalla** [comment]
> I have almost the same problem if I put a ScrollView inside a TabView.Item the content of the ScrollView disappears

@ruiaraujo012 Can you share a snack of your code, btw UI looks great

**Comment by ruiaraujo012** [comment]
> > I have almost the same problem if I put a ScrollView inside a TabView.Item the content of the ScrollView disappears
> 
> @ruiaraujo012 Can you share a snack of your code, btw UI looks great

Oh, nvm, I have a Tab content inside a View without styles, if I put flex: 1 in that View this works as expected.

https://snack.expo.io/wju-jRn2b

Thanks anyway

**Comment by ruiaraujo012** [comment]
Now, it work on android but in ios the scroll is buggy and not work as expected, if you try the same code but on ios device it won't work

**Comment by huyhomie66** [comment]
> Now, it works on android but in ios, the scroll is buggy and not work as expected if you try the same code but on an ios device, it won't work.
> 
> Edit:
> It can be "fixed" with the following code, but the swipe left/right to move between tabs stops working. I think I will use this approach for now, when this bug is fixed I will roll back my solutions.
> 
> `<TabView.Item onMoveShouldSetResponder={(e) => e.stopPropagation()}>`

you save my life thanks

**Comment by ruiaraujolink** [comment]
> > Now, it works on android but in ios, the scroll is buggy and not work as expected if you try the same code but on an ios device, it won't work.
> > Edit:
> > It can be "fixed" with the following code, but the swipe left/right to move between tabs stops working. I think I will use this approach for now, when this bug is fixed I will roll back my solutions.
> > `<TabView.Item onMoveShouldSetResponder={(e) => e.stopPropagation()}>`
> 
> you save my life thanks

I'm glad to hear this :D

**Comment by samijnih** [comment]
> Now, it works on android but in ios, the scroll is buggy and not work as expected if you try the same code but on an ios device, it won't work.
> 
> Edit:
> It can be "fixed" with the following code, but the swipe left/right to move between tabs stops working. I think I will use this approach for now, when this bug is fixed I will roll back my solutions.
> 
> `<TabView.Item onMoveShouldSetResponder={(e) => e.stopPropagation()}>`

Same issue with tab item and scrollview inside. Anyway, thanks @ruiaraujolink for the hack

**Comment by ruiaraujolink** [comment]
> > Now, it works on android but in ios, the scroll is buggy and not work as expected if you try the same code but on an ios device, it won't work.
> > Edit:
> > It can be "fixed" with the following code, but the swipe left/right to move between tabs stops working. I think I will use this approach for now, when this bug is fixed I will roll back my solutions.
> > `<TabView.Item onMoveShouldSetResponder={(e) => e.stopPropagation()}>`
> 
> Same issue with tab item and scrollview inside. Anyway, thanks @ruiaraujolink for the hack

You are welcome!

**Comment by aleantoniolli** [comment]
Has this been resolved?

**Comment by richagain** [comment]
> Now, it works on android but in ios, the scroll is buggy and not work as expected if you try the same code but on an ios device, it won't work.
> 
> Edit: It can be "fixed" with the following code, but the swipe left/right to move between tabs stops working. I think I will use this approach for now, when this bug is fixed I will roll back my solutions.
> 
> `<TabView.Item onMoveShouldSetResponder={(e) => e.stopPropagation()}>`

I have same issue on iOS device. I am using this approach for now, but expecting to have the swip to switch tab function back.

**Comment by MarouaniALA** [comment]
I have same issue, I found a tempo solution by creating VirtualizedView component because 2 scroll in the same orientation will throw a warning and put the tabView inside it also used @ruiaraujo012 solution for better performance


```
export default function VirtualizedView({
                                            children,
                                            getRef, ...props
                                        }: { children?: any, getRef?: any } & FlatListProps) {
    const {data, renderItem, ...otherProps} = props
    const flatListRef = useRef();

    useEffect(() => {
        if (getRef && flatListRef.current)
            getRef(flatListRef.current)

    }, [flatListRef]);


    function header() {
        return <React.Fragment>{children}</React.Fragment>;
    }

    return (
        <FlatList
            ref={flatListRef}
            data={[]}
            ListEmptyComponent={null}
            renderItem={null}
            ListHeaderComponent={header()}
            {...otherProps}
        />
    );
}

```
```

export function TabsScreen() {
    const [index, setIndex] = useState(0);
    const [listRef, setlistRef] = useState<FlatList>();

    useEffect(() => {
        listRef?.scrollToOffset({ animated: true, offset: 0 })
    }, [index]);

    return (
        <View>
            <Tab
                indicatorStyle={{backgroundColor: Colors.primary}}
                value={index} onChange={setIndex}>
                <Tab.Item
                    containerStyle={styles.itemContainer}
                    titleStyle={[index === 0 ? styles.selectedItem : styles.unSelectedItem, styles.tabTitleTxt]}
                    title="Tab1"/>

                <Tab.Item
                    containerStyle={styles.itemContainer}
                    titleStyle={[index === 1 ? styles.selectedItem : styles.unSelectedItem, styles.tabTitleTxt]}
                    title="Tab2"/>
            </Tab>

            <VirtualizedView
                getRef={(ref) => {
                    setlistRef(ref);
                }}
                contentContainerStyle={GlobalStyle.bgTransparent}>

                    <TabView value={index} onChange={setIndex}>
                        <TabView.Item
                            onMoveShouldSetResponder={(e) => {
                                e.stopPropagation();
                                return e.isPropagationStopped();
                            }}
                            style={styles.tabView}>

                            <FlatList
                                keyExtractor={item => item?.id.toString()}
                                data={[{id: 1}, {id: 2}, {id: 3}, {id: 4}, {id: 5}, {id: 6},]}
                                renderItem={({item}) => <ExchangeBox/>}

                            />
                        </TabView.Item>

                        <TabView.Item style={styles.tabView}>
                            <StyledText>Recent</StyledText>
                        </TabView.Item>
                    </TabView>
            </VirtualizedView>
        </View>
    )
}
```
hope it helps

**Comment by afrojuju1** [comment]
@ ruiaraujolink fix worked like a charm. thank you for saving me from days of debugging

**Comment by yasindemir94** [comment]
> Now, it works on android but in ios, the scroll is buggy and not work as expected if you try the same code but on an ios device, it won't work.
> 
> Edit: It can be "fixed" with the following code, but the swipe left/right to move between tabs stops working. I think I will use this approach for now, when this bug is fixed I will roll back my solutions.
> 
> `<TabView.Item onMoveShouldSetResponder={(e) => e.stopPropagation()}>`

thank you sooooooo much but i'm still thinking why it doesn't work on ios. i mean what cause that ?

**Comment by attackonryan** [comment]
> Now, it works on android but in ios, the scroll is buggy and not work as expected if you try the same code but on an ios device, it won't work.
> 
> Edit: It can be "fixed" with the following code, but the swipe left/right to move between tabs stops working. I think I will use this approach for now, when this bug is fixed I will roll back my solutions.
> 
> `<TabView.Item onMoveShouldSetResponder={(e) => e.stopPropagation()}>`

fix the worst issue in my graduation project.  thanks

**Comment by arpitBhalla** [comment]
This change will be available in next release. You can try this, by installing [Bleeding Edge ](https://reactnativeelements.com/docs/next/installation) version

or you can try with expo template
```bash
expo init app --template @rneui/template@bleeding-edge
```

**Comment by oleandrosiq** [comment]
Hey guys, I managed to solve my problem by following this question https://stackoverflow.com/questions/68502633/react-native-why-is-my-flatlist-not-displaying

Props that I added to my flatList to work.

`maxToRenderPerBatch={1000}`
`windowSize={60}`
`updateCellsBatchingPeriod={50}`
`initialNumToRender={50}`

Hope this helps you too <3
