### ISSUE TITLE
Input not registering in Overlay except input

### ISSUE THREAD

**Issue by Cortlandd** [react-native-elements/react-native-elements#3093]
**Explain what you did (Required)**
I implemented a modal with an input and a button

**Expected behavior (Required)**
I should be able to open the overlay and click the button or tap the backdrop to close without needing to open the overlay.

**Describe the bug (Required)**
The backdrop input and the button aren't responding unless i click inside the input first.

**To Reproduce (Required)**
See my sample code:

```ruby
<Overlay isVisible={overlayVisible} onBackdropPress={() => setOverlayVisible(false)}>
        <KeyboardAvoidingView style={{ width: 350, padding: 20 }}>
          <Text style={{ fontSize: 24, fontWeight: '500', textAlign: 'center' }}>Profile Image</Text>
          <View style={{ alignItems: 'center', justifyContent: 'center' }}>
            <Input
              value={urlInput}
              onChangeText={(value) => setUrlInput(value)}
              placeholder={'Enter URL to Image'}
              rightIcon={(<Icon name={'arrow-forward'} color={'white'} style={{ backgroundColor: Utils.isValidURL(urlInput) ? '#2089dc' : 'lightgray', borderRadius: 50, padding: 5 }} type={'ionicon'} />)}
            />
          </View>
          <Text style={{ fontSize: 16, fontWeight: '400', textAlign: 'center', marginBottom: 10, color: 'gray' }}>Or</Text>
          <Button
            icon={
              <Icon name={'image'} type={'ionicon'} color={'white'} />
            }
            title={'Upload Image'}
            raised
            onPress={handleImageUpload}
          />
        </KeyboardAvoidingView>
</Overlay>
```

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     3.3.1    |
| react-native          |     0.63.4    |

**Comment by arpitBhalla** [comment]
Working fine for `react-native-elements@latest` on Android

**Comment by Cortlandd** [comment]
> Working fine for `react-native-elements@latest` on Android

same, but with ios simulator. not much luck as all.

**Comment by arpitBhalla** [comment]
https://snack.expo.io/@arpitbhalla/3093


https://user-images.githubusercontent.com/55053424/123266367-9247a680-d519-11eb-9f84-16385d5a51fc.mp4

**Comment by Cortlandd** [comment]
Thanks for this. I updated the package and adjusted the overlay position and it seems to be working now. Much obliged
