### ISSUE TITLE
Card

### ISSUE THREAD

**Issue by kkrishna-choudhary** [react-native-elements/react-native-elements#3104]
**Explain what you did (Required)**
I have tried to render a card item and used <Card.FeaturedTitle>Hello<Card.FeaturedTitle> 

[``](url)
**Expected behavior (Required)**
An empty space appeared but Hello Text is not displayed, same happened with <Card.FeaturedSubtitle>

**Describe the bug (Required)**
It is not able to render any text between the tag [](url)

**To Reproduce (Required)**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Screenshots (Required)**
![Screenshot (102)](https://user-images.githubusercontent.com/65896774/123226014-e4280680-d4f0-11eb-92a1-53dba16a2fbc.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    "^3.4.2"     |
| react-native          |    "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz"     |
| expo          |     "~41.0.1"    |
| react-native-web       |     "~0.13.12"   |
| react-native-screens    |     "~3.0.0"   |

**Comment by arpitBhalla** [comment]
Actually its color is white so we aren't able to see it

**Comment by arpitBhalla** [comment]
https://github.com/react-native-elements/react-native-elements/blob/34c6936f70cb489b23342101641376785d12245a/src/Card/CardFeaturedTitle.tsx#L21

**Comment by arpitBhalla** [comment]
Actually its color is `white` so we aren't able to see it. You can use `Card.Title` or use style 

https://github.com/react-native-elements/react-native-elements/blob/34c6936f70cb489b23342101641376785d12245a/src/Card/CardFeaturedTitle.tsx#L21
https://github.com/react-native-elements/react-native-elements/blob/34c6936f70cb489b23342101641376785d12245a/src/Card/CardFeaturedSubtitle.tsx#L21
