### ISSUE TITLE
Email validation for Input component

### ISSUE THREAD

**Issue by KrisLau** [react-native-elements/react-native-elements#3109]
**Is your feature request related to a problem? Please Describe.**
It would be cool if we could set the input component's type to email which would then automatically validate the email format. Then, it should set the error message if the email's format is invalid or blank.

**Describe the solution you'd like**
`<Input type='email' />`
![image](https://user-images.githubusercontent.com/46275463/123448002-10e72700-d5a0-11eb-8d69-b40313d11911.png)

**Describe alternatives you've considered**
I'm just working on implementing it manually right now using a regex.

**Additional context**
N/A

**Comment by arpitBhalla** [comment]
https://github.com/react-native-elements/react-native-elements/issues/3067#issuecomment-856396299

**Comment by arpitBhalla** [comment]
Check this https://github.com/react-native-elements/react-native-elements/issues/3067#issuecomment-856396299

**Comment by arpitBhalla** [comment]
You can use formik or any other form validation library

**Comment by souviknsl07** [comment]
Can I work on this issue?

**Comment by flyingcircle** [comment]
I feel that https://reactnative.dev/docs/textinput already provides enough email specific features. Implementing a regex like this is simple enough for anyone to do with about 2 lines of code. And then this gets complicated when people want to write in their own error message, so then a separate prop has to be created for that... It's a little too specific for a general use library.
