### ISSUE TITLE
[Button]: disabledStyle prop should be distinguished for different button types

### ISSUE THREAD

**Issue by karladler** [react-native-elements/react-native-elements#3127]
**Is your feature request related to a problem? Please Describe.**

When setting the disabledStyle in the theme it applies for ALL button styles. So just setting the background to grey e.g. would also set it on a disabled button of type "clear". There should be an option to make the styling dependent from the button type.

**Describe the solution you'd like**

Two options I can imagine: 
1st: just add `disabledClearStyle`, `disabledOutlineStyle`, `disabledSolidStyle` as possible properties.
2nd: allow also a function for `disabledStyle` which takes the button type as a the first argument.

**Describe alternatives you've considered**

- create local components for ClearButton, SolidButton and OutlineButton with local styles.

**Additional context**
"react-native-elements": "^3.4.2",

Screenshots: sold & clear button enabled & disabled with grey background in theme for disabled state:
<img width="347" alt="Screenshot 2021-07-04 at 19 11 43" src="https://user-images.githubusercontent.com/906623/124393707-0f360580-dcfc-11eb-8013-6ef432b44bbe.png">
<img width="345" alt="Screenshot 2021-07-04 at 19 11 16" src="https://user-images.githubusercontent.com/906623/124393710-10673280-dcfc-11eb-8585-2828d27a0fd8.png">

**Comment by ritwik-boringnews** [comment]
hi sir can i try to work on this bug

**Comment by flyingcircle** [comment]
This I think sounds like too much, and a solution should be pretty simple to come up with from the developer using the library. (I'm not sure how common switching between different 'variants' of button is, but I don't think it's common enough to justify this)

**Comment by CaioMars** [comment]
Maybe I misunderstood the OP but I think he makes a valid point. I'm trying to style the diabled button using ThemeProvider with object `{ Button : { disabledStyle: {...} } }` and this styles all buttons, including active buttons.
