### ISSUE TITLE
Support StyleSheet.create for Theming Customization

### ISSUE THREAD

**Issue by daminhtung** [react-native-elements/react-native-elements#3131]
**What I did**

I am customizing the theme using `ThemeProvider` to migrate my app able to change all `fontFamily` of `Text`, `Button`, `Input` to ` fontFamily: 'Zapfino'`.

I realized in the documentation, there is two way to do that:

1. Using Composition - we create one component with the styles we want and use that instead of the built-in component(great for only one component).

2. Using `ThemeProvider`. This is what I am need and doing.
https://reactnativeelements.com/docs/customization#using-themeprovider

Everything good with `StyleSheet.flatten`, style object `styles = {}` until there is a style in my components that created by `StyleSheet.create`.  The `fontFamily` from theme config is always missing from `newProps` https://github.com/react-native-elements/react-native-elements/blob/next/src/config/withTheme.tsx#L36. And then, the theme was updated without `fontFamily` from the theme config.

That because the `deepmerge` function can't parse a StyleSheet object reference what returns as a number(updated)

**Expected behavior**

My expectation, the `ThemeProvider` config can able to work `StyleSheet.create` as well.
Hope this feature could be supported. Thank you very much.

# Snack
Please take a look at my example to have a clear illustration.
https://snack.expo.io/@daminhtung/change-fontfamily

**Comment by arpitBhalla** [comment]
> The fontFamily from theme config is always missing from ...
Yep, In ThemeProvider
```js
          deepmerge(
            { style: { fontFamily: 'Zapfino' } }, // from ThemeProvider
            { style: styles.text } // From Prop
          )
 ```
 returns ```{"style":329}```

**Comment by arpitBhalla** [comment]
@daminhtung You can do something like this https://snack.expo.io/@arpitbhalla/change-fontfamily

**Comment by daminhtung** [comment]
@arpitBhalla It worked with [styles.text].
When migrating from an existing project, we can easily reach it with a small number of <Text />, <Button /> usage.
However, with a huge number of nodes, it is quite terrible.

**Comment by arpitBhalla** [comment]
This change will be available in next release. You can try this, by installing [Bleeding Edge ](https://reactnativeelements.com/docs/next/installation) version

or you can try with expo template
```bash
expo init app --template react-native-elements-template@bleeding-edge
```
