### ISSUE TITLE
ListItem.Accordion overlaps ListItem

### ISSUE THREAD

**Issue by eatler-suresh** [react-native-elements/react-native-elements#3135]
ListItem.Accordion overlaps ListItem if there are more than 7 items.
![Simulator Screen Shot - iPhone 11 - 2021-07-09 at 20 04 48](https://user-images.githubusercontent.com/65071817/125094769-25bfd080-e0f1-11eb-8f23-05b672d281b4.png)
react: 16.13.1
react-native-elements: 3.4.2

**Comment by arpitBhalla** [comment]
Create a snack.

**Comment by eatler-suresh** [comment]
***@***.***/react-native-elements-accordion

**Comment by eatler-suresh** [comment]
Here is the snack.
https://snack.expo.io/@sureshkv/react-native-elements-accordion

**Comment by kanakgautam** [comment]
hello @arpitBhalla I am new to Open Source. I want to fix this issue. Please guide me.

**Comment by vhien1501** [comment]
hello @arpitBhalla  I have the same problem, so is there any solution to fix this issue?

**Comment by mednche** [comment]
I have the same issue. Any fix yet?

**Comment by arpitBhalla** [comment]
You can try this, using expo template with Bleeding Edge version

expo init app --template react-native-elements-template@bleeding-edge
