### ISSUE TITLE
ButtonGroup TS error

### ISSUE THREAD

**Issue by kickbk** [react-native-elements/react-native-elements#3139]
Getting TS error when using the same as the example [here](https://reactnativeelements.com/docs/button_group#using-components)

**Expected behavior (Required)**

Should not throw an error

**Describe the bug (Required)**

```js
import { ButtonGroup } from 'react-native-elements';

const Screen = ({ route, navigation }: Navigation) => {
  ...
  const component1 = () => <Text>Hello</Text>;
  const component2 = () => <Text>World</Text>;
  const buttons = [{ element: component1 }, { element: component2 }];

  return (
    <KeyboardAwareScrollView ...>
      <View>
        <ButtonGroup
          // onPress={this.updateIndex}
          // selectedIndex={selectedIndex}
          buttons={buttons} // <<<<< Throwing TS error
          containerStyle={{ height: 100 }}
        />
        ...
};
export default Screen;
```

**To Reproduce (Required)**

Use my code and see the error

**Screenshots (Required)**

![Screen Shot 2021-07-13 at 4 56 11 PM](https://user-images.githubusercontent.com/31323376/125540668-2eb58015-bcf0-469f-ac41-533a57a17b40.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |^3.4.2|
| Expo | SDK42|

**Comment by ritwik-boringnews** [comment]
hai can i try to solve this bug

**Comment by kickbk** [comment]
I believe the instructions you have on your site may be incorrect? Not sure. Regardless, doing this works:
```
const buttons = [(<View>...</View>),(<View>...</View>)];
<ButtonGroup
  buttons={buttons}
  ...
/>
```
