### ISSUE TITLE
ListItem.Swipeable rightWidth not adjusting swipe length

### ISSUE THREAD

**Issue by KrisLau** [react-native-elements/react-native-elements#3147]
**Explain what you did (Required)**
I changed the right width on my `ListItem.Swipeable` to `ScreenWidth/10`

**Expected behavior (Required)**
Something closer to this in terms of spacing
![image](https://user-images.githubusercontent.com/46275463/126006915-e87ba83a-0a66-473b-b94d-f1e2d19c6cc8.png)

**Describe the bug (Required)**
 It adjusted the button correctly but the swipe distance did not change accordingly so there is a large gap between the swiped list item and the `rightContent`. An image to better illustrate what I mean:
![image](https://user-images.githubusercontent.com/46275463/126006741-2bbe6fe7-2b3e-4e1e-a91f-a1bf6613883e.png)

**To Reproduce (Required)**
```
<ListItem.Swipeable
  rightContent={
    <Button
      title="Delete"
      icon={{ name: 'delete', color: 'white' }}
      buttonStyle={{ minHeight: '100%', backgroundColor: 'red' }}
    />
  }
  rightWidth={ScreenWidth/10}
>
  <Icon name="My Icon" />
  <ListItem.Content>
    <ListItem.Title>Hello Swiper</ListItem.Title>
  </ListItem.Content>
  <ListItem.Chevron />
</ListItem.Swipeable>
```

**Screenshots (Required)**
Screenshots attached above

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   3.4.2  |
| react-native          |    0.64.2     |

**Comment by flora8984461** [comment]
I created a snack: https://snack.expo.io/@floraliu3274/arrogant-churros

I think using `leftWidth` should be the fix?

**Comment by KrisLau** [comment]
@flora8984461 I tried the snack and it seems to work when I swipe left to reveal but then when I try to swipe right to hide the button, it gets stuck. I'm leaving the button at the default size/width for now since its really not a huge deal but I just thought I'd report it since it seems to be a bug haha. Thank you for the help though!

**Comment by flora8984461** [comment]
NP, glad I can help. I guess they use "leftWidth" which means `swipe to the left`? 😄  according 
to `Width to swipe left` in https://reactnativeelements.com/docs/next/main/props/listitem/#leftwidth

**Comment by KrisLau** [comment]
Ohhhh that's completely my bad I misunderstood the prop, thanks again for all the help and I'll close out the issue!
