### ISSUE TITLE
Button Component ts type error

### ISSUE THREAD

**Issue by mingyuyuyu** [react-native-elements/react-native-elements#3154]
version: 3.4.2
![image](https://user-images.githubusercontent.com/32156701/126472956-824f392d-997b-4ff0-b8f0-4f5eaa5aba37.png)
why, everyone

**Comment by aliwaqar9811** [comment]
I'm facing same error in SearchBar component

**Comment by arpitBhalla** [comment]
@mingyuyuyu Can you test with latest beta version
