### ISSUE TITLE
animation bug in Chip element

### ISSUE THREAD

**Issue by khali70** [react-native-elements/react-native-elements#3159]
![Peek 2021-07-28 17-34](https://user-images.githubusercontent.com/59835449/127352261-b1a6ce42-d0f7-40d1-90a9-6f8fe4dc5952.gif)
the animation is square but the Chip has `borderRadius`
**Environment :**
| software              | version |
| --------------------- | ------- |
| react-native-elements |    3.4.2     |
| react-native          |   64.0      |

**Comment by khali70** [comment]
### I could get around it by disable the animation 
```diff
<Chip
+  TouchableComponent={TouchableWithoutFeedback as any}
    key={id}
    title={mName}
    type={activeChip === mName ? 'solid' : 'outline'}
    titleStyle={activeChip !== mName && styles.outlineChipTitle}
    buttonStyle={
      activeChip === mName ? styles.activeChip : styles.outlineChip
    }
    onPress={() => {
      FilterByTag(mName);
    }}
  />
```

**Comment by flyingcircle** [comment]
@Dhananjayan-PN

**Comment by saideepesh000** [comment]
Hey @flyingcircle , can I work on this
