### ISSUE TITLE
⚠API KEY visible publicly. 

### ISSUE THREAD

**Issue by saksham-tiwari** [react-native-elements/react-native-elements#3161]
**Explain what you did (Required)**

Just forked the repository and found a security threat. Checked it and found the apikey is visible publicly

**Expected behavior (Required)**

Expect the repository to be safe.

**Describe the bug (Required)**

At this point, https://github.com/react-native-elements/react-native-elements/blob/next/website/docusaurus.config.js on line 94, API Key is visible publicly. Use Environment variables in order to hide it

Solve it ASAP.

**Comment by flyingcircle** [comment]
https://www.algolia.com/doc/guides/security/api-keys/#search-only-api-key
