### ISSUE TITLE
ListItem Swipeable close swipeable view and disable swipe leftContent or rightContent

### ISSUE THREAD

**Issue by elmcapp** [react-native-elements/react-native-elements#3162]
Is there a way to close the swipe view after a button is press. (a function to close the swiped view)?
also is there a way to disable swiping from the left or the right?

**Comment by KrisLau** [comment]
Commenting as I would like to know about the possibility of this as well. I have the swipeable item in a tab view so the left swipe is conflicting with the tab swipe a little

**Comment by jorgegvallejo** [comment]
Just want to add that setting the `leftWidth: 0` or `rightWidth:0`, while it doesn't disable the swipe, it seems to prevent the ListItem from staying open

**Comment by oldmannewbie** [comment]
> Is there a way to close the swipe view after a button is press. (a function to close the swiped view)? 

add a key into the ListItem.Swipeable

`<ListItem.Swipeable
        leftContent={
           <Button
           title="Info"
           icon={{ name: "info", color: "white" }}
           buttonStyle={{ minHeight: "100%" }}
          />
        }
        key={item.id}
      >`

**Comment by arpitBhalla** [comment]
You can try this, using expo template with Bleeding Edge version
```bash
expo init app --template react-native-elements-template@bleeding-edge
```
