### ISSUE TITLE
When I copy 6-digit pin from email and paste into add pin field, the copied number keeps formatting from email.

### ISSUE THREAD

**Issue by hpsurekha** [react-native-elements/react-native-elements#3166]
**Explain what you did (Required)**

When I copy a 6-digit pin from the email and paste it into add pin field, the copied number keeps formatting from the email.

**Expected behavior (Required)**

It has to copy the only numbers, not format, able to remove leading and trailing space using trim() or toString() function, but after copy/paste it alignment also get change, from left to center.

**Describe the bug (Required)**

formating issue while copy/paste pin from email.

**To Reproduce (Required)**

Add <input...> element in screen and do copy-paste content from email

![Screenshot 2021-08-06 at 2 48 37 PM](https://user-images.githubusercontent.com/88535459/128488227-d3a0cfe9-b82a-46e7-883b-79de354eb43b.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  2.0.0  |
| react-native          |  0.62.2  |
| OS          |  Android  |

**Comment by flyingcircle** [comment]
This is a problem with React Native's `TextInput`. Unfortunately, it doesn't look like they have a clean solution: https://github.com/facebook/react-native/issues/18926#issuecomment-490541013
