### ISSUE TITLE
ButtonGroup doesn't render correctly in vertical mode

### ISSUE THREAD

**Issue by andyasberry** [react-native-elements/react-native-elements#3175]
**Explain what you did (Required)**

Trying to render the ButtonGroup component in a vertical presentation.

**Expected behavior (Required)**

Expected the ButtonGroup to render the buttons "stacked" vertically, instead of side-by-side as in horizontal/default mode.

**Describe the bug (Required)**

Only a border/bar is rendered in vertical mode for iOS/Android. Seems to render as expected for web, according to [Snack](https://snack.expo.dev/@andyasberryih/rne-buttongroup-issue-vertical-mode).

**To Reproduce (Required)**

```bash
# Snack
https://snack.expo.dev/@andyasberryih/rne-buttongroup-issue-vertical-mode

# Steps
1. Render a vertical ButtonGroup on iOS or Android
2. Note that the buttons are not visible
```

Code from Snack:

```js
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';
import Constants from 'expo-constants';
import { ButtonGroup  } from 'react-native-elements';

export default function App() {
  return (
    <View style={styles.container}>
      <Text style={styles.paragraph}>
        Change code in the editor and watch it change on your phone! Save to get a shareable url.
      </Text>
      <ButtonGroup buttons={['One', 'Two']} />
      <ButtonGroup buttons={['Three', 'Four']} vertical />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
```

**Screenshots (Required)**

iOS:

![Screen Shot 2021-08-16 at 9 04 35 AM](https://user-images.githubusercontent.com/4965259/129576610-1f3f6003-e95c-4897-a38c-3dd6f1888a15.png)

Similar for Android:

![Screen Shot 2021-08-16 at 9 06 51 AM](https://user-images.githubusercontent.com/4965259/129576754-3e7c8ccc-6f1c-402f-98a1-039d22f98eb4.png)

Seems okay for web:

![Screen Shot 2021-08-16 at 9 07 38 AM](https://user-images.githubusercontent.com/4965259/129576852-04d0cb25-fb3d-427e-966a-bbce37040e93.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  3.4.2       |
| react-native          | 0.63.4        |

**Comment by nobi1007** [comment]
[Here](https://github.com/react-native-elements/react-native-elements/blob/6c27049d7e569662529580da8520d14a2ee7f776/src/ButtonGroup/ButtonGroup.tsx#L292) we have made `height` as `null` but it should be `40(default height) x numOfButtons`. Raised a pr here https://github.com/react-native-elements/react-native-elements/pull/3214.

**Comment by hitesh-coder** [comment]
when I was trying to reproduce this issue it was rendering correctly.

Code:
```
import React, {useState} from "react";
import {View, Text} from "react-native"
import { ButtonGroup } from 'react-native-elements'

const App = () => {
  const [selectedIndexes, setSelectedIndexes] = useState([0, 2, 3]);
  return(
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <ButtonGroup
        buttons={['Multiple', 'Select', 'Button', 'Group']}
        selectMultiple
        vertical
        selectedIndexes={selectedIndexes}
        onPress={(value) => {
          setSelectedIndexes(value);
        }}
        containerStyle={{ maxHeight: 200 }}
      />
    </View>
  )
}

export default App;
```

output:
<img width="399" alt="Screenshot 2022-03-06 at 12 26 16 AM" src="https://user-images.githubusercontent.com/58116679/156896564-48f3d972-729e-474f-a9fd-7f30d9cc685a.png">


**Is this issue already resolved?**

System info:
Mac Os Monterey M1 chip
