### ISSUE TITLE
/react-native-elements/dist/avatar/Accessory.js: Support for the experimental syntax 'jsx' isn't currently enabled 

### ISSUE THREAD

**Issue by sivagopaltech** [react-native-elements/react-native-elements#3183]
Getting following error when I add any import statement from react-native-elements

![image](https://user-images.githubusercontent.com/1880074/130854263-a7690ab3-a08d-4c76-926b-7338287961ef.png)

Here is my babel.config.js
![image](https://user-images.githubusercontent.com/1880074/130854745-a8ad15e0-5bd7-4ac1-b0b4-bc3e9813288e.png)

Here is my react component
![image](https://user-images.githubusercontent.com/1880074/130854821-209f9e24-7b93-4887-8627-23b158d49dd9.png)

| software              | version |
| --------------------- | ------- |
| react-native-elements |   3.4.2      |
| react-native          |        0.65 |

**Comment by hsavit1** [comment]
+1 for this error

I was able to get around it with react-native-elements 3.2.0

**Comment by khushal87** [comment]
Still, facing the issue @hsavit1 @sivagopaltech?

**Comment by hsavit1** [comment]
@khushal87 i was able to get around it by turning off typescript for my node module dependencies
