### ISSUE TITLE
Minimize props filter for documentation auto-gen

### ISSUE THREAD

**Issue by khushal87** [react-native-elements/react-native-elements#3184]
As the project uses Docusaurus as the documentation website, the format used in docusaurus to render docs is Markdown. Now, with the latest work, automatic generation of documentation is processed. There are some props that don't render well in markdown and break on compilation while running the documentation website.

To deal with this, I have added the props filter in the docgenParser in the file `website/scripts/docgenParser.ts`. This was the solution that was taken forward after considering other possibilities,

This issue is created in continuation to the fact that we can make the code more maintainable in the future by minimizing those props filters. This should be done taking in mind the fact that the docgen parser works well and the rendering of the generated markdown is not hampered.

Looking for contributions:
I am also creating a task list for the same:

- [ ] To replace all the '|' in props with 'or'. _(Done for the purpose of readability)._
- [ ] To replace all the '&' in props with 'and'. _(Done for the purpose of readability)._
- [ ] To deal with the props of type StyleProp<ViewStyle> and StyleProp<TextStyle> which breaks the markdown. _(This was done as the markdown was breaking due to the presence of angular braces)._
- [ ] To deal with the props of type `() => void` or `() => any`.
- [ ] To deal with prop's default value of type `() => null` or `() => {}`.
- [ ] To deal with the props of type Partial<> which breaks the markdown.
- [ ] Replace the occurrences of type Component/ViewComponent to React Component.
- [ ] To replace the containerStyle props with 'typeof styles'(Object) to Style Object.
- [ ] To replace the animation prop with a valid type of ListItem.Accordion.
- [ ] To deal with the platform-specific props default value in ButtonGroup.
- [ ] To replace '\r\n' which breaks the markdown for certain props to ''.
- [ ] To deal with the Badge Component with prop name onPress.
- [ ] To deal with the platform-specific props default value in Icon.
- [ ] To deal with the ViewComponent prop default value in Header.
- [ ] Replace all the props with default value theme?.colors?.primary to Color(Primary).
- [ ] To deal with the prop of default value onPress || onLongPress ? TouchableOpacity: View in Avatar.

**Comment by arpitBhalla** [comment]
Hopefully we can do it using TSdoc tags
