### ISSUE TITLE
Not working on the web

### ISSUE THREAD

**Issue by luke-hanwook** [react-native-elements/react-native-elements#3188]
**Explain what you did (Required)**
I tried to run follow [Usage on the Web](https://reactnativeelements.com/docs/web_usage)

**Expected behavior (Required)**
Compiled successfully

**Describe the bug (Required)**
Failed to compile.

./node_modules/react-native-elements/dist/bottomSheet/BottomSheet.js
Module not found: Can't resolve 'react-native-safe-area-context' in '/Users/USER_NAME/example/my_app/node_modules/react-native-elements/dist/bottomSheet'

**To Reproduce (Required)**
1. Run to script ```npx create-react-app my-app```
2. Run to script ```yarn add react-native-elements react-native-web react-native-vector-icons```
3. Run to script ```yarn add --dev @babel/plugin-proposal-class-properties customize-cra react-app-rewired```
4. Create a config-overrides.js file in the root of your project.
5. Change scripts in package.json to use react-app-rewired.
6. Run to script ```yarn start```

**Screenshots (Required)**
![image](https://user-images.githubusercontent.com/22446853/131519656-a5495e3a-50ea-4ad8-af55-af55cf05d3ee.png)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    "^3.4.2"     |
| react-native-web         |    "^0.17.1"     |

**Comment by hsavit1** [comment]
have you tried react-native-elements 3.2.0 ?
