### ISSUE TITLE
Input placeholder styling

### ISSUE THREAD

**Issue by KrisLau** [react-native-elements/react-native-elements#3190]
**Is your feature request related to a problem? Please Describe.**
I was trying to change the font size of the placeholder string but there was no `placeholderStyle` available

**Describe the solution you'd like**
Adding a `placeholderStyle`  prop

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by yashsehgal** [comment]
Hey @KrisLau 👋🏽 I would like to work on this issue. Can I get an assignment?

**Comment by KrisLau** [comment]
@yashsehgal I can't give the assignment. I think that has to be from one of the contributors who have access

**Comment by hamzawaleed0102** [comment]
@KrisLau 
`Input` component is using [TextInput](https://reactnative.dev/docs/textinput) which only provides [placeholderTextColor](https://reactnative.dev/docs/textinput#placeholdertextcolor) prop, which already exists in RNE `Input` component. So I think this issue can be closed as it's outside the scope of RNE.

**Comment by KrisLau** [comment]
@hamzawaleed0102 Ohh ok thank you!
