### ISSUE TITLE
Loading image in Avatar in long time

### ISSUE THREAD

**Issue by luongbahop** [react-native-elements/react-native-elements#3199]
When I using the Avatar component and react-native with expo
It takes me a lot of time for loading the image
Is there any one have the same issue?

**Comment by varora1406** [comment]
I am facing issue in loading avatar with `rounded` attribute in expo project

**Comment by khushal87** [comment]
Hey @luongbahop. Are you still facing this issue? It could be due to internet issues too. Can you share your code snippet? Thanks :)
