### ISSUE TITLE
'ListItem.Accordion' is something wrong with ScrollView

### ISSUE THREAD

**Issue by ccusean** [react-native-elements/react-native-elements#3200]
If 'isExpanded' options is false(collapsed list), empty space will be shown on bottom in scrollview.

It can also be checked in the example([react-native-elements/react-native-elements-app](https://github.com/react-native-elements/react-native-elements-app) Lists2).

**Comment by phatmann** [comment]
Found a fix!

```
<Animated.View style={[
        Boolean(animation) && {
            maxHeight: transition.interpolate({
                inputRange: [0, 1],
                outputRange: ['0%', '100%'],
            }),
            height: isExpanded ? 'auto' : 0,  // FIX: Add this line
            opacity: transition,
        },
    ]}>
```

I will submit a PR soon.

**Comment by phatmann** [comment]
Ok, I have a working fix:

```javascript
// ListItemAccordion.js
    // ...
    const [height, setHeight] = useState(isExpanded ? 'auto' : 0)
    const startAnimation = React.useCallback(() => {
        if (typeof animation !== 'boolean') {
            Animated[animation.type || 'timing'](transition, {
                toValue: Number(isExpanded),
                useNativeDriver: false,
                duration: animation.duration || 350,
            }).start(() => {setHeight(isExpanded ? 'auto' : 0)});
        }
    }, [isExpanded, transition, animation]);
    // ...
     <Animated.View style={[
        Boolean(animation) && {
            maxHeight: transition.interpolate({
                inputRange: [0, 1],
                outputRange: ['0%', '100%'],
            }),
            height,
            opacity: transition,
        },
    ]}>
```

When the animation is done, set height to auto or 0 depending on whether expanded or not.  I will submit a PR soon.

**Comment by jereztech** [comment]
I have the same problem, any fix for this?

**Comment by tjnk24** [comment]
this might be helpful

https://stackoverflow.com/a/67896989/12658187

**Comment by l2aelba** [comment]
I got same problem also.

Cannot do like

`{isExpanded && <ListItem item={item} />}`

it turns the animation of the accordion clunky as they said.

**Comment by jereztech** [comment]
@l2aelba I fixed it by migrating to [RN Paper](https://callstack.github.io/react-native-paper/list-accordion.html)

**Comment by arpitBhalla** [comment]
For now, I have removed height animation , it's working now, I'd work on this after v4 is released.
