### ISSUE TITLE
Input in Tabs TabView can't focus

### ISSUE THREAD

**Issue by leonineli** [react-native-elements/react-native-elements#3201]
Input in Tabs TabView can't focus.
My system platform is android 7.0.
I use main dependencies: 
    "react-native": "0.64.2",  
    "react-native-tab-view": "^2.16.0", 
    "react-native-elements": "^3.4.2",
    "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/material-top-tabs": "^5.3.15",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5"
My code:
```
<View style={{flex: 1}}>
      <Tab value={index} onChange={setIndex}>
        <Tab.Item title="recent" />
        <Tab.Item title="favorite" />
        <Tab.Item title="cart" />
      </Tab>
      <TabView value={index} animationType="timing">
        <TabView.Item style={{backgroundColor: 'red', width: '100%'}}>
          <View>
            <Text h1>Recent</Text>
            <ListItem bottomDivider>
              <ListItem.Title>name</ListItem.Title>
              <ListItem.Input placeholder="input name" />
            </ListItem>
          </View>
        </TabView.Item>
        <TabView.Item style={{backgroundColor: 'blue', width: '100%'}}>
          <Text h1>Favorite</Text>
        </TabView.Item>
        <TabView.Item style={{backgroundColor: 'green', width: '100%'}}>
          <Text h1>Cart</Text>
        </TabView.Item>
      </TabView>
    </View>
```

**Comment by arpitBhalla** [comment]
Unable to reproduce https://snack.expo.dev/@arpitbhalla/mad-pretzels

**Comment by Kwamena-S** [comment]
> Unable to reproduce https://snack.expo.dev/@arpitbhalla/mad-pretzels

Works fine on snack, but not on a physical device.

**Comment by sumj25** [comment]
working on this isuue.
