### ISSUE TITLE
A way to select from what point can the Swipe start in Swipeable list

### ISSUE THREAD

**Issue by aimen08** [react-native-elements/react-native-elements#3204]
**Is your feature request related to a problem? Please Describe.**

when putting components such number picker ,they don't register the change because the swipe animation cancel that,
this problem can be apparent in physical device not in emulator .

**Describe the solution you'd like**

the solution is a way to  fire the swipe only if the user started it from the edge of list item.

**Describe alternatives you've considered**

for now I ditched the Swipeable list and am putting my  hidden items such Delete button , inside the list item.

**Comment by aimen08** [comment]
if anyone is having the same issue I found a workaround , replace onPress with onPressIn which will make the event on the button fire.

**Comment by arpitBhalla** [comment]
Can you try if it's working now, Use
```bash
yarn add arpitbhalla/react-native-elements#base

yarn add arpitbhalla/react-native-elements#themed
```
