### ISSUE TITLE
BottomSheet not working with ListItem.Checkbox

### ISSUE THREAD

**Issue by cconnell12345** [react-native-elements/react-native-elements#3210]
**Explain what you did (Required)**

I am using the BottomSheet control with ListItems.  In particular the ListItem.CheckBox.  When the box is checked it is not reflected on the screen although the list data is correct.  I believe because the change is not sent to the Bottom Sheet.  Does the Bottom Sheet need a property like FlatList with extraData?  What am I missing?  Thanks.

**Expected behavior (Required)**

I expect the ListItem.CheckBox to be checked when the stateful property associated with it is changed to true.

**Describe the bug (Required)**

I believe that the BottomSheet does not register a change when the ListItem.Checkbox is changed so nothing gets updated on the screen.

**To Reproduce (Required)**

https://snack.expo.dev/@cconnell/bottomsheet-sample

**Comment by shangyilim** [comment]
The component works as intended. based on your sample code. i think the issue is with how you are updating the state :
```
const onCheckPress = (l) => {
    const list = usersList;
    list.forEach(item => {
      if (item.Email == l.Email) {
       // this does not work as changing the list item's property does not trigger a new change in userList state
       // as the reference to the userList state will still be the same,  which will not cause the component to be re-rendered.
        item.Selected = !l.Selected;
      }
    });
    setUsersList(list);
  }
```

So what we can do  is instead change the reference of the userList by creating a new list when the checkbox is pressed instead, which will re-render the list
```
const onCheckPress = (l) => {
    const newList = usersList.map((lv) => {
      return {
        ...lv,
        Selected:  lv.Email === l.Email ? !lv.Selected: lv.Selected,
        };
    });
    setUsersList(newList);
  }
```

**Comment by arpitBhalla** [comment]
Thanks @shangyilim
