### ISSUE TITLE
SearchBar Keyboard.removeListener

### ISSUE THREAD

**Issue by roffelund** [react-native-elements/react-native-elements#3213]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-elements@3.4.2` for the project I'm working on.

Keyboard.removeListener is Deprecated and caused a crash in Android for us. Keyboard.removeAllListeners resolves the issue.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-elements/dist/searchbar/SearchBar-android.js b/node_modules/react-native-elements/dist/searchbar/SearchBar-android.js
index 1bfd2b4..3ecd35c 100644
--- a/node_modules/react-native-elements/dist/searchbar/SearchBar-android.js
+++ b/node_modules/react-native-elements/dist/searchbar/SearchBar-android.js
@@ -85,7 +85,7 @@ class SearchBar extends Component {
         Keyboard.addListener('keyboardDidHide', this._keyboardDidHide);
     }
     componentWillUnmount() {
-        Keyboard.removeListener('keyboardDidHide', this._keyboardDidHide);
+        Keyboard.removeAllListeners('keyboardDidHide');
     }
     render() {
         var _a;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by pranshuchittora** [comment]
Thanks @roffelund for reporting this.
IMO calling `remove` instead of `removeAllListeners` would be the correct approach.
https://reactnative.dev/docs/keyboard#removelistener

**Comment by roffelund** [comment]
@pranshuchittora Ah yes i can see that. Created a pull request with the Remove function instead.
