### ISSUE TITLE
Horizontally scrolling tabs

### ISSUE THREAD

**Issue by alexisbronchart** [react-native-elements/react-native-elements#3216]
**Is your feature request related to a problem? Please Describe.**

I sometimes have to use up to 5 or 6 tabs to show what I need on a screen in my app. The titles are then compacted and shown vertically on several lines in each Tab.Item which ugly and completely unreadable.

**Describe the solution you'd like**

Horizontally scrollable (as an option ofc) tabs would solve this issue making more room to show titles on 1 line. This will make some Tab.Item go offscreen so when swiping the pages the selected Tab.Item would ideally have to automatically
 scroll to a visible position.

**Comment by ishqDehlvi** [comment]
Can you attach some files or Screenshots so It can be clear.......

**Comment by sgtpsibin** [comment]
+1

**Comment by entrymaster** [comment]
Hey Arpit, I want to work on this. I'm thinking of putting a horizontal ScrollView in Tab.tsx and changing the WIDTH which is currently set by screenWidth/ No. of children( Tabs) .

**Comment by rodrickcalvin** [comment]
As a GSOC student aspirant, I would love to work on this with your guidance @alexisbronchart.
