### ISSUE TITLE
[TabView] onPress is not getting fire in child component in Android.

### ISSUE THREAD

**Issue by santoshkumar964887** [react-native-elements/react-native-elements#3217]
Hi, I am using  react-native-elements  Tab and TabView, everything working fine, just facing issues  onPress is not getting fire in child component in Android.....??

**Comment by MakKir** [comment]
I faced the same issue

**Comment by SunyanLBJ23** [comment]
Set the outermost container style={{flex:1}}

**Comment by jamesanderbard** [comment]
I'm facing the same issue. Any solutions?

**Comment by Kwamena-S** [comment]
> Set the outermost container style={{flex:1}}

Didn't work for me.

**Comment by GaylordP** [comment]
Same issue :)

**Comment by ahamedm** [comment]
Observed the same issue. TabView receives input  in browser but not on the device.

**Comment by ramanansivagnanam** [comment]
In device Tab child components onPress event is not working.
It works fine in development env.

 version -    "react-native-elements": "^3.4.2"

**Comment by amirbhz86** [comment]
It works properly in production mode but not in development

**Comment by arpitBhalla** [comment]
Is onPress is not called in Tab.Item or TabView.Item or child of TabView.Item? Need repro for this issue. Can someone share code which you have tried with.

 I didn't added `onPress` in `Tab.Item` because we have `onChange` prop in `Tab` which have `(newIndex)=> type`. Is the error

**Comment by amirbhz86** [comment]
The pressable components doesn't press in TabView.Item
@arpitBhalla

**Comment by kaiyes** [comment]
Here is a video showcasing that. It works in ios. But in android, any Touchable stuff becomes almost unusable. Any workaround @arpitBhalla ? 

https://user-images.githubusercontent.com/5293742/157389884-ab3c83d1-30de-4df1-ba25-3d04857c1043.mp4

**Comment by blabno** [comment]
I'm experiencing the same issue. It seems that TabView intercepts the interaction as attempt to slide.
If I tap super shortly then the button's onPress gets triggered.

**Comment by arpitBhalla** [comment]
I tried fixing this in #3380 Can someone confirm this by installing [Bleeding Edge ](https://reactnativeelements.com/docs/next/installation) version

or you can try with expo template
```bash
expo init app --template react-native-elements-template@bleeding-edge
```
