### ISSUE TITLE
FAB size does nothing

### ISSUE THREAD

**Issue by brumik** [react-native-elements/react-native-elements#3222]
**Explain what you did (Required)**
Using the FAB like this:
```js
      <FAB
        icon={{
          name: 'plus',
          type: 'font-awesome-5',
          color: '#fff',
        }}
        title='New file'
        onPress={...}
        placement="right"
      />
```
Trying to set the `size='small'` on the button should make it smaller than the default (or the `large` should be larger than the default).

**Expected behavior (Required)**
The button changes sizes depending on the `size` prop. 

**Describe the bug (Required)**
The button does not changes size, no matte what is passed to the `size` prop.

**To Reproduce (Required)**
Just described above how to reproduce the issue.

**Screenshots (Required)**
Not applicable, the button always looks the same.

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   3.4.2      |
| react-native          |    0.64.2     |
| expo                     |    42.0.3 |

**Comment by sumj25** [comment]
Het armpit Bhalla can you describe to me how to produce this bug? I change the FAB size  to small and it works, here is a screenshot. 

![fab2](https://user-images.githubusercontent.com/59159432/150675169-b8ef8650-676b-40c5-a4f3-9d95620b8a07.jpeg)
![fab1](https://user-images.githubusercontent.com/59159432/150675174-d4bf3aa5-ce3c-475d-9f28-c84dc8f9c3c4.jpeg)

**Comment by arpitBhalla** [comment]
Try for extended (one with title) FAB

**Comment by sumj25** [comment]
@arpitBhalla Ohh yaa I find the bug can you please assign me. thanx.

**Comment by arpitBhalla** [comment]
You can create PR
