### ISSUE TITLE
thumbTouchSize is not working in react-native-elements/Slider

### ISSUE THREAD

**Issue by somegal** [react-native-elements/react-native-elements#3225]
Hey Guy,

I am new to React Native, and would like to use the Slider in react-native-elements. The design requires a small thumb for the slider, but with a full-screen touch-area. That means, whenever the user touch and move left or right, it should be able to move the thumb of the slider.

However, I cannot get the thumbTouchSize working. When I try to set it to be:
 thumbTouchSize={100,500}

It keeps return errors. I wonder what have I done wrong?? How can I get it works?

Many thanks in advance!

**Comment by Sinharitik589** [comment]
I think you are passing it wrongly ..it needs to be  `thumbTouchSize={{ width: THUMB_SIZE, height: THUMB_SIZE }}` instead. have a look at the  [documentation](https://reactnativeelements.com/docs/slider#thumbtouchsize)
