### ISSUE TITLE
add picker component 

### ISSUE THREAD

**Issue by SHIVAJIKUMAR007** [react-native-elements/react-native-elements#3228]
**Is your feature request related to a problem? Please Describe.**

You guys have implemented so many component for the devlopers, as you know that the Picker component is removed from react-native library and to achieve that we have to install a additional modual, so i want that you must add this picker componet in your modual 

thank you
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by flyingcircle** [comment]
This has been suggested a dozen times. There's an open ticket in https://github.com/react-native-elements/react-native-elements-universe/issues/11
