### ISSUE TITLE
Disable TabView swipe animation

### ISSUE THREAD

**Issue by Bradzer** [react-native-elements/react-native-elements#3232]
**Is your feature request related to a problem? Please Describe.**
There is no way to disable the swipe animation on a `TabView`.

**Describe the solution you'd like**
A way to disable the swipe  animation on a `TabView`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by arpitBhalla** [comment]
You can try this, by installing [Bleeding Edge ](https://reactnativeelements.com/docs/next/installation) version

or you can try with expo template
```bash
expo init app --template react-native-elements-template@bleeding-edge
```
