### ISSUE TITLE
Image not showing (drop in replacement)

### ISSUE THREAD

**Issue by tamis-laan** [react-native-elements/react-native-elements#3238]
It says the react native element Image component is a drop in replacement, however when switching the image is not loaded:

``` javascript
// Component
export default function Test() {
    return (
        <View style={styles.container}>
            <Image
                style={styles.image}
                resizeMode={'cover'}
                source={{uri:'https://wallup.net/wp-content/uploads/2014/10/14/funny/Funny_Kitten_Spoiled.jpg'}}
                PlaceholderContent={<ActivityIndicator />}
            />
        </View>
    )
}

// Styles
const styles = StyleSheet.create({
    container: {
        width:'100%',
        height:'100%',
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
    },
	image:{
        position:'absolute',
        top:0,
        left:0,
        bottom:0,
        right:0,
    },
})
```
Potential bug or am I doing something wrong here?

**Comment by AllInOneYT** [comment]
Try to replace
```tsx
style={styles.image}
```
With

```tsx
containerStyle={styles.image}
```

**Comment by AllInOneYT** [comment]
The `Image` component is wrapped inside `View` or `Pressable`. If you add `position:'absolute'`, it will be positioned absolute to its parent, which is the wrapper component. You could modify the wrapper's style with `containerStyle` prop

**Comment by kedar09** [comment]
> It says the react native element Image component is a drop in replacement, however when switching the image is not loaded:
> 
> ```js
> // Component
> export default function Test() {
>     return (
>         <View style={styles.container}>
>             <Image
>                 style={styles.image}
>                 resizeMode={'cover'}
>                 source={{uri:'https://wallup.net/wp-content/uploads/2014/10/14/funny/Funny_Kitten_Spoiled.jpg'}}
>                 PlaceholderContent={<ActivityIndicator />}
>             />
>         </View>
>     )
> }
> 
> // Styles
> const styles = StyleSheet.create({
>     container: {
>         width:'100%',
>         height:'100%',
>         backgroundColor: '#fff',
>         alignItems: 'center',
>         justifyContent: 'center',
>     },
> 	image:{
>         position:'absolute',
>         top:0,
>         left:0,
>         bottom:0,
>         right:0,
>     },
> })
> ```
> 
> Potential bug or am I doing something wrong here?

@arpitBhalla @tamis-laan i have used containerStyle instead of style in Image, its working properly.

**Comment by kedar09** [comment]
> It says the react native element Image component is a drop in replacement, however when switching the image is not loaded:
> 
> ```js
> // Component
> export default function Test() {
>     return (
>         <View style={styles.container}>
>             <Image
>                 style={styles.image}
>                 resizeMode={'cover'}
>                 source={{uri:'https://wallup.net/wp-content/uploads/2014/10/14/funny/Funny_Kitten_Spoiled.jpg'}}
>                 PlaceholderContent={<ActivityIndicator />}
>             />
>         </View>
>     )
> }
> 
> // Styles
> const styles = StyleSheet.create({
>     container: {
>         width:'100%',
>         height:'100%',
>         backgroundColor: '#fff',
>         alignItems: 'center',
>         justifyContent: 'center',
>     },
> 	image:{
>         position:'absolute',
>         top:0,
>         left:0,
>         bottom:0,
>         right:0,
>     },
> })
> ```
> 
> Potential bug or am I doing something wrong here?

@arpitBhalla @tamis-laan i have used containerStyle instead of style in Image, its working properly.

**Comment by kedar09** [comment]
> It says the react native element Image component is a drop in replacement, however when switching the image is not loaded:
> 
> ```js
> // Component
> export default function Test() {
>     return (
>         <View style={styles.container}>
>             <Image
>                 style={styles.image}
>                 resizeMode={'cover'}
>                 source={{uri:'https://wallup.net/wp-content/uploads/2014/10/14/funny/Funny_Kitten_Spoiled.jpg'}}
>                 PlaceholderContent={<ActivityIndicator />}
>             />
>         </View>
>     )
> }
> 
> // Styles
> const styles = StyleSheet.create({
>     container: {
>         width:'100%',
>         height:'100%',
>         backgroundColor: '#fff',
>         alignItems: 'center',
>         justifyContent: 'center',
>     },
> 	image:{
>         position:'absolute',
>         top:0,
>         left:0,
>         bottom:0,
>         right:0,
>     },
> })
> ```
> 
> Potential bug or am I doing something wrong here?

@arpitBhalla, I think @tamis-laan doing wrong. need to use containerStyle prop instead of style in the Image, it will work.
