### ISSUE TITLE
Hide documentation about circular slider until it's actually released

### ISSUE THREAD

**Issue by 1mike12** [react-native-elements/react-native-elements#3240]
I just found out that the component listed over at https://reactnativeelements.com/docs/circularslider isn't actually finished yet. Looks like others were just as confused https://github.com/react-native-elements/react-native-elements-universe/issues/13

Would be nice to hide non working components until they're ready

**Comment by abdullahranginwala** [comment]
Hello! Is this issue still open? It is my first time contributing and this seems a good place to start. I would really appreciate is someone could guide me.

**Comment by mariovelyov** [comment]
@arpitBhalla 
Hi, is CircularSlider component released as I still can't install it. Thanks in advance!
