### ISSUE TITLE
onSubmitEditing fires onCancel & cancel fires onCancel twice in Android

### ISSUE THREAD

**Issue by amie-wilt** [react-native-elements/react-native-elements#3247]
**Explain what you did (Required)**

I'm using the `SearchBar` component and am using the `onSubmitEditing` to submit the search. I also have an `onCancel` event  that calls a `goBack` method to close the screen (it's a modal view of React Navigation).

**Expected behavior (Required)**

I would expect that when I hit the "go" button on the keyboard the `onSubmitEditing` would fire and I would expect that when I hit the "cancel" button, the `onCancel` method would fire once.

**Describe the bug (Required)**

When I hit the "go" button, `onCancel` is called. Less impactful but still worth nothing, when I hit the "cancel" button, `onCancel` fires twice.

**To Reproduce (Required)**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Screenshots (Required)**

https://user-images.githubusercontent.com/8226176/142025295-fcf07379-9270-4962-8e5a-81c1f0393552.mov

**Your Environment (Required):**

Mac BigSur 11.0

| software              | version |
| --------------------- | ------- |
| react-native-elements |    `3.1.0`     |
| react-native          |   `0.63.4`      |

**Comment by knmn2000** [comment]
I'm unable to reproduce this issue, could you please link your repo here?
I'm on version 3.4.2 of RNE.

**Comment by entrymaster** [comment]
@amie-wilt Did u get this bug on iOS too?

**Comment by entrymaster** [comment]
@amie-wilt @arpitBhalla  I'm gonna take up this bug. If any updates, then please let me know.
