### ISSUE TITLE
Icon props @types error on typescript 

### ISSUE THREAD

**Issue by Usamaliaquat123** [react-native-elements/react-native-elements#3251]
i imported **<Icon />** component from **react-native-elements** and its look like i'm missing some props but when i go to its defination all the props are optional 

<img width="944" alt="Screenshot 2021-11-20 at 4 26 45 PM" src="https://user-images.githubusercontent.com/33973828/142724610-a0dae43e-edc4-4881-85d8-541745be3ea7.png">

react-native-elements  : ^3.4.2
@types/ react-native-elements : 0.18.0

**Comment by Salman-Usmani** [comment]
problem is in navigation, it should not say void...

**Comment by khushal87** [comment]
The type of `onPress` is `((event: GestureResponderEvent) => void) & ((event: GestureResponderEvent) => void)`. It takes in a `event` parameter.

**Comment by arpitBhalla** [comment]
Can you confirm with latest release?

**Comment by arpitBhalla** [comment]
Closing this issue after a prolonged period of inactivity. If this issue is still present in the latest release, please feel free to create a new issue with up-to-date information.
