### ISSUE TITLE
(TabView组件在鸿蒙系统中，输入框无法使用，并且无法成为受控组件)Tabview component in Hongmeng system, the input box cannot be used and cannot become a controlled component

### ISSUE THREAD

**Issue by djwlx** [react-native-elements/react-native-elements#3255]
TabView组件在鸿蒙系统中，通过value和onchange控制选项，无法正常使用，并且输入框也无法使用

**Comment by koploop** [comment]
> TabView组件在鸿蒙系统中，通过value和onchange控制选项，无法正常使用，并且输入框也无法使用

知道为啥给你直接关了吗？这是GitHub，用英文描述你的问题，这不是常识吗。别人难道还要费劲先翻译一下再给你解答？
