### ISSUE TITLE
Introduce TestID for containerStyles in ListItem.Accordion

### ISSUE THREAD

**Issue by mdarke1** [react-native-elements/react-native-elements#3256]
I am currently finding it impossible to test for style changes in a containerViews around the ListItem.Accordion, as RNE only provides access to the containerStyle and no testID in these views. 

I currently have container styles updating based on state changes, applicable on both the Listitem.Accordion children container views and the ListItem.Accordion icon. However because the views do not provide access to a testID prop there appears no way of accessing the view to check for updates.

It would be preferable to be able to add a testID to the container, but if this is not possible a generic testID would be useful as most testing libraries provide access to within specific elements. I see this has already been utilised in the icons text field using "iconIcon"

I am currently using "@testing-library/react-native" and jest.

**Comment by Udit-takkar** [comment]
@arpitBhalla  Can i take up this issue if still open?

**Comment by knmn2000** [comment]
Took up this issue as there were no updates here in the last week. 
I'm new to react native, please tell me if my pull request is what was required to fix this issue.
Thanks!
