### ISSUE TITLE
Bad type definition in file https://unpkg.com/react-native-elements@3.4.2/dist/searchbar/SearchBar.d.ts

### ISSUE THREAD

**Issue by Misaka-0x447f** [react-native-elements/react-native-elements#3261]
Checkout this image. Sorry for not filling the form.
source: https://unpkg.com/react-native-elements@3.4.2/dist/searchbar/SearchBar.d.ts
![image](https://user-images.githubusercontent.com/15797507/145748302-e1f08d4f-2c82-4639-9ee7-134afc7f5774.png)

**Explain what you did (Required)**

**Expected behavior (Required)**

**Describe the bug (Required)**

**To Reproduce (Required)**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Screenshots (Required)**

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |         |
| react-native          |         |

**Comment by JimTeva** [comment]
This has been an ongoing problem: see https://github.com/react-native-elements/react-native-elements/issues/3089
@arpitBhalla pushed something but no release yet

**Comment by arpitBhalla** [comment]
@JimTeva try unreleased version with this method https://reactnativeelements.com/docs/#bleeding-edge

**Comment by JimTeva** [comment]
@arpitBhalla thanks, just tested, it works great!
```sh
yarn add  https://github.com/react-native-elements/react-native-elements#dist
```

**Comment by flyingcircle** [comment]
now in the latest version 4.0.0-beta.0
