### ISSUE TITLE
not able to center the input

### ISSUE THREAD

**Issue by osamagamal7** [react-native-elements/react-native-elements#3275]
when i give the **containerStyle** width and **height** and apply flex on containerStyle to center the Input, it doesn't move.

<img width="410" alt="Screen Shot 2021-12-24 at 5 15 07 PM" src="https://user-images.githubusercontent.com/31896040/147365196-318ae3b7-ba25-4a10-a4ca-9944b044bd95.png">

<img width="626" alt="Screen Shot 2021-12-24 at 5 54 46 PM" src="https://user-images.githubusercontent.com/31896040/147365221-812475a8-87e0-4bfc-aedb-d7d1274e6298.png">

**Comment by priyansh71** [comment]
This issue can be solved by giving the `flex-direction: "row"` styling property to the inputContainer.
This will vertically align the input box to the centre of the inputContainer.

<img width="700" alt="Screenshot 2021-12-30 at 11 19 26" src="https://user-images.githubusercontent.com/77532581/147725188-3157423d-b7c2-401d-a885-9aedcefb53c3.png">

**Comment by osamagamal7** [comment]
thank you @priyansh71, that works.
but when i replaced the **containerStyle** with **inputContainerStyle**. it worked just fine with no need to set flex-direction to row.

**Comment by arpitBhalla** [comment]
I hope this solves your issue, feel free to re open this if it's still not solved.
