### ISSUE TITLE
Typescript typing: Property 'underlayColor' does not exist

### ISSUE THREAD

**Issue by jkoutavas** [react-native-elements/react-native-elements#3287]
**Explain what you did (Required)**

Attempted to lint check types on my app. Expected no errors.

**Expected behavior (Required)**

Got an error.  Initially I brought this error up on closed issue #3227

**Describe the bug (Required)**

I am having problems with `4.0.0-beta.0`'s types, getting a `Property 'underlayColor' does not exist on type 'IntrinsicAttributes & Omit<PressableProps & { containerStyle?: StyleProp<ViewStyle>; disabledStyle` error on using ListItem's `underlayColor` property

**To Reproduce (Required)**

```ts

...

    <ListItem
      containerStyle={styles.listItem}
      underlayColor="transparent"
      activeOpacity={0.3}
      onPress={(route || onNavigate) && onNavigationPress}
      {...listItemProps}
    >

...

const styles = StyleSheet.create({
  listItem: {
    paddingHorizontal: 24,
  } as ViewStyle,
});

```

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   4.0.0-beta.0      |
| react-native          |   0.66.4      |

**Comment by arpitBhalla** [comment]
Earlier this component uses `Touchable` but now it's using `Pressable` as base component. You need to remove underlayColor prop

**Comment by jkoutavas** [comment]
...which also means removal of `activeOpacity`.

**Comment by jkoutavas** [comment]
Thanks for the clarification you added to PR #3288.
