### ISSUE TITLE
AirbnbRating props are not sent to module in 4.0.0. beta 0

### ISSUE THREAD

**Issue by kickbk** [react-native-elements/react-native-elements#3289]
**Explain what you did (Required)**

Updated to 4 beta. Saw the AirbnbRating module had issue. Found out props are not properly sent to the original module. Solved it by installing the original library and used it instead.

**Expected behavior (Required)**

AirBNB ratings should not have changed its behavior

**Describe the bug (Required)**

Props passed to RNE as `TapRatingProps` are no longer sent to the original package.

**To Reproduce (Required)**

Just use your new version and see how the ratings module changed

**Screenshots (Required)**

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements | 4.0.0-beta0

**Comment by knmn2000** [comment]
The props are not being passed into the react-native-ratings component that RNE uses, I'll make a pull request with a fix for this issue.
