### ISSUE TITLE
Can't pass an array for containerStyle props on Card (and probably other components that i didn't test)

### ISSUE THREAD

**Issue by ardalan-nhd** [react-native-elements/react-native-elements#3292]
**Explain what you did (Required)**

Trying to pass an array for `containerStyle` props on card because i needed to pass several styles conditionally

**Expected behavior (Required)**

Being able to pass an array for styles since it is supported by style props in react native

**Describe the bug (Required)**

When i try to pass an array for `containerStyle` props instead of an object, the styles from theme that is provided by `ThemeProvider` component will be completely ignored. Imagine i have following object in global theme object for Card component:
```
Card: {
        containerStyle: {
            backgroundColor: palette.cardBG,
            margin: 0,
            borderWidth: 0
        }
    }
```
When i style the Card component like `<Card containerStyle={styles.card}>{children}</Card` everthing works fine. But when i try to style it like `<Card containerStyle={[styles.card, styles.conditional]}>{children}</Card` the whole styling from `ThemeProvider` will ignored and reset. for example `palette.cardBG` is a dim color but when i send array styles backgroundColor will become the default white color.

**To Reproduce (Required)**

# Steps
1. Start a new react native app using `react-native init <project-name>`
2. install `react-native-elements` and its required dependencies
3. Add a global theme object and provide the following theme object for it.
```
const theme = {
   Card: {
      containerStyles: {
         backgroundColor: 'black'
      }
   }
}
```
4. inside the `ThemeProvider` add the following code (put any styles that you want except for backgroundColor)
```
<Card containerStyle={[styles.card]}>
</Card>
```
5. You will see the background color of `Card` is not black and it is default white color
6.  See this [snack](https://snack.expo.dev/@ardalan_nhd/forlorn-candies)

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |3.4.2|
| react-native          |0.66.4|

**Comment by arpitBhalla** [comment]
Hey, there was a related issue, can you check https://github.com/react-native-elements/react-native-elements/issues/3131#issuecomment-874537839

**Comment by Sinharitik589** [comment]
@arpitBhalla can i work on it ?

**Comment by arpitBhalla** [comment]
I have already created a PR for this

**Comment by arpitBhalla** [comment]
This change will be available in next release. You can try this, by installing [Bleeding Edge ](https://reactnativeelements.com/docs/next/installation) version

or you can try with expo template
```bash
expo init app --template react-native-elements-template@bleeding-edge
```
