### ISSUE TITLE
 v4 Release 🚀

### ISSUE THREAD

**Issue by arpitBhalla** [react-native-elements/react-native-elements#3297]
Hey 👋🏼  React Native Elements users,
We are ready to release v4 very soon but there is some issue with pkg naming on NPM, For now you can use `Bleeding Edge` version (It's quite stable as of now). To Install Bleeding Edge version, use

```bash
# Install base pkg
yarn add react-native-elements/react-native-elements#base

# Install themed pkg
yarn add react-native-elements/react-native-elements#themed
```
You can also create an alias to help you smooth migration for v4, by aliasing `@react-native-elements/themed` with `react-native-elements`.
```bash
# this will create an alias name for pkg, which might help to migrate to v4
yarn add react-native-elements@react-native-elements/react-native-elements#themed
```
You may need to check [Migration Guide](https://reactnativeelements.com/docs/next/migration_guide#migrating-to-v4),

Please feel free to ask any question.

**Comment by monk-lee** [comment]
I want to use the `/themed` too, but that command doesn't work.

`yarn add react-native-elements/react-native-elements#base` <-- work

`yarn add react-native-elements@react-native-elements/react-native-elements#themed` <-- not work

`yarn add react-native-elements@npm:@react-native-elements/themed` <-- not work too

What should I do?

Thanks.

**Comment by arpitBhalla** [comment]
> yarn add react-native-elements@react-native-elements/react-native-elements#themed

It will be installed as `react-native-elements` alias for `@react-native-elements/themed`.

If you want to install without aliasing, you can do

```bash
yarn add react-native-elements/react-native-elements#themed
```

**Comment by monk-lee** [comment]
> > yarn add react-native-elements@react-native-elements/react-native-elements#themed
> 
> It will be installed as `react-native-elements` i.e. alias for `@react-native-elements/themed`.
> 
> If you want to install without aliasing, you can do
> 
> ```shell
> yarn add react-native-elements/react-native-elements#themed
> ```

`yarn add react-native-elements/react-native-elements#themed` 

There's an error like this

`Couldn't find package "@react-native-elements/base@^4.0.0-beta.1" required by "react-native-elements/react-native-elements#themed" on the "npm" registry.`

**Comment by arpitBhalla** [comment]
I have fixed this, you may install now

**Comment by monk-lee** [comment]
Thanks for helping me.
I'm always using it well.

**Comment by mbyrne00** [comment]
Hi @arpitBhalla - got same error again just now :( ... has something regressed again with the install?

```
$ yarn add react-native-elements/react-native-elements#themed
yarn add v1.22.17
[1/4] 🔍  Resolving packages...
error Couldn't find package "@react-native-elements/base@^4.0.0-beta.1" required by "react-native-elements/react-native-elements#themed" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

```

**Comment by arpitBhalla** [comment]
Sorry for this, I have fixed it. Will also make changes, so it will not happen in again.

**Comment by mbyrne00** [comment]
Oh great! Thanks @arpitBhalla. That did the trick.

**Comment by desonyuan** [comment]
PS C:\Users\Administrator\Documents\code\dingApp> npm install @react-native-elements/themed @react-native-elements/base
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@react-native-elements%2fbase - Not found
npm ERR! 404 
npm ERR! 404  '@react-native-elements/base@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2022-03-04T06_55_00_927Z-debug.log

**Comment by monk-lee** [comment]
> PS C:\Users\Administrator\Documents\code\dingApp> npm install @react-native-elements/themed @react-native-elements/base npm ERR! code E404 npm ERR! 404 Not Found - GET https://registry.npmjs.org/@react-native-elements%2fbase - Not found npm ERR! 404 npm ERR! 404 '@react-native-elements/base@latest' is not in the npm registry. npm ERR! 404 You should bug the author to publish it (or use the name yourself!) npm ERR! 404 npm ERR! 404 Note that you can also install from a npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\Administrator\AppData\Roaming\npm-cache_logs\2022-03-04T06_55_00_927Z-debug.log

there is some issue with pkg naming on NPM, For now you can use Bleeding Edge version

Try it with this command.

```shell
yarn add react-native-elements/react-native-elements#base
```

```shell
yarn add react-native-elements/react-native-elements#themed
```

**Comment by arpitBhalla** [comment]
Created a [discussion](https://github.com/react-native-elements/react-native-elements/discussions/3379) for this, please ask there
