### ISSUE TITLE
The title of a button is not in the center properly In Lists.

### ISSUE THREAD

**Issue by sumj25** [react-native-elements/react-native-elements#3301]
The title of a button is not in the center properly.

**Screenshots (Required)**

![titlebutton](https://user-images.githubusercontent.com/59159432/150388669-a8bbd572-fa96-46be-8fd1-785e793fdbe2.jpeg)

**Comment by sumj25** [comment]
Hii @arpitBhalla can I solve this issue.We can use Dimensions instead of passing some value for height to solve this issue.

**Comment by shubhayu09** [comment]
Hey @arpitBhalla ,
Can you please tell me that which file we have to change to fix up this issue? I'm unable to find the file in the code.

**Comment by sumj25** [comment]
> Hey @arpitBhalla , Can you please tell me that which file we have to change to fix up this issue? I'm unable to find the file in the code.

hey @shubhayu09 I'm already working on it.

**Comment by shubhayu09** [comment]
> 

Ok , cool.
