### ISSUE TITLE
New Universal Components 

### ISSUE THREAD

**Issue by arpit-bhalla** [react-native-elements/react-native-elements#3344]
We have few new Universal component proposals

- [ ] https://github.com/react-native-elements/react-native-elements-universe/issues/3 @knmn2000 
- [ ] https://github.com/react-native-elements/react-native-elements-universe/issues/11
- [x] https://github.com/react-native-elements/react-native-elements-universe/issues/4 @arpitBhalla 
- [x] ~https://github.com/react-native-elements/react-native-elements-universe/issues/5~ @arpitBhalla 
- [ ] https://github.com/react-native-elements/react-native-elements-universe/issues/7
- [ ] Stepper UI

### How to add them?

You can add another folder `<ComponentName>` inside `packages` add `tsconfig.json` and `package.json` similar to `circular-slider` component and name the package as `@react-native-elements/<ComponentName>`

**Comment by knmn2000** [comment]
[This issue](https://github.com/react-native-elements/react-native-elements-universe/issues/3) proposes using the [react-native-table-component](https://www.npmjs.com/package/react-native-table-component) library. 
Would it be okay to add this package as a dependency for RNE, given that the last update to this package was 2 years ago?
