### ISSUE TITLE
Can't Setup the Example app. 

### ISSUE THREAD

**Issue by pranav280300** [react-native-elements/react-native-elements#3346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

Hey,
So I was trying to setup the application.
 -  so Cloned the react-native-element repo.
 - then **cd Examples** directory
 - and **npm i**.

### Expected behavior

Should Ideally be able to install the dependencies for the example app.

### Describe the bug

Hey there,
This is my first time to try open-source, So I was trying to setup the example app after but I am facing an issue while installing the dependencies, below I have attached the  SS for the same.
Looking forward for help.

### Steps To Reproduce

```markdown
Followed the Readme,
 - so Cloned the react-native-element repo.
 - then **cd Examples** directory
 - and **npm i**.
```

### Screenshots

![image](https://user-images.githubusercontent.com/44639575/153699902-2b0ea81d-5b74-4f6c-acc8-8d26fae89a94.png)

### Your Environment

```markdown
react-native-elements: 4.0.0-beta.0
react-native: 0.64.3
```

**Comment by arpitBhalla** [comment]
Try `yarn` instead, we are using yarn workspaces
