### ISSUE TITLE
Overlay fade-in fade-out and timing

### ISSUE THREAD

**Issue by tamis-laan** [react-native-elements/react-native-elements#3349]
The `Overlay` component currently fades in extremely fast and does not fade out. It would be nice if the developer could control the fade in and fade out time of the Overlay component.

**Comment by mayank2021** [comment]
@arpitBhalla can I take this issue?

**Comment by hitesh-coder** [comment]
hey, @arpitBhalla as @kedar09 used animationType in his PR I have tried it and it is working properly.

code as follows:
```
<ModalComponent
    visible={isVisible}
    onRequestClose={onBackdropPress}
    transparent
    animationType='fade'
    {...rest}
  >
```

code without animation type fade:

https://user-images.githubusercontent.com/58116679/157029766-0e3b74c7-601a-4e59-928b-8ebafd59ae96.mov


code with animation type fade:

https://user-images.githubusercontent.com/58116679/157029831-c0405bd7-ba0f-40b4-86c1-92bf37031d42.mov

As you can see a small animation is added.

you can read about animationType over [Here](https://reactnative.dev/docs/modal#animationtype)

**Comment by arpitBhalla** [comment]
@hitesh-coder https://github.com/react-native-elements/react-native-elements/pull/3353#discussion_r805343089

**Comment by arpitBhalla** [comment]
Not sure if you can control the speed/duration of fade in/out, but try `animationType="fade"`
```tsx 
  <Overlay animationType="fade"></Overlay>
```
