### ISSUE TITLE
Extend default font styles doesn't work

### ISSUE THREAD

**Issue by crisfcodes** [react-native-elements/react-native-elements#3358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I've tried to extend the default font styles with interface merging as [documentation](https://reactnativeelements.com/docs/customization#typescript-definitions-extending-the-default-theme) explain:

```typescript
import 'react-native-elements';
import { ColorValue, StyleProp, TextStyle } from 'react-native';

type ColorSwatch = {
  otherColor: string;
};

declare module 'react-native-elements' {
  export interface Colors extends ColorSwatch {}

  export interface TextProps {
    h5Style: StyleProp<TextStyle>;
  }

  export interface FullTheme {
    colors: RecursivePartial<Colors>;
    Text: Partial<TextProps>;
  }
}
```

### Expected behavior

The expected behavior should be can access to the new styles inside theme object:

import { FullTheme } from 'react-native-elements';

export const theme: FullTheme = {
  Text: {
    h5Style: {
      fontFamily: '',
    },
  }
}

### Describe the bug

When I create the module with interface augmentatino I'm getting the following error:

```
Object literal may only specify known properties, but 'h5Style' does not exist in type 'Partial<TextProps>'. Did you mean to write 'h1Style'?
```

### Steps To Reproduce

```markdown
Just create a repo with react-native-elements and follow the doumentation in how extend default theme types, an try to create a new ones for font styles,s that's all you need to reproduce the error.

### react-native-elements.d.ts


import 'react-native-elements';
import { ColorValue, StyleProp, TextStyle } from 'react-native';

type ColorSwatch = {
  otherColor: string;
};

declare module 'react-native-elements' {
  export interface Colors extends ColorSwatch {}

  export interface TextProps {
    h5Style: StyleProp<TextStyle>;
  }

  export interface FullTheme {
    colors: RecursivePartial<Colors>;
    Text: Partial<TextProps>;
  }
}
```

### Screenshots

![image](https://user-images.githubusercontent.com/20000951/154191994-554cb0b0-8302-40c3-b496-6166d3f5e25f.png)

### Your Environment

```markdown
"react-native-elements": "^3.4.2",
"react-native": "0.67.2",
```

**Comment by arpitBhalla** [comment]
Fixed with https://github.com/react-native-elements/react-native-elements/pull/3198

**Comment by arpitBhalla** [comment]
Hey, that's because we can only merge `interfaces`. I made that change. Please let me know on Slack if you need any help.

**Comment by arpitBhalla** [comment]
If you are using Bleeding Edge, you can else not for now

**Comment by crisfcodes** [comment]
I am using Bleeding Edge and this behavior does not work, what I posted in the code this version, I'm doing something wrong

**Comment by monk-lee** [comment]
```typescript
interface TextProps {
  bold?: boolean;
  color?: string;
}

interface FullTheme {
  colors: RecursivePartial<Colors>;
  Text: Partial<TextProps>;
}
```

I want to make the text bold.

```javascript
<Text bold>...</Text>
```

How can I apply style to such added props?

**Comment by arpitBhalla** [comment]
@monk-lee I am working on that part.

**Comment by arpitBhalla** [comment]
@monk-lee @crisfcodes Can you test it?

## Install

```bash
yarn add arpitBhalla/react-native-elements#themed
```
## Usage

```tsx
declare module '@react-native-elements/themed' {
  export interface TextProps {
    bold?: boolean;
  }
  export interface ButtonProps {
    size?: 'small' | 'large';
  }
  export interface FullTheme {
    Text: Partial<TextProps>;
    Button: Partial<ButtonProps>;
  }
}
```

```tsx
const myTheme = createTheme({
  lightColors: {
    primary: '#00a680',
  },
  mode: 'dark',
  Text: (props) => ({
    style: {
      fontWeight: props.bold ? 'bold' : 'normal',
    },
  }),
  Button: (props) => ({
    buttonStyle:
      props.size === 'small' ? { padding: 40 } : { backgroundColor: 'red' },
  }),
  Card: {
    containerStyle: {
      borderRadius: 8,
    },
  },
});

const App = () => <ThemeProvider theme={myTheme}>
 <Text bold>Hello</Text>
</ThemeProvider>
```

**Comment by crisfcodes** [comment]
Let me check If all is working as expected @arpitBhalla

**Comment by monk-lee** [comment]
I don't think this is complete. `arpitBhalla/react-native-elements#themed`

```terminal
[Error: InternalError Metro has encountered an error: While trying to resolve module `@react-native-elements/themed` from file `/Users/sena/Desktop/myApp/index.js`, the package `/Users/sena/Desktop/myApp/node_modules/@react-native-elements/themed/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/sena/Desktop/myApp/node_modules/@react-native-elements/themed/src/index.ts`.
```

**Comment by arpitBhalla** [comment]
I have fixed it, can you check once again

**Comment by monk-lee** [comment]
I made it simple and I think it's working well.

```tsx
interface TextProps {
  bold?: boolean;
  p1?: boolean;
  p1Style?: StyleProp<TextStyle>;
}
```

**Comment by arpitBhalla** [comment]
Yeah, I have already created a PR https://github.com/react-native-elements/react-native-elements/pull/3324

**Comment by monk-lee** [comment]
> Yeah, I have already created a PR #3324

When can I start using this?

**Comment by arpitBhalla** [comment]
May be till end of [current Iteration](https://github.com/orgs/react-native-elements/projects/1/views/12)

**Comment by arpitBhalla** [comment]
This change will be available in next release. You can try this, by installing [Bleeding Edge ](https://reactnativeelements.com/docs/next/installation) version

or you can try with expo template
```bash
expo init app --template react-native-elements-template@bleeding-edge
```
