### ISSUE TITLE
[DropDown] Not Working Properly

### ISSUE THREAD

**Issue by abhinav-22-tech** [react-native-elements/react-native-elements#3368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

The DropDown Menu of the header of the website does not work properly.

Initial Stage
![image](https://user-images.githubusercontent.com/66718489/155157928-43405e8d-8a83-457c-b232-9b1d1af85d19.png)

When we click on `All versions` it shows the correct page but does not show `All versions` in the dropdown menu.
![image](https://user-images.githubusercontent.com/66718489/155158839-e6f9a380-ddc8-4228-b321-fbd42540d63f.png)

After `Click`
![image](https://user-images.githubusercontent.com/66718489/155158994-2df1c30e-65bc-4cce-b888-531725bcb10a.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/66718489/155159580-d486f754-d2f4-44bb-968c-8f812871cc58.png)

### Describe the bug

Bug explained above.

### Steps To Reproduce

```markdown
See on "https://reactnativeelements.com/versions"
Hover on the Header version dropdown 
And then click on All versions
```

**Comment by arpitBhalla** [comment]
I don't think it's an issue with `react-native-elements`, you can raise issue [here](https://github.com/facebook/docusaurus).
