### ISSUE TITLE
On Android simulator, button disabled has no effect on style change when in comparison to iOS

### ISSUE THREAD

**Issue by mendes-develop** [react-native-elements/react-native-elements#3369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

<img width="825" alt="Screen Shot 2022-02-22 at 3 53 16 PM" src="https://user-images.githubusercontent.com/46525527/155217422-38e18496-e4f8-4904-b5d8-aef0262c79f9.png">

`  return (
    <Button
      {...props}
      title={
        <P1 textAlign={"center"} color={titleColor}>
          {title}
        </P1>
      }
    />
  );
};`

The behavior of a disabled button on android is not the same on iOS

### Expected behavior

Same background color on disabled state for both ios and android

### Describe the bug

this component will render different on different platforms 

      <Button
        disabled
        buttonStyle={{ backgroundColor: "black" }}
        title={<Text color={"white"}>{"Button"}</Text>}
      />

### Steps To Reproduce

```markdown
run a react native app 

      <Button
        disabled
        buttonStyle={{ backgroundColor: "black" }}
        title={<Text color={"white"}>{"Button"}</T1>}
      />
```

### Your Environment

```markdown
react-native-elements: 3.4.0
react-native: 0.64
```

**Comment by khushal87** [comment]
iOS:
<img width="241" alt="Screenshot 2023-08-26 at 9 30 55 PM" src="https://github.com/react-native-elements/react-native-elements/assets/39884168/f0a5ecc7-8bf5-4e9b-a546-0b55a0179310">
Android:
<img width="241" alt="Screenshot 2023-08-26 at 9 30 47 PM" src="https://github.com/react-native-elements/react-native-elements/assets/39884168/8806452d-ca15-4e04-9612-f09eb63c0dbc">
Code:
```
<Button disabled buttonStyle={{ backgroundColor: 'black' }}>
Primary
</Button>
```

Hey @mendes-develop the issue doesn't seem to be relevant. Is it still reproducible?
