### ISSUE TITLE
makeStyles theme parameter typing is not accurate

### ISSUE THREAD

**Issue by mbyrne00** [react-native-elements/react-native-elements#3394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

```typescript
const useStyles = makeStyles((theme) => ({
  root: {
    backgroundColor: theme.colors.white,
  },
});
```

```
 ... error ... theme.colors could possibly be undefined
```

### Expected behavior

The `theme` param is `Partial<FullTheme>` however it appears that the `colors` property is _always_ present. Param type should reflect this.

### Describe the bug

Allow developers to assume full `theme.colors.xxx` set of values are present and defined.

### Steps To Reproduce

```markdown
See code above.
```

### Your Environment

```markdown
Used the "bleeding edge" install instructions

* react-native-elements: 4.0.0-beta.0 (sometimes also referred to as 4.0.0-beta.1 during install)
* expo: 44.0.6
* typescript: 4.6.2
```

**Comment by mbyrne00** [comment]
For now I've worked around this so that my code can happily use any overrides that we know have been set without any optional chaining, etc.

The workaround is to define my own `makeAppStyles` function.

```
export const theme: ThemeOptions = {
  // All my theme overrides
};

type RuntimeTheme = { colors: Colors } & typeof theme;

// Better typing definitions for fields we know are never undefined. See https://github.com/react-native-elements/react-native-elements/issues/3394
export const makeAppStyles = <
  T extends StyleSheet.NamedStyles<T> | StyleSheet.NamedStyles<unknown>,
  V
  >(
  styles: T | ((theme: RuntimeTheme, props: V) => T)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
) => makeStyles<T, V>(styles as any);
```

Then in my component, the below snippet no longer complains. This will also allow me to reference any other overrides safely without optional chaining. If the theme is changed then the compiler will help me to not reference fields that are no longer set.

```
const useStyles = makeStyles((theme) => ({
  root: {
    backgroundColor: theme.colors.white,
  },
});
```

**Comment by arpitBhalla** [comment]
It is because Colors are optional in Theme type, You may use optional chaining `theme?.colors?.primary`

**Comment by mbyrne00** [comment]
Thanks for the feedback @arpitBhalla but when I create an empty theme I see the theme.colors object still. When can it be undefined?

**Comment by arpitBhalla** [comment]
Yeah, it (`Partial<Colors> in Theme type`) exists since long ago.

**Comment by mbyrne00** [comment]
Oh ok - so does that mean this is something that can be _fixed_? (I'm guessing maybe it is from the milestone).  Obviously subject to prioritisation.

Just wanted to confirm I'm doing the right thing by assuming it will always be there with my workaround. Avoids a lot of unnecessary chaining and handling of undefined.

**Comment by arpitBhalla** [comment]
Yes there would be always colors property, even if you don't use ThemeProvider

**Comment by mbyrne00** [comment]
@arpitBhalla - I have updated to the latest (`rc2`) version of this lib and when I call `makeStyles` like below I am still getting an error saying `theme.colors is possibly undefined`. I see you fixed the type within `FullTheme` to say `colors` is mandatory, but the `makeStyles` call still has `theme: Partial<FullTheme>`. I'm not sure why that should be `Partial`

```
const useStyles = makeStyles((theme) => ({
   root: {
       borderColor: theme.colors.primary,
   }
});
```

I can confirm that `useTheme` is returning the full theme now with `colors` being required.
