### ISSUE TITLE
MISSING index.ts file cannot resolve module

### ISSUE THREAD

**Issue by omar-abdul** [react-native-elements/react-native-elements#3402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

After following the guide for installation in their official page, using github packages, treid to run react-native start  and it kept crashing  with this log

`the package `/mnt/Stuff/Sarifle App/Sarifle2/node_modules/@react-native-elements/themed/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/mnt/Stuff/Sarifle App/Sarifle2/node_modules/@react-native-elements/themed/src/index.ts`

### Expected behavior

Running metro.js and reloading app

### Describe the bug

Thr problem seemed to be package that i downloaded from the github packages( following the insatllation guide)  the package.json read
`{
  "name": "@react-native-elements/themed",
  "version": "4.0.0-rc.0",
  "description": "React Native Elements & UI Toolkit",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "react-native": "src/index.js",
  "source": "src/index.js",
  "prepublish": "tsc --composite false",
  "files": [...`

but the structure of the folder was dist>index.js

so i fixed it by renaming the folder to src (which took a whole while trying to configure imports) and then corrected package.json

Incase anyone has the same hassle, i suffered two sleepless nights 

### Steps To Reproduce

```markdown
install react-native-elements/themed or /base from github packages
```

### Your Environment

```markdown
react-native 0.67
```

**Comment by arpitBhalla** [comment]
> Incase anyone has the same hassle, i suffered two sleepless nights

You can ask on Slack ;)

**Comment by arpitBhalla** [comment]
Are you using Expo or React Native CLI?

**Comment by omar-abdul** [comment]
React Native Cli

**Comment by BlackSenPig** [comment]
I faced the same issue .
I have modified it -> 
`node_modules/@react-native-elements/themed/package.json`
```diff
- "react-native": "src/index.ts",
+ "react-native": "dist/index.js",
```

**Comment by omar-abdul** [comment]
Great, i opened this just incase...
am glad 😊

**Comment by l2aelba** [comment]
Any fix?

**Comment by omar-abdul** [comment]
Currently all i did was go into the node_modules folder and edit
package.json to point to dist/index.js (as suggested previously) everything
seems to be working,  so far so yeaay

**Comment by arpitBhalla** [comment]
Didn't metro use `main` as entry point?

**Comment by arpitBhalla** [comment]
I have fixed it, can someone confirm it?

**Comment by omar-abdul** [comment]
Yess yess its working i just tried it, it seems you removed the
react-nativr property which was what was causing it to go crazy, thanks

**Comment by arpitBhalla** [comment]
I added it because we have example app within the repo, and I need src/** files as source rather than building then using `dist`. 

Hope it'd work for all. Thanks for your feedback :)
