### ISSUE TITLE
Tooltip not working by default in rc0

### ISSUE THREAD

**Issue by p697** [react-native-elements/react-native-elements#3413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

When i'm useing Tooltip in version rc0, I found that I must use a new visible state and pass `visible` `onOpen` and `onClose` to Tooltip to make it work. This usage it's not the same with the doc.

### Expected behavior

The Tooltip is working perfectly.

### Describe the bug

I read the source code of Tooltip, I found that Tooltip is a totally user controlled Component, the `visible` props decide whether show or hide, and the`onOpen` and `onClose` might be the only way to change the `visible` state.

I ran the example and found that every Tooltip in the example now is not working.

### Steps To Reproduce

```markdown
in the next branch

`cd example`

`yarn start`

then navigete to the Tooltip page

you will find that they are all not working
```

### Your Environment

```markdown
rc0
```

**Comment by arpitBhalla** [comment]
Yes, it's uncontrolled component now, please see Migration Guide

**Comment by arpitBhalla** [comment]
Yes the behavior has been changed in v4, refer [Migration Guide](https://reactnativeelements.com/docs/migration_guide#tooltip)
