### ISSUE TITLE
text props for components

### ISSUE THREAD

**Issue by kickbk** [react-native-elements/react-native-elements#3414]
I am not sure whether you already implemented this, but it would be great to be able to pass Text props to a Button component (and other components using Text) so we could do something like `maxFontSizeMultiplier={1.2}`

**Comment by arpitBhalla** [comment]
I believe most of components have `textProp` or `titleProp`, you can pass TextProp there, 
For example, for Button it'd be
```tsx
 <Button titleProps={{ maxFontSizeMultiplier: 1.4 }} />
```

**Comment by kickbk** [comment]
Brilliant. Thank you.

**Comment by RyanTG** [comment]
Button has titleProps, but ButtonGroup doesn't seem to have it. https://github.com/react-native-elements/react-native-elements/blob/52056ded1e067061c33af6ab328fcf6168652bb1/packages/base/src/ButtonGroup/ButtonGroup.tsx Or am I missing something?
