### ISSUE TITLE
There is a spelling problem in the COLOR section of the document

### ISSUE THREAD

**Issue by shadowfish07** [react-native-elements/react-native-elements#3415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

it should be "colors"! I spent a lot of time checking why it didn't working,and I finaily find this problem.
![image](https://user-images.githubusercontent.com/38303418/160250280-94614c58-f341-48d7-aa77-d9953fa3da5c.png)

### Expected behavior

it should be "colors"!
![image](https://user-images.githubusercontent.com/38303418/160250329-ffe609c2-9ae4-478e-8c94-a63be01c948c.png)

### Describe the bug

There is a spelling problem in the COLOR section of the document.the "color" should be "colors"

### Steps To Reproduce

```markdown
~~
```

**Comment by arpitBhalla** [comment]
Would you like to create a PR?

**Comment by arpitBhalla** [comment]
Would you like to create a PR?
