### ISSUE TITLE
CircularSlider component

### ISSUE THREAD

**Issue by mariovelyov** [react-native-elements/react-native-elements#3421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I have tried to install CircularSlider component.

### Expected behavior

When yarn add @react-native-elements/circular-slider is run I expect the package to be installed.

### Describe the bug

Issue: 
error An unexpected error occurred: "https://registry.yarnpkg.com/@react-native-elements%2fcircular-slider: Not found".

When (@react-native-elements:registry=https://npm.pkg.github.com) is added to .npmrc to refer the installation guide there is similar error:

error Couldn't find package "@react-native-elements/circular-slider" on the "npm" registry.

Could you please help how to install the package. Thanks in advance.

### Steps To Reproduce

```markdown
Steps to reproduce:

Run yarn add @react-native-elements/circular-slider following the documentation here: https://reactnativeelements.com/docs/universe/circularslider.
```

### Your Environment

```markdown
"react-native": "0.66.4"
```

**Comment by arpitBhalla** [comment]
Try `npm i @rneui/circular-slider`
