### ISSUE TITLE
Can't open the demo app

### ISSUE THREAD

**Issue by ttanimichi** [react-native-elements/react-native-elements#3434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I've scanned [this QR code](https://expo.dev/@rne_org/react-native-elements) and opened the app, but got this error.

![image](https://user-images.githubusercontent.com/5486854/161370791-826df3ea-7d43-437e-a7cf-2510e043e03e.png)

### Expected behavior

Can open the demo app

### Describe the bug

Can't open the demo app

### Steps To Reproduce

```markdown
Scan the QR code and open the app
```

### Your Environment

```markdown
iPhone 12 mini
```

**Comment by arpitBhalla** [comment]
Try https://expo.dev/@rne_org/react-native-elements

**Comment by ttanimichi** [comment]
@arpitBhalla  It doesn’t seem to work

![IMG_942981E1AA40-1](https://user-images.githubusercontent.com/5486854/161372046-89d0f31c-e085-4953-aab9-0a2d771d9271.jpeg)

**Comment by arpitBhalla** [comment]
Try again?

**Comment by ttanimichi** [comment]
I've got the same result

**Comment by arpitBhalla** [comment]
Hey, @ttanimichi   Are you able to start the demo app?

**Comment by ttanimichi** [comment]
No, I can't
![IMG_0765](https://user-images.githubusercontent.com/5486854/161763689-93a7becd-7c78-4146-8039-3eb2552a1501.jpg)

**Comment by arpitBhalla** [comment]
Well, maybe you need to login first

https://stackoverflow.com/a/64901771/6682039

**Comment by ttanimichi** [comment]
I've signed in to my Expo account, but it still doesn't work

![IMG_0779](https://user-images.githubusercontent.com/5486854/162578190-77ce8679-ba00-405c-97d9-e93a6f1672bc.PNG)
---
![IMG_0780](https://user-images.githubusercontent.com/5486854/162578186-ee92f610-5324-474d-abb2-a4fa51fb6a33.jpg)

**Comment by arpitBhalla** [comment]
I really things this is something related to authentication, (because it throws 403)

**Comment by ttanimichi** [comment]
Would you mind re-opening this issue?

**Comment by arpitBhalla** [comment]
I can reopen but it's not related to React Native Elements in any way

**Comment by ttanimichi** [comment]
Yes, I think so too. But, it would be an RNE's issue that the QR code on the REN official website doesn't work and the users can't try the demo app

**Comment by arpitBhalla** [comment]
Hey @ttanimichi I am not sure which QR code you are scanning from, the one on the website should point to `https://expo.dev/%40rne_org/react-native-elements`, 

It's working on my device so I think it might be some issue with your device, maybe?

Also if you want to try the demo app, you can clone this repository, and start it from `example/`

**Comment by lucksp** [comment]
I have the same issue.  

I think it's related to entry points of the App with Expo

https://github.com/react-native-elements/react-native-elements/issues/3409#issuecomment-1095541439

For what it's worth, if I `npm install` there is no issue and `yarn start` opens the Expo UI successfully.  However, upon running the app from Expo it will not compile the bundle

```
Starting Metro Bundler
ERROR
14:44
Building JavaScript bundle: error
ERROR
14:44
While trying to resolve module `react-native-elements` from file `/Users/plucks-fluid/dev/react-native-elements-app/App.tsx`, the package `/Users/plucks-fluid/dev/react-native-elements-app/node_modules/react-native-elements/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/plucks-fluid/dev/react-native-elements-app/node_modules/react-native-elements/index`. Indeed, none of these files exist:

  * /Users/plucks-fluid/dev/react-native-elements-app/node_modules/react-native-elements/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * /Users/plucks-fluid/dev/react-native-elements-app/node_modules/react-native-elements/index/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * 
```

I have changed the package.json `react-native-elements` dependency from `"react-native-elements": "https://github.com/react-native-elements/react-native-elements#next",` to `"react-native-elements": "^3.4.2",` which makes no impact.
Also I did try the `master` branch instead of default `next` but it's a similar error when running `yarn start` just freezes in the iOS simulator, but `yarn start ios` shows why it freezes:

> Starting project at /Users/plucks-fluid/dev/react-native-elements-app/ios
The expected package.json path: /Users/plucks-fluid/dev/react-native-elements-app/ios/package.json does not exist
error Command failed with exit code 1.

**Comment by arpitBhalla** [comment]
Hey @lucksp please clone this repo, and start from `example` directory

**Comment by lucksp** [comment]
> Hey @lucksp please clone this repo, and start from `example` directory

OK, let me try.  I was following the instructions from the "examples" for Expo https://github.com/react-native-elements/react-native-elements/tree/next/example#getting-started

**Comment by arpitBhalla** [comment]
Refer this https://reactnativeelements.com/docs/contributing#setup

**Comment by arpitBhalla** [comment]
Hey, hopefully you are able to run Demo Expo app locally, I am closing this issue now.

**Comment by wan54** [comment]
I just now cloned the project, `yarn example:start` and got `ApiV2Error: Entity Not Authorized.` 

Expo Go on iOS 12
Client version: 2.25.3.1015682
Supported SDKs: 44, 45, 46

Also the same error when launching with iOS sim iPhone 14 Pro with Client version 2.26.4.101

**Comment by arpitBhalla** [comment]
Hey, this might help https://github.com/react-navigation/react-navigation/issues/10898#issuecomment-1269871392
