### ISSUE TITLE
Remove tvParallaxProperties from required in `IconButtonProps`

### ISSUE THREAD

**Issue by 1mike12** [react-native-elements/react-native-elements#3439]
**Is your feature request related to a problem? Please Describe.**

My IDE always shows an error because each icon requires a tvParallaxProperties prop even though I would wager 99% of people are not developing for TV, nor does leaving this prop out break anything. 

`dist/icons/Icon.d.ts` line 41

**Describe alternatives you've considered**

**Additional context**

version ^3.4.2

**Comment by arpitBhalla** [comment]
Can you try with latest version?

**Comment by arpitBhalla** [comment]
I can confirm this is resolved in latest release

**Comment by 1mike12** [comment]
@arpitBhalla  thanks so much!

**Comment by hlspablo** [comment]
@arpitBhalla its possible to make this fix available to v3?, v4 still in RC  and can break things... its very annoying see error everywhere in my project..., and for while i would like to stick with v3

**Comment by arpitBhalla** [comment]
@hlspablo sure
