### ISSUE TITLE
Links to components in readme are incorrect, lead to Page Not Found

### ISSUE THREAD

**Issue by AndrewE1234** [react-native-elements/react-native-elements#3443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

View documentation for components provided in the readme

### Expected behavior

Should open correct component page

### Describe the bug

Selecting one of the links in the "Components included" section of the readme leads to a Page Not Found error, which seems to be due to incorrect links. The readme has the url's set to https://reactnativeelements.com/docs/[component], but seems like the url is now https://reactnativeelements.com/docs/components/[component]. I saw a similar [issue to this that was closed](https://github.com/react-native-elements/react-native-elements/issues/3406), but that only fixed one link.

### Steps To Reproduce

```markdown
Open any of the links in the "Components included" section of the readme
```

### Your Environment

```markdown
Firefox on Windows 11
```

**Comment by arpitBhalla** [comment]
I was thinking of removing that section from readme, we can check available components from website sidebar, Do you have any thoughts for this?

**Comment by AndrewE1234** [comment]
Hi, sorry for not responding! I think removing that section was the right move, as it makes it less you need to track in future. Thanks for fixing the issue.
