### ISSUE TITLE
Type '{ children: Element; theme: CreateThemeOptions; }'

### ISSUE THREAD

**Issue by andrefedev** [react-native-elements/react-native-elements#3452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I installed react native and react native elements and followed the guide to use ThemeProvider and the children type is missing.

### Expected behavior

type children is not present.

### Describe the bug

(alias) const ThemeProvider: React.FC<{
    theme?: CreateThemeOptions | undefined;
}>
import ThemeProvider
Type '{ children: Element; theme: CreateThemeOptions; }' is not assignable to type 'IntrinsicAttributes & { theme?: CreateThemeOptions | undefined; }'.
  Property 'children' does not exist on type 'IntrinsicAttributes & { theme?: CreateThemeOptions | undefined; }'.ts(2322)

### Steps To Reproduce

```markdown
Follow code
```

### Screenshots

<img width="1147" alt="Captura de Pantalla 2022-04-10 a la(s) 8 16 47 p  m" src="https://user-images.githubusercontent.com/14114839/162649637-0d9ff071-e7b2-4780-ae86-c2960650abac.png">

### Your Environment

```markdown
react-native 0.68
react-native-elements 4.0.1.rc.1
```

**Comment by andrefedev** [comment]
They are relying on React.FC to have the children attribute when it is not. They should fix this and not trust React.FC.

**Comment by hcharley** [comment]
I believe this issue is likely from the @types/react 18 upgrade:

https://solverfox.dev/writing/no-implicit-children/
