### ISSUE TITLE
4.0.0.rc1: linter error in @rneui/base/Skeleton/index.d.ts

### ISSUE THREAD

**Issue by jkoutavas** [react-native-elements/react-native-elements#3456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

Ran `eslint . --ext .ts,.tsx --max-warnings 0` on my project. Got a TSC error. See screenshot below.

### Expected behavior

No linter errors

### Describe the bug

There's a typo or something in `Skeleton/index.d.ts`

### Steps To Reproduce

```markdown
I'm not sure how to reproduce this independently. Seems like a basic error in the TypeScript definition file?
```

### Screenshots

<img width="741" alt="image" src="https://user-images.githubusercontent.com/1264625/162956200-b82cd1f2-72f6-44dc-8140-eeaf37c9ed9d.png">

### Your Environment

```markdown
Excerpts from my `package.json` file:

    "@rneui/base": "^4.0.0-rc.1",
    "@rneui/themed": "^4.0.0-rc.1",
    "react-native": "0.67.4",
    "typescript": "^3.8.3"
```

**Comment by DPflasterer** [comment]
I ran into this too. I had to update typescript in my project (4.6.3) and I was able to build but I haven't tested further.

**Comment by jkoutavas** [comment]
> I ran into this too. I had to update typescript in my project (4.6.3) and I was able to build but I haven't tested further.

Yeah, updating to TypeScript 4.6.3 fixed this error for me, but introduced a whole world of new errors having to do with our subclass of RNE's Input component. Errors such as "shake property doesn't exist" and errors having to do with how we do Refs with RNE's Input component.
