### ISSUE TITLE
Dialog actions are rendered outside the dialog box on WEB

### ISSUE THREAD

**Issue by louislatreille** [react-native-elements/react-native-elements#3457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I am trying to use the Dialog component. Same issue arises on the [documentation page](https://reactnativeelements.com/docs/components/dialog)

### Expected behavior

The action buttons should stay within the dialog box.

### Describe the bug

The action buttons are rendered outside the dialog box. It seems like [the code](https://github.com/react-native-elements/react-native-elements/blob/587d8dbf8aef0beb9cd42683f16e52bbbe3b99c1/packages/base/src/Dialog/Dialog.Actions.tsx#L24) is currently adding a -35 right margin. I don't know if this is intended, but removing it fixes the issue.

It seems to be working fine on mobile.

### Steps To Reproduce

```markdown
1. Go to https://reactnativeelements.com/docs/components/dialog
2. Ensure you have the web version of snack selected
3. Click on the "Open Multi Action Dialog"
```

### Screenshots

![image](https://user-images.githubusercontent.com/8052355/163008375-4f70f421-35e6-42df-bee2-3f61244e6d9d.png)

### Your Environment

```markdown
- react-native-elements: 4.0.0-rc.1
- web
```

**Comment by JBradBarnes** [comment]
I was just about to do this exact issue off of the example :)
Might as well post a quick web workaround since I'm here...
Just wrap the Dialog.Actions in another view container.

```
export const DefaultDialogActions = (props) => (
  <View>
    <Dialog.Actions {...props} />
  </View>
);
```

**Comment by louislatreille** [comment]
@JBradBarnes I've tried your work-around and it doesn't seem to do anything for me.

@kedar09 This seems like a trivial change. Anything I can do to help merge your PR?

**Comment by arpitBhalla** [comment]
This change will be available in next release. You can try this, by installing [Bleeding Edge](https://reactnativeelements.com/docs/next/installation#bleeding-edge) version

or you can try with expo template
```bash
expo init app --template @rneui/template@bleeding-edge
```
