### ISSUE TITLE
SpeedDial.Action titles should be pressable

### ISSUE THREAD

**Issue by juho-ylikyla** [react-native-elements/react-native-elements#3463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

Pressing the speed dial actions sometimes does not trigger the `onPress` event. This may be due to the fact that the titles are not pressable.

### Expected behavior

Pressing the action title should trigger the actions `onPress` event

### Describe the bug

Attempting to press the speed dial action title does not trigger the `onPress` event

### Steps To Reproduce

```markdown
1. Open the example app
2. Go to Speed Dial screen
3. Tap on the "Add" title (not the FAB)
4. Notice that the action is not triggered
```

### Screenshots

![CleanShot 2022-04-20 at 09 32 32@2x](https://user-images.githubusercontent.com/62982612/164165233-e117ba52-72ab-4d22-8d1f-ed958abda5a3.png)

### Your Environment

```markdown
* react-native-elements: 3.4.2
* react-native: 0.67.3
```

**Comment by arpitBhalla** [comment]
This change will be available in next release. You can try this, by installing [Bleeding Edge ](https://reactnativeelements.com/docs/next/installation) version

or you can try with expo template
```bash
expo init app --template @rneui/template@bleeding-edge
```
