### ISSUE TITLE
Speed Dial Placement left doesnt move the speed dial actions

### ISSUE THREAD

**Issue by KrisLau** [react-native-elements/react-native-elements#3465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

Set `placement={'left'}` on `SpeedDial` and only the speed dial button moved left while the speed dial actions stayed right instead of the speed dial button and its actions.

### Expected behavior

Whole component should move right with the speed dial actions being placed above the speed dial behaviour on the left

### Describe the bug

only the speed dial button moved left instead of the speed dial button and its actions

### Steps To Reproduce

```markdown
<SpeedDial 
 placement={'left'}>
    ...
</SpeedDial>
```

### Screenshots

![image](https://user-images.githubusercontent.com/46275463/164478190-5805ebac-ca13-4b3e-adce-66ec8fcdb329.png)

### Your Environment

```markdown
react-native-elements: 3.4.2
react-native: 0.64.3
```

**Comment by arpitBhalla** [comment]
This change will be available in next release. You can try this, by installing [Bleeding Edge ](https://reactnativeelements.com/docs/next/installation) version

or you can try with expo template
```bash
expo init app --template @rneui/template@bleeding-edge
```

**Comment by KrisLau** [comment]
@arpitBhalla Ahh ok thank you! I'll close off the issue
