### ISSUE TITLE
Custom icon for ListItem.Accordion not working

### ISSUE THREAD

**Issue by mbastian93** [react-native-elements/react-native-elements#3499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I am trying to use a custom 'expand' icon for the ListItem.Accordion.

### Expected behavior

The custom icon should be displayed

### Describe the bug

The provided custom icon is ignored and the default icon is not displayed either

### Steps To Reproduce

reproduction here : [snack](https://snack.expo.dev/mdj8ch9-v?)

**Comment by arpitBhalla** [comment]
Please mention the version, you are using.

**Comment by mbastian93** [comment]
In my local project i used v^3.4.2 and for the repro on snack i used v4.0.0-rc.2 and neither worked as expected.

**Comment by arpitBhalla** [comment]
For now, You can use 
```
        expandIcon={{name:"place"}}
        icon={{name:"place"}}
```

**Comment by mbastian93** [comment]
> For now, You can use
> 
> ```
>         expandIcon={{name:"place"}}
>         icon={{name:"place"}}
> ```

Okay, that does work 👍
