### ISSUE TITLE
I cant acces to custom props from makeStyles method

### ISSUE THREAD

**Issue by crisfcodes** [react-native-elements/react-native-elements#3515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I want to access custom props declared in `theme.d.ts` file inside `makeStyles` method how I can do in `useStyles`. I can do something like:

```ts
const {theme} = useTheme();
console.log(theme.myCustomProp);
```

but I cant do this:

```ts
const useStyles = makeStyle((theme) => ({
    someStyle: {
        fontSize: theme.myCustomProp;
    }
}))
```

### Expected behavior

I'm getting TS erros trying to acces custom props in makeStyle method.

### Describe the bug

I'm trying to access custom properties declared in `theme.d.ts` in `makeStyle` method, but I'm getting TS errors because `makeStyles` cant access to custom props declared in `theme.d.ts`.  This is the current error that I'm getting:

`TS2339: Property 'InputSize' does not exist on type '{ colors: Colors; mode: ThemeMode; }'.`

### Steps To Reproduce

1. add a custom prop in Theme:

```ts
import "@rneui/themed";

declare module '@rneui/themed' {
  // Adding custom 'other' properties
  export interface Theme {
    ListItemSize: Sizes<ListItemStyle>;
    InputSize: Sizes<InputFocus>;
  }
}
```

2.  Try to access from `makeStyle` method:

```ts
export const getStyles = makeStyles((theme) => ({
  inputSize: theme.InputSize, // this thrown
}))
```

### Screenshots

![image](https://user-images.githubusercontent.com/20000951/168176697-36e67136-5b54-4a9b-8eb2-a073851b9813.png)

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
        "@rneui/base": "^4.0.0-rc.3",
        "@rneui/themed": "^4.0.0-rc.3",
        "react-native": "0.67.2",
      ```

</details>

**Comment by arpitBhalla** [comment]
FOr now, you can export the theme,
```tsx
export const theme = createTheme({
  InputSize: "12px",
  darkColors: {},
  lightColors: {},
});
```
and use it 
```tsx
import { theme } from 'theme.ts';

//...

const getStyles = makeStyles({
  inputSize: theme.InputSize,
});

```
