### ISSUE TITLE
@rneui/themed - New version of react results in error for Button -> "undefined is not an object (evaluating 'theme.spacing[radius]')"

### ISSUE THREAD

**Issue by brycedeneen** [react-native-elements/react-native-elements#3519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

Upgraded to the new react version on a working project. When I go back to the standard react button the error goes away

### Expected behavior

The button to load/work

### Describe the bug

When using the @rneui/themed regardless of what I use for radius (or don't use) it crashes the app and the error message is "undefined is not an object (evaluating 'theme.spacing[radius]')"

### Steps To Reproduce

```Markdown
Here is my code for easy reference  (I commented a few things out but did try to set radius to different sizes, numeric values, etc, all result in this error).

import {Button} from '@rneui/themed';
import React from 'react';
import {StyleSheet} from 'react-native';

export default function MYButton(props: any) {
    return (
        <Button
            buttonStyle={[styles.button, props.buttonStyle]}
            titleStyle={props.titleStyle}
            title={props.title}
            type={props.type}
            onPress={props.onPress}
            disabled={props.disabled ?? false}
            loading={props.loading}
            icon={{name: props.iconName, color: props.iconColor}}
            // loadingRight={props.loading ? props.loading : true}
            // radius={'xs'}
        />
    );
}

const styles = StyleSheet.create({
    button: {
        marginBottom: 7,
        marginTop: 10,
        // borderRadius: 20,
    },
});
```

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
        Output from `npx @rneui/envinfo` goes here.
      ```

</details>

**Comment by brycedeneen** [comment]
Forgot to add:

- I'm using:
- "@rneui/base": "^4.0.0-rc.3",
- "@rneui/themed": "^4.0.0-rc.3",
- using base works fine (aka import {Button} from '@rneui/base');

**Comment by arpitBhalla** [comment]
Thanks for reporting, For now you can add ThemeProvider in root of your app.

**Comment by shwky** [comment]
@brycedeneen 
------> using base works fine (aka import {Button} from '@rneui/base');
this line saved me in an infinite loop of app crashing 
I was importing elements like  :
import {Button} from '@rneui/themed';
and this was the problem of crashing the app
after I've changed all the components imports to be for example
import {Button} from '@rneui/base';
the app works again.
Thank you so so so much.
