### ISSUE TITLE
Example App Doesn't work on web on windows

### ISSUE THREAD

**Issue by jdinard** [react-native-elements/react-native-elements#3528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

Installed the expo CLI

Fresh cloned the repo and followed the instructions here: https://github.com/react-native-elements/react-native-elements/tree/next/example

Ran yarn install

Ran yarn web

I'm not sure if this issue is because of an incompatible expo version etc.

### Expected behavior

Application should run as per instructions

### Describe the bug

The app throws the following exceptions and does not run

`../packages/themed/src/index.ts 131:7
Module parse failed: Unexpected token (131:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| // Components Props exports
> export type {
|   AvatarProps,
|   BadgeProps,
../packages/base/src/Image/index.tsx 14:7
Module parse failed: Unexpected token (14:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { Image };
> export type { ImageProps };
|
../packages/base/src/Dialog/index.tsx 14:7
Module parse failed: Unexpected token (14:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| });
|
> export type {
|   DialogProps,
|   DialogLoadingProps,
../packages/base/src/helpers/index.tsx 15:7
Module parse failed: Unexpected token (15:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| const isIOS = Platform.OS === 'ios';
|
> export type StringOmit<K extends string> = K | Omit<string, K>;
|
| export type RneFunctionComponent<T> = React.FunctionComponent<
../packages/base/src/LinearProgress/index.tsx 16:33
Module parse failed: Unexpected token (16:33)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| const LinearProgress = Object.assign(LinearProgressBase, {
>   INDETERMINATE: 'indeterminate' as LinearProgressProps['variant'],
|   DETERMINATE: 'determinate' as LinearProgressProps['variant'],
| });
../packages/base/src/Card/index.tsx 23:7
Module parse failed: Unexpected token (23:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { Card };
> export type {
|   CardProps,
|   CardDividerProps,
../packages/base/src/ListItem/index.tsx 33:7
Module parse failed: Unexpected token (33:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| });
|
> export type {
|   ListItemAccordionProps,
|   ListItemButtonGroupProps,
../packages/base/src/AirbnbRating/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { AirbnbRating };
> export type { TapRatingProps };
|
../packages/base/src/BottomSheet/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { BottomSheet };
> export type { BottomSheetProps };
|
../packages/base/src/Button/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { Button };
> export type { ButtonProps };
|
../packages/base/src/ButtonGroup/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { ButtonGroup };
> export type { ButtonGroupProps };
|
../packages/base/src/CheckBox/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { CheckBox };
> export type { CheckBoxProps };
|
../packages/base/src/Chip/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { Chip };
> export type { ChipProps };
|
../packages/base/src/Divider/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { Divider };
> export type { DividerProps };
|
../packages/base/src/FAB/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { FAB };
> export type { FABProps };
|
../packages/base/src/Header/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { Header };
> export type { HeaderProps };
|
../packages/base/src/Icon/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { Icon };
> export type { IconProps, IconNode, IconObject, IconType };
|
../packages/base/src/Input/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { Input };
> export type { InputProps };
|
../packages/base/src/Overlay/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { Overlay };
> export type { OverlayProps };
|
../packages/base/src/PricingCard/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { PricingCard };
> export type { PricingCardProps };
|
../packages/base/src/Rating/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { Rating };
> export type { SwipeRatingProps };
|
../packages/base/src/Skeleton/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { Skeleton };
> export type { SkeletonProps };
|
../packages/base/src/Slider/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { Slider };
> export type { SliderProps };
|
../packages/base/src/SocialIcon/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { SocialIcon };
> export type { SocialIconProps };
|
../packages/base/src/Switch/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { Switch };
> export type { SwitchProps };
|
../packages/base/src/Text/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { Text };
> export type { TextProps };
|
../packages/base/src/Tile/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { Tile };
> export type { TileProps };
|
../packages/base/src/Tooltip/index.tsx 4:7
Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { Tooltip };
> export type { TooltipProps };
|
../packages/base/src/Badge/index.tsx 5:7
Module parse failed: Unexpected token (5:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { withBadge, Badge };
> export type { BadgeProps };
|
../packages/base/src/SearchBar/index.tsx 7:7
Module parse failed: Unexpected token (7:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export { SearchBar };
> export type {
|   SearchBarProps,
|   SearchBarAndroidProps,
../packages/base/src/TabView/index.tsx 7:7
Module parse failed: Unexpected token (7:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   Item: TabViewItem,
| });
> export type { TabViewProps, TabViewItemProps };
|
../packages/base/src/Tab/index.tsx 8:7
Module parse failed: Unexpected token (8:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| });
|
> export type { TabProps, TabItemProps };
|
../packages/base/src/SpeedDial/index.tsx 8:7
Module parse failed: Unexpected token (8:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| });
| export { DefaultSpeedDial as SpeedDial };
> export type { SpeedDialProps, SpeedDialActionProps };
|
../packages/base/src/Avatar/index.tsx 9:7
Module parse failed: Unexpected token (9:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export { Avatar, Accessory };
|
> export type { AccessoryProps, AvatarProps };`

### Steps To Reproduce

```Markdown
Follow instructions using yarn on windows:
https://github.com/react-native-elements/react-native-elements/tree/next/example

The example app will not run
```

### Screenshots

![image](https://user-images.githubusercontent.com/1543081/168719180-5f051705-9a24-4aa2-a081-cfeff134215e.png)

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>
npx: installed 2 in 2.032s

## npmGlobalPackages:
 - expo: Not Found
 - typescript: Not Found
 - react-native-cli: Not Found

<summary>`npm list -g --depth 0`</summary>

## npm global packages I have installed:
+-- expo-cli@5.4.4
+-- firebase-tools@9.20.0
+-- typescript@4.6.4
`-- yarn@1.22.17

</details>

**Comment by arpitBhalla** [comment]
I am using `expo-cli@5.3.1`, working fine for me 🤔 
<img width="410" alt="image" src="https://user-images.githubusercontent.com/55053424/168814388-af5dc05d-a898-4262-997f-efed13f5e39b.png">

**Comment by jdinard** [comment]
@arpitBhalla Are you using a fresh clone of the repo? What OS are you using? Were you able to launch the app? I also get a notice that the web bundling is complete, but then it throws a bunch of exceptions.

I've confirmed it on two windows machines now. I'm pretty sure there is something missing that isn't in the setup instructions.

 It seems to be failing on every typescript file.

![image](https://user-images.githubusercontent.com/1543081/168908206-ceb0c47e-fff4-4acc-9d9b-28328e0d0711.png)

**Comment by arpitBhalla** [comment]
Tried on macOS & Ubuntu with fresh clone, working fine...

**Comment by slayer1551** [comment]
Getting the same issue, works fine for iOS on the app but running the web version gives an error

**Comment by arpitBhalla** [comment]
@slayer1551 which OS?

**Comment by slayer1551** [comment]
> @slayer1551 which OS?

@arpitBhalla Im running it on Windows 11

**Comment by enisze** [comment]
I get the same issue running on mac OS.

**Comment by jeton-th** [comment]
I have the same issue, fresh expo and rne install.

**Comment by Matthew-Burfield** [comment]
I had the same issue. It seems like it's caused by webpack not yet supporting optional chaining in typescript.

The temporary fix is to configure a webpack file to tell babel to also transpile the @rneui components

## Steps to fix

1. Install expo webpack config dependency
`npm i -D @expo/webpack-config`

2. Create webpack.config.js in the root folder of the project and add the code snippet below
```
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function(env, argv) {
    const config = await createExpoWebpackConfigAsync({
        ...env,
        babel: {
            dangerouslyAddModulePathsToTranspile: ['@rneui/base/dist', '@rneui/themed/dist']
        }
    }, argv);
    return config;
};
```

If you want to read more, I found this solution here:
https://github.com/akveo/react-native-ui-kitten/issues/996#issuecomment-616115469

and here:
https://stackoverflow.com/questions/61124258/expo-web-failed-to-compile-optional-chaining/61124524#61124524

**Comment by arpitBhalla** [comment]
Will work now
