### ISSUE TITLE
Previews broken (`undefined is not an object` for `te.spacing[M]` or `te.spacing`)

### ISSUE THREAD

**Issue by bradjones1** [react-native-elements/react-native-elements#3548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

Attempted to access the web or android previews on https://reactnativeelements.com/docs/next/components/dialog (or any page, really)

### Expected behavior

Preview renders

### Describe the bug

React crashes with either `undefined is not an object` for `te.spacing[M]` or `te.spacing`

### Steps To Reproduce

```Markdown
Go to a component page, access the preview.
```

### Your Environment

Web preview.

**Comment by bradjones1** [comment]
May be a duplicate of https://github.com/react-native-elements/react-native-elements/issues/3530?

**Comment by golaod** [comment]
I found out that documentation examples do not mention that `<ThemeProvider>` probably should wrap the entire app in order to make some examples to work (if not all)

**Comment by arpitBhalla** [comment]
Yes, but it should work without provider too, will check it.
