### ISSUE TITLE
i set tab index， but  indicator dont scroll  to setting  index

### ISSUE THREAD

**Issue by gdutwyg** [react-native-elements/react-native-elements#3549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

i set tab index， but  indicator dont scroll  to setting  index

### Expected behavior

i set tab index， indicator can scroll  to setting  index

### Describe the bug

i set tab index， but  indicator dont scroll  to setting  index

### Steps To Reproduce

```Markdown
i set tab index， but  indicator dont scroll  to setting  index
```

### Screenshots

![image](https://user-images.githubusercontent.com/11848087/172773862-438d5865-3590-4ac8-bbe2-417745805bac.png)

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
        Output from `npx @rneui/envinfo` goes here.
      ```

</details>

**Comment by saurabhghadi0401** [comment]
I also get the same...

**Comment by GaylordP** [comment]
Same :/

Example : https://snack.expo.dev/jYgi_1HDV

**Comment by arpitBhalla** [comment]
Can someone test this with 
```bash
 npm i react-native-elements/react-native-elements#base-3564 react-native-elements/react-native-elements#themed-3564
```
