### ISSUE TITLE
Tooltip doesn't toggle out of the box

### ISSUE THREAD

**Issue by goldylucks** [react-native-elements/react-native-elements#3557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

copied the tooltip example from the docs, pressed any of the tooltips, nothing happened.

### Expected behavior

tooltip should toggle on tap

### Describe the bug

tooltip should toggle on tap

I fixed it by wrapping the tooltip in my own component:

```
import React, { useState } from "react"
import { Tooltip as RNTooltip, Text } from "@rneui/themed"

export default function Tooltip({ children, popover }: IProps) {
  const [isOpen, setIsOpen] = useState(false)
  const _popover =
    typeof popover === "string" ? <Text>{popover}</Text> : popover

  return (
    <RNTooltip
      onOpen={() => setIsOpen(true)}
      onClose={() => setIsOpen(false)}
      visible={isOpen}
      popover={_popover}
      withPointer={false}
      // eslint-disable-next-line react-native/no-inline-styles
      containerStyle={{
        backgroundColor: "white",
        borderColor: "#eee",
        borderWidth: 1,
        justifyContent: "center",
        width: 200,
      }}
    >
      {children}
    </RNTooltip>
  )
}

interface IProps {
  children: React.ReactElement
  popover: React.ReactElement | string
}

```

### Steps To Reproduce

```Markdown
1. Copy tooltip example from the docs
2. press any of the tooltips
```

### Your Environment

running `npx @rneui/envinfo` hung for a few minutes, tried several times

**Comment by arpitBhalla** [comment]
Default behaviour of this component has been changed, refer [Migration Guide](https://reactnativeelements.com/blog/2022/05/15/rneui-migration-guide#tooltip)
