### ISSUE TITLE
Custom theme properties missing when using withTheme

### ISSUE THREAD

**Issue by mfellner** [react-native-elements/react-native-elements#3571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

Add a custom property to the theme like this:

```ts
declare module '@rneui/themed' {
  export interface Theme {
    typography: {
      title: TextStyle;
    };
  }
}

export const theme = createTheme({
  typography: {
    title: {
      fontSize: normalize(18),
      fontWeight: '600',
    },
  },
});
```

Wrap a component with `withTheme` and access the property:

```ts
export const Text = withTheme<TextProps, Theme>(
  ({ theme }) => {
    // theme.typography should be defined
    return (/* ... */);
  },
);

```

### Expected behavior

The custom property should present in the theme object when wrapping a component with `withTheme`.

### Describe the bug

- The custom theme property is missing from the `theme` object when wrapping a component with `withTheme`.
- Modifying existing theme properties, like `spacing`, works.
- Getting the theme object with `useTheme` works: the object includes the custom theme property!
- Related issue: https://github.com/react-native-elements/react-native-elements/issues/3444

### Steps To Reproduce

```Markdown
1. Create a custom theme and add a custom property
2. Wrap a component with withTheme
3. Try to access the custom theme property from the `theme` prop.
```

### Your Environment

- macOS 12.4
- Node 16.15.1
- expo 45.0.6
- react 17.0.2
- react-native 0.68.2
- @rneui/themed 4.0.0-rc.5
- @rneui/base "4.0.0-rc.5

**Comment by arpitBhalla** [comment]
Can you use with `useTheme` hook for now.

**Comment by ste7en** [comment]
I temporarily solved a similar issue when wrapping a custom component theme using the `<ThemeConsumer>` wrapper
