### ISSUE TITLE
Copying the example given in the documentation for Tab component leads to TS errors

### ISSUE THREAD

**Issue by RaederDev** [react-native-elements/react-native-elements#3574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I tried to set-up Tabs with a TabView and I used the example provided in the documentation. https://reactnativeelements.com/docs/components/tab

### Expected behavior

Typescript does not complain.

### Describe the bug

`TS2769: No overload matches this call.   Overload 1 of 2, '(props: TabViewProps & { theme?: Theme | undefined; }, context?: any): ReactElement<any, any> | null', gave the following error.     Type '{ children: Element[]; value: number; onChange: Dispatch<SetStateAction<number>>; animationType: "spring"; }' is not assignable to type 'IntrinsicAttributes & TabViewProps & { theme?: Theme | undefined; }'.       Property 'children' does not exist on type 'IntrinsicAttributes & TabViewProps & { theme?: Theme | undefined; }'.   Overload 2 of 2, '(props: TabViewProps & { theme?: Theme | undefined; }): ReactElement<any, any> | null', gave the following error.     Type '{ children: Element[]; value: number; onChange: Dispatch<SetStateAction<number>>; animationType: "spring"; }' is not assignable to type 'IntrinsicAttributes & TabViewProps & { theme?: Theme | undefined; }'.       Property 'children' does not exist on type 'IntrinsicAttributes & TabViewProps & { theme?: Theme | undefined; }'.`

If I remove all children from the TabView component TS doesn't complain anymore but obviously now my tabs also don't have any content. 

### Steps To Reproduce

```Markdown
Copy and paste the example provided in the documentation:  
https://reactnativeelements.com/docs/components/tab
```
```JSX
import React from 'react';
import { Tab, Text, TabView } from '@rneui/themed';

export default () => {
const [index, setIndex] = React.useState(0);

return (
  <>
    <Tab
      value={index}
      onChange={(e) => setIndex(e)}
      indicatorStyle={{
        backgroundColor: 'white',
        height: 3,
      }}
      variant="primary"
    >
      <Tab.Item
        title="Recent"
        titleStyle={{ fontSize: 12 }}
        icon={{ name: 'timer', type: 'ionicon', color: 'white' }}
      />
      <Tab.Item
        title="favorite"
        titleStyle={{ fontSize: 12 }}
        icon={{ name: 'heart', type: 'ionicon', color: 'white' }}
      />
      <Tab.Item
        title="cart"
        titleStyle={{ fontSize: 12 }}
        icon={{ name: 'cart', type: 'ionicon', color: 'white' }}
      />
    </Tab>

    <TabView value={index} onChange={setIndex} animationType="spring">
      <TabView.Item style={{ backgroundColor: 'red', width: '100%' }}>
        <Text h1>Recent</Text>
      </TabView.Item>
      <TabView.Item style={{ backgroundColor: 'blue', width: '100%' }}>
        <Text h1>Favorite</Text>
      </TabView.Item>
      <TabView.Item style={{ backgroundColor: 'green', width: '100%' }}>
        <Text h1>Cart</Text>
      </TabView.Item>
    </TabView>
  </>
);
};
```

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```

  System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 18.43 GB / 31.26 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.3.0 - /usr/bin/node
    npm: 8.5.5 - /usr/bin/npm
  Managers:
    Composer: 2.3.7 - /usr/bin/composer
  Utilities:
    Make: 4.3 - /usr/bin/make
    GCC: 12.1.0 - /usr/bin/gcc
    Git: 2.36.1 - /usr/bin/git
    Clang: 13.0.1 - /usr/bin/clang
    FFmpeg: 5.0.1 - /usr/bin/ffmpeg
  Servers:
    Apache: 2.4.54 - /usr/bin/apachectl
  Virtualization:
    Docker: 20.10.17 - /usr/bin/docker
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Nano: 6.3 - /usr/bin/nano
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
    Perl: 5.36.0 - /usr/bin/perl
    PHP: 8.1.7 - /usr/bin/php
    Protoc: 3.21.1 - /usr/bin/protoc
    Python: 3.10.5 - /usr/bin/python
    Python3: 3.10.5 - /usr/bin/python3
  Databases:
    MySQL: 10.8.3 (MariaDB) - /usr/bin/mysql
    SQLite: 3.38.5 - /usr/bin/sqlite3
  Browsers:
    Firefox: 102.0


      ```

</details>

**Comment by arpitBhalla** [comment]
What's the version of react, react-native, expo, typescript?

**Comment by RaederDev** [comment]
> What's the version of react, react-native, expo, typescript?

"react": "18.0.0"
"react-native": "0.69.1"
"typescript": "^4.4.4"
"@rneui/base": "^4.0.0-rc.5"
"@rneui/themed": "^4.0.0-rc.5"

Expo is not used in my project.

**Comment by atothewest** [comment]
The type definitions for React 18 [removed implicit children](https://solverfox.dev/writing/no-implicit-children/) from `React.FC`/`React.FunctionalComponent`, which is used by [RneFunctionComponent](https://github.com/react-native-elements/react-native-elements/blob/next/packages/base/src/helpers/index.tsx#L17) and in turn by the `Tab` component (and also the `Card` component #3556 – and probably others).

The fix here would be to amend `RneFunctionComponent` to explicitly type `children` or to use [PropsWithChildren](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L799)

```
export type RneFunctionComponent<T> = React.FunctionComponent<
  React.PropsWithChildren<T> & {
    theme?: Theme;
  }
>;
```
