### ISSUE TITLE
Typescript error:  expected.  2 import { type Colors, darkColors, lightColors } from './colors'

### ISSUE THREAD

**Issue by jorgerodrigues** [react-native-elements/react-native-elements#3581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

- Installed new version
- Imported and used ´Input´ and ´InputProps´
- Ran ´yarn tsc´

### Expected behavior

No type errors

### Describe the bug

```
node_modules/@rneui/themed/dist/config/index.d.ts:2:15 - error TS1005: ',' expected. 
2 import { type Colors, darkColors, lightColors } from './colors';
```

### Steps To Reproduce

```Markdown
- Install new version
- Import and use ´Input´ and ´InputProps´
- Ran ´yarn tsc´
```

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
        Output from `npx @rneui/envinfo` goes here.
      ```

</details>

**Comment by arpitBhalla** [comment]
Duplicate of #3579
