### ISSUE TITLE
Switch component error "attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference"

### ISSUE THREAD

**Issue by jorgegvallejo** [react-native-elements/react-native-elements#3587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

A simple usage of the Switch component in Android throws an error when setting it to `false`. Error doesn't occur in iOS or when setting it as `true`.

### Expected behavior

Should be able to switch between `true` and `false`

### Describe the bug

When switching to `false` on Android, it throws an exception `"attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference"`

### Steps To Reproduce

```Markdown
Plain usage of the Switch component


const Switched = (props)=> {

  const [val, setVal] = useState(false);

return <Switch value={val} onValueChange={(v)=> setVal(v)}/>
}
```

### Screenshots

![IMG_6420](https://user-images.githubusercontent.com/33339972/179783808-0df6b25f-60a1-4f3c-885a-b884e95243be.jpg)

### Your Environment

"react-native": "0.67.3",
"@rneui/base": "^4.0.0-rc.4",
"@rneui/themed": "^4.0.0-rc.4",

**Comment by arpitBhalla** [comment]
@jorgegvallejo Can you confirm if you are able to use `Switch` from `react-native`?

**Comment by jorgegvallejo** [comment]
> @jorgegvallejo Can you confirm if you are able to use `Switch` from `react-native`?

Yes, the react-native switch works fine. I got this error on the emulator and on real device, btw.
