### ISSUE TITLE
Tooltip not work in any V4 online examples including Next

### ISSUE THREAD

**Issue by JBradBarnes** [react-native-elements/react-native-elements#3611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

Opened the docs page: https://reactnativeelements.com/docs/next/components/tooltip and tried to click text to view tooltips.
<img width="803" alt="image" src="https://user-images.githubusercontent.com/20904634/184431934-0675370a-a9b3-422a-ab3f-a8a8e55c9729.png">
the 

### Expected behavior

A popup with text should be above the example text when clicked.

### Describe the bug

No popup text

### Steps To Reproduce

```Markdown
Go to Doc page: https://reactnativeelements.com/docs/next/components/tooltip
Click on the text in Expo Snack
Nothing happens
```

### Screenshots

<img width="785" alt="image" src="https://user-images.githubusercontent.com/20904634/184432294-3a2f4ad4-a437-4bb7-9aa5-8bd766690d01.png">

### Your Environment

Web Browser Chrome, Expo Snack

**Comment by kollinmurphy** [comment]
I'm having the same problem on the web, and the Tooltip is also not working in my own Expo app (tried on both 4.0.0-rc.6 and 4.0.0-rc.4).

**Comment by vitoliu93** [comment]
same issue

**Comment by chenqiushi** [comment]
same here
