### ISSUE TITLE
`useThemeMode` is not working

### ISSUE THREAD

**Issue by emadbaqeri** [react-native-elements/react-native-elements#3612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I want to control the `backgroundColor` for the `SafeAreaView` and tried to utilize `useThemeMode` in my `App.tsx` file mentioned in the [documentation](https://reactnativeelements.com/docs/customization/themprovider#use-theme-mode-hook) but it is not working at all,

```tsx
const App = () => {
    const {mode} = useThemeMode();
    return (
        <SafeAreaView style={{backgroundColor: mode === "dark" ? "#000" : "#fff"}}>
            ...
        </SafeAreaView>
    )
}
```

### Expected behavior

expected behavior was that I should be able to detect the theme from inside the app

### Describe the bug

I can't not detect the themeMode inside app.tsx file

### Steps To Reproduce

```Markdown
Just follow the documentation and put the logic in the app.tsx file
```

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
        Output from `npx @rneui/envinfo` goes here.
      ```

</details>
And I'm getting nothing out of that

**Comment by arpitBhalla** [comment]
Have you used ThemeProvider in the root of your app?

**Comment by arpitBhalla** [comment]
Wrap `App` component with `ThemeProvider`

```tsx
const App = () => {
    const {mode} = useThemeMode();
    return (
        <SafeAreaView style={{backgroundColor: mode === "dark" ? "#000" : "#fff"}}>
            ...
        </SafeAreaView>
    )
}

const Root=()=>{
return <ThemeProvider><App/></ThemeProvide>
};

```
