### ISSUE TITLE
Property 'children' does not exist on type 'IntrinsicAttributes & AvatarProps in React 18

### ISSUE THREAD

**Issue by JacobGalati** [react-native-elements/react-native-elements#3628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

Use an Avatar component with a Avatar.Accessory child component

### Expected behavior

Avatar should accept the children prop. 

### Describe the bug

After upgrading to react-native 0.69.5 and react 18.0.0  a simple avatar component like 
```jsx
<Avatar source={source}>
    <Avatar.Accessory size={32}/>
</Avatar>
```
Causes a typescript error. 
```
Property 'children' does not exist on type 'IntrinsicAttributes & AvatarProps'
```

### Steps To Reproduce

```Markdown
https://snack.expo.dev/@thenumber_tech/avatar-typescript-error-example
```

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
        Output from `npx @rneui/envinfo` goes here.
      ```

</details>

**Comment by bartvanandel** [comment]
Got the same issue (may help with triage). Running `npx @rneui/envinfo` halts, so can't provide that, but maybe this helps:

<details>
<summary>npm ls --depth=0</summary>

    @org/our_app@0.0.1 D:\src\org\our_app
    ├── @babel/core@7.18.13
    ├── @expo/config@7.0.1
    ├── @react-native-async-storage/async-storage@1.17.10
    ├── @react-navigation/bottom-tabs@6.3.3
    ├── @react-navigation/native@6.0.12
    ├── @react-navigation/stack@6.2.3
    ├── @rneui/base@4.0.0-rc.6
    ├── @rneui/layout@0.0.0-alpha.4
    ├── @rneui/themed@4.0.0-rc.6
    ├── @types/color@3.0.3
    ├── @types/lodash@4.14.184
    ├── @types/react-native-calendars@1.1264.3
    ├── @types/react-native@0.69.6
    ├── @types/react@18.0.18
    ├── axios@0.27.2
    ├── babel-plugin-transform-inline-environment-variables@0.4.4
    ├── color@4.2.3
    ├── date-fns@2.29.2
    ├── dotenv@16.0.2
    ├── expo-auth-session@3.7.1
    ├── expo-constants@13.2.4
    ├── expo-dev-client@1.2.1
    ├── expo-device@4.3.0
    ├── expo-document-picker@10.3.0
    ├── expo-file-system@14.1.0
    ├── expo-font@10.2.0
    ├── expo-image-picker@13.3.1
    ├── expo-localization@13.1.0
    ├── expo-location@14.3.0
    ├── expo-notifications@0.16.1
    ├── expo-random@12.3.0
    ├── expo-status-bar@1.4.0
    ├── expo-updates@0.14.5
    ├── expo@46.0.9
    ├── extract-zip@2.0.1
    ├── fdir@5.2.0
    ├── formik@2.2.9
    ├── lodash@4.17.21
    ├── react-dom@18.0.0
    ├── react-i18next@11.18.5
    ├── react-native-calendars@1.1288.2
    ├── react-native-gesture-handler@2.5.0
    ├── react-native-maps@0.31.1
    ├── react-native-safe-area-context@4.3.1
    ├── react-native-svg@12.3.0
    ├── react-native-web@0.18.9
    ├── react-native@0.69.5
    ├── react@18.0.0
    ├── tempy@3.0.0
    └── typescript@4.8.2

</details>

**Comment by anietieasuquo** [comment]
Any update on this? I'm having the same issue with BottomSheet since updating to;

`"@rneui/base": "4.0.0-rc.6",
    "@rneui/themed": "4.0.0-rc.6",`
    
I know it's different, but I'm hoping the fix for this should apply as well.

**Comment by jeferson-sb** [comment]
This issue seems to be happening on a lot of components in `@rneui/themed`

**Comment by xiaomaodml** [comment]
Modify the properties defined by the component by adding "children? :React.ReactNode".
That's what I did

**Comment by bartvanandel** [comment]
> Modify the properties defined by the component by adding "children? :React.ReactNode".
> That's what I did

That's exactly what should be provided by the library.

**Comment by lucksp** [comment]
I am seeing this error on `BottomSheet`

> Type '{ children: Element; isVisible: boolean; }' is not assignable to type 'IntrinsicAttributes & BottomSheetProps & Partial<ThemeProps<BottomSheetProps>>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & BottomSheetProps & Partial<ThemeProps<BottomSheetProps>>'.ts(2322)

```js
<BottomSheet isVisible={isWriteOpen}>
        <View>
          <Typography>Write a Review</Typography>
        </View>
      </BottomSheet>
```

`"react-native-elements": "^3.4.3",`
