### ISSUE TITLE
[TabView] iOS TabView issue

### ISSUE THREAD

**Issue by radughitescu** [react-native-elements/react-native-elements#3629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I've tried impementing the example tabview on react native non expo and i get the following error.
<img width="331" alt="image" src="https://user-images.githubusercontent.com/20221798/188488906-57d7a5cc-b786-453c-97c3-35be2aa50f1c.png">

Code:
```
import React from 'react';
import {Tab, Text, TabView} from '@rneui/themed';
import {View} from 'react-native';

export default () => {
  const [index, setIndex] = React.useState(0);

  return (
    <View>
      <Tab
        value={index}
        onChange={e => setIndex(e)}
        indicatorStyle={{
          backgroundColor: 'white',
          height: 3,
        }}
        variant="primary">
        <Tab.Item title="Recent" titleStyle={{fontSize: 12}} />
        <Tab.Item title="favorite" titleStyle={{fontSize: 12}} />
        <Tab.Item title="cart" titleStyle={{fontSize: 12}} />
      </Tab>

      <TabView value={index} onChange={setIndex} animationType="spring">
        <TabView.Item style={{backgroundColor: 'red', width: '100%'}}>
          <Text h1>Recent</Text>
        </TabView.Item>
        <TabView.Item style={{backgroundColor: 'blue', width: '100%'}}>
          <Text h1>Favorite</Text>
        </TabView.Item>
        <TabView.Item style={{backgroundColor: 'green', width: '100%'}}>
          <Text h1>Cart</Text>
        </TabView.Item>
      </TabView>
    </View>
  );
};
```

### Expected behavior

Instead of rendering tabs, i get the error mentioned above in the screenshot.

### Describe the bug

The issue is intermitent on iOS, sometimes when i open the screen with a Tabs component i get the error.
On Android it doesn't happen.

### Steps To Reproduce

```Markdown
1. Create app with npx react-native init AwesomeProject
2.Copy example code
3.Run app on iOS and refresh a few times
4.Error appears

----versions----
"@rneui/base": "^4.0.0-rc.6",
"@rneui/themed": "^4.0.0-rc.6",
"react": "18.0.0",
"react-native": "0.69.4",
```

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
        Output from `npx @rneui/envinfo` goes here.
      ```

</details>

**Comment by tlmader** [comment]
Experiencing the same issue in `4.0.0-rc.3`. Intermittent on iOS and never has happened on Android.

**Comment by mrslimslim** [comment]
My ios app face the same issue in **^4.0.0-rc.6** ,hope it could be fixed soon.

**Comment by sgtpsibin** [comment]
Same issue, i'm using react-native-tab-view instead.

**Comment by d0rkish** [comment]
I am also experiencing this same behavior inconsistently on iOS 15.x. It appears to be a result of the animation interpolation occurring here:

https://github.com/react-native-elements/react-native-elements/blob/4dc1c0f03008521c3c9be0fc7a1d31b5a07ddaa6/packages/base/src/Tab/Tab.tsx#L157

**Comment by abhinav-official** [comment]
found a fix, guys.
@d0rkish @sgtpsibin @mrslimslim @tlmader @radughitescu 

All you need to do is add 
`if (inputRange.length-1!==outputRange.length)return 0;`
after line 53 and before line 54 

in `node_modules/@rneui/base/dist/Tab/Tab.js`

**Comment by radughitescu** [comment]
> 

Great, Thanks for the reply! I guess we should do a pull request to fix this issue.

**Comment by arpitBhalla** [comment]
This change will be available in next release. You can test, by installing [Bleeding Edge](https://reactnativeelements.com/docs/next/installation#bleeding-edge) version

**Comment by jerodb** [comment]
This fixes the problem.

> found a fix, guys. @d0rkish @sgtpsibin @mrslimslim @tlmader @radughitescu
> 
> All you need to do is add `if (inputRange.length-1!==outputRange.length)return 0;` after line 53 and before line 54
> 
> in `node_modules/@rneui/base/dist/Tab/Tab.js`
