### ISSUE TITLE
How to use the current theme color (light/dark) in the style definition inside a Theme

### ISSUE THREAD

**Issue by arpitBhalla** [react-native-elements/react-native-elements#3632]
### Discussed in https://github.com/react-native-elements/react-native-elements/discussions/3631

<div type='discussions-op-text'>

<sup>Originally posted by **marianolc** September  7, 2022</sup>
Hi, I've just created the following theme:

```
const theme = createTheme({
  lightColors: LightAppColors,
  darkColors: DarkAppColors,
  components: {
    ....
    },
  },
});

```

I want to change the color of the input when it's disabled so I tried to add the following in the components part:

```
Input: {
      disabledInputStyle: {
        color: '....',
      },
```

But the problem is I want to use "secondary" , the one that is for light when it's light, and the one that is for dark then it's dark. But it seems that the only option that works there are pure colors, like "#6465DA", so I would need to add the color manually in every input I need to draw. 

Is there any way to achieve this? Or i need to create a single theme for dark/light and the change it manually in the ThemeProvider? Right now is called like this:

```
    <ThemeProvider theme={theme}>
      ...
    </ThemeProvider>
```</div>

**Comment by hufftheweevil** [comment]
So strange... I was just about to post this same exact question, and it's already at the top of the list. So +1 for me!

**Comment by arpitBhalla** [comment]
Well, I have a solution, In createTheme, we can have `theme` param for each component, but I am not sure how efficient it would be.

```diff

const theme = createTheme({
  components: {
-    Input: (props) => ({
+    Input: (props, theme) => ({
      disabledInputStyle: {
-       color: "grey",
+       color: theme.colors.disabled,
      },
    }),
  },
});

```


Please let me know, if you have a better solution.

**Comment by arpitBhalla** [comment]
It'd be great if someone can try it by installing 
```bash
 npm i react-native-elements/react-native-elements#base-3645 react-native-elements/react-native-elements#themed-3645
```

^ @marianolc @hufftheweevil

**Comment by hufftheweevil** [comment]
I installed it but got `TypeError: Cannot read property 'colors' of undefined`. Checking the node_modules folder, it doesn't look like the `dist` files got the change since you've modified the `src` files and there was no build done I'm guessing?

**Comment by arpitBhalla** [comment]
No, the CI build the dist, [check this branch](https://github.com/react-native-elements/react-native-elements/tree/base-3645)
