### ISSUE TITLE
SearchBar doesn't work

### ISSUE THREAD

**Issue by kcLin2708** [react-native-elements/react-native-elements#3633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

Hi there,
I just want to try the SearchBar component with my app. However, I don't see any SearchBar on my iPad.

### Expected behavior

SearchBar should be shown.

### Describe the bug

I did use the code from [React Native Element Website](https://reactnativeelements.com/docs/components/searchbar) but it doesn't work.

### Steps To Reproduce

```Markdown
1. Copy the code from the react native elements of the component SearchBar.
2. Run npm start
3. Open expo on iPad
```

### Screenshots

![image](https://user-images.githubusercontent.com/22289840/189484106-fa06e9ec-5ee1-4ffe-8c3d-685d5ff175ef.png)

### Your Environment

<details>
 System:
    OS: Windows 10 10.0.22622
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
    Memory: 49.56 GB / 63.75 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Managers:
    pip3: 22.2.1 - ~\AppData\Local\Programs\Python\Python310\Scripts\pip3.EXE
  Utilities:
    Git: 2.32.0. - C:\Program Files\Git\cmd\git.EXE
  IDEs:
    VSCode: 1.71.0 - C:\Users\tws80\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Python: 3.10.6 - C:\Users\tws80\AppData\Local\Programs\Python\Python310\python.EXE
  Databases:
    SQLite: 3.36.0 - C:\Users\tws80\anaconda3\Library\bin\sqlite3.EXE
  Browsers:
    Edge: Spartan (44.22621.590.0), Chromium (105.0.1343.33)
    Internet Explorer: 11.0.22621.1

</details>

**Comment by willkrakow** [comment]
It looks like you have several undefined functions you're trying to call in the component: `setValue`, `onClearText`, and `onCancel`.

**Comment by khushal87** [comment]
This doesn't seem to be a bug on our side. Therefore closing this. Please feel free to open it back if its still relevant.
