### ISSUE TITLE
the 'color' style in iconContainerStyle in tab item can't work when change tab

### ISSUE THREAD

**Issue by SpringSan** [react-native-elements/react-native-elements#3654]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Explain what you did

I want to switch tab and wish the icon color can change the other color, ( from black change to white) ,I use iconContainerStyle, and when active equal true change white (color: active ? 'white' : 'black'), it can't work

### Expected behavior

the icon color change to the color I set in iconContainerStyle

### Describe the bug

I want to switch tab and wish the icon color can change the other color, ( from black change to white) ,I use iconContainerStyle, and when active equal true change white (color: active ? 'white' : 'black'), it can't work。

### Steps To Reproduce

```Markdown
<Tab.Item
          title="BT"
          titleStyle={active => ({
            fontSize: 12,
            color: active ? 'white' : 'black',
          })}
          containerStyle={active => ({
            backgroundColor: active ? '#216FED' : undefined,
          })}
          icon={{
            name: 'thermometer-alt',
            type: 'fontisto',
          }}
          iconContainerStyle={active => ({
            color: active ? 'white' : 'black',
          })}
        />
```

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
        Output from `npx @rneui/envinfo` goes here.
      ```

</details>

**Comment by SpringSan** [comment]
titleStyle  and containerStyle can work, but iconContainerStyle can't work。

**Comment by arpitBhalla** [comment]
Unfortunately, `iconContainerStyle` is for Outer container of `Icon`, you have to manually change icon's color for now,
```		
		icon={{
            name: 'thermometer-alt',
            type: 'fontisto',
			color: activeIndex===index ? "red" : "blue"
          }}
```
