### ISSUE TITLE
Docs pages each appear in search twice (once valid links, once invalid)

### ISSUE THREAD

**Issue by Nantris** [react-native-elements/react-native-elements#3666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

Search for "Icon" (or anything else) in the docs https://reactnativeelements.com/docs/components/icon

I have cleared cache and waited some days for server said caching maybe to resolve, but the search remains broken in this way.

### Expected behavior

Docs should only appear in search once

### Describe the bug

Docs should only appear in search once

### Steps To Reproduce

```Markdown
Search for "Icon" (or anything else) in the docs https://reactnativeelements.com/docs/components/icon
```

### Your Environment

N/A

**Comment by arpitBhalla** [comment]
I have reindexed the website
