### ISSUE TITLE
Peer dependency issue

### ISSUE THREAD

**Issue by relense** [react-native-elements/react-native-elements#3697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I wanted to install latest packages with npm. 

### Expected behavior

That everything works fine with npm install.

### Describe the bug

When I run npm i it gives an error because of dependecies.
```
 "react-native-elements": "^3.4.2",
 "react-native-safe-area-context": "^4.4.1",

```

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: react-native-elements@3.4.2
npm ERR! Found: react-native-safe-area-context@4.4.1
npm ERR! node_modules/react-native-safe-area-context
npm ERR!   react-native-safe-area-context@"^4.4.1" from the root project
npm ERR!   peer react-native-safe-area-context@">= 3.0.0" from @react-navigation/bottom-tabs@6.4.3
npm ERR!   node_modules/@react-navigation/bottom-tabs
npm ERR!     @react-navigation/bottom-tabs@"^6.4.0" from the root project
npm ERR!   2 more (@react-navigation/elements, @react-navigation/stack)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native-safe-area-context@"^3.1.9" from react-native-elements@3.4.2
npm ERR! node_modules/react-native-elements
npm ERR!   react-native-elements@"^3.4.2" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react-native-safe-area-context@3.4.1
npm ERR! node_modules/react-native-safe-area-context
npm ERR!   peer react-native-safe-area-context@"^3.1.9" from react-native-elements@3.4.2
npm ERR!   node_modules/react-native-elements
npm ERR!     react-native-elements@"^3.4.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/miguelfurtado/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/miguelfurtado/.npm/_logs/2022-12-05T11_04_46_223Z-debug-0.log
```

This started happening when I updated expo sdk version which in turn updated react-native-safe-area-acontext library.
This is the issue I opened with [expo](https://github.com/expo/expo/issues/20256).

### Steps To Reproduce

```Markdown
Install react-native-elements, then install react-native-safe-area-context.
```

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
        React Native Elements Env Info

## Global Dependencies:

   No related dependency found

## Local Dependencies:

 - expo : ^47.0.0
 - react : 18.1.0
 - react-native : 0.70.5
 - react-native-elements : ^3.4.2
 - @types/react : ~18.0.24
 - @types/react-native : ~0.70.6
      ```

</details>

**Comment by arpitBhalla** [comment]
Try `npm install react-native-elements --legacy-peer-deps`

**Comment by relense** [comment]
Hi @arpitBhalla, thanks for your input. I did and that works, but doesn't actually solve the issue it just bipasses. The dependecy issue is still there which is problematic to use with expo and to build for a deploy.

**Comment by zachrussell12** [comment]
Running into this issue as well. Elements still operate normally in Expo, however upon trying to build for submittal to the App Store, the build fails due to the dependency conflict.

**Comment by Defrosted** [comment]
> Try `npm install react-native-elements --legacy-peer-deps`

Yeah, this is not exactly a solution, just a temporary work-around. I don't want to perform the `npm install` with `--legacy-peer-deps` each time, as that opens the door for a lot of other issues. Would appreciate an update to this as soon as possible 👍

**Comment by arpitBhalla** [comment]
Try installing react-native-elements@3.4.3

**Comment by arpitBhalla** [comment]
Feel free to re-open/comment if anyone is still facing any issue.

**Comment by zachrussell12** [comment]
This issue still needs to be fixed in a future release so that old releases do not need to be used instead.

**Comment by Elena363** [comment]
Just for information to anyone struggling the bug. The issue is gone in the latest unstable release.
For now it is 

> `  "@rneui/base": "^0.0.0-edge.2",
>     "@rneui/themed": "^0.0.0-edge.2",`
