### ISSUE TITLE
example app does not work properly.

### ISSUE THREAD

**Issue by AsteriskZuo** [react-native-elements/react-native-elements#3709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

this repo commit id: dc2e5d187e8c1b418f96332407ae4fd2a8da729c
I want run example app.
1. `git clone git@github.com:react-native-elements/react-native-elements.git` to local.
2. `yarn` in project root directory.
3. `yarn run start`

branch is next.

tip:
```
Android Bundling failed 856ms
error: Error: resolveDependencies: Found duplicate dependency key 'undefined' in /Users/asterisk/Codes/rn/react-native-elements/example/index.js
    at resolveDependencies (/Users/asterisk/Codes/rn/react-native-elements/example/node_modules/metro/src/DeltaBundler/graphOperations.js:484:13)
    at processModule (/Users/asterisk/Codes/rn/react-native-elements/example/node_modules/metro/src/DeltaBundler/graphOperations.js:232:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async traverseDependenciesForSingleFile (/Users/asterisk/Codes/rn/react-native-elements/example/node_modules/metro/src/DeltaBundler/graphOperations.js:221:3)
    at async Promise.all (index 0)
```

### Expected behavior

example  app run in normal.

### Describe the bug

example app can not run in any device or simulator.

### Steps To Reproduce

```Markdown
1. `git clone git@github.com:react-native-elements/react-native-elements.git` to local.
2. `yarn` in project root directory.
3. `yarn run start`
```

### Screenshots

![Uploading 图片.png…]()

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
        Output from `npx @rneui/envinfo` goes here.
      ```

</details>

**Comment by AsteriskZuo** [comment]
<img width="1227" alt="图片" src="https://user-images.githubusercontent.com/11733363/207362103-2da2dd0b-7d67-440c-b9db-01151d721579.png">

**Comment by AsteriskZuo** [comment]
git commit id: 1885bd08785d566de1e5c3f82a230b4648daf256
v4.0.0-rc.7
example app runs properly.

**Comment by arpitBhalla** [comment]
I believe it's an issue with metro@>=0.72.0, need to look into it.

refer https://github.com/facebook/metro/issues/857

**Comment by arpitBhalla** [comment]
Hey, I have made some changes, could you try again, feel free to re-open/comment if anyone is still facing any issue.
