### ISSUE TITLE
 Missing dependency

### ISSUE THREAD

**Issue by b-r-s** [react-native-elements/react-native-elements#3710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

installed this repo

### Expected behavior

expected the app to run after installing from package.json

### Describe the bug

	"message": "File '@tsconfig/docusaurus/tsconfig.json' not found.",

### Steps To Reproduce

```Markdown
download/clone the repo - vs code will show this error under 'Problems'
```

### Screenshots

![image](https://user-images.githubusercontent.com/30550213/208531093-048f74d5-03ef-4c74-812f-5503b1c59b8f.png)

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
        Output from `npx @rneui/envinfo` goes here.
      ```

</details>

**Comment by arpitBhalla** [comment]
Hey, you need to install dependencies for website separately (if you are willing to make changes in `website`), here are the steps:-

```bash
git clone git@github.com:react-native-elements/react-native-elements.git
cd react-native-elements/website
yarn
```

**Comment by khushal87** [comment]
Hope the above solves your issue. Closing the issue till then. Please feel free to open it if its still relevant. Thanks 😄
