### ISSUE TITLE
Expo Go doesn't supports SDK 44.0.0

### ISSUE THREAD

**Issue by bulkinav** [react-native-elements/react-native-elements#3712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

The latest Expo Go app doesn't support SDK 44.0.0 and cannot run the demo from https://expo.dev/@rneui/react-native-elements

### Expected behavior

The latest Expo Go app can run the demo without any problems.

### Describe the bug

The latest Expo Go app display:

> This project uses SDK 44.0.0, but this version of Expo Go only supports the following SDKs: 47.0.0, 46.0.0, 45.0.0. To load the project, it must be updated to a supported SDK version or an older version of Expo Go must be used.

### Steps To Reproduce

```Markdown
1. Open https://expo.dev/@rneui/react-native-elements
2. Scan the QR code
```

### Screenshots

![Screenshot 2022-12-20 at 20 18 21](https://user-images.githubusercontent.com/1636367/208727356-99a46446-5a88-4c81-afc4-c2f67729b489.jpg)
![Screenshot 2022-12-20 at 20 18 35](https://user-images.githubusercontent.com/1636367/208727366-1b8d899d-9189-4364-b952-1e58bdcc7220.jpg)

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
        Output from `npx @rneui/envinfo` goes here.
      ```

</details>

**Comment by arpitBhalla** [comment]
Try now, using [this](https://expo.dev/%40rneui/react-native-elements?serviceType=classic&distribution=expo-go&releaseChannel=default) 

Or Scan this QR Code ![expo rneui](https://qr.expo.dev/expo-go?owner=rneui&slug=react-native-elements&releaseChannel=default&host=exp.host)

**Comment by bulkinav** [comment]
@arpitBhalla it works. Thanks.
