### ISSUE TITLE
Example app EXNetwork error 403 on iOS

### ISSUE THREAD

**Issue by BenMorel** [react-native-elements/react-native-elements#3724]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Issue

On the website: https://reactnativeelements.com/

The Expo QR code & the Expo link are broken: https://expo.dev/@rneui/react-native-elements

**Comment by arpitBhalla** [comment]
Did you try scanning it using [Expo Go](https://expo.dev/client)?

**Comment by BenMorel** [comment]
@arpitBhalla I did:

![Expo error](https://user-images.githubusercontent.com/1952838/210119726-07a4e91b-e74c-4ee9-9c80-749b69a22565.jpeg)

**Comment by arpitBhalla** [comment]
I think it's on iOS only, you need to login as team member on expo, I send you an invite to view the app.

**Comment by BenMorel** [comment]
It works now, thanks! How come it cannot be accessed publicly?

**Comment by arpitBhalla** [comment]
[This might help](https://stackoverflow.com/questions/66857797/exnetwork-error-403-when-publishing-app-to-ios-with-expo)
