### ISSUE TITLE
Add ability to remove `StatusBar` from `Header`

### ISSUE THREAD

**Issue by vruffer** [react-native-elements/react-native-elements#3755]
**Is your feature request related to a problem? Please Describe.**

Rendering a `StatusBar` component as a part of the `Header` component causes a lot of side-effects. Such as not being able to implement custom `StatusBar` components, like the one described [in this react-navigation guide](https://reactnavigation.org/docs/status-bar/).

**Describe the solution you'd like**

I think it would make sense to optionally render the `StatusBar` based on a prop. Such as:

```jsx
 <Header
  statusBar={false}
/>
```

which would then make the `Header` component look something like

```jsx
<>
  {props.statusBar === true && (
    <StatusBar
      barStyle={barStyle}
      translucent={true}
      backgroundColor={backgroundColor || theme?.colors?.primary}
      {...statusBarProps}
    />
  )}
</>
```

**Describe alternatives you've considered**

Since the last `StatusBar` in the render tree always takes preference, it is quite impossible to do custom logic on the `StatusBar` somewhere higher in the render tree, so I don't see another option, but please let me know if there's something I'm missing.

**Additional context**

If there are any issues with the approach that I've missed, please let me know, otherwise I'm happy to open a pull request with the above implementation 😄

**Comment by ramizqazi** [comment]
I want to contribute this feature
