### ISSUE TITLE
children prop error on Card component

### ISSUE THREAD

**Issue by lucksp** [react-native-elements/react-native-elements#3795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

Issue #3574  was marked closed, however, I see this issue still:

I have tried RNE bleeding edge & stable v4-rc.7 with the same outcome.
I am using TS version 4.9.5 in my project, but if I switch to the VSCode version 5, same issue. 

The use of children inside Card component results in TS error.

### Expected behavior

children are acceptable.

### Describe the bug

Just like the documents show, I am adding `children` to the `Card` component.  However, there is a TypeScript error:

> Type '{ children: (false | "" | 0 | Element | null | undefined)[]; containerStyle: { shadowColor: string; shadowOffset: { width: number; height: number; }; backgroundColor: string; elevation: number; shadowOpacity: number; shadowRadius: number; borderWidth: number; borderRadius: number; }; }' is not assignable to type 'IntrinsicAttributes & CardProps & Partial<ThemeProps<CardProps>>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & CardProps & Partial<ThemeProps<CardProps>>'.ts(2322)

It appears that the `Card.d.ts` file being imported from the RNE library is declared with:
`declare const ThemedCard: (React.FunctionComponent<Omit<CardProps & Partial<import("../config").ThemeProps<CardProps>>, keyof import("../config").ThemeProps<T>>> | React.ForwardRefExoticComponent<CardProps & Partial<import("../config").ThemeProps<CardProps>>>) & {
`
The `React.FunctionComponent` is then linked to @types/react, `ts5.0` instead of a ts4.0 version?

### Steps To Reproduce

```Markdown
Here is my code block:


import React, { ReactNode } from 'react';
import { View } from 'react-native';
import type { CardProps } from 'react-native-elements';
import { Card as RNECard } from 'react-native-elements';

import { useStyles } from './style';

interface Props extends CardProps {
  title?: ReactNode;
  subtitle?: ReactNode;
  divider?: boolean;
  children: ReactNode;
}

const Card = ({
  children,
  title,
  subtitle,
  divider = false,
  wrapperStyle,
  ...rest
}: Props) => {
  const styles = useStyles();

  return (
    <RNECard {...rest} containerStyle={styles.container}>
      {title && <RNECard.Title>{title}</RNECard.Title>}
      {subtitle && (
        <RNECard.FeaturedSubtitle>{subtitle}</RNECard.FeaturedSubtitle>
      )}
      {divider && <RNECard.Divider />}
      <View style={wrapperStyle}>{children}</View>
    </RNECard>
  );
};

export { Card };
```

### Screenshots

<img width="692" alt="image" src="https://github.com/react-native-elements/react-native-elements/assets/15162169/5793362f-77d6-4181-b3f1-495d1db86dbd">

### Your Environment

<summary>`npx @rneui/envinfo`</summary>

```
React Native Elements Env Info

## Global Dependencies:

 - expo-cli : 6.3.7

## Local Dependencies:

 - @rneui/base : ^4.0.0-rc.7
 - @rneui/themed : ^4.0.0-rc.7
 - expo : ~48.0.15
 - react : 18.2.0
 - react-native : 0.71.7
 - react-native-elements : ^3.4.3      
 
```

**Comment by RezaRahemtola** [comment]
Hey, any news about this issue ?

**Comment by khushal87** [comment]
Hey @lucksp can you try using Card from `@rneui/base`?

**Comment by lucksp** [comment]
This may be resolved now, on both `themed` & `base`.
