### ISSUE TITLE
Skeleton height/width prop incorrect typing

### ISSUE THREAD

**Issue by Blargel** [react-native-elements/react-native-elements#3799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I'm developing with TypeScript and I'm trying to make the Skeleton component fill up a containing View by setting its height and width to 100%.

### Expected behavior

I expected that setting the `height` and `width` props to the string `"100%"` would be accepted by TypeScript.

### Describe the bug

The `height` and `width` props are typed as numbers so TypeScript complains. When running the code anyway, the height and width is still properly set despite this. As a workaround to the typing issues, you can set the height and width using the `style` prop instead. Interesting, the `style` prop is not listed in [the documentation](https://reactnativeelements.com/docs/components/skeleton#props) but the `skeletonStyle` prop is. However, the `skeletonStyle` prop does not work for this workaround.

### Steps To Reproduce

While using TypeScript, try using the Skeleton component like this: 
```Markdown
<Skeleton width="100%" height="100%" />
```

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>
Sorry, the command is taking a ridiculously long time for some reason. If this is really needed for some reason, I'll edit it in later.
</details>

**Comment by deepak-rawat78** [comment]
Hi, Can I work on this issue?

As I can understand, we just need top update prop types for height and width. Also, adding styles as prop for Skeleton component.
