### ISSUE TITLE
Disappearance of 'Usage on the Web' Page from Documentation

### ISSUE THREAD

**Issue by 7nohe** [react-native-elements/react-native-elements#3818]
**Is your feature request related to a problem? Please Describe.**

I've recently noticed that the "Usage on the Web" page has disappeared from the latest version of the React Native Elements documentation. This has left me unsure whether React Native Elements is discontinuing support for the Web or whether the documentation has yet to be updated.

**Describe the solution you'd like**

If React Native Elements is still supporting the Web, could the "Usage on the Web" page be reintroduced? If updates to the documentation are still in progress, an estimated timeline would be helpful.

**Comment by Seanmclem** [comment]
I also noticed that documentation was bare react native specific, and not expo-web specific, which is how RN web is primarily used

**Comment by arpitBhalla** [comment]
You can find [usage on web](https://reactnativeelements.com/docs/installation#using-on-web).  Also I don't think there is any extra step needed for expo-web

**Comment by 7nohe** [comment]
@arpitBhalla Thank you for your quick response. I was just worried that support for the Web might be discontinued. I appreciate your help and will close this issue now.
