### ISSUE TITLE
Both Icon and image show up in the picture

### ISSUE THREAD

**Issue by WarriorofZarona** [react-native-elements/react-native-elements#3824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

Adding the Avatar component

### Expected behavior

The Avatar should show an icon if there is no image. When an image is added as a uri through the source prop, the icon should go away.

### Describe the bug

I was testing the Avatar component in my react native app and I coded something like this:

```
           <Avatar
              source={{ uri: imageUri }}
              size="large"
              rounded
              icon={{ name: 'user', type: 'font-awesome', color: colors.gray40 }}
              containerStyle={{ backgroundColor: colors.gray10 }}
            />
```

However, the icon does not go away, and so what I see is both the avatar and the image squishing into the avatar container itself

Note, this was working a couple of days ago, but I had to do a fresh install of all my dependencies and suddenly I'm seeing this. When I remove the icon prop, the image shows properly, but according to the docs, the icon should only serve as a placeholder when using the source prop. 

### Steps To Reproduce

```Markdown
1. import { Avatar } from '@rneui/themed'

2. Add Avatar component with both an icon prop and a source prop

3. Ensure the source prop has a uri to the image file
```

### Screenshots

![image](https://github.com/react-native-elements/react-native-elements/assets/56315576/a4e0a5d0-d7e8-4733-95f9-b38dbb5b09f4)

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
        Output from `npx @rneui/envinfo` goes here.
      ```

</details>

**Comment by l2aelba** [comment]
Same issue for me also
<img width="90" alt="Screenshot 2023-08-21 at 14 54 36" src="https://github.com/react-native-elements/react-native-elements/assets/983458/1630bfa0-3bce-4a10-81b4-2a896dca4c01">

**Comment by haeniya** [comment]
Same issue for me in the latest version 4.0.0-rc.8.

In 4.0.0-rc.7:
![image](https://github.com/react-native-elements/react-native-elements/assets/12571550/b7607d29-a7ef-4b6b-a06e-d8cb6b34d8d2)

In In 4.0.0-rc.8:
![avatar](https://github.com/react-native-elements/react-native-elements/assets/12571550/9f6ab948-d7d0-475d-b1de-b541589b83ef)

**Comment by msgerbush** [comment]
Just ran into this, if you need a temporary workaround this will reproduce the previous behavior:

```jsx
  const width = typeof size === 'number' ? size : avatarSizes[size] || avatarSizes.small;

  return (
    <Avatar
      imageProps={{
        PlaceholderContent: (
          <Text
            style={{
              fontSize: width / 2,
              color: '#ffffff',
              backgroundColor: 'transparent',
              textAlign: 'center',
            }}>
            {title}
          </Text>
        ),
      }}
    />
```

You'll want to remove the `title` attribute and put the `title` placeholder text you were using previously into the `Text` component.

**Comment by haeniya** [comment]
In my case, I need the title to be shown in two different situations:
1. As placeholder content when the image can not be loaded
2. As a fallback, if there is no image source passed (e.g. when the image source is undefined)

So I needed to adapt the workaround of @msgerbush a bit:
```js
<Avatar
  size={60}
  imageProps={{
    PlaceholderContent: (
      <Text
        style={{
          fontSize: 30,
          color: '#ffffff',
          backgroundColor: 'transparent',
          textAlign: 'center'
        }}
      >
        {title}
      </Text>
    )
  }}
  {...(imageSource ? { source: { uri: imageSource } } : { title })}
/>
```
This dynamically adds the source or title attribute depending on whether there's an `imageSource` but still has the placeholder content in case the image can not be loaded.

**Comment by RamanSB** [comment]
Seems like a shoddy work around though, is this not _properly_ fixed? Issue arises with 
"@rneui/base": "^4.0.0-rc.7",

Seems like the PR in the issue did not resolve the issue, please re-open @arpitBhalla.

I am using three props of interest, `renderPlaceholderContent`, `source` and `title`. Placeholder contnet whilst image is loading, if image doesn't exist use Title. What is the workaround for this.

**Comment by frankA10019** [comment]
@RamanSB Did you find the workaround?
