### ISSUE TITLE
Unable to resolve module with Expo 49

### ISSUE THREAD

**Issue by raRaRa** [react-native-elements/react-native-elements#3827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I upgraded to Expo 49 and the bundler complains about not resolving lodash/times which comes from `react-native-ratings` which is a dependency on react-native-elements.

### Expected behavior

Expected it to work.

### Describe the bug

The bundler complains about not resolving lodash/times which comes from `react-native-ratings` which is a dependency on react-native-elements.

```
iOS Bundling failed 2046ms
Unable to resolve "lodash/times" from "node_modules/@rneui/base/node_modules/react-native-ratings/dist/SwipeRating.js"
```

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>
## Global Dependencies:

 - expo-cli : 6.3.10

## Local Dependencies:

 - @rneui/base : ^4.0.0-rc.7
 - @rneui/themed : ^4.0.0-rc.8
 - expo : ^49.0.7
 - react : 18.2.0
 - react-native : 0.72.3
 - @types/react : ~18.2.14

</details>

**Comment by andresespinosapc** [comment]
How did you solve it? I also have this problem but in my case is a monorepo and the package not found is in a node_modules on another folder

**Comment by ajouve** [comment]
Same issue, any update ?
