### ISSUE TITLE
dependencies are not updated

### ISSUE THREAD

**Issue by Ramaloci** [react-native-elements/react-native-elements#3829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

i wanted to update both the themed and base packages to 4.0.0-rc.8 and got an error. 

on this line the dependencies were not updated:
https://github.com/react-native-elements/react-native-elements/blob/next/packages/themed/package.json#L53-L56

### Expected behavior

updating should work

### Describe the bug

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @rneui/themed@4.0.0-rc.8
npm ERR! Found: @rneui/base@4.0.0-rc.8
npm ERR! node_modules/@rneui/base
npm ERR!   @rneui/base@"4.0.0-rc.8" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @rneui/base@"4.0.0-rc.7" from @rneui/themed@4.0.0-rc.8
npm ERR! node_modules/@rneui/themed
npm ERR!   @rneui/themed@"4.0.0-rc.8" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @rneui/base@4.0.0-rc.7
npm ERR! node_modules/@rneui/base
npm ERR!   peer @rneui/base@"4.0.0-rc.7" from @rneui/themed@4.0.0-rc.8
npm ERR!   node_modules/@rneui/themed
npm ERR!     @rneui/themed@"4.0.0-rc.8" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

### Steps To Reproduce

```Markdown
trying to use base and themed together doesn't work on the latest versions
```

**Comment by Bilal-Abdeen** [comment]
I managed to get both versions updated using 2 methods. However, I am not sure if something else is going to break down the track!?

method-1: install themed first; then, install base:
`npm uninstall @rneui/themed @rneui/base`
`npm install @rneui/themed`
`npm install @rneui/base`

method-2: using --force:
`npm uninstall @rneui/themed @rneui/base`
`npm install @rneui/themed @rneui/base --force`

**Comment by Ramaloci** [comment]
i also managed to get a workaround running with using [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) in package.json:

`"overrides": {
    "@rneui/themed": {
      "@rneui/base": "4.0.0-rc.8"
    }
  }`

**Comment by l2aelba** [comment]
@Ramaloci @Bilal-Abdeen Still does not work for me.
I need to fix the avatar bug by this issue: https://github.com/react-native-elements/react-native-elements/pull/3831

Any trick? how to install or update into this?

**Comment by mbyrne00** [comment]
@arpitBhalla - the bug is with this line https://github.com/react-native-elements/react-native-elements/blob/72a4ac51ac60e305c1ef8fab4f81fdc7f0b7c9dd/packages/themed/package.json#L53

Why is `@rneu/themed` still requiring a peer dependency of `base` at `rc.7`? Is this a mistake? Surely they should be released in sync with each other?

The workarounds above are trying to get around the bug. Any chance you can do a new release with both packages having the same `rc` number, because we are fighting the dependencies you stipulate and can only make assumptions that it's a mistake.

**Comment by shobhitzcog** [comment]
is this still not resolved?

**Comment by scientistPargain** [comment]
Yeah I also want to know, facing same issue

**Comment by softov** [comment]
This lib is not maintained any more? Any alternative?

**Comment by patamarcelo** [comment]
same problem here

updated:
this solved my problem:
  "overrides": { "@rneui/themed": { "@rneui/base": "4.0.0-rc.8" } }

**Comment by deepktp** [comment]
@softov, @patamarcelo

I am working on a fork of this library under name [React Native Vikalp Elements](https://github.com/deepktp/react-native-vikalp-elements) and published on NPM, i have tried to fix multiple issues from here.

if you wish to use the library use the [migration guide](https://react-native-velements.thevikalp.com/blog/2025/05/15/migrate-to-rn-vui) or want to [open issues or contribute](https://github.com/deepktp/react-native-vikalp-elements).

If you need some help [Open a discussions](https://github.com/deepktp/react-native-vikalp-elements/discussions).
