### ISSUE TITLE
SociaIcon: Apple icon is missing

### ISSUE THREAD

**Issue by borgogelli** [react-native-elements/react-native-elements#3834]
The Apple guidelines require that apps that use a social login service (such as Facebook Login, Google Sign-In) must also offer Sign in with Apple as an equivalent option. So the Apple icon for the SocialIcon component is an indispensable feature.

**Comment by jayesh-685** [comment]
interested

**Comment by hrjaffery** [comment]
For some reason, I am still not getting the apple icon on version "4.0.0-rc.8"

**Comment by HamzaReza** [comment]
For some reason, I am still not getting the Apple icon on version "4.0.0-rc.8"
