### ISSUE TITLE
SearchBar - iOS icon error

### ISSUE THREAD

**Issue by Mazztwo** [react-native-elements/react-native-elements#3837]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- 
### Platform
- iOS
- rneui 4 rc8
- RN 72.4

### Explain what you did

Using the SearchBar on latest 4 rc8 shows a '?' as the search bar symbol on iOS instead of the magnifying glass. Showing this Error in console:

**Warning: Failed prop type: Invalid prop `name` of value `ios-search` supplied to `Icon`, expected one of ["accessibility",........]**

We are not passing any such prop and this is working in the react-native-vector-icon v9.2.0

### Expected behavior

We expect a magnifying glass as the search bar icon instead of the '?' with the warning.

### Screenshots
This is what it looks like:
![Screenshot 2023-09-11 at 3 32 06 PM](https://github.com/react-native-elements/react-native-elements/assets/10237098/db418ef2-efc8-424d-a796-4c05ef979cce)

Even the https://reactnativeelements.com/docs/components/searchbar playground is showing a bad search icon:

![Screenshot 2023-09-11 at 3 32 29 PM](https://github.com/react-native-elements/react-native-elements/assets/10237098/3ed3a211-4163-4ba5-956a-364844ffad42)

**Comment by Mazztwo** [comment]
Temporarily, I pass the SearchBar component the prop SearchIcon with the value being an Icon:

```
const searchIcon = () => {
        return (
            <Icon
                name={'magnify'}
                type={'material-community'}
            />
        );
    };

<SearchBar 
   ...
   searchIcon={searchIcon}
/>
```

**Comment by thomasamaddeo-genie** [comment]
Any update on this? 
having the same issue on iOS only.

Search and Clear icons not displaying

<img width="311" alt="image" src="https://github.com/react-native-elements/react-native-elements/assets/112924079/7a7b2ac2-6120-46f5-8018-f1c99f7d680e">

"@rneui/base": "^4.0.0-rc.8"
"@rneui/themed": "^4.0.0-rc.8"
"react-native": "0.72.6"

Also temporarily addressed it manually specifying both icons (which wasn't previously required).

**Comment by bitdriftr** [comment]
This happens to me when upgrading react-native-vector-icons from v9 to v10.

**Comment by soniaalabed** [comment]
I was able to fix this by adding the a searchIcon:
`<SearchBar 
searchIcon={Platform.OS === 'ios' ? {name: 'search'} : null}
clearIcon={Platform.OS === 'ios' ? {name: 'close-circle'} : null}
/>`
