### ISSUE TITLE
Typescript not recognising custom theme properties

### ISSUE THREAD

**Issue by mersiades** [react-native-elements/react-native-elements#3850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I have a new app Expo created via `npx create-expo-app --template` using the `expo-router` template.

I'm trying to extend the RN Elements `theme` by adding some custom properties as per the documentation [here](https://reactnativeelements.com/docs/customization/extending#adding-custom-other-properties).

### Expected behavior

Typescript should recognise custom properties added to a theme, and/or the documentation should show how to achieve that. "Recognise" means not showing a Typescript error and allowing type-based autocomplete.

### Describe the bug

The custom properties are successfully added: the code will compile and run okay.

But Typescript won't recognise the properties and I have to use `@ts-ignore` to allow the code run.

I'm not sure if this is a bug, the documentation is wrong or incomplete, or if I've somehow done something wrong.

Also, following the documentation for extending colours has a similar problem, where Typescript shows an error when passing them into `createTheme()`.

### Steps To Reproduce

Minimum reproducible example [here](https://github.com/mersiades/elements-mre)

### Screenshots

<img width="1050" alt="Screenshot 2023-10-17 at 5 44 44 pm" src="https://github.com/react-native-elements/react-native-elements/assets/6284016/3b6aab40-cf66-44d0-b7a0-5f0554ec49bf">

<img width="543" alt="Screenshot 2023-10-17 at 5 43 47 pm" src="https://github.com/react-native-elements/react-native-elements/assets/6284016/3e436c89-d455-4cf6-bc06-d89fda087514">

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
        React Native Elements Env Info

       ## Global Dependencies:

       No related dependency found

       ## Local Dependencies:

        - @rneui/base : ^4.0.0-rc.7
        - @rneui/themed : ^4.0.0-rc.8
         - expo : ~49.0.13
        - react : 18.2.0
        - react-native : 0.72.5
        - @types/react : ~18.2.14
      ```

</details>

**Comment by chirani** [comment]
Make sure you use this syntax here if you want to add custom properties.
This should be sufficient to fix your example

```TypeScript
declare module '@rneui/themed' {
  export interface CreateThemeOptions {
    foo: string;
}
}
```

**Comment by mersiades** [comment]
Thanks @chirani but that did not help, sadly.  And even if it did help, there would still be the problem of the documentation being different.

I've had more (but not complete) success on a different project using something like this:

```
type RecursivePartial<T> = { [P in keyof T]?: RecursivePartial<T[P]> };

declare module '@rneui/themed' {
  export interface Colors {
    tertiary: string;
    accent: string;
    surface: string;
  }

  export interface CreateThemeOptions extends RecursivePartial<Theme> {
    lightColors: Colors;
    darkColors: Colors;
  }
  
  export interface Theme {
    foo: string
  }
}
```
But that was only partially successful, seems like a workaround, and is different to the documentation.

**Comment by mersiades** [comment]
Okay, it turns out that this was a problem with my IDE, not react-native-elements. Closing this ticket.
