### ISSUE TITLE
import { styled } from '@rneui/themed' doesn't work

### ISSUE THREAD

**Issue by jamiechong** [react-native-elements/react-native-elements#3862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

The docs here: https://reactnativeelements.com/docs/customization/styles show me how to use `styled`, but this doesn't seem to be exported from the library: 

import { styled } from '@rneui/themed';

i'm using: 
    "@rneui/base": "^4.0.0-rc.7",
    "@rneui/themed": "^4.0.0-rc.8",

### Expected behavior

I expect the styled function to exist as it is specified in the docs. 

### Describe the bug

I can't import the lib. 

### Steps To Reproduce

```Markdown
npm install @rneui/themed @rneui/base
import { styled } from '@rneui/themed';
Fail
```

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
React Native Elements Env Info

## Global Dependencies:

   No related dependency found

## Local Dependencies:

 - @rneui/base : ^4.0.0-rc.7
 - @rneui/themed : ^4.0.0-rc.8
 - expo : ^49.0.18
 - react : 18.2.0
 - react-native : 0.72.6
 - @types/react : ~18.2.14
      ```

</details>

**Comment by JaweedVenturedive** [comment]
@jamiechong `styled` is no longer supported. You can import as following,

`import { makeStyles } from '@rneui/themed';`

**Comment by khushal87** [comment]
As per solution from @JaweedVenturedive, I will be closing this issue. Thanks 😄

**Comment by prof3ssorSt3v3** [comment]
styled is still in the documentation for v4, as if it is still supported...
