### ISSUE TITLE
NPM version missmatch for @rneui/themed's peerDeps/devDeps

### ISSUE THREAD

**Issue by bmatusiak** [react-native-elements/react-native-elements#3881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

i went to https://www.npmjs.com/package/@rneui/themed/v/4.0.0-rc.8?activeTab=code

and seen in package.json

```
"peerDependencies": {
    "@rneui/base": "4.0.0-rc.7"
  },
  "devDependencies": {
    "@rneui/base": "4.0.0-rc.7"
  },
```

### Expected behavior

expected to see 

```
"peerDependencies": {
    "@rneui/base": "4.0.0-rc.8"
  },
  "devDependencies": {
    "@rneui/base": "4.0.0-rc.8"
  },
```

### Describe the bug

NPM version missmatch

### Steps To Reproduce

```Markdown
npm install @rneui/themed @rneui/base
```

### Your Environment

npmjs.org public domain

**Comment by khushal87** [comment]
Hey @bmatusiak it was fixed here - https://github.com/react-native-elements/react-native-elements/pull/3871/files

**Comment by ChromeQ** [comment]
It's not really completed until it is released though...
Last tag was way back last July! What's the hold up to release v4 proper?
![image](https://github.com/user-attachments/assets/c572698d-9ed4-437f-8c53-9375d83367b9)
