### ISSUE TITLE
SearchBar has no Cancel button on iOS

### ISSUE THREAD

**Issue by lsarni** [react-native-elements/react-native-elements#3892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

I experienced it on my project, but the bug is visible on the example on the documentation:
```
import React, { useState } from 'react';
import { SearchBar } from '@rneui/themed';
import { View, Text, StyleSheet } from 'react-native';

type SearchBarComponentProps = {};

const SwitchComponent: React.FunctionComponent<SearchBarComponentProps> = () => {
const [search, setSearch] = useState("");

const updateSearch = (search) => {
  setSearch(search);
};

return (
  <View style={styles.view}>
    <SearchBar
      placeholder="Type Here..."
      onChangeText={updateSearch}
      value={search}
    />
  </View>
);
};
```

### Expected behavior

The "Cancel" button should appear on focus on iOS, and always if `showCancel` is set to true.

### Describe the bug

The "Cancel" button doesn't appear on focus, or when `showCancel` is set to true

### Steps To Reproduce

```Markdown
1. Go to https://snack.expo.dev/@lsarni/rne-searchbar
2. Start the app on iOS
3. Write on the search bar
4. See that no cancel button shows up
```

### Screenshots

![image](https://github.com/react-native-elements/react-native-elements/assets/15196342/45c0c740-6c34-4d43-bb0c-1985cc50f804)

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

## Global Dependencies:

   No related dependency found

## Local Dependencies:

 - @rneui/base : ^4.0.0-rc.7
 - @rneui/themed : ^4.0.0-rc.7
 - expo : ^50.0.0
 - react : 18.2.0
 - react-native : 0.73.2
 - @types/react : 18.2.0

</details>

**Comment by abdulbasithqb** [comment]
Wrap you IOS Component with SafeAreaView, it will work as expected

``` 
<SafeAreaView>
  <View style={styles.view}>
    <SearchBar
      placeholder="Type Here..."
      onChangeText={updateSearch}
      value={search}
    />
  </View>
  </SafeAreaView>
```

**Comment by khushal87** [comment]
<img width="1430" alt="Screenshot 2024-03-02 at 10 40 25 AM" src="https://github.com/react-native-elements/react-native-elements/assets/39884168/43e5dbb3-1b00-43e9-8650-39ea2f7a9ae1">
Hey @lsarni, this is working fine as expected, even on the snack that you shared.

**Comment by khushal87** [comment]
What is your version of `@expo/vector-icons`?

**Comment by lsarni** [comment]
@khushal87 I don't mean the cross/cancel icon, which is showing correctly, but the cancel button. Like it's shown on the [platform specific preview](https://reactnativeelements.com/docs/components/searchbar#platform-specific-searchbar) here:
![image](https://github.com/react-native-elements/react-native-elements/assets/15196342/fccbfa0b-3a6c-4ee5-b0f4-079968268380)

**Comment by lsarni** [comment]
I realized I needed to add `platform={Platform.OS === 'ios' ? 'ios' : 'android'}` to the `SearchBar` for it to work correctly
