### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by hemedani** [react-native-elements/react-native-elements#505]
any road map to support right to left language ?

**Comment by binoy14** [comment]
Not in the immediate future, feel free to submit a PR and we can help review it and merge it.

**Comment by hemedani** [comment]
thanks

**Comment by RamyarIran** [comment]
How can I set app to RTL ? I want to contribute but need help for the first step!

**Comment by Monte9** [comment]
Hi @RamyarIran! I'd be happy to help you submit your first PR. For starters, can you link to a react-native library that supports RTL languages? I haven't used any such library before.. and it would be a good start to see how other libraries handle this.

**Comment by hemedani** [comment]
Tanks, I'm very busy on several project and use this awesome lib on my project whenever I get some time post my PR

**Comment by j2l** [comment]
+1
I might help too. 
So far I found these libraries/projects:
[react-native-snap-carousel](https://github.com/archriss/react-native-snap-carousel)
[react-native-rtl](https://github.com/alizahid/react-native-rtl)

Also have a look at this [snack](https://snack.expo.io/Hkso38cg-)

**Comment by PavelPZ** [comment]
What about https://github.com/kentcdodds/rtl-css-js library? It just converts stylesObject to its RTL variant

**Comment by etabackman** [comment]
Also look at https://github.com/callstack/react-native-paper

**Comment by iRoachie** [comment]
Would love to get some work done on this. Could you all point out which components aren't rendering correctly in RTL? It's not my native language so I'm not exactly sure how some component should be displayed.

**Comment by iRoachie** [comment]
Is this how inputs/search should work?

![Screenshot_1564722805](https://user-images.githubusercontent.com/5962998/62346065-c4356700-b4c2-11e9-86ea-f542f1a9618d.png)

**Comment by flyingcircle** [comment]
Does anyone have a list of components that do not work with RTL? RN seems to handle most rtl automatically, so I'm not sure what remaining components are still needing work to work with this. I'll reopen this ticket if someone can provide this
