### ISSUE TITLE
Snack Demos - RNE components & use cases

### ISSUE THREAD

**Issue by Monte9** [react-native-elements/react-native-elements#681]
### Examples:
- **Card component:**  https://snack.expo.io/SJ3Sh73sb? https://snack.expo.io/ry1Ie490-
- **Card component with custom styling:** https://snack.expo.io/HkL1CABpb
- **Card, Avatar & Icon component:** https://snack.expo.io/BkxNCrJCW
- **Card with rounded image:** https://snack.expo.io/rJX-kHdIz
- **Cards inside a ScrollView:** https://snack.expo.io/Bkg0-DNwSz
- **Checkbox component:** https://snack.expo.io/BkCWHXqqZ
- **Disabled FormInput:** https://snack.expo.io/SJ3Sh73sb
- **Header component:** https://snack.expo.io/r1rkkaQnW
- **Header with clickable icon:** https://snack.expo.io/Bk3s0ackz
- **ListItem component with multiline title & subtitle:** https://snack.expo.io/rJs0FdEjb
- **ListItem component with various elements:** https://snack.expo.io/Skye7u10-
- **SocialIcon component with Facebook login:** https://snack.expo.io/ByQuAX_V-
- **Search Bar component with React Navigation (Full header):** https://snack.expo.io/H16d0uipb
- **Search Bar component with React Navigation (Title only):** https://snack.expo.io/S1QfebsCZ
- **Search Bar controlled with loading and clearIcon:** https://snack.expo.io/SkPhd7ZfM
- **Button component with vector icons:** https://snack.expo.io/Sk-yqN62-
- **Button component with custom image icon:** https://snack.expo.io/rk10cOexM
- **FormInput component controlled with validation:** https://snack.expo.io/HJxKSt77M

**Comment by iRoachie** [comment]
So we’re making snack demos for all the components?

**Comment by xavier-villelegier** [comment]
I think it's just about centralizing all snacks we do for `Help Wanted` issues

**Comment by iRoachie** [comment]
May actually be cool if we add in the docs too. Similarly to how react native’s website is with the embed snacks

**Comment by Monte9** [comment]
Yes, as @xavier-villelegier mentioned, the idea is to compile all the snack demos in one place for reference. So that 
1. Users can use it as a reference on how to use a specific component
2. We don't have to keep recreating the same snack demos and can share the link if it's similar.

@iRoachie that's a great idea. Yes, I am all for it. Any good docs on how we can get started with embedding snack on our website? It's important to note that we use [MKDocs](https://github.com/mkdocs/mkdocs) to generate our documentation from markdown, so that might make things a bit tricky.

**Comment by Monte9** [comment]
Let's revive this and make it more useful and user-facing for `beta4`.

/cc @iRoachie @xavier-villelegier

**Comment by iRoachie** [comment]
To minimize conflicts with https://github.com/react-native-training/react-native-elements/pull/1013, gonna push this to `beta5`

**Comment by jstansbe** [comment]
Proposed use case:
Badge + Icon = 
![image](https://user-images.githubusercontent.com/1250522/38707687-5b23cb26-3e80-11e8-991c-62494aa05af2.png)

**Comment by iRoachie** [comment]
Let's do this for just after v1 launches. So we'll be able to use that version number in snack

**Comment by narenderv7** [comment]
@Monte9  None of the links are working. Every link is showing following error,

```
Device: (78:20) Unable to resolve module 'module://react-native-elements.js'
  Evaluating module://react-native-elements.js
  Evaluating module://App.js
  Loading module://App.js
```

If you add `react-native-elements` in `package.json`, it showing a bunch of other modules errors which are used in `react-native-elements`


```
Device: (78:20) Unable to resolve module 'module://expo-font.js'
  Evaluating module://expo-font.js
  Evaluating module://react-native-elements.js
  Evaluating module://App.js
  Loading module://App.js

Device: (78:20) Unable to resolve module 'module://@unimodules/core.js'
  Evaluating module://@unimodules/core.js
  Evaluating module://expo-asset.js
  Evaluating module://expo-font.js
  Evaluating module://react-native-elements.js
  Evaluating module://App.js
  Loading module://App.js
```

**Comment by iRoachie** [comment]
@narenderv7 these are super old examples, and expo has deprecated the versions of expo-sdk in which these examples run on. The only person that'd be able to update them is the one who created so we may just have to redo them.

Also these are using react-native-elements@0.19.1 which is an older version. Are they any in particular you were looking at?

**Comment by narenderv7** [comment]
Oh Gotcha, @iRoachie Thanks for your quick response.

`Are they any, in particular, you were looking at?`  Nope, I just started getting dirty my hands on react-native, so searched for some examples on online and here am with those errors 😉

**Comment by itolimaesther** [comment]
Please how can solve this issue
Unable to resolve module 'module://components/Header.js'
  Evaluating module://components/Header.js
  Evaluating module://App.js.js
  Loading module://App.js

You can find it here
https://snack.expo.io/@esther66/5a5f75

**Comment by iRoachie** [comment]
@itolimaesther the example you posted isn't using react-native-elements
