### ISSUE TITLE
Clickable image on the cards

### ISSUE THREAD

**Issue by giveli** [react-native-elements/react-native-elements#814]
Hi, I was trying to add click action on the image of a card component. 

Here is my code :

```
<View style={styles.container}>
  <FlatList
      data={ this.state.interests }
      extraData={ this.state.showDetails }
      renderItem={
          ({item}) => {              
              return (
                  <Card
                      image={{ uri: item.picture }}
                      imageStyle= {styles.image}
                      backgroundColor='white'
                  >
                      {this.renderInterests(item)}
                  </Card> 
              );
          }
      }
      keyExtractor={(item, index) => index}
  />
 </View>
```

It seems from the documentation there isn't specific property on the card component. 
I definitely want to use the card's property image because I want to keep the header image style.

How I can do that ?  I need your help please !

**Comment by iRoachie** [comment]
You want to be able to click on the card?

**Comment by iRoachie** [comment]
Ah so @giveli we actually don't have this supported now although it sounds like a really great feature to have. Currently right now if you want to do this, you'll have to use an empty Card and handle the contents(image) as children yourself.

However if anyone wants to make this feature happen, they'll need to place a touchable around the image here  
https://github.com/react-native-training/react-native-elements/blob/c851d9ace8109db4e7b9b96b347ed4e53ed184a1/src/card/Card.js#L78-L105

**Comment by giveli** [comment]
Thank you so much for your help ! 
I locally add a touchable around the image on Card.js ! It works ! Thank  you ! 
I will add a pull request as soon as possible.

**Comment by iRoachie** [comment]
Great! I'll leave the issue open until it's implemented

**Comment by k3ithl1m** [comment]
I would like to help out with this

**Comment by ishigamii** [comment]
This feature has been added? will be added ? :D

**Comment by iRoachie** [comment]
Not as yet @ishigamii, Feel free to try implementing it and sending a PR!

**Comment by ishigamii** [comment]
@iRoachie I thought #814 was the PR for it my bad ;) I will maybe take a look at it though I don't know if I have the skills to create it but I can try :3

**Comment by iRoachie** [comment]
It was https://github.com/react-native-training/react-native-elements/pull/824, but the user never finished.

**Comment by lbelavoir** [comment]
@iRoachie is this still an issue ? I could take time to work on it.

**Comment by iRoachie** [comment]
Yea it’s still open.

**Comment by sudeepto-dutta** [comment]
@iRoachie I would like to work on this issue.  But I need some clarifications before I start with the implementation.

Based on [this](https://github.com/react-native-elements/react-native-elements/issues/814#issuecomment-357486244) comment of yours, shall I wrap the `<Image />` on [LINE 78](https://github.com/react-native-elements/react-native-elements/blob/next/src/card/Card.js#L78) with a `<TouchableOpacity />` component ? 

Shall this be done conditionally based on a new prop ? Like if the user want the `<Image />` to be touchable , then they can pass a prop , for e.g. `onImageClick`  ??

Let me know your thoughts so that I can get help solve this issue. 

Thanks

**Comment by flyingcircle** [comment]
@sudeepto-dutta There are other Components that change their outer Component based on whether they have an `onPress` prop set. For example you can look at `Avatar` where the `Component` prop is set by default on whether `onPress` or `onLongPress` is set. Having something similar for the `Image` Component I think would be the way to go on this. Then for Cards, users will be able to pass `onPress` in the `imageProps` without having to change `Card`.

**Comment by sudeepto-dutta** [comment]
@flyingcircle  Thanks for the input. Will try to follow the same pattern for `Avatar`  component as well.

**Comment by sudeepto-dutta** [comment]
@flyingcircle  I have created Pull Request [2506](https://github.com/react-native-elements/react-native-elements/pull/2506) following your comment.

Thank you for the help. Let me know if any change is required.
