### ISSUE TITLE
Vertical orientation for ButtonGroup

### ISSUE THREAD

**Issue by Donhv** [react-native-elements/react-native-elements#869]
As tittle. Pls help me.

**Comment by xavier-villelegier** [comment]
Just putting `containerStyle={{ flexDirection: 'column' }}` will give you a weird result, because the `ButtonGroup` doesn't support vertical orientation for now.

It could be a nice feature to have tho, I'll let that open if someone wants to take the lead on this.

**Comment by k3ithl1m** [comment]
I'm interested in taking a lead on this.

**Comment by iRoachie** [comment]
Go for it!

**Comment by k3ithl1m** [comment]
Would it look like this? Would it be like.
1. Adding a bool prop to determine whether it is vertical or not.
2. If it is, then flexDirection: 'column'.
3. Are there other more specific details that I should consider?
<img width="118" alt="screen shot 2018-02-16 at 5 04 35 am" src="https://user-images.githubusercontent.com/14284173/36302564-ecbc3dfa-12d6-11e8-9f31-127e50037476.png">

**Comment by iRoachie** [comment]
Will need @Donhv to confirm, but it seems like that's it

**Comment by iRoachie** [comment]
@k3ithl1m Did you get anywhere with implementing this?

**Comment by k3ithl1m** [comment]
I didn't because I thought we were waiting for confirmation. :X

**Comment by k3ithl1m** [comment]
Hey @iRoachie Should I just implement it?

**Comment by iRoachie** [comment]
Closing this until we have more information on the requirements

**Comment by iRoachie** [comment]
Example by @EskelCz https://github.com/react-native-training/react-native-elements/pull/1060#issuecomment-427677997

**Comment by antgel** [comment]
@iRoachie Any ideas what the status of this is? Various issues and PRs seem to have come and gone.

**Comment by iRoachie** [comment]
There's no one actively working on it. Feel free to submit a PR if you have an idea of how it should behave and look

**Comment by antgel** [comment]
@iRoachie Realistically, unfortunately I doubt I have the time to work on it. I see it's in the 1.1.0 milestone, which is cool. I see there is a PR https://github.com/react-native-training/react-native-elements/pull/1037, @k3ithl1m any news on this?

**Comment by k3ithl1m** [comment]
Hey @antgel, feel free to work on it as I've been pretty busy as well

**Comment by antgel** [comment]
I'm not sure I have the time and knowhow at the moment. Anyone willing to take it on a professional (funded) basis? Ping me offline if so. :)

**Comment by antgel** [comment]
@iRoachie Hi, I see you've modified the milestones. Does this mean that there are plans to work on this? Again, happy to fund it.

**Comment by iRoachie** [comment]
@antgel does the picture in https://github.com/react-native-training/react-native-elements/issues/869#issuecomment-366193571, describe what you imagine a vertical  button group would look like?

**Comment by antgel** [comment]
@iRoachie Yes, it does! :)

Some more colour... One feature that would be nice, is to be able to pad some space between the buttons whether horizontal or vertical. The use case is something like a questionnaire with several answers to choose from - each answer is a separate button in the group.

**Comment by haruelrovix** [comment]
Another use case for vertical button group will be your screen capture @iRoachie .

<img src="https://user-images.githubusercontent.com/5962998/41509798-511a12cc-7227-11e8-8612-cb573e73fcc0.gif" />

Reuse vertical button group in bottom sheet component? cc @antgel

**Comment by iRoachie** [comment]
I wouldn't use a vertical button group for this really. Button Group's primary function is as [SegmentedControl from iOS](https://developer.apple.com/design/human-interface-guidelines/ios/controls/segmented-controls/).

The above is actually easy done with 3 ListItem

**Comment by hammadzz** [comment]
Have we given up on this?

@iRoachie that would be creating a new custom stateful component when we can just add a layout change for ButtonGroup. And it seems we were almost done but missed a release in pull request #1037

**Comment by antgel** [comment]
> I wouldn't use a vertical button group for this really. Button Group's primary function is as [SegmentedControl from iOS](https://developer.apple.com/design/human-interface-guidelines/ios/controls/segmented-controls/).

Okay, but why exactly not? The "official" use sounds like tabs, but once it's styled, it can be like one of the above use cases. I defer to you as the expert, but it would be great to get some background.

**Comment by flyingcircle** [comment]
@antgel can you review my PR and see if what I submitted fits what you're looking for?

**Comment by thanhluantl2304** [comment]
hi guys, i need button groups with scrollable. Can you add scrollview to ButtonGroup?

**Comment by antgel** [comment]
> hi guys, i need button groups with scrollable. Can you add scrollview to ButtonGroup?

This is nothing to do with this issue, please open a new one to keep the conversation focused.
