### ISSUE TITLE
Type prop for SocialIcon

### ISSUE THREAD

**Issue by Oize** [react-native-elements/react-native-elements#872]
Is it possible to set icon type for SocialIcon?
You are currently using FontAwesome, but there are other fonts in react-native-vector-icons.
I would like to use Zocial, so now i have to kinda recreate your SocialIcon from scratch.

**Comment by xavier-villelegier** [comment]
Hey @Oize, this is currently not possible, but this is an interesting feature to have though, I'll let this open as an enhancement.
We have other priorities for the `v1.0.0` betas for now (React Native Web support, theming…) but feel free to submit a PR 👍

**Comment by Oize** [comment]
Ok, i was just wondering if it is acceptable because of different network icon names in different fonts and stuff like this.

**Comment by xavier-villelegier** [comment]
Yea this can be a bit tricky to implement properly. Let's see if someone takes the lead on this, otherwise if it becomes inactive I'll close it.

**Comment by Oize** [comment]
After diving a little into this i ended up with an Icon component with my own network-color map.
I also tried parsing type with regexps like that:
`if (/stack-?overflow/.test(type)) return '#f27f33';`
Works well, but imo we're losing the simplicity.

**Comment by LouisJS** [comment]
I don't understand the point of using SocialIcon when you can implement the same thing with the Icon Component such as : 

`<Icon
  name='sc-telegram'
  type='evilicon'
  color='#517fa4'
/>`

Am i missing something ?

**Comment by LouisJS** [comment]
You can still do this by using the `Icon` Component
Such as `<Icon raised reverse name='instagram' type='font-awesome' color='#517fa4' />`

which supports `type (defaults to material, options are material-community, zocial, font-awesome, octicon, ionicon, foundation, evilicon, simple-line-icon, feather or entypo`

So @Oize, you can use this for now
@xavier-villelegier You could implement SocialIcon type the same way you did for `Icon`, isn't it ?

**Comment by Oize** [comment]
@LouisJS yes, i can, just wanted to use more specific component with such an expressive name if it exists.
But currently `SocialIcon` looks way too specific to be usable.
